apache/hudi

hoodie-cli/src/main/scala/com/uber/hoodie/cli/SparkHelpers.scala
hoodie-common/src/main/java/com/uber/hoodie/common/HoodieJsonPayload.java
hoodie-utilities/pom.xml
hoodie-utilities/src/assembly/src.xml
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/HiveIncrementalPuller.java
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/HoodieDeltaStreamer.java
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/HoodieSnapshotCopier.java
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/exception/HoodieIncrementalPullException.java
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/exception/HoodieIncrementalPullSQLException.java
hoodie-utilities/src/main/resources/IncrementalPull.sqltemplate
hoodie-utilities/src/test/java/com/uber/hoodie/utilities/TestHoodieSnapshotCopier.java
pom.xml

Adding hoodie-utilities module

---

hoodie-utilities/pom.xml

Fixing version in hoodie-utilities pom.xml

---

hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/HoodieInputFormat.java
hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/UseFileSplitsFromInputFormat.java
hoodie-hadoop-mr/src/test/java/com/uber/hoodie/hadoop/AnnotationTest.java

- Tested with corresponding Presto changes (pending PR)
Fixes #24

Annotate HoodieInputFormat with UseFileSplitsFromInputFormat

---

hoodie-hadoop-mr/pom.xml

The extra merge commits should not happen from now on. Was trying out a new workflow which did not turn out right. Those commits should not have any changes.
This fixes #23

Build hoodie-hadoop-mr as a fat jar - include hoodie common

---

hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieKey.java

Fixing a typo.
@prazanna @vinothchandar

Format param comment in HoodieKey

---

hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieTableMetadata.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java
hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/HoodieROTablePathFilter.java
hoodie-hadoop-mr/src/test/java/com/uber/hoodie/hadoop/TestHoodieROTablePathFilter.java

- Unit tested
- Tested with few queries on Spark 2.x at Uber

Implement HoodieROTablePathFilter for use with Spark 2.0

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/CompactionFilter.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/CompactionOperation.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/HoodieCompactionMetadata.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/HoodieCompactor.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/HoodieRealtimeTableCompactor.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieCopyOnWriteTable.java
hoodie-client/src/test/java/com/uber/hoodie/common/HoodieTestDataGenerator.java
hoodie-client/src/test/java/com/uber/hoodie/io/TestHoodieCompactor.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieAvroPayload.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieTableType.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTableConfig.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTableMetaClient.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTimeline.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/HoodieLogAppendConfig.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/HoodieLogFile.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/avro/CompositeAvroLogReader.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/timeline/HoodieActiveTimeline.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/timeline/HoodieInstant.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/view/AbstractTableFileSystemView.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/view/ReadOptimizedTableView.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/view/RealtimeTableView.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/AvroUtils.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/FSUtils.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/HoodieAvroUtils.java
hoodie-common/src/main/java/com/uber/hoodie/exception/HoodieException.java
hoodie-common/src/main/java/com/uber/hoodie/exception/SchemaCompatabilityException.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/table/log/avro/AvroLogAppenderTest.java

Introduce RealtimeTableView and Implement HoodieRealtimeTableCompactor

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieReadClient.java
hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/main/java/com/uber/hoodie/index/HoodieBloomIndex.java

Cleanup code based on Java8 Lambdas

---

hoodie-client/src/main/java/com/uber/hoodie/index/HBaseIndex.java
hoodie-client/src/main/java/com/uber/hoodie/index/InMemoryHashIndex.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieAppendHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieInsertHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieUpdateHandle.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClient.java
hoodie-client/src/test/java/com/uber/hoodie/common/HoodieTestDataGenerator.java
hoodie-client/src/test/java/com/uber/hoodie/common/TestRawTripPayload.java
hoodie-client/src/test/java/com/uber/hoodie/index/TestHoodieBloomIndex.java
hoodie-common/src/main/java/com/uber/hoodie/common/HoodieJsonPayload.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieAvroPayload.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieRecord.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieRecordPayload.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieWriteStat.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/AvroUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java
pom.xml

More information in the ticket below.
https://github.com/uber/hoodie/issues/75

Add delete support to Hoodie

---

hoodie-cli/src/main/java/com/uber/hoodie/cli/HoodiePrompt.java
hoodie-cli/src/main/java/com/uber/hoodie/cli/commands/CleansCommand.java
hoodie-cli/src/main/java/com/uber/hoodie/cli/commands/SavepointsCommand.java
hoodie-cli/src/main/java/com/uber/hoodie/cli/commands/SparkMain.java
hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieCompactionConfig.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/exception/HoodieSavepointException.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCleaner.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCommitArchiveLog.java
hoodie-client/src/main/java/com/uber/hoodie/metrics/HoodieMetrics.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieTable.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClient.java
hoodie-client/src/test/java/com/uber/hoodie/io/TestHoodieCleaner.java
hoodie-common/pom.xml
hoodie-common/src/main/avro/HoodieCleanMetadata.avsc
hoodie-common/src/main/avro/HoodieRollbackMetadata.avsc
hoodie-common/src/main/avro/HoodieSavePointMetadata.avsc
hoodie-common/src/main/java/com/uber/hoodie/common/HoodieCleanStat.java
hoodie-common/src/main/java/com/uber/hoodie/common/HoodieRollbackStat.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieCleaningPolicy.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTimeline.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/timeline/HoodieActiveTimeline.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/timeline/HoodieInstant.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/AvroUtils.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/FSUtils.java
pom.xml

- Introduce avro to save clean metadata with details about the last commit that was retained
- Save rollback metadata in the meta timeline
- Create savepoint metadata and add API to createSavepoint, deleteSavepoint and rollbackToSavepoint
- Savepointed commit should not be rolledback or cleaned or archived
- introduce cli commands to show, create and rollback to savepoints
- Write unit tests to test savepoints and rollbackToSavepoints

Implement Savepoints and required metadata timeline

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/timeline/HoodieActiveTimeline.java
hoodie-common/src/test/java/com/uber/hoodie/common/table/string/HoodieActiveTimelineTest.java
hoodie-common/src/test/java/com/uber/hoodie/common/table/view/ReadOptimizedTableViewTest.java

Metadata timeline marks an already complete instant as complete again

---

docs/quickstart.md

Updating quickstart document. It fixes [https://github.com/uber/hoodie/issues/111].

few fixes to quick start document

---

hoodie-client/src/test/java/HoodieClientExample.java

Small fix separated from the GCS PR.
@prazanna @vinothchandar

Pass table path as argument to HoodieClientExample

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java

Rollback inflight commits as well when rolling back to savepoint

---

hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCommitArchiveLog.java
hoodie-client/src/test/java/com/uber/hoodie/common/HoodieTestDataGenerator.java
hoodie-client/src/test/java/com/uber/hoodie/io/TestHoodieCommitArchiveLog.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java

Savepoint should not create a hole in the commit timeline

---

hoodie-client/pom.xml
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieAppendHandle.java
hoodie-client/src/test/java/com/uber/hoodie/TestMergeOnReadTable.java
hoodie-client/src/test/java/com/uber/hoodie/common/HoodieMergeOnReadTestUtils.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/ParquetUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java

Deletes, after this change, works for any insert written to log files (which is the expected behavior going forward).

Enabled deletes in merge_on_read

---

hoodie-client/src/test/resources/log4j-surefire.properties
hoodie-common/src/test/resources/log4j-surefire.properties

suppressing logs (under 4MB) for jenkins

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java

@vinothchandar Introduced a config for bulkInsertParallelism.

adding new config to separate shuffle and write parallelism

---

hoodie-client/src/test/java/com/uber/hoodie/TestMergeOnReadTable.java
hoodie-client/src/test/java/com/uber/hoodie/common/HoodieClientTestUtils.java
hoodie-utilities/src/test/java/com/uber/hoodie/utilities/TestHDFSParquetImporter.java

Fix build failing issues

---

hoodie-client/src/main/java/com/uber/hoodie/table/HoodieCopyOnWriteTable.java

Lets make a call on this soon..

Revert effects of PR #259

---

hoodie-cli/src/main/java/com/uber/hoodie/cli/commands/ArchivedCommitsCommand.java
hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieAppendHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCommitArchiveLog.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/HoodieRealtimeTableCompactor.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieCopyOnWriteTable.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieMergeOnReadTable.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieTable.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClientOnCopyOnWriteStorage.java
hoodie-client/src/test/java/com/uber/hoodie/io/TestHoodieCommitArchiveLog.java
hoodie-client/src/test/java/com/uber/hoodie/io/TestHoodieCompactor.java
hoodie-client/src/test/java/com/uber/hoodie/table/TestMergeOnReadTable.java
hoodie-common/src/main/java/com/uber/hoodie/common/HoodieRollbackStat.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/HoodieCompactedLogRecordScanner.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/HoodieLogFormat.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/HoodieLogFormatReader.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/block/HoodieAvroDataBlock.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/block/HoodieCommandBlock.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/block/HoodieCorruptBlock.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/block/HoodieDeleteBlock.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/block/HoodieLogBlock.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/timeline/HoodieActiveTimeline.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/table/log/HoodieLogFormatTest.java
hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeRecordReader.java
hoodie-hadoop-mr/src/test/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeRecordReaderTest.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/HoodieHiveClient.java
hoodie-hive/src/test/java/com/uber/hoodie/hive/TestUtil.java

@vinothchandar @jianxu Initial pull request to get some feedback. Two caveats 
1) Rollback does not work for deletes 
2) Need some abstraction over HoodieLogWriter instead of using it directly.

Separated rollback as a table operation & Implement rollback for MOR

---

hoodie-client/src/main/java/com/uber/hoodie/config/HoodieCompactionConfig.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/HoodieRealtimeTableCompactor.java
hoodie-client/src/test/java/HoodieClientExample.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTableConfig.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTableMetaClient.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/HoodieCompactedLogRecordScanner.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/ReflectionUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/table/log/HoodieLogFormatTest.java
hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeFileSplit.java
hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeInputFormat.java
hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeRecordReader.java
hoodie-hadoop-mr/src/test/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeRecordReaderTest.java
hoodie-hive/src/test/java/com/uber/hoodie/hive/TestUtil.java
hoodie-spark/src/main/java/com/uber/hoodie/DataSourceUtils.java
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/deltastreamer/HoodieDeltaStreamer.java

Tested with unit tests, trying to test with an ingestion job, initial feedback will be helpful.

Implementing custom payload/merge hooks abstractions for application specific merge logic

---

hoodie-client/src/main/java/com/uber/hoodie/io/compact/HoodieRealtimeTableCompactor.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/strategy/DayBasedCompactionStrategy.java
hoodie-client/src/test/java/com/uber/hoodie/io/TestHoodieCompactor.java
hoodie-client/src/test/java/com/uber/hoodie/io/strategy/TestHoodieCompactionStrategy.java

1. Adding a new compaction strategy
2. Added filter to remove compactionoperations without delta files.

Partition compaction strategy

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCreateHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieIOHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieMergeHandle.java
hoodie-client/src/main/java/com/uber/hoodie/metrics/HoodieMetrics.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieCopyOnWriteTable.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieMergeOnReadTable.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieTable.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClientOnCopyOnWriteStorage.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieWriteStat.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTableMetaClient.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/FSUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/TestHoodieWriteStat.java
hoodie-common/src/test/java/com/uber/hoodie/common/util/TestFSUtils.java

@vinothchandar @n3nash this attempts to fix https://github.com/uber/hoodie/issues/284 for insert use cases.  The PR has been tested in Uber's internal staging environment.

Add FinalizeWrite in HoodieCreateHandle for COW tables

---

hoodie-client/pom.xml
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieIndexConfig.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/index/hbase/HBaseIndex.java
hoodie-client/src/test/java/com/uber/hoodie/index/TestHbaseIndex.java

- Adding tests or HbaseIndex
- Enabling global index functionality

Adding global indexing to HbaseIndex implementation

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieReadClient.java
hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClientOnCopyOnWriteStorage.java

With this change, we'll have the following new APIs in HoodieWriteClient:
1. upsertPreppedRecords
2. insertPreppedRecords
3. bulkInsertPreppedRecords
HoodieReadClient would have new API tagLocation.
@vinothchandar @n3nash @fishie9

Add new APIs in HoodieReadClient and HoodieWriteClient

---

hoodie-cli/hoodie-cli.sh
hoodie-cli/src/main/java/com/uber/hoodie/cli/commands/HoodieLogFileCommand.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/block/HoodieAvroDataBlock.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/HoodieHiveClient.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/util/SchemaUtil.java

This tool can help do that following :
- Read total records per commit
- Read metadata per block per commit
- Read all records, either merged or un-merged

Adding a tool to read/inspect a HoodieLogFile

---

hoodie-client/src/main/java/com/uber/hoodie/io/HoodieMergeHandle.java

Adding back changes in HoodieMergeHandle from https://github.com/uber/hudi/pull/285

Add back UseTempFolder changes in HoodieMergeHandle

---

hoodie-cli/src/main/scala/com/uber/hoodie/cli/SparkHelpers.scala
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieStorageConfig.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/io/storage/HoodieParquetConfig.java
hoodie-client/src/main/java/com/uber/hoodie/io/storage/HoodieParquetWriter.java
hoodie-client/src/main/java/com/uber/hoodie/io/storage/HoodieStorageWriterFactory.java
hoodie-client/src/test/java/com/uber/hoodie/index/bloom/TestHoodieBloomIndex.java

PR to have a configurable compression ratio. Will continue to fix the actual problem here https://github.com/uber/hudi/pull/347 soon.

Adding config for parquet compression ratio

---

hoodie-common/pom.xml
hoodie-common/src/main/java/com/uber/hoodie/avro/MercifulJsonConverter.java
hoodie-common/src/main/java/com/uber/hoodie/common/HoodieJsonPayload.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieCommitMetadata.java
hoodie-common/src/test/java/com/uber/hoodie/common/util/TestRecord.java
hoodie-spark/pom.xml

org.codehaus.jackson is a deprecated version of jackson lib

Replace deprecated jackson version

---

hoodie-client/src/main/java/com/uber/hoodie/config/HoodieHBaseIndexConfig.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieIndexConfig.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/index/hbase/HBaseIndex.java
hoodie-client/src/test/java/com/uber/hoodie/index/TestHbaseIndex.java
hoodie-client/src/test/java/com/uber/hoodie/index/TestHoodieIndex.java

Throttling to limit QPS from HbaseIndex

---

hoodie-cli/src/main/java/com/uber/hoodie/cli/utils/SparkUtil.java

@n3nash , @vinothchandar : Another PR required for demo. 
In the demo, I am using spark master which is setup in the environment but Spark launcher is not picking it up and always using Yarn.  This PR will fix it.

Use spark Master from environment if set

---

docs/configurations.md
hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/io/ConsistencyCheck.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieCopyOnWriteTable.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieMergeOnReadTable.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieTable.java
hoodie-client/src/test/java/com/uber/hoodie/TestCleaner.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClientBase.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClientOnCopyOnWriteStorage.java
hoodie-client/src/test/java/com/uber/hoodie/index/TestHbaseIndex.java
hoodie-client/src/test/java/com/uber/hoodie/io/TestConsistencyCheck.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTableMetaClient.java
hoodie-spark/src/main/scala/com/uber/hoodie/DefaultSource.scala
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/deltastreamer/HoodieDeltaStreamer.java
hoodie-utilities/src/test/java/com/uber/hoodie/utilities/TestHoodieDeltaStreamer.java
pom.xml

- Check to ensure written files are listable on storage
- Docs reflected to capture how this helps with s3 storage
- Unit tests added, corrections to existing tests
- Fix DeltaStreamer to manage archived commits in a separate folder

Perform consistency checks during write finalize

---

pom.xml

Adding Jiale & Anbu to contributors list

---

hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/HoodieInputFormat.java
hoodie-integ-test/src/test/java/com/uber/hoodie/integ/ITTestHoodieSanity.java

Added integration-test which fails in master but passes with this PR.

Fix regression bug which broke HoodieInputFormat handling of non-hoodie datasets

---

hoodie-client/src/test/java/com/uber/hoodie/common/HoodieTestDataGenerator.java
hoodie-spark/src/main/java/com/uber/hoodie/DataSourceUtils.java
hoodie-spark/src/main/scala/com/uber/hoodie/DataSourceOptions.scala
hoodie-spark/src/main/scala/com/uber/hoodie/DefaultSource.scala
hoodie-spark/src/test/scala/DataSourceTest.scala

Add additional feature to drop later arriving dups

---

hoodie-client/src/main/java/com/uber/hoodie/index/bloom/HoodieBloomIndexCheckFunction.java
hoodie-client/src/test/java/com/uber/hoodie/io/strategy/TestHoodieCompactionStrategy.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieRecordLocation.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/util/SchemaUtil.java
hoodie-spark/src/test/scala/DataSourceDefaultsTest.scala

fix some spell errorin Hudi
for example:
parition =>partition

fix some spell errorin Hudi

---

hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCreateHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieIOHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieMergeHandle.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/view/HoodieTableFileSystemView.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/FSUtils.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/HiveSyncConfig.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/HoodieHiveClient.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/NonPartitionedExtractor.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/util/SchemaUtil.java
hoodie-integ-test/src/test/java/com/uber/hoodie/integ/ITTestHoodieSanity.java
hoodie-spark/src/main/java/com/uber/hoodie/NonpartitionedKeyGenerator.java
hoodie-spark/src/main/scala/com/uber/hoodie/HoodieSparkSqlWriter.scala
hoodie-spark/src/test/java/HoodieJavaApp.java

Addresses both issues reported in https://github.com/uber/hudi/issues/493

Ensure Hoodie works for non-partitioned Hive table

---

hoodie-common/src/main/java/com/uber/hoodie/common/util/FSUtils.java

Right now, the partitions listed can include the following : 
.hoodie/.aux/x.compaction.requested, .hoodie/.aux/y.compaction.requested, ...

Passing a path filter to avoid including folders under .hoodie directory as partition paths

---

hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/realtime/AbstractRealtimeRecordReader.java
hoodie-hadoop-mr/src/test/java/com/uber/hoodie/hadoop/InputFormatTestUtil.java
hoodie-hadoop-mr/src/test/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeRecordReaderTest.java

Issue : https://github.com/uber/hudi/issues/561
Added Fix and unit-test which fails without the change

Fix Hoodie Record Reader to work with non-partitioned dataset ( ISSUE-561)

---

docs/quickstart.md
hoodie-hive/pom.xml
packaging/hoodie-hive-bundle/pom.xml
packaging/hoodie-presto-bundle/pom.xml
pom.xml

Fix hive sync (libfb version mismatch) and deltastreamer issue (missing cmdline argument) in demo

Fix hive sync and deltastreamer issue in demo

---

KEYS

Adding KEYS file - seeded with my key - other PPMC members please add your respective keys

HUDI-75: Add KEYS

---

docs/configurations.md

Related with #604
https://issues.apache.org/jira/browse/HUDI-77

Add compression codec configurations documents for HoodieParquetWriter.

---

docs/_data/topnav.yml
docs/community.md
docs/concepts.md
docs/configurations.md
docs/css/customstyles.css
docs/docker_demo.md
docs/performance.md
docs/querying_data.md
docs/quickstart.md
docs/writing_data.md

- Reworked Concepts, Querying/Writing data pages
- Added a section on storage management
- Trimmed down quickstart and separated out demo page
- Made all configs linkable
- Added link to HIP process
- Point code to asf repo

Major cleanup of docs structure/content

---

hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCreateHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieMergeHandle.java
hoodie-spark/src/main/java/com/uber/hoodie/BaseAvroPayload.java

- This will reduce the shuffle volume for datasource and deltastreamer significantly

Fixed HUDI-87 : Remove schemastr from BaseAvroPayload

---

hoodie-client/src/main/java/com/uber/hoodie/config/HoodieHBaseIndexConfig.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/HoodieRealtimeTableCompactor.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/strategy/BoundedPartitionAwareCompactionStrategy.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/strategy/DayBasedCompactionStrategy.java
hoodie-client/src/main/java/com/uber/hoodie/io/compact/strategy/UnBoundedPartitionAwareCompactionStrategy.java
hoodie-client/src/test/java/com/uber/hoodie/io/strategy/TestHoodieCompactionStrategy.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieCommitMetadata.java

@vinothchandar @bvaradar These are the only pending changes needed to be upstreamed after the list status cache fix. After this, we only have that 1 outstanding issue : https://github.com/apache/incubator-hudi/issues/591

1. Minor changes to fix compaction 2. Adding 2 compaction policies 3. Adding a Hbase index property

---

hoodie-client/src/main/java/com/uber/hoodie/config/HoodieCompactionConfig.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCommitArchiveLog.java

Addresses : https://issues.apache.org/jira/browse/HUDI-94

Performing commit archiving in batches to avoid keeping a huge chunk in memory

---

packaging/hoodie-hadoop-mr-bundle/pom.xml

@vinothchandar @n3nash  @ovj : There is an additional failure which is happening for RT queries when running the demo steps even after we reverted kryo changes.
Looking for volunteers for implementing HUDI-100 (automating demo steps in integration test). If not, will work on it in the background.

Fix Hive RT query failure in hoodie demo

---

docs/docker_demo.md

The deltastreamer command-line args for subsequent invocations is missing schemaProvider argument.  Also, there was a layout issue around Step 7(a)

Fix DeltaStreamer args and layout in docker demo page

---

content/admin_guide.html
content/docker_demo.html
content/feed.xml
content/powered_by.html
docs/powered_by.md

Updating Apache Hudi Website with latest changes in docs

Updating Apache Hudi Website with latest changes in docs

---

hoodie-common/pom.xml
hoodie-common/src/main/java/com/uber/hoodie/common/table/log/block/HoodieDeleteBlock.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/SerializationUtils.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/collection/DiskBasedMap.java
hoodie-common/src/main/java/com/uber/hoodie/common/util/collection/LazyFileIterable.java
hoodie-common/src/test/java/com/uber/hoodie/common/util/TestSerializationUtils.java
hoodie-utilities/pom.xml
packaging/hoodie-hadoop-mr-bundle/pom.xml
packaging/hoodie-presto-bundle/pom.xml
packaging/hoodie-spark-bundle/pom.xml

migrating kryo's dependency from twitter chill to plain kryo library. @vinothchandar / @bvaradar - PTAL.

migrating kryo's dependency from twitter chill to plain kryo library

---

hoodie-utilities/pom.xml
packaging/hoodie-hadoop-mr-bundle/pom.xml
packaging/hoodie-hive-bundle/pom.xml
packaging/hoodie-presto-bundle/pom.xml
packaging/hoodie-spark-bundle/pom.xml

@bvaradar Updated individual pom files with the exclusion filter. Tested, there are no signature files and also Demo steps are working absolutely fine. Please review.

HUDI-101: added exclusion filters for signature files.

---

.gitignore
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieIndexConfig.java
hoodie-client/src/main/java/com/uber/hoodie/config/HoodieWriteConfig.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/BucketizedBloomCheckPartitioner.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/HoodieBloomIndex.java
hoodie-client/src/test/java/com/uber/hoodie/index/bloom/TestBucketizedBloomCheckPartitioner.java
hoodie-client/src/test/java/com/uber/hoodie/index/bloom/TestHoodieBloomIndex.java

- Tackles the skew seen in sort based partitioning/checking
- Parameterized the HoodieBloomIndex test
- Config to turn on/off (on by default)
- Unit tests & also tested at scale

Bucketized Bloom Filter checking

---

hoodie-utilities/src/main/java/com/uber/hoodie/utilities/deltastreamer/HoodieDeltaStreamer.java

@vinothchandar @n3nash : Can you give a quick stamp ?

Minor CLI documentation change in delta-streamer

---

hoodie-utilities/src/main/java/com/uber/hoodie/utilities/sources/helpers/KafkaOffsetGen.java

make sure offset is available before to consume dataset.  https://issues.apache.org/jira/browse/HUDI-105

HUDI-105 : Fix up offsets not available on leader exception

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieWriteClient.java

Jira: https://issues.apache.org/jira/browse/HUDI-139

HUDI-139 Compaction running twice due to duplicate "map" transformation while finalizing compaction

---

hoodie-client/pom.xml
hoodie-spark/pom.xml
pom.xml

remove duplicated dependencies, to  fix maven build warning

fix maven pom

---

hoodie-spark/src/main/java/com/uber/hoodie/DataSourceUtils.java
hoodie-utilities/src/main/java/com/uber/hoodie/utilities/HoodieCompactionAdminTool.java

Issue : https://github.com/apache/incubator-hudi/issues/704

Close Hoodie Clients which are opened to properly shutdown embedded timeline service

---

hoodie-client/src/main/java/com/uber/hoodie/HoodieReadClient.java
hoodie-client/src/main/java/com/uber/hoodie/func/CopyOnWriteLazyInsertIterable.java
hoodie-client/src/main/java/com/uber/hoodie/index/HoodieIndex.java
hoodie-client/src/main/java/com/uber/hoodie/index/InMemoryHashIndex.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/BloomIndexFileInfo.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/HoodieBloomIndex.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/HoodieBloomIndexCheckFunction.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/HoodieGlobalBloomIndex.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/IntervalTreeBasedGlobalIndexFileFilter.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/IntervalTreeBasedIndexFileFilter.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/ListBasedGlobalIndexFileFilter.java
hoodie-client/src/main/java/com/uber/hoodie/index/bloom/ListBasedIndexFileFilter.java
hoodie-client/src/main/java/com/uber/hoodie/index/hbase/HBaseIndex.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieAppendHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieCreateHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieKeyLookupHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieMergeHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieRangeInfoHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieReadHandle.java
hoodie-client/src/main/java/com/uber/hoodie/io/HoodieWriteHandle.java
hoodie-client/src/main/java/com/uber/hoodie/table/HoodieCopyOnWriteTable.java
hoodie-client/src/main/java/com/uber/hoodie/table/WorkloadStat.java
hoodie-client/src/test/java/com/uber/hoodie/TestHoodieClientBase.java
hoodie-client/src/test/java/com/uber/hoodie/index/TestHbaseIndex.java
hoodie-client/src/test/java/com/uber/hoodie/index/bloom/TestHoodieBloomIndex.java
hoodie-client/src/test/java/com/uber/hoodie/index/bloom/TestHoodieGlobalBloomIndex.java
hoodie-common/src/main/java/com/uber/hoodie/common/model/HoodieRecordLocation.java
hoodie-common/src/test/java/com/uber/hoodie/common/model/HoodieTestUtils.java
hoodie-common/src/test/java/com/uber/hoodie/common/util/collection/TestExternalSpillableMap.java

- Generalized BloomIndex to work with file ids instead of paths
- Abstracted away Bloom filter checking into HoodieLookupHandle
- Abstracted away range information retrieval into HoodieRangeInfoHandle

Introduce HoodieReadHandle abstraction into index

---

hoodie-client/src/main/java/com/uber/hoodie/table/HoodieMergeOnReadTable.java

@bvaradar @vinothchandar please review

Reading baseCommitTime from the latest file slice as opposed to the tagged record value

---

hoodie-hadoop-mr/pom.xml
hoodie-spark/pom.xml
hoodie-timeline-service/pom.xml

Add parquet-avro dependency in hoodie-spark and hoodie-timeline should not be fat-jar

Add parquet-avro dependency in hoodie-spark and hoodie-timeline should not be fat-jar

---

hoodie-hive/pom.xml
hoodie-hive/src/main/java/com/uber/hoodie/hive/HiveSyncTool.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/HoodieHiveClient.java
hoodie-hive/src/main/java/com/uber/hoodie/hive/util/SchemaUtil.java
hoodie-hive/src/test/java/com/uber/hoodie/hive/util/HiveTestService.java

Hoodie Hive to use log4j Logger instead of slf4j

---

hoodie-client/src/main/java/com/uber/hoodie/client/embedded/EmbeddedTimelineService.java
hoodie-common/src/main/java/com/uber/hoodie/common/SerializableConfiguration.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/HoodieTableMetaClient.java
hoodie-common/src/main/java/com/uber/hoodie/common/table/view/FileSystemViewManager.java
hoodie-timeline-service/src/main/java/com/uber/hoodie/timeline/service/TimelineService.java

Ensure TableMetaClient and FileSystem instances have exclusive copy of Configuration

Ensure TableMetaClient and FileSystem instances have exclusive copy of Configuration

---

hoodie-common/src/main/java/com/uber/hoodie/common/storage/StorageSchemes.java

Related Issue: https://github.com/apache/incubator-hudi/issues/741

Add maprfs to storage schemes

---

docs/docker_demo.md

Doc Update for https://github.com/apache/incubator-hudi/pull/760

Update Hoodie Demo Documentation

---

hoodie-common/pom.xml

https://github.com/apache/incubator-hudi/pull/739
This change was also tested against the hackathon-0619 branch.

Support building Hoodie with Hadoop 2.8.x

---

hoodie-common/src/main/java/com/uber/hoodie/common/table/log/HoodieLogFileReader.java

fs.open(logFile.getPath(), bufferSize).getWrappedStream()  may not be a FSInputStream.
When use s3 in aws emr, it's  a BufferedFSInputStream

fix HoodieLogFileReader

---

hoodie-client/src/main/java/com/uber/hoodie/table/HoodieMergeOnReadTable.java

@vinothchandar @n3nash : Grepped the code base and verified no other similar pattern exists

HUDI-168 Ensure getFileStatus calls for files getting written happens after close() is called

---

docs/writing_data.md

- provided guidance for upsert vs insert vs bulk_insert
- provided guidance for soft deletes vs hard deletes

Update writing_data for operations/deletes

---

README.md

JIRA issue like: https://issues.apache.org/jira/browse/HUDI-181

[HUDI-181] Fix the Bold markdown grammar issue of README file

---

content/404.html
content/admin_guide.html
content/community.html
content/comparison.html
content/concepts.html
content/configurations.html
content/contributing.html
content/docker_demo.html
content/feed.xml
content/gcs_hoodie.html
content/index.html
content/js/mydoc_scroll.html
content/migration_guide.html
content/news.html
content/news_archive.html
content/performance.html
content/powered_by.html
content/privacy.html
content/querying_data.html
content/quickstart.html
content/s3_hoodie.html
content/sitemap.xml
content/strata-talk.html
content/use_cases.html
content/writing_data.html
docs/writing_data.md

HUDI-186 Fix formatting for new content in Writing Data page. Update website to reflect new apache links

HUDI-186 Fix formatting for new content in Writing Data page. Update website to reflect new apache links

---

hoodie-cli/hoodie-cli.sh
hoodie-hive/run_sync_tool.sh
hoodie-spark/run_hoodie_app.sh

HUDI-197 Hive Sync and othe CLIs using bundle picking sources jar instead of binary jar

HUDI-197 Hive Sync and othe CLIs using bundle picking sources jar instead of binary jar

---

hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/realtime/HoodieRealtimeInputFormat.java

- Fix realtime queries by removing COLUMN_ID and COLUMN_NAME cache in inputformat
- These variables were cached to make Hive on Spark work

HUDI-198 : Fix for realtime queries

---

hoodie-hadoop-mr/src/main/java/com/uber/hoodie/hadoop/hive/HoodieCombineHiveInputFormat.java

@vinothchandar @bvaradar I'm opening this PR since we want to ensure we have all the existing classes present in OSS when we rename the packages.

HUDI-182 : Adding HoodieCombineHiveInputFormat for COW tables

---

NOTICE.txt
docker/hoodie/hadoop/NOTICE.txt
docker/hoodie/hadoop/base/NOTICE.txt
docker/hoodie/hadoop/datanode/NOTICE.txt
docker/hoodie/hadoop/historyserver/NOTICE.txt
docker/hoodie/hadoop/hive_base/NOTICE.txt
docker/hoodie/hadoop/namenode/NOTICE.txt
docker/hoodie/hadoop/spark_base/NOTICE.txt
docker/hoodie/hadoop/sparkadhoc/NOTICE.txt
docker/hoodie/hadoop/sparkmaster/NOTICE.txt
docker/hoodie/hadoop/sparkworker/NOTICE.txt
hoodie-cli/src/main/resources/META-INF/NOTICE.txt
hoodie-client/pom.xml
hoodie-client/src/main/resources/META-INF/NOTICE.txt
hoodie-common/src/main/resources/META-INF/NOTICE.txt
hoodie-hadoop-mr/src/main/resources/META-INF/NOTICE.txt
hoodie-hive/pom.xml
hoodie-hive/src/main/resources/META-INF/NOTICE.txt
hoodie-integ-test/src/main/resources/META-INF/NOTICE.txt
hoodie-spark/src/main/resources/META-INF/NOTICE.txt
hoodie-timeline-service/src/main/resources/META-INF/NOTICE.txt
hoodie-utilities/pom.xml
hoodie-utilities/src/main/resources/META-INF/NOTICE.txt
packaging/hoodie-hadoop-mr-bundle/src/main/resources/META-INF/HUDI_NOTICE.txt
packaging/hoodie-hive-bundle/src/main/resources/META-INF/HUDI_NOTICE.txt
packaging/hoodie-presto-bundle/src/main/resources/META-INF/HUDI_NOTICE.txt
packaging/hoodie-spark-bundle/src/main/resources/META-INF/HUDI_NOTICE.txt
packaging/hoodie-utilities-bundle/src/main/resources/META-INF/HUDI_NOTICE.txt
pom.xml

Details in https://issues.apache.org/jira/browse/LEGAL-461
HUDI-149 - Remove platform dependencies and update NOTICE plugin

HUDI-149 - Remove platform dependencies and update NOTICE plugin

---

hoodie-common/src/main/java/com/uber/hoodie/common/util/collection/DiskBasedMap.java

Remove the tmp file if fail to create one.
https://issues.apache.org/jira/projects/HUDI/issues/HUDI-171?filter=allopenissues

HUDI-171 delete tmp file after split merge failure

---

content/community.html
content/contributing.html
docs/community.md
docs/contributing.md

- Minor details on JIRA usage
- Updated html files

[HUDI-196] First draft of committership guidelines

---

content/admin_guide.html
content/community.html
content/configurations.html
content/contributing.html
content/docker_demo.html
content/feed.xml
content/gcs_hoodie.html
content/migration_guide.html
content/querying_data.html
content/quickstart.html
content/s3_hoodie.html
content/writing_data.html
docs/admin_guide.md
docs/configurations.md
docs/contributing.md
docs/docker_demo.md
docs/gcs_filesystem.md
docs/migration_guide.md
docs/querying_data.md
docs/quickstart.md
docs/s3_filesystem.md
docs/writing_data.md

HUDI-201 Updated docs to reflect migration from com.uber.hoodie to org.apache.hudi

---

hudi-client/src/test/java/org/apache/hudi/TestHoodieClientOnCopyOnWriteStorage.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HiveIncrementalPuller.java

see jira: [HUDI-212](https://jira.apache.org/jira/browse/HUDI-212)

HUDI-212: Specify Charset to UTF-8 for IOUtils.toString

---

docs/community.md

Jira - https://issues.apache.org/jira/browse/HUDI-215

[HUDI-215] Mentioned github issue link for joining slack group in community.md

---

docs/README.md

JIRA issue ref: https://issues.apache.org/jira/browse/HUDI-213

[HUDI-213] Add gem dependencies installation step for building doc description

---

docs/docker_demo.md

Adding Presto related documentation for docker demo page.

[HUDI-82] Add docs for Presto integration in Docker demo

---

pom.xml

see jira:[HUDI-229](https://jira.apache.org/jira/projects/HUDI/issues/HUDI-229)

[HUDI-229] Fix mvn notice:generate issue in windows

---

hudi-client/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
hudi-client/src/test/java/org/apache/hudi/io/TestHoodieMergeHandle.java

Added MergeHandle unit-test to #777

HUDI-170 Updating hoodie record before inserting it into ExternalSpillableMap

---

.travis.yml
_config.yml
deploy/maven/sonatype-settings.xml
docker/compose/docker-compose_hadoop284_hive233_spark231.yml
docker/setup_demo.sh
docker/stop_demo.sh
hudi-cli/hudi-cli.sh
hudi-hive/run_sync_tool.sh
hudi-spark/run_hoodie_app.sh
release/config/license-mappings.xml
style/checkstyle-suppressions.xml
style/checkstyle.xml
style/eclipse-java-google-style.xml
style/intellij-java-google-style.xml
style/scalastyle-config.xml
tools/run_travis_tests.sh

see jira [HUDI-230](https://jira.apache.org/jira/projects/HUDI/issues/HUDI-230)
cc @bvaradar

[HUDI-230] Add missing Apache License in some files

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java

Allow ordering fields to be nested

[HUDI-231] Support nested ordering fields

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieWithTimelineServer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/adhoc/UpgradePayloadFromUberToApache.java

see jira[HUDI-236](https://jira.apache.org/jira/projects/HUDI/issues/HUDI-236)

[HUDI-236] Failed to close stream

---

hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java

[Minor] fix typo

---

docs/quickstart.cn.md

see jira[HUDI-237](https://issues.apache.org/jira/browse/HUDI-237)
cc @yanghua @vinothchandar PTAL.

[HUDI-237] Translate quickstart page

---

docs/use_cases.cn.md

see jira [HUDI-240](https://jira.apache.org/jira/browse/HUDI-240)

[HUDI-240] Translate Use Cases page

---

content/powered_by.html
content/quickstart.html
docs/powered_by.cn.md
docs/powered_by.md
docs/quickstart.md

- Added to .cn page as well
- Also fixed link to older releases in quickstart

[DOCS] : Add ApacheCon talk to powered_by page

---

LICENSE

[HUDI-252] Identify packages which are under non-apache license in LICENSE file

[HUDI-252] Identify packages which are under non-apache license in LICENSE file

---

hudi-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java
hudi-client/src/test/java/org/apache/hudi/table/TestCopyOnWriteTable.java

Due to test setup issue. Was able to repro the issue consistently and by adding initialization/cleanup step, the tests are passing consistently

[HUDI-257] Fix Bloom Index unit-test failures

---

docs/quickstart.cn.md
docs/use_cases.cn.md

[docs][chinese] update permalink for translated pages(quickstart.cn.md, use_cases.cn.md)

---

docs/contributing.md
docs/quickstart.cn.md
docs/use_cases.cn.md

[HUDI-228] Contributing page updated to include JIRA guidelines

---

.mailmap

@vinothchandar @bhasudha : Going to try this out to see if the contribution is reflected correctly

Adding mailmap to allow mapping of defunct emailIds to active emailIds

---

hudi-client/src/test/java/org/apache/hudi/HoodieClientTestHarness.java
hudi-client/src/test/java/org/apache/hudi/TestCleaner.java
hudi-client/src/test/java/org/apache/hudi/TestCompactionAdminClient.java
hudi-client/src/test/java/org/apache/hudi/io/TestHoodieCompactor.java
hudi-client/src/test/java/org/apache/hudi/table/TestMergeOnReadTable.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/test/java/org/apache/hudi/common/model/HoodieTestUtils.java
hudi-common/src/test/java/org/apache/hudi/common/table/log/HoodieLogFormatTest.java
hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/HoodieRealtimeRecordReaderTest.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java

jira ref: https://issues.apache.org/jira/browse/HUDI-267

HUDI-267 Refactor bad method name HoodieTestUtils#initTableType and HoodieTableMetaClient#initializePathAsHoodieDataset

---

docs/powered_by.cn.md

see [jira](https://jira.apache.org/jira/browse/HUDI-255)
cc @yihua PTAL when you are free. Thanks.

[HUDI-255] Translate Talks & Powered By page

---

RELEASE_NOTES.md
hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java

minimal change to have config file in another s3 bucket

[MINOR] Config from different bucket

---

docs/index.cn.md

jira ref: https://issues.apache.org/jira/browse/HUDI-220

HUDI-220 Translate root index page

---

docs/comparison.cn.md

see [jira-256](https://jira.apache.org/jira/browse/HUDI-256)
cc @yihua @yanghua Could you PTAL when you are free?

[HUDI-256] Translate Comparison page

---

docs/powered_by.cn.md

This PR is opened to address the comments of this PR [901](https://github.com/apache/incubator-hudi/pull/901)
cc @yihua @vinothchandar

[minor][docs-chinese] Improve translation

---

docs/admin_guide.cn.md

see [jira-278](https://jira.apache.org/jira/browse/HUDI-278)
cc @yihua @yanghua Could you PTAL when you are free?

[HUDI-278] Translate Administering page

---

hudi-client/src/main/java/org/apache/hudi/index/InMemoryHashIndex.java
hudi-client/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
hudi-client/src/main/java/org/apache/hudi/index/hbase/HBaseIndex.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
hudi-client/src/test/java/org/apache/hudi/func/TestUpdateMapFunction.java
hudi-client/src/test/java/org/apache/hudi/table/TestCopyOnWriteTable.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieRecord.java
hudi-common/src/test/java/org/apache/hudi/common/util/SpillableMapTestUtils.java

see jira: https://jira.apache.org/jira/projects/HUDI/issues/HUDI-232
CC @vinothchandar Please review when you get a chance. Thanks.

[HUDI-232] Implement sealing/unsealing for HoodieRecord class

---

docs/quickstart.cn.md
docs/use_cases.cn.md

context in https://lists.apache.org/thread.html/47015a0837e43975df3ec5b61d37ce7a839e6d05ac87f681bd0ed311@%3Cdev.hudi.apache.org%3E
CC @vinothchandar

[docs][chinese] revert the PR(#900)

---

docs/quickstart.md

- Uses spark-shell based examples to showcase Hudi core features
- Info related to hive sync, hive, presto, etc are removed

[HUDI-291] Simplify quickstart documentation

---

hudi-client/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java

Jira: https://jira.apache.org/jira/browse/HUDI-301

[HUDI-301] fix path error when updating a non-partition MOR table

---

docs/quickstart.cn.md

This PR sync the changes in the PR [937](https://github.com/apache/incubator-hudi/pull/937) to chinese.
@yihua PTAL when you get a chance. Thanks.

[docs][chinese] sync quickstart.md change to quickstart.cn.md

---

content/search.json
docs/_data/tags.yml
docs/docker_demo.cn.md
docs/docker_demo.md
docs/events/2016-12-30-strata-talk-2017.cn.md
docs/events/2016-12-30-strata-talk-2017.md
docs/events/2019-01-18-asf-incubation.cn.md
docs/events/2019-01-18-asf-incubation.md
docs/index.cn.md
docs/index.md
docs/js/mydoc_scroll.html
docs/news_archive.md
docs/quickstart.cn.md
docs/quickstart.md

jira: https://issues.apache.org/jira/browse/HUDI-286?filter=-1

HUDI-286 Remove tags from Hudi official web site

---

pom.xml

jira: https://jira.apache.org/jira/projects/HUDI/issues/HUDI-312
Cc @vinothchandar

[MINOR] Fix vm crashes

---

.travis.yml

see jira: https://jira.apache.org/jira/projects/HUDI/issues/HUDI-312
Cc @vinothchandar

[MINOR] Fix no output in travis

---

hudi-hive/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java

Fix annotation error in TestHiveSyncTool
Cc @vinothchandar @bvaradar

[MINOR] Fix annotation error in TestHiveSyncTool

---

docs/concepts.cn.md

see jira: https://jira.apache.org/jira/projects/HUDI/issues/HUDI-221
@yihua PTAL when you get a chance. Thanks.

[HUDI-221] Translate concept page

---

hudi-common/src/main/avro/HoodieArchivedMetaEntry.avsc
hudi-common/src/main/avro/HoodieCommitMetadata.avsc
hudi-common/src/main/avro/HoodieCompactionMetadata.avsc
hudi-common/src/main/avro/HoodieRestoreMetadata.avsc

Add proper default values to avro schemas

[MINOR] Fix avro schema warnings in builds

---

docs/quickstart.md

Uses --packages option referring to Hudi maven artifact instead of --jars.

[HUDI-317] change quickstart page spark-shell command 

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java
hudi-client/src/main/java/org/apache/hudi/HoodieWriteClient.java

Small code refactoring to remove redundant code.

[HUDI-245]: replaced instances of getInstants() and reverse() with getReverseOrderedInstants()

---

docs/quickstart.cn.md

It is a follow up PR to sync updates of PR(https://github.com/apache/incubator-hudi/pull/986)
@yihua PTAL. Thanks.

[chinese][docs] sync updates in quickstart page

---

README.md

Update to align with original Uber whitepaper

---

docs/configurations.cn.md

https://issues.apache.org/jira/browse/HUDI-276

[HUDI-276] Translate the Configurations page into Chinese

---

hudi-client/src/test/java/org/apache/hudi/TestCleaner.java
style/checkstyle.xml

**AIMS**
add EmptyStatement java checkstyle rule.

[HUDI-330] add EmptyStatement java checkstyle rule

---

pom.xml

**AIMS**
fix missing version of rat-plugin

[HOTFIX] fix missing version of rat-plugin

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieParquetRealtimeInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java

- Adding more comments to understand usage of reader/writer schema
- Fixing RT queries for HiveOnSpark that causes race conditions

[HUDI-151] Enable HiveOnSpark queries for RT tables

---

docs/404.cn.md

Translate the 404 page into chinese documentation. 
Help to review, thanks.

[doc][chinese] Translate the 404 page into chinese documentation

---

docs/quickstart.md

It is unable to run quickstart example smoothly by quick-start document.
- Add reload data step for quick-start document.

[DOC] Add reload step

---

docs/_data/sidebars/mydoc_sidebar_cn.yml
docs/_data/strings_cn.yml
docs/_data/topnav_cn.yml
docs/_includes/topnav.html
docs/quickstart.md
docs/releases.cn.md

Translate the release page into chinese documentation
- Translate the release page into chinese documentation
- Modify mydoc_sidebar_cn
- Add strings_cn
- Fix typo in quickstart
This pull request is a doc work without any test coverage.

[doc][chinese] Translate the release page into chinese documentation

---

docs/admin_guide.cn.md
docs/quickstart.cn.md

Sync translation and code in quickstart.cn and admin_guide.cn pages
- *translate a ignored line in admin_guide.cn*
- *sync reload code in quickstart.cn*

[HUDI-356][chinese] Sync translation and code in quickstart.cn and admin_guide.cn pages

---

hudi-spark/src/main/java/org/apache/hudi/QuickstartUtils.java

*Fix unable to generateUpdates in QuickstartUtils*
```
scala> convertToStringList(dataGen.generateInserts(1))
res0: java.util.List[String] = [{"ts": 0.0, "uuid": "78956d3a-c13b-4871-8b14-596b2a7e11d9", "rider": "rider-213", "driver": "driver-213", "begin_lat": 0.4726905879569653, "begin_lon": 0.46157858450465483, "end_lat": 0.754803407008858, "end_lon": 0.9671159942018241, "fare": 34.158284716382845, "partitionpath": "americas/brazil/sao_paulo"}]
scala> convertToStringList(dataGen.generateUpdates(1))
java.lang.IllegalArgumentException: bound must be positive
at java.util.Random.nextInt(Random.java:388)
at …
```

[HUDI-374] Unable to generateUpdates in QuickstartUtils

---

docs/powered_by.md

[DOCS] Add EMR to powered by page

---

README.md

Update Hudi Readme, please visit [overview](https://github.com/BigDataArtisans/incubator-hudi/tree/hudi-readme) to quick overview.
Update Hudi Readme
This pull request is a trivial code cleanup without any test coverage.

[Docs] Update Hudi Readme

---

README.md

update http to https.
update http://hudi.apache.org to https://hudi.apache.org
update http://avro.apache.org/docs/current/mr.html to https://avro.apache.org/docs/current/mr.html

[MINOR] Update some url from http to https in the README file

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieCLI.java
hudi-cli/src/main/java/org/apache/hudi/cli/HoodiePrintHelper.java
hudi-cli/src/main/java/org/apache/hudi/cli/Main.java
hudi-cli/src/main/java/org/apache/hudi/cli/Table.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/DatasetsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieSyncCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/StatsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/utils/CommitUtil.java
hudi-cli/src/main/java/org/apache/hudi/cli/utils/HiveUtil.java
hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java

*To refactor hudi-cli based on new ImportOrder code style rule*
- *Modify ImportOrder based on checkstyle rule in checkstyle.xml*

[HUDI-365] Refactor hudi-cli based on new ImportOrder code style rule

---

hudi-client/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java
hudi-client/src/main/java/org/apache/hudi/metrics/JmxMetricsReporter.java
hudi-client/src/test/java/org/apache/hudi/TestCleaner.java
hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieJmxMetrics.java
hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
hudi-common/src/main/java/org/apache/hudi/common/versioning/clean/CleanMetadataMigrator.java
hudi-common/src/main/java/org/apache/hudi/common/versioning/clean/CleanV1MigrationHandler.java
hudi-common/src/main/java/org/apache/hudi/common/versioning/clean/CleanV2MigrationHandler.java
hudi-hive/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
style/checkstyle.xml

[major] Refactor the rest codes based on new ImportOrder code style rule
- Refactor the rest codes based on new ImportOrder code style rule

[HUDI-378] Refactor the rest codes based on new ImportOrder code style rule

---

.gitignore

After run `hudi-cli.sh`, will generate a `hoodie-cmd.log` file. The git will detect it.
- add *.log to .gitignore file

[MINOR] add *.log to .gitignore file

---

docs/powered_by.md

[DOCS] Add reInvent talk to powered_by page

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieSplashScreen.java

Beautify the cli banner
- Beautify the cli banner

[MINOR] Beautify the cli banner

---

docs/contributing.md

Updated the ide set up section to have it in the form of points. Also added link for adding spark jars to the class path in Intellij externally.

[HUDI-380]: updated ide setup on contributing.html page

---

docs/community.cn.md
docs/community.md

add committers info.
Please checkout [https://gist.github.com/leesf/084f7c3eb7811b6613c357cc47af5e3e](https://gist.github.com/leesf/084f7c3eb7811b6613c357cc47af5e3e) to see the effects.
add committers info.

[MINOR] add committers info

---

README.md

Add slack invite icon on README
- Add slack invite icon on README
This pull request is doc update without any test coverage.

[MINOR] Add slack invite icon on README

---

hudi-spark/src/main/java/org/apache/hudi/ComplexKeyGenerator.java

*Fix TestComplexKeyGenerator#testSingleValueKeyGenerator and testMultipleValueKeyGenerator NPE*
- *Fix TestComplexKeyGenerator#testSingleValueKeyGenerator and testMultipleValueKeyGenerator NPE*

[HUDI-442] Fix TestComplexKeyGenerator#testSingleValueKeyGenerator and testMultipleValueKeyGenerator NPE

---

pom.xml
style/checkstyle.xml
style/scalastyle.xml

Check scala style rules one by one, disable rule which can not pass currently, then fix them one by one.
- Refactor hudi scala checkstyle rules.
```
mvn scalastyle:check
```

[HUDI-386] Refactor hudi scala checkstyle rules

---

hudi-cli/src/main/scala/org/apache/hudi/cli/DedupeSparkJob.scala
hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
style/scalastyle.xml

Refactor the codes based on scala codestyle NullChecker rule.
-  Refactor the codes based on scala codestyle NullChecker rule.
This pull request is a code cleanup without any test coverage.

[HUDI-444] Refactor the codes based on scala codestyle NullChecker rule

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java

[MINOR] typo fix

---

hudi-client/pom.xml
hudi-client/src/main/java/org/apache/hudi/AbstractHoodieClient.java
hudi-client/src/main/java/org/apache/hudi/CompactionAdminClient.java
hudi-client/src/main/java/org/apache/hudi/HoodieCleanClient.java
hudi-client/src/main/java/org/apache/hudi/HoodieReadClient.java
hudi-client/src/main/java/org/apache/hudi/HoodieWriteClient.java
hudi-client/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
hudi-client/src/main/java/org/apache/hudi/index/hbase/DefaultHBaseQPSResourceAllocator.java
hudi-client/src/main/java/org/apache/hudi/index/hbase/HBaseIndex.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieCleanHelper.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieCommitArchiveLog.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieKeyLookupHandle.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
hudi-client/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
hudi-client/src/main/java/org/apache/hudi/io/compact/HoodieRealtimeTableCompactor.java
hudi-client/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
hudi-client/src/main/java/org/apache/hudi/metrics/JmxMetricsReporter.java
hudi-client/src/main/java/org/apache/hudi/metrics/Metrics.java
hudi-client/src/main/java/org/apache/hudi/metrics/MetricsGraphiteReporter.java
hudi-client/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
hudi-client/src/main/java/org/apache/hudi/table/HoodieCopyOnWriteTable.java
hudi-client/src/main/java/org/apache/hudi/table/HoodieMergeOnReadTable.java
hudi-client/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/src/main/java/org/apache/hudi/table/RollbackExecutor.java

- Redo hudi-client log statements using SLF4J.
- Change the pom.xml of hudi-client, add slf4j dependency.
- Modify the related class from log4j to slf4j.

[HUDI-455] Redo hudi-client log statements using SLF4J

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java

Fix out of limits for results.
- Fix logic error
This pull request is a code cleanup without any test coverage.

[MINOR] Fix out of limits for results

---

doap_HUDI.rdf

DOAP file for HUDI
ASF Administrative Requirement for all projects in Foundation

[HUDI-343]: Create a DOAP file for Hudi

---

docs/powered_by.md

1. Added slides for Hadoop summit 2019, Bangalore
2. Updated Adoptions to include Tathastu.ai

[HUDI-443]: Added slides from Hadoop Summit 2019, Bangalore. Also updated Adoptions

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotCopier.java

Fix error usage of String.format.
- Modify `$s` to `%s`.

[MINOR] Fix error usage of String.format

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java

Added options for passing properties to Clean, Compact and importer commands in hudi-cli module.

[HUDI-118]: Options provided for passing properties to Cleaner, compactor and importer commands

---

hudi-timeline-service/pom.xml
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/FileSystemViewHandler.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/table/view/TestRemoteHoodieTableFileSystemView.java

Redo hudi-timeline-service log statements using SLF4J.
Redo hudi-timeline-service log statements using SLF4J.
Use existing tests to verify the original module.

[HUDI-462] Redo hudi-timeline-service log statements using SLF4J

---

hudi-spark/pom.xml
hudi-spark/src/main/scala/org/apache/hudi/DefaultSource.scala
hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
hudi-spark/src/main/scala/org/apache/hudi/IncrementalRelation.scala
hudi-spark/src/test/java/HoodieJavaApp.java
hudi-spark/src/test/java/HoodieJavaStreamingApp.java

Redo hudi-spark log statements using SLF4J.
Modify AnnotationLocation checkstyle rule in checkstyle.xml
Use existing tests to verify the original module.

[HUDI-461] Redo hudi-spark log statements using SLF4J

---

hudi-utilities/pom.xml
hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HiveIncrementalPuller.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCleaner.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotCopier.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/adhoc/UpgradePayloadFromUberToApache.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/AbstractDeltaStreamerService.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/Compactor.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/SchedulerConfGenerator.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/perf/TimelineServerPerf.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HiveIncrPullSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/FlatteningTransformer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/SqlQueryBasedTransformer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/AbstractBaseTestSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/DistributedTestDataSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestDataSource.java

Redo hudi-utilities log statements using SLF4J.
Modify AnnotationLocation checkstyle rule in checkstyle.xml
Use existing tests to verify the original module.

[HUDI-463] Redo hudi-utilities log statements using SLF4J

---

hudi-spark/src/main/java/org/apache/hudi/ComplexKeyGenerator.java
hudi-spark/src/main/java/org/apache/hudi/DataSourceUtils.java
hudi-spark/src/main/java/org/apache/hudi/NonpartitionedKeyGenerator.java
hudi-spark/src/main/java/org/apache/hudi/SimpleKeyGenerator.java
hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/keygen/TimestampBasedKeyGenerator.java

Added default partition path in TimestampBasedKeyGenerator

[HUDI-406] Added default partition path in TimestampBasedKeyGenerator

---

docker/setup_demo.sh
docker/stop_demo.sh

*Execute docker/setup_demo.sh in any directory*
- *Read the shell script path to docker-compose*
- *Set WS_ROOT=parent directory of the shell script*

[HUDI-501] Execute docker/setup_demo.sh in any directory

---

hudi-cli/pom.xml
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/main/java/org/apache/hudi/cli/utils/InputStreamConsumer.java
hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java
hudi-cli/src/main/scala/org/apache/hudi/cli/DedupeSparkJob.scala
pom.xml

Redo hudi-cli log statements using SLF4J.
Modify AnnotationLocation checkstyle rule in checkstyle.xml
Use existing tests to verify the original module.

[HUDI-454] Redo hudi-cli log statements using SLF4J

---

hudi-integ-test/pom.xml
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
pom.xml

*Redo hudi-integ-test log statements using SLF4J*
*Redo hudi-integ-test log statements using SLF4J*
This pull request should be covered by existing tests.

[HUDI-460] Redo hudi-integ-test log statements using SLF4J

---

hudi-client/src/main/java/org/apache/hudi/index/hbase/HBaseIndex.java

Jira: https://jira.apache.org/jira/browse/HUDI-495
Internally we are using HBase 2.x, and HBase 2.x no longer supports ```Htable.flushCommits()``` and it is replaced by ```BufferedMutator.flush()```.
Thus for put operation and delete operation, we can use BufferedMutator instead.
- *Replace HTable with BufferedMutator*

[HUDI-495] Update deprecated HBase API

---

hudi-hive/pom.xml
hudi-hive/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
hudi-hive/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
hudi-hive/src/main/java/org/apache/hudi/hive/util/SchemaUtil.java
hudi-hive/src/test/java/org/apache/hudi/hive/util/HiveTestService.java

Redo hudi-hive log statements using SLF4J.
- *Redo hudi-hive log statements using SLF4J.*

[HUDI-459] Redo hudi-hive log statements using SLF4J

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/util/HoodieAvroUtils.java

Replace utf-8 constant with StandardCharsets.UTF_8.
- *replace utf-8 constant with StandardCharsets.UTF_8.*

[CLEAN] replace utf-8 constant with StandardCharsets.UTF_8

---

hudi-client/src/test/java/org/apache/hudi/TestCleaner.java
hudi-client/src/test/java/org/apache/hudi/table/TestCopyOnWriteTable.java
hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
hudi-hive/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java

Fix `partition` typo.
- *Fix `partition` typo.*

[CLEAN] Fix partition typo

---

hudi-hadoop-mr/pom.xml
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveUtil.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/RecordReaderValueIterator.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/hive/HoodieCombineHiveInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieParquetRealtimeInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieRealtimeRecordReader.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java

*Redo hudi-hadoop-mr log statements using SLF4J*
*Redo hudi-hadoop-mr log statements using SLF4J*
This pull request should be covered by existing tests.

[HUDI-458] Redo hudi-hadoop-mr log statements using SLF4J

---

hudi-common/src/main/java/org/apache/hudi/common/util/TypedProperties.java

Refactor unnecessary boxing inside TypedProperties.
- *Refactor unnecessary boxing*

[MINOR] Refactor unnecessary boxing inside TypedProperties code

---

hudi-spark/src/main/java/org/apache/hudi/QuickstartUtils.java

Adding util methods to assist in adding deletion support to Quick Start
Verified that the util methods works.

[MINOR] Adding util methods to assist in adding deletion support to Quick Start

---

hudi-client/src/test/java/org/apache/hudi/common/HoodieTestDataGenerator.java
hudi-client/src/test/java/org/apache/hudi/func/TestBoundedInMemoryExecutor.java
hudi-client/src/test/java/org/apache/hudi/func/TestBoundedInMemoryQueue.java
hudi-client/src/test/java/org/apache/hudi/io/TestHoodieCompactor.java
hudi-client/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageWriterFactory.java
hudi-client/src/test/java/org/apache/hudi/table/TestMergeOnReadTable.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHDFSParquetImporter.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/UtilitiesTestBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/AbstractBaseTestSource.java

Make constant fields final in `HoodieTestDataGenerator` class and rename them based on the naming convention.
As above.  This is code clean-up.

[MINOR] Make constant fields final in HoodieTestDataGenerator

---

hudi-common/src/main/java/org/apache/hudi/common/model/TimelineLayoutVersion.java

Add toString method to TimelineLayoutVersion to make the log more readable, e.g. https://github.com/apache/incubator-hudi/blob/master/hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java#L122
modify TimelinelayoutVersion.java

[MINOR] Add toString method to TimelineLayoutVersion to make it more readable

---

doap_HUDI.rdf

[MINOR] Fix PMC in DOAP]

---

LICENSE

Add license for PR#1233
Update LICENSE file.

[HUDI-556] Add license for PR#1233

---

hudi-client/src/main/java/org/apache/hudi/client/utils/ClientUtils.java
hudi-client/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/src/test/java/org/apache/hudi/TestHoodieClientBase.java
hudi-client/src/test/java/org/apache/hudi/TestHoodieClientOnCopyOnWriteStorage.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/test/java/org/apache/hudi/common/table/string/TestHoodieActiveTimeline.java

Make sure by default table layout version honors the configuration in hoodie.properties

[HUDI-559] : Make sure by default table layout version honors the configuration in hoodie.properties

---

docker/hoodie/hadoop/base/pom.xml
docker/hoodie/hadoop/datanode/pom.xml
docker/hoodie/hadoop/historyserver/pom.xml
docker/hoodie/hadoop/hive_base/pom.xml
docker/hoodie/hadoop/namenode/pom.xml
docker/hoodie/hadoop/pom.xml
docker/hoodie/hadoop/prestobase/pom.xml
docker/hoodie/hadoop/spark_base/pom.xml
docker/hoodie/hadoop/sparkadhoc/pom.xml
docker/hoodie/hadoop/sparkmaster/pom.xml
docker/hoodie/hadoop/sparkworker/pom.xml
hudi-cli/pom.xml
hudi-client/pom.xml
hudi-common/pom.xml
hudi-hadoop-mr/pom.xml
hudi-hive/pom.xml
hudi-integ-test/pom.xml
hudi-spark/pom.xml
hudi-timeline-service/pom.xml
hudi-utilities/pom.xml
packaging/hudi-hadoop-mr-bundle/pom.xml
packaging/hudi-hive-bundle/pom.xml
packaging/hudi-presto-bundle/pom.xml
packaging/hudi-spark-bundle/pom.xml
packaging/hudi-timeline-server-bundle/pom.xml
packaging/hudi-utilities-bundle/pom.xml
pom.xml

Preparing for Release 0.5.1-incubating-rc1.
update pom files.

Preparing for Release 0.5.1-incubating-rc1

---

docker/hoodie/hadoop/base/pom.xml
docker/hoodie/hadoop/datanode/pom.xml
docker/hoodie/hadoop/historyserver/pom.xml
docker/hoodie/hadoop/hive_base/pom.xml
docker/hoodie/hadoop/namenode/pom.xml
docker/hoodie/hadoop/pom.xml
docker/hoodie/hadoop/prestobase/pom.xml
docker/hoodie/hadoop/spark_base/pom.xml
docker/hoodie/hadoop/sparkadhoc/pom.xml
docker/hoodie/hadoop/sparkmaster/pom.xml
docker/hoodie/hadoop/sparkworker/pom.xml
hudi-cli/pom.xml
hudi-client/pom.xml
hudi-common/pom.xml
hudi-hadoop-mr/pom.xml
hudi-hive/pom.xml
hudi-integ-test/pom.xml
hudi-spark/pom.xml
hudi-timeline-service/pom.xml
hudi-utilities/pom.xml
packaging/hudi-hadoop-mr-bundle/pom.xml
packaging/hudi-hive-bundle/pom.xml
packaging/hudi-presto-bundle/pom.xml
packaging/hudi-spark-bundle/pom.xml
packaging/hudi-timeline-server-bundle/pom.xml
packaging/hudi-utilities-bundle/pom.xml
pom.xml

Update version to 0.5.2-SNAPSHOT.
update pom files.

Moving to 0.5.2-SNAPSHOT on master branch.

---

docs/_data/ui-text.yml

Upper toc_label.
- *Upper toc_label.*
This pull request is rework of web-doc.

[MINOR] Upper toc_label

---

docs/_data/navigation.yml
docs/_docs/2_2_writing_data.md
docs/_docs/2_6_deployment.cn.md
docs/_docs/2_6_deployment.md

- Moved "Adminsitering" page to "Deployment"
- Still need to add information on deltastreamer modes/compaction
*(or)*
(or)
*(example:)* …

[HUDI-403] Adds guidelines on deployment/upgrading

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java

*Update the javadoc of HoodieTableMetaClient#scanFiles*
*Update the javadoc of HoodieTableMetaClient#scanFiles*

[MINOR] Update the javadoc of HoodieTableMetaClient#scanFiles

---

docs/_docs/0_3_migration_guide.md
docs/_docs/1_1_quick_start_guide.md
docs/_docs/1_2_structure.md
docs/_docs/1_3_use_cases.md
docs/_docs/1_5_comparison.md
docs/_docs/2_1_concepts.md
docs/_docs/2_2_writing_data.md
docs/_docs/2_3_querying_data.md
docs/_docs/2_4_configurations.md
docs/_docs/2_5_performance.md

[HUDI-510] Update site documentation in sync with cWiki

---

scripts/release/deploy_staging_jars.sh

[MINOR] Change deploy_staging_jars script to take in scala version

---

docker/demo/presto-batch1.commands
docker/demo/presto-batch2-after-compaction.commands
docker/demo/presto-table-check.commands
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java

[MINOR] Add missing licenses

---

docker/demo/presto-batch1.commands
docker/demo/presto-batch2-after-compaction.commands
docker/demo/presto-table-check.commands

[MINOR] Fix license issue

---

docs/_docs/0.5.0/1_1_quick_start_guide.md
docs/_docs/1_1_quick_start_guide.md

- Adding delete docs to QuickStart
Verified locally.

[Minor] Adding delete docs to QuickStart

---

docker/hoodie/hadoop/hive_base/pom.xml
docker/hoodie/hadoop/prestobase/pom.xml
hudi-integ-test/pom.xml
pom.xml

Fix missing groupId / version property of dependency.
- *Fix missing groupId / version property of dependency.*
This pull request is a code cleanup without any test coverage.

[MINOR] Fix missing groupId / version property of dependency

---

README.md
pom.xml

This `https://github.org` domain does not exist. 
Replace `https://github.org` with `https://github.com`
- *Fix invalid issue url.*
This pull request is a trivial rework without any test coverage.

[MINOR] Fix invalid issue url & quickstart url

---

docs/_docs/0.5.0/3_2_docs_versions.cn.md
docs/_docs/0.5.0/3_2_docs_versions.md
docs/_docs/3_2_docs_versions.cn.md
docs/_docs/3_2_docs_versions.md
docs/_sass/hudi_style/_page.scss
docs/_sass/hudi_style/_tables.scss
docs/_sass/hudi_style/skins/_hudi.scss

Add border to table on hudi website.
-------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------
This pull request is webui work.

[HUDI-579] Add border to table on hudi website

---

hudi-common/pom.xml
pom.xml

Remove junit-dep dependency.
- *Remove junit-dep dependency.*
No need to download `junit-dep`.
```
total 120
drwxr-xr-x  5 hmatu  staff   160 Jan 26 20:11 4.10
drwxr-xr-x  5 hmatu  staff   160 Jan 26 20:11 4.11-beta-1
drwxr-xr-x  6 hmatu  staff   192 Jan 26 20:11 4.11.20120805.1225
drwxr-xr-x  5 hmatu  staff   160 Jan 26 20:11 4.9
-rw-r--r--  1 hmatu  staff   563 Jan 26 20:11 maven-metadata-Maven Central.xml
-rw-r--r--  1 hmatu  staff    40 Jan 26 20:11 maven-metadata-Maven Central.xml.sha1
-rw-r--r--  1 hmatu  staff   563 Jan 26 20:11 maven-metadata-central.xml
-rw-r--r--  1 hmatu  staff    40 Jan 26 20:11 maven-metadata-central.xml.sha1
-rw-r--r--  1 hmatu  staff   733 Jan 26 20:11 maven-metadata-libs-milestone.xml
-rw-r--r--  1 hmatu  staff    40 Jan 26 20:11 …
```

[MINOR] Remove junit-dep dependency

---

hudi-common/src/test/java/org/apache/hudi/common/table/log/TestHoodieLogFormat.java
hudi-common/src/test/java/org/apache/hudi/common/table/log/TestHoodieLogFormatVersion.java

Added new test cases for HoodieLogFormat and HoodieLogFormatVersion.
mvn test --also-make -DfailIfNoTests=false -Dtest=TestHoodieLogFormat,TestHoodieLogFormatVersion -pl hudi-common

[HUDI-564] Added new test cases for HoodieLogFormat and HoodieLogFormatVersion.

---

docs/_docs/0_4_docker_demo.md
docs/_docs/1_1_quick_start_guide.md
docs/_docs/1_2_structure.md
docs/_docs/2_1_concepts.md
docs/_docs/2_2_writing_data.md
docs/_docs/2_3_querying_data.md
docs/_docs/2_5_performance.md

Summary:
- contains changes that reflect renaming of terminologies to be in sync wth CWiki
- contains doc changes pertaining to support of multiple scala versions
*(or)*
(or)
*(example:)*
- …

[HUDI-577] update docker demo page and quick start pages

---

content/docs/quick-start-guide.html
content/index.html
content/releases.html
docs/_docs/1_1_quick_start_guide.md
docs/_pages/index.md
docs/_pages/releases.md

Fix minor links
*(or)*
(or)
*(example:)*

[DOCS] Update site

---

doap_HUDI.rdf

[MINOR] Updated DOAP with 0.5.1 release

---

hudi-hive/src/test/java/org/apache/hudi/hive/util/HiveTestService.java
hudi-test-suite/pom.xml
hudi-test-suite/prepare_integration_suite.sh
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/helpers/HiveServiceProvider.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/reader/SparkBasedReader.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/writer/SparkAvroDeltaInputWriter.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/utils/TestUtils.java

*This pull request try to support spark version upgrade and fix the test failure on `hudi_test_suite_refactor` branch*
- *Excluded the old spark-avro dependency*
- *Introduce the new spark-avro dependency*
- *some trivial changes*

[HUDI-591] Support Spark version upgrade

---

docs/_pages/contributing.cn.md
docs/_pages/contributing.md

*This pull request adds some guidance about how to judge the scope of MINOR to the contribution guidance*
- *Add some guidance about how to judge the scope of MINOR to the contribution guidance*

[HUDI-602] Add some guidance about how to judge the scope of MINOR to the contribution guidance

---

NOTICE

Fix the year in NOTICE
- *Update NOTICE year to 2020*

[HUDI-582] Update NOTICE year

---

hudi-test-suite/pom.xml

*This pull request removes duplicated dependencies in the pom file of test suite module*
- *Remove duplicated dependencies in the pom file of test suite module*

[HUDI-592] Remove duplicated dependencies in the pom file of test suite module

---

hudi-client/src/main/java/org/apache/hudi/HoodieWriteClient.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java

*Fix some typos*
*Fix some typos*

[MINOR] Fix some typos

---

hudi-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java
hudi-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieGlobalBloomIndex.java
hudi-client/src/test/java/org/apache/hudi/io/TestHoodieCommitArchiveLog.java
hudi-client/src/test/java/org/apache/hudi/io/strategy/TestHoodieCompactionStrategy.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/RocksDbBasedFileSystemView.java
hudi-common/src/test/java/org/apache/hudi/common/model/HoodieTestUtils.java
hudi-common/src/test/java/org/apache/hudi/common/table/log/TestHoodieLogFormat.java
hudi-common/src/test/java/org/apache/hudi/common/table/string/TestHoodieActiveTimeline.java
hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/hive/HoodieCombineHiveInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeUnmergedRecordReader.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
hudi-hive/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
hudi-hive/src/main/java/org/apache/hudi/hive/SchemaDifference.java
hudi-hive/src/main/java/org/apache/hudi/hive/util/ColumnNameXLator.java

Code cleanup - prelude to Guava elimination

[MINOR] Code Cleanup, remove redundant code

---

hudi-client/src/main/java/org/apache/hudi/HoodieCleanClient.java
hudi-client/src/main/java/org/apache/hudi/HoodieWriteClient.java
hudi-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
hudi-client/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
hudi-client/src/main/java/org/apache/hudi/index/bloom/HoodieGlobalBloomIndex.java
hudi-client/src/main/java/org/apache/hudi/index/hbase/HBaseIndex.java
hudi-client/src/main/java/org/apache/hudi/io/compact/strategy/BoundedPartitionAwareCompactionStrategy.java
hudi-client/src/main/java/org/apache/hudi/io/compact/strategy/DayBasedCompactionStrategy.java
hudi-client/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
hudi-client/src/main/java/org/apache/hudi/table/HoodieMergeOnReadTable.java
hudi-common/src/main/java/org/apache/hudi/common/bloom/filter/InternalFilter.java
hudi-common/src/main/java/org/apache/hudi/common/util/BufferedRandomAccessFile.java
hudi-common/src/main/java/org/apache/hudi/common/util/FSUtils.java
hudi-common/src/main/java/org/apache/hudi/common/util/ObjectSizeCalculator.java
hudi-common/src/main/java/org/apache/hudi/common/util/RocksDBDAO.java
hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryQueue.java
hudi-spark/src/main/scala/org/apache/hudi/AvroConversionHelper.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java

Remove @VisibleForTesting annotation as part of Guava cleanup in PR#  1159

[HUDI-622]: Remove VisibleForTesting annotation and import from code

---

docs/_docs/2_3_querying_data.cn.md
docs/_docs/2_3_querying_data.md

*Add impala guide to doc*
- *add to querying_data English version and Chinese version*

HUDI-611 Add Impala Guide to Doc

---

content/docs/docker_demo.html
docs/_docs/0_4_docker_demo.md

JIRA: https://issues.apache.org/jira/browse/HUDI-632
- *Mentioned both commit and deltacommit files in docker_demo*

[HUDI-632] Update documentation (docker_demo) to mention both commit and deltacommit files

---

hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
hudi-common/src/test/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemViewTest.java
hudi-common/src/test/java/org/apache/hudi/common/table/view/TestPriorityBasedFileSystemView.java

- This PR is to address the JIRA ticket - [HUDI-618](https://issues.apache.org/jira/browse/HUDI-618)
- Added unit tests for `org.apache.hudi.common.table.view. PriorityBasedFileSystemView`
- Refactored DRY code in `org.apache.hudi.common.table.view.RemoteHoodieTableFileSystemView`
- Added unit tests to `org.apache.hudi.common.table.view. PriorityBasedFileSystemView` for improving code coverage
- Checked code coverage to ensure all methods and branches are covered
- Run all tests to ensure refactoring didn't break anything

[HUDI-618] Adding unit tests for PriorityBasedFileSystemView

---

docs/_config.yml
docs/_pages/security.cn.md
docs/_pages/security.md

Provide a statement page to describe how to report security issues
- *Provide a statement page to describe how to report security issues*

[HUDI-645] Provide a statement page to describe how to report security issues

---

docs/_pages/community.md

*This pull request changed community.html page with new PPMC/committers*
- *Change community.html page with new PPMC/committers*

[HUDI-647] Change community.html page with new PPMC/committers

---

scripts/release/deploy_staging_jars.sh

update release scripts due to https://github.com/apache/incubator-hudi/pull/1293
run ./deploy_staging_jars.sh

[HUDI-599] Update release guide & release scripts due to the change of scala 2.12 build

---

scripts/release/cut_release_branch.sh

*This pull request fixes cut_release_branch script missed a double quotation marks*
- *Fix cut_release_branch script missed a double quotation marks*

[MINOR] Fix cut_release_branch script missed a double quotation marks

---

docs/_docs/2_3_querying_data.md

- Added support matrix for COW and MOR tables
- Change reference from (`views`|`pulls`) to `queries`
- And minor restructuring
*(or)*
(or)
*(example:)*
- *Added HoodieClientWriteTest to …

[HUDI-589][DOCS] Fix querying_data page

---

docs/_docs/2_3_querying_data.md

[HUDI-589] Follow on fixes to querying_data page

---

docs/_docs/2_3_querying_data.md

I am not sure if the Read Optimized Table will work if the format is MOR table. Will double check once I get the chance.

MINOR add impala to matrix

---

hudi-client/src/main/java/org/apache/hudi/client/HoodieReadClient.java
hudi-client/src/test/java/org/apache/hudi/client/TestHoodieReadClient.java
hudi-client/src/test/java/org/apache/hudi/table/TestMergeOnReadTable.java
hudi-client/src/test/java/org/apache/hudi/table/compact/TestAsyncCompaction.java
hudi-spark/src/main/java/org/apache/hudi/DataSourceUtils.java

*This pull request try to decouple HoodieReadClient and AbstractHoodieClient to break the inheritance chain*
- *Decouple HoodieReadClient and AbstractHoodieClient to break the inheritance chain*

[HUDI-652] Decouple HoodieReadClient and AbstractHoodieClient to break the inheritance chain

---

docs/_docs/0_4_docker_demo.md

1. Change one line command to multi line 
2. Modify  sub title
**Compare changes**
- https://hudi.apache.org/docs/docker_demo.html
- https://lamber-ken.github.io/docs/docker_demo.html

[HUDI-604] Update docker page

---

docs/_docs/2_4_configurations.cn.md
docs/_docs/2_4_configurations.md

* `hoodie.bloom.index.update.partition.path`

[HUDI-499] Add configuration docs

---

docs/_docs/0_4_docker_demo.cn.md
docs/_docs/0_4_docker_demo.md

After https://github.com/apache/incubator-hudi/pull/1374 , need to update the run_sync_tool.sh script path
- `/var/hoodie/ws/hudi-hive` to `/var/hoodie/ws/hudi-hive-sync`
Ignore

[MINOR] Update run_sync_tool.sh script path

---

hudi-client/src/test/java/org/apache/hudi/index/TestHbaseIndex.java

Added unit-test for HBaseIndex
Added unit test for code missing coverage.
mvn test

[HUDI-671] Added unit-test for HBaseIndex

---

NOTICE

Need to fix NOTICE file, else Justin's gonna smack ya.

[HUDI-581] NOTICE need more work as it missing content form included 3rd party ALv2 licensed NOTICE files

---

hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieJmxMetrics.java
hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java

Added unit-tests for HUDI metrics.
Added unit test for code missing coverage.
mvn test

[HUDI-668] Added unit-tests for HUDI metrics.

---

hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestDiskBasedMap.java

Added unit-test for DiskBasedMap
Added unit test for code missing coverage.
mvn test

[HUDI-670] Added test cases for TestDiskBasedMap.

---

hudi-client/src/test/java/org/apache/hudi/common/HoodieTestDataGenerator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieDeltaStreamer.java

PR fixes a bug in delete record generation for tests in hoodie delta streamer. 
- Fixing a bug in delete record generation for tests in hoodie delta streamer
This pull request is already covered by existing tests. Most tests in TestHoodieDeltaStreamer tests deletes. Have to make some fixes to continuous tests as part of the bug fix.

[HUDI-667] Fixing delete tests for DeltaStreamer

---

hudi-client/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java

Remove some dead code. Improves code coverage.
Removed code is present in the base class HoodieWriteHandle.
This pull request is a trivial rework / code cleanup without any test coverage. Verified using:
mvn clean package

[MINOR] Removing code which is duplicated from the base class.

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java

*Now, deleteSavepoint already provided in HoodieWriteClient, but not provide to user, add it in CLI.*
- *Add delete savepoint for cli*

[HUDI-692] Add delete savepoint for cli

---

docs/_docs/0.5.2/1_1_quick_start_guide.cn.md
docs/_docs/0.5.2/1_1_quick_start_guide.md
docs/_docs/0.5.2/2_2_writing_data.md
docs/_docs/0.5.2/2_3_querying_data.md
docs/_docs/0.5.2/2_6_deployment.md

*This pull request updates the old hudi version to 0.5.2*
- *Update the old hudi version to 0.5.2*

Update the old hudi version to 0.5.2

---

hudi-cli/src/test/java/org/apache/hudi/cli/AbstractShellIntegrationTest.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestSparkEnvCommand.java
hudi-cli/src/test/resources/log4j-surefire-quiet.properties
hudi-cli/src/test/resources/log4j-surefire.properties

*Add unit test for SparkEnvCommand in hudi-cli module*
- *Add unit test for SparkEnvCommand*
- *Add unit test for SparkEnvCommand*

[HUDI-694]Add unit test for SparkEnvCommand

---

hudi-cli/pom.xml
hudi-cli/src/test/java/org/apache/hudi/cli/AbstractShellIntegrationTest.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java

*Add unit test for TableCommand in hudi-cli module*
- *Add unit test for TableCommand*
- *Add unit test for TableCommand*

[HUDI-695]Add unit test for TableCommand

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java

[HUDI-539] Make ROPathFilter conf member serializable

---

hudi-client/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
hudi-client/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/src/main/java/org/apache/hudi/index/HoodieIndex.java
hudi-client/src/test/java/org/apache/hudi/index/TestHoodieIndex.java

Support user-defined index.
Modify HoodieIndex.java
Add UTs in TestHoodieIndex.java

[HUDI-437] Support user-defined index

---

docs/_docs/0.5.0/2_4_configurations.md
docs/_docs/0.5.1/2_4_configurations.md
docs/_docs/2_4_configurations.cn.md
docs/_docs/2_4_configurations.md

Add user-defined index config docs with the PR(https://github.com/apache/incubator-hudi/pull/1408)
*(or)*
(or)
*(example:)*

[HUDI-437] Add user-defined index config

---

hudi-client/pom.xml
hudi-client/src/main/java/org/apache/hudi/config/HoodieMetricsConfig.java
hudi-client/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/src/main/java/org/apache/hudi/metrics/InMemoryMetricsReporter.java
hudi-client/src/main/java/org/apache/hudi/metrics/JmxMetricsReporter.java
hudi-client/src/main/java/org/apache/hudi/metrics/JmxReporterServer.java
hudi-client/src/main/java/org/apache/hudi/metrics/Metrics.java
hudi-client/src/main/java/org/apache/hudi/metrics/MetricsGraphiteReporter.java
hudi-client/src/main/java/org/apache/hudi/metrics/MetricsReporter.java
hudi-client/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieJmxMetrics.java
pom.xml

The server to which JMX clients connect to. Allows for better control over port usage for JMX metrics reporter.
*The changes are as follows:*
- *pom.xml*
- *hudi-client/pom.xml*
- *hudi-client/src/main/java/org/apache/hudi/config/HoodieMetricsConfig.java*
- *hudi-client/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java*
- *hudi-client/src/main/java/org/apache/hudi/metrics/JmxMetricsReporter.java*
- *hudi-client/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java*
- *hudi-client/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java*
- *hudi-client/src/main/java/org/apache/hudi/client/utils/NetUtils.java*
- *hudi-client/src/main/java/org/apache/hudi/client/utils/UnionIterator.java*
- *By …

[HUDI-209] Implement JMX metrics reporter

---

docs/_docs/2_4_configurations.cn.md
docs/_docs/2_4_configurations.md
docs/_docs/2_6_deployment.cn.md
docs/_docs/2_6_deployment.md

Add JMX Report Config to doc
*(or)*
(or)
*(example:)*

[HUDI-653] Add JMX Report Config to Doc

---

hudi-common/src/main/java/org/apache/hudi/common/versioning/compaction/CompactionV2MigrationHandler.java
hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java

What is the purpose of the pull request
Add more test for compaction plan upgrade
Brief change log
check upgrade from old plan to new plan for compaction
Verify this pull request

[HUDI-400]check upgrade from old plan to new plan for compaction

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java

*Delete unused method in HoodieDeltaStreamer*
*Delete unused method in HoodieDeltaStreamer*

[HUDI-726]Delete unused method in HoodieDeltaStreamer

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java

*Remove init log in the constructor of DeltaSync*
*Remove init log in the constructor of DeltaSync*

[HUDI-725] Remove init log in the constructor of DeltaSync

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java

cleanup redundant comment and code
cleanup redundant comment and code

[MINOR] cleanup redundant comment and unused variable,  and fix typo

---

hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieDeltaStreamer.java

[HUDI-616]: fixed parquet files getting created on local FS

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java

More detail, please go ahead with https://github.com/apache/incubator-hudi/issues/1375
1. the first commit content like following:
```
{
"partitionToWriteStats" : { },
"compacted" : false,
"extraMetadata" : {
"ROLLING_STAT" : "{\n  \"partitionToRollingStats\" : { },\n  \"actionType\" : \"commit\"\n}",
"schema" : "{\"type\":\"record\",\"name\":\"stock_ticks\",\"fields\":[{\"name\":\"volume\",\"type\":\"long\"},{\"name\":\"ts\",\"type\":\"string\"},{\"name\":\"symbol\",\"type\":\"string\"},{\"name\":\"year\",\"type\":\"int\"},{\"name\":\"month\",\"type\":\"string\"},{\"name\":\"high\",\"type\":\"double\"},{\"name\":\"low\",\"type\":\"double\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"date\",\"type\":\"string\"},{\"name\":\"close\",\"type\":\"double\"},{\"name\":\"open\",\"type\":\" …
```

[HUDI-663] Fix HoodieDeltaStreamer offset not handled correctly

---

docs/_docs/1_4_powered_by.cn.md
docs/_docs/1_4_powered_by.md

Add Hudi online meeup talk to website
*(or)*
(or)
*(example:)*

[MINOR] Add Hudi Online Meetup

---

hudi-client/src/main/java/org/apache/hudi/table/HoodieCopyOnWriteTable.java

*Fix javadoc of InsertBucket*
*Fix javadoc of InsertBucket*

[MINOR] Fix javadoc of InsertBucket

---

docs/_docs/1_4_powered_by.cn.md
docs/_docs/1_4_powered_by.md

[MINOR] Add link for yields.io usage

---

content/cn/docs/powered_by.html
content/cn/releases.html
content/docs/powered_by.html
content/releases.html
docs/_pages/releases.cn.md
docs/_pages/releases.md

*This pull request UpdateS the release note url for 0.5.2*
- *Update the release note url for 0.5.2*

[MINOR] Update the release note url for 0.5.2

---

doap_HUDI.rdf

Update DOAP
Updated DOAP for 0.5.2 Release

[MINOR] Update DOAP with 0.5.2 Release

---

docs/_docs/0.5.2/2_3_querying_data.cn.md
docs/_docs/0.5.2/2_3_querying_data.md
docs/_docs/2_3_querying_data.cn.md
docs/_docs/2_3_querying_data.md

Change Impala matrix
Add incremental pulling from certain partitions to 0.5.2 and latest Doc

MINOR update doc to include inc query on partitions

---

pom.xml

[HUDI-745] CI should fail PRs with unapproved license files

---

hudi-client/src/test/java/org/apache/hudi/common/HoodieMergeOnReadTestUtils.java

Minor changes to enhance HoodieMergeOnReadTestUtils for future use (for HUDI-741)
1. getRecordsUsingInputFormat() can take a custom Configuration which can be used to specify HUDI table properties (e.g. <table>.consume.mode or <table>.consume.start.timestamp)
2. Fixed the return to return an empty List rather than raise an Exception if no records are found

[MINOR] Updated HoodieMergeOnReadTestUtils for future testing requirements.

---

hudi-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
hudi-client/src/test/java/org/apache/hudi/index/bloom/TestBucketizedBloomCheckPartitioner.java

To fix the exception, link: https://issues.apache.org/jira/browse/HUDI-742, discussion: https://github.com/apache/incubator-hudi/issues/1455
- modified:   hudi-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
- modified:   hudi-client/src/test/java/org/apache/hudi/index/bloom/TestBucketizedBloomCheckPartitioner.java
- modified:   hudi-client/src/test/java/org/apache/hudi/index/bloom/TestBucketizedBloomCheckPartitioner.java

[HUDI-742] Fix Java Math Exception

---

.asf.yaml

*This pull request configures `.asf.yaml` for Hudi Github repository*
- *Configure .asf.yaml for Hudi Github repository*

[HUDI-754] Configure .asf.yaml for Hudi Github repository

---

packaging/hudi-timeline-server-bundle/run_server.sh

Fix packaging/hudi-timeline-server-bundle./run_server.sh start error
fix
This change can get more accurate information

[HUDI-749] Fix hudi-timeline-server-bundle./run_server.sh start error

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/ChainedTransformer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestUtilHelpers.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestChainedTransformer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestFlatteningTransformer.java

Add `ChainedTransformer` to facilitate chained transformation. A subclass is to supply a list transformers.

[HUDI-731] Add ChainedTransformer

---

.asf.yaml

*This pull request fixes label issue in .asf.yaml*
- *Fix label issue in .asf.yaml*

Fix label issue in .asf.yaml

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/checkpointing/InitialCheckPointProvider.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/checkpointing/KafkaConnectHdfsProvider.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/checkpointing/TestKafkaConnectHdfsProvider.java

This PR adds a checkpoint provider interfaces for delta streamer and implement the kafka connect hdfs checkpoint provider
- *New class CheckpointProvider*
- *New class KafkaConnectHdfsProvider*
- *New test TestCheckpointProvider*
- *New test TestCheckpointProvider to cover the new classes*

HUDI-644 kafka connect checkpoint provider

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieKey.java

clear up the redundant comment.
HoodieKey.java has a redundant comment.

[MINOR]clear up the redundant comment.

---

hudi-spark/src/test/java/TestComplexKeyGenerator.java
hudi-test-suite/pom.xml
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/configuration/DFSDeltaConfig.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/configuration/DeltaConfig.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/BulkInsertNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/CompactNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/HiveQueryNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/InsertNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/UpsertNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/generator/LazyRecordGeneratorIterator.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/helpers/DFSTestSuitePathSelector.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/job/HoodieDeltaStreamerWrapper.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/job/HoodieTestSuiteJob.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/reader/DFSDeltaInputReader.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/reader/DFSHoodieDatasetInputReader.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/writer/AvroDeltaInputWriter.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/writer/DeltaWriter.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/TestDFSDeltaWriterAdapter.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/TestFileDeltaInputWriter.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/dag/ComplexDagGenerator.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/generator/TestGenericRecordPayloadGenerator.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/job/TestHoodieTestSuiteJob.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/reader/TestDFSAvroDeltaInputReader.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/reader/TestDFSHoodieDatasetInputReader.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/writer/TestDeltaWriter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/UtilitiesTestBase.java
packaging/hudi-test-suite-bundle/pom.xml

- Port bug fixes to test suite
- Additional features to test suite will be added in a separate PR
- Fix compilation issues
- This pull request is a trivial rework / code cleanup without any test coverage.
- I have yet to actually run the tests. Will do this momentarily.

Fix Compilation Issues + Port Bug Fixes

---

docs/_pages/community.cn.md
docs/_pages/community.md

Update community info
This pull request is a trivial work.

[MINOR] Update community info

---

hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java

Fix typo in TimelineService
stand alone -> standalone
There's no need for verfication.

[MINOR] Fix typo in TimelineService

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderConfig.java
hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java

*Add unit test for FileSystemViewCommand*
- *Add unit test for FileSystemViewCommand*

[HUDI-700]Add unit test for FileSystemViewCommand

---

hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
hudi-common/src/test/java/org/apache/hudi/common/storage/TestStorageSchemes.java

Add support of Aliyun object storage service.
- Modify StorageSchemes add support for oss, add testcase

[HUDI-782] Add support of Aliyun object storage service.

---

docs/_docs/0_5_oss_filesystem.cn.md
docs/_docs/0_5_oss_filesystem.md

Add doc for oss filesystem
- add 0_5_oss_filesystem.cn.md
- add 0_5_oss_filesystem.md

[HUDI-782] Add doc for OSS filesystem

---

hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystem.java

- Disabling flaky test in InlineFileSystem. Need time to work on investigating and put up a fix. 

[HUDI-786] Disabling flaky test in InlineFileSystem

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-client/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
hudi-client/src/main/java/org/apache/hudi/client/HoodieWriteClient.java
hudi-client/src/main/java/org/apache/hudi/exception/HoodieRestoreException.java
hudi-client/src/main/java/org/apache/hudi/table/HoodieCopyOnWriteTable.java
hudi-client/src/main/java/org/apache/hudi/table/HoodieMergeOnReadTable.java
hudi-client/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
hudi-client/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java
hudi-client/src/main/java/org/apache/hudi/table/action/restore/CopyOnWriteRestoreActionExecutor.java
hudi-client/src/main/java/org/apache/hudi/table/action/restore/MergeOnReadRestoreActionExecutor.java
hudi-client/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
hudi-client/src/main/java/org/apache/hudi/table/action/rollback/CopyOnWriteRollbackActionExecutor.java
hudi-client/src/main/java/org/apache/hudi/table/action/rollback/MergeOnReadRollbackActionExecutor.java
hudi-client/src/main/java/org/apache/hudi/table/action/rollback/RollbackHelper.java
hudi-client/src/main/java/org/apache/hudi/table/action/rollback/RollbackRequest.java
hudi-client/src/test/java/org/apache/hudi/client/TestClientRollback.java
hudi-client/src/test/java/org/apache/hudi/table/TestCleaner.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystem.java

…xecutor abstraction
*(or)*
(or)
*(example:)*

[HUDI-761] Refactoring rollback and restore actions using the ActionExecutor abstraction

---

.travis.yml
hudi-cli/pom.xml
hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCleansCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCleansCommand.java
hudi-cli/src/test/resources/clean.properties
scripts/run_travis_tests.sh

*Add unit test for CleansCommand in hudi-cli module*
- *Add unit test for CleansCommand*
- *Add unit test for CleansCommand.*

[HUDI-698]Add unit test for CleansCommand

---

hudi-cli/pom.xml
hudi-client/pom.xml
hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieJmxMetrics.java
hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
hudi-common/pom.xml
hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroWriteSupport.java
hudi-hadoop-mr/pom.xml
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/InputPathHandlerTest.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestAnnotation.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestRecordReaderValueIterator.java
hudi-hive-sync/pom.xml
hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestUtil.java
hudi-integ-test/pom.xml
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieSanity.java
hudi-spark/pom.xml
hudi-spark/src/test/java/DataSourceUtilsTest.java
hudi-spark/src/test/scala/TestDataSource.scala
hudi-spark/src/test/scala/TestDataSourceDefaults.scala
hudi-timeline-service/pom.xml
hudi-utilities/pom.xml
hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestChainedTransformer.java
pom.xml

- Add junit 5 dependencies to all modules
- Migrate test cases in modules
- hudi-cli (none, need refactoring)
- hudi-client (selected test cases)
- hudi-common (selected test cases)
- hudi-hadoop-mr (selected test cases)
- hudi-hive-sync ✅ 
- hudi-integ-test ✅ 
- hudi-spark ✅ 
- hudi-timeline-service (none, no import)
- hudi-utilities (selected test cases)

[HUDI-780] Migrate test cases to Junit 5

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java

[HUDI-777] Update Deltastreamer param description for --target-table

---

docs/_docs/0_4_docker_demo.cn.md
docs/_docs/0_4_docker_demo.md

*Fix typo*
*Fix typo*
- *modify Kakfa to Kafka in 0_4_docker_demo.cn.md and 0_4_docker_demo.md*

[HUDI-815] fix typo

---

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java

*Remove reduntant code and fix typo in HoodieDefaultTimeline*
*Remove reduntant code and fix typo in HoodieDefaultTimeline*

[MINOR]Remove reduntant code and fix typo in HoodieDefaultTimeline

---

docs/_docs/0_5_oss_filesystem.cn.md
docs/_docs/0_5_oss_filesystem.md

* Update docs for oss_filesystem
- Modify docs/_docs/0_5_oss_filesystem.cn.md
- Modify docs/_docs/0_5_oss_filesystem.md
*(or)*
(or)

[Minor] Update docs for oss_filesystem

---

docs/_docs/1_1_quick_start_guide.cn.md
docs/_docs/1_1_quick_start_guide.md

[HUDI-823] fix typo

---

hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/BulkInsertNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/CleanNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/CompactNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/DagNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/HiveQueryNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/HiveSyncNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/InsertNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/RollbackNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/ScheduleCompactNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/SparkSQLQueryNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/nodes/UpsertNode.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/dag/scheduler/DagScheduler.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/generator/DeltaGenerator.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/generator/GenericRecordFullPayloadGenerator.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/job/HoodieTestSuiteJob.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/reader/DFSHoodieDatasetInputReader.java
hudi-test-suite/src/main/java/org/apache/hudi/testsuite/writer/AvroDeltaInputWriter.java
hudi-test-suite/src/test/java/org/apache/hudi/testsuite/reader/TestDFSHoodieDatasetInputReader.java

*Normalize log print statement*
*Redo hudi-test-suite log statements using SLF4J*
*Normalize log print statement*
*Redo hudi-test-suite log statements using SLF4J*
This pull request should be covered by existing tests.

[HUDI-397] Normalize log print statement

---

docs/_docs/1_1_quick_start_guide.cn.md

*Revise translation in quick start*
*Revise translation in quick start*

[MINOR] revise translation

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java

*Add unit test for HoodieLogFileCommand*
- *Add unit test for HoodieLogFileCommand*

[HUDI-702]Add test for HoodieLogFileCommand

---

docs/_docs/1_1_quick_start_guide.md

To add the example of hudi pyspark
Modify 1_1_quick_start doc.
yes
*(or)*
(or)
*(example:)*
- *Manually verified the change by running …

[HUDI-783] Add pyspark example in quickstart

---

docs/_docs/1_5_comparison.md

*fix typo in comparison document*
*fix typo in comparison document*

[MINOR] fix typo in comparison document

---

docs/_docs/1_3_use_cases.md

*(Fix typo in use-case document)*
*Fix typo in use-case document*

[MINOR]Fix typo in use case

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/main/scala/org/apache/hudi/cli/SparkHelpers.scala
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestRepairsCommand.java
hudi-cli/src/test/resources/table-config.properties

*Add test for RepairsCommand in hudi-cli module*
- *Add test for RepairsCommand*

[HUDI-704]Add test for RepairsCommand

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java

This one was hard to reproduce and debug, but proposed fix gets rid of the error. Still not sure whether it is issue with GCS library or static array. 
- Modifed HoodieLogFileReader.
Not sure what the test should be...

[HUDI-784] Adressing issue with log reader on GCS

---

hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieJmxMetrics.java
hudi-common/src/test/java/org/apache/hudi/common/minicluster/HdfsTestService.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/NetworkTestUtils.java

[MINOR] Fix hardcoding of ports in TestHoodieJmxMetrics

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java

Fix exception log error
KafkaOffsetGen.java

MINOR Fix log content error

---

docs/_pages/releases.cn.md
docs/_pages/releases.md

This is a follow up from the graduation DISCUSS thread. 
*(or)*
(or)
*(example:)*

[MINOR] Point release page to downloads.apache.org directly

---

docs/_includes/footer.html
docs/_sass/hudi_style/skins/_hudi.scss

Justin Mclean point that there are also some required links / branding missing on your the web site.
https://whimsy.apache.org/pods/project/hudi
https://lists.apache.org/thread.html/rf661535e8837c13f25c8ec184310391108f029ee7eb88b98b5d6b465%40%3Cgeneral.incubator.apache.org%3E

[HUDI-891] Improve websites for graduation required content

---

hudi-cli/pom.xml
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestHDFSParquetImportCommand.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHDFSParquetImporter.java

*Add unit test for HDFSParquetImportCommand*

[HUDI-701]Add unit test for HDFSParquetImportCommand

---

docs/_docs/1_4_powered_by.md
docs/_layouts/home.html
docs/_sass/hudi_style/skins/_hudi.scss

- Remove logos on home page
- Move logos to powered by page.
**Sync**
https://lamber-ken.github.io
https://lamber-ken.github.io/docs/powered_by.html

[MINOR] Remove logos on home page

---

pom.xml

To avoid getting OOM in running CI tests.

[MINOR] Increase heap space for surefire

---

hudi-client/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
hudi-client/src/main/java/org/apache/hudi/table/WorkloadProfile.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieKey.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
hudi-spark/src/main/java/org/apache/hudi/DataSourceUtils.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java

*Add javadoc and comments to hudi write method link*
*Add javadoc and comments to hudi write method link*
- *Add javadoc*
- *Add some comments in methods*
- *Code clean*

[HUDI-714]Add javadoc and comments to hudi write method link

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRollbacksCommand.java

*Add unit test for RollbacksCommand*
- *Add unit test for RollbacksCommand*

[HUDI-705]Add unit test for RollbacksCommand

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestSavepointsCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestSavepointsCommand.java

*Add unit test for SavepointsCommand*
- *Add unit test for SavepointsCommand*

[HUDI-706]Add unit test for SavepointsCommand

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java

This PR fixes a NPE when compacting via hudi-cli and providing a compaction props file via `propsFilePath`
- initialize `FileSystem` before use

[HUDI-888] fix NullPointerException

---

hudi-client/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
hudi-client/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
hudi-hive-sync/pom.xml
hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestService.java
hudi-spark/pom.xml
hudi-utilities/pom.xml
pom.xml

This is to enable timeline-server and incremental cleaning by default

[HUDI-846][HUDI-848] Enable Incremental cleaning and embedded timeline-server by default

---

docs/_docs/0.5.2/2_3_querying_data.cn.md
docs/_docs/0.5.2/2_3_querying_data.md
docs/_docs/1_1_quick_start_guide.cn.md
docs/_docs/1_1_quick_start_guide.md
docs/_docs/2_3_querying_data.cn.md
docs/_docs/2_3_querying_data.md

[MINOR] add impala release and spark partition discovery

---

docs/_docs/1_4_powered_by.md

Add alibaba cloud to powered-by page.
*(or)*
(or)
*(example:)*

[MINOR] Add Alibaba cloud to powered by page

---

NOTICE
README.md
doap_HUDI.rdf
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
pom.xml
scripts/release/cut_release_branch.sh
scripts/release/preparation_before_release.sh
scripts/release/validate_staged_release.sh

*Remove incubating from NOTICE*
*(or)*
(or)
*(example:)*

[HUDI-938] Remove incubating/incubator from project

---

.travis.yml
docs/_docs/1_1_quick_start_guide.md

Update site to reflect graduation
- Remove `incubator`
- Update doc

[MINOR] Update site to reflect graduation

---

docs/_docs/1_4_powered_by.md

[MINOR] Update usages reported and order companies alphabetically

---

doap_HUDI.rdf

[MINOR] Fix PMC tag in doap file

---

docs/_docs/0_5_oss_filesystem.cn.md
docs/_docs/0_5_oss_filesystem.md
docs/_docs/0_6_azure_filesystem.cn.md
docs/_docs/0_6_azure_filesystem.md
docs/_docs/2_4_configurations.cn.md
docs/_docs/2_4_configurations.md

[HUDI-804] Add Azure support to doc

---

docs/_docs/1_4_powered_by.md

it's better to be conservative here, add it back if they are actually using it. : )
- Remove kyligence from powered_by page

[MINOR] Remove kyligence from powered_by page

---

docs/_docs/2_4_configurations.cn.md
docs/_docs/2_4_configurations.md

Update configuration docs for https://github.com/apache/incubator-hudi/pull/1572

[HUDI-836] Add configs for Datadog metrics reporter

---

docs/_docs/1_4_powered_by.md

Add text in powered_by page.
cc @lamber-ken @vinothchandar

[MINOR] Add Text in powered_by

---

docs/_docs/0_4_docker_demo.md

updated prerequisite : jq
updated prerequisite : jq
Documentation change no tests.

[MINOR] Updated prerequisites: jq, Maven, and Java 8

---

scripts/release/validate_staged_release.sh

Fixes release validation script for 1: ignoring application/json files 2: checking for presence of DISCLAIMER file

[MINOR] Fixing binary file checks and disclaimer file checks

---

hudi-client/src/test/java/org/apache/hudi/client/TestCompactionAdminClient.java
hudi-client/src/test/java/org/apache/hudi/client/TestMultiFS.java
hudi-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
hudi-client/src/test/java/org/apache/hudi/client/TestUpdateSchemaEvolution.java
hudi-client/src/test/java/org/apache/hudi/execution/TestBoundedInMemoryQueue.java
hudi-client/src/test/java/org/apache/hudi/execution/TestSparkBoundedInMemoryExecutor.java
hudi-client/src/test/java/org/apache/hudi/index/TestHoodieIndex.java
hudi-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java
hudi-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieGlobalBloomIndex.java
hudi-client/src/test/java/org/apache/hudi/io/TestHoodieCommitArchiveLog.java
hudi-client/src/test/java/org/apache/hudi/io/TestHoodieKeyLocationFetchHandle.java
hudi-client/src/test/java/org/apache/hudi/io/TestHoodieMergeHandle.java
hudi-client/src/test/java/org/apache/hudi/table/TestConsistencyGuard.java
hudi-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
hudi-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
hudi-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java
hudi-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
hudi-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
hudi-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/FileSystemViewHandler.java
pom.xml

Fix unit tests flakiness.
- *clean up some unit tests*

[HUDI-988] fix more unit tests flakiness

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveUtil.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java

*Ignore case when setting incremental mode in hive query
*(or)*
(or)
*(example:)*

[HUDI-1002] Ignore case when setting incremental mode in hive query

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java

sourceLimit should not be less than the number of kafka partitions

[HUDI-918] Fix kafkaOffsetGen can not read kafka data bug

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/hive/HoodieCombineHiveInputFormat.java
hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestService.java

JIRA: https://issues.apache.org/jira/browse/HUDI-515
This PR resolved the API level conflict between Hive 2 & Hive 3.
(This PR is not enough to make Hudi support Hive 3 since there are other dependencies issue)
- Changed some APIs to make it be compatible with Hive 3.

HUDI-515 Resolve API conflict for Hive 2 & Hive 3

---

hudi-client/src/main/java/org/apache/hudi/table/action/rollback/MergeOnReadRollbackActionExecutor.java

* Code optimization in MergeOnReadRollbackActionExecutor
*(or)*
(or)
*(example:)*

[HUDI-1016] [Minor] Code optimization

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java

*Clean refresh command in CLI*
- *Clean refresh command in CLI*

[HUDI-1019]Clean refresh command in CLI

---

hudi-examples/README.md

*This pull request fixes the ordered list for the hudi-examples README file*
- *Added break line for the ordered list*

[MINOR] Fix the ordered list for the hudi-examples README file

---

doap_HUDI.rdf

- Updating doap file for 0.5.3 release

Updating doap file for 0.5.3 release

---

docs/_pages/releases.md

This pull request adds release docs for release-0.5.3
- Updates releases.md with release info for release-0.5.3
This pull request is updating release docs.

Updating release docs for release-0.5.3

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/UtilsCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUtilsCommand.java

*Add unit test for UtilsCommand*
- *Add unit test for UtilsCommand*

[HUDI-709]Add unit test for UtilsCommand

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCommitsCommand.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java

*Fix bug of command `commits compare`*
*Add unit test for CommitsCommand*
- *Add unit test for CommitsCommand*

[HUDI-696] Add unit test for CommitsCommand

---

docs/_data/navigation.yml
docs/_docs/0.5.3/2_4_configurations.cn.md
docs/_docs/0.5.3/2_4_configurations.md
docs/_docs/0.5.3/2_7_cloud.cn.md
docs/_docs/0.5.3/2_7_cloud.md
docs/_docs/2_4_configurations.cn.md
docs/_docs/2_4_configurations.md
docs/_docs/2_7_cloud.cn.md
docs/_docs/2_7_cloud.md

Cloud information is hard to find right now. Moving it to an obvious place.

[DOC] Move cloud to a separate page

---

.codecov.yml
.travis.yml
hudi-cli/pom.xml
hudi-client/src/test/java/org/apache/hudi/metrics/TestMetricsReporterFactory.java
hudi-integ-test/pom.xml
hudi-spark/pom.xml
hudi-timeline-service/pom.xml
packaging/hudi-spark-bundle/pom.xml
pom.xml
scripts/report_coverage.sh
scripts/run_travis_tests.sh

- use codecov flags for each module to report coverage
- parallelize CI jobs for shorter time
- add a testcase for MetricsReporterFactory (to trigger codecov comment)

[HUDI-896] Report test coverage by modules

---

content/community.html

Add the users@ mailing list to the community page
- *Add the users@ mailing list to the community page*

[MINOR] Add the users@ mailing list to the community page

---

hudi-client/src/test/java/org/apache/hudi/testutils/DFSProvider.java
hudi-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
hudi-client/src/test/java/org/apache/hudi/testutils/SparkProvider.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java
hudi-utilities/pom.xml
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieSnapshotExporter.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/checkpointing/TestKafkaConnectHdfsProvider.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestAWSDatabaseMigrationServiceSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestChainedTransformer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHDFSParquetImporter.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotCopier.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotExporter.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestJdbcbasedSchemaProvider.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/UtilitiesFunctionalTestSuite.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestChainedTransformer.java
pom.xml
style/checkstyle.xml

- Share resources for functional tests
- Add suite for some functional test classes from hudi-utilities
- Run suite in a different maven profile
- Run function tests (suite) in a separate travis job

[HUDI-996] Add functional test suite for hudi-utilities

---

hudi-client/src/main/java/org/apache/hudi/metrics/HoodieGauge.java
hudi-client/src/main/java/org/apache/hudi/metrics/Metrics.java

* Add MetricsSource to support update metrics in HoodieDeltaStreamerMetrics.
*(or)*
(or)
*(example:)*

[HUDI-1004] Support update metrics in HoodieDeltaStreamerMetrics

---

hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala

table name value trim
Trim hoodie table name
This pull request is a trivial rework / code cleanup without any test coverage. There are no modifications to code functionality.
we can use HoodieSparkSqlWriterSuite test.

[HUDI-1064]Trim hoodie table name

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestKafkaSource.java

KafkaOffsetGen
*Remove unnecessary maxEvent check and add some log in KafkaOffsetGen*
*(or)*
(or)
*(example:)*

[HUDI-1062]Remove unnecessary maxEvent check and add some log in KafkaOffsetGen

---

hudi-client/src/test/java/org/apache/hudi/index/hbase/TestHBaseQPSResourceAllocator.java

- Remove unnecessary mini servers in TestHBaseQPSResourceAllocator

[HUDI-994] Make TestHBaseQPSResourceAllocator a unit test

---

hudi-spark/src/main/java/org/apache/hudi/QuickstartUtils.java

Fix IllegalArgumentException in Delete data demo of Quick-Start Guide
*Fix IllegalArgumentException in Delete data demo of Quick-Start Guide*
*(or)*
(or)
*(example:)* …

[HUDI-1078]Fix IllegalArgumentException in Delete data demo of Quick-Start Guide

---

docs/_docs/1_4_powered_by.cn.md
docs/_docs/1_4_powered_by.md
docs/_pages/releases.md

[DOCS] Update recent talks & articles

---

hudi-client/pom.xml
hudi-client/src/test/java/org/apache/hudi/ClientFunctionalTestSuite.java
hudi-client/src/test/java/org/apache/hudi/index/hbase/TestHBaseIndex.java
hudi-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
hudi-client/src/test/java/org/apache/hudi/testutils/providers/DFSProvider.java
hudi-client/src/test/java/org/apache/hudi/testutils/providers/HoodieMetaClientProvider.java
hudi-client/src/test/java/org/apache/hudi/testutils/providers/HoodieWriteClientProvider.java
hudi-client/src/test/java/org/apache/hudi/testutils/providers/SparkProvider.java

- Add functional test suite in hudi-client
- Tag TestHBaseIndex as functional

[HUDI-996] Add functional test suite in hudi-client

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieCLI.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/TempViewCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkTempViewProvider.java
hudi-cli/src/main/java/org/apache/hudi/cli/utils/TempViewProvider.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTempViewCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/testutils/AbstractShellBaseIntegrationTest.java

*1. Add command `temps show`*
*2. Add unit test for TempViewCommand*

[HUDI-708]Add temps show and unit test for TempViewCommand

---

hudi-client/src/test/java/org/apache/hudi/client/TestHoodieClientOnCopyOnWriteStorage.java

- Passed 20+ times locally now
*(or)*
(or)
*(example:)*

[MINOR] Fix flaky testUpsertsUpdatePartitionPath* tests

---

hudi-client/src/test/java/org/apache/hudi/client/TestHoodieClientOnCopyOnWriteStorage.java

[MINOR] Fix checkstyle issue on TestHoodieClientOnCopyOnWriteStorage

---

hudi-client/src/main/java/org/apache/hudi/callback/HoodieWriteCommitCallback.java
hudi-client/src/main/java/org/apache/hudi/callback/client/http/HoodieWriteCommitHttpCallbackClient.java
hudi-client/src/main/java/org/apache/hudi/callback/common/HoodieWriteCommitCallbackMessage.java
hudi-client/src/main/java/org/apache/hudi/callback/impl/HoodieWriteCommitHttpCallback.java
hudi-client/src/main/java/org/apache/hudi/callback/util/HoodieCommitCallbackFactory.java
hudi-client/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
hudi-client/src/main/java/org/apache/hudi/config/HoodieWriteCommitCallbackConfig.java
hudi-client/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/src/main/java/org/apache/hudi/exception/HoodieCommitCallbackException.java
hudi-client/src/test/java/org/apache/hudi/callback/http/TestCallbackHttpClient.java
packaging/hudi-spark-bundle/pom.xml
packaging/hudi-utilities-bundle/pom.xml

*Introduce a write committed callback hook*
*Introduce a write committed callback hook implemented by HTTP*
This pull request is already covered by existing tests, such as 
*org.apache.hudi.callback.http.TestCallBackHttpClient*.
*org.apache.hudi.callback.http.TestHoodieHttpWriteCommitCallBack*

[HUDI-1037]Introduce a write committed callback hook

---

hudi-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
hudi-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java

* Fix minor bug in deciding the insert buckets
*(or)*
(or)
*(example:)*

[HUDI-1082] Fix minor bug in deciding the insert buckets

---

hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieWriteStat.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java

To avoid repeated datetime format "yyyyMMddHHmmss".

[MINOR] Use HoodieActiveTimeline.COMMIT_FORMATTER

---

docker/demo/config/hoodie-incr.properties
docker/demo/config/hoodie-schema.avsc
docker/demo/sync-validate.commands
hudi-cli/pom.xml
hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieSyncCommand.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/HoodieTestHiveBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieSanity.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/command/ITTestHoodieSyncCommand.java
hudi-integ-test/src/test/resources/hoodie-docker.properties
hudi-spark/run_hoodie_app.sh
hudi-spark/src/test/java/HoodieJavaGenerateApp.java

[HUDI-703]Add unit test for HoodieSyncCommand

---

hudi-spark/src/test/java/HoodieJavaGenerateApp.java

Master has a compilation failure which is fixed by this PR.

Fix master compilation failure

---

hudi-client/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java

Fixing default value for simple index parallelism

[MINOR] Fixing default index parallelism for simple index

---

docker/demo/config/log4j.properties
docker/demo/setup_demo_container.sh
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java

[MINOR] Suppressing spark logs for hudi-integ and hudi-utilities

---

hudi-spark/pom.xml
scripts/run_travis_tests.sh

[MINOR] Prevent scalatest plugin from running in non-UTs

---

docs/_docs/1_4_powered_by.md

Adding apache hudi design and code walk through talk link to Apache Hudi website
This pull request just adds a link to Apache hudi website.

[MINOR] Adding apache hudi design and code walk through talk link to Apache Hudi website

---

hudi-client/src/main/java/org/apache/hudi/metrics/ConsoleMetricsReporter.java
hudi-client/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
hudi-client/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java
hudi-client/src/test/java/org/apache/hudi/metrics/TestHoodieConsoleMetrics.java

Added a new metric reporter which prints the metrics on the console.
Added a new metric reporter which prints the metrics on the console.
Added a unit test.

[HUDI-1149] Added a console metrics reporter and associated unit tests.

---

hudi-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java

[HUDI-1026]: removed slf4j dependency from HoodieClientTestHarness

---

packaging/hudi-spark-bundle/pom.xml
packaging/hudi-utilities-bundle/pom.xml

fix hudi-prometheus pom dependency
fix hudi-prometheus pom dependency

[HUDI-1173] fix hudi-prometheus pom dependency 

---

docker/demo/compaction-bootstrap.commands
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
pom.xml

- Adding some log statements
- Commenting out testsuite tests from integration tests until we investigate CI flakiness
*This patch comments out test suite tests from integration tests. Also, adds some log statements*
- Commented out test suite tests from integration tests
- Adding log statements before each command starts
This pull request is a trivial work.

[HUDI-1175] Minor fixes for CI flakiness

---

docs/_docs/2_2_writing_data.md

[HUDI-766]: added section for HoodieMultiTableDeltaStreamer

---

hudi-client/src/main/java/org/apache/hudi/index/HoodieIndex.java
hudi-common/src/main/java/org/apache/hudi/ApiMaturityLevel.java
hudi-common/src/main/java/org/apache/hudi/PublicAPIClass.java
hudi-common/src/main/java/org/apache/hudi/PublicAPIMethod.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordPayload.java
hudi-spark/src/main/java/org/apache/hudi/HoodieDataSourceHelpers.java
hudi-spark/src/main/java/org/apache/hudi/keygen/KeyGenerator.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/checkpointing/InitialCheckPointProvider.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaProvider.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/Transformer.java

- Maturity levels one of : evolving, stable, deprecated
- Took a pass and marked out most of the existing public API
*(or)*
(or)
*(example:)* …

[HUDI-1190] Introduce @PublicAPIClass and @PublicAPIMethod annotations to mark public APIs

---

hudi-spark/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala

This fixes scala 2.12 build error
Fix multiple imports that cause ambiguity when converting scala to java.
[x] This pull request is a trivial rework / code cleanup without any test coverage.
*(or)*
(or)
*(example:)* …

[HUDI-1197] Fix import issue that fails scala 2.12 build

---

hudi-spark/src/main/java/org/apache/hudi/keygen/TimestampBasedKeyGenerator.java
hudi-spark/src/main/java/org/apache/hudi/keygen/parser/HoodieDateTimeParser.java
hudi-spark/src/main/java/org/apache/hudi/keygen/parser/HoodieDateTimeParserImpl.java

[HUDI-1177]: fixed TaskNotSerializableException in TimestampBasedKeyGenerator

---

hudi-client/src/main/java/org/apache/hudi/exception/HoodieUpgradeDowngradeException.java
hudi-client/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java

*Move HoodieUpgradeDowngradeException to exception package*
Keep all the exception class in `org.apache.hudi.exception` might be better
*(or)*

[MINOR] Move HoodieUpgradeDowngradeException to exception package

---

hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-common/src/main/java/org/apache/hudi/common/model/BaseAvroPayload.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroPayload.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/AvroBinaryTestPayload.java

*Improve avroToBytes method of HoodieAvroUtils with try with resource*
This pull request is already covered by TestGenericRecordPayloadGenerator

[HUDI-1217] Improve avroToBytes method of HoodieAvroUtils

---

docs/_docs/1_1_quick_start_guide.md

Fix Delete data demo in Quick-Start Guide
*(or)*
(or)
*(example:)*

[HUDI-1103]Fix Delete data demo in Quick-Start Guide

---

README.md

- add maven profile to test running commands
- remove -DskipITs for packaging commands

[MINOR] Update README.md

---

docs/_docs/1_2_structure.md
docs/_docs/1_4_powered_by.md
docs/_docs/1_5_comparison.md
docs/_docs/2_3_querying_data.cn.md
docs/_docs/2_3_querying_data.md
docs/_docs/2_4_configurations.md
docs/_docs/2_6_deployment.md

[DOC] Doc changes for release 0.6.0 

---

hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/helpers/DFSTestSuitePathSelector.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroDFSSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/DFSPathSelector.java

Add configuration option to pick different path selector
Add configuration option to pick different path selector. This is useful for replace and insert overwrite (RFC-18/RFC-19 still in progress)
This is test suite only change. This can be verified with test suite dags

[HUDI-1137] Add option to configure different path selector

---

doap_HUDI.rdf

[MINOR] Update DOAP with 0.6.0 Release

---

hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java

Make timeline server timeout settings configurable.
Add timeout config settings for timeline server.

[HUDI-1135] Make timeline server timeout settings configurable.

---

hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestDFSHoodieTestSuiteWriterAdapter.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestFileDeltaInputWriter.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/configuration/TestWorkflowBuilder.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/converter/TestUpdateConverter.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/dag/ComplexDagGenerator.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/dag/HiveSyncDagGenerator.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/dag/HiveSyncDagGeneratorMOR.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/dag/TestDagUtils.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/generator/TestGenericRecordPayloadEstimator.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/generator/TestGenericRecordPayloadGenerator.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSAvroDeltaInputReader.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSHoodieDatasetInputReader.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/utils/TestUtils.java

*Add java doc for hudi test suite test classes*
*Add java doc for hudi test suite test classes*

[HUDI-532] Add java doc for the test classes of hudi test suite

---

docs/_docs/0.5.3/1_1_quick_start_guide.cn.md
docs/_docs/1_1_quick_start_guide.cn.md

*Create chinese version of pyspark quickstart example*

[HUDI-1216] Create chinese version of pyspark quickstart example

---

hudi-integ-test/prepare_integration_suite.sh

*Specify version information for each component separately*
- *Specify version information for each component separately*

[HUDI-978] Specify version information for each component separately

---

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java

Add utility method for querying extra metadata. This is useful for several DeltaStreamer like usecases. We cant use DeltaStreamer because source is different than kafka.
- Add utility method to query extra metadata from latest commit
- Add utility method to query extra metadata from all active commits

[HUDI-1228] Add utility method to query extra metadata

---

hudi-client/src/test/java/org/apache/hudi/table/TestCleaner.java

- Use private static assert methods
- Use ParameterizedTest
- Fix a HoodieTestTable API usage issue

[MINOR] Improve helper methods in TestCleaner

---

docs/_pages/community.cn.md
docs/_pages/community.md

- Update committers list
- Update cn page with latest en page content
*(or)*
(or)
*(example:)* …

[DOCS] Update community page

---

docs/_pages/contributing.md

[DOCS] Adding coding guidelines

---

hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java

When unit tests are run on shared machines (e.g. jenkins cluster), the unit tests sometimes fail due to BindException in starting HDFS Cluster. This is because the port chosen may have been bound by another process using the same machine. The fix is to retry the port selection a few times.
Added a loop when creating HDFS Cluster.

[MINOR] Fix BindException when running tests on shared machines.

---

docs/_docs/0_4_docker_demo.md

[MINOR]: removed redundant line from docker-demo page

---

docs/_docs/0_4_docker_demo.cn.md
docs/_docs/0_4_docker_demo.md

*This pull request adds a description to remind users that Hudis docker images have mounted the projects workspace*
- *Added a description*

[MINOR] Add description to remind users that Hudis docker images have mounted the projects workspace

---

content/cn/docs/0.5.3-powered_by.html

This PR adds the youtube link for the data council chat on Apache Hudi

[HUDI-1299] : Adding youtube link for DC_THURS chat on Hudi

---

scripts/checkout_pr.sh
scripts/pr_push_command.sh

- Tested the checkout_pr.sh locally
- Tested a dryrun of pr_push_command.sh
*(or)*
(or)
*(example:)* …

[MINOR] Adding scripts to checkout and push to PRs

---

hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryQueue.java

Fix checkstyle error, cause by merging and pushing by users concurrently.
*(or)*
(or)
*(example:)*

[MINOR] Fix checkstyle

---

hudi-integ-test/prepare_integration_suite.sh

*Reformat prepare_integration_suite script*
- *Reformat prepare_integration_suite script*

[MINOR] Reformat prepare_integration_suite script

---

hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/scheduler/DagScheduler.java

* This pull request changes the log level of the dag scheduler for the test suite*
- *Change the log level of the dag scheduler for the test suite*

[MINOR] Change the log level of the dag scheduler for the test suite

---

docs/_pages/community.md

[MINOR] Add weekly meeting link on community page

---

packaging/hudi-utilities-bundle/pom.xml

[HUDI-1199]: relocated jetty in hudi-utilities-bundle pom

---

docs/_docs/1_4_powered_by.cn.md
docs/_docs/1_4_powered_by.md

[DOCS] PrestoCon Panel Discussion added to site

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/bootstrap/FullRecordBootstrapDataProvider.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndex.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BulkInsertPartitioner.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/AbstractWriteHelper.java

*This pull request fixes wrong javadoc and refactor some naming issues*
- *Fix wrong javadoc and refactor some naming issues (***rdd*** relevant)*

[MINOR] Fix wrong javadoc and refactor some naming issues

---

hudi-spark/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
hudi-spark/src/main/scala/org/apache/hudi/IncrementalRelation.scala

delete useless import in hudi-spark module
*(or)*
(or)
*(example:)*

[HUDI-1339] delete useless import in hudi-spark module

---

docs/_pages/contributing.md

[HUDI-1034][DOCS] Add code guidelines for writing tests

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java

Replace null by Option in Delta Streamer. Make the code look cleaner and more robust
*(or)*
(or)
*(example:)*

[HUDI-791] Replace null by Option in Delta Streamer

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java

Add unit test to ensure compaction works on top of replaced file groups
Add unit test to ensure compaction works on top of replaced file groups
- Test only change

[HUDI-1304] Add unit test for testing compaction on replaced file groups

---

docs/_docs/1_4_powered_by.md

##What is the purpose of the pull request
Adding ApacheCon talk link to site
Verified by deploying the site locally.

[MINOR] Adding ApacheCon talk link to site

---

hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala

…ead consistent
add test to check timestamp date decimal type write and read consistent
*(or)*
(or)
*(example:)*

[HUDI-307] add test to check data type write and read consistent

---

packaging/hudi-utilities-bundle/pom.xml

[HUDI-1345] Remove Hbase and htrace relocation from utilities bundle

---

docs/_docs/1_4_powered_by.md

[DOCS] Adding grofers to site

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTimelineArchiveLog.java

Cleanup rollback files residing in .hoodie folder
*(or)*
(or)
*(example:)*

[HUDI-1118] Cleanup rollback files residing in .hoodie folder

---

docs/_data/authors.yml
docs/_posts/2020-10-06-cdc-solution-using-hudi-by-nclouds.md
docs/_posts/2020-10-19-hudi-meets-aws-emr-and-aws-dms.md

Add links to AWS blogs published in October 2020.
*(or)*
(or)
*(example:)*

Add links to Hudi Blogs published by AWS in October 2020

---

docs/_docs/1_4_powered_by.cn.md
docs/_docs/1_4_powered_by.md

[DOCS] Adding new blogs and link to the blogs page

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/AbstractMergeHelper.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/index/FlinkHoodieIndex.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkDeleteHelper.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/rollback/FlinkMarkerBasedRollbackStrategy.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackHelper.java
hudi-flink/src/main/java/org/apache/hudi/HoodieFlinkStreamer.java
hudi-flink/src/main/java/org/apache/hudi/operator/InstantGenerateOperator.java
hudi-flink/src/main/java/org/apache/hudi/operator/KeyedWriteProcessFunction.java
hudi-flink/src/main/java/org/apache/hudi/operator/KeyedWriteProcessOperator.java
hudi-flink/src/main/java/org/apache/hudi/schema/FilebasedSchemaProvider.java
hudi-flink/src/main/java/org/apache/hudi/schema/SchemaProvider.java
hudi-flink/src/main/java/org/apache/hudi/sink/CommitSink.java
hudi-flink/src/main/java/org/apache/hudi/source/JsonStringToHoodieRecordMapFunction.java
hudi-flink/src/main/java/org/apache/hudi/util/AvroConvertor.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java

Minor code clean up and added some comments.
rename HudiFlinkStreamer to HoodieFlinkStreamer

[MINOR] clean up and add comments to flink client

---

.asf.yaml

[MINOR] Add apacheflink label to asf.yaml

---

docs/_data/authors.yml
docs/_docs/1_4_powered_by.md

[DOCS] Update more blogs, talks to the powered by page

---

hudi-flink/src/main/java/org/apache/hudi/operator/InstantGenerateOperator.java

Change-Id: I2c2d9411c3809edfad57dea4b3f36d2db767a970
Fix error information
*(or)*
(or)
*(example:)* …

[MINOR] Fix error information in exception

---

docs/_posts/2020-11-11-hudi-indexing-mechanisms.md

[DOCS] Fix minor typos in the indexing blog

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala

This CR fixes the reading exception after updating bootstrap table with written Hudi table.
- Fixed the bug in ```HoodieBootstrapRelation.scala```
- Refactored ```TestDataSourceForBootstrap.scala``` since there are many duplicated code.
- Added test cases to cover this change.
Modfied ```TestDataSourceForBootstrap.scala``` to cover this code change.

[HUDI-1489] Fix NPE when reading updated written bootstrap table

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java

…it test
add structured streaming and delta streamer inline clustering unit test. Then async clustering can also base on the unit test
*(or)*
(or)
*(example:)* …

[HUDI-1481] add streaming and delta streamer inline clustering unit test

---

scripts/report_coverage.sh

[MINOR] Update report_coverage.sh

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java

sync UpsertPartitioner modify of HUDI-1398 to flink/java
- *Modify UpsertPartitioner in flink/java client*
- *TestUpsertPartitioner#testUpsertPartitionerWithRecordsPerBucket *

[MINOR] Sync UpsertPartitioner modify of HUDI-1398 to flink/java

---

hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaDeleteCommitActionExecutor.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaDeleteHelper.java
hudi-examples/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java

[HUDI-1423] Support delete in hudi-java-client

---

docs/_docs/2_4_configurations.cn.md
docs/_docs/2_4_configurations.md

[HUDI-913] Update docs about KeyGenerator

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkWriteHelper.java

[MINOR] Sync HUDI-1196 to FlinkWriteHelper

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala

[MINOR] fix spark 3 build for incremental query on MOR

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestHBaseIndex.java

- *An incorrect method was being used to generate a new commit with data. There were 2 startCommit()s being called which was causing rollback to fail.*
*(or)*
(or)
*(example:)* …

[HUDI-1525] Fix test hbase index

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/metadata/TestHoodieBackedMetadata.java
hudi-flink/src/test/java/org/apache/hudi/source/TestJsonStringToHoodieRecordMapFunction.java

[MINOR] Disabling problematic tests temporarily to stabilize CI

---

.travis.yml

[MINOR] Make a separate travis CI job for hudi-utilities

---

hudi-spark-datasource/hudi-spark2/pom.xml
hudi-spark-datasource/hudi-spark3/pom.xml
pom.xml

JIRA https://issues.apache.org/jira/browse/HUDI-1512
Skip unit tests of ```hudi-spark2``` when enabling spark3 profile.
Run test against Spark3:
https://travis-ci.org/github/zhedoubushishi/hudi/builds/753238199

[HUDI-1512] Fix spark 2 unit tests failure with Spark 3

---

packaging/hudi-flink-bundle/pom.xml
pom.xml

*Add back dependency org.apache.flink:flink-connector-kafka-base_2.11*
Fix 
```
java.lang.NoClassDefFoundError: org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumerBase
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at …
```

[HOTFIX] Revert upgrade flink verison to 1.12.0

---

hudi-flink/src/main/java/org/apache/hudi/operator/InstantGenerateOperator.java

…o hudi
Fix NPE when no new data in kafka using HoodieDeltaStreamer
```
java.lang.NullPointerException: Keyed state can only be used on a 'keyed stream', i.e., after a 'keyBy()' operation.
at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:75)
at org.apache.flink.streaming.api.operators.StreamingRuntimeContext.checkPreconditionsAndGetKeyedStateStore(StreamingRuntimeContext.java:223)
at org.apache.flink.streaming.api.operators.StreamingRuntimeContext.getMapState(StreamingRuntimeContext.java:216)
at org.apache.hudi.index.state.FlinkInMemoryStateIndex.<init>(FlinkInMemoryStateIndex.java:58)
at …
```

[HUDI-1453] Fix NPE using HoodieFlinkStreamer to etl data from kafka to hudi

---

doap_HUDI.rdf

[MINOR] Update doap with 0.7.0 release

---

pom.xml

[MINOR] Add Jira URL and Mailing List

---

docs/_pages/community.md

[MINOR] Updating committer role

---

hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java

*Fix typo*
*Fix typo*
*(or)*
(or)
*(example:)*

[MINOR] Fix method comment typo

---

docs/_pages/community.cn.md
docs/_pages/community.md

*Add commiter role to web site*

[MINOR] Add commiter role to web site

---

docs/_docs/0_4_docker_demo.md
docs/_docs/2_2_writing_data.md
docs/_docs/2_4_configurations.md

Fixing documentation in website for various issues. 
- Fixed run_sync_tool.sh path in docker demo
- Fixed precombine documentation
- Added more details for record_keys
- Fixed SimpleKeyGenerator path in configuration.
Built site locally and verified it.

[HUDI-1379] [HUDI-1475] [HUDI-1279] [HUDI-1235] Fixing docs wrt hive_sync path, record key description and precombine, etc.

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala

- Add test cases for INSERT_OVERWRITE operation 
- Fix minor bugs of INSERT_OVERWRITE_TABLE operation
- Fix some comment errors
- Modify test cases in `org.apache.hudi.functional.TestCOWDataSource`
- *Added integration tests for INSERT_OVERWRITE operation.*

[HUDI-1545] Add test cases for INSERT_OVERWRITE Operation

---

hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java

com.esotericsoftware.kryo.KryoException: java.lang.RuntimeException: Could not serialize lambda Serialization trace
issue tracker: https://issues.apache.org/jira/browse/HUDI-1603

[HUDI-1603] fix DefaultHoodieRecordPayload serialization failure

---

content/index.html
docs/_layouts/home.html

*This pull request adds clustering feature to the home page*
- *Add clustering feature to the home page*

[MINOR] Add clustering feature to the home page

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/datadog/TestHoodieMetricsDatadogConfig.java

[MINOR] Default to empty list for unset datadog tags property

---

README.md

*This pull request adds clustering to feature list*
- *Add clustering to feature list*

[MINOR] Add clustering to feature list

---

docs/_docs/0.7.0/2_1_overview.md
docs/_docs/2_1_overview.md

MOR table will have new records updated before COW table.
But once the records are in COW table, the query execution time against COW will be faster than the query execution time against MOR table

[MINOR][DOCS] Add query latency trade-off for COW vs MOR

---

docs/_posts/2021-02-13-hudi-key-generators.md

* Adding a blog for KeyGenerators in Apache Hudi
- *Adding a blog for KeyGenerators in Apache Hudi*
Verified locally

[HUDI-1617] Adding a blog for KeyGenerators in Apache Hudi

---

docs/_posts/2020-11-11-hudi-indexing-mechanisms.md
docs/_posts/2021-01-27-hudi-clustering-intro.md
docs/_posts/2021-02-13-hudi-key-generators.md

Fixing authors for blogs
- Fixing authors for blogs
Tested locally. Clustering blog does not render sathish's name since it has "." in between. but fixing with his apache id for now.

[MINOR] Fixing authors for blogs

---

azure-pipelines.yml
pom.xml

Use a separate maven profile `azp-unit-tests` to exclude some failing tests in Azure pipelines.

[HUDI-393] Add azure pipelines configs

---

hudi-integ-test/README.md

* Fixing Hudi Test suite readme for long running job
- Fixing Hudi Test suite readme for long running job
- Verified by running a job locally.

[MINOR] Fixing Hudi Test suite readme for long running job

---

docs/_docs/1_4_powered_by.md

*Adding Hudi Learning series presentation & Uber eng blog links*

[HUDI 1642] Adding Hudi Learning series presentation & Uber eng blog links

---

docs/_docs/1_4_powered_by.md

[MINOR] Fixing slideshare link

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestWriteStatus.java
hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePayloadProps.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
hudi-common/src/main/java/org/apache/hudi/common/util/DateTimeUtils.java
hudi-common/src/test/java/org/apache/hudi/common/model/TestDefaultHoodieRecordPayload.java
hudi-common/src/test/java/org/apache/hudi/common/util/TestDateTimeUtils.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala

Cache min and max of event time in each commit and compute the latency and freshness metrics.

[HUDI-1587] Add latency and freshness support

---

docs/_docs/0_4_docker_demo.cn.md

Fix docs hive_sync path
*(or)*
(or)
*(example:)*

[DOCS] Fix docs hive_sync path

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java

*This PR fixes a bug to ensure that pending compaction & clustering operations are always excluded when performing inflight rollbacks*

[HUDI-1660] Excluding compaction and clustering instants from inflight rollback

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
hudi-flink/src/main/java/org/apache/hudi/operator/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/operator/StreamReadMonitoringFunction.java
hudi-flink/src/main/java/org/apache/hudi/operator/StreamReadOperator.java
hudi-flink/src/main/java/org/apache/hudi/sink/HoodieTableSink.java
hudi-flink/src/main/java/org/apache/hudi/source/HoodieTableSource.java
hudi-flink/src/main/java/org/apache/hudi/source/format/FilePathUtils.java
hudi-flink/src/main/java/org/apache/hudi/source/format/mor/InstantRange.java
hudi-flink/src/main/java/org/apache/hudi/source/format/mor/MergeOnReadInputFormat.java
hudi-flink/src/main/java/org/apache/hudi/source/format/mor/MergeOnReadInputSplit.java
hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamerV2.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-flink/src/test/java/org/apache/hudi/operator/utils/TestConfigurations.java
hudi-flink/src/test/java/org/apache/hudi/operator/utils/TestData.java
hudi-flink/src/test/java/org/apache/hudi/source/HoodieDataSourceITCase.java
hudi-flink/src/test/java/org/apache/hudi/source/TestHoodieTableSource.java
hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadMonitoringFunction.java
hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadOperator.java
hudi-flink/src/test/java/org/apache/hudi/source/format/TestInputFormat.java
hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java
hudi-flink/src/test/java/org/apache/hudi/utils/factory/CollectSinkTableFactory.java
hudi-flink/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
hudi-flink/src/test/resources/test_source2.data

Support streaming read for HUDI Flink MOR table.
*(or)*
(or)
*(example:)*

[HUDI-1663] Streaming read for Flink MOR table

---

hudi-flink/src/main/java/org/apache/hudi/operator/transform/RowDataToHoodieFunction.java
hudi-flink/src/test/java/org/apache/hudi/operator/TestWriteCopyOnWrite.java
hudi-flink/src/test/java/org/apache/hudi/operator/utils/TestData.java
hudi-flink/src/test/java/org/apache/hudi/source/HoodieDataSourceITCase.java
hudi-flink/src/test/java/org/apache/hudi/source/TestHoodieTableSource.java
hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadMonitoringFunction.java
hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadOperator.java
hudi-flink/src/test/java/org/apache/hudi/source/format/TestInputFormat.java

Support row level delete for HUDI sink. With this feature, we can consume the records from CDC and make snapshot table in HUID format.
*(or)*
(or)
*(example:)*

[HUDI-1678] Row level delete for Flink sink

---

docs/_docs/1_4_powered_by.md

Adding  "Data Lakehouse: Building the Next Generation of Data Lakes using Apache Hudi".
Link: https://medium.com/slalom-build/data-lakehouse-building-the-next-generation-of-data-lakes-using-apache-hudi-41550f62f5f

Adding "Data Lakehouse: Building the Next Generation of Data Lakes using Apache Hudi"

---

docs/_config.yml
docs/_data/navigation.yml
docs/_docs/0_3_migration_guide.cn.md
docs/_docs/0_3_migration_guide.md
docs/_docs/1_1_spark_quick_start_guide.cn.md
docs/_docs/1_1_spark_quick_start_guide.md
docs/_docs/1_6_flink_quick_start_guide.md
docs/_docs/2_2_writing_data.md
docs/_docs/2_3_querying_data.md
docs/_docs/2_4_configurations.md
docs/_layouts/home.html
docs/_pages/contributing.cn.md
docs/_pages/contributing.md
docs/_pages/releases.md

[HUDI-1693] Add document about HUDI Flink integration

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala

fix the bug that hudi cannot uncache rdds correctly
now， hudi improve write performance by cache necessary rdds； however when the write operation is finnished， those cached rdds have not been uncached which waste lots of memory.
https://github.com/apache/hudi/blob/master/hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java#L115
https://github.com/apache/hudi/blob/master/hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java#L214
In our environment：
step1： insert 100GB data into hudi table by spark   （ok）
step2： insert …

[HUDI-1688] Uncache Rdd once write operation is complete

---

docs/_data/navigation.yml
docs/_docs/2_4_configurations.md
docs/_docs/2_9_concurrency_control.md

[HUDI-1679] Concurrency Control in Hudi

---

hudi-common/src/main/java/org/apache/hudi/common/config/LockConfiguration.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java

*Standardize configs under the same name for hoodie write configs*

[HUDI-1712] Rename & standardize config to match other configs

---

hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java

[hotfix] Log the error message for creating table source first

---

docs/_docs/2_9_concurrency_control.md

[HUDI-1713] Updating config name for concurrency

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
hudi-spark-datasource/hudi-spark2/pom.xml
hudi-spark-datasource/hudi-spark3/pom.xml
hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
pom.xml

[HOTFIX] fix spark session leak in FunctionalTestHarness

---

pom.xml

[HOTFIX] Disable ITs for Spark3 and scala2.12

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBaseBloomIndex.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBaseBloomIndexCheckFunction.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/index/FlinkHoodieIndex.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/index/JavaHoodieBloomIndex.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/index/JavaHoodieIndex.java

[HUDI-1478] Introduce HoodieBloomIndex to hudi-java-client

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
hudi-spark-datasource/hudi-spark2/pom.xml
hudi-spark-datasource/hudi-spark3/pom.xml
hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
pom.xml
scripts/release/deploy_staging_jars.sh

[HOTFIX] Cherry pick 0.8.0 release fix to master

---

docker/demo/config/test-suite/test.properties
scripts/release/validate_staged_release.sh

[MINOR] Add Missing Apache License to test files

---

docs/_docs/2_9_concurrency_control.md

[MINOR] Fix concurrency docs based on recent changes

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java

* This pull request extracts common method to improve code reuse.*
- *Extract common method in HoodieCreateHandle & FlinkCreateHandle*
This pull request is a  code cleanup without any test coverage.

[HUDI-1737][hudi-client] Code Cleanup: Extract common method in HoodieCreateHandle & FlinkCreateHandle

---

docs/_docs/0_4_docker_demo.md

Minor corrections in the docker-demo page I observed while going through them. 
*(or)*
(or)
*(example:)*

[MINOR] minor corrections in docker-demo page

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCleaner.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java

Fix hung bug for clean/compaction/rollback command when operation fail.
verify the fix manually

[HUDI-1749] Clean/Compaction/Rollback command maybe never exit when operation fail

---

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCompactionCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCompactionCommand.java
hudi-cli/src/test/java/org/apache/hudi/cli/testutils/AbstractShellIntegrationTest.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/CompactionAdminClient.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiveLog.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java

*1. Fix CompactionCommand*
*2.  add unit test for CompactionCommand*
- *Fix CompactionCommand and add unit test for CompactionCommand*

[HUDI-699] Fix CompactionCommand and add unit test for CompactionCommand

---

content/docs/configurations.html

[MINOR] Correct logFileDataBlockMaxSize description

---

doap_HUDI.rdf

[MINOR] Update doap with 0.8.0 release

---

docs/_pages/releases.md

[DOCS]Fix 0.8.0 release doc link

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java

[HUDI-1775] Add option for compaction parallelism

---

docs/_docs/0.8.0/2_4_configurations.md
docs/_docs/0.8.0/2_9_concurrency_control.md
docs/_docs/2_4_configurations.md
docs/_docs/2_9_concurrency_control.md

[MINOR] Fix concurrency docs

---

hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java

add support for huawei cloud object stroage
*(or)*
(or)
*(example:)*

[HUDI-1783] Support Huawei Cloud Object Storage

---

docs/_docs/0.7.0/2_3_querying_data.cn.md
docs/_docs/0.7.0/2_3_querying_data.md
docs/_docs/0.8.0/2_3_querying_data.cn.md
docs/_docs/0.8.0/2_3_querying_data.md
docs/_docs/2_3_querying_data.cn.md
docs/_docs/2_3_querying_data.md

[DOC] update query matrix

---

hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java

[Hotfix][javadocs] fix typo.

---

hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/converter/DeleteConverter.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/DagUtils.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/scheduler/DagScheduler.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/scheduler/SaferSchemaDagScheduler.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/DeleteGeneratorIterator.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/DeltaGenerator.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/FlexibleSchemaRecordGenerationIterator.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/GenericRecordFullPayloadGenerator.java
hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/writer/DFSDeltaWriterAdapter.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/HoodieTestHiveBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/converter/TestDeleteConverter.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/converter/TestUpdateConverter.java
hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalTable.java

Remove unused imports and some other checkstyle issues mainly in `hudi-integ-test` module

[MINOR] Remove unused imports and some other checkstyle issues

---

docs/_docs/1_6_flink_quick_start_guide.md
docs/_docs/2_3_querying_data.md
docs/_docs/2_4_configurations.md

[HUDI-1782] Add more options for HUDI Flink

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java

[HUDI-1786] Add option for merge max memory

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/checkpointing/InitialCheckpointFromAnotherHoodieTimelineProvider.java

[Hotfix][utilities] Optimized codes

---

docs/_docs/2_4_configurations.md

Fixed typo in documentation for configurations

Fixed typo in documentation for configurations

---

packaging/hudi-presto-bundle/pom.xml

Add jackson module to Presto bundle and shade it. 
Without this, presto is throwing NoClassDefFoundError for jackson modules.
Tagging it as minor. Happy to create a ticket if you think its needed.
This change is deployed to internal presto clusters

[MINOR] Add jackson module to presto bundle

---

hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java

[MINOR][hudi-sync] Fix typos

---

packaging/hudi-timeline-server-bundle/pom.xml

Fix https://issues.apache.org/jira/browse/HUDI-1802
Add `com.esotericsoftware` package to `hudi-timeline-server-bundle` pom.xml
Have tested in a standalone hudi timeline server.

 [HUDI-1802] Timeline Server Bundle need to include com.esotericsoftware package

---

docs/_posts/2021-02-13-hudi-key-generators.md

*Fixing key generators blog content*
- *Modify contents of Key generators blog*
N/A. Only text changes.

[MINOR] Fixing key generators blog content

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java
hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java

[HUDI-1814] Non partitioned table for Flink writer

---

hudi-common/src/main/java/org/apache/hudi/exception/TableNotFoundException.java

*Expose the detailed exception object for table not found*
- *Expose the detailed exception object for table not found*

[MINOR] Expose the detailed exception object for table not found

---

README.md
docs/_data/navigation.yml
docs/_pages/download.cn.md
docs/_pages/download.md
docs/_pages/older_releases.cn.md
docs/_pages/older_releases.md

Add the download page to the asf site
Added download.md and add download tab on the navigation bar.
Built the site locally. Tested on chrome and safari.

[HUDI-1769]Add download page to the site

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java

[MINOR] Remove redundant method-calling.

---

hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/HoodieDLAClient.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/AbstractSyncHoodieClient.java

[Hotfix][hudi-sync] Refactor method up to parent-class

---

packaging/hudi-flink-bundle/pom.xml

*Fix cannot create table due to jar conflict*
- *Modify packaging/hudi-flink-bundle/pom.xml*
* This pull request is already covered by existing tests, such as *(please describe tests)*.

[HUDI-1858] Fix cannot create table due to jar conflict

---

docs/_docs/1_6_flink_quick_start_guide.md

[MINOR] minimize flink quick start resource

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunction.java
hudi-flink/src/main/java/org/apache/hudi/source/StreamReadOperator.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
hudi-flink/src/test/java/org/apache/hudi/sink/transform/TestRowDataToHoodieFunction.java
hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java

[HUDI-1863] Add rate limiter to Flink writer to avoid OOM for bootstrap

---

docs/_docs/2_4_configurations.md

[HUDI-1853] Add flink index and compaction options to document

---

hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java

[HUDI-1811] Fix TestHoodieRealtimeRecordReader (Azure CI)

---

azure-pipelines.yml

[HUDI-1810] Fix azure setting for integ tests (Azure CI)

---

hudi-cli/src/main/scala/org/apache/hudi/cli/SparkHelpers.scala
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriterFactory.java

*Wiring in Hadoop Conf with AvroSchemaConverters instantiation
- *Wiring in Hadoop Conf with AvroSchemaConverters instantiation
Trivial enough patch. User confirmed that the patch worked.

[HUDI-1876] Wiring in Hadoop Conf with AvroSchemaConverters instantiation

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java
hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java

[HUDI-1886] Avoid to generates corrupted files for flink sink

---

docker/demo/config/test-suite/templates/clustering.yaml.template
docker/demo/config/test-suite/templates/long-running.yaml.template
docker/demo/config/test-suite/templates/spark_command.txt.template
docker/demo/config/test-suite/templates/test.properties.template
docker/generate_test_suite.sh

*Automate suite of tests suites w/ docker and integ test
- *Added templates and script to automate tests w/ integ test suite job in docker*
Ran locally to verify
./generate_test_suite.sh 
./generate_test_suite.sh --include_cluster_yaml true
./generate_test_suite.sh --num_iterations 50 --intermittent_delay_mins 1 --table_type MERGE_ON_READ

[HUDI-1851] Automate suite of tests suites w/ docker and integ test

---

docs/_docs/0.6.0/2_4_configurations.md
docs/_docs/0.7.0/2_4_configurations.md
docs/_docs/0.8.0/2_4_configurations.md
docs/_docs/2_4_configurations.md

Fixing some of the configs. part of HUDI-1769 is part of this PR. ConsistencyGuardConfig will take it up in a diff PR. 
*(or)*
(or)
*(example:)*

[HUDI-1769] Fixing some of the configs in configuration page

---

docs/_config.yml
docs/_docs/0.8.0/1_1_spark_quick_start_guide.cn.md
docs/_docs/0.8.0/1_1_spark_quick_start_guide.md
docs/_docs/1_1_spark_quick_start_guide.cn.md
docs/_docs/1_1_spark_quick_start_guide.md
docs/_pages/community.cn.md

Fix incorrect links and wrong avro version.
update community page to reflect new committers pmcs.
Build locally

[DOCS] fix incorrect info and update community page

---

hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java

[MINOR][hudi-client] Code-cleanup,remove redundant variable declarations

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala

*Honoring skipROSuffix in spark ds
- Honoring skipROSuffix in spark ds
- Tested via HoodieSparkSqlWriterSuite.Test build sync config for spark sql

[HUDI-1806] Honoring skipROSuffix in spark ds

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkMergeOnReadTable.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/rollback/FlinkMergeOnReadRollbackActionExecutor.java
hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java

[HUDI-1915] Fix the file id for write data buffer before flushing

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java
packaging/hudi-flink-bundle/pom.xml

[HUDI-1871] Fix hive conf for Flink writer hive meta sync

---

hudi-common/src/main/java/org/apache/hudi/common/engine/EngineType.java

[MINOR] Update the javadoc of EngieType

---

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala

* Fix Bulk insert with row supports MoR table.
*(or)*
(or)
*(example:)*
cc @nsivabalan PTAL.

[HUDI-1922] Bulk insert with row writer supports mor table

---

hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlQueryBasedTransformer.java

[HUDI-1940] Add SqlQueryBasedTransformer unit test

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java

[MINOR] 'return' is unnecessary as the last statement in a 'void' method

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java

fix the grammer err of the comment in the HoodieTableMetaClient
fix the grammer err of the comment in the HoodieTableMetaClient

[MINOR] fix the grammer err of the comment in the HoodieTableMetaClient

---

packaging/hudi-flink-bundle/pom.xml

[HUDI-1948] Shade kryo-shaded jar for hudi flink bundle

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java

[MINOR] The collection can use forEach() directly

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HeartbeatUtils.java

[MINOR] Access the static member getLastHeartbeatTime via the class instead

---

hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java

[HUDI-1943] Lose properties when hoodieWriteConfig initializtion

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java

[HUDI-1921] Add target io option for flink compaction

---

packaging/hudi-flink-bundle/pom.xml

The purpose of this PR is to support the Flink writer hive3 metastore synchronization and fix the kryo package conflict problem, as a follow-up PR of HUDI-1871 #2968, which support Flink writer hive2 meta sync. 
*(or)*
(or)
*(example:)*
- *Added …

[HUDI-1952] Fix hive3 meta sync for flink writer

---

hudi-common/src/main/java/org/apache/hudi/exception/HoodieException.java

[MINOR] Remove the implementation of Serializable from HoodieException

---

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java

*Remove unused method org.apache.hudi.DataSourceUtils#createDateTimeParser*
`org.apache.hudi.DataSourceUtils#createDateTimeParser` has been replaced by
`org.apache.hudi.keygen.KeyGenUtils#createDateTimeParser`
*(or)*
(or)
*(example:)*
- *Added …

[MINOR] Remove unused method in DataSourceUtils

---

hudi-sync/hudi-dla-sync/pom.xml
packaging/hudi-flink-bundle/pom.xml
packaging/hudi-integ-test-bundle/pom.xml
pom.xml

Fixes #160 #2479
*(or)*
(or)
*(example:)*

[MINOR] Resolve build issue arising from inaccessible pentaho jar

---

hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java

*jira: https://issues.apache.org/jira/browse/HUDI-1954*
*(or)*
(or)
*(example:)*

[HUDI-1954] Only reset bucket when flush bucket success

---

hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java

Log the warning instead of throwing Runtime exception if files does not exist
- Adding a warn log and returning in case there are no files

[HUDI-1909] Skip Commits with empty files

---

hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java

Remove Hadoop configuration log because it prints a lot of times in the log and does not add value while debugging as well
Remove Log statement

[HUDI-1148] Remove Hadoop Conf Logs

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandle.java

[HUDI-1986] Skip creating marker files for flink merge handle

---

hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java
hudi-flink/src/main/java/org/apache/hudi/table/format/FilePathUtils.java
hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java

[HUDI-1987] Fix non partition table hive meta sync for flink writer

---

docs/_docs/0_9_bos_filesystem.cn.md
docs/_docs/0_9_bos_filesystem.md
docs/_docs/2_7_cloud.cn.md
docs/_docs/2_7_cloud.md

Add Baidu BOS storage support for hudi,
*(or)*
(or)
*(example:)*

[HUDI-1993]Add Baidu BOS storage support for hudi

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java

[HUDI-1992] Release the new records map for merge handle #close

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java

[MINOR] Remove boxing

---

hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java

Add Baidu BOS storage support for hudi
the pr of the docs is  : https://github.com/apache/hudi/pull/3057 
*(or)*
(or)
*(example:)*

[HUDI-1993] Add Baidu BOS storage support for hudi

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java

[HUDI-1994] Release the new records iterator for append handle #close

---

hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java

[MINOR] Add Tencent Cloud HDFS storage support for hudi

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HiveIncrementalPuller.java

*Modify the log level to ERROR, which is convenient for users to troubleshoot problems*
*(or)*
(or)
*(example:)*

[HUDI-2002] Modify HiveIncrementalPuller log level to ERROR

---

docs/_docs/2_4_configurations.md

Update the documentation to add a note for setting HIVE_AUTO_CREATE_DATABASE 
Updated configurations.html to add note

[HUDI-1997] Adding Note for explicitly setting HIVE_AUTO_CREATE_DATABASE

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java

*The file writer can be release eagerly to save the memory footprint.*
*(or)*
(or)
*(example:)*

[HUDI-2000] Release file writer for merge handle #close

---

README.md
azure-pipelines.yml
hudi-common/src/test/java/org/apache/hudi/common/util/TestParquetUtils.java
pom.xml

[HUDI-1950] Fix Azure CI failure in TestParquetUtils

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java

*release writer for append handle #close*
*(or)*
(or)
*(example:)*

[HUDI-2022] Release writer for append handle #close

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java

[HUDI-2008] Add an annotation to suppress the compiler warnings

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/RowKeyGeneratorHelper.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeUnmergedRecordReader.java

[MINOR] Fix Javadoc wrong references

---

scripts/release/generate_jar_path.py

[MINOR] Remove unuse module

---

hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java

[HUDI-2054] Remove the duplicate name for flink write pipeline

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/metadata/TestHoodieBackedMetadata.java

[HUDI-2064] Fix TestHoodieBackedMetadata#testOnlyValidPartitionsAdded

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/DefaultSource.scala

The test case `HoodieSparkSqlWriterSuite(test schema evolution for xx) `often crash because currently we have not specify the right schema to the `DataSource.apply` in `DefaultSource#getBaseFileOnlyView`. In this case, the parquet file format will choose one of the parquet file's schema as the table schema which may not the latest schema for evolution.
- Specify the latest schema to the `DataSource.apply`.
*(or)*
(or)
*(example:)* …

[HUDI-2061] Incorrect Schema Inference For Schema Evolved Table

---

hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java

[MINOR] Remove unused methods in StreamUtil

---

hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java

[MINOR] Drop duplicate keygenerator class configuration setting

---

hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/util/TestHiveSchemaUtil.java

[HUDI-2081] Move schema util tests out from TestHiveSyncTool

---

docs/_docs/2_9_concurrency_control.md

*Adding caveat for multiwriter*

[MINOR] Add caveat for multiwriter usage

---

hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java

Add rebalance before index bootstrap.
*(or)*
(or)
*(example:)*

[HUDI-2103] Add rebalance before index bootstrap

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java

[MINOR] Fix broken build due to FlinkOptions

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java

[MINOR] Add Documentation to KEYGENERATOR_TYPE_PROP

---

hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java

[HUDI-2121] Add operator uid for flink stateful operators

---

packaging/hudi-flink-bundle/pom.xml

Support hive1 metadata sync for flink writer. If user use hive1 to sync metadata from hudi to hive1, he just need to add profile while install.
*(or)*
(or)
*(example:)* …

[HUDI-2133] Support hive1 metadata sync for flink writer

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java
hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java

[HUDI-2135] Add compaction schedule option for flink

---

hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/functional/TestHiveMetastoreBasedLockProvider.java

[MINOR] Fix build broken from #3186

---

hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java

*Fix some wrong assert reasons*
- *Fix some wrong assert reasons*

[MINOR] Fix some wrong assert reasons

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BucketType.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkAppendHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java

[HUDI-2087] Support Append only in Flink stream

---

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java

[HUDI-2171] Add parallelism conf for bootstrap operator

---

hudi-flink/src/main/java/org/apache/hudi/sink/transform/ChainedTransformer.java
hudi-flink/src/main/java/org/apache/hudi/sink/transform/Transformer.java
hudi-flink/src/main/java/org/apache/hudi/streamer/ChainedTransformer.java
hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-flink/src/test/java/org/apache/hudi/sink/StreamWriteITCase.java

*This pull request supports transformer feature for HoodieFlinkStreamer*
- *Support Transformer for HoodieFlinkStreamer*
- *StreamWriteITCase#testTransformerBeforeWriting*
- *StreamWriteITCase#testChainedTransformersBeforeWriting*

[HUDI-2165] Support Transformer for HoodieFlinkStreamer

---

hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestParquet2SparkSchemaUtils.java

[HUDI-2180] Fix Compile Error For Spark3

---

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/GlobalHiveSyncTool.java

*Refactor hive sync tool to reduce duplicate code*
- *Refactor hive sync tool to reduce duplicate code*

[MINOR] Refactor hive sync tool to reduce duplicate code

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/HoodieWriteCommitCallback.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/client/http/HoodieWriteCommitHttpCallbackClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/common/HoodieWriteCommitCallbackMessage.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/impl/HoodieWriteCommitHttpCallback.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/kafka/HoodieWriteCommitKafkaCallback.java

Currently, we need to know which partitions hudi has successfully written.
org.apache.hudi.client.AbstractHoodieWriteClient

[HUDI-1633] Make callback return HoodieWriteStat

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BucketType.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkAppendHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java

This reverts commit 783c9cb3
*(or)*
(or)
*(example:)*

Revert "[HUDI-2087] Support Append only in Flink stream (#3252)"

---

docs/_docs/1_4_powered_by.md

Updating more talks to our website
*(or)*
(or)
*(example:)*

[MINOR] Update talks to site

---

docs/_pages/community.cn.md
docs/_pages/community.md

Update committer and PMC list
- Update committer and PMC list
Built the site locally

[DOC] Update committer and PMC list

---

docs/_docs/1_4_powered_by.md

[MINOR] Adding more talk links and articles to site
