hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestFiltersInFileGroupReader.java

reduced number of inserts/updates (from 100000/20000 to 100/20);  
While running testFiltersInFileFormat locally:  
before: [true] - 1,26min, [false] - 1,01min;  
after: [true] - 37sec, [false] - 23 sec.  
none
none

[HUDI-7849] Reduce time spent on running testFiltersInFileFormat

---

hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncTool.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java

Unless the tables in bigquery metastore are explicitly deleted & recreated, updates to basepath don't come into effect. Through these changes, any updates in table base path would be identified and the same will updated in bigquery metastore without having to delete & recreate it.
Any updates in table base path would be identified and the same will updated in bigquery metastore without having to delete & recreate it.
Low
NA

[HUDI-7881] Verify table base path as well for syncing table in bigquery metastore

---

.github/workflows/bot.yml
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-examples/hudi-examples-common/pom.xml
hudi-examples/hudi-examples-java/pom.xml
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java

This PR adds support for compiling Hudi on Java 11 for engines like Spark and Flink that support Java 11 and 17.  Detailed changes:
- Fixes compilation errors on Java 11; maintains the code to be compilable on Java 8.
- Adds new GitHub CI jobs on validating Hudi built by Java 11, by running the tests on Spark 3.5 with Java 17 runtime.  These are moved from existing CI jobs validating Hudi built by Java 8.  The tests on Spark 3.3 and 3.4 still run with Java 8 compilation and Java 17 runtime. 
Kudos to @Zouxxyy for contributing to this PR from #9300.
Makes Hudi compilable on Java 11.
none
Docs on Java 11 compilation support.

[HUDI-6508] Support compilation on Java 11

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala

DataSet.ofRows will create new QueryExecution, which is not registered, so the dag metric will not update when running job
None
None
None

[HUDI-5956] fix spark DAG ui when write

---

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
hudi-aws/src/test/java/org/apache/hudi/aws/testutils/GlueTestUtil.java

Updated AwsGlueCatalogSyncClient to add comment to the FieldSchema returned getMetastoreFieldSchemas method.
- getMetastoreFieldSchemas now return returns FieldSchema with comments, which can be used for sync if required. 
None

[HUDI-7909] Add Comment to the FieldSchema returned by Aws Glue Client

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMetrics.java

For some of the metrics type like duration we are using incrementMetric instead of setMetric.
Also some of the redundant metrics are removed. For example a count type metric has both count and duration metric getting pushed even though duration is not calculated.
File lookup count metric is added for bloom filter and column stat
NA
low
NA

[HUDI-7395] Fix computation for metrics in HoodieMetadataMetrics

---

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java

This PR adds a test case for batch clean in Flink.
New test.
none
none

[HUDI-4945] Add a test case for batch clean.

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/SqlFileBasedTransformer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/SqlQueryBasedTransformer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlQueryBasedTransformer.java

Removed checks in apply method of SqlQueryBasedTransformer and SqlFileBasedTransformer.  
`getStringWithAltKeys` never returns `null`, if there is no config in properties - it throws IllegalArgumentExceprion (property xxx not found), so null-checking of the result is unreachable (useless) here.
none
none
none

[MINOR] Removed useless checks from SqlBasedTransformers

---

pom.xml

I got errors like
```
java.io.IOException: Failed to delete temp directory /tmp/junit*****
```
from time to time. The last time was on `ITTestConsistentBucketStreamWrite#testWriteMOR`. There `@TempDir` is used.
I suppose the problem could be fixed by this change: https://github.com/junit-team/junit5/pull/2624. There `@TempDir` cleanup resets readable and executable permissions of the root temporary directory and any contained directories instead of failing to delete them.
To integrate this change we could bump JUnit version to 5.8.2. For proper tests discovering, `junit.platform.version` also should be bumped to 1.8.2.
Only on tests run, which would be checked.
None
No need

[MINOR] `@TempDir` fails to cleanup temporary directory

---

.github/workflows/bot.yml
hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java
hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/JavaScalaConverters.scala
scripts/release/deploy_staging_jars.sh
scripts/release/validate_staged_bundles.sh

This PR adds the Hudi CLI bundle for Scala 2.13:
- Fixes build failure of `hudi-cli` module on Scala 2.13
- Updates CI script to validate the CLI bundle build on Scala 2.13
- Updates release scripts on the new bundle `hudi-cli-bundle_2.13`
Tested locally that the commits, archival, and compaction commands work with `hudi-cli-bundle_2.13` on Spark 3.5 and Scala 2.13.
Hudi CLI bundle support on Scala 2.13.
none
Docs will be updated by [HUDI-7923](https://issues.apache.org/jira/browse/HUDI-7923).

[HUDI-7922] Add Hudi CLI bundle for Scala 2.13

---

hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala

Before this MR for `TimestampBasedKeyGenerator` we got
```
Failed to cast value `2004-02-29 01` to `LongType` for partition column `ts`
```
when we read data by Spark SQL.
`listPartitionPaths()` is called with `parsePartitionColumnValues()`, and we got ClassCastException during parsing of partition paths. But we couldn't reconstruct partition column values from partition paths when `TimestampBasedKeyGenerator` of `SCALAR`, `UNIX_TIMESTAMP` or `EPOCHMILLISECONDS` types is used, due to lost information after corresponding processing of values.
This MR fixes ClassCastException, but there are still not finished separate tasks (old ones) mentioned in the added `TestSparkSqlWithTimestampKeyGenerator`:
- Fix for [HUDI-3896] overwrites `shouldExtractPartitionValuesFromPartitionPath` in …

[HUDI-7709] ClassCastException while reading the data using `TimestampBasedKeyGenerator`

---

hudi-common/src/main/avro/HoodieMetadata.avsc
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java

RLI should save the record position so that can be used in the index lookup. This PR adds a position field in the RLI metadata to track the same.
NA
low
NA

[HUDI-7877] Add record position to record index metadata payload

---

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncTool.java
hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/metrics/HoodieMetaSyncMetrics.java
hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/metrics/TestHoodieMetaSyncMetrics.java

Added latency and failure metrics for recreate table on meta sync failure.
- Results in pushing new metrics to prometheus which helps in monitoring the performance of recreating table.
None

[HUDI-7924] Capture Latency and Failure Metrics For Hive Table recreation

---

doap_HUDI.rdf

Fix the syntax of the project's DOAP description
whatever generates https://projects.apache.org/json/projects/hudi.json and https://projects.apache.org/project.html?hudi should start working again
none
n/a

[MINOR] doap: don't nest multiple versions in a release

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala

HoodieFileGroupReader failed if preCombine and partition fields are the same with IllegalArgumentException: `Field: ts does not exist in the table schema`. precombineField is required but it was filtered from dataSchema as other partition fields.  
To fix this I made `HoodieFileGroupReaderBasedParquetFileFormat` do not filter partitionColumn from dataSchema if it is the same as preCombine field.
none
none
none

[HUDI-7908] HoodieFileGroupReader fails if preCombine and partition fields are the same

---

hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/SyncableFileSystemView.java

Closing fsview in HoodieTableFileIndex
Avoid memory leaks w/ FileIndex
low

[HUDI-7921] Closing fsview in HoodieTableFileIndex

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala

This PR fixes the skipping using storage partition stats index with sql. Previously, the issue was not caught in tests because it did not assert the skipping. Though there were no correctness issues, but queries were just as slow as without the index. Added more tests and validations to ensure the skipping indeed happens.
Efficient data skipping using storage partition stats index.
low …

[HUDI-7903] Fix storage partition stats index to skip data

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java

SmallFileAssignState#totalUnassigned means the total number of records, but the variable name 'totalUnassigned' has a significant meaning. It should be changed to 'total'.
none
none
none

[HUDI-7942] Fix SmallFileAssignState#totalUnassigned naming error

---

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java

Update HiveSyncTool to recreate table when hoodie basepath changes
- recreating the glue/hive table when the hoodie base path doesn't match the glue/hive table location.
Low. recreate table is not an atomic operation. It can leave the table in an inconsistent state. Chances of that happening are very low. And have alerts added for monitoring.
NA

[HUDI-7933] Sync table in Glue/HMS if table base path is updated

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/SecondaryIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBloomFiltersIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDataSkippingQuery.scala

dataskipping failure mode should be strict in test. if use fallback mode default, the query ut is meaningless.
There may be other codes that have been introduced into bugs but cannot be measured.
change:
- query index use dataskipping strick mode 
- bucket query index add required parameters
None
none
none

[HUDI-7926] dataskipping failure mode should be strict in query test

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala

While writing the Hudi table in spark, I want to sync the table to Glue.
However, the sync mode: `"hoodie.datasource.hive_sync.mode": "glue"` is actually not applicable in spark.
It instead works using this setting: `"hoodie.meta.sync.client.tool.class": "org.apache.hudi.aws.sync.AwsGlueCatalogSyncTool"`.
I believe that the former config offers a better developer experience and is rather cheap to implement. Raising the PR for same as well.
Some spark code might spurious hoodie option of `"hoodie.datasource.hive_sync.mode": "glue"` but is actually writing to some other hive metastore. The behavior might start breaking.
na
"none"

[MINOR] if sync mode is glue, fix the sync tool class

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java

- Only considers files in Hudi partitions for MDT to avoid any parsing issues
- Avoids runtime exceptions trying to parse information from file paths
None

[HUDI-7758] Only consider files in Hudi partitions when initializing MDT

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
packaging/hudi-aws-bundle/pom.xml

Hudi 0.15 added some Hudi classes with avro usages (e.g. `ParquetTableSchemaResolver`), also had `hudi-aws-bundle `depend on `hudi-hadoop-common`.  `hudi-aws-bundle` won't relocate avro classes to be compatible with hudi-spark.
The issue would happen when using hudi-flink-bundle with hudi-aws-bundle. hudi-flink-bundle has relocated avro classes and would cause class conflict:
```
java.lang.NoSuchMethodError: 'org.apache.parquet.schema.MessageType org.apache.hudi.common.table.ParquetTableSchemaResolver.convertAvroSchemaToParquet(org.apache.hudi.org.apache.avro.Schema, org.apache.hadoop.conf.Configuration)'
```
none
low
- _The config description must be updated if …

[HUDI-7951] Fix conflict caused by classes using avro in hudi-aws-bundle

---

hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/util/FileFormatUtils.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/test/java/org/apache/hudi/common/util/TestBaseFileUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDataSkippingQuery.scala

This PR fixes the partition and file pruning using `PARTITION_STATS` index in Spark.
Before this fix, when there were more than one base file in a table partition, the corresponding `PARTITION_STATS` index record in the metadata table contained `null` as the `file_path` field in `HoodieColumnRangeMetadata`.  The `null` causes `NPE` when loading the column stats per partition from `PARTITION_STATS` index (see the stacktrace at the end).  Also, the current implementation of `PartitionStatsIndexSupport` assumes that the `file_path` field contains the exact file name and it does not work if the the file path is filled as `null`.
To fix the problem, the following changes are made:
- The relative partition path is filled into the `file_path` field of the `PARTITION_STATS` index record using …

[HUDI-7945] Fix partition pruning using PARTITION_STATS index in Spark

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/SecondaryIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

When there are no log files in index, then the lookup returns no secondary keys or candidate files, because of a bug - `logRecordsMap` is empty in this code and base file records are ignored - https://github.com/apache/hudi/blob/70f44efe298771fcef9d029820a9b431e1ff165c/hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java#L970
Even though current tests for pruning asserts the filtered files count < total data files count. It is weak in the sense that it does not filtered files count > 0, and hence the assertion passed even when filtered files count = 0. This PR fixes the code and the test. The test without the change in `HoodieBackedTableMetadata` will fail. With the change, we also see number of files getting scanned is lesser (without the change, number of …

[HUDI-7954] Fix data skipping with secondary index when there are no log files

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndex.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java

1) HoodieActiveTimeline#createNewInstant 
Delete the incorrect comment "Create the in-flight file". The parameter HoodieInstant of createNewInstant can be request or infight, not just inflight.
2) HoodieActiveTimeline#deleteInstantFile
deleteInstantFile parameter HoodieInstant not only infight commit.
3) HoodieActiveTimeline#revertCompleteToInflight
Same reason as above.
none
none
none

[HUDI-7953] Improved the variable naming and formatting of HoodieActiveTimeline and HoodieIndex

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystPlansUtils.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystPlanUtils.scala
hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/HoodieSpark30CatalystPlanUtils.scala
hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystPlanUtils.scala
hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystPlanUtils.scala
hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/ResolveInsertionBase.scala
hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystPlanUtils.scala
hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/HoodieSpark34CatalystPlanUtils.scala
hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/HoodieSpark35CatalystPlanUtils.scala

as #11552 describe, hoodie insert not support column specified, support this case:
- user can specified column order when insert into/overwrite
only support spark version >= 3.2
- if user specified column list, reorder  plan with `Project` 
spark34 not support when default value enable
https://github.com/apache/spark/pull/36077
- first: in this pr, spark34 support default value for insert into, it will regenerate the user specified cols
so, no need deal with it in hudi side
- second: in this pr, it will append hoodie meta field with default value, has some bug, it look like be fixed
in spark35(https://github.com/apache/spark/pull/41262), so if user want specified cols in spark34, need disable default feature.
none
none
none

[HUDI-7949] insert into hudi table with columns specified

---

hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaUtils.java

Running [long-running](https://github.com/apache/hudi/blob/dbfe8b23c0b4f160b26379053873cfc2a46acef4/docker/demo/config/test-suite/spark-long-running-non-partitioned.yaml) deltastreamer with following properties: https://github.com/apache/hudi/blob/dbfe8b23c0b4f160b26379053873cfc2a46acef4/docker/demo/config/test-suite/test-nonpartitioned.properties
The job throws NPE during validation phase:
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 69.0 failed 4 times, most recent failure: Lost task 0.3 in stage 69.0 (TID 345) (10.0.103.207 executor 1): java.lang.NullPointerException  at org.apache.avro.JsonProperties$2$1$1.<init>(JsonProperties.java:175)  at org.apache.avro.JsonProperties$2$1.iterator(JsonProperties.java:174)  at …
```

[HUDI-7966] Handle NPE from AvroSchemaUtils.createNewSchemaFromFieldsWithReference

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java
hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/IncrementalQueryAnalyzer.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCRelation.scala

Enables the cdc logs for MOR compaction, and integrate it with the Flink incremental reader.
none
low
- introduce a new config option for Flink reader: 'read.cdc.from.changelog'

[HUDI-7911] Enable cdc log for MOR table

---

hudi-common/src/main/java/org/apache/hudi/common/util/hash/BucketIndexUtil.java
hudi-common/src/test/java/org/apache/hudi/common/util/hash/TestBucketIndexUtil.java

as https://github.com/apache/hudi/pull/11578 describe, current algorithm in some case has drawbacks, but this new algorithm also has drawbacks, so we can proceed based on practical considerations desgin the ut.
old algorithm:
new algorithm:
both of them perform bad case https://github.com/apache/hudi/pull/11578#issuecomment-2219339643 : partition values are discontinuous
parallelism = 10, bucketNumber = 5 and partition = ["2021-01-01", "2021-01-03"]
old: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
new: [2, 2, 2, 2, 2]
parallelism = 20, bucketNumber = 5 and partition = ["2021-01-01", "2021-01-03"]
old: [2, 2, 2, 2, 2]
new: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
none
low
none

[HUDI-7977] Improve bucket index partitioner algorithm

---

website/docs/sql_ddl.md
website/versioned_docs/version-0.11.0/quick-start-guide.md
website/versioned_docs/version-0.11.1/quick-start-guide.md
website/versioned_docs/version-0.12.0/quick-start-guide.md
website/versioned_docs/version-0.12.1/quick-start-guide.md
website/versioned_docs/version-0.12.2/quick-start-guide.md
website/versioned_docs/version-0.12.3/quick-start-guide.md
website/versioned_docs/version-0.13.0/quick-start-guide.md
website/versioned_docs/version-0.13.1/quick-start-guide.md
website/versioned_docs/version-0.14.0/sql_ddl.md
website/versioned_docs/version-0.14.1/sql_ddl.md
website/versioned_docs/version-0.15.0/sql_ddl.md

If we specify partition fields in an order different from the order in create table schema, then query does not fail and the whole partitioning is incorrect. This has been an issue even in 0.15 and 0.14. We will fix this in HUDI-7964. Meanwhile, it's important we update the docs. 
Docs improvement.
low
changes to the …

[HUDI-7978][DOCS] Add a note on field oldering in partitioned by clause of create sql

---

hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
hudi-common/src/main/java/org/apache/hudi/common/config/SerializableConfiguration.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java
hudi-common/src/main/java/org/apache/hudi/exception/HoodieException.java
hudi-common/src/main/java/org/apache/hudi/exception/HoodieIOException.java
hudi-common/src/main/java/org/apache/hudi/exception/HoodieIncompatibleSchemaException.java

Adjusting defaults with spillable map memory. Looks like we were allocating 80% of memory to pending compactions, giving only 15Mb to file groups. Also found some gaps around memory computation which was missed when new actions were added. 
After the fix, here is what the default looks like
total memory for spillable: 100Mb
pending compaction: 10Mb
pending clustering: 2Mb
pending log compaction: 2Mb
completed replace commits: 5Mb
bootstrap files: 5M 
actual file groups: 76Mb. 
More memory for file groups in FSVs when spillable map is enabled. 
low
- …

[HUDI-7979] Adjusting defaults with spillable map memory

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala

This MR fixes `ClassCastException` while reading by Spark, when `TimestampBasedKeyGenerator` is used.
Previous fix https://github.com/apache/hudi/pull/11501 has been reverted by https://github.com/apache/hudi/pull/11586.
In the previous fix nulls have been passed instead of parsing partition paths.
Anyway, we shouldn't parse partition paths, but in this fix partition paths are passed as it is. `UTF8String`s are passed instead of nulls as I mentioned in the discussion under https://github.com/apache/hudi/pull/11501.
Fixes `ClassCastException`. Save previous behavior for unaffected cases.
Low. Affects only if `TimestampBasedKeyGenerator` of `SCALAR`, `UNIX_TIMESTAMP` or `EPOCHMILLISECONDS` types is used. There is added `TestSparkSqlWithTimestampKeyGenerator`.
No need.

[HUDI-7709] Pass partition paths as partition column values if `TimestampBasedKeyGenerator` is used

---

packaging/hudi-spark-bundle/pom.xml
packaging/hudi-utilities-bundle/pom.xml
pom.xml

This PR unifies the shading rule of roaring bitmap dependency in the root POM for consistency among bundles.
Makes sure there is no conflict due to roaring bitmap dependency.
none
N/A

[HUDI-7950] Shade roaring bitmap dependency in root POM

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieSparkMergeOnReadTableClustering.java

Currently, the row writer defaults to snapshot reads for all tables. However, this method is relatively inefficient for MOR  tables when there are no logs. Additionally, we have already configured the glob path for queries. We need to read all the files from the glob path without requiring additional configurations for time travel queries. I believe the parameter 
TIMESTAMP_AS_OF is unnecessary and may lead to inconsistencies between the instant and the selected files, potentially causing data loss. Therefore, we should optimize this part of the configuration.
None
None
low
None

[HUDI-7980] Optimize the configuration content when performing clustering with row writer

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveAvroSerializer.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieHiveUtils.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/shims/Hive2Shim.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/shims/Hive3Shim.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/shims/HiveShim.java

In the bugfix for [HUDI-7955](https://issues.apache.org/jira/browse/HUDI-7955), the wrong class for invoking {{getTimestamp }}was used.
1. **Wrong**: org.apache.hadoop.hive.common.type.Timestamp
2. **Correct**: org.apache.hadoop.hive.serde2.io.TimestampWritableV2
Submitting a bugfix to fix this bugfix... 
Log levels for the exception block is also changed to warn so errors will be printed out.
However, false positives might be printed when the environment is indeed in Hive2.
On top of that, we have simplified the `getMillis` shim to remove the method that was added in [HUDI-7955](https://issues.apache.org/jira/browse/HUDI-7955) to standardise it with how `getDays` is written.
None
None
_Describe any necessary documentation update if there is any new feature, config, or user-facing change. …

[HUDI-7976] Fix BUG introduced in HUDI-7955 due to usage of wrong class

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodiePruneFileSourcePartitions.scala

`HoodiePruneFileSourcePartitions` use fileIndex to prune partition now can use `dataFilters`, it will cause repeated calculation in `look up candidate`
none
none
none

[MINOR] remove repeated look up candidate

---

hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDBDAO.java
hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestRocksDBDAO.java

Done this https://github.com/apache/hudi/issues/11075  
+  
Fix UT:  
Accordinly to commented code, all items must be deleted:  
```
// Delete the last entry
getRocksDB().delete(getUTF8Bytes(lastEntry));
```
I fixed deletion of last entry and fix assertion in UT.
RocksDBDAO prefixDelete deletes all items
none
none

[HUDI-7934] Fix RocksDBDAO prefixDelete to delete last entry properly

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala

When downgrading the hudi table version from 8 to 7, rename the instant file to match the 0.x naming format.
EightToSevenDowngradeHandler
low

[HUDI-7859] Rename instant files to be consistent with 0.x naming format when downgrade

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackStrategy.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java

fix #11589 not support rollback logcompact when not use marker.
1. support rollback inflight log compact instance
2. fix can not rollback complete delta instance which is create by logcompact
None
low
None

[HUDI-7988] ListingBasedRollbackStrategy support log compact

---

website/src/components/EventFeature/index.js
website/src/pages/index.js

Add events banner for next community sync
site changes
none

[DOCS] Add Event banner for next community sync

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java

The PR adds changes such that:
If cleaner last clean commit tracks savepointed instants and there is a replace commit following the savepoint and before earliest instant to retain for cleaner, then the archival will block on the replace commit instead of the earliest instant to retain. 
This is required to handle the issue of duplicates. If replace commit is replacing file groups retained by the savepoint, the cleaner must be able to clean these file groups before the replace commit is archived.
NA
low
NA

[HUDI-7779] Guard archival on savepoint removal until cleaner is able to clean it up

---

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/HiveSchemaUtil.java

Currently hudi supports several type promotion. However hive sync (including glue sync by inheritance) will fail.
More details in #11599
Fixes #11599
None
none

[HUDI-7997] Hivesync to support promotion type correctly

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java

- Leverages time travel to avoid reading entries from the RLI partition that are not yet committed in the data table
- Makes the validation more consistent
None

[MINOR] Update how RLI validation filters out new entries

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala

From previous PR:
HoodieFileGroupReader failed if preCombine and partition fields are the same with IllegalArgumentException: Field: ts does not exist in the table schema. precombineField is required but it was filtered from dataSchema as other partition fields.
To fix this I made HoodieFileGroupReaderBasedParquetFileFormat do not filter partitionColumn from dataSchema if it is the same as preCombine field.
But I did it wrong, as you can see from this discussion:  https://github.com/apache/hudi/pull/11473/files#r1681098941
There were 2 mistakes:   
- filtering condition was wrong during evaluation of dataSchema;  
- options did not contain precombineField.  
With this PR I fixed it.
precombineField and partition field may be the same, and it works with local spark and on cluster.
none …

[HUDI-7908] Hotfix: HoodieFileGroupReader fails if preCombine and partition fields are the same

---

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java

Glue will miss some partitions when multiple writers are involved. This is related to #8745
and it fixes #8634 
This implements needed methods to handle OCC writes in glue sync
None
Low

[HUDI-7494]: multi writer sync partition to glue will missing some partitions

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestCreateTable.scala

The issue with Spark 3.5.1 arises because the InsertIntoHoodieTableCommand chain calls the initialization of the HoodieFileIndex class. For v1 tables, the path is stored in CatalogTable#CatalogStorageFormat#storageProperties, but not in CatalogTable#properties. 
When Spark reloads the table, it removes the path key from CatalogTable#CatalogStorageFormat#storageProperties. 
Consequently, InsertIntoHoodieTableCommand in Hudi cannot retrieve the path from either CatalogTable#CatalogStorageFormat#storageProperties or CatalogTable#properties during deduceOverwriteConfig. This absence of the path key in combinedOpts leads to an error when initializing HoodieFileIndex.
None
None
None
None

[HUDI-8001] Insert overwrite failed due to missing 'path' property when using Spark 3.5.1 and Hudi 1.0.0

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java

The discussion about this change has been done with @xushiyan. ( https://github.com/apache/hudi/issues/11640 )
The HoodieSnapshotExporter was updated with overwrite=false as of 0.13.0 ( https://issues.apache.org/jira/browse/HUDI-712 )
But, the change  introduced a regression impact that caused Spark Job failed when failed Tasks are retried on Spark due to the created target by the previous failed Task. ( By the way, this is a task level )
On the Job level, the target path existence is checked by the existing logic
HoodieSnapshotExporter will work as usual although Spark Tasks failed and retried.
low
no need

[HUDI-712] Revert back to overwrite=true in HoodieSnapshotExporter

---

scripts/pr_compliance.py

The regex for the title validation doesn't follow the syntax.
So, this PR updates the regex string to use raw string
no more SyntaxWarning in pr_compliance.py
low
no need

[MINOR] Fix SyntaxWarning in pr_compliance.py

---

hudi-utilities/pom.xml
hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/converter/JsonToAvroSchemaConverter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/converter/ProtoSchemaToAvroSchemaConverter.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/converter/TestJsonToAvroSchemaConverter.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/converter/TestProtoSchemaToAvroSchemaConverter.java
pom.xml

- Migrates to using the Confluent registry client in order to properly resolve the proto schema references
- Updates schema converters to operate on the `ParsedSchema` returned by the SDK
- Allows users to properly resolve the schemas returned by the confluent registry
Low

[HUDI-8008] Handle proto schema references in returned schema

---

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java

When multiple updateTable are chained, the async call may overlap and some intermediary table changes may be lost. By forcing the future, it fixes this behavior.
related to #11599
Low
none

[HUDI-8006] Fix glue sync async call to update table

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java

HoodieTable#getPendingCommitTimeline returns commits, COW table is commit/replace/clustering, MOR table has delta_commit on the basis of COW table. So:
1) Optimize function name: from getPendingCommitTimeline -> getPendingCommitsTimeline
2) Optimize function implementation
none
none
none

[HUDI-8009] Optimize the code of HoodieTable#getPendingCommitTimeline

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReader.scala
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedSchemaHandler.java
hudi-common/src/main/java/org/apache/hudi/internal/schema/InternalSchema.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReaderBase.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/TestSparkParquetReaderFormat.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestSpark35RecordPositionMetadataColumn.scala
hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark24ParquetReader.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParquetSchemaEvolutionUtils.scala
hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30ParquetReader.scala
hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30ParquetSchemaEvolutionUtils.scala
hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31ParquetReader.scala
hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31ParquetSchemaEvolutionUtils.scala
hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32ParquetReader.scala
hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32PlusParquetSchemaEvolutionUtils.scala
hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33ParquetReader.scala
hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34ParquetReader.scala
hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark35ParquetReader.scala

Add internalschemaopt as param to the hoodie spark readers.
add the positional merge column to the internal schema when positional merging could be used.
Need to store internalschemaopt separate from internal schema, because sometimes we need the column in the base file, but not in the log reader
support schema.on.read with positional merging
low
N/A

[HUDI-8011] allow schema.on.read with positional merging

---

hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java

Subsume FUNCTIONAL_INDEX config subgroup in the INDEX subgroup and remove INDEXING group.
All index configs will be listed together.
none

[HUDI-7025] Consolidate index and functional index config groups

---

hudi-common/src/main/java/org/apache/hudi/common/util/JsonUtils.java
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
pom.xml

- set fasterxml version for spark3.2
- dependencies
- low
none

[HUDI-7943] Resolve version conflict of fasterxml on spark3.2

---

packaging/bundle-validation/base/build_flink1146hive313spark331.sh
packaging/bundle-validation/base/build_flink1153hive313spark334.sh
packaging/bundle-validation/base/build_flink1162hive313spark343.sh
packaging/bundle-validation/base/build_flink1170hive313spark351.sh
packaging/bundle-validation/base/build_flink1180hive313spark351scala213.sh

This PR adds build scripts for new bundle validation images:
- flink1146hive313spark331
- flink1153hive313spark334
- flink1162hive313spark343
- flink1170hive313spark351
- flink1180hive313spark351scala213
New images are uploaded to DockerHub.
New bundle validation images to simplifies the combinations
none
none

[MINOR] Add build scripts for new bundle validation images

---

hudi-common/src/main/java/org/apache/hudi/avro/AvroLogicalTypeEnum.java
hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
hudi-common/src/test/resources/date-type-invalid.avsc
hudi-common/src/test/resources/date-type.avsc
hudi-common/src/test/resources/decimal-logical-type-fixed-type.avsc
hudi-common/src/test/resources/decimal-logical-type-invalid.avsc
hudi-common/src/test/resources/decimal-logical-type.avsc
hudi-common/src/test/resources/duration-logical-type-invalid.avsc
hudi-common/src/test/resources/duration-logical-type.avsc
hudi-common/src/test/resources/local-timestamp-logical-type.avsc
hudi-common/src/test/resources/local-timestamp-micros-logical-type.avsc
hudi-common/src/test/resources/local-timestamp-millis-logical-type.avsc
hudi-common/src/test/resources/time-logical-type.avsc
hudi-common/src/test/resources/timestamp-logical-type2.avsc
hudi-common/src/test/resources/uuid-logical-type.avsc

Extended Merciful json converter to support Time, Date, UUID, Timestamp, LocalTimestamp and Duration. For supported and unsupported converter input please refer unit tests.
Test:
unit test with exhaustive branch coverage.
The merciful json convertor now is able to convert raw json input to avro logical type data that are compliant to the avro schema specifications
As an extension of component functionality, it has no impact on existing behavior. For use cases the extension addressed, it should work automatically
Low given the code coverage.
None

[HUDI-7774] Add Avro Logical type support for Merciful Java convertor

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestRecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestSecondaryIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala

Apply data skipping with record index if the query contains filter on `_hoodie_record_key`. This PR assumes that the literal in the predicate expression will be correctly specified by the user if the table has mutliple record key fields.
Data skipping with record key meta field.
low

[HUDI-7993] Apply record index if _hoodie_record_key meta field in filter

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/config/KafkaSourceConfig.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java

Github Issue - https://github.com/apache/hudi/issues/8522  
Fix the logic to accept simple checkpoint and should not need to pass the topic name.
Able to pass a new checkpoint string to HoodieStreamer as just the offset number alone.
none
It is necessary to update documentation in part of configs for `KafkaSourceConfig.KAFKA_CHECKPOINT_TYPE`.

[HUDI-6191] Improve passing the debezium checkpoint values to start job from offset

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java

fix for add missing table configurations to payloadProps (fixes #11685)
Add table configurations to the `payloadProps` of `AbstractRealtimeRecordReader` so that they can be used in custom payload.
none
none

[HUDI-8030] Fix for add missing table configurations to payloadProps (fixes #11685)

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/config/KafkaSourceConfig.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieRetryingKafkaConsumer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java

Cleanup KafkaOffsetGen: introduced retrying configurable KafkaConsumer.
Using proper retrying client
none
Documentation update is needed in part of KafkaSourceConfig:  
- remove KAFKA_FETCH_PARTITION_TIME_OUT;  
- add INITIAL_RETRY_INTERVAL_MS, MAX_RETRY_INTERVAL_MS, MAX_RETRY_COUNT, RETRY_EXCEPTIONS.

[HUDI-4625] Clean up KafkaOffsetGen: introduce retrying KafkaConsumer

---

hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedImplicitPartitionKeyLockProvider.java
hudi-aws/src/test/java/org/apache/hudi/aws/transaction/integ/ITTestDynamoDBBasedLockProvider.java
hudi-aws/src/test/java/org/apache/hudi/aws/utils/S3UtilsTest.java
hudi-aws/src/test/java/org/apache/hudi/aws/utils/TestS3Utils.java

DynamoDBBasedImplicitPartitionKeyLockProvider as a lock provider derives its partition key from hudi table name and hudi table base path. Considering the s3 uri can be of prefix s3:// or s3a://. It is enforced that we always use s3:// version when doing the partition key calculation.
Implementation + test
None
None as this lock provider is not in use yet.
Regarding the implicit partition key calculation, we should explicitly mention that if the base path of the hudi table is a s3 uri and it's prefix is "s3a", before calculating the hash value the prefix is replaced with "s3".

[HUDI-8029] Enforce s3 base path format for partition key calculation

---

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java

If the table has all timeline instants files with the older format without completion time, the upgrade fails because org.apache.hudi.common.table.timeline.HoodieActiveTimeline#getInstantDetails is trying to read file with completion time.
NA
low
NA

[HUDI-8035] Fetching commit metadata from timeline fails during upgrade

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SimpleConcurrentFileWritesConflictResolutionStrategy.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestConflictResolutionStrategyUtil.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java

Because replacecommit can be clustering, insert overwrite and delete partition. In SimpleConcurrentFileWritesConflictResolutionStrategy funciton getCandidateInstants, here only want to get pending clustering but actually it get pending replacommit(contains insert overwrite).   when we get insert overwrite, it will case BucketIndexConcurrentFileWritesConflictResolutionStrategy hasConflict function BucketIdentifier.bucketIdFromFileId throw arrayIndexOutofBound Exception.  （see the discussion in https://github.com/apache/hudi/issues/11516）
So, in SimpleConcurrentFileWritesConflictResolutionStrategy getCandidateInstants, we filter real clustring instant.
NA 
low
NA 
- _Any new …

[HUDI-8040] Fix SimpleConcurrentFileWritesConflictResolutionStrategy get pending clustering wrong

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java

support projection push down for lookup join and fix lookup join test.
If the dim table have 100 fields, and we only use 3 fields of them, then we should only keep 3 fields in the cache.
1. Modify `HoodieTableSource`,  when constructing `HoodieLookupFunction`, pass in query required schema, instead of the dim table schema.  
2. Fix lookup join test in `ITTestHoodieDataSource`. It will pass no matter what before, because source table and target table share same path.
None
low …

[HUDI-8041] Support projection push down for lookup join

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala

Extract metadata record type to `MetadataPartitionType` enum. Note that we use two different record types for `FILES` partition, so `getRecordType` accepts a key as an argument. For most MDT partitions, except `FILES` key is passed as empty string.
minor refactoring
none

[HUDI-7692] Extract metadata record type to MetadataPartitionType enum

---

hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java

To verify if the bigquery table basepath is updated or not, use source-uris as well if hive partitioning options are not available.
This will fix the issue with bigquery sync always creating the same table where hive partitioning options are not available.
low
NA

[HUDI-7881] Compare bigquery table base path via source-uris if hive partitioning options are not available

---

hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProviderBase.java
hudi-aws/src/test/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProviderBaseTest.java

Implementation + test
getDynamoDBClient method of DynamoDBBasedLockProviderBase class internally uses this.dynamoDbBasedLockConfig. So it must be called after this field is initialized. Otherwise we will hit NullPointerException.
Test:
Unit test
Critical bug fix
None
None

[HUDI-8043] Fix DDB Lock provider bug

---

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java

Updated AwsGlueCatalaogSyncClient createOrReplace method to drop and create the table, instead of updating the table.
Updated the check to compare the base of the hudi table and metastore table location to ignore file schemas.
AWS Glue table will be dropped and recreated using the latest schema. 
low
changes to the …

[HUDI-8015] Fix Glue Meta Sync Failure with recreating the table

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReader.java
hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReaderIterator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java

Set the writer configs properly so that schema changes are relaxed.
Add in the rewrite record capabilities that we use for avro log blocks
non row writer now fully works with schema evolution
medium
enabled non row writer testing in the schema evolution tests
N/A

[HUDI-6948] Fix schema evolution for non row writer

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReader.java
hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReaderIterator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java

0.x version of https://github.com/apache/hudi/pull/11731
Set the writer configs properly so that schema changes are relaxed.
Add in the rewrite record capabilities that we use for avro log blocks
non row writer now fully works with schema evolution
medium
enabled non row writer testing in the schema evolution tests
N/A

[HUDI-6948] Fix non row writer schema evolution

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java

Replace String.format with concatenation for better performance
Over 7 seconds of 2 minute job is spent for bucket key generation for flink on MOR table.
Replacing String.format with concat is 10x times faster.
none
none

[MINOR] improve performance of generateBucketKey

---

hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java

Improved performance of the createFullName in HoodieAvroUtils.
Use iterator and StringBuilder instead of stream api. 
Also I suggest that  incoming fields list mostly have only single item.
In my test case: insert 50M rows into MOR table it decrease createFullName CPU time from ~60000ms to ~1500ms (total test duration is about 9min).
none
none

[MINOR] HoodieAvroUtils performance optimization of createFullName method

---

docker/setup_demo.sh
docker/stop_demo.sh
hudi-integ-test/pom.xml

Run IT's using the command line to do docker compose instead of the plugin. The plugin we were using https://github.com/Systemmanic/docker-compose-maven-plugin is pretty much just calling cli. So I tried to replicate the same command. The only thing that does not translate directly is the timeout. We will see if the exec timeout feature will deliver the same result.
Get CI to work again so we can land prs
none
N/A

[HUDI-8067] Use exec to run the IT

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java

> case  
When I run a ut in `TestHoodieCompactor`, I found that every compaction will write a same merged file 2 times.
> reason
1. `WriteStatus::collect` is called after compaction.
2. `collect` will cause RDD computation again.     
3.  But RDD cache about this RDD id has been removed when compaction is completed.
4. So it will cause computation again from this stage. `HoodieCompactor::compact`
1. set stats in metadata after compaction
6. fix wrong usage about HoodieWriteMetadata which cause the repeated write behavior in ut
none
none
_Describe …

[MINOR] avoid repeated write behavior in ut

---

hudi-examples/hudi-examples-java/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java

Build fails locally because of checkstyle issue in hudi-examples-java:  
(naming) ConstantName: Name 'morStr' must match pattern '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.  
Fixed checkstyle in HoodieJavaWriteClientExample.
Now checkstyle is not failing
none
none

[MINOR] Fixed checkstyle in HoodieJavaWriteClientExample

---

README.md

As above, after we migrated the Azure CI to the new organization and project in Azure DevOps (`apachehudi/hudi-oss-ci`).
Reflects the correct links.
none
As above

[MINOR] Update Azure CI links in README

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanEvent.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java

I found a skew in the flink compaction task.
Compaction task shuffle the compaction operation with ***keyby***,  A series of hash mods results in skew.
One file group on compaction operator, so we don't need keyby, just rebalance is OK.
This is the result of rebanlace.
none
none
none

[MINOR] improve comaction operator shuffle

---

.github/workflows/bot.yml
README.md
azure-pipelines-20230430.yml
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSparkSampleWritesUtils.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotExporter.java
pom.xml

This PR makes Spark 3.5 the default build profile for Spark integration and Azure CI to run tests with Spark 3.5 profile.  ORC tests are temporarily disabled and will be investigated by HUDI-8081.
Makes Spark 3.5 the default.
none
Updates `README.md`.

[HUDI-7920] Make Spark 3.5 the default build profile for Spark integration

---

hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java

Fixed Externalized Config filename in documentation: from `hudi-default.conf` to `hudi-defaults.conf`
documentation on site will be correct
none
none

[HUDI-8088] Fix documentation: filename of Externalized Config file

---

hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
website/docs/configurations.md
website/releases/release-0.10.0.md
website/versioned_docs/version-0.10.0/configurations.md
website/versioned_docs/version-0.10.1/configurations.md
website/versioned_docs/version-0.11.0/configurations.md
website/versioned_docs/version-0.12.0/configurations.md
website/versioned_docs/version-0.12.0/quick-start-guide.md
website/versioned_docs/version-0.12.1/configurations.md
website/versioned_docs/version-0.12.1/quick-start-guide.md
website/versioned_docs/version-0.12.2/configurations.md
website/versioned_docs/version-0.12.2/quick-start-guide.md
website/versioned_docs/version-0.12.3/configurations.md
website/versioned_docs/version-0.12.3/quick-start-guide.md
website/versioned_docs/version-0.13.0/configurations.md
website/versioned_docs/version-0.13.0/quick-start-guide.md
website/versioned_docs/version-0.13.1/configurations.md
website/versioned_docs/version-0.13.1/quick-start-guide.md
website/versioned_docs/version-0.14.0/configurations.md
website/versioned_docs/version-0.14.1/configurations.md
website/versioned_docs/version-0.15.0/configurations.md

Fixed Externalized Config filename in documentation: from hudi-default.conf to hudi-defaults.conf
fixed documentation
none
none

[HUDI-8088][DOCS] Fix documentation: filename of Externalized Config file

---

hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteNonDefaultsWithLatestAvroPayload.java

The Java Doc of OverwriteNonDefaultsWithLatestAvroPayload is ambiguous and users cannot understand it. 
Modify it to: combineAndGetUpdateValue/getInsertValue - overwrite the storage for the specified fields with the fields from the latest delta record that are not default values.
none
none
none

[HUDI-8096] Improve OverwriteNonDefaultsWithLatestAvroPayload Java Doc

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark/src/test/resources/external-config/hudi-defaults.conf
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestSqlConf.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/hudi/Spark33ResolveHudiAlterTableCommand.scala
hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/hudi/Spark34ResolveHudiAlterTableCommand.scala
hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/hudi/Spark35ResolveHudiAlterTableCommand.scala

Value of `hoodie.schema.on.read.enable` from externalized config `hudi-defaults.conf` was not taken into consideration while processing commands such as `alter table change column .. ` in Spark.   
Fixed it by utilzing `DFSPropertiesConfiguration.getGlobalProps` in `HoodieCatalog.loadTable` and `SparkXXResolveHudiAlterTableCommand.apply`.  
Removed code duplicates in `SparkXXResolveHudiAlterTableCommand` classes by moving common method `isSchemaEvolutionEnabled` to `ProvidesHoodieConfig`.
Schema evolution option from hudi-defaults.conf works properly now with Spark SQL alter table change colunm.
none
none
- _Any new feature or user-facing change requires updating the Hudi …

[HUDI-8097] Fix getting Schema evolution setting from hudi-defaults.conf on altering columns

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/bootstrap/BootstrapUtils.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/DirectWriteMarkers.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/WriteMarkersFactory.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToFiveUpgradeHandler.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/HoodieTestCommitGenerator.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/GenericRecordValidationTestUtils.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieMergeOnReadTestUtils.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaTableServiceClient.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HadoopStorageConfiguration.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HadoopFSTestUtils.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/perf/TimelineServerPerf.java

Replace Hadoop Configuration with StorageConfiguration in hudi-client-common module
Added new methods in `HadoopFSUtils` for classes in `hudi-client-common` to handle Hadoop related confs indirectly:
- new `getStorageConf()` to create storage configuration with empty hadoop conf
- new `getFs` to provide option to copy storage conf when getting `FileSystem`
- `convertToHadoopConf` to convert storage conf to hadoop conf
- `convertToJobConf` to convert storage conf to job conf
- `setConfForConfigurableInputFormat` set hadoop conf for `FileInputFormat` that implement `Configurable`
This is a part of effort of removing Hadoop deps from `hudi-client-common`
None
None
- …

[HUDI-8093] Replace Hadoop Configuration with StorageConfiguration in hudi-client-common module

---

hudi-sync/hudi-hive-sync/run_sync_tool.sh

to allow the ability to add additional jars to execute the run_sync_tool
No changes to API or performance
Low
"none".

[HUDI-8133] allow the ability to add additional jars to execute the run_sync_tool

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java

Removing unused function `convertMetadataToRecords` in `HoodieTableMetadataUtil` class. 
NA
Low
NA

[MINOR] Removing unused function convertMetadataToRecords

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java

This PR fixes two issues in the marker-based rollback strategy after the log file marker is introduced:
- When MDT enabled, the rollback plan may include the non-existent log files based on the marker-based rollback strategy.  That leads to MDT file listing to contain the non-existent log files.  This PR fixes the MDT file listing to exclude non-existent log files.
- If the log files written in the failed commit create new file groups, these log files are not deleted through the rollback.  This PR fixes the rollback plan based on the marker-based rollback strategy. 
New tests are added to cover the cases that failed before this PR.
The bug discovered by this PR affects 0.15.0 release.
Bug fixes.
low
N/A

[HUDI-8123] Fix MDT file listing to exclude non-existent log files in marker-based rollback

---

pom.xml

mac m1 profile requires spark version so that it does not block activate by default profiles
easier for users who can't bother to set profiles that they expect
none
N/A

[HUDI-8134] Prevent mac m1 activation of profile without specifying spark version

---

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndexClient.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCLIUtils.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCompactionProcedure.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieTTLJob.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestUtilHelpers.java

When a table is on OSS and MDT is enabled, the current code adds some lock parameters. It sets the FileSystemBasedLockProvider as the default lock. However, in its constructor, it checks if the current file system supports atomicity. If it does not, an error is thrown. Currently, it seems there is no configuration to bypass this error, which prevents tables on file system such as OSS from using capabilities like calling clustering procedures.
The fix  is to skip adding this configuration when the file system does not support atomicity. This way, at least the basic functionality won't be blocked by this lock and can operate normally.
The error message is as follows:
```
Exception in thread "main" org.apache.hudi.exception.HoodieException: Unable to instantiate class …
```

[HUDI-8109] Fix the error related to locking during clustering/compaction when calling the file system which is not atomic.

---

hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java

- When the `MercifulJsonConverter` is meant to write a value as a string, it writes out the value using the `ObjectMapper` if the input value is not a string. This allows us to simply pass through values without manipulating them.
- If a user has a string field that can be json, it would end up translating this field to a map and writing as the `Map`'s `toString` output instead of simply passing through the original value.
Low
ticket …

[HUDI-8125] Update handling of non-string inputs for string fields in MercifulJsonConverter

---

hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java

Adds a test to ensure the backward compatibility is maintained for the partiton field APIs. Partition fields in table config now store the partition field type as well which are useful for CustomKeyGenerator.
NA
low
NA

[MINOR] Add backward compatibility test for HoodieTableConfig partition field APIs

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java

For hudi MOR table with timestamp column In some cases we get exception:
org.apache.hadoop.io.LongWritable cannot be cast to org.apache.hadoop.hive.serde2.io.TimestampWritable*
This happens because timestamp long value in log file converted to LongWritable but must be converted to TimestampWritable.
Reason: field AbstractRealtimeRecordReader.supportTimestamp not initialized if Schema evolution context contain internal schema.
This example reproduce problem (tested on spark3.3, hive 3.1):
spark-sql>
set hoodie.schema.on.read.enable=true;
create table hudi_test1 (col0 int, col1 float, col2 string, col3 timestamp)
using hudi
type='mor',
primaryKey='col0',
preCombineField='col1',
'hoodie.compaction.payload.class'='org.apache.hudi.common.model.OverwriteWithLatestAvroPayload'); …

[HUDI-8175] Fix LongWritable cannot be cast to TimestampWritable for MOR table with timestamp column and schema evolution enabled

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala

Just like column stats index, we can create partition stats index for all column if no columns configured by the user.
Users don't necessarily have to configure columns to aggregate stats at partition level.
low

[HUDI-7958] Create partition stats index for all columns when no cols specified

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/TestSparkParquetReaderFormat.scala

This PR fixes the remaining places that broadcast storage configuration in Spark, which can cause `NullPointerException`.  `org.apache.spark.util.SerializableConfiguration` is used for broadcasting instead.
Fixes NPE issues.
none
N/A

[HUDI-8159] Use SerializableConfiguration with Spark broadcast

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestProvidesHoodieConfig.scala

Hudi tables created with datafram API would become unwritable to SQL INSERT INTO queries due to config conflict.
See https://github.com/apache/hudi/issues/11772 for more details
Read precombine value from both table write config
None
None
None

[HUDI-8083] Read precombine value from both table write config

---

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataTableWithSparkDataSource.scala

Datasource read of MDT does not correctly use the time travel timestamp
MDT validation relies on time travel query
low
N/A

[HUDI-8137] Support time travel query on MDT in Spark Datasource

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

Adding validating last N file slices with HoodieMetadataValidator. Sometimes validating just latest may not be able to catch out of sync issues. But validating all file slices might be time consuming if lot of file slices are retained. So, adding a new parameter w/ HoodieMetadataTableValidator where in, users can choose to validate last N file slices. 
Users can choose to validate latest N files slices after this patch. "--validate-last-n-file-slices" can be used to avail this feature. 
low
- _Any new feature or user-facing change requires updating …

[HUDI-8111] Adding support to validate last N file slices with HoodieMetadataValidator

---

.github/workflows/scheduled_workflow.yml

make permissions more strict now that we know the delete cache workflow works.
According to https://github.com/actions/gh-actions-cache/issues/85 it is the write action permission that we need for delete cache 
ok, found proof in the documentation: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-github-actions-caches-for-a-repository-using-a-cache-key
more security for the repo
low
N/A

[HUDI-8180] make permissions more strict for scheduled workflow

---

docker/setup_demo.sh
docker/stop_demo.sh
hudi-integ-test/pom.xml

0.X pr of https://github.com/apache/hudi/pull/11751
Run IT's using the command line to do docker compose instead of the plugin. The plugin we were using https://github.com/Systemmanic/docker-compose-maven-plugin is pretty much just calling cli. So I tried to replicate the same command. The only thing that does not translate directly is the timeout. We will see if the exec timeout feature will deliver the same result.
Get CI to work again so we can land prs
none
N/A

[HUDI-8067] Use exec to run the IT 

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJdbcSource.java

Basepath should not be hard-coded, instead use the tempdir in base class.
Clean code
none

[MINOR] Replace hard-coded path by temp dir in tests

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java

- Pass through the properties for the remote file system view configuration if present to the meta sync properties so a meta sync can leverage this view if required
- Allows meta syncs to leverage the existing remote file system view if one exists, this can allow the syncs to avoid creating their own file system view
Low
N/A

[MINOR] Add remote file system props to meta sync properties

---

hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/common/TestMultipleHoodieJavaWriteClient.java

This PR adds one new UT for multiple java clients to validate they do not hit deadlock.
Improves test coverage
none
N/A

[HUDI-5583] Add UT on multiple Java client writers while cleaning to validate no deadlock

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/CustomAvroKeyGenerator.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala

Before, we were reading all columns from the file when using custom keygen. Now, we only read the timestamp columns.
Better read performance
low
N/A

[HUDI-8098] With custom keygen, only read timestamp partition columns from the file

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java

When meta sync is enabled, if the meta sync class name is empty string, java reflection would fail due to the empty class name.
Reduce the error message. 
No.

[ENG-13924] Fix empty meta sync class issue

---

hudi-cli/pom.xml
hudi-cli/src/main/resources/application.yml
hudi-cli/src/main/resources/version.txt
pom.xml

Hudi Cli version command output empty string. Adding property files to output the version number according with the hudi parent project version. 
Will cause confusion for client without knowing the version number
none
N/A

[HUDI-8184] Fix Hudi CLI 'version' command to return Hudi version

---

hudi-client/hudi-client-common/pom.xml

This PR removes `hudi-hadoop-common` from `hudi-client-common` as #11805 has removed all Hadoop compile-scope usages from `hudi-client-common`
None
None
none

[HUDI-8095] Remove hudi-hadoop-common compile dependency from hudi-client-common

---

hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java

Method seems to be doing pretty much the same thing so we can get rid of the worse one. Added feature to just use the default for the metadata columns to match the behavior of the old one.
Cleaner code
low
N/A

[HUDI-1441] Unify HoodieAvroUtils.rewriteRecord with HoodieAvroUtils.rewriteRecordWithNewSchema

---

hudi-tests-common/pom.xml

"slf4j-reload4j" could cause binding issue with "log4j-slf4j-impl" in some cases.
1. Remove the binding issue;
2. Less warning noisy messages.
none
N/A

[MINOR] Exclude slf4j-reload4j dependency from hudi-tests-common

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HoodieRetryWrapperFileSystem.java
hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java

We should not skip failure which means fail to delete invalid files because users might get wrong result.
The pr aims to fix the [issue#11419](https://github.com/apache/hudi/issues/11419).
Fix the bug when delete invalid files.
None
None

[HUDI-7867] Ensuring delete invalid all files during finalizing the writer

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestAutoGenerationOfRecordKeys.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataRecordIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTableDropPartition.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestCDCForSparkSQL.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestCompactionTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDataSkippingQuery.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestTimeTravelTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestUpdateTable.scala

This PR enhances our spark-sql test coverage as follows:
1. HUDI-8018 - Parameterize tests to run for both MOR and COW table type. Many tests already do so. This PR closes the gap.
2. HUDI-8019 - Merges redundant test, e.g. in `TestSpark3DDL`, merge some redundant tests such as double to decimal, string to decimal, float to decimal.
3. HUDI-8020 - Test compaction commd with deletes.
4. HUDI-8021 - Test update command with clustering.
Testing improvement
none
- _Any new feature or user-facing change requires updating the Hudi website. Please create a …

[HUDI-8018] Improve Spark SQL tests

---

hudi-common/src/main/java/org/apache/hudi/avro/ConvertingGenericData.java
hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java

While building colstats for `bytes` field, we noticed that the comparison throws below exception:
```
java.lang.ClassCastException: [B cannot be cast to java.lang.Comparable
at org.apache.avro.generic.GenericData.compare(GenericData.java:1263)
at org.apache.avro.generic.GenericData.compare(GenericData.java:1148)
...
```
Byte arrays are not inherently comparable. So, we first need to wrap in `ByteBuffer`. This PR fixes the issue and adds a simple comparison test.
Fix byte array comparison (colstats is one use case).
low …

[HUDI-8185] Handle Avro GenericData byte array comparison

---

packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh

I noticed that although the variable for path to auxlib is defined, it is not being used correctly. So running the CLI from repo-root kept redownloading the jakarta jars. The expected auxlib points to <repo_root>/packaging/hudi-cli-bundle/auxlib as defined in the $HUDI_AUX_LIB variable. However, the wget kept downloading to $PWD/auxlib which is incorrect.
NA
None
NA

[MINOR] fix the target location for auxlib download in hudi CLI

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java

Get rid of set sqlconf because it has side effects
Also use fgreader for all the schema evolution ds tests
prevent side effects of modifying sqlconf mid query
low
N/A

[HUDI-8197] Get rid of set sqlconf in Filegroupreader parquet file format

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/DatePartitionPathSelector.java

Use HadoopFSUtils.getFs to get filesystem. This is to follow up on #7105
None
None
None

[HUDI-5128] Use HadoopFSUtils.getFs to get filesystem

---

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/BaseWriterCommitMessage.java

Have BaseWriterCommitMessage implement Serializable. Recently we are exploring using Hudi with JavaSerializer instead of Kryo and found this minor gap. It shouldn't impact existing Hudi code.
None
none
none

[MINOR] Have BaseWriterCommitMessage implement Serializable

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java

The shared HFile reader in `HoodieNativeAvroHFileReader` uses non-trivial amount of memory (see the screenshots below) and is kept open for reading meta info from the HFile.  This PR adds the changes to avoid keeping the reference to the shared HFile reader by removing the shared HFile reader and caching the meta info by loading the information once, so the memory usage is reduced.
This PR also enables the native HFile reader (`_hoodie.hfile.use.native.reader`) by default again.  It was turned off by default before in #11488 due to OOM in CI.
Screenshots of memory usage of `HoodieNativeAvroHFileReader`:
Reduces memory usage.
low
N/A

[HUDI-7928] Remove shared HFile reader in HoodieNativeAvroHFileReader

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala

The PR enables data skipping and position-based record merging by default for Hudi 1.0.
Stability for 1.0.0
low
N/A

[HUDI-8102] Turn on data skipping and position-based record merging by default

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelectorCommon.java
hudi-utilities/src/test/resources/data/nested_data_1.json
hudi-utilities/src/test/resources/data/nested_data_2.json
hudi-utilities/src/test/resources/data/nested_data_3.json
hudi-utilities/src/test/resources/data/partitioned/country=US/state=TX/old_data.json
hudi-utilities/src/test/resources/schema/nested_data_schema.avsc
hudi-utilities/src/test/resources/schema/sample_data_schema.avsc

In case source data contains fields with alias fields (inplace of actual fields), we should be able read this data into dataset and convert this into original schema.
Allows to read source data if data contains fields from aliases in the schema.
None,
This is behind a feature flag, and default value is false. And should be enabled if source data contains alias fields from schema …

[HUDI-8116] Coalesce Row Source Aliases with Schema Fields in S3/GCS

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ExportInstantsProcedure.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/ScalaAssertionSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/AvroSerDerBenchmark.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestHdfsParquetImportProcedure.scala

Fix WARNING during compile.
- remove redundant `try`
- add explicit Throwable
- remove useless cast
N/A
none
N/A

[HUDI-5530] Fix WARNING during compile

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeyGenUtils.java
hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/util/SparkConfigUtils.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithCustomKeyGenerator.scala

Currently KeyGenUtils#inferKeyGeneratorTypeForAutoKeyGen  does not support custom key generators but supports the other key generator types. This PR aims to add support for it.
Also HoodieCatalogTable should be modified to add support for storing partition fields with key generator partition type. This was left out in [HUDI-7996](https://issues.apache.org/jira/browse/HUDI-7996) because of no support for custom keygen with HoodieCatalogTable
NA
low
NA

[HUDI-8034] Support custom key generator with HoodieCatalogTable

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroConversionUtils.scala

In a few cases, Avro exception is pretty good. Highlighting the error message instead of suppressing it is more informational.
e.g.: In this `spark connect` example, there is a duplicate column error. But the error is visible on the driver. Not on the python client. This PR will bubble the error message proactively and improve the UX.
```python
from pyspark.sql.session import SparkSession
sp = (
SparkSession.builder.appName("Hudi").remote("sc://0.0.0.0").getOrCreate()
)
df_1 = sp.createDataFrame([
(1, "foo"), (2, "bar"), (3, "baz")
], ["id", "name"])
df_2 = sp.createDataFrame([
(1, "foo"), (2, "bar"), (3, "baz")
], ["id", "name"])
df = df_1.join(df_2, on="id")
df.write.format("hudi").option(
"hoodie.table.name", "hudi_table"
).mode("overwrite").save("/tmp/hudi")
```
**Error _with_ this …

[MINOR] pass the avro exception for better information

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

Test with 2 writers running concurrently and validate both secondary and partition stats. There are already such tests for RLI and colstats.
Test improvement and coverage.
none

[HUDI-8023] Add multiwriter test for secondary and partition stats index

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionMetrics.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/ErrorTableUtils.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerMetrics.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestErrorTableUtils.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieStreamerMetrics.java

Pass HoodieIngestionMetrics to Error Table Writer, keep support for old interface for ErrorTableWriter.
Pass HoodieIngestionMetrics to Error Table Writer to be able to emit metrics for Error Table Wrier.
Low

[HUDI-7940] Pass HoodieIngestionMetrics to Error Table Writer to be able to emit metrics for Error Table Writer

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieOperation.java

When we check if the Spark record is a delete record, we add logic to check the `_hoodie_operation`.
If the field exists, and its value is "D", then we think this record is a delete record.
Incorporate more logic to identify delete records.
Low.

[HUDI-6909] Add logic to check operation metadata field for Spark Record

---

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/ConsistentBucketStreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockKeyedStateStore.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockOperatorStateStore.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockStateInitializationContext.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockStreamingRuntimeContext.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/keyedstate/MockKeyContext.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/keyedstate/MockKeyedListState.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/keyedstate/MockKeyedMapState.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/keyedstate/MockKeyedValueState.java

hudi-flink UnitTest uses MockOperatorStateStore as the storage behind the state of KeyedStream. Because MockOperatorStateStore does not consider the key, stateful KeyedStream operators such as BucketAssignFunction are invalid for some tests because MockOperatorStateStore considers all input records to be duplicates, even if the key is different.
We added support for KeyedStream operators with MockKeyedStateStore.
none
none
none

[HUDI-8191] Fix MockStateInitializationContext#getKeyedStateStore to use non-KeyedStateStore

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java

Similar to KafkaSource, the source profile populated in StreamContext can be used for better parallelism and instead of using a static value for numInstantsPerFetch, a dynamic value generated based on heuristics can be used. This PR needs to be merged after [https://github.com/https://github.com/apache/hudi/pull/10918]
Try to fetch the latestSourceProfile always, this ensures the profile is refreshed if it's no longer valid. The implementation of source profile takes care when a profile needs to be refreshed or re-computed again.
A new constructor added for HoodieIncrSource for emitting metrics related to source parallelism and source bytes ingested.
Medium
None.

[HUDI-7718] Use source profile in HoodieIncrSource

---

packaging/hudi-flink-bundle/pom.xml

Remove shaded of codahale metrics in flink bundle for hudi-0.14.2
backport from [https://github.com/apache/hudi/pull/10723](url)
Remove shaded of codahale metrics in flink bundle，and then we can register write metrics to flink correctly.
low
NONE

[MINOR] Remove shaded of codahale metrics in flink bundle.

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/CustomKeyGenerator.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SnapshotLoadQuerySplitter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryInfo.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSnapshotQuerySplitterImpl.java

Add new method getNextCheckpointWithPredicates in abstract class SnapshotLoadQuerySplitter for retrieving the next checkpoint along with file pruning predicates (partition filters etc.) for optimising snapshot query. These predicates help us in identifying the parquet files as part of the buildScan stage in spark data source.
No impact to existing API, new functionality being added for retrieving the next checkpoint with predicate filters. Null or Empty predicates are handled to ensure backwards compatibility.
Medium
None.

[HUDI-7830] Add predicate filter pruning for snapshot queries in hudi related sources

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

- Adding support to configure view storage type with HoodieMetadataTableValidator. We are adding two new config params, named "view-storage-type-fs-listing" and "view-storage-type-mdt" to configure different view storage types for FileSystem listing and MDT based listing. Possible values are "MEMORY" and "SPILLABLE_DISK". 
Adding support to configure view storage type with HoodieMetadataTableValidator. We are adding two new config params, named "view-storage-type-fs-listing" and "view-storage-type-mdt" to configure different view storage types for FileSystem listing and MDT based listing. Possible values are "MEMORY" and "SPILLABLE_DISK". 
low
- _The config …

[HUDI-8200] Adding support to configure view storage type with HoodieMetadataTableValidator

---

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/Parquet2SparkSchemaUtils.java

_Support array field type whose element type can be nullable._
_none._
_none._

[HUDI-7609] Support array field type whose element type can be nullable

---

docker/setup_demo.sh
docker/stop_demo.sh

While using docker demo with the later docker compose versions > 2, the docker compose command fails with error `unknown shorthand flag: f`. The PR fixes the use of the flag in the command as mentioned in the docker compose issue.
https://github.com/docker/compose/issues/8986
NA
low
NA

[MINOR] Fix  unknown shorthand flag error with docker demo

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudDataFetcher.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java

Currently, the source partition for s3 incr source is computed within the source. This PR adds support to be able to configure the source partition from the SourceProfile and used in case the num partitions from the source profile is higher than what is computed by the s3 incr source.
No impact to any public API.
Low …

[HUDI-8068] Hook up source partitions to s3 incr source

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java

Refactored for better formatting
Less Sonar warning.
No.

[HUDI-8077] Improve logging in clean planning

---

.github/workflows/azure_ci.js

The hudi-bot comment of the Azure CI status can contain the status of multiple runs on the same commit (see the screenshot below). Right now Github checks only reflect the status of the first run which is inconsistent in the case of multiple runs. As long as there is one successful CI run on a particular commit, we treat the commit passing CI (there can be flakiness outside the scope of the PR or previously cancelled runs). This PR fixes Azure CI status check to consider such multiple runs on the same commit so the Github checks reflect the correct status of the Azure CI.
Fixes Github checks to be consistent with the status of the Azure CI.
none
N/A

[MINOR] Fix Azure CI status check to consider multiple runs on the same commit

---

hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java

This PR changes config properties in the Hudi streamer to be always loaded from environment variable first and then from the config file specified by the environment variable for any overrides.
No Major Impact
Low
HUDI-8223

[HUDI-8218] Change the properties to be loaded from both default path and environment variable

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
hudi-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieLogBlock.java

If an exception occurs in the line 272~274, an error will be reported in the screenshot
Error stacktrace:
```
java.lang.IllegalStateException: Block has already been inflated
at org.apache.hudi.common.util.ValidationUtils.checkState(ValidationUtils.java:76)
at org.apache.hudi.common.table.log.block.HoodieLogBlock.inflate(HoodieLogBlock.java:308)
at org.apache.hudi.common.table.log.block.HoodieLogBlock.inflate(HoodieLogBlock.java:324)
```
Fix bug in error handling of log reading.
low
NA

[HUDI-5240] Reset the content during error handling in the log block reading

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala

Disable flaky test. Tracked in HUDI-8234
none
none

[MINOR] Disable flaky testPartitionStatsWithMultiWriter temporarily

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java

Change the way metadata table obtains minValue string strong-aroundmethod
Fixing If the primary key is a non-string type, and metastore table is used for filtering, taking minValue to forcibly convert to String will error
metadata table skip data
low
none

[HUDI-6069] Fix record key range fetching from the metadata table in Bloom Index

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/TimestampBasedAvroKeyGenerator.java
hudi-common/src/main/java/org/apache/hudi/common/config/TimestampKeyGeneratorConfig.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestTimestampBasedKeyGenerator.java

Adding support for EPOCHMICROSECONDS in TimestampBasedAvroKeyGenerator
Users can pass value EPOCHMICROSECONDS to config hoodie.deltastreamer.keygen.timebased.timestamp.type, key gen field is parsed into the correct partitions i.e. yyyy/mm/dd
Low
For testing I created a jar locally with hudi-utilities-bundle_2.12-0.12.2 with my code change and substituted it in my Spark job - it worked as planned, microsecond timestamps are being partitioned as expected now. Running Google Dataproc Hudi Deltastreamer job, reading from Confluent Cloud Debezium Avro Kafka topic, writing Hudi outputs to S3.
This would require an update to the keygen timestamp.type in the documentation to include …

[HUDI-8235] Adding support for EPOCHMICROSECONDS in TimestampBasedAvroKeyGenerator

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/HoodieCompactionPlanGenerator.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/CompositeCompactionStrategy.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java
hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/HDFSParquetImporterUtils.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java

1. support composite compaction strategy
1. support composite compaction strategy
none
low
none
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setup#we …

[HUDI-8215] Support composite compaction strategy

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java

Set the bootstrap index class name instead of payload class in metaclient when bootstrap index type is provided.
Bug fix for bootstrap
low

[HUDI-8247] Fix bootstrap index type setting in metaClient

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java

- Support dropping index through SQL
- Add a test to drop sec index and func index (RLI is already covered)
- Some renames and refactoring
Users can now drop index using SQL
low

[HUDI-7563] Add support to drop index using sql

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/CustomAvroKeyGenerator.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/CustomKeyGenerator.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/SparkParsePartitionUtil.scala
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BucketIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestCustomKeyGenerator.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithCustomKeyGenerator.scala

We changed the format of partition field table config "hoodie.table.partition.fields" for custom keygen on master and Hudi 1.0.  Hudi 1.0 reader should be able to read both 1.0 and 0.x tables with custom key generator and different partition field table config formats.
The PR makes sure that old partition field format in TableConfig is also handled. The new format was used for determining partition schema for timestamp partition type in custom keygen.
The PR also handles the logic where partition path field config `hoodie.datasource.write.partitionpath.field` is derived from existing table config so that it uses the custom keygen partition type when available.
NA
low
_Describe any necessary documentation update if there is any new feature, config, or user-facing change. If not, put …

[HUDI-8187] Hudi 1.0 reader should be able to read both 1.0 and 0.x tables with custom key generator

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala

If the recordkey field doesn't exist at all, throw an exception
Currently happens silently so user won't know until they query the record
low
N/A

[HUDI-8183] Throw exception if record key field does not exist

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestDescribeTable.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark3Analysis.scala

Addressing this issue https://github.com/apache/hudi/issues/11858  
Now desc command provides full table information independently from schema-evolution settings.
none
none

[HUDI-8161] Make spark-sql command 'desc' independent from schema evolution config

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala

Add a metadata config to enable or disable functional index. Note that this is an uber config to disable all functional indexes. To build or drop each functional index individually, users still need to use CREATE/DROP INDEX SQL commands.
Ease of use, users can easily disable func index with a simple toggle.
low
changes to …

[HUDI-7662] Add a metadata config to enable or disable functional index

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java

- Avoids serializing a FileSystemView as part of the CleanPlanner object by leveraging the methods for the HoodieTable when needed
- Avoids serializing full commit timeline as well
- Avoids serialization issues if SpillableMap is used for the file system view
None

[HUDI-8266] Ensure CleanPlanner is serializable

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/DefaultSparkRecordMerger.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDefaultSparkRecordMerger.java

`isDeleted()` only checks if the data == null.
`isDelete()` returns true when 
1. data == null; or 
2. _hoodie_operation field exists and is "D"; or 
3. data contains a specified delete field.
Therefore, remove `isDeleted()` and its underlying variable.
Clean the logic of determining delete record for Spark.
Medium.
Existing tests should be sufficient. …

[HUDI-6909] Use isDelete instead of isDeleted function for Spark merger

---

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java

Increase the waiting time to allow Compaction to complete successfully and avoid unit test failures.
During my testing on a Mac Book, with a current wait time of 20 seconds, there is a 50% probability that Compaction will not complete, resulting in unit test failures.
Of course, the failure probability depends on the machine's performance. By increasing the wait time to 35 seconds, the success rate reaches 100%.
Significantly reduce the failure rate of ITTestDataStreamWrite.
For example, a PR addressing the failures in ITTestDataStreamWrite can be found at: [PR 12025 Link](https://github.com/apache/hudi/pull/12025)
none
none

[HUDI-8277] Update wait time in ITTestDataStreamWrite#execute to prevent unit test failures

---

hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
hudi-common/src/main/java/org/apache/hudi/avro/processors/DecimalLogicalTypeProcessor.java
hudi-common/src/test/java/org/apache/hudi/avro/MercifulJsonConverterTestBase.java
hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieJsonToRowConversionException.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/MercifulJsonToRowConverter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/RowConverter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonDFSSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestMercifulJsonToRowConverter.java
hudi-utilities/src/test/resources/schema/simple-test-with-default-value.avsc

Currently when source data has to read in row format and sanitization is enabled, we first read the data in avro format(which supports sanitization) and later convert from avro to row. This new approach simplifies this process by directly converting from json to row while applying sanitization.
When source data has to be read in row format, and sanitization is enabled. This change should make the conversion from json to row faster by directly converting from json to row.
This change directly affects the existing streams. This is currently added behind a flag which can be disabled if any issues are to be found.
None
- _The config description must be updated if new …

[HUDI-5829] Optimize conversion from json to row format when sanitizing field names

---

.github/workflows/bot.yml

This PR disables maven cache in more jobs in Github action that contribute to large cache entries and files (see below), causing the integration tests to run out of disk space.
```
test-spark-java17-java-tests
Cache Size: ~861 MB (903308583 B)
test-flink (flink1.16)
Cache Size: ~762 MB (799024766 B)
validate-bundles (scala-2.13, flink1.19, spark3.5, spark3.5.1)
Cache Size: ~1153 MB (1209484010 B)
validate-bundles-java11 (scala-2.12, flink1.19, spark3.5, spark3.5.0)
Cache Size: ~1935 MB (2029325940 B)
```
Improves Github CI stability
none
none

[MINOR] Disable Maven cache that generates large files in Github Java setup

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java

The main issue mentioned in the ticket is already fixed by https://github.com/apache/hudi/pull/11496/files#diff-bba4d3c385b771e0e3d64f12cdd07c89b1ad4d9bde44895a999db058c200b428. This PR adds a test to validate the scenario mentioned in the ticket, which is as follows:
- Writer 1 is performing an index update for a specific commit instant, fetching the latest file slices and their corresponding log files.
- Writer 2 is aggressively cleaning older file slices, including log files that Writer 1 might rely on for the index update.
- If Writer 2 removes file slices or log files before Writer 1 finishes the index update, there is a potential for a `FileNotFoundException`, blocking Writer 1’s operation.
The issue is fixed in the linked patch as the file system view fetched in the …

[HUDI-7581] Add a multi writer test with index updates and cleaning

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestGlobalIndexEnableUpdatePartitions.java

Same as https://github.com/apache/hudi/pull/12033 for 0.x branch. 
- Fix Log record reading with rollback blocks having higher timestamps compared to maxInstant configured.  
LogRecordReader takes in a maxInstant time beyond which log blocks are ignored. But w/ rollbacks, there are chances it could lead to data consistency issues. 
Lets go through an illustration: 
Say, we have t1.dc, t2.dc and t2.dc crashed mid way.  
Current layout is, 
```
base file(t1), lf1(partially committed data w/ t2 as instant time)
```
Then we start t5.dc say. just when we start t5.dc, hudi detects pending commit and triggers a rollback. And this rollback will get an instant time of t6 (t6.rb). Note that rollback's commit time is greater than t5 or current ongoing delta commit. 
So, once rollback completes, this …

[HUDI-8248] Fixing Log Record reader to include rollback blocks with timestamps > maxInstant times

---

.github/workflows/bot.yml

After disabling Maven cache for some jobs in #12037, there are more coming up that lead to large cache.  This PR disables Maven cache in Github Java setup in all jobs except the source validation, to make CI stable.  There is not much impact on CI time.
```
test-spark-java-tests (scala-2.12, spark3.3, hudi-spark-datasource/hudi-spark3.3.x)
Cache Size: ~858 MB (899355069 B)
test-spark-java11-17-scala-tests (scala-2.13, spark3.5, hudi-spark-datasource/hudi-spark3.5.x)
Cache Size: ~902 MB (945678236 B)
```
Makes Github CI stable
none
none

[MINOR] Disable Maven cache in Github Java setup in all jobs

---

docker/hoodie/hadoop/base/Dockerfile
docker/hoodie/hadoop/hive_base/Dockerfile
docker/hoodie/hadoop/pom.xml

After #11994, the integration tests are unstable in Github CI due to larger docker image size and large disk usage causing no space on disk. This PR reduces the docker image size for docker demo and integration tests:
- Removes `hadoop-2.8.4/share/doc` which contains docs only in the image.  This occupies 423MB out of 679MB in the Hadoop installation.
```
root@adhoc-1:/opt/hadoop-2.8.4/share# du -d 1 -h .
257M	./hadoop
423M	./doc
679M	.
```
- Avoids storing Hudi bundle jars in the image which account for ~300MB.  Based on our docker demo guide and integration test flow, the bundle jars are always built based on the code base and dynamically referenced, so there is no point storing pre-built bundle jars.
```
target:
total 314188
drwxr-xr-x 3 root root        96 Oct  5 05:54 antrun …
```

[HUDI-8307] Reduce docker image size for docker demo and integration tests

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala

Remove the broadcast for `dataSchema`, and `requestSchema` variables; since broadcast function made null the `props` field of the schema objects, such that causes NPE for various queries using fg reader.
Fix a bug.
None.

[HUDI-7276] Fix schema used for constructing file group reader on Spark

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

Tests for partition stats and secondary index with compaction, clustering, cleaning including metadata table compaction.
Improve test coverage.
none

[HUDI-8025] Add tests for index updates with table services

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestGlobalIndexEnableUpdatePartitions.java

- Fix Log record reading with rollback blocks having higher timestamps compared to maxInstant configured.  
LogRecordReader takes in a maxInstant time beyond which log blocks are ignored. But w/ rollbacks, there are chances it could lead to data consistency issues. 
Lets go through an illustration: 
Say, we have t1.dc, t2.dc and t2.dc crashed mid way.  
Current layout is, 
```
base file(t1), lf1(partially committed data w/ t2 as instant time)
```
Then we start t5.dc say. just when we start t5.dc, hudi detects pending commit and triggers a rollback. And this rollback will get an instant time of t6 (t6.rb). Note that rollback's commit time is greater than t5 or current ongoing delta commit. 
So, once rollback completes, this is the layout.
```
base file, lf1(from t2.dc partially failed), …
```

[HUDI-8248] Fixing Log Record reader to include rollback blocks with timestamps > maxInstant times 

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java

Add support for regex-based path matching for Hoodie Incr source
When users add file path pattern field in Hoodie Incr Sourc source config, we read only files matching this provided regular expression
NA
- Added a new configuration to capture the file path pattern: hoodie.streamer.source.cloud.data.select.path.regex, with an alternative configuration hoodie.deltastreamer.source.cloud.data.select.path.regex.

[HUDI-8276] Add support for File path regex for Hoodie Incr Source

---

hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncConfig.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java

When the big query dataset project id is different than billing project id, the job has to be submitted in different project.
none
low
Big Query sync Documentation update is necessary for the extra config. Will raise a PR for that too.

[HUDI-8212] Add extra config of billing project ID for BigQuery sync

---

docker/demo/sparksql-incremental.commands
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java

This PR fixes incremental queries in integration tests on Spark:
- Adds missing Spark configs for running queries on Hudi tables in `spark-shell`
- Simplifies and enhances incremental query validation on Spark in the docker demo test
- Adds Spark incremental query validation after compaction
Adds back incremental query validation in integration tests using docker demo.
none
N/A

[HUDI-8272] Fix incremental queries in integration tests on Spark

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java

Currently, `StreamWriteFunction` uses buffer with `DataBucket`s consisting of `DataItem`s, which are transformed `HoodieRecord`s. And when we need to flush bucket, we convert `DataItem`'s back to `HoodieRecord`s in `DataBucket::writeBuffer`.
We could use `HoodieRecord`s directly to reduce number of objects in the heap, and decrease GC workload. In a result, Flink stream write is quicker in total.
|  | Before | After |
| -- | -- | -- |
| GC mainly related CPU samples | 66.7K | 43.6K |
| Memory allocation | 2.04 TB | 2.04 TB |
| Total time of 60M rows writing | 4 min | 3 min 50 s |
GC before:
GC after:
CPU samples number, which are mainly related to GC, decreased from 66.7K samples to 43.6K:
Memory allocation in `StreamOneInputProcessor::processInput` also decreased by 0.2%:
Improved Flink …

[HUDI-8301] Removed `DataItem` for Flink stream writing

---

website/docs/configurations.md

Docs update for the behavior change of config loading
none
none
none

[HUDI-8223][DOCS] Docs update for the behavior change of config loading

---

hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java

This PR enables Hive incremental queries in integration tests.  The Hive incremental queries failed due to failures in snapshot queries before.  The Hive snapshot query issue will be addressed by HUDI-8275.
Re-enables tests for test coverage
none
N/A

[HUDI-8271] Enable Hive incremental queries in integration tests

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala

Functional index using column stats can be created but the file-level stats were not getting updated. This PR fixes the issue. The root cause is that the index was initialized in COLUMN_STATS partition instead of corresponding FUNCTIONAL_INDEX partition.
Fix file-level stats update for index function.
low
changes to the …

[HUDI-5216] Implement file-level stats update for index function

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
hudi-common/src/main/java/org/apache/hudi/exception/TableNotFoundException.java
hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java

Remove `TableNotFoundException#checkTableValidity` and its usages.
This method is excessive because Hudi should just fail later on if this path is not valid/does not exist. This check is also problematic because it adds excessive FS calls, which can be very expensive when interacting with object stores like S3.
none
low
none

[HUDI-8331] Remove excessive table validity check

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala

There are two issues with the test:
1. Originally we use `insert` operation for concurrent writes. Since most of the time, these two writes have conflicts, only one write could succeed and another one fails. In such case, there are no test failures, and it is not very meaningful for the purpose of the test.
2. When we use `bulk_insert` operation, two concurrent writes could both succeed; but there is a test failure. The failure is caused by the race condition between two concurrent updates on the latestSnapshot. After adding the `synchronized` keyword, the problem is resolved. 
More coverage.
None.
- _The config description must be updated if new configs are added …

[HUDI-8234] Fix and enable testPartitionStatsWithMultiWriter

---

hudi-common/src/main/java/org/apache/hudi/common/model/FileSlice.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestNewHoodieParquetFileFormat.java

redo of https://github.com/apache/hudi/pull/12056
If a filegroup had both bootstrap base file, and log files, it would pass the log files to the fg reader.
Additionally, data skipping does not consider log files if includelogfiles is false
Additionally, we set shouldEmbedFIleSlices to true for all indexes used by the fg reader read path so that timestamp filter conversion occurs if needed.
Read optimized query correct for bootstrap mor
data skipping is better
fixes bugs around partition pruning for timestamp keygen
low
N/A

[HUDI-8273] Fix read optimized query for bootstrap tables

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java

Previously, metadata file system view was being initialized multiple times depending on whether record index and secondary index is enabled. Instead, we can just initialize once and reuse.
Minor optimization, slightly better memory utilization.
none

[HUDI-8350] Reuse metadata filesystem view once initialized in metadata writer

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/exception/HoodieMetadataIndexException.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

Fixes HUDI-8349 and HUDI-8351
- Since RLI is required for secondary index, so do not create secondary index if RLI does not exist.
- Fix secondary index update by passing the right instant time in merged log record scanner. 
- Return early when WriteOperationType is COMPACT or CLUSTER.
A bug fix and minor optimization for secondary index update.
low …

[HUDI-8351] Fix and optimize secondary index update

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java

Instead of glob path, which might have some inefficiencies due to listing, this patch uses base file reader or HoodieUnMergedLogRecordScaner to get records (for selected columns) while building column stats. Then, the lsit of HoodieRecord is converted to Dataset<Row>. 
Avoid glob path.
low

[HUDI-8339] Avoid glob path loading while building functional index

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala

For file groups without delta logs, we can make the following optimizations:
a) If the requested columns are not included in mandatoryColumns, they can be removed from requiredDataSchema.
b) Apply filters to reader for data skipping since no merging.
Optimize the performance of read mor table with file group contains only base file with filter
medium
none

[HUDI-8335] Optimize the mor table filter push down when the file group contains only base file

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java

Currently for HoodieStreamer, spark app name is created using `streamer-<target-table-name>`
2 Different databases can have same tables & using the current spark app name convention, 2 tables with same name will end up having same spark app name.
The proposed idea to resolve this by adding a new config `--spark-app-name`.
This will make sure that existing things stays as is while providing user with a config to override spark app name
NA
NA
_Describe any necessary documentation update if there is any new feature, config, or user-facing change. If not, put "none". : none …

[HUDI-8363] Support to provide custom spark app name for HoodieStreamer

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

We delete metadata records for a restore operation. Currently, anything other than FILES and RECORD_INDEX are deleted. The method `MetadataPartitionType.shouldDeletePartitionOnRestore` holds the logic for which partitions to delete. Added a test for column stats, partition stats, sec index with files and record index.
Make index correct.
Medium. …

[HUDI-8344] Delete certain indexes for restore operation

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

Throwing exception for partition stats instantiation for non partitioned table
Throwing exception for partition stats instantiation for non partitioned table
low

[HUDI-8342] Log warning and skip building partition stats for non partitioned table

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala

Make sure the partition stats payload is merged correctly even with async compaction. Added a test to simulate async compaction with commit between when compaction was requested and completed.
Fix partition stats update with async comapction.
low

[HUDI-8347] Fix partition stats update with async comapction

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkParquetReader.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieParquetFileFormatHelper.scala
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkBasicSchemaEvolution.scala
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedSchemaHandler.java
hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReader.java
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark3ParquetSchemaEvolutionUtils.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java

Reading will fail if a parquet log block for some schema evolutions.  Now we will return the records in the requested schema when reading log files. 
I modeled HoodieSparkParquetReader after HoodieAvroParquetReader and I reused some of the schema evolution utils that we use for reading base files in the fg reader.
Allow reading uncompacted mor table with schema evolution.
(Also might fix most schema evolution issues when writing with spark records but has not been tested)
low
N/A

[HUDI-6910] Fix schema evolution in the filegroup reader for parquet log blocks

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieCombineRealtimeRecordReader.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieParquetRealtimeInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java

Don't use fg reader when bootstrap table.
Keep hive reader working for bootstrap tables
low
N/A

[HUDI-8275] Do not use filegroup reader for bootstrap for now

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaTable.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
hudi-common/src/main/java/org/apache/hudi/common/util/HoodieCommonKryoRegistrar.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/io/storage/row/TestHoodieRowCreateHandle.java

- Lazily initialize the `HoodieTableMetadata`, `HoodieIndex`, and `HoodieStorageLayout` objects within the `HoodieTable` and avoid serializing it as part of the `HoodieTable`
- Register classes referenced within `HoodieTable` and the `HoodieTableMetaClient` with Kryo
Reduces serialization overhead of Spark tasks that reference `HoodieTable` 
Low …

[HUDI-8365] Reduce serialization overhead of HoodieTable

---

hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java

Fixing casting utf8 to string while constructing metadata payload for col stats
Fixing casting utf8 to string while constructing metadata payload for col stats
low

[HUDI-8178] Fixing casting utf8 to string while constructing metadata payload for col stats

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

Whenever any new file slice is added, can we do the full computation of stats for the partitions touched to ensure partition stats are accurate.
NA
low
NA

[HUDI-8348] Whenever any new file slice is added, do the full computation of stats for the partitions touched

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/DropHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
pom.xml

Bump Spark version from 3.5.1 to 3.5.3
Bump Spark version from 3.5.1 to 3.5.3
low
none

[HUDI-8396] Bump Spark version from 3.5.1 to 3.5.3

---

hudi-spark-datasource/hudi-spark-common/pom.xml

Removed redundant dependency in hudi-spark-common pom.
None
None
None

[MINOR] Remove redundant dependency

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/ConsistentBucketStreamWriteFunction.java

`DataBucket::preWrite` sets new current location, using `fileID` from `DataBucket`, only for first record in the bucket. But `fileID` is set only during `DataBucket` initialization, where we use passed first record. So, we actually don't need to call `preWrite`.
No impact
Low
No need

[HUDI-8370] Removed excessive `DataBucket::preWrite`

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieFunctionalIndex.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala

Fixing functional index record generation using spark distributed computation.
NA
low
NA

[HUDI-8340] Fix functional index record generation using spark distributed computation

---

hudi-common/pom.xml
pom.xml

Upgrade httpclient version to 4.5.13
Upgrade avro version to 1.11.3
**Reference PR**  - https://github.com/apache/hudi/pull/11964
This issue will address the below CVE from hudi-presto-bundle:0.14.0 jar
https://nvd.nist.gov/vuln/detail/CVE-2023-39410
https://nvd.nist.gov/vuln/detail/CVE-2020-13956
No user facing impacts
Included the new changes in presto and we haven't seen any regression issues
None

[HUDI-8402] Fix for CVE-2023-39410 and CVE-2020-13956

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java

Fixed flaky test.
No
No
No need

[MINOR] Fix of flaky `TestHoodieClientMultiWriter::testMultiWriterWithAsyncTableServicesWithConflict`

---

hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java

Avro logs blocks written not with spark datasource will actually be enum type. When we read with spark we will try to read it as a string. To fix this we add it to the extended avro type promotion.
Prevent failure when reading table with spark that was written with a different engine and has enums and is mor
low
N/A

[HUDI-8412] Fix enum reading in spark for Avro log blocks

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java

In Flink engine, if exception occurs when task writing data, it will be ignored and the exception will be reported to StreamWriteCoordinator with write event, StreamWriteCoordinator will decide whether to commit when there is write failure according to 'write.ignore.failed'.
This PR apply 'write.ignore.failed' ahead when write failure occurs, thus throw an exception faster.
for example:
CP interval of Flink job is 15 minutes, the exception will not be found until CP commit, it will make a longer data latency in real-time sensitive scenarios.
module: hudi-client、 hudi-flink-datasource
low
None

[HUDI-8400] apply 'write.ignore.failed' when write data failed

---

hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java

reader context had default implementation of get engine delete representation as null. The unmerged reader does not have handling for that. When compared with the other unmerged reader implementations they never process delete blocks, so the unmerged buffer is now updated to skip delete blocks
Spark npe is avoided and should be a slight perf boost. Also 1 less reader context method which is good.
none
N/A

[HUDI-8411] Fix unmerged reader to skip delete blocks and avoid NPE

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala

Avoid log warn message about closing the writer for normal write operations:
we got this warn message each time we perform writing
```
24/10/23 11:16:18 WARN HoodieSparkSqlWriterInternal: Closing write client
```
Avoid log warn message about closing the writer for normal write operations
none
none

[MINOR] Avoid log warn message about closing the writer for normal write operations

---

website/src/pages/powered-by.md

Add Kuaishou to powered-by page
None
None
None

[DOCS] Add Kuaishou to powered-by page

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/index/bucket/TestBucketIdentifier.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeyGenUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/BuiltinKeyGenerator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala

During optimization found out that current bucketing using timestamps is wrong. Described in the comment below:
https://github.com/apache/hudi/pull/12120#issuecomment-2428125344
`KeyGenUtils::extractRecordKeysByFields` is used in Flink stream processing with buckets. Optimization of this part is critical because it's called from `BucketStreamWriteFunction::processElement`, which means it's called for each record.
**Before changes**:
**After changes**:
Also, fix for HUDI-5302 introduced complex behavior depending on combination and sequence of `,` and `:`.
Actually, a sequence of `,` is not supported. For instance, key `col1:val1,,,col2:val2` with hash fields `col2` will be processed in the following way:
- parsed key value pair: `col1:val1`, `:null`, `:null`, `col2:val2`,
- after …

[HUDI-8403] Fixed values extraction for bucketing and optimized `KeyGenUtils::extractRecordKeysByFields`

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala

For timestamp keygen, timestamp type was [recently added](https://github.com/apache/hudi/pull/11615/files#diff-53ae78ff1f1bd5d8b0f87cb69853299e5228b44f30b770e27f60c0c3c27d4185R288) to the table config. In case this property is not present in table config, we still need to be backward compatible and fallback to the usual way of parsing partition values. Otherwise, NPE is thrown as below. This PR adds the null check.
```
at org.apache.hudi.SparkHoodieTableFileIndex.doParsePartitionColumnValues(SparkHoodieTableFileIndex.scala:381)
at org.apache.hudi.BaseHoodieTableFileIndex.parsePartitionColumnValues(BaseHoodieTableFileIndex.java:363)
at org.apache.hudi.BaseHoodieTableFileIndex.convertToPartitionPath(BaseHoodieTableFileIndex.java:487)
at …
```

[MINOR] Fix NPE while parsing partition values in file index

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala

Replace `hadoopConf` with `storageConf` in `HoodieCatalogTable`
none
none
none

[MINOR] Use HoodieStorage and StorageConf in HoodieCatalogTable

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkPartitionUtils.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorType.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieTableFileIndex.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCDCFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala

Logic for partition column values parse is removed from `SparkHoodieTableFileIndex`, and localized in `HoodieSparkUtils`.
**Before:**
**After:**
No
None
No need

[HUDI-8455] Logic for partition column values parse is localized in `HoodieSparkUtils`

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala

The record merge implementation class of `HoodieSparkValidateDuplicateKeyRecordMerger` and `recordMergeStrategyId` should not be required for Spark SQL INSERT INTO statement for strict insert mode and deduplication after #11943.  This PR removes such configs in `TestInsertTable`.
Makes test realistic based on the expected user experience.
none
none

[HUDI-8430] Remove redundant configs in TestInsertTable

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineServerHelper.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java

Remove the check `config.isEmbeddedTimelineServerEnabled()` from EmbeddedTimelineServerHelper#createEmbeddedTimelineService. The purpose of the function is to create an instance, and the caller should decide whether to invoke this function
none
none
none

[HUDI-8450] Optimize the design of EmbeddedTimelineServerHelper#createEmbeddedTimelineService

---

dependencies/hudi-kafka-connect-bundle.txt
pom.xml

Upgrade protobuf version to 3.25.5 to fix CVE-2024-7254
protobuf version ,which is less than 3.25 version, is having vulnerability  CVE-2024-7254
High
Upgrade protobuf version to 3.25.5 to fix CVE-2024-7254 …

[HUDI-8399]  Upgrade protobuf version to 3.25.5 to fix CVE-2024-7254

---

hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParsePartitionUtil.scala

When we specify `hoodie.datasource.write.partitionpath.field=ts:timestamp`, the partition column `ts` has data type `Long`. When we specify `hoodie.keygen.timebased.output.dateformat=yyyyMMdd---HH`, then the partition column `ts` value becomes a string in format `yyyyMMdd---HH`.
When the file index tries to collect the file list grouped by a partition path, Hudi parses the partition path value (`yyyyMMdd---HH`), and converted into their original data type (Long).
The solution is to avoid using their original type when they are specified using `<column>:timestamp` format, and uses `String` as their type to avoid any conversion failures.
No failures is caused when we specified the partition using `<column>:timestamp` format.
Low.
_Describe any necessary documentation update if there is any …

[HUDI-4818] Update partition column type to avoid type conversion failure

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/heartbeat/TestHoodieHeartbeatClient.java

The heartbeat should be removed from memory when it has been explicitly stopped (in the post-commit step, which means the instant has been committed), otherwise the heartbeat is left in memory until the write client has been stopped entirely. In streaming pipeline, the write client is been reused for multiple instants.
The heartbeats are mainly designed for lazy cleaning and very probaly the clean table service is executed asynchronously on another workload, the in-memory heatbeat does not make any sense for a committed instant actually.
none
none
none

[HUDI-8484] Instant heartbeats memory leak

---

hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParsePartitionUtil.scala

This reverts commit 3d81ea0a313bba1902065de87de4ee2be38538e3.
As said yihua here https://github.com/apache/hudi/pull/12165#pullrequestreview-2419134364
"This PR is not ready to merge and the logic can cause correctness issue. Let's revert it."
none
none

Revert "[HUDI-4818] Update the data type to string to avoid type convertion failure (#12165)"

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadMonitoringFunction.java

When empty commits are allowed , if number of continuous empty commits exceeds 'read.commits.limit' ,    IssuedInstant will not be updated which will block stream read.
hudi-flink-datasource
low
None

[HUDI-8433] Fix not update issuedOffset when stream read empty commits

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala

When we expected there is a conflict between two upserts, which may not happen since the these two commits may not update existing records.
Created a function to take in records to ensure the conflict happens.
Less flaky.
Low.

[HUDI-8410] Fix a flaky test for partition stats

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DropPartitionProcedure.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestDropPartitionProcedure.scala

Add drop_partition procedure which supports drop single and multiple partitions
hudi-spark-datasource
Low
None

[HUDI-8495] Add drop_partition procedure

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

Initialize partition stats based on latest file slices only instead of all files in a partition.
Initalization of partition stats should take much less time.
low

[HUDI-8452] Init partition stats based on latest file slices only

---

website/src/components/EventFeature/index.js

added new event banner for amazon community sync

[SITE][MINOR] Add Event banner for upcoming community sync Amazon

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/CommonClientUtils.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestMultipleTableVersionWriting.scala

After debugging, I found that upgrade path is invoked but the `metaClient` is not reloaded after that. Simply reloading in `tryUpgrade` is not enough because we call that in a lambda. So, this PR fixes the issue as follows:
- Updated `doInitTable()` to return the potentially reloaded `metaClient`, allowing `initTable()` to access the updated `metaClient` reference after an upgrade. 
- Enhanced `HoodieCommitMetadata.fromBytes()` method with a fallback mechanism for JSON deserialization given that commit metadata serialization changed from json to avro in 1.0.
Tested manually by running the same steps as mentioned in HUDI-8395.
Refactor metaClient handling during upgrade/downgrade, and implement fallback in JSON deserialization.
medium
_Describe any necessary documentation update if there …

[HUDI-8395] Fix metaClient handling when running upgrade or downgrade

---

README.md

The previous [Avro documentation URL](https://avro.apache.org/docs/current/mr.html) was outdated and non-functional. This has been updated in the README to [the correct Avro documentation link](https://avro.apache.org/docs/).
None
None
Yes

[MINOR] Update Avro URL in README

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala

Multiple secondary indexes (or functional index) exist in different partitions but still we use the same file id prefix. So, thre is a chance of collision in the append handle when two different secondary index have same file id prefix and same shard. This PR fixes the file id prefix in such a case. Added updates to the existing test case which creates multiple secondary index.
Fix updates with multiple secondary indexes.
low
only affects sec index and func index.
NA

[HUDI-8519] Fix update with multiple secondary indexes

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordGlobalLocation.java
hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieRecordGlobalLocation.java

We remove the `position` from the `equals` function; otherwise, the workload profile will be huge and can cause OOM issue.
Better performance when using global indexes.
Low.

[HUDI-8513] Fix equals in HoodieRecordGlobalLocation

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestProvidesHoodieConfig.scala

The current implementation missed database when building hudi config, which will lead to obtain the incorrect table even though the table exists. Such as the case of `spark writing data`
https://github.com/apache/hudi/blob/cea81e82fdeecec4e1d7eb53ae1f8e9eaeede11c/hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala#L97
https://github.com/apache/hudi/blob/cea81e82fdeecec4e1d7eb53ae1f8e9eaeede11c/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala#L251-L254
Because the value of `DATABASE_NAME.key` is lost when `buildHoodieInsertConfig`, so `databaseName` is empty in `tableIdentifier`.
https://github.com/apache/hudi/blob/cea81e82fdeecec4e1d7eb53ae1f8e9eaeede11c/hudi-spark-datasource/h …

[HUDI-8504] Fix missing database config when building Hudi configs in Spark

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala

testStructuredStreamingWithCompaction
testStructuredStreamingWithClustering
testSecondaryIndexWithClusteringAndCleaning
are flakey. Created blocker followups attached in the ticket
unblock development
none
N/A

[HUDI-8547] Disable flakey tests

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

Looks like we were not surfacing all errors/failures to the caller. So, fixing all such cases in this patch. Added tests w/ both ignoreFailed = false and true and validated the cases.
Cases covered:
Partition mis-match: when ignoreFailed = true, throws HoodieValidationException to caller. when ignoreFailed = false, validator execution may not fail, but caller can get exception via hasValidationFailure() and validator.getThrowables().get(0)
File slice mis-match w/ log files: when ignoreFailed = true, throws HoodieValidationException to caller. when ignoreFailed = false, validator execution may not fail, but caller can get exception via hasValidationFailure() and validator.getThrowables().get(0)
RLI mis-match (file slices match, but RLI mis-matches): when ignoreFailed = true, throws …

[HUDI-8337] Fixing failure handling with HoodieMetadataTableValidator

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/HoodieWriterClientTestHarness.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala

For overwrite related write operations like insert overwrite, insert overwrite table and delete partition operations we need to throw an error indicating that secondary index update is not supported with these operations.
We would be adding the support of such operations in a separate jira. Currently the user would need to drop and recreate the index after the operation.
INSERT_OVERWRITE, INSERT_OVERWRITE_TABLE and DELETE_PARTITION would throw error if secondary index is enabled
low
INSERT_OVERWRITE, INSERT_OVERWRITE_TABLE and DELETE_PARTITION would throw error if secondary index is enabled. Index needs to be dropped and recreated after the operation

[HUDI-8530] Error out secondary index update for write operations such as insert overwrite where it is not supported

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

Fixing flaky tests TestSecondaryIndexPruning.testSecondaryIndexWithClusteringAndCleaning. Its a test set up issue, where duplicate records were inserted. SI is not expected to work deterministically if there are duplicates in the data table. 
no more CI failures due to this flaky test. 
none

[HUDI-8549] Fixing flaky tests TestSecondaryIndexPruning.testSecondaryIndexWithClusteringAndCleaning

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/BootstrapCommand.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/OverwriteWithLatestSparkRecordMerger.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/config/RecordMergeMode.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordMerger.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordPayload.java
hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestMerger.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestOverwriteWithLatestMerger.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/OverwriteWithLatestHiveRecordMerger.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBasicSchemaEvolution.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java

Use COMMIT_TIME_ORDERING  instead of OVERWRITE_WITH_LATEST.
Just renaming.
None.

[HUDI-8554] Use COMMIT_TIME_ORDERING

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala

We cannot have absolute paths here. lets make them relative, so copy works.
hoodie.table.index.defs.path=file\:/tmp/hudi_test_table/.hoodie/.index_defs/index.json  
PR changes the corresponding config and makes it relative instead.
After PR - 
```
hoodie.table.index.defs.path=.hoodie/.index_defs/index.json
```
NA
low
NA

[HUDI-8541] Change to relative paths for the index defs json

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieFunctionalIndex.java
hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestSecondaryIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala

Allow creation of functional index without an input function. The PR uses a default function in such a case.
NA
low
NA

[HUDI-8533] Bloom functional Index creation without function fails

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/utils/TestHoodieArrayWritableAvroUtils.java

since it is using eventtime based merging, we need to actually set a real field for the precombine. 
Also need to convert the precombine to hive type when we read the hoodie records from log blocks
fix test, and also support precombine field types
low
N/A

[HUDI-8427] Fix delete in file group reader and re-enable test in TestHoodieSparkMergeOnReadTableInsertUpdateDelete 

---

hudi-hadoop-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java

`/etc/hudi/conf` is the default hudi conf path, We add it to conf paths by default.
When we do `export HUDI_CONF_DIR=/etc/hudi/conf`,  it is double referenced.
To avoid confusing error message, we check if the default conf path has been added before we add it.
Avoid confusing message.
Better UX.

[HUDI-8559] Avoid adding the conf file twice

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java

There seems to be some code changes that introduced performance degradation in [HUDI-7660](https://issues.apache.org/jira/browse/HUDI-7660).
This PR addresses the performance issues by removing `String.format` usages. 
Concat operator is the implementation for the fixed version.
`String.format` is the original implementation.
There is a **8.74x** slowdown​.
None
None …

[HUDI-8573] Fix performance degradation in RowDataKeyGen

---

hudi-common/src/test/java/org/apache/hudi/common/util/TestRetryHelper.java
hudi-io/src/main/java/org/apache/hudi/common/util/RetryHelper.java

issue: https://github.com/apache/hudi/issues/12315
1. Fix RetryHelper sleep with negative time because of Long Type overflow.
none
low
none …

[HUDI-8565]: Fix RetryHelper sleep with negative time

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala

meta client fails due to both timeline layout options being empty, now we will throw a proper error.
better error message for users
test expected tablenotfoundexception when the table is not ready, so now it will be the expected exception
low
N/A

[HUDI-8548] fail create meta client if table does not exist and proper configs not set

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala

Previously we update the merge mode for COW to be event time ordering; for MOR to be commit time. However, for COW tables with OverwriteWithLatestPayload, their compactions work as expected, since they don't have logs files, and records within different commits obeys commit time ordering. However, for MOR, since there could multiple log files for a base file, the merge orders for records from different logs may not obey 
Since we want to avoid the compaction issue for MOR, we upgrade the opposite way.
Fix inconsistent behavior.
LOW.
- _Any new feature …

[HUDI-8571] Fix the upgrade for OverwriteWithLatestPayload

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

In this patch, we handle unsupported payloads with Secondary Index creation. Only OverwriteWithLatestPayload is supported for SI with current release. We will be adding support for other payloads in next release.
Handle unsupported flows properly.
low
NA

 [HUDI-8545] Handle unsupported payloads with Secondary Index creation

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestRecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala

Fix data skipping with RLI if record key is composite. When there are multiple record key fields, we need to form the record keys sequence correctly. Added a test to show skipping with more than one record key fields.
We make a call to filterRecord key function for every record key and verify if there are literals available for every record key. If that is the case we can filter on the combination of such literals.
Support data skipping for complex primary keys
low
NA

 [HUDI-8432] Fix data skipping with RLI if record key is composite

---

website/docs/overview.mdx
website/docs/python-rust-quick-start-guide.md
website/sidebars.js
website/src/pages/ecosystem.md
website/versioned_docs/version-0.15.0/overview.mdx
website/versioned_docs/version-0.15.0/python-rust-quick-start-guide.md
website/versioned_sidebars/version-0.15.0-sidebars.json

- Add info for hudi-rs in the docs/overview page
- Add a quick start page for [hudi-rs](https://github.com/apache/hudi-rs)
- Add ecosystem links for Ray Data and Daft
NA

[DOCS][site] add hudi-rs page and ecosystem links

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestRecordLevelIndexSupport.scala

Currently AND operator can allow other operators like OR and allow to filter records. We need to disallow the behavior as it can lead to some records not getting filtered. Ideally for other unsupported operators it should not filter any records.
NA
low
NA

[HUDI-8598] Fix AND operator to not filter unsupported query types

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestDataSkippingWithMORColstats.java
hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/column-stats-index-table-short-schema.json
hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/cow-updated2-column-stats-index-table-short-schema.json
hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/mor-updated2-column-stats-index-table-short-schema.json
hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/updated-column-stats-index-table-short-schema.json
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java

Add new config `hoodie.metadata.index.column.stats.max.columns` with default of 32. 
If user does not set `hoodie.metadata.index.column.stats.column.list` then the new config will limit the number of columns to generate stats for. If `hoodie.metadata.index.column.stats.column.list` has more columns than `hoodie.metadata.index.column.stats.max.columns` it will still generate column stats for all the columns set in the config. The new config just limits the naive case where a user could have hundreds or thousands of columns and enables col stats and then performance is bad. 
Additionally, we will always index the meta fields: _hoodie_commit_time, _hoodie_record_key, _hoodie_partition_path when col stats is enabled.
Example of the config. Lets say the table schema is:
_hoodie_commit_time, …

[HUDI-8556] Add config for max number of colstats columns

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestFileIndex.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/stats/TestColumnStatsIndex.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala

- Allow partition stats only for certain data types
- Make column stats a pre-requisite for partition stats
Partition stats correctness
low

[HUDI-8586] Allow partition stats only for primitive types

---

.github/workflows/bot.yml
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala

- Enabling metadata by default on reads.
- Enabling metadata by default on reads.
low

[HUDI-8557] Enabling Metadata by default on reads

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_3Adapter.scala
hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_4Adapter.scala
hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_5Adapter.scala

Currently index commands like index creation command fail when table is created using external location. The failure occurs due to failure of resolution of command as a CreateIndexCommand.
The Jira fixes the resolution logic to make sure that CreateIndex plan with valid Hudi ResolvedTable can be resolved as hudi table.
NA
low
NA

[HUDI-8604] Support index command with External table in Spark SQL

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/AbstractIndexingCatchupTask.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/IndexingCatchupTaskFactory.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RecordBasedIndexingCatchupTask.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/WriteStatBasedIndexingCatchupTask.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/index/TestIndexingCatchupTask.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java

Indexing catchup task iterates over all the commits to sync them to MDT. It will periodically check if the commit completed. But if the commit actually failed then it will forever be in inflight mode and hence the indexing run will not progress. This PR fixes the issue by using heartbeat to detect failed commits and ignore them. Without the change in `awaitInstantCaughtUp`, the new test `testHeartbeatExpired` will fail.
Indexer can be used even with pending/failed commits.
low
- _Any new feature or user-facing change requires updating the Hudi …

[HUDI-6371] Indexing catchup tasks should handle failed commits based on heartbeat

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java

As above, to make user-facing config names consistent with the terminology.
As above
none
As above

[HUDI-8612] Rename expression index config names

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java

With 1.0, we are adding locks to commit time generation. so, for a single writer use-case, we are enforcing InProcessLockProvider as the lock provider class. 
Better out of the box user exp. 
low

[HUDI-8603] Fixing lock provider for single writer use-cases

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CommitMetadataSerDeV2.java
hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java

At a few places, the completed instant is used to derive the requested instant for clustering. Now the pending clustering instants can have different actions in tv 6 and 8. This patch infers the action based on timeline layout version.
Fix clustering/replacecommit action inference
low

[HUDI-8610] Fix clustering/replacecommit action inference

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BucketIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala

SparkBaseIndexSupport.getPrunedPartitionsAndFileNames(), we are not setting any value for includeLogFiles in which case, the default value of false takes effect. The PR adds a test for the API and makes sure we use the corresponding state from FileIndex instead.
NA
low
NA

[HUDI-8588] Col stats pruning is ignoring to leverage stats from log files

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestCreateTable.scala

If one of the partition columns is the precombine, always read that column from the file. This is not recommended at all to do this, but it should not fail if the user decides to do this for some reason. 
Prevent read failure for case where partition and precombine are the same field
low
N/A

[HUDI-8609] always read partition column from file if it is the precombine

---

azure-pipelines-20230430.yml
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala

- Parallelize lookup of secondary keys using engine context
- Remove the optimization for single file slice, use executors even for reading single file slice.
Avoid OOM in driver.
low

[HUDI-8606] Use spark engineContext to parallelize secondary keys lookup

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/TestIncrementalQueryWithArchivedInstants.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadWithFullTableScan.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

In an incremental query, Hud may need to read details from an archived instant. The ActiveTimeline and ArchivedTimeline have different ways to generate the file path. Therefore, when an ActiveTime tries to read the file of an archived instant, we see the FileNotFound error.
Our fix is to use the correct timeline object to read the instant file.
Fixed the bug.
Medium. …

[HUDI-8602] Fix a bug for incremental query

---

hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCRelation.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala

- Not allowing start time earlier than active timeline with CDC queries. Also cleans up some resources in CDCFileGroupIterator.
- Not allowing start time earlier than active timeline with CDC queries. Also cleans up some resources in CDCFileGroupIterator.
low

[HUDI-7503] Not allowing start time earlier than active timeline with CDC queries

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieSourceOffset.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV1.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV2.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala

- Add checkpoint translation for Spark streaming source
- Leverage the `Checkpoint` API added by #12342 
- Two seprate - `HoodieStreamSourceV1` and `HoodieStreamSourceV2` depending on whether source is reading offsets for table version 6 or 8.
- Add some tests for stream source to cover this scenario.
None
medium
changes …

[HUDI-8619] Add checkpoint translation for Spark streaming source

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV2.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala

We use this to avoid confusion for our users who uses incremental source and streaming source.
Better UX.
Low.

[HUDI-8619] Use new config for streaming source table version

---

website/docs/metadata_indexing.md
website/docs/quick-start-guide.md
website/docs/sql_ddl.md
website/docs/sql_queries.md

Adds documentation for indexing features in 1.0.
- Adds section on index creation using Datasource and SQL in Metadata Indexing
- Create Index section in SQL DDL
- Show and Drop index section in SQL DDL
- Quickstart - Indexing example
Adds documentation for indexing features in 1.0.
low
NA

[DOCS] Add indexing examples and info for 1.0

---

hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/CheckpointUtils.java
hudi-common/src/test/java/org/apache/hudi/common/table/checkpoint/TestCheckpointUtils.java

When the checkpoint is not given, the initial one is created with default start time: "00000000000000".
Since there is no completion time for it, the translation fails.
When we meet this kind of checkpoint, we should just return the correct checkpoint with the same time.
Fix a bug.
Low.

[HUDI-8619] fix a bug for checkpoint translation

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala

Currently the expression index does not filter records for from_unixtime spark function properly. The Jira aims to ensure that such filtering can be performed using expression index.
Expression index can filter records for from_unixtime function
low
NA

[HUDI-8643] Filter records for from_unixtime function with expression index

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowInvalidParquetProcedure.scala

add new parameter in ShowInvalidParquetProcedure, support specifying 'partitions' and filter invalid parquet files by partitions.
hudi-spark-datasource
Low
None

[HUDI-8639] Support filter by partitions in ShowInvalidParquetProcedure

---

hudi-spark-datasource/hudi-spark-common/pom.xml
hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestDataSourceUtils.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java

- Pass in the existing HoodieEngineContext instead of creating a new one when calling dedupe from the StreamSync
- Add basic unit test to ensure no wiring breaks here
- Uses a consistent engine context
None

[MINOR] Pass in engine context from StreamSync to dedupe

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/SparkBroadcastManager.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
hudi-common/src/main/java/org/apache/hudi/common/util/AvroSchemaCache.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReaderBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala

- Adding support to read input for clustering based on new FG reader 
- Fixed FileGroup reader to maintain a schema cache and avoid storing entire schema for every record in the spillable map. 
Standardized file slice reading across all different code paths (table services)
medium

[HUDI-8552] Adding support to read input for clustering based on new FG reader 

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/GenericRecordValidationTestUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieReadStats.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java

This PR makes the following improvements and fixes to the functionality around file group reader-baed compaction (`HoodieSparkFileGroupReaderBasedMergeHandle`):
- Removes the Avro `ENUM` type check which prevents file group reader-based compaction before.  Now there is no such restraint;
- Fixes `ENUM` data validation in `GenericRecordValidationTestUtils` (HUDI-8660 to revisit Avro ENUM type and corresponding Spark StructType schema type);
- Disables `HoodieSparkFileGroupReaderBasedMergeHandle` for log compaction;
- Adds complete log reading stats to the file group reader and the write stat from `HoodieSparkFileGroupReaderBasedMergeHandle`;
- Fixes `TestMetadataUtilRLIandSIRecordGeneration#testRecordGenerationAPIsForCOW` to correctly set up the table with the precombine field.
Improves …

[HUDI-8659] Remove ENUM type check and add other fixes for file group reader-based compaction

---

.github/workflows/bot.yml
README.md
release/release_guide.md

This is in context of https://github.com/apache/hudi/pull/12426#issuecomment-2520197590
We are going to use only Spark 3.3.2+ for spark 3.3 versions.
Spark patch version support update.
low

[MINOR] Fix README and CI fir min Spark 3.3 patch version support

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/config/S3EventsHoodieIncrSourceConfig.java

When updating the configuration docs based on `release-1.0.0` branch, we have to make changes in https://github.com/apache/hudi/pull/12439/commits/2ea3bf75c71a9932983a9834410781722b61fb02 to make the website compile.  This PR fixes the configs docs in the source code, i.e., making sure code examples are wrapped with backticks.
Improve config docs to avoid build errors
none
As above

[MINOR] Improve config docs to avoid build errors

---

.github/workflows/bot.yml
hudi-common/pom.xml

We made a fix to an issue that fails Flink 1.20 bundle build in the release script which was not caught by CI: #12432 .  The root cause is that CI build is not consistent with the release script, specifically the `avro.version` set.  This PR fixes the GH CI to be consistent with the release script by setting the `avro.version` per supported Flink version.
After fixing the build command CI and testing against the POM before the fix, now CI throws build error as expected:
Improves CI on Hudi Flink.
none
N/A

[HUDI-8674] Fix Flink build in CI to be consistent with release script

---

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java

- When lastMaxCompletionTime is present, we should only use completed instants to compare.
- Only get completion time in complete timeline
None

[MINOR] Only getCompletionTime for completedInstants

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java

Check for consistency :
primary/partition keys from DDL  and primary/partition keys  from parameter for 
hoodie.datasource.write.recordkey.field/hoodie.datasource.write.partitionpath.field.

[HUDI-8497]Check consistency between pk statement and option when create table using HoodieHiveCatalog

---

website/versioned_docs/version-0.15.0/hoodie_cleaner.md

* manging => managing
* atleast => at least
* long => the long
See the title of the command: `Example of cleaner keeping the latest 10 commits` but in the cli command its value is `10` so the title of the command should be fixed as below:
`Example of cleaner keeping the latest 3 commits` since the default value of the config is already `10`.
NA
none
Yes
I am only proposing these spelling changes in the documentation
* manging => managing
* atleast => at least
* long => the long

[Docs] Update hoodie_cleaner.md , Spelling correction and cli command example correction

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
hudi-io/src/main/java/org/apache/hudi/common/util/ValidationUtils.java

When using ValidationUtils to check arguments or states, messages are created immediately regardless of the result of the expression, which can lead to frequent String variable creation in some scenarios or unnecessarily large string variables, resulting in a certain amount of stress on the jvm.
For example, our task was failed because OOM caused by appending String message:
1. improve ValidationUtils performance by lazy appending msg
none
none
_Describe any necessary documentation update if there is any new feature, config, or user-facing change. …

[HUDI-8676] Improve ValidationUtils performance by lazy appending msg

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddColumnsCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterTableCommand.scala

When executing an alter-table- command, it is unnecessary to perform a clean operation. 
This can mistakenly delete the regular files of the Flink stream-write task. …

[HUDI-8537] Alter table operation no need to do rollback for failed writes

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLocationFetchHandle.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
hudi-common/src/main/java/org/apache/hudi/common/util/FileFormatUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/HFileUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/TestParquetUtils.java

- Update Simple and Global index to pass in a partition path instead of reading it from the underlying file
Reduce number of bytes processed in indexing step
Low

[HUDI-8706] Avoid reading partition path from records if not required

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala

Preconditions：
Flink create table with setting 'hoodie.datasource.write.partitionpath.field' and specifying 'hoodie.datasource.write.keygenerator.class' = 'org.apache.hudi.keygen.ComplexAvroKeyGenerator'
Scenario：
When using Spark bulk insert, ComplexAvroKeyGenerator will override default BuiltinKeyGenerator,  which will cause exception like 'Caused by: java.lang.ClassCastException: org.apache.hudi.keygen.ComplexAvroKeyGenerator cannot be cast to org.apache.hudi.keygen.BuiltinKeyGenerator'
hudi-spark-client
Low
None

[HUDI-8630] Fix convert spark key generator issue

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bucket/HoodieSparkConsistentBucketIndex.java
hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java

In the consistent-bucket mode, the creation of the `hash_metadata_file` may be read by another task or job. In this case, the Metadata may be loaded incorrectly because the `hash_metadata_file` may be read in the intermediate state.
For example, two task load `p_date=20241202` partition's hash-metadata:
1. task-a load from fs but found nothing.
2. task-a start to create initial-hash-metadata-file
3. initial-hash-metadata-file created
4. task-b load form fs and found created but empty initial-hash-metadata-file
5. task-b throw exception
6. task-a write metadata content to initial-hash-metadata-file
So task-b can see the ntermediate state of hash-metadata-file.
I wrote a UT to verify it.
1. using rename to create consistent-hash-metadata file
_Describe context and summary for this change. …

[HUDI-8626] fix: using rename to create consistent-hash-metadata file

---

rfc/rfc-77/rfc-77.md

Abstract:
In this RFC, we propose implementing Secondary Indexes (SI), a new capability in Hudi's metadata table (MDT) based indexing system.  SI are indexes defined on user specified columns of the table. Similar to record level indexes, SI will improve query performance when the query predicate contains secondary keys. The number of files that a query needs to scan can be pruned down using secondary indexes.
New RFC
NA
NA
NA

[HUDI-7146] [RFC-77] RFC for secondary index

---

website/docs/cleaning.md
website/docs/cli.md
website/docs/clustering.md
website/docs/compaction.md
website/docs/concurrency_control.md
website/docs/deployment.md
website/docs/gcp_bigquery.md
website/docs/hoodie_streaming_ingestion.md
website/docs/metadata_indexing.md
website/docs/migration_guide.md
website/docs/querying_data.md
website/docs/quick-start-guide.md
website/docs/snapshot_exporter.md
website/docs/syncing_datahub.md

This PR improves docs around Hudi Spark support to remove any reference to removed Spark versions (Spark 3.2 and below, Scala 2.11) and usage of `hudi-utilities-slim-bundle`, by recommending `hudi-utilities-slim-bundle` over `hudi-utilities-bundle`.
Docs clarity
none
As above

[HUDI-8296] Improve docs around Hudi Spark support and hudi-utilities-slim-bundle

---

website/versioned_docs/version-0.15.0/docker_demo.md

Adding -Dscala-2.11 argument to `mvn clean package` to ensure that the supported Scala Version 2.11 is used and to avoid errors like https://github.com/apache/hudi/issues/10262
Documentation Update to include the `-Dscala-2.11` command line argument after `mvn clean package -Pintegration-tests -DskipTests`, which tells the build to use Scala version 2.11, the supported Version for Hudi, as the build would fail using other Scala versions.
Less support requests due to "wrong" Scala versions used for the demo build.
None
none

Update docker_demo.md to explicitily use Scala Version 2.11 for the demo build

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v2/TimelineArchiverV2.java

- Avoid scanning timeline again if there is nothing to archive
Reduces file system listing calls in a particular case for efficiency's sake
None

[MINOR] Avoid scanning raw timeline on archival if no instants to archive

---

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java

Handle `null` value returned from `org.apache.hudi.avro.model.HoodieCleanPartitionMetadata#getIsPartitionDeleted`
Meta sync and spark catalog to get the correct partitions. 
Low
NA

[HUDI-8772] Fix NPE when deserialize cleaner plan

---

hudi-hadoop-common/src/main/java/org/apache/parquet/avro/HoodieAvroReadSupport.java
hudi-hadoop-common/src/test/java/org/apache/parquet/avro/TestHoodieAvroReadSupport.java

- Update check to see if there are any fields matching the legacy format. The legacy list format can be present with the proper map format causing an inaccurate result in the current implementation.
Fixes issue that prevents user from being able to read certain files
None

[HUDI-8748] Fix check for whether legacy mode is enabled for file

---

website/src/components/EventFeature/index.js

Update site banner
Site changes
none

[site][MINOR] Update event banner

---

hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java

This PR changes the level of marker creation logs from `INFO` to `DEBUG` at the timeline server to avoid large volume of logs from a large number of files created.
Reduces logging burden.
none
N/A

[MINOR] Reduce logs from marker creation

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
hudi-io/src/main/java/org/apache/hudi/common/util/ValidationUtils.java

issue: https://github.com/apache/hudi/issues/12338
1. wrong file path for consistent-bucket-commit-marker-file
none
low …

[HUDI-8590] fix: wrong file path for consistent-bucket-commit-marker-file

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BucketIndexBulkInsertPartitioner.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeyGenUtils.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestRDDSimpleBucketBulkInsertPartitioner.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala

In the case of:
- bulk insert operation,
- `hoodie.datasource.write.row.writer.enable = false`,
- simple bucket index,
we could do bulk insert into COW table multiple times. And only the first one will produce parquet files, the next one will produce log files, despite the fact that table type is COW. To prevent it, restrict of `AppendHandleFactory` calling for COW table is added.
Full discussion is available in https://github.com/apache/hudi/issues/12133.
No
Low
No need

[HUDI-8394] Restrict multiple bulk inserts into COW with simple bucket and disabled Spark native row writer

---

hudi-sync/hudi-datahub-sync/pom.xml
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubResponseLogger.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubTableProperties.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/util/SchemaFieldsUtil.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestDataHubSyncConfig.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestHoodieDataHubDatasetIdentifier.java
packaging/hudi-datahub-sync-bundle/pom.xml
pom.xml

This update includes several improvements:
* Enhanced schema updates sync using the Avro schema converter from the Java DataHub client.
* Table sync now includes:
- Basic Hudi table properties
- Partitioning information
- User-defined properties
- Spark-related properties
- Parent container (database) details
- Additional information such as status, subtype, and browse path
- Optionally, attach a domain object
This update significantly enhances the integration by providing richer information.
Low
The end-to-end testing was successfully completed locally by running a Spark application and verifying the output in the DataHub UI.
**Command:**
```shell
spark-submit \
--master "local[*]" --driver-memory 2g \
--jars 'packaging/hudi-spark-bundle/target/hudi-spark3.5-bundle_2.12-1.1.0-SNAPSHOT.jar …
```

[HUDI-8616] feat(hudi-datahub-sync): improvements

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/InputPathHandler.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestInputPathHandler.java

- Fix Incorrect classification of input paths in `InputPathHandler` and `HoodieInputFormatUtils`
- `HoodieInputFormatUtils.groupSnapshotPathsByMetaClient()` was not strict enough and allowed multiple ownership of paths. `forEach()` usage could potentially make multiple `metaClient` associations for a single path.
- Remove not used `HoodieInputFormatUtils.groupFileStatusForSnapshotPaths()` since the logic that called this method were refactored in [HUDI-3094](https://github.com/apache/hudi/pull/4417) and this responsibility moved to `InputPathHandler`
Reduce ambiguity of input paths classification  
Low
- _The config description must be updated if new configs are …

[HUDI-8771] Fix Incorrect classification of input paths in InputPathHandler and HoodieInputFormatUtils

---

website/src/pages/tech-specs-1point0.md

Update secondary index in tech specs.
Update secondary index in tech specs.
none

[DOCS] Update secondary index in tech specs

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BucketIndexBulkInsertPartitioner.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BucketSortBulkInsertPartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/ConsistentBucketIndexBulkInsertPartitionerWithRows.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDBucketIndexPartitioner.java

Currently there are some common code logic in the partitioner of type bucket, refactor these code into a common parent class for better code maintainability and readability.
1. extract the public logic for the bucket-type bulk insert partitioner
none
none
none …

[MINOR] refactor: extract the common logic for the bucket-type bulk insert partitioner

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/ConcatenatingIterator.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LazyConcatenatingIterator.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestLazyConcatenatingIterator.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java

Currently, when performing the read phase of clustering, I find that the memory usage in exeutor can exceed the limit.
For example: 
If we set `hoodie.clustering.group.read.parallelism = 1` and if we have 10 file-slices in one clustering group.
So we need to initialize these reader one by one, and we need to close the previous reader in time to avoid exceeding memory usage limits and optimize gc process.
1. optimize executor memory usage during executing clustering
none
none
none
_Describe any necessary documentation update if there is any new …

[HUDI-8781] Optimize executor memory usage during executing clustering

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
hudi-platform-service/hudi-metaserver/README.md
packaging/bundle-validation/service/read.scala
packaging/bundle-validation/service/write.scala

Fix incorrect configuration name "hoodie.metadata.enabled" --> "hoodie.metadata.enable"
Low
Low
none

[MINOR] Fix incorrect configuration name "hoodie.metadata.enabled"  --> "hoodie.metadata.enable"

---

packaging/hudi-presto-bundle/pom.xml
packaging/hudi-trino-bundle/pom.xml

- Removed guava, commons-lang 
Presto, Trino bundles need to rely on native HFile reader going forward. 
medium: need to be ultimately tested on trino/presto side. 
none

[HUDI-8789] Dropping hbase deps from presto/trino bundle

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java

Currently, `hoodie.populate.meta.fields` is not supported in Flink. This config should be used for append mode, so this MR adds support for this case.
**Before**, master, 3cb874fd53390b4465a8a8b9acd615b1b7f362cf:
**After**:
|  | Before | After |
| -- | -- | -- |
| CPU samples | 79.8K | 67.9K |
| Total time of 60M rows writing | 108 s | 93 s |
TPC-H lineitem table is used for profiling.
14% faster write in append mode for Flink when `hoodie.populate.meta.fields = false`.
The next possible optimization for this scenario is to think about do we really need Bloom filters in this use case, because it costs 16% of CPU after optimization of this MR:
No
Low
No need. There is no mention in "All Configurations" page that `hoodie.populate.meta.fields` is not supported for Flink.

[HUDI-8631] Support of `hoodie.populate.meta.fields` for Flink append mode

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAutoKeyGenForSQL.scala

To confirm if the auto key gen works well for Spark SQL.
Better reliability.
Low.

[HUDI-8784] Validate auto key gen for SQL

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineServerHelper.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestHoodieJavaWriteClientInsert.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java

- Pass in caller's writer config for the server to update with the host address and port
When reusing a single timeline server, the client properties such as enabling retries were being overwritten with the config of the first table that was used to create the server. Now the properties will not be overridden.
None
changes …

[HUDI-8792] Fix bug with timeline server reuse overriding client properties

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexKeyUtils.java

When we try to search for the SI records for a given record key, the way we search for the secondary key could cause some SI records missed, and further cause some SI records are not deleted correctly.
Correct SI behavior.
Medium.

[HUDI-8648] Fix a bug for secondary index deletion

---

hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieFileSliceReader.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java

When `HoodieFileSliceReader` performs reading:
For base records that have a corresponding update record in the log file, it first converts the HoodieAvroIndexRecord format that it reads from the Base Reader to the HoodieAvroRecord format. Then when it performs the merge, it convert itself to the HoodieAvroIndexRecord, and since it was the HoodieAvroIndexRecord in the first place, this extra conversion is not necessary.
`HoodieFileSlice`
`HoodieAvroRecordMerger`
1. avoid unnecessary conversion between HoodieIndexAvroRecord and HoodieAvroRecord in HoodieFileSliceReader
low
low
_If medium or high, explain what verification was …

[HUDI-8802] Avoid unnecessary conversion between HoodieIndexAvroRecord and HoodieAvroRecord in HoodieFileSliceReader

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestVectorizedReadWithSchemaEvolution.scala
hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/spark/sql/execution/datasources/parquet/Spark3HoodieVectorizedParquetRecordReader.java

While vectorized reading parquet file with schema evolution,  occasionally it will failed with ArrayIndexOutOfBoundsException
```
24/11/25 11:53:38 [Executor task launch worker for task 9] ERROR Executor: Exception in task 0.5 in stage 3.0 (TID 9)
java.lang.ArrayIndexOutOfBoundsException: -1
at org.apache.spark.sql.execution.vectorized.OnHeapColumnVector.isNullAt(OnHeapColumnVector.java:130)
at org.apache.spark.sql.execution.vectorized.WritableColumnVector.getUTF8String(WritableColumnVector.java:396)
at org.apache.spark.sql.vectorized.ColumnarBatchRow.getUTF8String(ColumnarBatch.java:220)
at org.apache.spark.sql.catalyst.InternalRow.getString(InternalRow.scala:34)
at org.apache.hudi.RecordMergingFileIterator.hasNextInternal(Iterators.scala:200)
at …
```

[HUDI-8803] Fix ArrayIndexOutOfBoundsException while vectorized read with schema evolution

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala

The recordKey was introduced starting from version 0.9 (version 2). We encountered a exception where users upgrading from Hudi 0.8:
```
org.apache.hudi.exception.HoodieException: Config conflict(key  current value   existing value):
RecordKey:      line_number,dealer_id   null
at org.apache.hudi.HoodieWriterUtils$.validateTableConfig(HoodieWriterUtils.scala:211)
at org.apache.hudi.HoodieSparkSqlWriter$.writeInternal(HoodieSparkSqlWriter.scala:178)
at org.apache.hudi.HoodieSparkSqlWriter$.write(HoodieSparkSqlWriter.scala:133)
at org.apache.hudi.DefaultSource.createRelation(DefaultSource.scala:150)
at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:47)
at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzyco …
```

[HUDI-8795] Skip checking recordKey config for table version <=1

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/DiskMap.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/FilterIterator.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/KeyFilteringIterable.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/PredicatePushdownIterable.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDBDAO.java
hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDbDiskMap.java
hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestFilterIterator.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/collection/TestBitCaskDiskMap.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/collection/TestRocksDbDiskMap.java

`HoodieMergeHandle::writeIncomingRecords` will always read all the log records from disk even thought these log records we have previously confirmed that we do not need to insert.
So we should push down this predicate to `ExternalSpillableMap::iterator` to avoid unnecessary disk access.
1. improve compaction performance by avoid unnecessary disk visiting
2. support push down predicate to `ExternalSpillableMap`
none
none
- …

[HUDI-8787] Improve compaction performance by reducing unnecessary disk access

---

website/docs/azure_hoodie.md
website/docs/cleaning.md
website/docs/cli.md
website/docs/clustering.md
website/docs/compaction.md
website/docs/concepts.md
website/docs/concurrency_control.md
website/docs/indexes.md
website/docs/key_generation.md
website/docs/markers.md
website/docs/metadata.md
website/docs/performance.md
website/docs/precommit_validator.md
website/docs/record_merger.md
website/docs/timeline.md
website/docs/writing_tables_streaming_writes.md

Added some reference blogs to hudi website docs
none

[DOCS] Added reference blogs to hudi docs

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/HoodieWriterClientTestHarness.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java

Clean and archival should share the same error handling logic as inline clustering and compaction.
Improved table service logging in general to include table base path. Without base path info we cannot differentiate if the operation is against the data table or MDT.
clean and archival will behave correctly and have error logs on unhappy code path.
low
none

[HUDI-8804] clean and archival should also be in try-catch block

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/common/TestHoodieSparkEngineContext.java

because in hudi HoodieSparkEngineContext the jobGroupId is set as activeModule  , so when the query cancelling happens and thrift server tries to find active jobs with the SQL statement id and nothing will be found.
Any users including OSS using spark-hudi have such issue, not just OH.
This issue can be simply avoided by not overriding jobGroupId with activeModule.
Initial state: there is a spark job inflight, enter Ctrl+C in beeline
After the change: 
Job group of spark task and query statement id are the same
the inflight job will be aborted as soon as the interruption is acked, which can be told by 1. the failed job has 0 task completed as I stop the job at the very beginning of the execution. 2. The inflight job end up as a "Failed job". Also I can see the job execution throws …

[HUDI-8596] Fix Hudi Spark SQL cancelling issue

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java

Currently, there exists some redundant byte copies at the record level during appending 
`HoodieAvroDataBlock` to log file. Reducing these copies will effectively decrease GC  pressure.
reduce unnecessary memory usage during writing log
none
none

[HUDI-8829] reduce bytes copy during writing avro records to log file

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java

Fix log info format.
Log info will contain the right paramter value.
none
none

[MINOR] Fix bad log info in table services

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDecimalTypeDataWorkflow.scala

Add a test to insert/update/delete/read data for a MOR table
Verify that decimal data type workflow works.
Low.

[HUDI-8783] Add tests for decimal data type

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java

`close` is slow when large amount rowCreateHandles in BulkInsertWriterHelper, this PR close this handles in parallel. 
hudi-flink-datasource
Low
None

[HUDI-8782] BulkInsertWriterHelper parallel close

---

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV1.scala
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java

There are many code like that to get latest_completed_time:
There is a risk, however, that if timeline were not completed-timeline, it would filter out unfinished instant in `BaseHoodieTime::getInstantsOrderedByCompletionTime`, causing `skip(activeTimeline.countInstants() - 1)` will exceed the stream range.
I refactor the code that uses this pattern to avoid the associated risks.
1. fix wrong way to get the latest completed instant
none
low
none
_Describe any necessary documentation update if there is any new feature, config, or user-facing change. …

[MINOR] Avoid wrong way to get the latest completed instant

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala

- As of now, we lookup in col stats for all filter expressions. This patch checks for any non indexed cols and avoids col stats based pruning. The files from pruned files are used as candidate files if any non indexed cols are detected. If not, pruning happens based on col stats index in MDT and candidate files are deduced.  We have also optimized the AND clause. If we have a `leftExpr AND rightExpr`, where leftExpr has non indexed cols, while rightExpr has all indexed cols, we can still afford to prune files based on col stats index. The expression to look up in col stats will omit leftExpr accordingly. Only if both leftExpr and rightExpr has non indexex cols, we can avoid looking up in col stats index. Incase of 'Or' clause, we can't do much, but have to resort to bypass col stats …

[HUDI-8663] Look up in col stats based on indexed cols

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/HoodieJavaEngineContext.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieEngineContext.java
hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieLocalEngineContext.java
hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
hudi-common/src/main/java/org/apache/hudi/metadata/BaseFileRecordParsingUtils.java
hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexRecordGenerationUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala

- Ensure deletes via custom payload or merger gets synced to RLI (HUDI-8741)
- Fix secondary index updates for event_time and custom merge modes (HUDI-8518)
- Ensure secondary index updates are done in distributed manner without collected any record keys or maps in driver (HUDI-8740)
Index correctness with custom mergers, and optimization.
medium …

[HUDI-8518] Fix RLI and Secondary index with custom payload or merge mode

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala

Addressing this comment https://github.com/apache/hudi/issues/11865#issuecomment-2330174420
No need to explicitly set hoodie.avro.schema.validate to false now.
none
none

[HUDI-8173] Default value of hoodie.avro.schema.validate silently getting updated if not passed explicitly

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala

PR reenables TestExpressionIndex which was disabled earlier due to test infra failures
NA
low
NA

[HUDI-8849] Reenable TestExpressionIndex

---

hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowInvalidParquetProcedure.scala

recent production troubleshooting has requirements for filtering by instants in ShowInvalidParquetProcedure.
this PR support specifying 'instants' and filter invalid parquet files by instants.
None.
Low
None.

[HUDI-8859] Support filter by instants in ShowInvalidParquetProcedure

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/LogFileIterator.java
hudi-common/src/test/java/org/apache/hudi/common/table/log/TestLogFileIterator.java

Issue already fixed in https://github.com/apache/hudi/commit/6db37510ab07dcd5ff99b84dc85e480e1bb3a373
Just adding a test.
Without the above fix, it leads to following exception
```
Caused by org.apache.hudi.exception.HoodieException: Unsupported Operation Exception
at org.apache.hudi.common.util.collection.BitCaskDiskMap.values(BitCaskDiskMap.java:302)
at org.apache.hudi.common.util.collection.ExternalSpillableMap.values(ExternalSpillableMap.java:290)
at org.apache.hudi.common.table.log.LogFileIterator.hasNextInternal(LogFileIterator.java:44)
at org.apache.hudi.common.table.log.LogFileIterator.doHasNext(LogFileIterator.java:55)
at org.apache.hudi.common.table.log.HoodieFileSliceReader.hasNextInternal(HoodieFileSliceReader.java:90)
at …
```

[HUDI-8860] Avoid calling values() on ExternalSpillableMap

---

hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTableWithNonRecordKeyField.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala

For insert and update clause of MIT, in some cases if we didn't set the primary key/precombine field value explicitly, MIT errors out in the query analyze phase.
Also some changes that make sure the precombine key value data type is the same over source and target table (an irrelevant test maintenance)
Better user facing error message and guard against cases we don't support.
none
We track MIT doc update all in https://issues.apache.org/jira/browse/HUDI-8527

[HUDI-8824] MIT should error out for some assignment clause patterns

---

hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDataSourceHelpers.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala

Fix broken test as we changed hudi_table_change to spark streaming.
TestSparkSqlCoreFlow all green now
none
none

[HUDI-8664] Fix TestSparkSqlCoreFlow to be based on completion time

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala

add MIT test coverage
better coverage
none
none

[HUDI-8828] Test coverage of MIT partial insert and update

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestUpdateTable.scala

update will error out when it tries to change partition column /primary key column value.
guard update against unsupported use cases.
none
Maybe we should update the update query doc on this behavior.

[HUDI-8823] Ban update from updating primary key and partition key

---

website/docs/sql_dml.md
website/versioned_docs/version-1.0.0/sql_dml.md

As above, to mention that "MERGE INTO" and "INSERT INTO" do not support schema evolution.
List the limitations in DML docs
none
As above

[HUDI-8629] Update Spark DML docs on schema evolution

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java

when sync hive in `StreamWriteOperatorCoordinator.notifyCheckpointComplete`,  `this.instant` has beed updated in `startInstant` which causes `syncHiveAsync` logs the newer instant(actually should be the committed one ), which will cause misleading when troubleshooting.
case like:
timeline
```
-rw-r--r-- 3 xx_edw xx_edw 19.8 K 2024-12-31 12:04 hdfs://nsxxx/user/xx_edw/dwd.db/dwd_product_other_sku_1_chain_hudi/.hoodie/20241231120258437.deltacommit
-rw-r--r-- 3 xx_edw xx_edw 0 2024-12-31 12:02 hdfs://nsxxx/user/xx_edw/dwd.db/dwd_product_other_sku_1_chain_hudi/.hoodie/20241231120258437.deltacommit.inflight
-rw-r--r-- 3 xx_edw xx_edw 0 2024-12-31 12:02 hdfs://nsxxx/user/xx_edw/dwd.db/dwd_product_other_sku_1_chain_hudi/.hoodie/20241231120258437.deltacommit.requested
-rw-r--r-- 3 xx_edw xx_edw 0 …
```

[HUDI-8862] Fix inconsistent instant when sync hive in StreamWriteOperatorCoordinator

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelationV2.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

When start commit is archived, 
1. If we allow falling back to full scan, which avoids checking the commit metadata;
2. otherwise, we will read the archived metadata if needed.
Avoid expensive metadata fetching for archived instants.
Medium.

[HUDI-8624] Enable fullscan by default for incremental queries

---

website/docs/concurrency_control.md

Fixed a broken link in concurrency control page which points to timeline/truetime-generation
Low/docs
Low
Link fix in Concurrency control page

[DOCS] Fix broken link in concurrency control page

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/HoodieSpark35CatalystPlanUtils.scala

Before this fix, If there are unresolved columns in the `MERGE INTO` statement using Hudi, currently Spark 3.5 throws the exception below which is not user-friendly:
```
Caused by: org.apache.spark.SparkException: [INTERNAL_ERROR] Cannot find main error class '_LEGACY_ERROR_TEMP_2309'
at org.apache.spark.SparkException$.internalError(SparkException.scala:92)
at org.apache.spark.SparkException$.internalError(SparkException.scala:96)
at org.apache.spark.ErrorClassesJsonReader.$anonfun$getMessageTemplate$1(ErrorClassesJSONReader.scala:68)
at scala.collection.immutable.HashMap$HashMap1.getOrElse0(HashMap.scala:361)
at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:594)
at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:589)
at …
```

[HUDI-8865] Fix error message of unresolved columns in MERGE INTO on Spark 3.5

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java

In https://github.com/apache/hudi/pull/12376 - we attempted to revert the optimization for single file slice, and do the computation such as getRecordByKeys, etc. over executors even if it is for a single file slice. This means when listing files using metadata files index, even if the data partition has only one file slice, it happens over the executor and the request is sent to the timeline server (RemoteFileSystemView). However, we noticed that the timeline server did not respond and the request timed out in the case of bootstrap of a MOR table having multiple partition fields.
The PR reverts the single file slice optimisation and also fixes the test failure in TestBootstrapRead.testBootstrapFunctional. The test was failing because all spark threads are used up in the list calls for …

[HUDI-8621] Revert single file slice optimisation for getRecordsByKeys in MDT table

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/parser/HoodieSqlCommonAstBuilder.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallCommandParser.scala

Hudi parser parse any sql text that looks like 'call xx.yy(z1,z2)' as `CallCommand`,  then fails with AnalysisException in `HoodieAnalysis` if the command is not support by hudi。 This make other parsers like Iceberg or other user defined  lost chance to parse the call sql
None
medium
None

[HUDI-8831] Hudi parser should passthrough unsupport procedure to delegate

---

hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala

we support bucket index pruning since [HUDI-6207](https://issues.apache.org/jira/browse/HUDI-6207), but the configurations of bucket index doesn't been passed to SparkHoodieTableFileIndex.
none
none
none

[HUDI-8855] Add bucket properties for spark bucket index query pruning

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowClusteringProcedure.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala

Added filtering of received plans by isPresent
Hudi "show_clustering" SQL procedure doesn't throw java.util.NoSuchElementException: No value present in Option
None
None

[HUDI-8806] Fix "No value present in Option" in show_clustering procedure

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala

This PR improves the test coverage around the following cases:
(1) For `UPDATE SET` clause in `MERGE INTO` statement, it can contain different field names from the source table, as long as the assignment clause associates the source and target table fields properly, e.g., `UPDATE SET price = source.new_price`.
(2) Table schema should not be evolved in any case for `INSERT INTO` or `MERGE INTO` statements.
Improves test coverage on the above cases.
none
N/A

[HUDI-8629] Improve test coverage around different field names in MERGE INTO statements

---

README.md
pom.xml

Currently, `javadoc:aggregate` couldn't be run at all. Fixed it in this MR. Proper versions for `genjavadoc-plugin_**` are taken from [this list of available versions](https://mvnrepository.com/artifact/com.typesafe.genjavadoc/genjavadoc-plugin).
Proper run is consist of two stages:
```bash
mvn clean install -DskipTests -Dspark* -Dflink* -T 1C
mvn javadoc:aggregate -DskipTests -Dspark* -Dflink* -T 1C -Pjavadocs
```
There are still many errors and warnings in `javadoc:aggregate` results, which require fixes in javadoc comments everywhere in the code. Created corresponding ticket HUDI-8872.
No
No risk
No need

[MINOR] Fixed run of `javadoc:aggregate`

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestSparkNonBlockingConcurrencyControl.java

In NBCC mode, the file id of each bucket should be fixed, and we should follow the generation rules everywhere to avoid having different file ids in the same bucket.
1. fix the generation of uncertain file id in NBCC mode
none
low
none …

[HUDI-8866] Unified the file naming rules in NBCC mode

---

hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

the test has been disabled for more than 2 years by this PR https://github.com/apache/hudi/pull/5124. The test cannot even run locally as it is broken.
The PR repaired the test and enable it again. In case there are new flakiness surfaced, we should cut new Jira and tracking it. There is no sense to RCA a test failed 2 years ago.
Also verified that from the point of randomness of the test data we generated, that could not affect the test stability - the test data always go to the same fixed partition path and the test just try to delete a deterministically created partition.
better test coverage
none
none

[HUDI-8693] Renable TestHoodieDeltaStreamer.testDeletePartitions

---

hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java

The test was added in HUDI-288 but has always been in Ignored state. I have checked that the string being asserted `Please provide valid table config arguments` never existed in the codebase even duting the commit. I think it is ok to remove the test.
NA
low
NA

[HUDI-8696] Remove TestHoodieMultiTableDeltaStreamer#testInvalidIngestionProps

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/SqlKeyGenerator.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala

the issue is at SqlKeyGenerator#convertPartitionPathToSqlType
where the default HIVE_DEFAULT_PARTITION value is trying to be converted into Long/milli second.
update SqlKeyGenerator#convertPartitionPathToSqlType to handle default_partition_path
TODO:
partition_path for timestamp partition
low
NA

[HUDI-8315] update SqlKeyGenerator#convertPartitionPathToSqlType to handle default_partition_path

---

pom.xml

Bump maven shade plugin version from 3.4.0 to 3.5.1.
This is necessary to bump JDK version to 20+, as older versioned shade plugin won't support new JDK, sample error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.4.0:shade (default) on project hudi-examples-k8s: Error creating shaded jar: Problem shading JAR /home/release/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.jar entry META-INF/versions/21/org/bouncycastle/pqc/jcajce/provider/NTRU$Mappings.class: java.lang.IllegalArgumentException: Unsupported class file major version 65 -> [Help 1]
```
None
None
none …

[MINOR] Bump maven shade plugin version

---

hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

The culprit leads to validation issue is because instead of extracting the commit time from the data file and compare, we just treat the whole file name as a string and check if the string contains the commit instant time string. This causes issue if the commit instant time string is short (like "002") as the file name is generated with UUID and it can contain this string by chance.
The fix is we explicitly extract the commit time from the file name and compare, this eliminates any ambiguity of the validation we are doing.
Also we should write more informative error message, containing as many context on what we validated as possible. It saves tons of time reproducing the issue.
fixed flaky test
none
none

[HUDI-7374] Fix flaky test concurrent compaction test

---

hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java

The filesystem based lock provider might not do atomic operations based on OS/docker container the test uses, which leads to lock provider not functioning correctly and leads to validation phase of OCC to run concurrently.
For more info please refer https://issues.apache.org/jira/browse/HUDI-8887.
Get rid of flaky test.
none
none

[HUDI-7483] Disable flaky test dimension

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/avro/HoodieAvroParquetReader.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/avro/HoodieTimestampAwareParquetInputFormat.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java

Fix the exception happens when hive scan hudi table after new column is added.
Consolidating hive scan to support more schema evolution scenarios.
low

[HUDI-8880] Fix hive scan exception after new column is added

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

The PR enables disabled test TestSecondaryIndexPruning#testSecondaryIndexWithClusteringAndCleaning.
First running the test 200 times to check for flakiness.
NA
low
NA

[HUDI-8689] Enable TestSecondaryIndexPruning#testSecondaryIndexWithClusteringAndCleaning

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala

Change afterImageRecords to use spillable hashmap to mitigate OOM issue.
CdcFileGroupIterator is less prone to OOM. The default threshold for memory spill is 100MB.
none
Added a new configuration `hoodie.cdc.file.group.iterator.memory.spill.bytes` for overriding default memory spill threshold.

[HUDI-8839] CdcFileGroupIterator use spillable hashmap

---

hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java

Re-enable testLatestCheckpointCarryOverWithMultipleWriters
- Fix checkpoint fetch in the test (use CheckpointUtils)
- Fix metaclient creation in the test
Improve CI flakiness
none

[HUDI-8694] Re-enable testLatestCheckpointCarryOverWithMultipleWriters

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieStatsIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala

Reuse methods from subclasses HoodieSparkClientTestBase
Enhance reusability
None
None

[HUDI-7598] Remove duplicate methods in subclasses of HoodieSparkClientTestBase to enhance reusability

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala

Make sure the conflict happens since the update records are shared between the two writers.
Fix a flaky test.
Test locally for 40+ times; there are no failures.
None.

[HUDI-7656] Fix a flaky test for concurrent writes

---

hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/testutils/SparkDatasetTestUtils.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/KeyGeneratorTestUtilities.java

refactor SparkDatasetTestUtils#serializeRow -> removed Spark 2 case, and reduced the reflection (optimized to work with spark3+ versions)
org.apache.hudi.testutils.KeyGeneratorTestUtilities#serializeRow -> since same code is used, SparkDatasetTestUtils#serializeRow is reused.
NA
NA
NA

[HUDI-8298] refactor SparkDatasetTestUtils#serializeRow

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieCompactionHandler.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala

This PR enables schema on read in file group reader-based compaction and clustering in Spark after #12510 makes the schema on read-related configs are propagated properly.  For compaction, the write config containing the schema on read related information needs to be propagated properly to the merge handle.
Before this PR, `TestSpark3DDL`.`Test alter table properties and add rename drop column` fails if we enable schema evolution on read in the file group reader-based compaction without fixing the write config.  In this PR, this test is enhanced (renamed to `Test alter table properties and add rename drop column with table services`) to cover both compaction and clustering with schema on read enabled in Spark.
Removes limitation of file group reader-based compaction and clustering in …

[HUDI-8634] Support schema on read in file group reader-based compaction and clustering in Spark

---

hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

This PR improves the logging from MDT validator to avoid oversized log message that can cause OpenSearch to throw error on indexing the logs.
```
The length of [log] field of [1252665] doc of [logstash-%{[url][path]}-2024.11.29] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!
```
Specifically:
- Introduces `StringUtils#toStringWithThreshold` to limit the size of String when converting the list of objects to String;
- Improves logging in the validation of metadata listing to limit the list of metadata items to show using `StringUtils#toStringWithThreshold` or only show necessary item that …

[HUDI-8857] Log shortened list of files instead of all files in MDT validator to avoid huge log message

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java

This reverts commit 79e1730aea01dab80181fb10bd22c2d3f00204e7. Since this commit landed we see that the CI runtime has increased a lot. Reverting commit for HUDI-8621
NA
low
NA

Revert "[HUDI-8621] Revert single file slice optimisation for getRecordsByKeys in MDT table (#12643)"

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java

TestHoodieCompactionStrategy.testBoundedIOSimple is Unstable because of random compactions based on ` .map(e -> Pair.of(e, partitionPaths[RANDOM.nextInt(partitionPaths.length - 1)]))`
no
low

[HUDI-8910] Fix Unstable UT TestHoodieCompactionStrategy

---

azure-pipelines-20230430.yml

As above.  This is based on the latest run on master:
- Moves Flink tests from Job 2 to Job 1
- Moves all utilities tests from Job 6 to Job 5
Before this PR: 
After this PR:
Reduces overall Azure CI finish time to make PR landing faster.
none
N/A

[MINOR] Rebalance Azure CI jobs (2025-01-24)

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark35Analysis.scala

This PR fixes the issue that the INSERT SQL statement with a subset of columns fails on Hudi table in Spark 3.5. The same succeeds in Spark 3.4.
In Spark 3.5, the following Resolution rules are removed, `ResolveUserSpecifiedColumns` and `ResolveDefaultColumns` (see code changes in [[org.apache.spark.sql.catalyst.analysis.Analyzer]] from https://github.com/apache/spark/pull/41262). The same logic of resolving the user-specified columns and default values, which are required for a subset of columns as user-specified compared to the table schema to work properly, are deferred to `PreprocessTableInsertion` for v1 INSERT.
Note that `HoodieAnalysis` intercepts the `InsertIntoStatement` after Spark's built-in Resolution rules are applies, the logic of resolving the user specified columns and …

[HUDI-8898] Support INSERT SQL statement with a subset of columns in Spark 3.5

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java

Ensure partitions created by async indexer are not deleted by regular writers.
- Add a new metadata config to declare what metadata partitions to delete.
- Fix the condition for checking whether MDT partition needs to be deleted in `HoodieTable`
- Add a test in `TestHoodieIndexer`
Let's understand the interplay between index enable/disable boolean flag and the new config. For illustration prupose, we will assume, `files` and column_stats` are enabled by ingestion writer, and `record_index` is created using async indexer. 
Existing boolean configs: `hoodie.metadata.enable`, `hoodie.metadata.index.column.stats.enable` and `hoodie.metadata.record.index.enable`.
New string config: `hoodie.metadata.index.drop` (this takes the index name/MDT partition name as value)
1. Regular ingestion writer …

[HUDI-5769] Ensure partitions created by async indexer are not deleted by regular writers

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/BaseHoodieIndexClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/HoodieSparkIndexClient.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/expression/ExpressionIndexSparkFunctions.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieSparkIndex.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieIndexDefinition.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/main/java/org/apache/hudi/index/expression/HoodieExpressionIndex.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
hudi-utilities/src/test/resources/streamer-config/indexer-expression-index.properties
hudi-utilities/src/test/resources/streamer-config/indexer-secondary-index.properties

- Added new write configs for secondary index (SI) and expression index (EI) conformant to sql syntax for create index.
- Use those configs to check if we need to update new SI/EI definition in index definition file.
- Initialize SI/EI if a new one is being created through write configs.
- Add asyn indexer and spark datasource to validate index gets built successfully.
Support secondary and expression index creation through async indexer and write configs.
medium
- _Any new feature or user-facing change requires updating the Hudi website. Please …

[HUDI-8844] Support secondary and expression index creation through async indexer and write configs

---

dependencies/hudi-flink-bundle_2.11.txt
dependencies/hudi-flink-bundle_2.12.txt
dependencies/hudi-hadoop-mr-bundle.txt
dependencies/hudi-hive-sync-bundle.txt
dependencies/hudi-integ-test-bundle.txt
dependencies/hudi-kafka-connect-bundle.txt
dependencies/hudi-presto-bundle.txt
dependencies/hudi-spark-bundle_2.11.txt
dependencies/hudi-spark-bundle_2.12.txt
dependencies/hudi-spark3-bundle_2.12.txt
dependencies/hudi-timeline-server-bundle.txt
dependencies/hudi-utilities-bundle_2.11.txt
dependencies/hudi-utilities-bundle_2.12.txt
pom.xml

Upgrade commons-io to fix https://github.com/advisories/GHSA-78wr-2p64-hpwj
https://github.com/advisories/GHSA-78wr-2p64-hpwj:
Uncontrolled Resource Consumption vulnerability in Apache Commons IO. The org.apache.commons.io.input.XmlStreamReader class may excessively consume CPU resources when processing maliciously crafted input.
HIGH
Upgrade commons-io to 2.14.0 version

[HUDI-8805]  Upgrade commons-io version to 2.14.0 to fix CVE-2024-47554

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala

Introduced API that correctly retrieve the table schema `getTableSchemaFromLatestCommitMetadataV2`. Compared to what we previously do it only focuses on instants that can evolve table schema. We need the rest of the RFC-82 code change to be in place in order for this API to be fully functional.
Also for inline clustering it is now hard wired to use table schema as the write schema.
Table service will never use a wrong writer schema 
none
None

[HUDI-8628] Table Service writer config hard wired to table schema 

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeCommitTimeOrdering.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala

```
CREATE TABLE hudi_14_table_sql_005 (
event_id INT,
event_date STRING,
event_name STRING,
event_ts STRING,
event_type STRING
) USING hudi
OPTIONS(
type = 'cow', -- or 'mor'
primaryKey = 'event_id,event_date',
preCombileField = 'event_ts',
hoodie.write.table.version = 6
)
PARTITIONED BY (event_type)
LOCATION 's3://<some_bucket>/hudi_14_table_sql_005';
```
resulted in hoodie.table.version 8 instead of 6.
It is because when creating table the code path does not read write table version config to determine table version. Now it is added and we have warning messages that if user intends to set table version they should set the right config.
hoodie.write.table.version will also contribute to how hoodie.table.version is configured now.
none
none

[HUDI-8832] Add merge mode test coverage for DML

---

hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/ScalaTestUtils.scala

The jira aims to add an API for running a test multiple times. This is useful for assuring that the flaky tests are fixed.
NA
low
NA

[HUDI-8897] Add a Scala retry API for running test multiple times

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java
hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
hudi-common/src/main/java/org/apache/hudi/common/model/EventTimeAvroPayload.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/utils/TestHoodieArrayWritableAvroUtils.java
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/parquet/TestSparkFileFormatInternalRowReaderContext.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala

This PR simplifies precombine and ordering field value handling in the file group reader by assuming that the precombine field should not be changed after table creation, i.e., both the field name and type should not be changed.  All the type cast logic specifically for ordering value is removed.
If the user does want to change the precombine or ordering field in rare cases, we should advise them to compact the table fully first, and then change the table config through a special process through Hudi CLI for example.  After this PR, such a process can still work as the precombine and ordering value comparison only happens when merging records from base and log files.
Simplify precombine and ordering field value handling in the file group reader and avoids hidden mishandling of precombine …

[HUDI-8682] Simplify precombine and ordering field value handling in the file group reader

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/util/SparkConfigUtils.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestWriteTableVersionConfig.scala

There are 3 configs at interplay:
table config `hoodie.table.version` - can be 6 or 8
writer config `hoodie.write.table.version` - can be 6 or 8
writer config `hoodie.write.auto.upgrade` - boolean flag to control transition during upgrade, avoiding unintended upgrades.
`hoodie.table.version` reflects the **actual state** of the table.
`hoodie.write.table.version` defines the **intended state** of data written by the writer.
During upgrade, the initial phase for writers should be configured with `hoodie.write.auto.upgrade=false` and `hoodie.write.table.version=6 `until when users are ready to start writing in the new format (i.e. after all readers have been upgraded).
For creating new tables using 1.0, by default i.e. when none of the writer configs are set, hoodie.table.version should be …

[HUDI-8817] fix backward compatibility issue

---

website/docs/concurrency_control.md

Added some additional settings and requirement for Zookeeper in the HMS locking section.
None - Doc change
- Concurrency control page - clarified a mandatory requirement in the page

[DOC] Changes to Hive Metastore-based distributed locking in the Concurrency control doc.

---

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDeleteFromTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala

In the prepped DELETE operation in Spark, NPE was thrown from the `HoodieAppendHandle` for ecord merge mode of `EVENT_TIME_ORDERING` on MOR table (see stacktrace below).
The issue is that `HoodieEmptyRecord` should be generated for deletes instead of `HoodieSparkRecord` for `SPARK` record type on the write path.
New tests are added to guard DELETE SQL with different record merge modes and table types.
```
at org.apache.spark.sql.HoodieUnsafeRowUtils$.getNestedInternalRowValue(HoodieUnsafeRowUtils.scala:69)
at org.apache.spark.sql.HoodieUnsafeRowUtils.getNestedInternalRowValue(HoodieUnsafeRowUtils.scala)
at org.apache.hudi.common.model.HoodieSparkRecord.getOrderingValue(HoodieSparkRecord.java:322)
at …
```

[HUDI-8851] Fix delete record generation in Prepped DELETE operation in Spark

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala

After #12452, we disallow the type change of precombine field to be safe (which wasn't supported before in 0.x releases).  In SQL, the input precombine values must match the type of the table schema, thus the fix on `TestMergeModeEventTimeOrdering`.
Fix CI failure based on expected behavior.
none
N/A

[HUDI-8926] Fix precombine field value to be in the same type in TestMergeModeEventTimeOrdering

---

hudi-sync/hudi-datahub-sync/pom.xml
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubResponseLogger.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubTableProperties.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/util/SchemaFieldsUtil.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestDataHubSyncConfig.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestHoodieDataHubDatasetIdentifier.java
packaging/hudi-datahub-sync-bundle/pom.xml

Applies PR #12456 on top of branch-0.x branch.
And supersedes PR #12565 
From PR #12456
> This update significantly enhances the integration by providing richer information.
Low, as per PR #12456

[HUDI-8616] DataHub meta sync improvements (#12456)

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/CheckpointUtils.java
hudi-common/src/test/java/org/apache/hudi/common/table/checkpoint/TestCheckpointUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV1.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV2.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamerCheckpointUtils.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/CheckpointValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/DummyOperationExecutor.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/MockGcsEventsHoodieIncrSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/MockS3EventsHoodieIncrSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSourceHarness.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestS3GcsEventsHoodieIncrSourceE2ECkpVersion.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamerCheckpointUtils.java

Fixed and bump up massive test coverage for checkpoint and some missing coverage when related code is introduced
```
public Pair<InputBatch, Boolean> readFromSource(String instantTime, HoodieTableMetaClient metaClient) throws IOException {
// Retrieve the previous round checkpoints, if any. Consumption of checkpoint
Option<Checkpoint> checkpointToResume = StreamerCheckpointUtils.getCheckpointToResumeFrom(commitsTimelineOpt, cfg, props);
public static Option<Checkpoint> getCheckpointToResumeFrom(Option<HoodieTimeline> commitsTimelineOpt,
HoodieStreamer.Config streamerConfig,
TypedProperties props) throws IOException {
Option<Checkpoint> checkpoint = Option.empty();
if (commitsTimelineOpt.isPresent()) {
checkpoint = getCheckpointToResumeString(commitsTimelineOpt, streamerConfig, props);
} …
```

[HUDI-8726] s3/gcs incremental source should stick to checkpoint v1

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/HoodieRollbackTestBase.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/TestBaseRollbackHelper.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/TestMarkerBasedRollbackStrategy.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/TestRollbackUtils.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java

When there are multiple log files generated in the same file group in a inflight deltacommit, rollback of such a deltacommit can fail, because (1) the rollback plan contains multiple rollback requests targeting the log files to roll back in the same file group (2) concurrent execution of these rollback requests in Spark executors cause creation of new rollback log files (appending rollback blocks) in parallel, which involves determining the new log version concurrently, leading to the same new log version to be used in multiple executors, causing marker creation to fail (i.e., multiple executors try to create the marker on the same file name, and subsequent marker creation requests fail due to the fact that marker already exists).
Note that this problem only happens for table version 6 …

[HUDI-8808] Fix concurrent execution of appending rollback blocks in the same file group

---

hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala

Use payload to do merging inside of expression payload.
If your tables payload was overwrite with latest, and you did MIT, it would use ordering field if defined. Now we will use the actual payload.
For MIT update, the payload would be honored. For delete it still does not honor the payload logic. Today's behavior is it will always delete even using event ordering and incoming record precombine field value is smaller.
Low. There can be performance hit for customized payload since we use reflection for every record.
none

[HUDI-8468] use payload to do merging inside the expression payload 

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala

Ignoring PSI lookup for filters w/ nulls. Null counts and value counts stored in PSI may not be reliable. Hence, avoiding the lookup for such filters. 
Ignoring PSI lookup for filters w/ nulls. Null counts and value counts stored in PSI may not be reliable. Hence, avoiding the lookup for such filters. 
low
changes to the …

[HUDI-8895] Ignoring PSI lookup for filters w/ nulls

---

hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeCommitTimeOrdering.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala

This PR fixes record merge mode related issues and improves test coverage in Spark SQL:
- Table version 6 does not have record merge mode in the table config.  The file group reader is changed to infer the record merge mode if it does not exist in the table config, so it can read Hudi table of version 6.
- For INSERT INTO in Spark SQL, the write config of record merge mode is not properly determined in `buildHoodieInsertConfig`.  The relevant logic is removed since the SQL writer can automatically get the correct write config of record merge mode from the table config.
- In MERGE INTO in Spark SQL, the record merge mode check is fixed to avoid NPE.
- More tests are added in `TestMergeModeCommitTimeOrdering` and `TestMergeModeEventTimeOrdering` to coverage different cases of merge modes …

[HUDI-8850] Fix record merge mode related issues and improve test coverage in Spark SQL

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestBucketizedBloomCheckPartitioner.java

- The current code creates two copies of the data when only one is required. This will help reduce overhead. 
- Reduces shuffle cost when using bloom index and fanning out the comparisons to different spark partitions
None

[MINOR] Fix bloom index shuffle setup

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala

Currently partition stats avoids data skipping if even one of the query filters has a null, value count based expression. Or if any query uses a complex expression like expression index.
The jira aims to fix the logic so that index only filters out such queries and performs pruning based on the other queries.
For example Spark automatically adds query isNotNull on a column like:- isnotnull(driver#869) when an equality query on driver is used. We can ignore such queries for partition stats.
NA
low
NA

[HUDI-8943] Partition stats should skip queries with null or complex expressions

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java

Currently, the following queries execution by Flink:
```SQL
CREATE TABLE hudi_debug (
id INT,
part INT,
desc STRING,
PRIMARY KEY (id) NOT ENFORCED
) 
WITH (
'connector' = 'hudi',
'path' = '...',
'table.type' = 'MERGE_ON_READ',
'write.operation' = 'upsert',
'hoodie.populate.meta.fields' = 'false'
); 
INSERT INTO hudi_debug VALUES 
(1,100,'aaa'),
(2,200,'bbb'); 
SELECT * FROM hudi_debug; 
```
would result in
```text
org.apache.hudi.exception.HoodieException: Exception when reading log file
```
The reason is missed configuration of `hoodie.populate.meta.fields` during table initialization by Flink.
Proposed changes allow to run successfully 
```SQL
SELECT * FROM hudi_debug
```
Fixed read by Flink of data without Hudi metacolumns.
Low
No need

[HUDI-8785] Missed set of `POPULATE_META_FIELDS` parameter during table initialization by Flink

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/util/SparkConfigUtils.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java

https://github.com/apache/hudi/pull/12600 added a validation to ensure mode based on payload class and record merger strategy is same - [https://github.com/apache/hudi/blob/27a950ee22320d7b447fd3e31693ae9290dd5842/hudi-[…]c/main/java/org/apache/hudi/common/table/HoodieTableConfig.java](https://github.com/apache/hudi/blob/27a950ee22320d7b447fd3e31693ae9290dd5842/hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java#L785)
In 0.14/0.15 we had just one default record merger strategy (which now corresponds to event time) - https://github.com/apache/hudi/blob/38832854be37cb78ad1edd87f515f01ca5ea6a8a/hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java#L175.
Users starting with overwrite payload in 0.x will have payload class as overwrite payload, …

[HUDI-8942] Validate merge mode based on payload class and merger strategy only for table versions 8 or higher

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/JavaTestUtils.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

The PR adds test for the following scenarios.
a. Spark datasource ingestion (OR streamer all inline) going on. User is trying to build index via indexer concurrently (w/o stopping the main writer)
b. deltastreamer + async clustering ongoing. User concurrently builds the index via indexer.
NA
low
NA

[HUDI-8607] Test concurrent indexing with multi writer scenarios

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala

The PR fixes the code to use filtered query filters in Partition Stats Index pruning. We are using original query filters while creating the index filter.
NA
low
NA

[HUDI-8948] Use filtered query filters in Partition Stats Index pruning

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/providers/HoodieMetaClientProvider.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandleWithChangeLog.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandleWithChangeLog.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormat.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeCommitTimeOrdering.scala

We found an issue, where log file naming and creation logic with table version 6 could end up deleting already committed log files. Fixing the  same in this patch. 
Robust log file naming and no data consistency issues with table version 6 writes. 
medium

[HUDI-8947] Fixing log file naming with MOR table writes using table version 6

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieIncrSourceE2E.java

Checkpoint version is also a func of target table version. But one of the recent validations we aded started failing for custom sources when we try creating table with version 6. Relaxing the constraint for now. We will follow up w/ a proper fix later. 
Checkpoint version is also a func of target table version. But one of the recent validations we aded started failing for custom sources when we try creating table with version 6. Relaxing the constraint for now. We will follow up w/ a proper fix later. 
low
- _Any new feature or user-facing change …

[HUDI-8949] Relaxing checkpoint validation for HoodieStreamerSources

---

.github/workflows/maven_artifact_validation.yml
.github/workflows/release_candidate_validation.yml
packaging/bundle-validation/README.md
packaging/bundle-validation/ci_run.sh
release/release_guide.md

Currently, we have bundle validation for artifacts staged in nexus repo. To ensure the necessary bundles are released to maven central, we should validate the bundles after they appear in maven central.
- Add bundle validation for release artifacts in maven central
- Update release guide to run this validation after artifacts appear in maven central
- Update how to run this validation in bundle validation README
Ensuring release artifacts in Maven central are valid.
none …

[HUDI-8767] Add bundle validation for release artifacts in Maven central

---

hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java

This change included on Hudi 1.0 require hoodie.base.path to exist in the props #11498 
But when running Hudi jobs with dataframe api, users are not required to configure `hoodie.base.path` explicitly, causing metrics feature not usable due to the exception below:
```
Caused by: org.apache.hudi.exception.HoodieException: Unable to instantiate class org.apache.hudi.hive.HiveSyncTool
at org.apache.hudi.common.util.ReflectionUtils.loadClass(ReflectionUtils.java:75) ~[hudi-spark3-bundle_2.12-1.0.0.jar:1.0.0]
at org.apache.hudi.sync.common.util.SyncUtilHelpers.instantiateMetaSyncTool(SyncUtilHelpers.java:140) ~[hudi-spark3-bundle_2.12-1.0.0.jar:1.0.0]
at org.apache.hudi.sync.common.util.SyncUtilHelpers.runHoodieMetaSync(SyncUtilHelpers.java:103) ~[hudi-spark3-bundle_2.12-1.0.0.jar:1.0.0]
... …
```

[HUDI-8950] Explicitly set base path in sync config

---

hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

CI is broken now due to flaky `TestHoodieDeltaStreamer::testHoodieIndexerExecutionAfterClustering`.
A lot of failed runs:
https://dev.azure.com/apachehudi/hudi-oss-ci/_build/results?buildId=3363&view=results
https://dev.azure.com/apachehudi/hudi-oss-ci/_build/results?buildId=3364&view=results
Temporarily disabled flaky test.
None
No need

[HUDI-8951] Disabled flaky `TestHoodieDeltaStreamer::testHoodieIndexerExecutionAfterClustering`

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java

- Fixing Compaction scheduling for tbl v6. w/ Table version 6, when there are pending delta commits, we can't schedule compaction. So, this fixes the backwards compatible writer for compaction scheduling. 
- Fixing Compaction scheduling for tbl v6. w/ Table version 6, when there are pending delta commits, we can't schedule compaction. So, this fixes the backwards compatible writer for compaction scheduling. 
low
ticket number here and …

[HUDI-8989] Fixing Compaction scheduling for tbl v6

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestGlobalIndex.scala

We prepend the meta fields, but used schema without meta fields for converting records to payload
Fix problem with update/insert overwrite mor table with global index
NA
None

[HUDI-8569] Fix Insert overwrite / update MOR with global index does not work

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-common/src/main/java/org/apache/hudi/exception/HoodieDuplicateDataFileDetectedException.java

The PR adds a config which fails the entire job if an invaild file is detected. The config is disabled by default.
NA
low
NA

[HUDI-8967] Add a config to fail job if duplicate data files detected during reconcileAgainstMarkers

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

Currently metadata table validator fails if table is not found at the base path. The jira aims to add a fix so that the validator can ignore such an error.
NA
low
NA

[HUDI-8959] HoodieMetadataTableValidator can skip validation if data table is not found

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/TestHoodieTable.java

During rollbacks, we avoid rescheduling existing rollbacks.
More efficient.
Low.

[HUDI-8922] Avoid rescheduling pending rollbacks

---

website/contribute/developer-setup.md
website/contribute/developer-sync-call.md
website/contribute/report-security-issues.md
website/contribute/rfc-process.md
website/docusaurus.config.js

Add page for developer sync call. And align the ordering of the items between drop down and sidebar.

[SITE] Add developer sync call page

---

hudi-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieAvroDataBlock.java

Recently i faced this failure:  
`Error:    TestHoodieAvroDataBlock.testGetRecordIteratorWithInputStream:188->verifyRecords:360 Record count mismatch ==> expected: <0> but was: <1000>`  
That happened because of unnecessary random value generation in `selectRandomRecords`: as a number of selected records was randomly generated 0 value, so it returned an empty list `recordsForFilter` (and `keysForFilter`). Later, when we call `dataBlock.getRecordIterator` with empty list as `keysForFilter`, it returns all records, and it causes records verification to fail.  
This PR fixes it by not using Random for generating number of selected records, just use value `allRecordsNum/4`.
fix flaky test
none
none
- _The config description must be updated if new configs are added or the default value of the …

[MINOR] Fix flaky TestHoodieAvroDataBlock

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java

Fixing metadata metrics to honor metrics prefix. 
Fix: Will honor the metrics prefix with "_metadata" suffixed. 
For eg, incase of "clean_duration" metric:
with metrics prefix set to "ohds":
data table metric name => "ohds_clean_duration" 
and metadata metric name => "ohds_metadata_clean_duration" 
One set of metrics for metadata table. 
I could not write an automated tests. But manually verified by using console metrics. 
```
ohds.timer.deltastreamer
ohds_metadata.timer.deltacommit
```
Prior to the fix, each metric for metadata will have the table name prefixed w/ metric name. For datatable, still the metircsPrefix was honored. 
```
ohds.timer.deltastreamer
hoodie_trips_metadata.timer.deltacommit
```
low
_Describe any necessary documentation update if there is any new feature, config, or …

[HUDI-8971] Fixing metadata metrics to honor metrics prefix

---

hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java

- Updates `FSUtils#getAllDataFilesInPartition` to return an empty list if a `FileNotFoundException` is thrown. Currently the code will do another check to see if the path exists but this exception type will only be thrown when the path does not exist. This can result in a potential race condition if there is another thread creating that directory. The FS API also states that it `Throws: FileNotFoundException – when the path does not exist`
- Fixes exception thrown in flakey test `Test Bulk Insert Into Consistent Hashing Bucket Index Table`
Low
- _Any …

[HUDI-9009] Fix potential race condition when listing files by leveraging exception type

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

Every commit is expected to release resources irrespective of whether it succeeds or fail. But in HoodieStreamer, in some unhappy paths, we missed to do that. And so, the heart beat could potentially be getting updated for a failed ingestion commit which in turn will never get a chance to rollback by async workers (STS). We are fixing the resource closure ( and hence the heart beat emitting) for failed writes in HoodieStreamer in this patch. 
Tests have been written to validate both happy and unhappy paths. 
Robust closure of resources and heart beat stoppage for failed commits in HoodieStreamer. 
low
- _The config description must be updated if new configs are …

[HUDI-8972] Fixing heart beats for failed writes in HoodieStreamer

---

azure-pipelines-20230430.yml
pom.xml
scripts/jacoco/README.md
scripts/jacoco/download_jacoco.sh
scripts/jacoco/generate_jacoco_coverage_report.sh
scripts/jacoco/merge_jacoco_exec_files.sh
scripts/jacoco/merge_jacoco_job_files.sh

This PR enables a single Jacoco code coverage report aggregated across all modules.  The Jacoco code coverage report is published to Azure DevOps, and attached to the pipeline run.  We'll explore Codecov coverage report visualization in a follow-up.
We used to report code coverage on each PR in early days (see https://github.com/apache/hudi/pull/1667#issuecomment-633665810, screenshot below).  However, we have disabled it due to several problems:
- We now use Azure DevOps Pipeline as CI to run tests in multiple jobs.  Due to permission issues, we mirror the repo and branch for running the tests.  This creates hurdles in reporting aggregation.
- Hudi project contains multiple source modules.  There has been multiple code refactoring iterations around module organization so that some …

[HUDI-7596] Enable Jacoco code coverage report across multiple modules

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/FlinkTaskContextSupplier.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/JavaTaskContextSupplier.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkTaskContextSupplier.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/common/engine/LocalTaskContextSupplier.java
hudi-common/src/main/java/org/apache/hudi/common/engine/TaskContextSupplier.java
hudi-common/src/main/java/org/apache/hudi/metrics/InMemoryMetricsReporter.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestColStatsRecordWithMetadataRecord.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java

Adding more logs during indexing
Adding more logs during indexing
low

[HUDI-8962] Adding more logs during indexing

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java

* Add condition before the initTable transaction to check whether table upgrade / downgrade is needed and if metadata table is enabled.
* This avoids lock contention when many writes tries to run doInitTable transaction even though it's not necessary.
Avoids lock contention when many writes tries to run doInitTable transaction
Low
None
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setup#webs …

[HUDI-9039] Run do init table transaction only when required

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java

Similar like https://github.com/apache/hudi/pull/12466 ,  this PR add time instant metrics for compaction、clean、rollback：
earliest_inflight_XXX_instant
latest_completed_XXX_instant
clustering_pendingXXXCount
Also, this PR refine the whole code impl.
hudi-client-common
Low
None

[HUDI-8882] Support Compaction/Rollback/Clean Timeline Instant Metrics in HoodieMetrics

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieErrorTableConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/SourceCommitCallback.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractCloudObjectsSourceTestBase.java

Persist the sourceRDD in fetchNext method for optimising error table DAG. It helps in avoiding expensive source reads when writing to the error table.
Cuts down the overall e2e sync latency when `hoodie.errortable.enable` is enabled  as we will avoid reading from the source twice.
Ran a load test by ingesting 15GB to see the improvements for the three approaches.
Union DAG Optimisation PR -> https://github.com/apache/hudi/pull/11843/files
```
1. Current version ➝ 1h 29min. 
2. Union DAG Optimisation ➝ 1h 9min. 
3. Source RDD Persist + Union DAG Optimisation ➝ 43min.
```
Medium.
```
public static final ConfigProperty<Boolean> ERROR_TABLE_PERSIST_SOURCE_RDD = ConfigProperty
.key("hoodie.errortable.source.rdd.persist")
.defaultValue(false)
.withDocumentation("Enabling this config, persists …
```

[HUDI-8126] Persist sourceRdd to optimise writeStatus DAG

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/compact/TestScheduleCompactionActionExecutor.java

Compaction Planners can make use of extraMetadata to decide which partitions/file groups to compact, eg: extraMetadata can be used to keep track of previous compaction results.
Provides ability to write compaction planner which can make use of extraMetadata to decide which partitions/file groups to compact. 
Low
```
public static final ConfigProperty<String> COMPACTION_PLAN_GENERATOR = ConfigProperty
.key("hoodie.compaction.plan.generator")
.defaultValue(HoodieCompactionPlanGenerator.class.getName())
.markAdvanced()
.withDocumentation("Compaction plan generator for data files. Override with a custom plan generator "
+ "if there's a need to use extraMetadata in the compaction plan for optimizations, ignore otherwise");
```

[HUDI-8883] Add ability to configure HoodieCompactionPlanGenerator using reflection

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java

Fixed the **schedule** alias name from **sc** to **sch**.
**Before fixing the issue:**
```sh
% spark-submit \
--class org.apache.hudi.utilities.HoodieCompactor \
packaging/hudi-utilities-bundle/target/hudi-utilities-bundle_2.12-1.1.0-SNAPSHOT.jar \
--base-path /tmp/hudi/hudi-test-topic \
--table-name hudi-test-topic
```
```sh
25/02/13 15:33:59 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Exception in thread "main" org.apache.hudi.com.beust.jcommander.ParameterException: Found the option -sc multiple times
at org.apache.hudi.com.beust.jcommander.JCommander.addDescription(JCommander.java:627)
at org.apache.hudi.com.beust.jcommander.JCommander.createDescriptions(JCommander.java:594)
at org.apache.hudi.com.beust.jcommander.JCommander.<init>(JCommander.java:249)
at …
```

[HUDI-9016] Fix the HoodieCompactor schedule parameter alias name

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
hudi-client/hudi-spark-client/pom.xml
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestWriteMarkersBase.java
hudi-common/pom.xml
hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
hudi-common/src/main/java/org/apache/hudi/timeline/TimelineServiceClient.java
hudi-common/src/main/java/org/apache/hudi/timeline/TimelineServiceClientBase.java
hudi-common/src/test/java/org/apache/hudi/timeline/TestTimelineServiceClient.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TimelineServiceTestHarness.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
pom.xml

Since there are no retries, requests to timeline services may sometime get assigned to a connection pool with a broken connection and fail. This is an issue specific to fluent HTTP client, and can be solved using retries.
It changes the code path for timeline network calls for Remote File System View and Markers.
Medium. …

[HUDI-8988] Implement retry logic for all HTTP calls to timeline server including remote file system view and markers

---

hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CompletionTimeQueryViewV2.java

- Fixes bug in `getInstantTimes` where the output is not sorted
- The interface declares that the output is expected to be sorted but there is a case where it is not and ordering is random. This breaks the contract of the interface. The code change here fixes that.
None

[HUDI-9059] Fix ordering of getInstantTimes in CompletionTimeQueryViewV2

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieTableServiceClient.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaTableServiceClient.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkClusteringCornerCases.java

When clustering plan has log files which delete all records in the base file, the clustering used to fail before, now the validation has been removed. 
20250130014738074.replacecommit
```
{
"partitionToWriteStats" : { },
"compacted" : false,
"extraMetadata" : {
"schema" : "{\"type\": \"record\",\"name\": \"triprec\",\"fields\": [ {\"name\": \"timestamp\",\"type\": \"long\"},{\"name\": \"_row_key\", \"type\": \"string\"},{\"name\": \"partition_path\", \"type\": [\"null\", \"string\"], \"default\": null },{\"name\": \"trip_type\", \"type\": {\"type\": \"enum\", \"name\": \"TripType\", \"symbols\": [\"UNKNOWN\", \"UBERX\", \"BLACK\"], \"default\": \"UNKNOWN\"}},{\"name\": \"rider\", \"type\": \"string\"},{\"name\": \"driver\", \"type\": \"string\"},{\"name\": \"begin_lat\", \"type\": …
```

[HUDI-9060] Remove validations for clustering metadata

---

hudi-client/hudi-spark-client/pom.xml
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/ProtoKafkaSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
packaging/hudi-integ-test-bundle/pom.xml
packaging/hudi-spark-bundle/pom.xml
packaging/hudi-utilities-bundle/pom.xml
packaging/hudi-utilities-slim-bundle/pom.xml
pom.xml

NOTE: Stacked on top of https://github.com/apache/hudi/pull/11844
Persisting a proto RDD<Message> is failing because KyroSerializer in Spark doesn't have handling for proto messages and failing with errors like this.
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1) (vinish-ka-mbp executor driver): com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
dependencies (com.google.protobuf.Descriptors$DescriptorPool)
pool (com.google.protobuf.Descriptors$FileDescriptor)
file (com.google.protobuf.Descriptors$FieldDescriptor)
fields (com.google.protobuf.Descriptors$Descriptor)
containingType (com.google.protobuf.Descriptors$Descriptor)
descriptor …
```

[HUDI-8126] Support proto messages for spark kryo serializer excluding DynamicMessages

---

hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
hudi-common/src/main/java/org/apache/hudi/common/serialization/HoodieFileSliceSerializer.java
hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
hudi-common/src/test/java/org/apache/hudi/common/serialization/TestHoodieFileSliceSerializer.java
hudi-common/src/test/java/org/apache/hudi/common/util/TestConfigUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/bootstrap/index/TestBaseHoodieTableFileIndex.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java

`cachedAllInputFileSlices` in `BaseHoodieTableFileIndex` is using a HashMap, when doing multiple queries on large tables (1000+ partitions and each partition has 20K file groups/slices for example) on a single spark driver we cache all the file slices for queried partitions. This overwhelms the driver especially in the scenario when there are multiple downstream consumers for the same table and the ingestion/spark sql is running on the same driver.  
Using an `ExternalSpillableMap` for cachedAllInputFileSlices to not overwhelm the spark driver in such cases.  The default value for `HOODIE_FILE_INDEX_SPILLABLE_MEMORY` is 500MB
Medium 
```
public static final ConfigProperty<Long> HOODIE_FILE_INDEX_SPILLABLE_MEMORY = ConfigProperty
.key("hoodie.file.index.cache.spillable.mem") …
```

[HUDI-8868] Use external spillable map for cachedAllInputFileSlices in BaseHoodieTableFileIndex

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieErrorTableConfig.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieErrorTableConfig.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerErrorTableWriteFlow.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java

Enable writing of error and data table in parallel. This behavior is disabled by default and can enabled by setting error table config property: `hoodie.errortable.write.union.enable` to true.
The DAG's for data table + error table are sequential today, this change executes them in a union to better utilize the executor resources in the spark driver.
Low. 
```
public static final ConfigProperty<Boolean> ENABLE_ERROR_TABLE_WRITE_UNIFICATION = ConfigProperty
.key("hoodie.errortable.write.union.enable")
.defaultValue(false)
.withDocumentation("Enable error table union with data table when writing for improved commit performance. "
+ "By default it is disabled meaning data table and error table writes are sequential");
```

[HUDI-8126] Use union to parallelize data and error table writes

---

hudi-common/src/main/java/org/apache/hudi/common/fs/SizeAwareDataInputStream.java
hudi-common/src/test/java/org/apache/hudi/common/fs/TestSizeAwareDataInputStream.java

1. Improve SizeAwareDataInputStream to implement idempotent
2. Improve SizeAwareDataInputStream#skipBytes to avoid potential skip byte count errors
Enhance robustness
none
none

[HUDI-8501] Improve SizeAwareDataInputStream to implement idempotent

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaSourceUtil.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroKafkaSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaSourceUtil.java
hudi-utilities/src/test/resources/schema/evolved-test-with-default-value.avsc

Add consumer group id to kafka params based on the schema hash when KafkaAvroSchemaDeserializer is used to avoid kafka connector caching the KafkaConsumer causing issues with schema evolution.
Kafka connector will create a new Kafka consumer whenever there's a change in the schema instead of using cached kafka consumer.
NA …

[HUDI-8378] Fix Avro schema deserializer failing with schema evolution

---

packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh

The Hudi CLI bundle script currently overwrites the user-defined `HUDI_CONF_DIR` environment variable with a hardcoded path. This causes hudi configuration file loading failures when users attempt to use their own custom configuration directory. The issue remained undetected because when `HUDI_CONF_DIR` is not set by users, the script works as expected, the conflict only surfaces when users explicitly set `HUDI_CONF_DIR` environment variable.
https://github.com/apache/hudi/issues/11909
None
None
None

[HUDI-9070] Fix Hudi cli bundle script to use HUDI_CONF_DIR environment variable

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/BaseFileHandler.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/Handler.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/InstantStateHandler.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/TimelineHandler.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/MockHoodieHadoopStorage.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TestRequestHandler.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TestTimelineService.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TimelineServiceTestHarness.java
hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/perf/TimelineServerPerf.java

Timeline server currently caches the hoodie storage which it further uses to process all the requests. When reuse timeline server is enabled, same timeline server can be used by different streams. If two streams are from two different lakes(or buckets) this would fail. 
`{
"exception": {
"stacktrace": "java.lang.IllegalArgumentException: Wrong FS s3a:/ABCD\/v1\/.hoodie\/.temp\/20250122111902624 -expected s3a:\/\/<lake2>l\n\tat org.apache.hadoop.fs.s3native.S3xLoginHelper.checkPath(S3xLoginHelper.java:224)\n\tat org.apache.hadoop.fs.s3a.S3AFileSystem.checkPath(S3AFileSystem.java:1155)\n\tat org.apache.hadoop.fs.FileSystem.makeQualified(FileSystem.java:666)\n\tat org.apache.hadoop.fs.s3a.S3AFileSystem.makeQualified(S3AFileSystem.java:1117)\n\tat …

[HUDI-8901] Fix Timeline Server to process requests from multiple storage lakes

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIdentifier.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkInternalRow.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkInternalRowSerializer.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkInternalRowTypeInfo.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/batch/BatchBootstrapOperator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteOperator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/ConsistentBucketAssignFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/ConsistentBucketStreamWriteFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunctionWithRateLimit.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunctions.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/PayloadCreation.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestConsistentBucketStreamWrite.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/ConsistentBucketStreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java

Changes in Flink stream write into Hudi table corresponding to [Design of RFC-84, Optimized SerDe of DataStream in Flink operators](https://github.com/apache/hudi/pull/12697).
Architecture of Flink write pipelines: https://miro.com/app/board/uXjVLsCpf48=/
Changes in this PR doesn't affect bulk insert and append mode.
Main points:
- `HoodieFlinkInternalRow` is introduced. It doesn't extend `HoodieRecord` because we need to create data structure with Flink row data and Hudi metadata, constructed from Flink internal data types.
- `HoodieFlinkInternalRow` is effective for Flink processing due to implemented `HoodieFlinkInternalRowTypeInfo` and `HoodieFlinkInternalRowSerializer` with custom `serialize` and `deserialize` methods.
`Lineitem` table from TPC-H benchmark was used. 60 mln rows, from …

[HUDI-8920] [RFC-84] Optimize SerDe of stream records for Flink write (excluding bulk insert and append mode)

---

hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

bump up unit test coverage
MDT validator should be configurable on if log truncation is required. Otherwise, we might stuck in a situation where we could not get the full list of mismatches at all.
Now to avoid truncation, just give a none positive value to --log-detail-max-length option. By default it uses value 1e5.
Better operation experience when using this utility.
none
none

[HUDI-9071] MDT validator can configure if log truncation applies

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableRenameCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala

Instead of using `catalogTable.storage.locationUri.get.getPath` that could remove scheme and authority, simply use `catalogTable.location` instead when resetting table path in rename command.
none
low
none

[HUDI-9040] Set the correct table path when renaming tables

---

hudi-common/src/main/avro/HoodieCommitMetadata.avsc
hudi-common/src/main/avro/HoodieReplaceCommitMetadata.avsc
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieReplaceCommitMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CommitMetadataSerDeV2.java
hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieCommitMetadata.java
hudi-common/src/test/java/org/apache/hudi/common/table/timeline/versioning/BaseTestCommitMetadataSerDe.java
hudi-common/src/test/java/org/apache/hudi/common/table/timeline/versioning/v1/TestCommitMetadataSerDeV1.java
hudi-common/src/test/java/org/apache/hudi/common/table/timeline/versioning/v2/TestCommitMetadataSerDeV2.java

Previously for CommitMetadataSerDeV2 to handle the deserialization logic this is how it works:
avro binary array 
-> deserialize to hoodie commit metadata object of Avro auto generated class, org.apache.hudi.avro.model.HoodieReplaceCommitMetadata
-> serialize to json binary 
-> deserialize to commit metadata java pojo class object, org.apache.hudi.common.model.HoodieCommitMetadata
conversion from  Java POJO
It can be avoided as com.fasterxml.jackson.databind.ObjectMapper provides API for direct conversion from Avro class to Java pojo class.
As we wrote comprehensive unit test, we found that the Avro class definitions miss a few data members that are presented in the POJO class definition. As a result, the value of those data members are lost at serialization-deserialization process. …

[HUDI-8992] Fix serde issues in commit metadata

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java

Bloom Index causes data skew when bucketized partitioning is used, during repartition and sorting stage when there are hollow buckets created. This happens when there are lot of writes to one partition and few writes to other partitions.
In this pr, we're partitioning based on the fileId + recordKey sort partitioner which distributes the keys equally while keeping same fileIds together.
Bloom Index can now use fileId and recordkey based partitioner to distribute the comparisons equally across partitions where bucketized partitioning is causing data skew.
Medium
Added Functional Tests
```java
public static final ConfigProperty<String> BLOOM_INDEX_FILE_GROUP_ID_KEY_SORT_PARTITIONER = ConfigProperty
.key("hoodie.bloom.index.fileId.key.sort.partitioner")
.defaultValue("false")
.markAdvanced() …
```

[HUDI-8940] Fix Bloom Index Partitioner to distribute keys uniformly across partitions

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala

use the util method to get the config or default
default for the config is used
low
N/A

[HUDI-8577] Use config default for query type in default source in Spark

---

website/docs/hudi_stack.md
website/versioned_docs/version-1.0.0/hudi_stack.md
website/versioned_docs/version-1.0.1/hudi_stack.md

fix typo
this PR is just to fix a typo
No impact on any API or functionality, this is purely typo fix.
low risk, just a text change
This is an update to the documentation

[DOCS] Typo fix in hudi_stack.md

---

website/docs/quick-start-guide.md
website/docs/write_operations.md
website/versioned_docs/version-1.0.1/quick-start-guide.md
website/versioned_docs/version-1.0.1/write_operations.md

* Missing indentation formatting for "Merging Data" code example.
* Typo: rerwrite -> rewrite
For the following:

[DOCS] Fix minor website typos

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTableColumnTypeMismatch.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestTableColumnTypeMismatch.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoLogOnlyTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTableWithNonRecordKeyField.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeCommitTimeOrdering.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala

Merge into updated & insert actions will fail the query once detect column type mismatch for primary key/partition key/precombined key
Allowing implicit casting of partition key can leads to partition path corruption. An example is if we do MIT where source table has a double value column and target table partitions on the same column with int type, after merge into completes the partition path will contain double value. Later select queries over the table will complain it cannot convert double to int.
Allowing implicit casting of primary key can leads to data correctness issue. Here is an example:
```
create table $targetTable (
id double,
name string,
value_double double,
ts long
) using hudi
location '${tmp.getCanonicalPath}/$targetTable'
type = '$tableType',
primaryKey …
```

[HUDI-8486] Enforce data type match for required columns in Spark SQL MERGE INTO

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockSubtaskGateway.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
hudi-flink-datasource/hudi-flink1.14.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
hudi-flink-datasource/hudi-flink1.15.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
hudi-flink-datasource/hudi-flink1.16.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
hudi-flink-datasource/hudi-flink1.17.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java

cherry-pick #12849
Send commit ack event when reuse instant that recovered from checkpoint to unblock write tasks
low

[HUDI-9041] Send commit ack event when reusing current instant

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestTableColumnTypeMismatch.scala

Tested what happens in case we update partition column with mismatch data type.
better test coverages
none
none

[HUDI-8486] Add column mismatch test coverage

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java

Fix the HoodieClusteringJob duplicate parameter alias. Corrected the alias from "-sc" to "-sch"
**Exception:**
```
25/02/28 23:39:50 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Exception in thread "main" org.apache.hudi.com.beust.jcommander.ParameterException: Found the option -sc multiple times
at org.apache.hudi.com.beust.jcommander.JCommander.addDescription(JCommander.java:627)
at org.apache.hudi.com.beust.jcommander.JCommander.createDescriptions(JCommander.java:594)
at org.apache.hudi.com.beust.jcommander.JCommander.<init>(JCommander.java:249)
at org.apache.hudi.utilities.HoodieClusteringJob.main(HoodieClusteringJob.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.j …
```

[HUDI-9093] Fix the HoodieClusteringJob duplicate parameter alias

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToFiveUpgradeHandler.java

Fixed the default partition migration steps.
```scala
"default" partition detected. From 0.12, we are changing the default partition in hudi to "__HIVE_DEFAULT_PARTITION__". Please read and write back the data in "default" partition in hudi to new partition path "__HIVE_DEFAULT_PARTITION__". "
Sample spark command to use to re-write the data: 
val df = spark.read.format("hudi").load(HUDI_TABLE_PATH).filter(col("PARTITION_PATH_COLUMN") === "default"); 	 
df.drop("_hoodie_commit_time").drop("_hoodie_commit_seqno").drop("_hoodie_record_key")
.drop("_hoodie_partition_path").drop("_hoodie_file_name").withColumn(PARTITION_PATH_COLUMN,"__HIVE_DEFAULT_PARTITION__")
.write.format("hudi").options(writeOptions).mode(Append).save(HUDI_TABLE_PATH);
Please fix values for PARTITION_PATH_COLUMN, …
```

[HUDI-9079] Log the exception message properly to handle the "default" partition

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestInsertDedupPolicy.scala

The issue was already fixed in https://github.com/apache/hudi/commit/ef9ab24cff93a4130c1b3477454dbc8e9eb7eeee. Just adding a test here to validate that RLI/SI return correct data with different insert dups plocies.
Test coverage
none

[HUDI-8745] Add tests for record index and secondary index with insert dups policy

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/common/TestHoodieSparkEngineContext.java

- Fixing num spark tasks for clean action. 
Validated the fix using simple quick start. 
```
import scala.collection.JavaConversions._
import org.apache.spark.sql.SaveMode._
import org.apache.hudi.DataSourceReadOptions._
import org.apache.hudi.DataSourceWriteOptions._
import org.apache.hudi.common.table.HoodieTableConfig._
import org.apache.hudi.config.HoodieWriteConfig._
import org.apache.hudi.keygen.constant.KeyGeneratorOptions._
import org.apache.hudi.common.model.HoodieRecord
import spark.implicits._
val tableName = "trips_table1"
val basePath = "file:///tmp/trips_table1"
val columns = Seq("ts","uuid","rider","driver","fare","city")
val data =
Seq((1695159649087L,"334e26e9-8355-45cc-97c6-c31daf0df330","rider-A","driver-K",19.10,"san_francisco"), …
```

[HUDI-9067] Fixing num spark tasks for clean action

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java

Currently the RDD partition id is incorrectly used as the bucket id to generate the file id.
1. fix generating file id with wrong bucket index
low
none …

[MINOR] Fix generating file id with wrong bucket index

---

scripts/jacoco/merge_jacoco_exec_files.sh

This PR adds retries and logs to merging Jacoco execution data files to debug the following error from Jacoco CLI:
```
Jacoco CLI jar: jacoco-lib/lib/jacococli.jar
Hudi source directory: /home/vsts/work/1/s
[INFO] Loading execution data file /home/vsts/work/1/s/hudi-client/hudi-spark-client/target/jacoco-agent/jacoco1.exec.
[INFO] Loading execution data file /home/vsts/work/1/s/hudi-client/hudi-spark-client/target/jacoco-agent/jacoco2.exec.
Exception in thread "main" java.io.EOFException
at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
at org.jacoco.cli.internal.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
at org.jacoco.cli.internal.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
at …
```

[MINOR] Add retries and logs to merging Jacoco execution data files

---

hudi-utilities/pom.xml
packaging/hudi-utilities-bundle/pom.xml
packaging/hudi-utilities-slim-bundle/pom.xml
pom.xml

With 1.0 release, OSS users reported ClassNotFound issue due to ProtoBufSchemaProvider w/ schema registry client. Fixing the same in this patch by including the jar of interest to utilities bundle jar and utilities slim bundle jar.
Offending commit of interest: https://github.com/apache/hudi/pull/11660/files#r1973933358 
Essentially, we are introducing 
```
new ProtobufSchemaProvider() and  new JsonSchemaProvider()
```
in this commit which expects these classes to be present in CP during runtime. 
Before the fix: 
```
[INFO] -------------< org.apache.hudi:hudi-utilities-bundle_2.12 >-------------
[INFO] Building hudi-utilities-bundle_2.12 1.1.0-SNAPSHOT               [22/22]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from confluent: …
```

[HUDI-9057] Fixing ClassNotFound issue w/ ProtoBufSchemaProvider

---

hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestDataSourceUtils.java
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hive/TestHiveClientUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieDataSourceHelper.scala

After some investigation, we narrowed it down to TestHiveClientUtils.setUp is instantiating a spark session which is never shutdown. We could not really find a fix for it. So, for now, we are disabling the only test in this class (TestHiveClientUtils.reuseHiveClientFromSparkSession) so that we can re-enable other two tests. 
This test being disabled just validated the double checked locking paradigm which is very common. So, its ok to have it disabled. 
Filed a low priority follow up https://issues.apache.org/jira/browse/HUDI-9118 
Re-enable flaky tests and fixing spark context not shutting down.
low
- _The config description must be updated if new configs are …

[HUDI-9086] Re-enable flaky tests and fixing spark context not shutting down

---

azure-pipelines-20230430.yml

The merging of Jacoco execution data files may fail because the file is corrupt from Azure CI Job 1 FT.  The merge can succeed when the file is empty, which is also abnormal.  This PR temporarily skips merging Jacoco execution data file from Azure Job 1 FT to avoid Azure CI failure during investigation (HUDI-9143).
Makes Azure CI stable.
none
N/A

[MINOR] Skip merging Jacoco execution data file from Azure Job 1 FT

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java

- Add alternatives for the config values so users do not need to upgrade their configs when updating to Hudi 1.0.X
- Helps users migrate without issues
None

[MINOR] Fix cleaner config compatibility with older releases

---

website/docs/cli.md
website/versioned_docs/version-1.0.0/cli.md
website/versioned_docs/version-1.0.1/cli.md

Update public documentation Post Hudi CLI script deprecation in Hudi release 1.1.0.
Update Hudi CLI  public documentation for releases 1.0.0 and 1.0.1
None
None
Updating public documentation post Hudi CLI script deprecation.

[HUDI-9116] Update Hudi CLI public documentation

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDeleteTable.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestUpdateTable.scala

Empty row key string could fail the initialization of SimpleKeyGenerator during its validation.
Fixes a corner case.
Low.

[HUDI-9132] Avoid empty string row key for delete and update operations

---

hudi-aws/src/main/java/org/apache/hudi/aws/cloudwatch/CloudWatchReporter.java
hudi-aws/src/test/java/org/apache/hudi/aws/cloudwatch/TestCloudWatchReporter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java

Cloudwatch metrics broken because of new metrics name that doesn't contain table name. This PR is to change the metric name to be under a table name space. 
Changed the metric name to contain table name
none
none

[HUDI-9068] Fix cloudwatch metrics

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestHoodieFileIndex.scala

Database name can be null or empty, but in either case they should use the default value `default`. Handle this corner case in `HoodieFileIndex`
Issue this can cause:
```
Caused by: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to fetch table basic_hudi_test_cow_glue_enabled_d7f80d5c_37ef_4c0a_a2bf_f2777b080a93. dbName cannot be null or empty
at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:131)
at org.apache.spark.sql.hive.HiveExternalCatalog.tableExists(HiveExternalCatalog.scala:917)
at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.tableExists(ExternalCatalogWithListener.scala:146)
at org.apache.spark.sql.catalyst.catalog.SessionCatalog.tableExists(SessionCatalog.scala:524)
at …
```

[HUDI-9141] Handle the case that dbName is empty in HoodieFileIndex

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionMetrics.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerMetrics.java

- Removes the storage variable from the HoodieIngestionMetrics class
- The HoodieIngestionMetrics class is marked as serializable but the Storage class is not so it breaks serializability 
None

[MINOR] Remove storage instance variable from HoodieIngestionMetrics

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieReaderConfig.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java

Use StorageConfiguration instead of Configuration
Fix the deps.
Low.

[HUDI-9020] Remove hadoop deps from hudi-common

---

hudi-common/src/main/java/org/apache/hudi/common/util/collection/DiskMap.java

close: #12918
We have verified in doris that this change avoids the problem that BitCaskDiskMap will not be recycled
https://github.com/apache/doris/pull/48916
None
high
None

[HUDI-9166] Static cleanup method that doesn't hold references to DiskMap instances

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala

For the record we need to delete, we only need to read the `hoodie_meta_fields`, `record_keys` and the columns involved in the delete condition from the table, which can greatly reduce the amount of read data when deleting.
> benchmark in our production
- 1000 columns
- execute `delete from table where col-a = 'xxx'`
- 50,000,000 records per partition
> before optimized
> after optimized
In our wide table scenario, column pruning will greatly reduce the amount of data scanning and shuffle overhead in the entire process.
1. introduce schema pruning for delete record
improve delete performance especially tables with more columns
low
none

[HUDI-9166] Introduce schema pruning for delete-record

---

rfc/rfc-89/rfc-89.md

Correcting ambiguity in DDL expression
no
low

[HUDI-8990][RFC-89] Correcting ambiguity in DDL expression

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergedReadHandle.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java

- Updates the `getLatestFileSlice` method to inspect the latest merged slice to avoid an empty base file option
- Add functional test that triggers the issue
- Fixes the index lookup to allow writes to succeed  when there is an inflight compaction
Medium

[HUDI-9173] Fix issue with inflight compaction and global index lookup

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala

tableState has fields that we are not using
don't calculate unnecessary fields
low
N/A

[HUDI-9186] Remove tableState from HoodieFileGroupReaderBasedParquetFileFormat constructor 

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala

Partition stats entry for deleted partitions were not removed. This could cause incorrect query results (incorrect partition pruning). This patch simply marks such entries as deleted and adds a test to validate the index.
Fix partition stats index consistency.
low

[HUDI-8345] Delete partition stats index for a partition that is deleted

---

hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java

The flakiness has been removed. Enable it.
More coverage.
None.

[HUDI-7375] Enable testLogReaderWithDifferentVersionsOfDeleteBlocks

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieColumnStatsIndexUtils.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/common/model/ActionType.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java

The check is unnecessary because the MDT write is already committed.
No impact.
low
none

[HUDI-9175] Remove the unnecessary MDT metadata check for col_stats index config update

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java

Completion time generation was not honoring the timezone used during request time generation or whats set in table config. Fixing the same in this patch. 
Request time and completion time will use the same timezone to generate instant times.  
low

[HUDI-9127] Fixing completion time generation to honor timezone from table config

---

hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupRecordBuffer.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieDatasetBulkInsertHelper.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
hudi-spark-datasource/hudi-spark/src/test/resources/exampleEvolvedSchema.txt
hudi-spark-datasource/hudi-spark/src/test/resources/exampleSchema.txt
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSource.scala

Fixing schema projection with file group reader with Event time based merge mode and dataset having "_hoodie_is_deleted" field. 
Fixing schema projection with file group reader with Event time based merge mode and dataset having "_hoodie_is_deleted" field. Key based merging with new file group reader when data block contains records with _hoodie_is_deleted set to true will be honored. 
low …

[HUDI-9170] Fixing schema projection with file group reader

---

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java

This PR disables flaky tests on Flink to unblock CI.  HUDI-9196 for further investigation.
Unblocks CI.
none
N/A

[HUDI-9196] Disable flaky tests on Flink

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunctionWithRateLimit.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunctions.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunctionWithRateLimit.java

Support rate limit for append mode
none
low

[HUDI-9198] Support rate limit for append mode

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BootstrapExecutor.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java

The tests were failing when hiveStylePartitioning && urlEncodePartitioning is true for 0.x spark reader and table version 6.
[https://github.com/onehouseinc/hudi-internal/blob/master/hudi-spark-datasource/hud[…]/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala](https://github.com/onehouseinc/hudi-internal/blob/master/hudi-spark-datasource/hud%5B%E2%80%A6%5D/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala)
```
=> org.sparkproject.guava.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Cannot find columns: 'country:simple' in the schema[StructField(_hoodie_commit_time,StringType,true),StructField(_hoodie_commit_seqno,StringType,true),StructField(_hoodie_record_key,StringType,true),StructField(_hoodie_partition_path,StringType,true), …
```

[HUDI-9215] Set partitionColumnsWithKeyGenerator based on table version

---

hudi-sync/hudi-datahub-sync/pom.xml
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubTableProperties.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubTableProperties.java

- Updates the `getInt` and `getString` calls to return the default if not set to avoid NullPointerExceptions
- Fixes runtime issue if the config is not set for `HIVE_SYNC_SCHEMA_STRING_LENGTH_THRESHOLD`
None

[HUDI-9211] Fix bug with config in DataHubSyncTool

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestHoodieFileIndex.scala

1.x spark reader tries to return the database as "default" instead of the database found in the sparkSession causing validation failures. 
A user can take a hudi basePath, register it their own catalog with the database name of their choice and do spark SQL queries on it. 
Low
None

[HUDI-9216] Fallback to spark.catalog.currentDatabase if tableConfig.databaseName is null or empty

---

hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java

Fix that cannot find write operation type during inline log-compaction.
recognizes operation type for writes
low
none

[HUDI-9220] Cannot find write operation type if run inline log compaction

---

hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java

As above.
Fixes test flakiness.
none
none

[MINOR] Fix flaky test testCreateNewInstantTimes

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieHFileInputFormat.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestHoodieWriterUtils.java

If user passes a different value of `hoodie.database.name` in properties, the validation can be ignored if tableConfig (content in hoodie.properties) contains null/empty string in it. This is primarily for use-cases, where there's an external table created with 0.x, initializing the table using 1.x adds `hoodie.database.name` in hoodie.properties as empty string and the validation keeps failing after that.
In the current PR we are removing both - the validation for empty `hoodie.database.name` and not setting `hoodie.database.name` in tableConfig if it's null or empty.
Low
Medium 
None.

[HUDI-9216] Ignore validation of empty databaseName in HoodieTableMetaClient

---

hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/spark/sql/execution/datasources/parquet/Spark3HoodieVectorizedParquetRecordReader.java

Follow up HUDI-8803, optimize vectorized reader by cache 'batchIdxField'
None
low
none

[MINOR]Follow up HUDI-8803, optimize vectorized reader by cache 'batchIdxField'

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/BaseZookeeperBasedLockProvider.java

- Use ConfigUtils to avoid null pointers at runtime by using defaults if values are not set. Also eases in any future config renames by factoring in the alternate keys.
- Improves usability
None

[MINOR] Use ConfigUtils to handle defaults for all Zookeeper lock provider configs

---

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala

Fix bulk insert overwrite after a failed insert
```sql
set hoodie.spark.sql.insert.into.operation=bulk_insert;
create table t(
id int,
name string,
dt int
) using hudi
type = 'cow',
primaryKey = 'id'
) partitioned by (dt);
-- kill this
insert overwrite table t partition (dt) values(1, 'a1', 10);
-- rerun will raise exception
insert overwrite table t partition (dt) values(1, 'a1', 10);
```
```
Caused by: org.apache.hudi.exception.HoodieIOException: Failed to check emptiness of instant [==>20250327073905540__replacecommit__REQUESTED]
at org.apache.hudi.common.table.timeline.TimelineUtils.isEmpty(TimelineUtils.java:616)
at org.apache.hudi.common.table.timeline.versioning.v2.ActiveTimelineV2.isEmpty(ActiveTimelineV2.java:755)
at …
```

[HUDI-9227] Fix bulk insert overwrite after a failed insert

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala

- Handle the case where the initial commit is empty for a table with col stats enabled
- Fixes potential edge case in StreamSync path
Low

[HUDI-9233] Handle empty table edge case for col stats initialization

---

packaging/bundle-validation/validate.sh
packaging/hudi-spark-bundle/pom.xml
packaging/hudi-utilities-slim-bundle/pom.xml

This PR removes redundant classes in `hudi-spark-bundle` and in `hudi-utilities-slim-bundle` that have already been packaged by `hudi-spark-bundle` to avoid conflicting dependency version, including Avro, with `hudi-spark-bundle`, so that `hudi-utilities-slim-bundle` and `hudi-spark-bundle` can be used together in all Spark versions without any problem.  Note that we always build `hudi-utilities-slim-bundle` with Spark 3.5 profile as part of the maven release assuming that the dependencies included in the `hudi-utilities-slim-bundle` do not depend on the Spark profile (which was not the case for Avro before this PR).
Fixes issues with Avro classes included in `hudi-utilities-slim-bundle` that conflict with different versions of `hudi-spark-bundle`.
The number of classes in Spark bundle is …

[HUDI-9167] Remove redundant classes in hudi-utilities-slim-bundle

---

hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java

For now using basePath String as Cache Key
for the extra `\` ( DFS consider the paths to be the same), the cache is released strictly according to the string comparison and is considered to be different paths, resulting in unclean release.
For Example
Put in Cache
Check cache key during release cache stage
Spark Cache release
low …

[HUDI-9239]Fix the bug of Spark Cache not releasing cleanly

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
pom.xml

Confluent 5.5.0 implementation of `ParsedSchema::canonicalString` accessed Avro's `Schema.FACTORY` in the incorrect way. See https://github.com/confluentinc/schema-registry/issues/1432
This was fixed later [here](https://github.com/confluentinc/schema-registry/pull/1742/files#diff-c050108d2e79a497d4150248a9fca3d516baf47c225155c543e44ca86039d85c). 
But, upgrading the version confluent version leads to dependency conflict with Guava. So, this patch adds a fallback to the previous way of fetching schema if the schema type is not Protobuf.
Fix regression with fetching Avro/Json schema.
low
- _The config description must be updated if new configs are added or the …

[HUDI-9133] Fallback to legacy schema fetching in case of IllegalAccessError from schema registry client

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala

While inserting into hudi table，the DAG in the Spark web ui is not fully displayed，missing the DAG for subquery of insert into statement。Although [HUDI-5956](https://issues.apache.org/jira/browse/HUDI-5956) has enabled subquery DAG display in sub-execution, it remains insufficiently user-friendly.
- Moving `alignedQuery` to analysis phase
- Adjusting parent class  of `InsertIntoHudiTableCommand` and `CreateHoodieTableAsSelectCommand` to `DataWritingCommand`
- use `sparkPlan` of `DataWritingCommand` to generate the DataFrame
Before:
After:
https://github.com/apache/hudi/issues/9944
https://github.com/apache/hudi/pull/11376
None
None
None

[HUDI-9231]Show complete DAG for one single query in spark web ui while inserting into hudi table

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderInflightCommit.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestHarness.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileGroupReaderBasedRecordReader.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala

The PR adds capability to read inflight instants with HoodieLogRecordReader by adding `allowInflightInstants` flag. The capability is required for updating RLI since RLI reads the log records and finds deleted keys.
While replacing `HoodieMergedLogRecordScanner` with new reader class, we need to use the allowInflightInstants flag.
NA
low
NA

[HUDI-9206] Support reading inflight instants with HoodieLogRecordReader

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java

Currently BaseHoodieWriteClient checks for both upgrade and downgrade using `UpgradeDowngrade#needsUpgradeOrDowngrade`. It should instead check for upgrade only. The Jira introduces a new function needsUpgrade and uses it in BaseHoodieWriteClient instead.
NA
low
NA

[HUDI-9252] BaseHoodieWriteClient should only check for upgrade

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java

The warning was added because compatibility with table version 6 was still being worked on. We are removing the warning after the compatibility fixes in 1.0.2.
NA
low
NA

[MINOR] Remove warning around table version six

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriterTableVersionSix.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java

With table version 6, MDT uses suffix `001` for compaction instants. This causes NumberFormatException while updating metrics while parsing the instant as Long. The PR fixes the issue to use only the timestamp while updating the metrics.
NA
low
NA

[MINOR] Fix NumberFormatException while updating metrics for MDT in table version 6

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordMerger.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderSchemaHandler.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java

- We are inferring merge mode by inferring it using merge strategy id when table version is 8 and using payload when table version is 6. The Jira aims to use a similar rule when inferring merge strategy id.
If table version is 8, we use table config merge strategy id otherwise we determine strategy id using payload. This handling is required only for custom merge mode.
- Also, fixed the table version argument that we pass in to infer merge mode configs. 
NA
low
NA

[HUDI-9255] Fix inferring correct merge behavior for few scenarios 

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieSparkTable.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestDirectWriteMarkers.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestWriteMarkersBase.java

During marker reconciliation, we intend to delete additional files. But we were not checking the return status. So, due to n/w interruptions, if file deletion failed, we do not want to proceed. Fixing it in this patch. 
If we could not delete additional files during marker reconciliation, we will fail the writes. 
low …

[HUDI-9259] Fixing marker reconciliation for failures during deleting additional files

---

website/docs/precommit_validator.md
website/versioned_docs/version-0.14.0/precommit_validator.md
website/versioned_docs/version-0.14.1/precommit_validator.md
website/versioned_docs/version-0.15.0/precommit_validator.md
website/versioned_docs/version-1.0.0/precommit_validator.md
website/versioned_docs/version-1.0.1/precommit_validator.md

Context is missing about the fact that pre-commit validation is skipped when write mode is set to BULK_INSERT so I propose to add it because it is not obvious.
Also I tried to use the same syntax for information about separator and syntax usage for existing validator classes. …

[DOCS] Data quality docs update

---

pom.xml

This code change is made to update jetty version to fix CVE-2024-8184
No impact. Fixes the vulnerability
None
None

[MINOR] Upgrade jetty version to 9.4.57.v20241219 to fix CVE-2024-8184

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java

EightToSevenDowngradeHandler.downgradeFromLSMTimeline exception gets suppressed. The function already handles the exception handling so exception handling is not required in its caller
Avoids exception suppression
low
NA

[MINOR] Fix logging issue with EightToSevenDowngradeHandler

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/models/HeartbeatManager.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/models/LockProviderHeartbeatManager.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/models/TestLockProviderHeartbeatManager.java

Adds a heartbeat manager for the lock provider with conditional writes.
See RFC: https://github.com/apache/hudi/pull/12927
This heartbeat manager is responsible for maintaining a thread which constantly updates the lock file in storage.
The heartbeat manager runs on a thread in same jvm as lock manager/writer client. This allows us to abstract away maintaining the lock from the lock provider. From the perspective of lock provider, all it does is call `heartbeatManager.startHeartbeatForThread(Thread.currentThread())`.
None
None

[HUDI-9156] Add lock provider heartbeat manager

---

website/docs/concurrency_control.md
website/docs/configurations.md

Adds doc updates for new configs with ConditionalWriteLockProvider
See: https://github.com/apache/hudi/pull/13103
N/A
None
Adding docs

[HUDI-9158] Add doc updates for conditional writes-based lock provider

---

azure-pipelines-20230430.yml

There's some issue with the latest linux kernel version in the ubuntu 22.04 version, so using ubuntu 24.04 which still refers to `6.8.0-1021-azure` linux version is a temporary workaround to get `UT hudi-hadoop-common & Hudi Utilities others` passing in Azure CI.
Test fix
None
N/A

[MINOR] Force UT hudi-hadoop-common & Hudi Utilities others Azure CI to use ubuntu 24

---

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java

While downgrading archived timeline, EightToSevenDowngradeHandler hits an error where it is trying to get instant details from active timeline instead of archive timeline.
```
25/04/07 15:26:47 WARN UpgradeDowngrade: Unable to upgrade or downgrade the metadata table to version SIX, ignoring the error and continue.
org.apache.hudi.exception.HoodieException: Failed to downgrade LSM timeline to old archived format
    at org.apache.hudi.table.upgrade.EightToSevenDowngradeHandler.downgradeFromLSMTimeline(EightToSevenDowngradeHandler.java:232)
    at org.apache.hudi.table.upgrade.EightToSevenDowngradeHandler.downgrade(EightToSevenDowngradeHandler.java:131)
    at org.apache.hudi.table.upgrade.UpgradeDowngrade.downgrade(UpgradeDowngrade.java:275)
    at …
```

[HUDI-9263] Archived timeline downgrade fails with EightToSevenDowngradeHandler

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java

If reading column stats from an older version of Hudi, `isTightBound` field is not present. We should handle that appropriately, otherwise it leads to below exception:
```
Caused by: org.apache.hudi.exception.HoodieException: Unable to instantiate payload class 
at org.apache.hudi.common.util.HoodieRecordUtils.loadPayload(HoodieRecordUtils.java:114)
at org.apache.hudi.common.util.SpillableMapUtils.convertToHoodieRecordPayload(SpillableMapUtils.java:155)
at org.apache.hudi.metadata.HoodieBackedTableMetadata.composeRecord(HoodieBackedTableMetadata.java:560)
at org.apache.hudi.metadata.HoodieBackedTableMetadata.lambda$fetchBaseFileRecordsByKeys$11(HoodieBackedTableMetadata.java:435)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
at …
```

[HUDI-9269] Handle tight bound field in columns stats metadata

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieFileGroup.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/model/TestHoodieFileGroup.java

- Use same filter in `getAllFileSlicesBeforeOn` as is used in `getAllFileSlices`
- Fixes bug where slice can be returned without being committed which can cause issues in other parts of the code. This was causing errors in the small file handling flow.
Low

[HUDI-9288] Fix file group bug with uncommitted slices

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala

Support displaying complete dag for update statement in spark web ui
- resolve input plan while analyzing `UpdateTable`  and  then convert `UpdateTable` to `UpdateHoodieTableCommand`.
- make `UpdateHoodieTableCommand` extends `DataWritingCommand`
Before：
After：
None
None
None

[HUDI-9270]Support displaying complete dag for update statement in spark web ui

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/IOUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala

1. Dynamically computes compaction/merge available memory and passes it to `FileGroupReader`
Use dynamic memory to provide `FileGroupReade` for merge usage
low
none

[HUDI-9268] Dynamically computes compaction/merge available memory and passes it to `FileGroupReader`

---

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java

Column stats creation fails when a decimal field with precision exceeds the max limit.
```
org.apache.avro.AvroTypeException: Cannot encode decimal with precision 35 as max precision 30. This is after safely adjusting scale from 0 to required 15
at org.apache.hudi.metadata.HoodieTableMetadataUtil.tryUpcastDecimal(HoodieTableMetadataUtil.java:1833)
at org.apache.hudi.avro.HoodieAvroUtils.wrapValueIntoAvro(HoodieAvroUtils.java:1464)
at org.apache.hudi.metadata.HoodieMetadataPayload.createColumnStatsRecord(HoodieMetadataPayload.java:523)
at org.apache.hudi.metadata.HoodieMetadataPayload.lambda$createColumnStatsRecords$5(HoodieMetadataPayload.java:497)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
```
This patch simply skip building stats for such fields instead …

[HUDI-9262] Skip building stats for decimal field with very high precision

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieEmptyRecord.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestCustomMerger.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala

Fix the file group reader log file sequence to be in asending order, so that to keep the "processing_time" merging semantics for streaming scenarios: always choose the latest incoming if the ordering val are equals.
This semantics works now for both `COMMIT_TIME` and `EVENT_TIME` merging modes after the fix.
Also fix some other issues:
* the unnecessary copy of rows for position based merging;
* the event time merging sequence for CUSTOM merger.
* fix the null ordering value in DeleteBlock coming from `HoodieEmptyRecord`
* fix the position based merging fallback read under COMMIT_TIME merging mode
no impact
low
- _The config description must be updated if new …

[HUDI-9267] Fix the file group reader log file read sequence

---

hudi-common/src/main/java/org/apache/hudi/common/model/PartitionBucketIndexHashingConfig.java
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/PartitionBucketIndexManager.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTableWithPartitionBucketIndex.scala

Enhance PartitionBucketIndexManager Support
1. Show Config Commands
2. Rollback Bucket Rescale Command 
3. Dry-Run
4. Add Expression Command
PartitionBucketIndexManager
low

[HUDI-8990] PartitionBucketIndexManager Enhance

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/hive/HoodieCombineHiveInputFormat.java
hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/hive/TestHoodieCombineHiveInputFormat.java

`mapreduce.input.fileinputformat.split.maxsize` is used to control the split size. When using CombineInputFormat, it is used to control the size of `CombineSplit`. But in `HoodieCombineHiveInputFormat`, it is used to control how many original splits are combined into one `CombineSplit`.
https://github.com/apache/hudi/blob/7c9a1ddc1b2b39b5a3a634691a83054b1b876f0b/hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/hive/HoodieCombineHiveInputFormat.java#L978-L989
None
None
None

[HUDI-9308]Fix incorrect usage of mapreduce.input.fileinputformat.split.maxsize in HoodieCombineHiveInputFormat

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataFileWriterFactory.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java

1.  Add a new storage config to hoodie.parquet.flink.rowdata.write.support.class
2. Use reflection to load the class with default constructor
none
none
None

[HUDI-9304] support configurable RowDataParquetWriteSupport for Flink

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala

https://github.com/apache/hudi/pull/13044
https://github.com/apache/hudi/pull/13110
these two commit both use `sparkRowSerDe` to convert `RDD[InternalRow]` to `RDD[Row],` and then use `sparkSession.createDataFrame` to convert to `DataFrame`. this introduce perf regression for insert
use `sparkSession.internalCreateDataFrame` instead
None
None
None

[HUDI-9309]Fix perf regression from supporting display dag of insert/update statment in spark ui

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java

when creating table with HiveCatalog in Flink, the order of partitions fields in hoodie meta are inconsistent with HMS, which may cause unexpected data disorder.
this PR checks the order
hudi-flink-datasource
Low
None

[HUDI-9266] Check order of partition fields in hoodie meta and HMS

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java

Currently master fails while upgrading from table version (6, 7) to 8 with `hoodie.write.auto.upgrade` set to false and metadata enabled. Since backward compatibility of metadata writer has been fixed with HUDI-9026, the PR aims to remove those checks. 
Ensures that a version 6 or 7 table can be upgraded to version 8 with metadata enabled
low
While upgrading to table version 8, we do not need to disable metadata  when `hoodie.write.auto.upgrade` is set to false.

[HUDI-9203] Fix usability w/ upgrading from 0.x to 1.x and wish to stay in table version 6

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java

In https://github.com/apache/hudi/commit/7cf6dc1832a902392b31fd0f3ee03d5895b4f680 we reverted the default to false and went back to using legacy hbase hfile reader. We also fixed an issue. However, that means other engines now need to have hbase dependencies in the classpath to read the metadata table. This defeats the purpose of native hfile reader.
The reason we went back to leagacy hfile reader in the above commit was that the native hfile reader does not work for large hfiles (> 200mb) with multiple branching of leaf index. This will be fixed in HUDI-8601. But, going back to legacy is a backward step and will not work for engines like Trino. In production, very few users will have large hfiles. We are going to call out this limitation and fix HUDI-8601 immediately in the next release. …

[MINOR] Use native file reader by default

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordPayload.java
hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java

The construction of HoodieConfig is very costly, this would impact the regular read and also compaction.
none
none

[HUDI-9321] Fix unnecessary hoodie config conversion for ConfigUtils.getPayloadClass

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieTimeGeneratorConfig.java
hudi-common/src/test/java/org/apache/hudi/common/config/TestHoodieTimeGeneratorConfig.java

- Fixes issue in the ordering of applying defaults so that the in process time generator will sleep for 1ms as intended
- Lowers execution time by 199ms for a lot of our tests
None

[MINOR] Time generator defaults to sleeping for 200ms even with in-process lock provider

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala

Support displaying complete dag for delete statement in spark web ui
- resolve input plan while analyzing `DeleteTable` and then convert to `DeleteHoodieTableCommand`
- make `DeleteHoodieTableCommand` extends `DataWritingCommand`
Before:
After:
None
None
None
None

[HUDI-9324]Support displaying complete dag for delete statement in spark web ui

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-common/src/main/java/org/apache/hudi/common/model/BaseAvroPayload.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieEmptyRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordCompatibilityInterface.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCommandBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCorruptBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ArchivedTimelineV1.java
hudi-common/src/main/java/org/apache/hudi/common/util/FileFormatUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/HFileUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieDeleteBlock.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveRecord.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java

Cherry-pick "[HUDI-9322] Optimizing performance for hoodie log files writing"
Improve log writing performance, include regular write and metadata table write.
low

Cherry-pick "[HUDI-9322] Optimizing performance for hoodie log files writing"

---

hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hive/TestHiveClientUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieDataSourceHelper.scala

Cherrypicks #12909 into `branch-0.x`
After some investigation, we narrowed it down to TestHiveClientUtils.setUp is instantiating a spark session which is never shutdown. We could not really find a fix for it. So, for now, we are disabling the only test in this class (TestHiveClientUtils.reuseHiveClientFromSparkSession) so that we can re-enable other two tests. 
This test being disabled just validated the double checked locking paradigm which is very common. So, its ok to have it disabled. 
Filed a low priority follow up https://issues.apache.org/jira/browse/HUDI-9118 
Unblock GH CI
none
N/A

[HUDI-9086] Fix spark context not shutting down in CI

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieParquetFileFormatHelper.scala
hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/InternalSchemaManager.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark3ParquetSchemaEvolutionUtils.scala
hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33LegacyHoodieParquetFileFormat.scala
hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34LegacyHoodieParquetFileFormat.scala
hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark35LegacyHoodieParquetFileFormat.scala

Fix the incorrect data read after changing the column type from float to double
There are two reasons for the above problems：
1. `InternalSchemaCache` cannot obtain the path of the commit file correctly. Because after version 1.x, we placed the commit file separately in the `timeline` directory. However, `InternalSchemaCache` still retrievals files from `basePath/.hoodie`, thus failing to obtain the correct schema.
2. When we read parquet file without `enableVectorizedReader`, we use spark 's `CAST` for type conversion when we need to do scheme evolution, but spark has a loss of precision when dealing with `CAST` that converts `float` to `double`.
Change logs:
1. pass the correct timeline path for `InternalSchemaCache`
2. for schema evolution without `enableVectorizedReader`, for the case …

[HUDI-8902] Fix the incorrect data read after changing the column type from float to double

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala

This PR fixes the unnecessary scanning of the target table in MERGE INTO statement in Spark by only using the source table as the input if the target table has a record key (before this change the source and target table is left joined, causing all partitions in the target table to be scanned unnecessarily, if the source table only contains data targeting a handful of partitions).  For primary-keyless table the logic is not changed, i.e., the source and target table is left joined to get the meta column values for prepped upsert in MERGE INTO.
Spark SQL for testing:
```
create database MIT_partition_pruning5;
use MIT_partition_pruning5;
CREATE TABLE merge_source (
ts BIGINT,
uuid STRING,
fare DOUBLE,
city STRING
) USING PARQUET;
INSERT INTO merge_source
VALUES …
```

[HUDI-9088] Fix unnecessary scanning of target table in MERGE INTO on Spark

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java

Updated the logic for estimating averageCDCRecordSize during CDC block accumulation.
Instead of estimating the size only once based on the first record, the estimation is now refreshed every 100 records using an exponential moving average
Reduces the risk of OOM caused by underestimating memory usage due to anomalously small initial CDC records.
Enables more accurate triggering of CDC block flushes, improving memory stability during write operations.
The change maintains minimal overhead by updating the estimation infrequently (every 100 records) and smoothing transitions using a weighted average.
none
none

[HUDI-9331] Fix Incorrect memory estimation for CDC block flushing can lead to OOM

---

packaging/bundle-validation/README.md

The `validate-release-candidate-bundles` was moved to a new file in this PR: https://github.com/apache/hudi/pull/10729, however the readme wasn't updated, this PR cleans it up.
None
None
None

[MINOR] Update bundle validation README.md

---

packaging/bundle-validation/cli/commands.txt
packaging/bundle-validation/validate.sh
rfc/rfc-65/rfc-65.md
rfc/rfc-66/rfc-66.md
rfc/rfc-93/rfc-93.md

Cleaning up RAT check errors when running:
```shell
mvn apache-rat:check
```
The error below is thrown:
```shell
[INFO] --- apache-rat:0.16.1:check (default-cli) @ hudi ---
[WARNING]  Parameter 'licenseFamilies' is deprecated: No reason given
[WARNING]  Parameter 'licenses' is deprecated: No reason given
[WARNING] Configuration uses deprecated configuration.  Please upgrade to v0.17 configuration options
[INFO] Rat check: Summary over all files. Unapproved: 4, unknown: 4, generated: 0, approved: 4343 licenses.
[WARNING] Files with unapproved licenses:
packaging/bundle-validation/cli/commands.txt
rfc/rfc-65/rfc-65.md
rfc/rfc-66/rfc-66.md
rfc/rfc-93/rfc-93.md
```
Rat check is performed manually with the command below when verifying a staged release:
```shell
cd scripts && …
```

[MINOR] Clean up RAT check errors

---

hudi-common/src/main/java/org/apache/hudi/common/util/hash/BucketIndexUtil.java
hudi-common/src/test/java/org/apache/hudi/common/util/hash/TestBucketIndexUtil.java

We execute a sql with:
1. `bulk insert` operation
2. `92160 ` buckets per partition
3. `set hoodie.bulkinsert.shuffle.parallelism=92160`
And then there a error occurs:
The reason for this error is that when our partitioner calculates the partition id, it returns a number that is not within the parallelism range.
As for why an illegal id was returned, is it because there is an overflow of int type during the process of calculating the id.
1. avoid obtaining an incorrect partition id due to int type overflow in `BucketIndexUtil`
fix the error when we set a large buckets num and large `hoodie.bulkinsert.shuffle.parallelism`
low
none
- _The config description must be updated if new configs are added or the …

[HUDI-9329] Avoid obtaining an incorrect partition id due to int type overflow in `BucketIndexUtil`

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala

In `TestRecordLevelIndexWithSQL#testRLIWithThreeRecordKeyFields`, the config values for **primaryKey** and **hoodie.datasource.write.recordkey.field** are different.
Although there are no test failures as the value in **hoodie.datasource.write.recordkey.field** will be used (superseding **primaryKey**), it is still good to clean this up.
On top of that, the repeated config values are moved to a variable to reduce repeated declaration.
None
None
None

[MINOR] Clean up config inconsistency in recordKeyFields config

---

hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala

This PR fixes the flaky test `testDeletePartitionsV2` as shown below.  The root cause is that the test expects 3 partitions to be written by `deletePartitionSetup` but the random record generator can generate records in fewer partitions due to how the partition path value is set.
https://github.com/apache/hudi/actions/runs/14589199410/job/40920578922
```
Error:  Tests run: 57, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 172.08 s <<< FAILURE! - in org.apache.hudi.TestHoodieSparkSqlWriter
Error:  testDeletePartitionsV2{boolean}[2]  Time elapsed: 3.315 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <6> but was: <4>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at …
```

[MINOR] Fix flaky test testDeletePartitionsV2

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieReplaceCommitMetadata.java

For POJO java class HoodieCommitMetadata and its subclass, we should consider deprecating them completely and only rely on their avro counterpart completely.
none
none
none

[HUDI-9078] Deprecate POJO commit metadata class and its subclasses

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java

`ENABLE_METADATA_INDEX_PARTITION_STATS` is enabled by default, a change that was introduce in the PR below that sets its default value to the value of `ENABLE_METADATA_INDEX_COLUMN_STATS` here:
https://github.com/apache/hudi/pull/12707/files#diff-11e9ef6bd53ef1001b669a1dc68dde2aba9b33c9eb72cc1e4198750336d79772R893
However, the config value is false. This PR changes the config value to remove this discrepancy. Automated config docs will also be updated as a result to reduce confusion.
In this PR, we are updating the doc description to better reflect the default value of this config.
None
None
Default value of `ENABLE_METADATA_INDEX_PARTITION_STATS` / `hoodie.metadata.index.partition.enable` will be changed in the config docs.

[HUDI-8680] Update doc description for metadata index partition enable

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java

Currently, there is no exception when we try to write data in Flink append mode using bucket index. Data will be written, but in parquet files without bucket IDs. And it would happen silently. This MR propose to throw exception in this case, instead of silent write of unexpected data, which is not compatible with index settings..
Simple bucket index is not supported in Flink append mode. Therefore we need to prevent silent unexpected behavior.
Low. Corresponding test is added.
There is no detailed description in the documentation about how different index types are working in different modes of different engines.

[HUDI-8796] Restrict insert operation with bucket index for Flink

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/AbstractHoodieRowData.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkRecord.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieRowDataWithPartialMetaFields.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieRowDataWithUpdatedMetaField.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/RowDataAvroQueryContexts.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieInternalRowUtils.scala
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieEmptyRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecord.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveRecord.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala

Cherry-picked from #13213
Refactor the log records presentation in FileGroupRecordBuffer
cache ordering value for HoodieRecord to avoid dup calculating.
introduce a pojo BufferedRecord to substitute Pair<Option<T>, Map<String, Object>> for record buffer in file group reader.
convert the buffered record into binary-format before put into spillable map to save space, and reduce spilling.
Reduce heap size of record to make ExternalSpillableMap less prone to spill.
medium
- _Any new feature or user-facing change requires updating the Hudi website. Please …

[HUDI-9318] Refactor the log records presentation in FileGroupRecordBuffer

---

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java

When cleaner and meta-sync are running concurrently, the activeTimeline for meta-sync can contain clean instants that are archived.
Avoids failures which will succeed on retry but can create a lot of noise.
Low
None.

[HUDI-9347] Handle archived clean instants in meta-sync for droppedPartitions

---

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java

Use hoodie.table.precombine.field parameter as fallback when building HoodieWriteConfig

[HUDI-9345] Use hoodie.table.precombine.field parameter as fallback  when building HoodieWriteConfig

---

hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/RocksDbBasedFileSystemView.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java

completionTimeQueryView is a new resource that's initialized in 1.x fsView, but it's not closed properly in the close method. 
Properly close resources in views which are created often. 
Medium. 
None.

[HUDI-9352] Close CompletionTimeQueryView in fsView

---

hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java

- There is an edge case where the spillable map's in-memory size limit is reached and the number of records in that map are a multiple of 100. This would cause the estimator to be called on every insert and impact performance as a result.
- Fixes edge case that causes performance regression
None

[MINOR] Avoid edge case where spillable map estimator is repeatedly called

---

hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
hudi-hadoop-common/src/test/java/org/apache/hudi/storage/hadoop/TestHoodieHadoopStorage.java

This PR removes `FileSystem#close` in `HoodieHadoopStorage#close`.  If the underlying `FileSystem` object is closed, the cache of the object based on the path is closed and removed, which causes problems if the object is reused elsewhere.
Fixes `FileSystem` object usage.
none
N/A

[HUDI-9355] Avoid calling FileSystem#close in HoodieHadoopStorage

---

hudi-aws/pom.xml
hudi-gcp/pom.xml
hudi-gcp/src/main/java/org/apache/hudi/gcp/transaction/lock/GCSStorageLockClient.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/transaction/lock/TestGCSStorageBasedLockProvider.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/transaction/lock/TestGCSStorageLockClient.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
hudi-io/src/main/java/org/apache/hudi/storage/StorageSchemes.java
hudi-tests-common/pom.xml

Adds the storage based lock provider implementation for GCS hudi tables.
Allows conditional writes based locking for multi writer scenarios with hudi tables in gcs.
None
None
In order to test this we setup local hudi/spark bundles and ran some concurrent spark sql queries to tables with this LP enabled to ensure things functioned as expected.

[HUDI-9160]: GCS implementation of StorageLockClient for StorageBasedLockProvider

---

hudi-common/src/main/java/org/apache/hudi/common/serialization/HoodieFileGroupSerializer.java
hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieFileGroupSizeEstimator.java
hudi-common/src/main/java/org/apache/hudi/common/util/SerializationUtils.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieFileGroupSizeEstimator.java

- Reduce size of serialized File Group in FSView 
- Register the required classes for Kryo to reduce the size 
- Only compute valid instants once for MDT reader instead of per scanner
- Reduces overhead of loading the FSView from the metadata table
Low

[HUDI-9364] Improve FileSystemView loading performance with large partitions

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieFileSliceReader.java
hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexRecordGenerationUtils.java

This PR extracts common logic of getting the file slice reader for secondary index to reduce code duplication.  It also makes changes to close resources in the file slice reader and the iterator for the secondary index properly.
Improves code maintainability and resource management
none
none

[HUDI-9336] Extract common logic of getting reader for secondary index

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java
hudi-common/src/test/java/org/apache/hudi/common/config/TestHoodieStorageConfig.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala

This PR simplifies bloom filter config passing in metadata table writer by avoiding passing `metadataWriteConfig` to `SparkMetadataWriterUtils#getExprIndexRecords` and instead using the storage config which is necessary.  This change makes subsequent refactoring of the metadata table writer easier.
Simplification of config passing
none
none

[HUDI-9369] Simplify bloom filter config passing in metadata table writer

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubQueueClient.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/gcs/TestPubsubQueueClient.java

- Handle an empty response when trying to fetch the number of remaining messages
- Handles an edge case that would otherwise throw a runtime error
None

[MINOR] Fix bug in PubsubQueueClient for handling empty response

---

hudi-common/src/main/java/org/apache/hudi/common/table/view/NoOpTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java

Introduces an API to look up stats for multiple columns in a single API to avoid multiple network calls to fetch HFile blocks.
Callers can compute col stats for multiple columns quickly.
Low. 
None.

[HUDI-9346] Add getColumnStats method which supports list of columns

---

hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestHoodieDataHubDatasetIdentifier.java

This update introduces the ability to set `DataPlatformInstance` via configuration.
**Before this PR:**
* `DataPlatformInstance` was not emitted for either `Dataset` or `Container` entities.
* It was automatically injected by the DataHub backend, only for `Dataset`, and included only the `platform` field.
**With this PR:**
* If no platform instance is configured:
* `DataPlatformInstance` is consistently emitted for both `Dataset` and `Container` entities, including only the `platform` field.
* If a platform instance is configured:
* `DataPlatformInstance` is consistently emitted for both `Dataset` and `Container` entities, including both the `platform` and `instance` fields.
* The platform instance is included in the browse paths.
* The platform instance is also included in the identity …

[HUDI-9377] feat(datahub-sync): adds DataPlatformInstance aspect

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java

This PR unifies logic of fetching files and file slices in the metadata table writer so the index initialization is only based on two types of information of the file system view:
- (1) `partitionIdToAllFilesMap`: all the files in a table used by `FILES`, `BLOOM_FILTERS`, and `COLUMN_STATS` partitions;
- (2) `lazyLatestMergedPartitionFileSliceList` (lazily evaluated only if needed): latest merged file slices used by `RECORD_INDEX`, `EXPRESSION_INDEX`, `PARTITION_STATS`, and `SECONDARY_INDEX` partitions.  Also the merged partition file slices are reused now instead of recomputed for each metadata partition.
Note that these two may be further unified, which is out of the scope of this PR.  These two types of information are good enough for two types of indexes, one type based on all files …

[HUDI-9370] Unify logic of fetching files and file slices in the metadata table writer

---

website/docs/cli.md
website/versioned_docs/version-1.0.2/cli.md

Update the Apache Hudi public documentation to reflect the CLI deprecation changes.  Although these changes were initially targeted for release 1.1.0, they have been included in the recent 1.0.2 release.
None
None
- Update the Apache Hudi public documentation to reflect the CLI deprecation changes that were merged in version 1.0.2. 

Correction in Hudi CLI public documentation

---

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieReplaceCommitMetadata.java

Revert HUDI-9078 Deprecate POJO commit metadata class and its subclasses
This reverts commit c009ebf3651aa54d97d11a253bd0c229555ef76c.
none
none
none

Revert [HUDI-9078] Deprecate POJO commit metadata class and its subclasses

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/StorageBasedLockProvider.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/TestStorageBasedLockProvider.java

Small miss where the LP validity was defaulting to 300ms instead of 300 seconds due to ms -> seconds conversion.
Fixes existing bug
Low
N/A

[HUDI-9159] Fix LP validity bug

---

website/docs/disaster_recovery.md

Added the documentation steps to perform Savepoint and Restore operations using both Hudi CLI and SQL Procedures. 
Added different ways to perform the Savepoint and Restore operations.
low
Updated Disaster recovery documentation.

[HUDI-9374] - Update the Disaster Recovery documentation

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestBucketizedBloomCheckPartitioner.java

This PR improves bloom filter bucketizing in Spark.  Currently the parallelism of the bloom filter bucketizing is limited by the input parallelism if the bloom index parallelism is not configured, which becomes the bottleneck if the number of file groups and buckets (based on the number of key per bucket) is much larger.
To improve the performance of bucketizing bloom filter checking, the new feature of dynamic parallelism and config `hoodie.bloom.index.bucketized.checking.with.dynamic.parallelism` is added.  When enabled and bloom index parallelism is not configured, the index parallelism is dynamically determined by the number of file groups to look up and the number of keys per bucket to split comparisons within a file group.  In this case, the duration of each task is bounded by the …

[HUDI-9399] Improve bloom filter bucketizing in Spark

---

packaging/hudi-hive-sync-bundle/pom.xml

Got the following exception while running the Hudi Hive Sync Bundle inside Docker image.
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/Caffeine
at org.apache.hudi.avro.AvroSchemaCache.<clinit>(AvroSchemaCache.java:36)
at org.apache.hudi.common.table.log.block.HoodieDataBlock.<init>(HoodieDataBlock.java:115)
at org.apache.hudi.common.table.log.block.HoodieHFileDataBlock.<init>(HoodieHFileDataBlock.java:79)
at org.apache.hudi.common.table.log.HoodieLogFileReader.readBlock(HoodieLogFileReader.java:202)
at org.apache.hudi.common.table.log.HoodieLogFileReader.next(HoodieLogFileReader.java:386)
at org.apache.hudi.common.table.log.HoodieLogFormatReader.next(HoodieLogFormatReader.java:102)
at …
```

[HUDI-9400] - Included Caffeine jar to the Hudi Hive Sync Bundle

---

hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark3ParquetSchemaEvolutionUtils.scala

The precision is incorrect for evolution from float to double and has been fixed for most of spark by https://github.com/apache/hudi/pull/13188. However, there are some edge cases that still need to be fixed.
This pr fixes avro log blocks the evolution is fixed by adding the float -> double conversion into the method that determines if we need to manually convert the record (and the manual conversion already has the float->double conversion correct)
Fix float -> double precision issue for avro log blocks
low
N/A

[HUDI-8902] Fix schema evolution from float to double for avro log blocks

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/DefaultSparkRecordMerger.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkRecordMerger.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/OverwriteWithLatestSparkRecordMerger.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala

support partial update in commit time ordering merge mode for spark and put some duplicated code into a common method.
Discovered https://issues.apache.org/jira/browse/HUDI-9375 when writing the test. To work around this, I did one merge with a lower ordering value and then subsequently I did the same merge with a higher ordering value. This demonstrates that it will use both merger types with different results, but test correct behavior over the entire test
Support partial update for commit time ordering
low
N/A

[HUDI-8835] Support partial update in COMMIT_TIME_ORDERING merge mode

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/ConcurrentOperation.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SimpleConcurrentFileWritesConflictResolutionStrategy.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestConflictResolutionStrategyUtil.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestPreferWriterConflictResolutionStrategy.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java

- Fixes conflict detection when there is an in-flight clustering. Previously an in-flight clustering would inspect the in-flight commit which is empty. This would mean that the code would always return that there was no conflict and potentially result in a false negative. Now the code will check the requested commit when it is a clustering.
- Fixes conflict detection with replace commits for non-clustering actions. Previously these were filtered out. Now they are included.
- Updates tests to be consistent with action type to ensure we're testing real world scenarios
- Fixes conflict detection to avoid data consistency issues
None
- _The config description must be …

[HUDI-9371] Fix conflict resolution handling of inflight clustering

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/HoodieCommandMetrics.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/TestHoodieCommandMetrics.scala

Support displaying metrics of Update/Delete/MergeIntoHoodieTableCommand in Spark Web UI
Similar to #13068 
None
None
None

[HUDI-9412] Support displaying metrics of Update/Delete/MergeIntoHoodieTableCommand in Spark Web UI

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieWriteClient.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ActiveTimelineV1.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java

- Updates the HoodieBaseWriteClient to create the instant time and persist it to the timeline in the same transaction if no commit time is provided. If a commit time is provided, just the timeline update happens within a transaction.
- This is another step towards ensuring that multiple writers can safely run concurrently for the same table
Low …

[HUDI-9387] Writer creates commit time and persists to timeline in one transaction

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestUtilHelpers.java

When a HoodieException occurs in a constructor in CreateSource we fail to log it and instead throw an error at the end when the final constructor does not support the parameters we tried.
Fixes error handling in CreateSource
Low
none

[HUDI-9148] Refactor error handling for UtilHelpers#CreateSource

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/v2/FlinkFileGroupReaderBasedMergeHandle.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java

- Adds support for generating an iterator of HoodieRecord instead of simply the engine record in the FileGroupReader code. This will aide in migrating existing uses of LogScanner and other reader implementations that expect a HoodieRecord as the output.
- Aides in the migration to FileGroupReader in other code paths
Low …

[HUDI-9316] Add support for creating iterator of HoodieRecord from FGReader

---

hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java

Fixes the database path in the Dataset's browse path aspect
Low
None
None

[MINOR] fix(datahub-sync): fixes database path for dataset's browse path

---

website/src/pages/roadmap.md

This PR updates the Hudi roadmap based on the latest in the community.
Roadmap update
none
As above

[DOCS] Update Hudi roadmap (May 2025)

---

hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java

From Hudi 0.14.0 to 0.14.1, Hudi changed its logic to load all commits that can change schema to respect schema evolution: https://github.com/apache/hudi/pull/9743/files#diff-79515156c9d8e0421cea5a397ea00bbff098dd9c9c04afa57ba1ba3abf0f2f7bR392. 
This logic can benefit from the caching method `getCachedCommitMetadata` to boost performance
Use cache to load
none
none
none

[HUDI-9435] Use cache to get table schema from commit metadata

---

website/docs/cleaning.md
website/docs/clustering.md
website/docs/compaction.md
website/docs/metadata_indexing.md
website/versioned_docs/version-1.0.2/cleaning.md
website/versioned_docs/version-1.0.2/clustering.md
website/versioned_docs/version-1.0.2/compaction.md
website/versioned_docs/version-1.0.2/metadata_indexing.md

Updated the Hudi table service documentation(v1.0.2)
None
None
Updated the Hudi table service documentation(v1.0.2) commands from version 1.0.1 to 1.0.2. Additionally corrected an inconsistency in the commit retention example - the description mentioned retaining 10 commits, but the command was set to retain only 3. Updated the command to align with the example.

[MINOR][DOCS] Updating Hudi table services documentation

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/clean/TestCleanPlanActionExecutor.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ActiveTimelineV1.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java
hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java

It is not necessary for hudi to store a clean plan in the inflight clean instant as well. This will increase the storage waste of our metadata directory.
Clean plan can always be fetched from request clean instant.
1. avoid storing the clean plan in inflight clean instant
reduce storage waste about timeline
low
none

[HUDI-9330] Avoid storing the clean plan in inflight clean instant

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/CloseableConcatenatingIterator.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-examples/hudi-examples-flink/src/test/java/org/apache/hudi/examples/quickstart/TestQuickstartData.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RecordKeyToRowDataConverter.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestConsistentBucketStreamWrite.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieFileGroupReaderOnFlink.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestRecordKeyToRowDataConverter.java

Integrating FileGroup reader into Flink CDC reader
Improve performance of flink CDC reader.
low

[HUDI-9146][part3] Integrating FileGroup reader into Flink CDC reader

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java

- Updates the instant time and plan generation to happen in the same lock for restore and rollback actions
- Ensures timeline consistency and avoids possible race conditions in the gap between generating the instant time and writing out the plan
Low

[HUDI-941] Update restore/rollback/indexing planning and instant generation

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaTable.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java

- Optimizing metadata getter for metadata table
- Optimizing metadata getter for metadata table. Short circuiting `getMetadataWriter` for metadata table. 
none. 

[MINOR] Optimizing metadata getter for metadata table

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v2/TimelineArchiverV2.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/DirectMarkerTransactionManager.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/TransactionManager.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/AbstractIndexingCatchupTask.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieWriteClient.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestTransactionManager.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java

- begin/end Transaction is confusing.
- Naming aligns with how these methods are called, whenever action state changes
None. just renaming internal class
low
none

[MINOR] Renaming TransactionManager methods to begin/end x StateChange

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/StorageBasedLockProvider.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/TestStorageBasedLockProvider.java

Some code paths seem to directly call close() on the `LockManager` rather than just "unlock". This makes sense, especially if there is a shutdown occurring. However, when we close the `StorageBasedLockProvider` we explicitly remove the shutdown hook. If there is already a shutdown occurring this fails with an `IllegalStateException` and the lock does not get released properly. Therefore we will catch this exception and proceed with normal `close()` logic.
Fixes a race condition when shutting down the JVM in `StorageBasedLockProvider`
Low
N/A

[HUDI-9494] Fix small shutdown hook race condition in StorageBasedLockProvider

---

hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java

Previously we checked if the file is from MDT explicitly in FG reader.
FG reader should not know this detail at all.
Therefore, move this logic to the reader context and simply the logic accordingly.
Clean.
Low.

[HUDI-9235] Refactor InstantRange handling for MDT table base file

---

hudi-aws/pom.xml
hudi-client/hudi-client-common/pom.xml
hudi-tests-common/pom.xml
pom.xml

Remove redundant io.netty dependencies from hudi-aws-bundle package.
Compared the classes from prevous and new bundles, and no io.netty classes differeces.
[hudi-aws-bundle-1.1.0-SNAPSHOT.classes.txt](https://github.com/user-attachments/files/20657392/hudi-aws-bundle-1.1.0-SNAPSHOT.classes.txt)
[hudi-aws-bundle-1.1.0-SNAPSHOT.classes.txt](https://github.com/user-attachments/files/20657396/hudi-aws-bundle-1.1.0-SNAPSHOT.classes.txt)
Also compared all other bundles, e.g., hudi-presto-bundle, hudi-trino-bundle, hudi-spark-bundle, hudi-utilities-bundle and hudi-utilities-slim-bundle, and there were no differences.
Less redundant dependency.
Low.
- _The config …

[HUDI-9481] Remove extra io.netty dependencies from hudi-aws bundle

---

hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java

Avoids `Only one SparkContext should be running in this JVM` error.
A hotfix for spark quickstart example class `HoodieSparkQuickstart`.
Error logs:
Toubleshooting:
`HoodieExampleSparkUtils.defaultSparkSession(...)` creates a `SparkContext`. However, the example also calls `new JavaSparkContext(sparkConf)`, resulting in a duplicate `SparkContext` in the same JVM, which is not allowed and causes a SparkException.
none
none
none

[MINOR] Fix SparkContext conflict error in HoodieSparkQuickstart

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/MetadataIndexGenerator.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metadata/TestMetadataIndexGenerator.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriterTableVersionSix.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkMetadataWriterFactory.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/BaseTestHandle.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/KeyGeneratorForDataGeneratorRecords.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestAppendHandle.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestCreateHandle.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestMergeHandle.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestMetadataWriterCommit.java

The PR adds support for streaming writes in HoodieBackedMetadataTableWriter and introduces new APIs for the same. 
3 APIs are added as detailed below.
a. to start a new commit in MDT 
```
/**
* Starts a new commit in metadata table for optimized write flow.
* @param instantTime
*/
void startCommit(String instantTime); 
```
b. to do streaming write to MDT 
```
/**
* Prepare records and write to Metadata table for all eligible partitions except FILES partition. This will be used in optimized writes,
* where in data table writes statuses are maintained as HoodieData and based on that, we prepare records and write to Metadata table
* partitions (except FILES). Caution should be followed to ensure the action is not triggered on the incoming HoodieData < WriteStatus >
*   and for the writes to …
```

[HUDI-9405] Adding new writer apis and impl to Metadata writer to support streaming writes

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java

Scanner resources not properly closed in HoodieCompact
The scanner.close() is called in the happy path but may not be called if exceptions occur
It may lead-out to memory leak
Introduced try finally blocks and scanner.close() is called now inside finally block so that we can ensure scanner.close() will get called for sure
NA

[HUDI-9514] Scanner resources not properly closed in HoodieCompact

---

hudi-hadoop-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/TestDFSPropertiesConfiguration.java

`hudi-defaults.conf` does not work with `include=`
Before this was producing NPE.
Low
none

[HUDI-9524] Fix include in DFSPropertiesConfiguration

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/append/TestAppendWriteFunction.java

Trigger failure when write failure is detected for flink hudi sink
The early detection of write failure will prevent checkpoint to complete before hudi commit. Thus, prevent the data loss when checkpoint is completed, but hudi can't committed due the write failure.
none
It is an improvement of existing functionality, no user facing feature is introduced.

[HUDI-8881] Fails fast in Flink append write function

---

hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordScanner.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestCustomMerger.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestEventTimeMerging.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestHarness.java

- Ensure that the ordering field options are properly set for payload and merger classes when constructing the FileGroupRecordBuffer
- Simplify the HoodieFileGroupReader to set the ordering field based off of the table config instead of allowing the user to override this value and cause inconsistent behavior
- Update tests to execute this path where the fields are read from the table config
- Moving the code to a common location helps prevent future bugs
None
- _Any new feature or user-facing change requires updating the Hudi website. Please create a …

[HUDI-8286] Add special handling for ordering fields when building FileGroupReader

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkBucketIndexBucketInfoGetter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/InsertOverwriteBucketInfoGetter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/ListBasedSparkBucketInfoGetter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/MapBasedSparkBucketInfoGetter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexBucketInfoGetter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketInfoGetter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkHoodiePartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwriteCommitActionExecutor.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwritePartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkMetadataTableUpsertPartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkPartitionBucketIndexBucketInfoGetter.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkPartitionBucketIndexPartitioner.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestSparkMetadataTableUpsertPartitioner.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieIndex.java

For large tables, the broadcast of some of the partitioners can be a performance issue. Most of the data is not used, so SparkBucketInfoGetter abstraction is added to be a lightweight holder of only the data needed for getBucketInfo().
Performance improvement
low
N/A

[HUDI-9535] Prevent Unnecessary data transfer b/w driver and executor in Spark Partitioner

---

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveRecord.java

Fixes getColumnValueAsJava for HoodieHiveRecord. The other record implementations were fixed as part of HUDI-9340. Only HoodieHiveRecord implementation needs to be fixed here.
NA
low
NA

[MINOR] Fix getColumnValueAsJava for HoodieHiveRecord

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala

- Current TestExpressionIndex uses a mix of scalatest and junit testing code which could be causing the spark session to not close properly so I am updating all tests in this class to use scalatest.
- Fix CI issues
None

[MINOR] Use scala-test throughout TestExpressionIndex.scala

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionDirectoryConverter.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestPartitionDirectoryConverter.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala

Our current logic is that we will disguise all the files under each partition as a `PartitionDirectory` together. In order to enable the task to know the files that really need to be read, we have also put the collection of all `FileSlice` under this partition into the `PartitionValue`. 
It is convenient to find the corresponding file slice to be read from the file slice mapping set in the `PartitionValue` when each subsequent task is executed and read. 
However, I found that when the number of files in one partition increases, for example, when there are tens of thousands of files in one partition, the file slices in the `PartitionValue` will be 100MB+ in size. And when spark creates reading tasks, it needs to pass this mapping of `FileSlice` to each task. Therefore, under our default …

[HUDI-9451] Avoid broadcasting unnecessary `FileSlice` when reading

---

hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java

- Updates code to avoid creating empty files when there is content to write
- Avoid risk of creating an empty file due to a crash
None

[HUDI-9512] Avoid creating empty files when there is content to write

---

hudi-common/src/test/java/org/apache/hudi/common/table/read/TestKeyBasedFileGroupRecordBuffer.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java

Fixed two issues:
1. Azure CI test failed due to table configuration # changed from 39 to 41.
2. GH CI test failed due to signature change of KeyBasedFileGroupRecordBuffer. 
Make CI test passed.
None.

[MINOR] Fix test failures

---

hudi-examples/hudi-examples-flink/pom.xml
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/EventBuffers.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java

Using coordinator state to persist and recommit write metadata.
Solving the data loss problem for async instant generation for flink writer.
low

[HUDI-9570] Using coordinator state to persist and recommit write metadata

---

hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java

remove usage of log scanner from cli because we are deprecating it
remove reliance on deprecated code
low
N/A

[HUDI-9174] remove use of log scanner from cli

---

hudi-common/src/main/java/org/apache/hudi/internal/schema/action/TableChanges.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolutionBySQL.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala

TableChanges throws a more context specific exception type.
Helps consumer code better understand and categorize the exception.
None
None

[MINOR] TableChanges class throw schema evolution exception

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedAppendHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/SortedKeyBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/UpdateProcessor.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestKeyBasedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestSortedKeyBasedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
hudi-common/src/test/java/org/apache/hudi/common/testutils/RawTripTestPayload.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java

- Fixes discrepancy on "inserts" for compaction between old and new code. Inserts are only meant to count new records (records in log files only) whereas the FileGroupReader based compaction is counting any record without an update as an insert.
- Once this is updated, the total records written must also be updated since it was the sum of inserts and updates previously
- Update test case to prevent regressions
- Fixes stats generated by compaction
- Low
- _Any new feature or user-facing change requires updating the Hudi website. Please create a Jira …

[HUDI-8635] Fix stats for total records written and num inserts in FileGroupReader based compaction

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieIncrementalFileIndex.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionDirectoryConverter.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestPartitionDirectoryConverter.scala

There was duplicate code and then some of it was changed in:
https://issues.apache.org/jira/browse/HUDI-9250
https://issues.apache.org/jira/browse/HUDI-9451
causing a divergence. This pr breaks out the common logic so that changes will be used by both branches now.
benefits of  HUDI-9250 and HUDI-9451 apply to incremental queries and prevent further divergence
low
N/A

[HUDI-9621] Fix divergence between file index and incremental file index

---

hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListDataPairData.java

the test is flaky because it use a non thread safe ArrayList and use it in the lambda function of HoodieListData.map, which underlying implementation is parallelStream based, exposing the list to a multi-threading context.
You might have already noticed that anything captured in lambda functions has to be "effective final", which serves the purpose of safely publish the variable across all threads that consume the lambda function. Yet if we want to write to the list and later read its content back after the operation, we need a thread safe variable. Otherwise, we only protect the safety of the reference to the list variable, but not the reference to the elements that the list holds, this is a classic escape pattern.
Hit such issues in [Azure …

[MINOR] fix flaky test

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/PartialUpdateStrategy.java
hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestPartialUpdateStrategy.java
hudi-common/src/test/java/org/apache/hudi/common/util/TestConfigUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPayloadDeprecationFlow.scala

Replace original one property with multiple properties with the same prefix.
More conventional.
Low.

[HUDI-9640] Replace merge_properties with a list properties with a given prefix

---

hudi-common/src/main/java/org/apache/hudi/common/util/HoodieDataUtils.java
hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListDataPairData.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieDataUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java

Bug fix for getSecondaryIndexRecords API. For V1 it is the correct behavior that we return seckey -> reckey mapping yet in v2 we accidentally reversed it to be recKey -> secKey.
To handle null value, 2 main changes are applied
- we revise the SI lookup interface methods to return HoodiePairData<String, String>, instead of HotoodiePairData<String, Set<String>>
- for dag where we need to group by key, reduce by key which could not handle null, we revise them to first wrap things with Option, run the downstream dag and unwrap in the end.
bug free for index lookup API, along with a few util class enhancement supporting that
none
none

[HUDI-9505] Bug fix for getSecondaryIndexRecords API

---

hudi-client/hudi-client-common/pom.xml
hudi-client/hudi-spark-client/pom.xml
hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
hudi-common/pom.xml
hudi-hadoop-common/pom.xml
hudi-io/pom.xml
hudi-spark-datasource/hudi-spark/pom.xml
hudi-sync/hudi-hive-sync/pom.xml
hudi-utilities/pom.xml
packaging/hudi-integ-test-bundle/pom.xml
packaging/hudi-utilities-bundle/pom.xml
packaging/hudi-utilities-slim-bundle/pom.xml
pom.xml

- Moves the protobuf relocation to only exist in the hudi-io module
- Modules that depend on hudi-io now depend on the shaded jar with the relocated protobuf libraries
- Fixes runtime issues when reading protobuf encoded topics in the Streamer
Medium, packaging related changes may have side effects. I have run some tests with this change and have not found any packaging related issues though. …

[HUDI-9246] Confine protobuf shading to the hudi-io package

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaPairRDD.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaRDD.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieSparkRDDUtils.java
hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTableRecordIndex.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/data/TestHoodieJavaPairRDD.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/data/TestHoodieJavaRDD.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkRDDValidationUtils.java
hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java
hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java
hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListPairData.java
hudi-common/src/main/java/org/apache/hudi/common/data/HoodiePairData.java
hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieDataCleanupManager.java
hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieBackedTableMetadataDataCleanup.java
hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieDataCleanupManager.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieBackedMetadata.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataRecordIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

https://issues.apache.org/jira/browse/HUDI-9632
index lookup path now is equipped with uncache mechanism:
- add unpersistWithDependencies API so that as long as we hold a reference to a rdd, we can unpersist all its dependencies without caring what they are and not necessarily need to hold direct references to those rdds.
- the read path unpersist is splited into 2 scenarios
Happy case - the API directly return a hoodie data back to callers. In that case, it is callers responsibility to call the unpersist API once they are done with the rdd. So it always uses the pattern of
```
rdd = indexLookupAPI(..)
try {
// do all you need with the rdd
} finally {
rdd.unpersistWithDependencies
}
```
for unhappy case - after the API called some rdd.persist internally, yet before it returns back to …

[HUDI-9632] Index lookup path rdd unpersist support v2

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java
hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
hudi-common/src/test/java/org/apache/hudi/common/config/TestHoodieStorageConfig.java
hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieNativeAvroHFileReader.java
hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroFileReaderFactory.java
hudi-hadoop-common/src/test/java/org/apache/hudi/io/hadoop/TestHoodieHFileReaderWriter.java

This PR adds the support of bloom filter of keys prior to HFile lookup to avoid download and deserialization of the relevant Hfile blocks when possible. For instance, in RLI with insert heavy workloads, we can achieve significant speedup by pruning most of the keys prior to HFile lookup.
The following configs are added:
- `hoodie.metadata.bloom.filter.enable`: whether to use bloom filter in the files for lookup in the metadata table
- `hoodie.metadata.bloom.filter.type`: bloom filter type to use for files in the metadata table
- `hoodie.metadata.bloom.filter.num.entries`: number of entries to store in a bloom filter for files in the metadata table
- `hoodie.metadata.bloom.filter.fpp`: expected probability a false positive in a bloom filter for files in the metadata table
- …

[HUDI-9628] Add bloom filtering to prune keys prior to lookup in Metadata HFiles

---

hudi-client/hudi-java-client/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnJava.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java

- recordNeedsRewriteForExtendedAvroTypePromotion was creating a map of field names when we can just check if get is null
- we already have avro projection implemented so we don't need to have a rewritten method that does the same thing, but worse
cleaner code
low
N/A

[MINOR] Fix a few minor issues for java file group reader

---

hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
hudi-common/src/test/java/org/apache/hudi/common/model/TestDefaultHoodieRecordPayload.java

Since `event_time` is populated in HoodieWriteHandle, there is no need to duplicate the logic in `DefaultHoodieRecordPayload`. So far, `event_time` is the only payload that supports `event_time` metadata.
Therefore, we remove the support from `DefaultHoodieRecordPayload` now.
No duplicated support for `event_time` from `DefaultHoodieRecordPayload`.
Low. …

[HUDI-9673] Remove event_time metadata support from DefaultHoodieRecordPayload

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceReadWithDeletes.java

Spark reads should skip record with UPDATE_BEFORE operation
Ensure records with UPDATE_BEFORE operation are not read by spark snapshot scan
low

[HUDI-9671] Spark reads should skip record with UPDATE_BEFORE operation

---

website/releases/release-0.14.1.md
website/releases/release-0.15.0.md
website/releases/release-1.0.0.md
website/releases/release-1.0.1.md
website/releases/release-1.0.2.md

Updating 1.x release docs to call out ComplexKeyGenerator regression
Updating 1.x release docs to call out ComplexKeyGenerator regression
This is a doc update patch. 
The change itself is a doc update.

[MINOR][DOCS] Updating 1.x release to call out ComplexKeyGenerator regression

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelationV2.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala

…ering enabled
Disable skipping clustering for spark incremental query to avoid data duplication, see details in description of JIRA HUDI-9672.
Fix data duplication problem for spark incremental query.
low

[HUDI-9672] Disable skipping clustering for spark incremental query to avoid data duplication

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieInternalRowUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieInternalRowUtils.scala

Rename columns are not respected if a column is renamed to the name of a column in the old schema
avro had a similar issue: https://github.com/apache/hudi/pull/13663
Fix schema on read for spark log files
low
N/A

[HUDI-9683] Fix field renames in HoodieInternalRowUtils.genUnsafeRowWriter

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/savepoint/SavepointActionExecutor.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/savepoint/TestSavepointActionExecutor.java

In the case of cleaner policy `KEEP_LATEST_FILE_VERSIONS`, the `earliestCommitToRetain` is never set in the cleaner plan or clean metadata. The savepoint operation currently relies on this field to determine whether the instant is valid for a savepoint. If that value is not set, the code will assume all instants are valid which is not accurate.
To handle the case where the `KEEP_LATEST_FILE_VERSIONS` policy is used, we instead ensure that the instant provided to the savepoint is no older than the last commit before the last clean operation. Since the clean metadata does not include the number of file versions it kept, this is the only commit that we can guarantee is fully intact with this cleaner policy.
Adds more safety when creating savepoints
None
_Describe any necessary documentation …

[HUDI-9675] Add safety check to Savepoint when earliest commit retained is not set in cleaner output

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java

If the input RDD's parallelism is 1, we will use that parallelism as the target parallelism. We should set a default min of 10 to avoid scenarios where there is bottlenecking.
Adjusts the min parallelism to 10 for SparkHoodieBloomIndexHelper.
Low. The main config `hoodie.bloom.index.parallelism` still takes precedence.
None.

[HUDI-9687] Set min parallelism to 10 for SparkHoodieBloomIndexHelper

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRecordContext.java
hudi-common/src/main/java/org/apache/hudi/avro/AvroRecordContext.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-common/src/main/java/org/apache/hudi/common/engine/RecordContext.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieIndexedRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
hudi-common/src/main/java/org/apache/hudi/common/model/SerializableIndexedRecord.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/DeleteContext.java
hudi-common/src/main/java/org/apache/hudi/common/util/HoodieCommonKryoRegistrar.java
hudi-common/src/test/java/org/apache/hudi/common/model/TestSerializableIndexRecord.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/SchemaHandlerTestBase.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRecordContext.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/AvroOrcUtils.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/model/TestHoodieAvroIndexedRecord.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveRecordContext.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBufferedRecordMerger.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/model/TestHoodieRecordSerialization.scala

Currently, our payload based paths use `HoodieAvroRecord` to transport data between Spark Executors. As we move away from the Payloads though, we can start relying on the other record objects directly. The `HoodieAvroIndexedRecord` can fit our needs for transporting the Avro data but needs some changes to match the existing performance.
This change introduces a new class `SerializableIndexedRecord` which is used to manage the serialization of the data in the `HoodieAvroIndexedRecord`. Unlike payloads, the data is only written out to a byte array when it is required. This allows us to keep performance on par with the existing performance when working with data that only resides within a single machine.
For existing workflows that use `HoodieAvroIndexedRecord` like compaction, we expect to …

[HUDI-9641] Improve Serialization Performance of HoodieAvroIndexedRecord

---

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java

Currently CDCInputFormat uses HoodieRecordMerger. The Jira aims to replace it with BufferedRecordMerger.
NA
low
NA

[HUDI-9696] Use BufferedRecordMerger with CDCInputFormat

---

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUpgradeDowngradeCommand.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToNineUpgradeHandler.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestTwoToThreeUpgradeHandler.java
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngradeLegacy.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieBackedMetadata.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSixToFiveDowngradeHandler.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala

https://issues.apache.org/jira/browse/HUDI-9698
Discussed with @nsivabalan @yihua @linliu-code, this pr aims to make a couple of changes around what is considered a valid upgrade in 1.1.x.
For 1.1 going forward users will only be to upgrade table that are six or greater, and downgrade max to the lowest table version of six. Also depending on if `AUTO_UPGRADE` flag is disabled, we will need to ensure that the `hoodie.write.table.version` is brought down to the same version as the `hoodie.table.version` and skip the upgrade process. 
This pr adds several tests to ensure coverage of these new checks, as well as disables older legacy tests for versions below six.
The apis themselves are not changing but the behavior is which will mention in doc update section
medium risk, we have tried to add …

[HUDI-9698] Ensure valid upgrade/downgrade checks for table versions greater than SIX

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/StorageBasedLockProvider.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/models/LockProviderHeartbeatManager.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/StorageBasedLockConfig.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/TestStorageBasedLockProvider.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/models/TestLockProviderHeartbeatManager.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestStorageBasedLockConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
hudi-io/src/main/java/org/apache/hudi/storage/StorageSchemes.java

Adds the abstract implementation of the storage-based lock provider using conditional writes.
See RFC: https://github.com/apache/hudi/pull/12927
Based on 1.x PR: https://github.com/apache/hudi/pull/13103
Adds abstract lock provider implementation
None, without StorageLock implementation, this class will not be used.
Config updates added here: https://github.com/apache/hudi/pull/13104

[HUDI-9158] Add storage based lock provider abstract implementation to 0.x branch

---

hudi-gcp/pom.xml
hudi-gcp/src/main/java/org/apache/hudi/gcp/transaction/lock/GCSStorageLockClient.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/transaction/lock/TestGCSStorageLockClient.java

Adds the storage based lock provider implementation for GCS hudi tables.
Based on: https://github.com/apache/hudi/pull/13230
Allows conditional writes based locking for multi writer scenarios with hudi tables in gcs.
None
None
In order to test this we setup local hudi/spark bundles and ran some concurrent spark sql queries to tables with this LP enabled to ensure things functioned as expected.

[HUDI-9160] Add GCS implementation of StorageBasedLockProvider

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/StorageBasedLockProvider.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/TestStorageBasedLockProvider.java

The LP constructor format changed in 0.15, so need to support both formats in 0.x branch
Allows for 0.14 support
Low

[HUDI-9158] Add lock provider constructor which supports 0.14.x LP constructor format

---

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRecordContext.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/TestBaseSparkInternalRowReaderContext.java
hudi-common/src/main/java/org/apache/hudi/avro/AvroRecordContext.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
hudi-common/src/main/java/org/apache/hudi/common/engine/RecordContext.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecord.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderSchemaHandler.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/UpdateProcessor.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/FileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/KeyBasedFileGroupRecordBuffer.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/UnmergedFileGroupRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/SchemaHandlerTestBase.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestReusableKeyBasedRecordBuffer.java
hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestSortedKeyBasedFileGroupRecordBuffer.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRecordContext.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveRecordContext.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBufferedRecordMerger.java

[HUDI-9664](https://issues.apache.org/jira/browse/HUDI-9664) moves most of the record operation related APIs into a separate entity called Record context. This Jira aims to move some other pending APIs like seal, toBinary and project to Record context as well.
NA
low
NA

[HUDI-9704] Move remaining APIs from reader context to record context

---

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/HoodieTableMetaserverClient.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieBackedMetadata.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestSqlConf.scala
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java

The merging behaviors can not be changed once the table is created.
previously when building a meta client, there is opportunity for the `Builder` to override merging behaviors then triggers `hoodie.properties` rewrite, this should be forbidden.
low
none

[HUDI-9720] Forbid to modify hoodie.properties for read path

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestMergeIntoHoodieTableCommand.scala

Add an additional check for partial merging for MIT
Avoid data curruption for this corner case.
Low

[HUDI-9725] Disable partial merging when partial update mode is set for MIT

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToNineUpgradeHandler.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/NineToEightDowngradeHandler.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestEightToNineUpgradeHandler.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestNineToEightDowngradeHandler.java
hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCreateRecordUtils.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestEightToNineUpgrade.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPayloadDeprecationFlow.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala

Migrating MySqlDebeziumPayload to merge mode. 
Pending work:
Adding tests to TestPayloadDeprecationFlow for MySqlDebeziumPayload
MySqlDebeziumPayload in V9 will be using merge modes w/ multiple ordering fields.
medium

[HUDI-9691] Migrate MysqlDebeziumPayload to merge mode

---

hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java

This PR cherrypicks the #11250 to branch-0.x to remove mkdir in partition listing and add try catch to listStatus of partition.
As above
low
N/A

[HUDI-9681] Remove mkdir in partition listing and add try catch to listStatus of partition

---

hudi-gcp/src/main/java/org/apache/hudi/gcp/transaction/lock/GCSStorageLockClient.java
hudi-gcp/src/test/java/org/apache/hudi/gcp/transaction/lock/TestGCSStorageLockClient.java

GCS buckets could have underscores in their name, and getHost does NOT like it since it does not conform with the standard DNS naming. This PR fixes it by using getAuthority instead. S3 does not allow underscores so we can keep that as getHost().
None to core path or any APIs.
Low

[HUDI-9736] Fix lock provider for gcs when bucket has underscores

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/metrics/HoodieLockMetrics.java
hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestHoodieLockMetrics.java

Adds lock release metrics
Adds metrics when releasing locks
Low, this is just a counter

[HUDI-9742] Add lock release metrics

---

hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java

Fix empty partition handling with HoodieMetadataTableVadlidator. 
If a write failed mid-way after creating a new partition, there are chances that, FS based listing could list this partition, but MDT based listing may not. This patch accounts for this mis match with HoodieMetadataTableVadlidator. In other words, validation will not fail for this case. 
Fix empty partition handling with HoodieMetadataTableVadlidator. 
low
ticket number …

[HUDI-9750] Fix empty partition handling with HoodieMetadataTableVadlidator

---

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java

- Make methods protected so we can plug in our strategy at a clustering group level
- Allows more customization for clustering
None
No doc update

[HUDI-9759] Expose methods as protected in MultipleSparkJobExecutionStrategy

---

docker/compose/docker-compose_hadoop284_hive233_spark353_amd64.yml
docker/compose/docker-compose_hadoop284_hive233_spark353_arm64.yml
hudi-aws/pom.xml
hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
hudi-aws/src/main/java/org/apache/hudi/config/GlueCatalogSyncClientConfig.java
hudi-aws/src/test/java/org/apache/hudi/aws/sync/MockAwsGlueCatalogSyncTool.java
hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAwsGlueSyncTool.java
hudi-aws/src/test/java/org/apache/hudi/aws/testutils/GlueTestUtil.java
hudi-common/src/main/java/org/apache/hudi/common/config/ConfigProperty.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncTool.java
hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestDataHubSyncConfig.java
hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncClient.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/multisync/TestMultipleMetaSync.java

Recently the hudi community has put out several PRs in order to add new functionality to our existing glue and datahub related sync code paths. This PR aims to consolidate all these changes into one PR. Here are the original following prs
https://github.com/apache/hudi/pull/12314 (cross catalog sync functionality)
https://github.com/apache/hudi/pull/13424 (support database and table name for glue/datahub catalog)
https://github.com/apache/hudi/pull/13505 (glue resource tagging on database/table)
* Adds catalogid as part of glue sync
* Introduces new configs for glue and datahub sync for database and table name
* Introduces resource tagging for glue
medium 
For the new configs we likely will need to follow up with a doc update.

[HUDI-9771] Add improvements for Glue and Datahub Sync

---

.asf.yaml

Remove to avoid error:
> An error occurred while processing the github feature in .asf.yaml:
while parsing a mapping
unexpected key not in schema 'new_discussion'
in "hudi.git/.asf.yaml::github", line 27, column 1:
new_discussion: '{title} ({r ...
^ (line: 27)
---
With regards, ASF Infra.
For further information, please see the .asf.yaml documentation at:
https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

[MINOR] Update discussions settings

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java

Since HoodieAvroRecord has been deprecated due to payload deprecation.
Fix a corner case for payload deprecation.
Low.

[HUDI-9779] Use HoodieAvroIndexedRecord for records of error table

---

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/MysqlDebeziumSource.java
hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestMysqlDebeziumSource.java

If somehow debezium pushes an invalid MySQL event without binlog or position we block the event rather than generating an invalid event_seq
Adds validation for `MySqlDebeziumSource`
Low

[HUDI-9784] Adding mysql binlog validation for debezium

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala

Fixed upgrade and downgrade back for lower version tables (like V6→V9→V6) upgrade/downgrade failures caused by Avro format inconsistency between timeline archiver versions. The issue occurred because `TimelineArchiverV1` produces raw binary-encoded Avro records (without magic bytes) while `TimelineArchiverV2` produces Avro file format (with `Obj\x01` magic bytes). During upgrade/downgrade operations, this format mismatch caused `InvalidAvroMagicException` and `NoSuchElementException`.
**Key Changes:**
- Enhanced `LegacyArchivedMetaEntryReader.readInstant()` with magic bytes detection to ensure consistent Avro file format output
- Added specific archival configurations to `testV6TableUpgradeToV9ToV6` for controlled test environment
**User-Facing Changes:**
- Fixes table upgrade/downgrade …

[HUDI-9794] Convert the avro into file bytes in LegacyArchivedMetaEntryReader to keep forward compatibility

---

website/src/theme/BlogPostItem/BlogPostBox.js

When a blog link redirects to an external page, it opens in the same tab. As a result, the browser's back button doesn't return users to the blog list—it jumps back to the redirect page and then immediately back to the external blog, which creates a frustrating loop. Users are forced to manually open a new tab and navigate back to the blog list from the Hudi homepage.
To improve the experience, external blog links should open in a new tab—just like the video guide links do.
Minor
None
N/A

[Website][Minor] - Blog links redirect should open new tab

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java

Enable HFile block cache by default as to test stability.
Faster MDT reads potentially.
Low
Configurations for this should be automatically generated.

[MINOR] Enable HFile block cache by default

---

website/sidebars.js
website/versioned_sidebars/version-1.0.0-sidebars.json
website/versioned_sidebars/version-1.0.1-sidebars.json
website/versioned_sidebars/version-1.0.2-sidebars.json

Removed FAQ from Docs starting from 1.0.0
**Before:**
**After:**
None
none
Removed FAQ from Docs starting from 1.0.0

(docs) Removed FAQ from Docs starting from 1.0.0

---

.github/ISSUE_TEMPLATE/hudi_bug.yml
.github/ISSUE_TEMPLATE/hudi_community_support.yml
.github/ISSUE_TEMPLATE/hudi_feature.yml
.github/ISSUE_TEMPLATE/hudi_improvement.yml

Fixes issue where the issue template placeholder disappears on it. 
N/A
none
none
none

chore: Change issue template to use value instead of placeholder

---

website/src/theme/BlogPostItem/BlogPostBox.js

When a blog link redirects to an external page, it opens in the same tab. As a result, the browser's back button doesn't return users to the blog list—it jumps back to the redirect page and then immediately back to the external blog, which creates a frustrating loop. Users are forced to manually open a new tab and navigate back to the blog list from the Hudi homepage.
To improve the experience, external blog links should open in a new tab—just like the video guide links do.
Minor
None
N/A

fix: make sure blog links redirect opens a new tab

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala

There are two cases that currently re-trigger the `initializeFromFilesystem` on each write:
1. Partition stats are always missing on tables that are not partitioned
2. Secondary index is missing on tables with Record Level Index
Fix:
- Return that secondary index is only enabled if a column is specified for the index
- Remove partition stats index from the list of enabled partitions if the table is not partitioned
Reduces writer overhead
Low …

[HUDI-9611] Metadata writer tries to initialize invalid partitions

---

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala

Enhancing functional tests for incr and time travel query with diff ordering values. 
Adding functional tests for incr and time travel query with diff ordering values. 
Will help catch any breaking changes to time travel and incr query.
low

[MINOR] Incremental and Time Travel Query Testing

---

website/versioned_docs/version-1.0.2/cli.md

This PR fixes two issues in the CLI docs:
1) S3 setup commands use `wget -o` (log file) instead of `wget -O` (output file). With `-o`, the jar is not downloaded to the specified path, so copy/paste fails. Updated both lines to use `-O` in the “Using Hudi-cli in S3” section.
2) Minor grammar: “the shell can be fired by via …” → “fired up via …”.
Source page: Docs → Operating Hudi → CLI (version 1.0.2).

docs(cli): fix wget output flag (-O) in S3 instructions and “fired up via” wording

---

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java

For queries that run short, e.g., a few seconds, the impact of reading Hudi metadata table could be huge on the query latency. We have observed that the metadata read latency could be higher than that of the data read itself.  Therefore, reducing the latency of reading Hudi metadata is important for these short running queries. 
Previously the hfile reader could trigger multiple read for a single hfile in the MDT, e.g., one read is triggered when a data block of a hfile is requested. When the hfile becomes bigger, this could be become a huge problem. An feature that Hudi introduces to alleviate this problem is caching the entire hfile before reading it if hfile size is below a certain threshold. By default the threshold is 0MB. 
This change Increases the threshold from 0 MB to 50 MB, …

perf: Increase HFile prefetch threshold

---

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkRecord.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/format/FlinkRecordContext.java

Fix issue: https://github.com/apache/hudi/issues/13969
Adapt delete handling with `DeleteContext` for `HoodieFlinkRecord`
none.
low.

refactor: Adapt delete handling with DeleteContext for HoodieFlinkRecord

---

README.md
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/PositionBasedFileGroupRecordBuffer.java
hudi-hadoop-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java

Based on local testing using spark-sql, there are many places where extra noisy WARN logs are confusing.
- rewrote some messages to be correct/clear
- Added a line to README around Spark 4 profile
Cleaner spark-shell and spark-sql runs
none
Readme updated

docs: Change some noisy WARN logs to INFO/DEBUG

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkFileGroupReaderBasedMergeHandle.java

Fix issue https://github.com/apache/hudi/issues/13983
Do not spill for file group reader during Flink COW writing
Improve performance for flink cow writing.
low.

feat: Do not spill for file group reader during Flink COW writing

---

hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileDataBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileFileInfoBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileIndexBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileLeafIndexBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileMetaBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileMetaIndexBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileRootIndexBlock.java
hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileWriterImpl.java
hudi-io/src/test/java/org/apache/hudi/io/hfile/TestHFileWriter.java

https://github.com/apache/hudi/issues/13978
When HFile writer serializes an entry, e.g., a key value pair for data block or an index for index block, a ByteBuffer is used to allocate memory to keep serialized data. Since the capacity of the ByteBuffer cannot be changed once allocated and this buffer is used to serialize all entries for a block, its capacity should be set properly.
Previously the capacity of the buffer equals the HFile data block size (1MB by default) with the assumption that the key value pair should not be larger than the block size. However, we found that in fact the above assumption is not true. When this happened, `java.nio.BufferOverflowException` exception was thrown.
To solve the above problem, we remove the usage of ByteBuffer, and instead we use …

fix: Fix the buffer overflow issue for hfile writer

---

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
hudi-spark-datasource/hudi-spark4-common/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala

The updates to the command are causing runtime issues with schema mismatches.
For example, our internal release testing was throwing errors like:
```
org.apache.hive.service.cli.HiveSQLException: Error running query: java.lang.IllegalStateException: Couldn't find operation#8969 in [id#8958,name#8899,price#8970,ts#8959L,email#8902,department#8903,salary#8904,hire_date#8905,is_manager#8906,operation#8907,name#8978,price#8979,ts#8980L,email#8981,department#8982,salary#8983,hire_date#8984,is_manager#8985,id#8986]
```
In this error you can see the instance ID does not align with the available fields.
Reverts the changes from https://github.com/apache/hudi/commit/b689a711ef9ac9dff9cf0c80b3945163a784f63d
Fixes issues with Merge Into queries
None

fix: Merge Into Command updates cause runtime issues

---

docker/build_docker_images.sh
docker/compose/docker-compose_hadoop334_hive313_spark353_amd64.yml
docker/hoodie/hadoop/sparkadhoc/Dockerfile
docker/hoodie/hadoop/sparkadhoc/adhoc.sh
docker/setup_demo.sh
docker/stop_demo.sh

Fix issue https://github.com/apache/hudi/issues/13961
Update AMD64 Docker demo images to use latest Hudi version
None
None
None

fix: Update AMD64 Docker demo images to use latest Hudi version

---

hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java

Issue: https://github.com/apache/hudi/issues/14014
* Following test mentioned in issue thread is failing due to a bug. For now we would like to have ci green and will investigate async.
none
none
none

test: Disable testUpgradeOrDowngrade due to intermittent failures

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkFileGroupReaderBasedMergeHandle.java

Fix the issue: https://github.com/apache/hudi/issues/14009
Minor refactor: set merge memory for flink COW write path properly
none
low

refactor: Set merge memory for flink COW write path properly

---

hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineFactory.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/TimelineV1Factory.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CompletionTimeQueryViewV2.java
hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/TimelineV2Factory.java
hudi-common/src/test/java/org/apache/hudi/tableformat/TestTimelineFactory.java

Fix issue https://github.com/apache/hudi/issues/14018
Remove the eager loading of CompletionTimeQueryView
Improve performance for CompletionTimeQueryView
low.

perf: Remove the eager loading of CompletionTimeQueryView

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToNineUpgradeHandler.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPayloadDeprecationFlow.scala

This PR aims to enhance the coverage of payload testing by adding batches of data that contain higher and lower order values, as well as trying to add compaction and clustering commits on the timeline. We also add a downgrade flow to bring the table back its original version and do an additional write and then do verification on the data itself.
* Add higher and lower ordering values to data
* Add downgrade flow
* Add expected downgrade configs, and data validation.
None
None
<!-- Describe any necessary documentation update if there is any new feature, config, or user-facing change. If not, put "none".
None

test: Add lowering order and higher ordering values to payloads

---

hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java
hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListData.java

There is one path in the metadata table that is not properly leveraging iterators and needs a fix
- Added a new method for `HoodieListData` that takes in an iterator. This method will convert to a stream and add the proper hook to close the iterator if required.
- Updates the `readSliceAndFilterByKeysIntoList` to use the above constructor
Avoids reading data into a list just to create an iterator
None

perf: Avoid materializing into intermediate list in metadata table path

---

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/insert/TestInsertTable.scala

INSERT INTO operations silently deduplicate records when tables have preCombineField defined, even when explicitly setting `hoodie.spark.sql.insert.into.operation=insert`. This violates spark-sql writes expected behavior when sql.insert.into.operation is explicitly set to "insert". The root cause is that the presence of preCombineField automatically sets `combineBeforeInsert=true`, overriding INSERT operation semantics.
deduplication can be happen by explicitly setting `hoodie.combine.before.insert=true` if need be. 
fixes: https://github.com/apache/hudi/issues/14049
Fixed INSERT INTO operations to preserve duplicates when `hoodie.spark.sql.insert.into.operation=insert` is set.
User control - INSERT operations now correctly preserve duplicates when …

fix: INSERT INTO should preserve duplication with hoodie.spark.sql.insert.into.operation=insert

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java

When scheduling secondary or expression indexes, the code was incorrectly using the partition type prefix (`secondary_index_` or `expr_index_`) along with computed partition names (e.x `secondary_index_idx_rider`). It is later filtered out but the logs in between are getting improper results
Fixed `ScheduleIndexActionExecutor` to update the evaluation correctly
No much impact, just cleaner way
none
none

fix: tracking partition names correctly during secondary index

---

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexRecordGenerationUtils.java
hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala

For Secondary index record generation in MDT(non streaming writes), we were listing data table partitions w/o metadata table. We are fixing that in this patch to simplify and fix how we compute the secondary index stats. 
Fixing secondary index record generation for MDT (non streaming flow) to ensure we don't do file listing to poll data table for latest file slice. 
No unwanted fs listing for data table. 
low

fix: Fixing secondary record generation for MDT

---

website/docs/docker_demo.md

- This PR updates the Docker-based demo documentation to reflect compatibility with the latest Hudi version (1.1.0).
- The existing guide relied on older Spark, Hive, and Hadoop versions. 
- This update ensures reproducibility using officially maintained images, adds support for Hudi’s latest Spark 3.5 bundle, and demonstrates compatibility with external systems like MinIO.
**Before**
**After**
- Removed Presto (4c, 6c) and Trino (4d, 6d) from the demo
- Updated the namenode port
- Updated  beeline command and its output to show the tables
- Updated Hudi CLI command and the logs
- Refactored Dockerfiles and docker-compose.yml to support:
Hudi 1.1.0
Spark 3.5.3
Hive 3.1.3
Hadoop 3.3.4
JDK 8 across all components
- Introduced support for JupyterLab with PySpark for notebook-based …

docs: Updating Docker Demo Guide for latest Hudi Version
