hudi-integ-test/pom.xml, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkBulkInsertNode.scala
- Fixing hudi test suite for spark nodes and adding spark bulk_insert node
- Fixed spark nodes in hudi test suite infra
- Fixing hudi test suite for spark nodes and adding spark bulk_insert node
- Fixed spark nodes in hudi test suite infra
- Added config to enable row writing
=> [HUDI-2007] Fixing hudi_test_suite for spark nodes and adding spark bulk_insert node

.codecov.yml
This is attempt to disable codecov because its not useful and polluting PR
Follow codecov instructions to 
1) Disable codecov comments on PR
2) Not run coverage on patch/changes
3) Disbale project check
=> [MINOR] Disable codecov

docs/_docs/2_2_writing_data.md
Add documentation for schema evolution with example.
Build the docs locally and verified the changes.
=> [HUDI-1548] Add documentation for schema evolution

hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanSourceFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java, hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
=> [HUDI-2205] Rollback inflight compaction for flink writer

hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieConsoleMetrics.java
=> [HUDI-2211] Fix NullPointerException in TestHoodieConsoleMetrics

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
=> [HUDI-2216] Correct the words fiels in the comments to fields

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/compact/HoodieFlinkMergeOnReadTableCompactor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/compact/HoodieSparkMergeOnReadTableCompactor.java
*Close scanner after a single compaction operation completed*
- *call scanner.close() after compaction*
=> [MINOR] Close log scanner after compaction completed

hudi-flink/src/main/java/org/apache/hudi/util/RowDataToAvroConverters.java
Correct the words 'accroding' in the comments to 'according'
*(or)*
(or)
*(example:)* …
=> [MINOR] Correct the words accroding in the comments to according

hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java
=> [HUDI-2219] Fix NPE of HoodieConfig

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Fix no value present in incremental query on MOR
- *handle no instant being pull from incremental query*
Add test for MOR and COW functional test
=> [HUDI-2217] Fix no value present in incremental query on MOR

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddColumnsCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableChangeColumnCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTable.scala
=> [HUDI-2223] Fix Alter Partitioned Table Failed

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
Add option 'hive_sync.mode' for flink writer
*(or)*
(or)
*(example:)*
=> [HUDI-2228] Add option 'hive_sync.mode' for flink writer

hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
=> [HUDI-2241] Explicit parallelism for flink bulk insert

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestEmptyCommit.scala
=> [MINOR] fix checkstyle error introduced by merge of  #2296

docs/_docs/1_4_powered_by.md
=> [MINOR] Fixing an article Hyperlink

hudi-spark-datasource/hudi-spark2/src/test/java/org/apache/hudi/internal/TestHoodieBulkInsertDataInternalWriter.java, hudi-spark-datasource/hudi-spark2/src/test/java/org/apache/hudi/internal/TestHoodieDataSourceInternalWriter.java, hudi-spark-datasource/hudi-spark3/src/test/java/org/apache/hudi/spark3/internal/TestHoodieBulkInsertDataInternalWriter.java, hudi-spark-datasource/hudi-spark3/src/test/java/org/apache/hudi/spark3/internal/TestHoodieDataSourceInternalBatchWrite.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamerBase.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieMultiTableDeltaStreamer.java
- DeltaStreamer and MultiTableDeltaStreamer tests. 
- Bulk insert row writer tests
*(or)*
(or)
*(example:)* …
=> [HUDI-2253] Refactoring few tests to reduce run time. 

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieRowData.java, hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java, hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java, hudi-flink/src/main/java/org/apache/hudi/sink/bulk/sort/SortOperator.java, hudi-flink/src/main/java/org/apache/hudi/sink/bulk/sort/SortOperatorGen.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java
=> [HUDI-2254] Builtin sort operator for flink bulk insert

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
=> [MINOR] Improving runtime of TestStructuredStreaming by 2 mins

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java, hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapFunction.java, hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
=> [HUDI-2269] Release the disk map resource for flink streaming reader

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Pass the baseFileFormat to custom Meta sync interface implementations
1. Pass baseFileFormat in deltasync
2. Use syncHive() to avoid duplication of code
=> [HUDI-2272] Pass base file format to sync clients

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkMergeOnReadTable.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/delta/FlinkUpsertPreppedDeltaCommitActionExecutor.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/compact/FlinkCompactHelpers.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/rollback/FlinkMarkerBasedRollbackStrategy.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackHelper.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/FlinkClientUtil.java, hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/event/WriteMetadataEvent.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
=> [HUDI-2258] Metadata table for flink

hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/sql/IExpressionEvaluator.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionCodeGen.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/SqlTypedRecord.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
Fix the bug that merge into fails when table having nested struct type
*(or)*
(or)
*(example:)*
=> [HUDI-2232]  [SQL] MERGE INTO fails with table having nested struct type

website/blog/2021-07-21-streaming-data-lake-platform.md, website/docusaurus.config.js, website/src/pages/index.js
=> [DOCS] Continuous refinement of how we explain Hudi

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkMergeOnReadTable.java, hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java, hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java, hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java, hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
=> [HUDI-2274] Allows INSERT duplicates for Flink MOR table

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionHoodiePathCommand.scala
=> [MINOR] fix compile error in compaction command

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/sql/InsertMode.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/SqlKeyGenerator.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UuidKeyGenerator.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieSqlBase.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Support bulk insert for spark sql & fix the bug for combine before insert
*(or)*
(or)
*(example:)*
=> [HUDI-2208] Support Bulk Insert For Spark Sql

.github/PULL_REQUEST_TEMPLATE.md
Fixes a simple link to the contributing guide.
=> [MINOR] Fix contribution link in PULL_REQUEST_TEMPLATE

hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
*Correct TestKafkaSource class and comment*
- *Correct TestKafkaSource class and comment*
=> [MINOR] Correct TestKafkaSource class and comment

website/docs/flink-quick-start-guide.md
Improve the Flink guide docs.
*(or)*
(or)
*(example:)*
=> [HUDI-2293] Improve the Flink guide docs

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieDeltaStreamerException.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
HoodieDeltaStreamerException should exist in hudi-utilities
=> [MINOR] HoodieDeltaStreamerException should exist in hudi-utilities

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Set table props pertaining to virtual keys when a table is created via deltastreamer. 
Ran a local kafka + deltastreamer and ensured meta fields are disabled(with query). and here is the content of hoodie.properties
```
hoodie.table.precombine.field=impresssiontime
hoodie.table.partition.fields=userid
hoodie.table.type=COPY_ON_WRITE
hoodie.archivelog.folder=archived
hoodie.populate.meta.fields=false
hoodie.timeline.layout.version=1
hoodie.table.version=1
hoodie.table.recordkey.fields=impressionid
hoodie.table.base.file.format=PARQUET
hoodie.table.keygenerator.class=org.apache.hudi.keygen.SimpleKeyGenerator
hoodie.table.name=impressions_cow
```
=> [HUDI-2294] Adding virtual keys props in deltastreamer path

hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink/src/main/java/org/apache/hudi/util/RowDataProjection.java
=> [MINOR] Tweak change log more as FULL for flink streaming source

hudi-examples/src/main/java/org/apache/hudi/examples/spark/HoodieWriteClientExample.java
Fix method use error in HoodieWriteClientExample
HoodieWriteClientExample.class
=> [MINOR] Fix method use error in HoodieWriteClientExample

docker/demo/config/test-suite/templates/spark_command.txt.template
=> [HOT-FIX] Add apache license to spark_command.txt.template

hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/HoodieSparkFunctionalTestSuite.java
=> [MINOR] Fix SelectPackages in HoodieSparkFunctionalTestSuite

docker/demo/config/test-suite/templates/spark_command.txt.template
=> [Hot Fix] Add apache license to spark_command.txt.template

website/docs/flink-quick-start-guide.md, website/i18n/cn/docusaurus-plugin-content-docs/current/flink-quick-start-guide.md
Support Flink Chinese guide docs and fix some errors in flink English guide.
*(or)*
(or)
*(example:)*
=> [HUDI-2313] Support Flink Chinese guide docs

hudi-examples/src/main/java/org/apache/hudi/examples/spark/HoodieWriteClientExample.java, hudi-examples/src/main/scala/org/apache/hudi/examples/spark/HoodieDataSourceExample.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/QuickstartUtils.java
add partition level delete example
=> [HUDI-1674] Add partition level delete example

hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/batch/BatchBootstrapFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestSQL.java
Support Flink batch upsert.
*(or)*
(or)
*(example:)*
=> [HUDI-2316] Support Flink batch upsert

scripts/release/validate_staged_release.sh
=> [MINOR] Fixing release validation script to ignore tests packages while searching for non-binary files

hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/batch/BatchBootstrapFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
=> [MINOR] Some cosmetic changes for Flink

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
=> [HUDI-2339] Create Table If Not Exists Failed After Alter Table

hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/batch/BatchBootstrapOperator.java
=> [MINOR] Fix BatchBootstrapOperator initialization

docker/demo/config/test-suite/cow-spark-long-running.yaml, docker/demo/config/test-suite/cow-spark-simple.yaml, hudi-integ-test/README.md, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkDeleteNode.scala
Adding spark delete node to integ test suite.
- Adding spark delete node to integ test suite
- Added couple of yamls with spark nodes
- *Manually verified the change by running a integ test suite job locally with the added yamls*
=> [HUDI-2349] Adding spark delete node to integ test suite

website/docs/quick-start-guide.md
Fixing spark quick start guide for spark-sql
*(or)*
(or)
*(example:)*
=> [HUDI-2356] Fixing spark quick start guide for spark-sql

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
JIRA : https://issues.apache.org/jira/browse/HUDI-2359
In issue thread https://github.com/apache/hudi/issues/3321, there was a discussion around the functionality of `hoodie_is_deleted` field.
1. We wanted to ensure that when this field was being set to `true`, that the specified record would be deleted.
2. We also wanted to make sure that this field only needed to be set to `true` for an incoming record, and not for existing records.
The goal of this PR is to add unit tests that follow similar reproductions as discussed in the above github issue thread.
@nsivabalan example https://gist.github.com/nsivabalan/e5ac69677ed05e9f2749fae67d3abc19 
@nmukerje example https://github.com/nmukerje/misc/blob/master/Hudi/Hudi_Pyspark_Delete_Upsert_Test.ipynb
This change added test methods to existing …
=> [HUDI-2359] Add basic "hoodie_is_deleted" unit tests to TestDataSource classes

website/blog/2021-08-18-virtual-keys.md
- Adding virtual keys blog
*(or)*
(or)
*(example:)*
=> [HUDI-2317] Adding virtual keys blog

website/blog/2021-08-23-async-clustering.md
Blog on different async clustering strategies and how to setup.
```
cd website
npm run build
npm run serve
```
Goto http://localhost:3000/blog
=> [HUDI-2346] Async clustering usage blog

website/versioned_docs/version-0.9.0/quick-start-guide.md
Fixing 0.9.0 spark quick start page for spark-sql tabs
*(or)*
(or)
*(example:)*
=> [HUDI-2373] Fixing 0.9.0 spark quick start page for spark-sql tabs

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePreCommitValidatorConfig.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
Annotate two new classes of configs: Common configs and pre commit validation. Tested with local build of asf site
=> [HUDI-2378] Add common and pre validate configs to website

website/docusaurus.config.js, website/releases/download.md, website/releases/older-releases.md, website/releases/release-0.5.3.md, website/releases/release-0.6.0.md, website/releases/release-0.7.0.md, website/releases/release-0.8.0.md, website/releases/release-0.9.0.md, website/src/pages/index.js
=> [HUDI-2382] Add Hudi 0.9.0 release page with highlights

website/docs/quick-start-guide.md, website/versioned_docs/version-0.9.0/quick-start-guide.md
=> [HUDI-2381] Fixing quick start guide

website/releases/release-0.9.0.md
=> [MINOR] Fixing a link reference for a config in release page

hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
=> [HUDI-2379] Include the pending compaction file groups for flink streaming reader

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
Allow log file size more than 2GB
- *Change log file size config to long*
=> [HUDI-2384] Change log file size config to long

azure-pipelines.yml
- make tests run through without being blocked by style issues
- let GitHub Actions tasks give quick feedback on build, style and other
checks
=> [MINOR] Skip checkstyle and rat in Azure

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
=> [HUDI-2380] The default archive folder should be 'archived'

azure-pipelines.yml
=> [HUDI-2399] Rebalance CI jobs for shorter wait time

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHBaseIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java
=> [MINOR] Fixing some functional tests by moving to right packages

.asf.yaml
=> [MINOR] Remove commenting from Github, JIRA bridge

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java, hudi-flink/src/test/java/org/apache/hudi/source/TestFileIndex.java, hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
=> [HUDI-2403] Add metadata table listing for flink query source

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMetricsPrometheusConfig.java
Add the document to the PUSHGATEWAY configuration item.
=> [MINOR]Add the document to the PUSHGATEWAY configuration item

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBaseBloomIndexCheckFunction.java
=> [HUDI-2411] Remove unnecessary method overriden and note

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java, hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java, hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java, hudi-flink/src/main/java/org/apache/hudi/util/DataTypeUtils.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java, hudi-flink/src/test/java/org/apache/hudi/source/TestFileIndex.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
=> [HUDI-2412] Add timestamp based partitioning for flink writer

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
*Fix typo, 'requried' corrected to 'required'*
- *Fix typo, 'requried' corrected to 'required'*
*(or)*
(or)
*(example:)*
=> [MINOR] Fix typo, 'requried' corrected to 'required'

hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
=> [HUDI-2415]  Add more info log for flink streaming reader

website/contribute/how-to-contribute.md
*Fixed the broken link on the how-to-contribute page.*
*(or)*
(or)
*(example:)*
=> [DOCS] Fixed the broken link on the how to contribute page

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
*Fix typo,'compatiblity' corrected to 'compatibility'*
- *Fix typo,'compatiblity' corrected to 'compatibility'*
*(or)*
(or)
*(example:)*
=> [MINOR] Fix typo,'compatiblity' corrected to 'compatibility'

website/docs/flink-quick-start-guide.md, website/versioned_docs/version-0.9.0/flink-quick-start-guide.md
=> [HUDI-2453] Update the flink version of site

website/docs/quick-start-guide.md, website/releases/release-0.8.0.md, website/versioned_docs/version-0.9.0/quick-start-guide.md
=> [HUDI-2457] Fixing minor issues in docs

website/src/pages/talks-articles.md
Adding more talks and articles, sep 2021
*(or)*
(or)
*(example:)*
=> [MINOR] Adding more talks and articles, sep 2021

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroParquetConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieBaseParquetConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriterFactory.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieParquetWriter.java
=> [HUDI-2385] Make parquet dictionary encoding configurable

hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java, hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java, hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java, hudi-flink/src/test/java/org/apache/hudi/sink/StreamWriteITCase.java, hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
=> [HUDI-2483] Infer changelog mode for flink compactor

hudi-flink/src/main/java/org/apache/hudi/source/StreamReadOperator.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java, hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputSplit.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java
=> [HUDI-2485] Consume as mini-batch for flink stream reader

.github/workflows/bot.yml, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
=> [MINOR] fix typo,'SPAKR' corrected to 'SPARK'

hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java, hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectConfigs.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
*Fix typo,'Kakfa' corrected to 'Kafka' & 'parquest' corrected to 'parquet'*
- *Fix typo,'Kakfa' corrected to 'Kafka' & 'parquest' corrected to 'parquet'*
*(or)*
(or)
*(example:)*
=> [MINOR] Fix typo,'Kakfa' corrected to 'Kafka' & 'parquest' corrected to 'parquet'

website/learn/faq.md
Add an faq for overriding Hudi jars in EMR cluster
Website change in faq page
*(or)*
(or)
*(example:)*
- *Manually verified …
=> [MINOR] Add faq for overriding Hudi jar in EMR cluster

website/contribute/get-involved.md, website/contribute/how-to-contribute.md, website/contribute/report-security-issues.md, website/contribute/rfc-process.md, website/contribute/team.md, website/docusaurus.config.js
- Nested under the "Contribute" menu
- Largely same text as we had in cwiki
- Broke it up into three phases
- Reordered the side bar to make it nicer to read
*(or)*
(or)
*(example:)* …
=> [DOCS] New RFC Process

rfc/README.md, rfc/template.md
=> [MINOR] Add a RFC template and folder

hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java, hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
*Fix typo,'Hooodie' corrected to 'Hoodie' & 'reuqired' corrected to 'required'*
- *Fix typo,'Hooodie' corrected to 'Hoodie' & 'reuqired' corrected to 'required'*
*(or)*
(or)
*(example:)*
=> [MINOR] Fix typo Hooodie corrected to Hoodie & reuqired corrected to required

hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java, hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
Support JuiceFileSystem
https://github.com/juicedata/juicefs
*(or)*
(or)
*(example:)*
=> Support JuiceFileSystem

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java, hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java, hudi-flink/src/main/java/org/apache/hudi/util/FlinkTables.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
=> [HUDI-2654] Schedules the compaction from earliest for flink

website/docs/quick-start-guide.md
=> [HUDI-2627]Fix unsupported query instant time format in quickstart page

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
=> [HUDI-2005] Fixing partition path creation in AbstractTableFileSystemView

hudi-common/src/main/java/org/apache/hudi/common/util/ParquetReaderIterator.java, hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryQueue.java, hudi-common/src/test/java/org/apache/hudi/common/util/TestParquetReaderIterator.java
*Add close when producing records failed*
- *Add close when producing records failed*
- *Fix typos*
*(or)*
(or)
*(example:)*
=> [HUDI-2515] Add close when producing records failed

hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDatasetBulkInsertHelper.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieDatasetBulkInsertHelper.java
#3759  *Tips*
*(or)*
(or)
*(example:)*
=> [HUDI-2582] Support concurrent key gen for different tables with row writer path

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkAppendHandle.java
=> [HUDI-2678] flink writer writes huge log file

hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
=> [HUDI-2651] Sync all the missing sql options for HoodieFlinkStreamer

hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/aggregate/BootstrapAccumulator.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/aggregate/BootstrapAggFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/batch/BatchBootstrapOperator.java
=> [HUDI-2686] Proccess record after all bootstrap operator ready

hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
=> [HUDI-2698] Remove the table source options validation

website/docs/flink-quick-start-guide.md
=> [HUDI-2729] Fix the options of flink quick start page

rfc/README.md
Claiming a RFC number for the Metadata based bloom index feature
Updated the RFC readme for Metadata based bloom index feature. 
*(or)*
(or)
*(example:)*
=> [HUDI-2589] Claiming RFC-37 for Metadata based bloom index feature.

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/IntervalTreeBasedGlobalIndexFileFilter.java
*this pull request fix typo in IntervalTreeBasedGlobalIndexFileFilter*
*fix typo*
- *fix typo in IntervalTreeBasedGlobalIndexFileFilter*
=> [MINOR] fix typo in IntervalTreeBasedGlobalIndexFileFilter

website/src/pages/talks-articles.md
Updating article links and talks for sep, oct, nov 2021
*(or)*
(or)
*(example:)*
=> [MINOR] Updating article links and talks for sep, oct, nov 2021

hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
As mentioned in https://github.com/apache/hudi/issues/3971
*(or)*
(or)
*(example:)*
=> [HUDI-2760] Check --source-avro-schema-path  parameter

hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
=> [HUDI-2789] Flink batch upsert for non partitioned table does not work

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
=> [HUDI-2791] Allows duplicate files for metadata commit

rfc/README.md
Claim RFC number for RFC for debezium source for deltastreamer
Add new RFC entry in RFC readme
=> Claim RFC number for RFC for debezium source for deltastreamer

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/InputBatch.java
*optimize in the constructor of inputbatch class*
- *optimize in the constructor of inputbatch class*
=> [MINOR] optimize in constructor of inputbatch class

rfc/README.md
=> [HUDI-2813] Claim RFC number for RFC for spark datasource V2 Integration

hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactFunction.java
=> [HUDI-2799] Fix the classloader of flink write task

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
The builds are failing due to compilation error that is fixed by this patch.
*(or)*
(or)
*(example:)*
=> [MINOR] Fix instant parsing in HoodieClusteringJob

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
Fix typo,'multipe' corrected to 'multiple'
Fix typo,'multipe' corrected to 'multiple'
=> [MINOR] Fix typo,'multipe' corrected to 'multiple'

website/docs/snapshot_exporter.md, website/sidebars.js
HoodieSnapshotExporter did not have any documentation.
- Added docs for HoodieSnapshotExporter
This pull request is a docs update only
=> [HUDI-2726] - Docs for HoodieSnapshotExporter

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableDropPartitionCommand.scala
=> [HUDI-2838] refresh table after drop partition

rfc/README.md
Claim rfc 40 number for Hudi Connector for Trino
*(or)*
(or)
*(example:)*
=> [HUDI-2688] Claim rfc 40 for Hudi Connector for Trino

website/community/syncs.md
Someone in Slack requested to see European timezones in the link for the community sync
- Updated the timezone link
- Added the Zoom join link up front for easy discoverability
This pull request is a trivial docs change.
=> [MINOR] - Docs - Updated Timezone link for community sync

website/docs/hoodie_cleaner.md, website/sidebars.js
Add documentation for the HoodieCleaner utility
- added docs for HoodieCleaner utility
This pull request is docs changes only
=> [HUDI-2805] - Docs for HoodieCleaner

website/docs/file_sizing.md, website/sidebars.js
Added docs for auto file sizing management guide.
- Added file-sizing doc
- Added it to the guides section
This is a docs change only
=> [HUDI-2822] Doc for auto file sizing guide

packaging/hudi-kafka-connect-bundle/pom.xml, packaging/hudi-utilities-bundle/pom.xml
Add JMX deps in hudi utilities and kafka connect bundles. As a follow up to: https://github.com/apache/hudi/pull/3632
=> [HUDI-2853] Add JMX deps in hudi utilities and kafka connect bundles

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamerWithMultiWriter.java
Fix build failure on master due to checkstyle issues
- Fix unused imports.
Build passes.
=> [MINOR] Fix build failure due to checkstyle issues

website/docs/metrics.md
Docs for Prometheus metrics reporter
- Added Docs for Prometheus metrics reporter
=> [HUDI-2727] - Docs for Prometheus metrics reporter

hudi-aws/pom.xml, hudi-aws/src/main/java/org/apache/hudi/aws/cloudwatch/CloudWatchReporter.java, hudi-aws/src/main/java/org/apache/hudi/config/AWSLockConfiguration.java, hudi-aws/src/main/java/org/apache/hudi/config/HoodieAWSConfig.java, hudi-aws/src/main/java/org/apache/hudi/config/HoodieMetricsCloudWatchConfig.java, hudi-aws/src/test/java/org/apache/hudi/aws/cloudwatch/TestCloudWatchReporter.java, hudi-client/hudi-client-common/pom.xml, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/cloudwatch/CloudWatchMetricsReporter.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/cloudwatch/TestCloudWatchMetricsReporter.java, hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
=> [HUDI-2801] Add Amazon CloudWatch metrics reporter

website/docs/file_sizing.md, website/docs/migration_guide.md, website/docs/snapshot_exporter.md, website/sidebars.js
Renamed snapshotting, exporter, and bootstrapping pages for consistency
Renamed snapshotting, exporter, and bootstrapping pages for consistency
Minor docs change only
=> [MINOR] Docs - Renaming pages for consistency

packaging/hudi-flink-bundle/pom.xml
Shade org.apache.hadoop.hive.ql package for flink bundle jar
- *Shade org.apache.hadoop.hive.ql package for flink bundle jar*
=> [HUDI-2851] Shade org.apache.hadoop.hive.ql.optimizer package for flink bundle jar

packaging/hudi-flink-bundle/pom.xml
HUDI-2801 makes this jar as required.
*(or)*
(or)
*(example:)*
=> [MINOR] Include hudi-aws in flink bundle jar

website/docs/transforms.md
Adding basic documentation for the Hoodie Transformer Utilities
- Added transforms.md
This is a docs only change
=> [HUDI-2806] - Docs for Transformer Utilities

hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkEnvCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java
- Added a way to set the spark master env so that commands needing spark execution
can work
- Added metadata --validate option to validate the metadata table correctness
compared to the fs based listing
- Fixed partition and file listings display
*(or)*
(or)
*(example:)*
=> [HUDI-2845] Metadata CLI - files/partition file listing fix and new validate option

hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java
=> [HUDI-2856] Bit cask disk map delete modified

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
=> [MINOR] Follow ups from HUDI-2861 (re-use same rollback instant for failed rollback)

website/docs/quick-start-guide.md
=> [MINOR] Fixing instant time query format

scripts/release/create_source_release.sh
=> [MINOR] Fix syntax error in create_source_release.sh

website/src/pages/talks-articles.md
=> [MINOR] Adding halodoc link to list of articles

website/src/pages/index.js
Add a banner to call for voting for release 0.10.0
=> [HUDI-2885] Add banner to call for voting for latest release version

website/src/pages/index.js
[HUDI-2885] Fix the latest release banner
=>  [HUDI-2885] Fix the latest release banner

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala
*Add support ignoring case in update sql operation*
- *Add support ignoring case in update sql operation*
- *Added unit test in TestUpdateTable.*
=> [HUDI-2642] Add support ignoring case in update sql operation

website/docs/configurations.md, website/docs/markers.md, website/sidebars.js
Added documentation for markers
- added marker docs
- updated the default value in configs that is changing in 0.10.0
This is docs change only.
=> [HUDI-2825] - Docs for markers

hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java, hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/WriteProfile.java
=> [minor] Refactor write profile to always generate fs view

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
=> [MINOR] use catalog schema if can not find table schema

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
=> [HUDI-2933] DISABLE Metadata table by default

hudi-flink/src/main/java/org/apache/hudi/table/catalog/CatalogOptions.java, hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java, hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogFactory.java, hudi-flink/src/main/java/org/apache/hudi/table/catalog/TableOptionProperties.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
Support flink catalog to help user use flink table conveniently
- *Support flink catalog to help user use flink table conveniently*
- *Added TestHoodieCatalog to verify the change.*
=> [HUDI-2877] Support flink catalog to help user use flink table conveniently

.gitignore, .idea/vcs.xml
Add IssueNavigationLink for IDEA, so we would click the link to jira and PR from idea
*(or)*
(or)
*(example:)*
=> [HUDI-2916] Add IssueNavigationLink for IDEA

packaging/hudi-timeline-server-bundle/pom.xml
Use maven-shade-plugin version for hudi-timeline-server-bundle from main pom.xml
=> [MINOR] Use maven-shade-plugin version for hudi-timeline-server-bundle from main pom.xml

website/docs/indexing.md, website/docs/key_generation.md, website/docs/writing_data.md, website/sidebars.js
Documenting Public APIs
- added mention of Public APIs to indexing, key gen, commit callbacks.
- noticed that transformers wasn't in the sidebars, so I added it.
=> [HUDI-2829] - Document Public APIs

doap_HUDI.rdf
=> [MINOR] Update DOAP with 0.10.0 Release

website/docs/metadata.md, website/sidebars.js
Added docs for Hudi Metadata Table
Added docs for Hudi Metadata Table
This is a docs change only
=> [HUDI-2821] - Docs for Metadata Table

README.md, hudi-utils/README.md, hudi-utils/pom.xml, website/docs/configurations.md
- Updating configurations page to pull in latest configs.
- Fixed main readme to include steps to refresh configs
*(or)*
(or)
*(example:)*
=> [HUDI-2963] Updating configs with latest

website/docs/configurations.md
=> [MINOR] Updating configs to reflect dynamoDB based lock configs

website/docs/hoodie_deltastreamer.md
Added docs for SchemaProviders and Sources
- Added docs for SchemaProviders and Sources
=> [HUDI-2827] - Docs for DeltaStreamer SchemaProviders, Sources, and Checkpoints

website/docs/write_operations.md, website/docs/writing_data.md
Added more details for deletes and described high level full write path as described in this deep dive: https://www.youtube.com/watch?v=N2eDfU_rQ_U
=> [HUDI-2956] - Updating write docs for deletes and full write path description

hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
*(or)*
(or)
*(example:)*
CC @guanziyue
=> [MINOR] Fix Compile broken

website/docs/metadata.md, website/sidebars.js
Added benchmark results from VC's study posted here: https://github.com/apache/hudi/pull/4226#issuecomment-989162876
- adjusted message of metadata table motivation
- added benchmark results
docs change only
=> [HUDI-2821] - Docs for Metadata Table - added reference to vc's benchmark study

.github/ISSUE_TEMPLATE/SUPPORT_REQUEST.md
Fixes a broken link in SUPPORT_REQUEST template
=> [MINOR] Fix FAQ link in SUPPORT_REQUEST template

rfc/README.md
=> [HUDI-2973] Claiming RFC number for data skipping index (updated version)

website/docs/quick-start-guide.md
=> [HUDI-2878] enhance hudi-quick-start guide for spark-sql

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/AbstractWriteHelper.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/WriteMarkers.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
The pull request improve the job description of SparkUI for writing hudi. 
Before:
After:
Add or improve spark UI description for different processes in hudi DeltaStreamer ingestion.
=> [HUDI-2849] improve SparkUI job description for write path

hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
=> [HUDI-2912] Fix CompactionPlanOperator typo

website/docusaurus.config.js, website/releases/download.md, website/releases/older-releases.md, website/releases/release-0.10.0.md, website/releases/release-0.7.0.md, website/releases/release-0.8.0.md, website/releases/release-0.9.0.md, website/src/pages/index.js
=> [HUDI-2976] Add Hudi 0.10.0 release page with highlights

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AsyncCleanerService.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java
=> [HUDI-2959] Fix the thread leak of cleaning service

hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, packaging/hudi-flink-bundle/pom.xml
=> [HUDI-2985] Shade jackson for hudi flink bundle jar

website/docs/flink-quick-start-guide.md, website/docs/hoodie_deltastreamer.md, website/versioned_docs/version-0.10.0/flink-quick-start-guide.md, website/versioned_docs/version-0.10.0/hoodie_deltastreamer.md
=> [minor] fix flink notification for streaming ingestion and quick start

hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/AbstractSyncHoodieClient.java
=> [HUDI-3022] Fix npe for isDropPartition method

rfc/README.md
=> [HUDI-2998] Claiming RFC number for consistent hashing index

rfc/README.md
=> [HUDI-3046] Claim RFC number for RFC for Compaction / Clustering Service

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamerWithMultiWriter.java
=> [HUDI-3043] De-coupling multi writer tests

website/community/team.md
Add myself to the committer list on the team page.
As above.
The site can be built and up.
=> [MINOR] Update committer list

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
=> [MINOR] remove unused import in HoodieFileIndex

azure-pipelines.yml
=> [MINOR] Increasing CI timeout to 90 mins

website/docs/flink-quick-start-guide.md, website/versioned_docs/version-0.10.0/flink-quick-start-guide.md
=> [HUDI-3084] Fix the link of flink guide page

hudi-examples/README.md
=> [HUDI-3027] Update hudi-examples README.md

hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java, hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
=> [HUDI-2547] Schedule Flink compaction in service

hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
=> [HUDI-3098] Fixing dynamoDbLockConfig required prop check

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
=> [MINOR] HoodieInstantTimeGenerator improve method used

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DropHoodieTableCommand.scala
*Fix Purge Drop MOR Table Inconsistent Cause query error*
link: [HUDI-3108](https://issues.apache.org/jira/browse/HUDI-3108)
*Fix Purge Drop MOR Table Inconsistent Cause query error*
*(or)*
(or)
*(example:)*
=> [HUDI-3108] Fix Purge Drop MOR Table Cause error

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/parquet/ParquetRowDataWriter.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/parquet/ParquetSchemaConverter.java, hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/io/storage/row/parquet/TestParquetSchemaConverter.java, hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/ParquetColumnarRowSplitReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/ParquetDecimalVector.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/data/ColumnarArrayData.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/data/ColumnarMapData.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/data/ColumnarRowData.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/HeapArrayVector.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/HeapMapColumnVector.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/HeapRowColumnVector.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/MapColumnVector.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/RowColumnVector.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/VectorizedColumnBatch.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ArrayColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/BaseVectorizedColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/MapColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetDataColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetDataColumnReaderFactory.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/RowColumnReader.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestSQL.java
Support component data types for flink bulk_insert
Support component data types for flink bulk_insert
*(or)*
(or)
*(example:)*
=> [HUDI-3083] Support component data types for flink bulk_insert

hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java
=> [HUDI-3120] Cache compactionPlan in buffer

hudi-examples/src/main/java/org/apache/hudi/examples/spark/HoodieSparkBootstrapExample.java
=> [HUDI-3040] Fix HoodieSparkBootstrapExample error info for usage

website/src/pages/talks-articles.md
Updated recent article references
Updated recent article references
docs change only
=> [MINOR] - Updated articles doc page through 2021

pom.xml
=> [HUDI-3134] Fix insert error after adding columns on Spark 3.2.0

hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
=> [HUDI-3140] Fix bulk_insert failure on Spark 3.2.0

hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
With fast ingestion through deltastreamer (no min sync interval) and frequent async clustering enabled, it could be possible that two clustering plans created the same replacecommit metadata. This PR avoid the duplication by merging them.
EDIT: After discussion (see comments below), we discarded merging duplicates. Instead, we will error it out with a suggesttion to add delay.
Manually verified by running deltastreamer for 30 commits multiple times. Could not reproduce with this patch.
=> [HUDI-2774] Handle duplicate instants while fetching pending clustering plans

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
=> [HUDI-2966] Closing LogRecordScanner in compactor

hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
=> [HUDI-3171] Sync empty table to hive metastore

website/docusaurus.config.js, website/src/pages/roadmap.md
=> [DOCS] Summarizing roadmap for Hudi based on JIRA epics' status

website/docs/metrics.md, website/versioned_docs/version-0.10.0/metrics.md
Added cloudwatch docs
Added cloudwatch docs
docs change only
=> [HUDI-3080] - added cloudwatch docs

website/docs/configurations.md, website/versioned_docs/version-0.10.0/configurations.md
Adding docs for config details
- Adding docs for config details
=> [HUDI-3076] - Docs for config file details

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelector.java
Adding support to ignore files in S3 incremental source.
Manually verified the ignore filtering works as expected.
=> [HUDI-3009] making some fixes to S3 incremental source

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
=> [HUDI-3131] fix ctas error in spark3.1.1

website/blog/2021-08-18-improving-marker-mechanism.md
Fix performance table content in marker blog.
The site can build and launch.
=> [MINOR] Fix performance table in marker blog

rfc/README.md
=> [HUDI-3211][RFC-44] Claim RFC number for RFC for Hudi Connector for Presto

hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroWriteSupport.java
=> [MINOR] refactor HoodieAvroWriteSupport with remove unused static var

website/docs/flink-quick-start-guide.md, website/docs/hoodie_deltastreamer.md, website/versioned_docs/version-0.10.0/flink-quick-start-guide.md, website/versioned_docs/version-0.10.0/hoodie_deltastreamer.md
=> [HUDI-3230] Add streaming read for flink document

rfc/README.md
Claim RFC-45 for async metadata indexing.
*(or)*
(or)
*(example:)*
=> [HUDI-3225] Claim RFC-45 for async metadata indexing

hudi-sync/hudi-hive-sync/pom.xml, hudi-utilities/pom.xml, pom.xml
#4574 for minor release branch.
*(or)*
(or)
*(example:)*
=> [HUDI-3235] Fix ClassNotFoundException due to log4j-core dependency

packaging/hudi-presto-bundle/pom.xml
#4551 for minor release 0.10.1
*(or)*
(or)
*(example:)*
=> [HUDI-3010] Unbundle parquet-avro and shade other dependencies in presto bundle

hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
This PR fixes a local flaky test in TestFSUtils.
=> [MINOR] Fix local flaky test in TestFSUtils

website/docs/cli.md
Adds instructions to our website to usage hudi-cli with S3 dataset.
*(or)*
(or)
*(example:)*
=> [HUDI-2083] Adding instructions to access S3 in hudi-cli

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteTable.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala
=> [HUDI-2968] add UT for update/delete on non-pk condition

hudi-common/src/main/java/org/apache/hudi/common/util/TablePathUtils.java
=> [MINOR] Fix delete unused parameter in `TablePathUtils`

website/src/pages/talks-articles.md
Adding links to Hudi Meetup at Uber, Jan 2022
=> [HUDI-3256] Adding Video of Hudi Meetup on Jan11, 2022

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
=> [MINOR] Minor improvement in JsonkafkaSource

packaging/hudi-hadoop-mr-bundle/pom.xml
Shade org.apache.parquet.avro. to org.apache.hudi.org.apache.parquet.avro. for hudi-hadoop-mr-bundle module
Modify the pom file of the a module hudi-hadoop-mr-bundle
=> [HUDI-3261] Query rt table by hive cli throw NoSuchMethodError

website/docs/quick-start-guide.md, website/versioned_docs/version-0.10.0/quick-start-guide.md
*Docs for Spark SQL type support 0.10.0+*
link: [HUDI-3151](https://issues.apache.org/jira/browse/HUDI-3151)
*(or)*
(or)
*(example:)* …
=> [HUDI-3151] Docs for Spark SQL type support 0.10.0+

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/bootstrap/BootstrapUtils.java
=> [HUDI-3277] Filter non-parquet files in bootstrap procedure

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
=> [MINOR] Fix typo in the doc of BULK_INSERT_SORT_MODE

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
*Code optimization and clean up unused code in HoodieSparkSqlWriter*
- *Code optimization and clean up unused code in HoodieSparkSqlWriter*
*(or)*
(or)
*(example:)*
=> [HUDI-3271] Code optimization and clean up unused code in HoodieSparkSqlWriter

website/docs/quick-start-guide.md, website/versioned_docs/version-0.10.0/quick-start-guide.md
=> [MINOR] [DOCS] fix a typo in Spark quick start example

packaging/hudi-flink-bundle/pom.xml
=> [minor] Fix hive-exec scope of flink bundle jar

packaging/hudi-integ-test-bundle/pom.xml, packaging/hudi-utilities-bundle/pom.xml
=> [HUDI-3262] Fixing utilities and integ test suite bundle to include hudi spark datasources

pom.xml
Fix #4638 by upgrading rocksdb version
Upgrading rocksdb version to v6.27.3 in base pom.xml
*(or)*
(or)
*(example:)*
=> [HUDI-3306] Upgrade rocksdb version

rfc/README.md
Claim the number for the RFC-46 dedicated to "Optimizing the handling of the Record Payload"
Added the records into the RFCs table
N/A
=> [HUDI-3217] Claim the number for RFC-46

doap_HUDI.rdf
=> [HUDI-3328] Updating doap file for release 0.10.1

website/docs/syncing_metastore.md
Add documentation for different hive sync modes.
*(or)*
(or)
*(example:)*
=> [HUDI-2521] Add doc for hive sync modes

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/SerializableHoodieRollbackRequest.java
=> [MINOR] fixing serializability of SerializableHoodieRollbackRequest

website/docs/configurations.md
=> [HUDI-3331] Updating configs from 0.10.1

website/docs/docker_demo.md
This PR adjusts Hudi CLI commands for compaction in Docker Demo so that they have expected behavior for the demo.
The site can build and show updated content.
=> [MINOR] Adjust Hudi CLI commands for compaction in Docker Demo

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Added more logging for debugging checkpoint resume logic
=> [MINOR] Added log to debug checkpoint resumption when set to 0

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
=> [HUDI-3253] preferred to use the table's own location

website/docs/quick-start-guide.md, website/versioned_docs/version-0.10.1/quick-start-guide.md
=> [MINOR] Fixing 0.10.1 docs

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
=> [HUDI-3293] Fixing default value for clustering small file config

hudi-examples/src/main/scala/org/apache/hudi/examples/spark/HoodieDataSourceExample.scala
This pull request is to standard code format for HoodieDataSourceExample.scala
- *Align code in HoodieDataSourceExample.scala*
=> [HUDI-3344] Standard format for HoodieDataSourceExample.scala

hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
Simplify building precommit file system view. 
Avoid mutating list and only use immutable stream API to build precommit file system view. This helps avoid ConcurrentModificationException that happens occasionally (HUDI-3058)
Minor refactoring. Existing tests in TestHoodieClientOnCopyOnWriteStorage cover functional correctness.
=> [HUDI-3058] Simplify Precommit file system view

docker/demo/config/test-suite/cow-spark-long-running.yaml, docker/demo/config/test-suite/cow-spark-simple.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-hive.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml, docker/demo/config/test-suite/detlastreamer-long-running-example.yaml, docker/demo/config/test-suite/simple-clustering-hive.yaml, docker/demo/config/test-suite/simple-clustering.yaml, docker/demo/config/test-suite/simple-deltastreamer-hive.yaml, docker/demo/config/test-suite/simple-deltastreamer.yaml, hudi-integ-test/README.md, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseValidateDatasetNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/ValidateDatasetNode.java, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertNode.scala
Fixing spark datasource tests in integ test suite framework
*(or)*
(or)
*(example:)*
=> [HUDI-3312] Fixing spark yaml and adding hive validation to integ test suite

hudi-client/hudi-flink-client/pom.xml, hudi-flink/pom.xml, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunctionWithRateLimit.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink/src/main/java/org/apache/hudi/source/StreamReadOperator.java, hudi-flink/src/test/java/org/apache/hudi/sink/StreamWriteITCase.java, hudi-flink/src/test/java/org/apache/hudi/sink/utils/CollectorOutput.java, hudi-flink/src/test/java/org/apache/hudi/sink/utils/CompactFunctionWrapper.java, hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockStateInitializationContext.java, hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockStreamingRuntimeContext.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, pom.xml
=> [HUDI-3389] Bump flink version to 1.14.3

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
…ource Using HoodieDeltaStreamer
*(or)*
(or)
*(example:)*
=> [HUDI-3413] Fix empty message jackson parse error in JsonKafkaSource

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
=> [MINOR] Unused import introduced by HUDI-3413

website/src/pages/index.js
=> [MINOR] Fixing release link in homepage

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestArchivedCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCompactionCommand.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncArchiveService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncCleanerService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/async/TestAsyncArchiveService.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
- add `AsyncArchiveService` and its UT
- rename `HoodieTimelineArchiveLog` to `HoodieTimelineArchiver`
- move `AsyncCleanerService` to `org.apache.hudi.async` for alignment
- make `BaseHoodieWriteClient` spawn async archive thread conditionally based on configs `hoodie.archive.automatic` and `hoodie.archive.async`
=> [HUDI-1576] Make archiving an async service

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncArchiveService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncCleanerService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncClusteringService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncCompactService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncTableService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/RunsTableService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/async/TestHoodieAsyncTableService.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
=> [HUDI-2931] Add config to disable table services

website/docs/faq.md, website/docs/quick-start-guide.md, website/learn/faq.md
Adding faq to add guidance on converting COW table to MOR
*(or)*
(or)
*(example:)*
=> [MINOR] Adding faq to convert COW table to MOR

website/docs/disaster_recovery.md, website/sidebars.js
=> [HUDI-1273] Adding savepoint and restore docs to website

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
This PR fixes typos and improves docs in HoodieMetadataConfig
=> [MINOR] Fix typos and improve docs in HoodieMetadataConfig

hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieSchemaProviderException.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/HiveSchemaProvider.java
=> [HUDI-3464] Fix wrong exception thrown from HiveSchemaProvider

packaging/hudi-flink-bundle/pom.xml
=> [HUDI-3476] Remove the shade pattern for parquet for flink bundle jar

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
=> [HUDI-3455] Fixing checkpoint management in S3IncrSource

hudi-common/src/main/avro/HoodieClusteringGroup.avsc
=> [HUDI-3420] Remove duplicates type in HoodieClusteringGroup.avsc

website/docs/disaster_recovery.md
=> [MINOR] fixing savepoint restore docs

website/docs/s3_hoodie.md
This task to add a note for S3  versioned bucket
Updated s3_hoodie doc
=> [HUDI-3496] Add a note for S3 Versioned Bucket

website/src/pages/roadmap.md
=> Update roadmap page to reflect latest state

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java, hudi-flink/src/main/java/org/apache/hudi/sink/BucketStreamWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/BucketStreamWriteOperator.java, hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
=> [minor] Cosmetic changes following HUDI-3315

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
Fix timezone config comparison
=> [MINOR] fix UTC timezone config

hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeFileSplit.java
Add unit test to ensure de-/serialization working for `HoodieRealtimeFileSplit`.
=> [HUDI-3348] Add UT to verify HoodieRealtimeFileSplit serde

website/src/pages/roadmap.md
"JDBC Incremental Source" move to 0.12
=> [DOCS] Update roadmap

azure-pipelines.yml
=> [MINOR] Add IT CI Test timeout option

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/ParquetDecimalVector.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/AbstractColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ArrayColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/FixedLenBytesColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/Int64TimestampColumnReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java, hudi-flink/src/main/java/org/apache/hudi/table/format/cow/vector/reader/RunLengthDecoder.java, hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java, hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java, hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
=> [HUDI-3581] Reorganize some clazz for hudi flink

docker/demo/config/test-suite/cow-spark-long-running.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml, docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml
=> [HUDI-3613] Adding/fixing yamls for metadata

packaging/hudi-utilities-bundle/pom.xml
=> [MINOR] Remove repeated kafka-clients dependencies

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileScanRDD.scala
Fix this:
```java
22/03/17 14:58:13 INFO HoodieFileScanRDD: Reading File null
```
*(or)*
(or)
*(example:)*
=> [MINOR] HoodieFileScanRDD could print null path

website/src/pages/talks-articles.md
*Adding Video link of Hudi Meetup on March1st, 2022*
=> [HUDI-3658] Adding Video Link of Hudi Meetup on March1st, 2022

docker/demo/config/test-suite/deltastreamer-medium-clustering.yaml, docker/demo/config/test-suite/spark-medium-clustering.yaml, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/ValidateAsyncOperations.java
=> [HUDI-3656] Adding medium sized dataset for clustering and minor fixes to integ tests

hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkUpsertNode.scala
=> [MINOR] Fixing sparkUpdateNode for record generation

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
=> [HUDI-3697] Fixing non partitioned all files record in MDT

rfc/README.md
Claim RFC number 48 for RFC on LogCompaction action for MOR tables.
Added the records into the RFCs table
N/A
=> [HUDI-3580] Claim RFC number 48 for LogCompaction action RFC

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/processor/maxwell/MaxwellJsonKafkaSourcePostProcessor.java
…BINE_FIELD_TYPE_PROP
*(or)*
(or)
*(example:)*
=> [MINOR] Fix typo in MaxwellJsonKafkaSourcePostProcessor.Config#PRECOMBINE_FIELD_TYPE_PROP

hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java, hudi-examples/hudi-examples-spark/src/main/scala/org/apache/hudi/examples/spark/HoodieDataSourceExample.scala, hudi-examples/hudi-examples-spark/src/main/scala/org/apache/hudi/examples/spark/HoodieMorCompactionJob.scala, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/QuickstartUtils.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestQuickstartUtils.java
=> [MINOR] fix QuickstartUtils move

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallCommandParser.scala
=> [MINOR] fix call command parser use spark3.2

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HMSDDLExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveQueryDDLExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/HivePartitionUtil.java
=> [HUDI-2520] Fix drop partition issue when sync to hive

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
=> [HUDI-2520] Fix CTAS statment issue when sync to hive

website/src/pages/roadmap.md
=> [DOCS] Update roadmap page

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
=> [minor] Follow 3178, fix the flink metadata table compaction

hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
I finally tested this on a real aws env, and found out it still got issues which are fixed here. Please apologies for issues @nsivabalan
related to:
#4967 
#4904
=> [HUDI-3736] Fix null pointer when key not specified

README.md, packaging/hudi-utilities-slim-bundle/README.md
As above, this PR moves the hudi-utilities-slim-bundle docs to the module.
=> [MINOR][DOCS] Update hudi-utilities-slim-bundle docs

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AwsGlueCatalogSyncTool.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveSyncMode.java
=> [HUDI-3771] flink supports sync table information to aws glue

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR improves docs and logs of HoodieMetadataTableValidator to make the log readable and searcheable.
=> [HUDI-3784] Improve docs and logs of HoodieMetadataTableValidator

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java, hudi-cli/src/test/resources/table-config.properties, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-common/src/main/java/org/apache/hudi/exception/HoodieIncompatibleSchemaException.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
….write.drop.partition.columns
*(or)*
(or)
*(example:)*
=> [HUDI-3748] write and select hudi table when enable hoodie.datasource.write.drop.partition.columns

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
Fixed stack overflows in Spark MOR Record Iterators: instead of relying on recursion, we leverage `@tailrec` to unfold those into loops.
- Fixed stack overflows in Spark MOR Record Iterators
=> [HUDI-3723] Fixed stack overflows in Spark MOR Record Iterators

hudi-examples/hudi-examples-flink/pom.xml
=> [MINOR] Fixing build failure when using flink-1.13

website/contribute/developer-setup.md
=> [MINOR] doc: fix error link to community tab

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
=> [MINOR] Fix typos in the comments of HoodieMergeHandle

website/docs/procedures.md, website/docs/quick-start-guide.md, website/sidebars.js
Adding doc for procedures, including how to use and some details about specific procedures.
- Add ``website/docs/procedures.md``
- Add entrance for procedures in the sidebar
*(or)*
(or)
*(example:)*
=> Adding doc for procedures

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
*Minor optimization, moved a piece of code from executor to driver.*
- *Minor optimization, moved a piece of code from executor to driver.*
=> [HUDI-3838] Moved the getPartitionColumns logic to driver.

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
=> [HUDI-3868] Disable the sort input for flink streaming append mode

hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java, hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java, hudi-examples/hudi-examples-flink/src/test/java/org/apache/hudi/examples/quickstart/TestQuickstartData.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
=> [minor] Rework 3454, inline the partition path logic into the builder

hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
=> [MINOR] Code cleanup in test utils

hudi-common/src/main/java/org/apache/hudi/common/util/ObjectSizeCalculator.java
=> Revert "[HUDI-3652] Make ObjectSizeCalculator threadlocal to reduce memory footprint"

hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java
=> [HUDI-3835] Add UT for delete in java client

hudi-client/hudi-client-common/src/test/resources/log4j-surefire.properties, hudi-client/hudi-flink-client/src/main/resources/log4j-surefire.properties, hudi-client/hudi-flink-client/src/test/resources/log4j-surefire.properties, hudi-client/hudi-java-client/src/test/resources/log4j-surefire.properties, hudi-client/hudi-spark-client/src/test/resources/log4j-surefire.properties, hudi-common/src/test/resources/log4j-surefire.properties, hudi-examples/hudi-examples-flink/src/test/resources/log4j-surefire.properties, hudi-examples/hudi-examples-spark/src/test/resources/log4j-surefire.properties, hudi-flink-datasource/hudi-flink/src/test/resources/log4j-surefire.properties, hudi-hadoop-mr/src/test/resources/log4j-surefire.properties, hudi-integ-test/src/test/resources/log4j-surefire.properties, hudi-kafka-connect/src/test/resources/log4j-surefire.properties, hudi-spark-datasource/hudi-spark/src/test/resources/log4j-surefire.properties, hudi-spark-datasource/hudi-spark2/src/test/resources/log4j-surefire.properties, hudi-spark-datasource/hudi-spark3/src/test/resources/log4j-surefire.properties, hudi-sync/hudi-datahub-sync/src/test/resources/log4j-surefire.properties, hudi-sync/hudi-dla-sync/src/test/resources/log4j-surefire.properties, hudi-sync/hudi-hive-sync/src/test/resources/log4j-surefire.properties, hudi-sync/hudi-sync-common/src/test/resources/log4j-surefire.properties, hudi-timeline-service/src/test/resources/log4j-surefire.properties, hudi-utilities/src/test/resources/log4j-surefire.properties
=> [MINOR] Fix typos in log4j-surefire.properties

website/src/pages/talks-articles.md
updated the external articles for hudi docs
=> [MINOR] - updated external article list on Hudi docs 

website/docs/metadata.md
This PR updates metadata table docs with more detailed configurations and deployment considerations based on 0.11.0 release.
- Revised `metadata.md`
The website and the page can be built and visualized properly.
=> [HUDI-3779] Update metadata table docs

website/versioned_docs/version-0.10.1/compaction.md
=> [doc] fix typo for compaction

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
Fixing files partitioning sequence for `BaseFileOnlyRelation` to make sure we efficiently bucket small files. This brings Hudi tables on par w/ raw Parquet tables.
- Make sure we reverse sort the files before bucketing
=> [HUDI-3895] Fixing files partitioning sequence for `BaseFileOnlyRelation`

website/docs/clustering.md, website/docs/concurrency_control.md, website/docs/deployment.md, website/docs/faq.md, website/docs/flink-quick-start-guide.md, website/docs/flink_configuration.md, website/docs/hoodie_cleaner.md, website/docs/hoodie_deltastreamer.md, website/docs/key_generation.md, website/docs/metrics.md, website/docs/performance.md, website/docs/query_engine_setup.md, website/docs/querying_data.md, website/docs/quick-start-guide.md, website/docs/use_cases.md, website/docs/write_operations.md, website/docs/writing_data.md
update broken links across the website
*(or)*
(or)
*(example:)*
=> [DOCS] update broken links

packaging/hudi-gcp-bundle/pom.xml
=> [HUDI-3894] Fix gcp bundle to include HBase dependencies and shading

rfc/README.md
=> [HUDI-3904] Claim RFC number for Improve timeline server

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java
Retry count in lockmanager should be incremented even when it attempts to acquire lock but fails.
*(or)*
(or)
*(example:)*
=> [HUDI-3940] Fix retry count increment in lock manager

website/docs/syncing_aws_glue_data_catalog.md, website/docs/syncing_datahub.md, website/docs/syncing_metastore.md, website/sidebars.js
=> [HUDI-3927][DOCS] Add datahub and glue sync on website

rfc/README.md
=> [HUDI-3478] Claim RFC 51 For CDC

website/docs/key_generation.md
=> [MINOR] Fix typo in key_generation.md

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableRenameCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
for pattern matching
*(or)*
(or)
*(example:)*
=> [MINOR] update alter rename command class type for pattern matching

rfc/README.md
…ormance
*(or)*
(or)
*(example:)*
=> [HUDI-3907]Claim RFC 52 for Introduce Secondary Index to Improve HUDI Query Performance

website/docs/gcp_bigquery.md, website/sidebars.js
=> [HUDI-3927][DOCS] Add bigquery integration docs

website/docs/quick-start-guide.md, website/docs/schema_evolution.md
=> [HUDI-3925][DOCS] Consolidate alter table examples

website/docs/quick-start-guide.md
=> [HUDI-3929][DOCS] add spark sql time travel example

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMemoryConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
Some Incorrect description fixes for 0.10.1 docs
For example, the default value of METADATA_COMPACTION_DELTA_COMMITS is 10, which is described as 24.
=> [HUDI-3943] Some description fixes for 0.10.1 docs

website/docs/compaction.md, website/learn/faq.md
This pull request add a FAQ entry
*(or)*
(or)
*(example:)*
=> [DOCS] Add faq for async compaction options

website/docs/cli.md, website/docs/disaster_recovery.md, website/docs/faq.md, website/docs/hoodie_deltastreamer.md, website/docs/writing_data.md, website/learn/faq.md
Adding docs for various features for 0.11. 
- Savepoint restore to Cli 
- Pulsar commit callback
- Hive schema provider. 
*(or)*
(or)
*(example:)*
=> [HUDI-3928][HUDI-3932] Adding docs for 0.11 release (savepoint restore to CLI, pulsar commit callback, hive schema provider)

website/docs/deployment.md, website/docs/docker_demo.md, website/docs/hoodie_deltastreamer.md, website/docs/quick-start-guide.md, website/docs/syncing_metastore.md
This PR updates docs around Spark, utilities, and utilities-slim bundles.
The website can be built and run locally.
=> [HUDI-3680][HUDI-3926] Update docs for Spark, utilities, and utilities-slim bundles

hudi-utils/README.md, hudi-utils/pom.xml, website/docs/configurations.md
=> [HUDI-3997] Update configs for 0.11.0

website/releases/release-0.11.0.md
add encryption highlight in the release notes.
=> [HUDI-3997] Update 0.11.0 release notes

website/docs/async_meta_indexing.md, website/releases/release-0.11.0.md, website/sidebars.js
=> [HUDI-3931][DOCS] Guide to setup async metadata indexing

website/docs/flink-quick-start-guide.md, website/docs/gcp_bigquery.md, website/docs/quick-start-guide.md, website/docs/table_management.md, website/releases/release-0.11.0.md, website/versioned_docs/version-0.11.0/flink-quick-start-guide.md, website/versioned_docs/version-0.11.0/gcp_bigquery.md, website/versioned_docs/version-0.11.0/quick-start-guide.md, website/versioned_docs/version-0.11.0/table_management.md
Edits on quick start guides (backfilled 0.11.0 version) and 0.11 release notes.
=> [HUDI-3997] update 0.11.0 docs

rfc/README.md
Update status for some of the RFCs which landed or near landing.
*(or)*
(or)
*(example:)*
=> [MINOR] Update RFC status

website/src/css/custom.css
The navbar in the main page was giving a weird experience and wasnt responsive when shrinking the the dimensions of the app.
*(or)*
(or)
*(example:)*
- *Added …
=> [MINOR] Make main navbar responsive

hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark3Analysis.scala
In spark-3.2 (compiling with mvn -P3.2), test of TestTruncateTable("Test Truncate single-partition table' partitions") fails. The reason is HoodieSpark3Analysis seems forgot to transform TruncatePartition to TruncateHoodieTableCommand.
- Add a branch to transform TruncatePartition to TruncateHoodieTableCommand in HoodieSpark3Analysis;
- Replace some checking of "isInstance" with case-class pattern matching;
This pull request is already covered by existing tests, such as *TestTruncateTable*.
=> [HUDI-4042] Support truncate-partition for Spark-3.2

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java
=> [MINOR] fixing flaky parquet tests in deltastreamer tests

hudi-common/src/main/java/org/apache/hudi/common/util/RateLimiter.java
RateLimiter recursively call itself to do rate control. In some occasion, it may lead stackOverFlow.
https://issues.apache.org/jira/browse/HUDI-4055
Use loop replace recursive call in rate limiter to avoid stackOverFlow in some special case
This pull request is already covered by existing tests, such as TestRatelimiter.
=> [HUDI-4055]refactor ratelimiter to avoid stack overflow

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
=> [MINOR] Fixing close for HoodieCatalog's test

website/docs/compaction.md, website/docs/hoodie_deltastreamer.md, website/versioned_docs/version-0.11.0/compaction.md, website/versioned_docs/version-0.11.0/hoodie_deltastreamer.md
=> [HUDI-4063] Update the site doc for flink since release 0.11

hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java
=> [HUDI-4099][MINOR]fix hive sync no partition table error

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
=> [HUDI-4110] Clean the marker files for flink compaction.

website/blog/2021-12-29-hudi-zorder-and-hilbert-space-filling-curves.md, website/src/css/custom.css, website/src/theme/BlogPostItem/index.js, website/src/theme/BlogPostItem/styles.module.css
Fixed the blog page header and made the navbar responsive after addition of blogs . 
*(or)*
(or)
*(example:)*
=> Fixed styling and responsiveness

website/blog/2022-01-25-Cost-Efficiency-Scale-in-Big-Data-File-Format.mdx, website/blog/2022-02-02-Onehouse-Commitment-to-Openness.mdx, website/blog/2022-02-03-Onehouse-brings-a-fully-managed-lakehouse-to-Apache-Hudi.mdx, website/blog/2022-02-17-Fresher-Data-Lake-on-AWS-S3.mdx, website/blog/2022-03-01-Create-a-low-latency-source-to-data-lake-pipeline-using-Amazon-MSK-Connect-Apache-Flink-and-Apache-Hudi.mdx, website/blog/2022-03-09-Build-a-serverless-pipeline-to-analyze-streaming-data-using-AWS-Glue-Apache-Hudi-and-Amazon-S3.mdx, website/blog/2022-04-04-Key-Learnings-on-Using-Apache-HUDI-in-building-Lakehouse-Architecture-at-Halodoc.mdx, website/blog/2022-05-17-Introducing-Multi-Modal-Index-for-the-Lakehouse-in-Apache-Hudi.mdx
=> [DOCS] Add multimodel index blog and images to other blogs

website/src/css/custom.css
Fixed alignment of blogs and their respective blog pages
Earlier it was like this - 
now - 
responsiveness - 
normal dimensions - 
responsiveness - 
*(or)*
(or)
*(example:)*
- …
=> Fixed alignment and arrangement of blogs styling

pom.xml
Remove gson as it is not used.
=> [MINOR] remove unused gson test dependency

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/WriteProfile.java
…ystemView#refresh
*(or)*
(or)
*(example:)*
=> [HUDI-4129] Initializes a new fs view for WriteProfile#reload

rfc/README.md
=> [HUDI-4142] Claim RFC-54 for new table APIs

website/releases/release-0.11.0.md, website/releases/release-0.9.0.md
=> [MINOR][DOCS] Minor fix on 0.9.0 and 0.11.0 release notes

hudi-spark-datasource/hudi-spark2/pom.xml
=> [HUDI-4135] Remove netty and netty-all

website/blog/2022-04-04-Key-Learnings-on-Using-Apache-HUDI-in-building-Lakehouse-Architecture-at-Halodoc.mdx, website/blog/2022-05-17-Introducing-Multi-Modal-Index-for-the-Lakehouse-in-Apache-Hudi.mdx, website/src/css/custom.css, website/src/theme/BlogPostItem/index.js, website/src/theme/BlogPostItem/styles.module.css
Added tags and authors list in blogs page with responsiveness 
*(or)*
(or)
*(example:)* …
=> [DOCS] [MINOR] Added tags and authors list

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
=> [HUDI-4162] Fix metasync constant mappings

website/blog/2022-04-04-Key-Learnings-on-Using-Apache-HUDI-in-building-Lakehouse-Architecture-at-Halodoc.mdx, website/blog/2022-05-17-Introducing-Multi-Modal-Index-for-the-Lakehouse-in-Apache-Hudi.mdx, website/src/css/custom.css, website/src/theme/BlogPostItem/index.js, website/src/theme/BlogPostItem/styles.module.css
This reverts commit 8f8151b33934576bc5f0dfdadc62b2d717e28ad6.
*(or)*
(or)
*(example:)* …
=> Revert "[DOCS][MINOR] Added tags and authors list (#5680)"

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
=> [MINOR] Fix Hive and meta sync config for sql statement

hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
=> [HUDI-3551] Fix testStorageSchemes for oci storage

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncClusteringService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncCompactService.java
The old thread factory used anonymous classes and created the same thread name for each thread. We can use an already existing thread factory to create threads
*(or)*
(or)
*(example:)*
=> [HUDI-4086] Use CustomizedThreadFactory in async compaction and clustering

website/docs/table_management.md, website/versioned_docs/version-0.10.0/table_management.md, website/versioned_docs/version-0.10.1/table_management.md, website/versioned_docs/version-0.11.0/table_management.md, website/versioned_docs/version-0.9.0/quick-start-guide.md
This pull request is for document syntax errors to change, involving a total of 5 MD documents.
=> [MINOR] Fix incorrect full-width comma usage in the doc DDL demo

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDCustomColumnsSortPartitioner.java
fix can not change data layout when use clusteringJob with default ruler **LINEAR**
*(or)*
(or)
*(example:)*
=> [HUDI-4179] cluster with sort cloumns invalid

website/blog/2022-01-14-change-data-capture-with-debezium-and-apache-hudi.md, website/blog/2022-04-04-Key-Learnings-on-Using-Apache-HUDI-in-building-Lakehouse-Architecture-at-Halodoc.mdx, website/blog/2022-05-17-Introducing-Multi-Modal-Index-for-the-Lakehouse-in-Apache-Hudi.mdx, website/src/css/custom.css, website/src/theme/BlogPostItem/index.js, website/src/theme/BlogPostItem/styles.module.css
Showing tags when there are tags and align all blogs by their titles
*(or)*
(or)
*(example:)* …
=> [MINOR][UI] Show tags when there are tags and align all blogs by their titles

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
=> [HUDI-4188] Fix flaky ITTestDataSTreamWrite.testWriteCopyOnWrite

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
=> [MINOR] Mark AWSGlueCatalogSyncClient experimental

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkStateBackendConverter.java
=> [MINOR] FlinkStateBackendConverter add more  exception message

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
=> [HUDI-4139]improvement for flink write operator name to identify tables easily

website/docs/hoodie_deltastreamer.md, website/versioned_docs/version-0.10.0/hoodie_deltastreamer.md, website/versioned_docs/version-0.10.1/hoodie_deltastreamer.md, website/versioned_docs/version-0.11.0/hoodie_deltastreamer.md
This PR aims to improve the docs on hudi delta streamer for DFS on two things:
- The expected behavior around partitions that @yihua explained to me on [this](https://github.com/apache/hudi/issues/5485) issue.
- The necessity to inform schemas for JSON files that were not clear in the docs and I had to ask on the slack channel.
- *Modify Distributed File System (DFS) subsection under Sources section, at this moment the changes doesn't affect versioned docs*
This pull request is a trivial improvement in the docs without any test coverage.
=> Update the docs for Distributed File System (DFS) section on Hudi Delta Streamer page

website/docs/faq.md
=> [DOCS] Adding FAQ on why hudi has record key requirement

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
=> [minor] Following HUDI-4207, remote the new wrapper #init method

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
=> [HUDI-4218] Expose the real exception information when an exception occurs in the tableExists method

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
=> [HUDI-4277] supoort flink table source with computed column

doap_HUDI.rdf
Update DOAP with 0.11.1 release.
Only metadata update.
=> [MINOR] Update DOAP with 0.11.1 Release

website/releases/download.md, website/releases/older-releases.md, website/releases/release-0.10.0.md, website/releases/release-0.10.1.md, website/releases/release-0.11.0.md, website/releases/release-0.11.1.md, website/releases/release-0.7.0.md, website/releases/release-0.8.0.md, website/releases/release-0.9.0.md
As above
The website can be built and visualized properly.
=> [HUDI-4286] Add release notes for 0.11.1

website/docs/query_engine_setup.md, website/versioned_docs/version-0.10.0/query_engine_setup.md, website/versioned_docs/version-0.10.1/query_engine_setup.md, website/versioned_docs/version-0.11.0/query_engine_setup.md, website/versioned_docs/version-0.11.1/query_engine_setup.md, website/versioned_docs/version-0.9.0/query_engine_setup.md
=> [DOCS] Fix trino jar bundle in query engine setup page

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileMetadataProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileRecordsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestHoodieLogFileProcedure.scala
=> [HUDI-3509] Add call procedure for HoodieLogFileCommand

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
Reverts apache/hudi#5948  since the commit msg is not correctly
=> Revert "[HUDI-4296] fix the bug that TestHoodieSparkSqlWriter.testSchemaEvolutionForTableType is flaky"

hudi-sync/hudi-adb-sync/pom.xml
Upgrading mysql connector/J version due to security vulnerability.
[CVE-2021-3711](https://github.com/advisories/GHSA-5ww6-px42-wc85) [CVE-2020-1967](https://github.com/advisories/GHSA-jq65-29v4-4x35) [CVE-2021-3712](https://github.com/advisories/GHSA-q9wj-f4qw-6vfj) [CVE-2021-3450](https://github.com/advisories/GHSA-8hfj-xrj2-pm22) [CVE-2018-3258](https://github.com/advisories/GHSA-4vrv-ch96-6h42)
*(or)*
(or)
*(example:)*
- *Added …
=> [HUDI-5246] Bumping mysql connector version due to security vulnerability

website/blog/2021-08-23-s3-events-source.md
=> [DOCS] Fix Reliable ingestion from AWS S3 blog for configs

rfc/README.md
Claim RFC-56: Early Conflict Detection For Multi-writer
=> [HUDI-1575] Claim RFC-56: Early Conflict Detection For Multi-writer

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ExportInstantsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileMetadataProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileRecordsProcedure.scala
=> [HUDI-4344] fix use of HoodieDataBlock#getRecordIterator

website/docusaurus.config.js, website/learn/faq.md
Reverts apache/hudi#5998
Reason: recheck if all internal redirects are working fine.
=> Revert "[DOCS] Remove duplicate faq page"

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/HadoopConfigurations.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/NonThrownExecutor.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ColumnStatsIndices.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ExpressionEvaluator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FilePathUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroSchemaConverter.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroToRowDataConverters.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/DataTypeUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ExpressionUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataProjection.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ViewStorageProperties.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestHiveSyncContext.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestFileIndex.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/stats/TestColumnStatsIndices.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/stats/TestExpressionEvaluator.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestAvroSchemaConverter.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestViewStorageProperties.java
=> [HUDI-4353] Column stats data skipping for flink

website/community/syncs.md, website/i18n/cn/docusaurus-plugin-content-pages/syncs.md
=> [DOCS] Add Chinese community call page.

website/docs/faq.md, website/learn/faq.md, website/versioned_docs/version-0.11.1/faq.md
Add schema reconciliation example to faq
Add schema reconciliation example to faq
- *Manually verified the change locally.*
=> [DOCS] Add schema reconciliation example to FAQ

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDropPartitionsTool.java
This PR fixes HoodieDropPartitionsTool based on refactored meta sync and the failed Java CI on master.
- Fix the usage of old configs and APIs in `HoodieDropPartitionsTool`.
=> [HUDI-4360] Fix HoodieDropPartitionsTool based on refactored meta sync

website/docs/hoodie_deltastreamer.md
minor edit in the doc when mentions HoodieDeltaStreamer in the `hoodie_deltastreamer.md`. Using Inline code style when mentions HoodieDeltaStreamer to make the doc consistent
minor edit in the doc when mentions HoodieDeltaStreamer in the `hoodie_deltastreamer.md`. Using Inline code style when mentions HoodieDeltaStreamer to make the doc consistent
This pull request is a trivial rework
=> [DOCS] Minor edit in the doc when mentions HoodieDeltaStreamer

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java
=> [HUDI-4366] Synchronous cleaning for flink bounded source

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CopyToTableProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCopyToTableProcedure.scala
=> [HUDI-4367] Support copyToTable on call

rfc/README.md
Add slot for RFC-57
*(or)*
(or)
*(example:)*
=> [HUDI-4399][RFC-57] Claim RFC 57 for DeltaStreamer proto support

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCleanProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCleanProcedure.scala
=> [HUDI-3503]  Add call procedure for CleanCommand

website/docs/query_engine_setup.md, website/docs/querying_data.md
=> [DOCS] Update query pages for Redshift Spectrum support for Hudi

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
=> [HUDI-4427] Add a computed column IT test

rfc/rfc-55/rfc-55.md
Update RFC 55 for config changes.
=> [HUDI-4146][RFC-55] Update config changes proposal

website/versioned_docs/version-0.10.0/query_engine_setup.md, website/versioned_docs/version-0.10.0/querying_data.md, website/versioned_docs/version-0.5.2/querying_data.md, website/versioned_docs/version-0.6.0/querying_data.md, website/versioned_docs/version-0.7.0/querying_data.md, website/versioned_docs/version-0.8.0/querying_data.md, website/versioned_docs/version-0.9.0/querying_data.md
s Please enter the commit message for your changes. Lines starting
*This pull adds Redshift Spectrum info to several Hudi doc versions 0.5.2, 0.6.0, 0.7.0, 0.8.0, 0.9.0, and 0.10.0.*
- *This pull adds Redshift Spectrum info to several old Hudi doc versions.*
*This pull request is a trivial rework / code cleanup without any test coverage.*
*(or)*
(or)
*(example:)*
- *Added HoodieClientWriteTest to …
=> [DOCS] Redshift Spectrum update for old Hudi versions.

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
=> Add logger for HoodieCopyOnWriteTableInputFormat

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
Fixing broken IT on master.
See above
*(example:)*
=> [MINOR] Fixing broken IT on master

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
JIRA https://issues.apache.org/jira/browse/HUDI-4436
*(or)*
(or)
*(example:)*
- *Manually verified the change by running a …
=> [HUDI-4436] Invalidate cached table in Spark after write

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/payload/SqlTypedRecord.scala
fix data quality in concurrent scene when use merge into
every executor thread use it own HoodieAvroDeserializer cache
*(or)*
(or)
*(example:)*
=> [HUDI-4348] fix merge into sql data quality in concurrent scene

hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestAWSDmsAvroPayload.java, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/payload/AWSDmsAvroPayload.java
=> [HUDI-4490] Make AWSDmsAvroPayload class backwards compatible

hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
This PR fixes the tests of `HoodieWrapperFileSystem.convertPathWithScheme`.
- Fixes tests in `TestStorageSchemes`
This change adds tests in `TestStorageSchemes`.
=> [MINOR] Fix convertPathWithScheme tests

hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestConfigUtils.java
=> [MINOR] Add license header

hudi-flink-datasource/hudi-flink/pom.xml
For now flink bundle include test resource in fat jar , It was danger
*(or)*
(or)
*(example:)*
=> [HUDI-4425] Remove test resources in hudi-flink module

website/docs/flink-quick-start-guide.md, website/docs/hoodie_deltastreamer.md, website/docs/querying_data.md
=> [HUDI-4535] Add document for flink data skipping

website/docs/concurrency_control.md, website/docs/configurations.md, website/versioned_docs/version-0.10.0/concurrency_control.md, website/versioned_docs/version-0.10.1/concurrency_control.md, website/versioned_docs/version-0.11.0/concurrency_control.md, website/versioned_docs/version-0.11.1/concurrency_control.md
Update documentation for DynamoDB lock provider to include IAM policy and additional dependencies
Update to DynamoDB lock provider documentation to mention all configuration properties, additional required dependencies and AWS IAM policy.
- Update latest and versioned docs for 0.10.0+ 
- update dynamodb documentation for clarity
=> [DOCS] Update aws dynamodb lock provider docs 

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
=> [HUDI-4470] Remove spark dataPrefetch disabled prop in DefaultSource

hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark3Analysis.scala
=> [HUDI-4546] Optimize catalog cast logic in HoodieSpark3Analysis

.github/PULL_REQUEST_TEMPLATE.md
Simplify and improve PR description template to focus on impact analysis. 
Guide contributors to explain PR changes more clearly and help reviewers evaluate PRs more effectively.
=> [MINOR] Update PR description template

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
=> [HUDI-4447] fix the sync problem when performing delete table operation

website/src/pages/talks.md
=> [DOCS] Add Presto Tech Talk June 2022 to talks page

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
=> [MINOR] fix potential NPE in spark writer

website/docs/cli.md
=> [HUDI-4579] Add docs on upgrading and downgrading table through CLI

website/docs/query_engine_setup.md
This PR updates the documentation for Hudi-Presto integration to its current state.
None
=> [HUDI-4565][HUDI-4307][HUDI-3013] Updated docs for presto-hudi integration

hudi-utils/README.md, hudi-utils/generate_config.sh, hudi-utils/pom.xml, website/docs/basic_configurations.md, website/docs/configurations.md, website/docs/writing_data.md
This is a docs update PR to reflect the current master configurations.
None
=> [HUDI-4566] Document configuration updates

website/docs/schema_evolution.md, website/versioned_docs/version-0.11.0/schema_evolution.md, website/versioned_docs/version-0.11.1/schema_evolution.md
=> [MINOR][DOCS] add tip to schema evolution

website/docs/performance.md
Add optimal write configs for bulk insert under the performance guide. Also, point to the benchmarking blog for tpc-ds benchmark.
None
None
=> [HUDI-4583][DOCS] Optimal write configs for bulk insert

doap_HUDI.rdf
=> [MINOR] Update DOAP with 0.12.0 Release

pom.xml
=> [HUDI-4632] Remove the force active property for flink1.14 profile

hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/BootstrapCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/ClusteringCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/ExportCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/MarkersCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkEnvCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/TempViewCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/UtilsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestArchivedCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCompactionCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestSavepointsCommand.java
As above for code style changes only.  There is no logic change.
Only code reformatting.
=> [MINOR] Improve code style of CLI Command classes

rfc/README.md
As above.
Only RFC list update.
=> [HUDI-3625] Claim RFC-60 for Federated Storage Layer

website/docusaurus.config.js, website/src/pages/tech-specs.md
- Removing the draft status
- Added table/details around table versioning/compatibility
- 1 missing point on reader expectations.
- Explain table configs and the hoodie.properties file!
=> [DOCS] More improvements to spec

pom.xml
This reverts commit 9055b2f65d670c2b153c7492ca323188b84c3362 (#6415 )
=> Revert "[HUDI-4632] Remove the force active property for flink1.14 profile

hudi-examples/hudi-examples-flink/pom.xml, hudi-flink-datasource/hudi-flink/pom.xml, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java, pom.xml
=> [HUDI-4644] Change default flink profile to 1.15.x

website/src/pages/powered-by.md
Add NerdWallet blog reference to What is New on the Hudi website.
Updated the website/src/pages/powered-by.md file.  No other changes.
=> [DOCS] Add NerdWallet reference to What is New on the Hudi website.

website/releases/release-0.12.0.md
=> [MINOR] Add filesystem based lock provider to release note

rfc/README.md
=> [HUDI-4678] Claim RFC-61 for Snapshot view management

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowInvalidParquetProcedure.scala
=> [HUDI-4687] add show_invalid_parquet procedure

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
=> [HUDI-4713] Fix flaky ITTestHoodieDataSource#testAppendWrite

website/docs/flink-quick-start-guide.md, website/docs/table_management.md, website/versioned_docs/version-0.12.0/flink-quick-start-guide.md, website/versioned_docs/version-0.12.0/table_management.md
=> [HUDI-4723] Add document about Hoodie Catalog

website/docs/query_engine_setup.md
…ent doc.
[DOCS] Update Hudi support versions for Redshift Spectrum in the current doc.
One doc file changed: query_engine_setup.md.
None
=> [DOCS] Update Hudi support versions for Redshift Spectrum in the current doc.

website/docs/quick-start-guide.md, website/versioned_docs/version-0.10.0/quick-start-guide.md, website/versioned_docs/version-0.10.1/quick-start-guide.md, website/versioned_docs/version-0.11.0/quick-start-guide.md, website/versioned_docs/version-0.11.1/quick-start-guide.md, website/versioned_docs/version-0.12.0/quick-start-guide.md
#6405  #6514 , user will not use extend config when read current doc
=> [DOCS][MINOR] Improve spark quick start doc

website/docs/compaction.md
=> [DOCS] Fix typo in  compaction.md

website/docs/hoodie_cleaner.md, website/versioned_docs/version-0.11.1/hoodie_cleaner.md, website/versioned_docs/version-0.12.0/hoodie_cleaner.md
=> [HUDI-4339] Add example configuration for HoodieCleaner in docs

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Fixing flaky deltastreamer test testCleanerDeleteReplacedDataWithArchive
none. 
=> [HUDI-4327] Fixing flaky deltastreamer test (testCleanerDeleteReplacedDataWithArchive)

website/docs/migration_guide.md, website/versioned_docs/version-0.11.1/migration_guide.md, website/versioned_docs/version-0.12.0/migration_guide.md
The doc about bootstrap is out of date, I add some updates, please review.
*(or)*
(or)
*(example:)*
=> [DOCS] Update migration_guide.md

azure-pipelines.yml
Add a CI task for each UT/FT task to print top 100 long-running testcases.
=> [HUDI-4694] Print testcase running time for CI jobs

hudi-cli/src/main/scala/org/apache/hudi/cli/DedupeSparkJob.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/DedupeSparkJob.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ValidateHoodieSyncProcedure.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
The single variable via ${} expression should be removed redundant {}.
=> [MINOR] Fix remove redundant brace

hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
Separate  log word for CommitUitls class
no
=> [HUDI-4618] Separate log word for CommitUitls class

website/docs/query_engine_setup.md, website/versioned_docs/version-0.10.0/query_engine_setup.md, website/versioned_docs/version-0.10.1/query_engine_setup.md, website/versioned_docs/version-0.10.1/querying_data.md, website/versioned_docs/version-0.11.0/query_engine_setup.md, website/versioned_docs/version-0.11.0/querying_data.md, website/versioned_docs/version-0.11.1/query_engine_setup.md, website/versioned_docs/version-0.11.1/querying_data.md, website/versioned_docs/version-0.12.0/query_engine_setup.md, website/versioned_docs/version-0.12.0/querying_data.md, website/versioned_docs/version-0.5.2/querying_data.md, website/versioned_docs/version-0.6.0/querying_data.md, website/versioned_docs/version-0.7.0/querying_data.md, website/versioned_docs/version-0.8.0/querying_data.md, website/versioned_docs/version-0.9.0/querying_data.md
=> [DOCS] Fix Redshift spectrum Hudi version details

website/docs/metrics.md
Adds list of monitoring metrics configured in Hudi.
No impact on code
=> [HUDI-4610] Document list of metrics emitted by Hudi

website/docs/configurations.md
in master branch, the default value of 'read.tasks & write.tasks' in flink option is updated to noDefaultValue, however, the description in website doc hasn't been updated;
=> [DOCS] Asf site update flink option 'read.tasks & write.tasks' description

README.md
This PR fixes the Slack invite link in README.md.
=> [DOCS] Fix Slack invite link in README.md

website/docs/faq.md
Adding FAQs for some popularly asked questions.
=> [DOCS] Add more FAQs

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
*This pull request is a minor fix for a wrong calling in HoodieFlinkWriteClient*
=> [MINOR] Insert should call validateInsertSchema in HoodieFlinkWriteClient

website/docs/cloud.md
Added a note regrading lifecyle policy under cloud documentation. See issue #5281 
None. Documentation change.
None
=> [HUDI-3893][DOCS] Add a note about lifecycle policies

website/docs/concepts.md, website/versioned_docs/version-0.10.0/concepts.md, website/versioned_docs/version-0.10.1/concepts.md, website/versioned_docs/version-0.11.0/concepts.md, website/versioned_docs/version-0.11.1/concepts.md, website/versioned_docs/version-0.12.0/concepts.md
In merge on read tables delta log file holds incoming updates in row based file
*(or)*
(or)
*(example:)*
- *Manually …
=> [MINOR] Update concepts.md

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
Fix unnecessary time.Sleep where it should not be happening, otherwise it introduces unnecessary 10 seconds delay.
moved time sleep into if condition in case of a failure.
=> [HUDI-4837] Stop sleeping where it is not necessary after the success

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
As above, to avoid confusion on the Spark stages.
=> [MINOR] Fix the Spark job status description for metadata-only bootstrap operation

website/src/css/custom.css, website/src/theme/BlogLayout/index.js, website/src/theme/BlogPostItem/index.js, website/src/theme/BlogPostItem/styles.module.css
- fixed various tags style issue
=> [DOCS] fix site tags various style issues

website/src/css/custom.css
=> [DOCS] fix: blog image landing page

website/docs/file_sizing.md, website/versioned_docs/version-0.10.0/file_sizing.md, website/versioned_docs/version-0.10.1/file_sizing.md, website/versioned_docs/version-0.11.0/file_sizing.md, website/versioned_docs/version-0.11.1/file_sizing.md, website/versioned_docs/version-0.12.0/file_sizing.md
=> [DOCS] Fix typo in File Sizing docs

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bucket/TestHoodieSimpleBucketIndex.java
Make org.apache.hudi.index.bucket.TestHoodieSimpleBucketIndex#testTagLocation work correct
Correct test case.
None
=> [HUDI-4877] Fix org.apache.hudi.index.bucket.TestHoodieSimpleBucketIndex#testTagLocation not work correct issue

hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
=> [MINOR] fix indent to make build pass

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
Improve API and refactor code about metasync for serde properties. Follow up fix for https://github.com/apache/hudi/pull/5920
=> [HUDI-4326] Fix hive sync serde properties

.gitignore
=> [MINOR] Add .mvn directory to gitignore

hudi-flink-datasource/hudi-flink/pom.xml, pom.xml
Add avro.version to Flink profiles to avoid avro version conflict between Flink and Spark
This is a follow-up PR of #6628 
=> [HUDI-4901] Add avro.version to Flink profiles

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HiveSyncProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
=> [HUDI-4559] Support hiveSync command based on Call Produce Command

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
Fixing flaky test by drastically reducing concurrency level (to avoid CI flakiness)
**Risk level: None
=> [MINOR] Fixing flaky test by drastically reducing concurrency level (to avoid CI flakiness)

website/contribute/developer-setup.md
=> [DOCS] Add Documentation for running unit tests/debugger with spark3

website/docs/docker_demo.md, website/docs/faq.md, website/versioned_docs/version-0.12.0/faq.md
- Fixing faq for diff indexing schemes with hudi. 
- Fixing hive sync command in docker demo
=> [HUDI-4884] Fixing faq for indexes with hudi and fixing docker demo for hive sync

website/docs/s3_hoodie.md, website/versioned_docs/version-0.12.0/s3_hoodie.md
updated s3n to s3a because s3n has been deprecated
=> [DOCS] Update s3_hoodie.md

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java
=> [MINOR] Simple logging fix in LockManager

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkEnvCommand.java
Fix bugs about when trying to show the non -existing key from env, NullPointException occurs.
=> [HUDI-4918] Fix bugs about when trying to show the non -existing key from env, NullPointException occurs.

README.md, website/blog/2022-08-24-Implementation-of-SCD-2-with-Apache-Hudi-and-Spark.mdx, website/blog/2022-09-20-Data-Lake-Lakehouse-Guide-Powered-by-Data-Lake-Table-Formats-Delta-Lake-Iceberg-Hudi.mdx
=> [DOCS] Add new blogs

website/blog/2021-02-13-hudi-key-generators.md, website/blog/2021-08-18-virtual-keys.md, website/docs/key_generation.md, website/versioned_docs/version-0.10.0/key_generation.md, website/versioned_docs/version-0.10.1/key_generation.md, website/versioned_docs/version-0.11.0/key_generation.md, website/versioned_docs/version-0.11.1/key_generation.md, website/versioned_docs/version-0.12.0/key_generation.md, website/versioned_docs/version-0.6.0/writing_data.md, website/versioned_docs/version-0.7.0/writing_data.md, website/versioned_docs/version-0.8.0/writing_data.md
=> [DOCS] Fix typo in NonpartitionedKeyGenerator related docs

website/src/pages/roadmap.md
As above.
The website can be built and visualized.
N/A.
=> [DOCS] Add 1.0.0 release entry to Roadmap

hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
This reverts commit 79b3e2b899cc303490c22610fda0e5ac2013cf02.
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setup#we …
=> Revert "[HUDI-4915] improve avro serializer/deserializer (#6788)"

scripts/release/deploy_staging_jars.sh, scripts/release/validate_staged_bundles.sh
Fix deploy script for flink bundle 1.15
=> [MINOR] Fix deploy script for flink 1.15

website/docs/quick-start-guide.md
Remove validation code from spark scala python examples.
=> [MINOR][DOCS] remove validation code from quickstart examples

.asf.yaml
Only allow squash and merge. Disable merge and rebase
NA
=> [MINOR] Update GitHub setting for merge button

website/docs/key_generation.md, website/versioned_docs/version-0.10.0/key_generation.md, website/versioned_docs/version-0.10.1/key_generation.md, website/versioned_docs/version-0.11.0/key_generation.md, website/versioned_docs/version-0.11.1/key_generation.md, website/versioned_docs/version-0.12.0/key_generation.md
Update docs related to GlobalDeleteKeyGenerator in the website
=> [HUDI-4816] [DOCS] Update docs for GlobalDeleteKeyGenerator

website/docs/hoodie_cleaner.md, website/versioned_docs/version-0.12.0/hoodie_cleaner.md
The parameter **--hoodieConfigs** in "cleans run" is a String array, the value should be separated with " ".
Risk level: none
=> [HUDI-4996] Update hoodie_cleaner.md

docker/setup_demo.sh
Removing unnecessary verbosity in docker demo set up.
Will fix noisy logs
=> [MINOR] Fixing verbosity of docker set up

doap_HUDI.rdf
_Update doap_HUDI.rdf._
_Add release 0.12.1._
_low._
=> [MINOR] Update DOAP with 0.12.1 Release

website/docs/query_engine_setup.md
Update Trino query docs with information about the new connector.
None
None
=> [HUDI-2695] Update Trino section with new connector

website/releases/release-0.12.0.md
Updating 0.12.0 docs to caution about the regression
Might help users to be cautious when using row writer flow with 0.12.0 
low -> medium 
This patch is about adding docs about the regression to our 0.12.0 release page.
=> [HUDI-5052][DOCS] Updating 0.12.0 docs for known regression

.asf.yaml
- require at least 1 approving review
Ref: https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection
- Stricter rules for landing PRs.
none
NA
=> [MINOR] Update GitHub setting for branch protection

hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java, hudi-timeline-service/pom.xml, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerCreationFuture.java, pom.xml
Upgrade versions for Jetty, Javalin and make appropriate API changes for these libs
Low-medium
low
API usage update only.
N/A
=> [HUDI-4960] Upgrade jetty version for timeline server

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
=> [MINOR] fix cdc flake ut

website/docs/cli.md, website/docs/flink-quick-start-guide.md, website/docs/metadata_indexing.md, website/docs/query_engine_setup.md, website/docs/quick-start-guide.md, website/versioned_docs/version-0.12.1/cli.md, website/versioned_docs/version-0.12.1/flink-quick-start-guide.md, website/versioned_docs/version-0.12.1/metadata_indexing.md, website/versioned_docs/version-0.12.1/query_engine_setup.md, website/versioned_docs/version-0.12.1/quick-start-guide.md
_Update version 0.12.0 to 0.12.1 in some files._
_Users can see the correct version number on the website._
_low._
=> [MINOR] Fixing 0.12.1 docs

website/versioned_docs/version-0.12.0/quick-start-guide.md, website/versioned_docs/version-0.12.1/quick-start-guide.md
Replicated the work done in https://github.com/apache/hudi/pull/6879 and removed the validations from the versioned docs.
Now will work for new users to the site.
none
This is a documentation update
=> [MINOR][DOCS] Remove Validations from the Versioned Docs

azure-pipelines.yml
relevant issue https://github.com/microsoft/azure-pipelines-tasks/issues/16520
=> [MINOR] use default maven version since it already fix the warnings recently in Azure CI

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
Fix doc of org.apache.hudi.sink.meta.CkpMetadata#bootstrap
none
none
none
=> [MINOR] Fix doc of org.apache.hudi.sink.meta.CkpMetadata#bootstrap

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
Fix #7095
update the default payload, the payload class have rename to other package, the old one can not work.
No
No
none
no
no …
=> [MINOR] Fix OverwriteWithLatestAvroPayload full class name

website/docs/quick-start-guide.md
Updated and fix a few things for the Python side: 
1. Updated time travel query to have the right format 
2. Fixed copy issue for hard and soft deletes
3. Minor stylistic changes
Doc changes/ improved user experience for python 
=> [DOCS] Edit quickstart

website/docs/faq.md, website/versioned_docs/version-0.12.1/faq.md
This helps users solve HUDI-5074 using the website FAQ if they don't see the warning in the logs.
Helps users debug an issue.
none
This is the documentation update for PR 7077
=> [HUDI-5074] Website Changes to help users debug when their table has capital letters

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Metadata table initialization was using non serializable Path with engineContext.map(). Fixing that in this patch. 
Metadata table initialization will succeed w/o any issues. 
low
N/A
=> [HUDI-5076] Fixing non serializable path used in engineContext with metadata table intialization

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
related to [issue-7100](https://github.com/apache/hudi/issues/7100)
- Delete duplicate configuration items PAYLOAD_CLASS_NAME
The user is affected when using write.payload.class
low
=> [HUDI-5126] Delete duplicate configuration items PAYLOAD_CLASS_NAME

website/contribute/developer-setup.md
Adding useful maven commands to our website. 
Improves productivity for devs.
low.
=> [DOCS][MINOR] Adding useful maven commands to website

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
The pre check is redundant now.
No impact
none
=> [HUDI-5187] Remove the preCondition check of BucketAssigner assign state

rfc/rfc-46/rfc-46.md
Update rfc46 doc.
Affect nothing.
None.
Update rfc46 doc.
=> [MINOR] update rfc46 doc

hudi-examples/hudi-examples-spark/src/test/python/README.md
Remove line that is not needed
I think this line is wrong and could potentially be misleading.
none
N/A
=> [HUDI-5184] Remove unnecessary line from example

azure-pipelines.yml
- job 1: common (UT/FT) + flink-datasource (UT/FT) + spark-client (UT)
- job 2: spark-client (FT)
- job 3: spark-datasource (UT/FT)
- job 4: everything else except hudi-examples (covered in GH actions)
- job 5: IT
NA
none
NA
=> [MINOR] Balance CI jobs

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandle.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
Supports partial failover for flink write pipeline.
No impact.
none
=> [HUDI-5223] Partial failover for flink

hudi-timeline-service/pom.xml, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java, packaging/hudi-timeline-server-bundle/pom.xml, pom.xml
Minor jetty and javalin upgrade
Minimal API changes
no doc update needed
done
=> [HUDI-5227] Bump Javalin to 4.6.7 and Jetty to 9.4.48

hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestSchemaEvolutionClient.java
Fix `TestSchemaEvolutionClient` compilation
NA
none
NA
=> [MINOR] Fix `TestSchemaEvolutionClient` compilation

website/blog/2021-10-14-How-Amazon-Transportation-Service-enabled-near-real-time-event-analytics-at-petabyte-scale-using-AWS-Glue-with-Apache-Hudi.mdx, website/blog/2022-10-17-Get-started-with-Apache-Hudi-using-AWS.mdx, website/blog/2022-11-10-How-Hudl-built-a-cost-optimized-AWS-Glue-pipeline-with-Apache-Hudi-datasets.mdx, website/src/pages/talks.md
=> [DOCS] Add more blogs and talks

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
- add `--parallelism` to allow overwrite parallelism
- parallelize copying commit files
Fix https://github.com/apache/hudi/issues/6970
Only affect utilities SnapshotExporter for Hudi output format mode
low
NA
=> [HUDI-712] Improve exporter file listing and copy perf

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
This tests were accidentally disabled, when landing #6358
N/A
No risk
N/A
=> [MINOR] Re-enable Cleaner tests

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
Fix IncrementalInputSplits compilation failure on the latest master branch
Fix compilation failure
Low
None
=> [MINOR] Fix IncrementalInputSplits compilation failure

hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
Remove some useless log references.
No impact.
none
=> [MINOR] Remove the log refrence and imports in HoodieHFileDataBlock

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/CastMap.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/ParquetSplitRecordIterator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/RecordIterators.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/SchemaEvolvedRecordIterator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
* Unify RecordIterator and HoodieParquetReader with ClosableIterator
* Add a factory clazz for RecordIterator
* Add more documents
No
none
=> [HUDI-5306] Unify RecordIterator and HoodieParquetReader with ClosableIterator

website/docs/cli.md, website/i18n/cn/docusaurus-plugin-content-docs/current/deployment.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.0/admin_guide.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.1/deployment.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.2/deployment.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.3/deployment.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.6.0/deployment.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.7.0/deployment.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.8.0/deployment.md, website/i18n/cn/docusaurus-plugin-content-docs/version-0.9.0/deployment.md, website/versioned_docs/version-0.10.0/cli.md, website/versioned_docs/version-0.10.1/cli.md, website/versioned_docs/version-0.11.0/cli.md, website/versioned_docs/version-0.11.1/cli.md, website/versioned_docs/version-0.12.0/cli.md, website/versioned_docs/version-0.12.1/cli.md, website/versioned_docs/version-0.5.0/admin_guide.md, website/versioned_docs/version-0.5.1/deployment.md, website/versioned_docs/version-0.5.2/deployment.md, website/versioned_docs/version-0.5.3/deployment.md, website/versioned_docs/version-0.6.0/deployment.md, website/versioned_docs/version-0.7.0/deployment.md, website/versioned_docs/version-0.8.0/deployment.md, website/versioned_docs/version-0.9.0/cli.md, website/versioned_docs/version-0.9.0/deployment.md
Fix Compaction Cli usage specifically for unschedule 
Correcting website only
none
Updated all versions where relevant
=> [DOCS] Fix compaction cli usage

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/HoodiePipeline.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
=> [HUDI-5331] Add schema settings with stream api

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java, hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
Support type change for schema on read + reconcile schema
Fixes #7283 
https://issues.apache.org/jira/browse/HUDI-5293
Less warnings
none
N/A
=> [HUDI-5294] Support type change for schema on read + reconcile schema

hudi-spark-datasource/hudi-spark/src/main/antlr4/org/apache/hudi/spark/sql/parser/HoodieSqlCommon.g4, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HelpProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/parser/HoodieSqlCommonAstBuilder.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCommitsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestHelpProcedure.scala
add call help procedure.
no
low
add `call help` procedure
=> [HUDI-5314] add call help procedure

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/DayBasedCompactionStrategy.java
Fix possible out of bounds exception in DayBasedCompactionStrategy during sublist operation.
Bug fix.
none
N/A
=> [MINOR] Fix Out of Bounds Exception for DayBasedCompactionStrategy

hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java, hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
Add tos & cfs storage schemes into `StorageSchemes` class
No
No
No
=> [HUDI-5365] Add Volcengine Object Storage(tos) and Cloud HDFS(cfs)

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitSink.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkTables.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/partitioner/TestBucketAssigner.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestViewStorageProperties.java
Cherry pick for HUDI-5007 and HUDI-5228
Cherry pick for HUDI-5007 and HUDI-5228
none
=> Cherry pick for HUDI-5007 and HUDI-5228

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
(cherry picked from commit c63728019a091b60591241e41062465098ce049c)
cherry pick HUDI-5412
None
none
=> [HUDI-5412] Send the boostrap event if the JM also rebooted (#7497)

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
Optimize the iterator for cow base files with instant range filtering.
None
none
=> [HUDI-5399] Flink mor table streaming read throws NPE

packaging/bundle-validation/Dockerfile, packaging/bundle-validation/flink/compact.sh, packaging/bundle-validation/validate.sh
Add sleep to improve stability.
NA
NA
NA
=> [MINOR] Improve flink bundle validation stability

azure-pipelines.yml, hudi-spark-datasource/hudi-spark/pom.xml, pom.xml
Upgrade ubuntu image version in azure-pipelines.yml from 18.04 to 22.04.
NA
none
NA
=> [HUDI-4827] Rebase Azure Image on Ubuntu 22.04 - scalatest-maven-plugin version update

doap_HUDI.rdf
=> [MINOR] Update DOAP with 0.12.2 release

hudi-utils/pom.xml, website/docs/configurations.md
Config now has dependency on aws module com/amazonaws/services/dynamodbv2/model/BillingMode. 
none
low
none
=> [DOCS] Add aws module dependency for config generation and update new configs

doap_HUDI.rdf
Fix doap file syntax for compliance.
To match the date with announcement email sent on 2022-12-28
NA
NA
NA
=> [MINOR] Fix doap file syntax

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanPartitionFilter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanPartitionFilterMode.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestSparkClusteringPlanPartitionFilter.java
=> [HUDI-3572]support DAY_ROLLING strategy in ClusteringPlanPartitionFilterMode

website/docs/concurrency_control.md, website/docs/metadata.md, website/releases/release-0.12.0.md, website/versioned_docs/version-0.12.0/concurrency_control.md, website/versioned_docs/version-0.12.0/metadata.md, website/versioned_docs/version-0.12.1/concurrency_control.md, website/versioned_docs/version-0.12.1/metadata.md, website/versioned_docs/version-0.12.2/concurrency_control.md, website/versioned_docs/version-0.12.2/metadata.md
Update for `FileSystemBasedLockProvider`.
NA
None.
NA
=> [DOCS][MINOR] Update docs for fs based lock provider

website/versioned_docs/version-0.12.0/concurrency_control.md, website/versioned_docs/version-0.12.1/concurrency_control.md, website/versioned_docs/version-0.12.2/concurrency_control.md
Update for FileSystemBasedLockProvider.
NA
none
=> [DOCS][MINOR] add File base lock description 

hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/InternalSchemaUtils.java
Made the error messages better
Makes our project look better
none
N/A
=> [MINOR] Fixed some spelling and syntax issues in InternalSchemaUtils

.gitignore
Add metastore_db/ into gitignore file.
N/A
none
N/A
=> [MINOR] Add `metastore_db/` into gitignore file

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/InternalSchemaManager.java
Added supplementary javadocs to InternalSchemaManager.
None
Low
=> [HUDI-5542] Add javadocs for InternalSchemaManager

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR fixex minor issues in HoodieMetadataTableValidator docs.
Only Javadocs update.
none
N/A
=> [MINOR] Fix minor issues in HoodieMetadataTableValidator docs

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
_Add database config for flink._
_Add database config in FlinkOptions._
_low._
=> [MINOR] Add database config for flink

hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Disable testcases for short term.
NA
None
NA
=> [MINOR] Disable async clean in testCleanerDeleteReplacedDataWithArchive

pom.xml
Fix the module and bundle jar name for flink 1.15.x version.
Fix the name
none
=> [MINOR] Fix flink 1.15 build profile

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetaserverConfig.java, packaging/bundle-validation/service/read.scala, packaging/bundle-validation/validate.sh
Fix bundle validation script which does not run kafka connect and metaserver validation due to early exit.
NA
None
NA
=> [HUDI-5620] Fix bundle validation early exiting issue

rfc/rfc-41/rfc-41.md, rfc/rfc-51/rfc-51.md
=> [MINOR] Correct RFC numbering

website/src/pages/videos.md
=> [DOCS] Add more video resources to the website

pom.xml
As above.
If not doing, we're missing these artifacts when building the project.
none
N/A
=> [MINOR] Add `hudi-platform-service` and `hudi-metaserver-server-bundle` to root pom

pom.xml
=> Revert "[MINOR] Add `hudi-platform-service` and `hudi-metaserver-server-bundle` to root pom"

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
Fix `usersVirtualKeys` flag
NA
Low
NA
=> [MINOR] Fix `HoodieCDCRDD` setting flag `usesVirtualKeys`

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
Supplement to https://github.com/apache/hudi/pull/7767
None
low
None
=> [HUDI-5629] Clean CDC log files for enable/disable scenario

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
This PR makes most of the Spark SQL operations configs overridable, leaving only a few ones as those that should not and couldn't be overridden by the user
Allows user greater flexibility in controlling behavior of Spark SQL statements
Low
N/A
=> [MINOR] Make most of the Spark SQL DML operations configs overridable

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieBootstrapConfig.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
=> [MINOR] Fix bootstrap typos

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
Fix typos in HoodieIndexer class
Only comments and descriptions
none
none
=> [MINOR] Fix indexer typos

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
improve RunClusteringProcedure with partition selected
NA
low
NA
=> [MINOR] Improve RunClusteringProcedure with partition selected

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/FlinkClusteringConfig.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java
Description update for Flink Clustering and Compaction configuration
None
None
=> [MINOR] Description update for Flink Clustering and Compaction configuration

hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/ArchiveExecutorUtils.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ArchiveCommitsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestArchiveCommitsProcedure.scala
Support archive command for spark sql
NA
none
NA
=> [HUDI-5773] Support archive command for spark sql

rfc/rfc-48/rfc-48.md
=> [MINOR] Fixing RFC 48 title

azure-pipelines.yml
Enable publish test results so we can use azure devops features that rely on test results
find failing tests easier
high
not sure what happens, could mess up our ci pipeline
N/A
=> [MINOR] enable publish test results

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Improvement to tracking of failures by passing boolean state to downstream functions.
As above
low
NA
=> [MINOR] Improving logging and tracking of failures for metadata validator

rfc/rfc-56/rfc-56.md
This PR updates RFC-56 based on the new naming of conflict detection strategy classes and configurations, and adds caveats.
RFC updates only.
none
RFC updates only.
=> [HUDI-5809][RFC-56] Keep RFC-56 early conflict detection update to date

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PushGatewayReporter.java
Currently we maintain a single Metrics instance per table (and a separate one for metadata table). That means we create a separate instance for PushGateway, the client for push gateway. This implies that we have a connection pool per hudi table, that is leading to a lot of open/waiting/blocked TCP connections on the push gw, possibly causing it to crash. 
In this PR, we ensure that we use a single PushGateway instance per hostname and port, ensuring we only maintain a single connection pool per PushGw Server Instance
Reduces chance of exception
low
N/A
=> [HUDI-5795] Ensure we only have a single push gw client and hence a single connection pool

hudi-utils/generate_config.sh, hudi-utils/pom.xml, hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
Also make changes so required configs  bubble up to the top of the section.
=> [DOCS] Change Config generator to generate subgroups

doap_HUDI.rdf
As above.
Adds 0.13.0 release.
none
N/A
=> [MINOR] Update DOAP with 0.13.0 Release

website/docs/metadata.md, website/docs/metadata_indexing.md
Update metadata indexing docs.
Docs update.
low
=> [DOCS] Update metadata indexing doc

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataToAvroConverters.java
fix  the compilation failure for master branch.
None
=> [MINOR] fix  the compilation failure for master branch.

hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/SchemaChangeUtils.java
schema evolution  relax decimal type conversion conditions.
None.
=> [MINOR] schema evolution  relax decimal type conversion conditions

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AwsGlueCatalogSyncTool.java, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDropPartitionsTool.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BootstrapExecutor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
Release the resource for all kinds of hoodie sync tool instances.
No impact.
none.
=> [HUDI-5852] Release the HoodieSyncTool actively if possible

hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java, hudi-common/src/main/java/org/apache/hudi/common/fs/ConsistencyGuard.java, hudi-common/src/main/java/org/apache/hudi/common/fs/ConsistencyGuardConfig.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FailSafeConsistencyGuard.java, hudi-common/src/main/java/org/apache/hudi/common/fs/OptimisticConsistencyGuard.java, hudi-common/src/main/java/org/apache/hudi/common/fs/SizeAwareDataOutputStream.java, hudi-common/src/main/java/org/apache/hudi/common/model/debezium/AbstractDebeziumAvroPayload.java
JIRA: HUDI-5869. Fix Some Typos in Hudi-Common.
When reading the code, I found some typo issues and fixed them.
none.
none.
none.
=> [HUDI-5869] Fix Some Typos in Hudi-Common.

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java, hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java, hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaUtils.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java, hudi-flink-datasource/hudi-flink/src/test/resources/test_read_schema_dropped_age.avsc, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableChangeColumnCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
This PR adds column dropping check when `hoodie.avro.schema.validate=false`
Core changes are in `org.apache.hudi.table.HoodieTable#validateSchema` 
1. Added column drop check into HoodieTable validation
2. Improved exception message of validation failure
3. Added test `testColumnDroppingIsNotAllowed()`
Fixed issue:
```sql
-- Step 1.
create table tbl(
`uuid` bigint,
`name` string,
`age` int null, -- column to be dropped
`part` int
) partitioned by (`part`) with (
'connector'='hudi',
'path'='/tmp/tbl',
'hoodie.avro.schema.validate'='false',
'hoodie.datasource.write.schema.allow.auto.evolution.column.drop'='false'
);
insert into tbl values (1, 'Danny', 23, 10);
drop table tbl;
-- Step 2.
create table tbl(
`uuid` bigint,
`name` string,
`part` int
) partitioned by (`part`) with ( …
```
=> [HUDI-5736] Common de-coupling column drop flag and schema validation flag

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BulkInsertDataInternalWriterHelper.java
Currently a log msg that says "Creating new file for partition path" is generated every time the current partition changes, even when no new file is being created (which is confusing). This issue is fixed by #7658 in Flink, but it's not fixed in Spark.
N/A
low
N/A
=> [HUDI-5866] Fix unnecessary log messages during bulk insert in Spark

website/docs/configurations.md
=> [MINOR][DOC] Fix typo for "ontained"

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
There is no need to initialize the txn manager related variables when auto commit is disabled. The metadata file desrrialization takes unnecessary cost.
No impact for API
none
=> [HUDI-5878] Optimize the txn metadata for BaseCommitActionExecutor

hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/HiveQueryNode.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerMetrics.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionException.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionMetrics.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionService.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/ProtoKafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/MysqlDebeziumSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/PostgresDebeziumSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroKafkaSource.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSourcePostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestAbstractDebeziumSource.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Add abstraction classes for DeltaSyncService and DeltaStreamerMetrics
- HoodieIngestionService
- HoodieIngestionMetrics
NA
Low
=> [HUDI-5872] Abstraction for DeltaSyncService and DeltaStreamerMetrics

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/savepoint/SavepointActionExecutor.java
Currently, savepoint only considers the completed clean instant. It is possible just before savepoint started, a clean instant was inflight. Savepoint completed as well as clean complated. But, now when we do restore to that savepoint, it will fail as the cleaner would have cleaned up the instant. This PR fixes that by aborting savepoint if there is a pending clean with earliest commit to retain greater than savepoint instant.
No public API change. Fixing a corner case in savepoint.
low
- _Any new feature or user-facing change requires updating the Hudi website. Please …
=> [HUDI-5881] Handle pending clean instants while running savepoint

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
upport more than one update actions in merge into table
NA
NA
low
NA
=> [HUDI-5904] support more than one update actions in merge into table

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieHBaseIndexConfig.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/RebalancedSparkHoodieHBaseIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestRebalancedSparkHoodieHBaseIndex.java
=> [HUDI-4675] add unittest for RebalancedSparkHoodieHBaseIndex

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
Ignoring unnecessary warn msgs about timeline server disabled for MDT. 
doc changes.
none.
=> [MINOR] Ignoring warn msg for timeline server for mdt

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java, hudi-utilities/src/test/resources/delta-streamer-config/short_trip_uber_config.properties
Context:  https://github.com/apache/hudi/pull/6726#issuecomment-1468270289
This change reverts commit c392fb7ff8cfbbe898c465ea7b219458c43b2692.
Reverts https://github.com/apache/hudi/pull/6726 as it introduces NPE 
none
N/A
=> [HUDI-4630]  Revert "HUDI-4630 Add transformer capability to individual feeds in MultiTableDeltaStreamer"

website/docs/cli.md
Add Hudi cli bundle docs
medium 
low 
This change is a doc update
=> [HUDI-5652] Add hudi-cli-bundle docs

.github/workflows/bot.yml
bot.yml ignore more filetype.
N/A
none
N/A
=> [MINOR] bot.yml ignore more filetype.

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
Introduced by #7345
No impact.
none
=> [HUDI-5938] No need to init the properties for each data flushing

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
HoodieDeltaStreamer already supports [more operations](https://github.com/apache/hudi/blob/master/hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java#L758) and needs to improve the description of operations in HoodieDeltaStreamer.
No
None
=> [HUDI-5931] Improve the description of operation in HoodieDeltaStreamer

README.md
Adding Flink 1.15.x and 1.16.x building info to the README.md. 
No impact.
none
=> [HUDI-5947] Update the README for flink jar building

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Cherry pick the changes to Flink engine.
No impact.
none.
=> [HUDI-5407] Following the first patch, add changes for Flink

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
Add more fallback keys for Flink options to reduce the ambiguity.
No impact.
none
=> [HUDI-5965] Add fallback keys for Flink options
