apache/hudi

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
=> [HUDI-3268] Fixing NullPointerException with HoodieFileIndex when keygenclass is null in table config (against 0.10.1 branch)

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableChangeColumnCommand.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableDropPartitionCommand.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/ShowHoodieTablePartitionsCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTable.scala
=> [HUDI-3236] use fields'comments persisted in catalog to fill in schema

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BootstrapExecutor.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
=> [HUDI-3283] Bootstrap support overwrite existing table

website/docs/docker_demo.md
This PR updates the Docker Demo docs with Trino setup and queries.
- Updates `docker_demo.md`
Verified the Docker Demo page locally after building and starting the website with `npm start`.
=> [HUDI-2785][DOCS] Update Docker Demo docs with Trino setup and queries

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala, hudi-spark-datasource/hudi-spark/pom.xml, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
Existing `SparkHoodieTableFileIndex` requires checking against the key generator class name to generate the partition schema.  This logic introduces NPE when the key generator class name is not present in `hoodie.properties`.  This PR fixes the issue so that if the key generator class name is not present, default logic is used.
Stacktrace:
```
scala> val basePath = "/tmp/hoodie/hudi-test-topic"
basePath: String = /tmp/hoodie/hudi-test-topic
scala> val df = spark.read.format("hudi").load(basePath)
df: org.apache.spark.sql.DataFrame = [_hoodie_commit_time: string, _hoodie_commit_seqno: string ... 15 more fields]
scala> df.count
at org.apache.hudi.SparkHoodieTableFileIndex._partitionSchemaFromProperties$lzycompute(SparkHoodieTableFileIndex.scala:83)
at …
```
=> [HUDI-3268] Fix NPE while reading table with Spark datasource

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/EmptyRelation.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/EmptyRelation.scala
*Fixed read of an empty table (failed write) with proper information.
- Fixed read of an empty table (failed write) with proper information.
Stacktrace before the fix: 
find in the attached jira. 
Result after the fix:
```
val df = spark.read.format("hudi").load("/tmp/hudi_trips_cow")
df: org.apache.spark.sql.DataFrame = []
```
=> [HUDI-1850][HUDI-3234] Fixing read of a empty table but with failed write

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala
```
hudi 0.11.0 master build
spark: 2.4.5
```
```bash
hive
create database test_hudi;
```
```scala
spark-shell --master yarn --deploy-mode client --executor-memory 2G --num-executors 3 --executor-cores 2 --driver-memory 4G --driver-cores 2 --conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'  --conf 'spark.sql.extensions=org.apache.spark.sql.hudi.HoodieSparkSessionExtension' --principal ..  --keytab ..
import org.apache.hudi.DataSourceWriteOptions._
import org.apache.hudi.QuickstartUtils.{DataGenerator, convertToStringList, getQuickstartWriteConfigs}
import org.apache.hudi.config.HoodieWriteConfig.TBL_NAME
import org.apache.spark.sql.SaveMode._
import org.apache.spark.sql.{SaveMode, SparkSession}
import org.apache.spark.sql.functions.lit
import …
```
=> [HUDI-3282] Fix delete exception for Spark SQL when sync Hive

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Looks like conflict resolution had a bug in auto commit code path. Incidentally both spark datasource writer and deltastreamer uses non auto commit code path and hence this was never an issue. Fixing the same in this patch and added tests to verify the fix. 
*(or)*
(or)
*(example:)*
=> [HUDI-3072] Fixing conflict resolution in transaction management code path for auto commit code path

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
A little change want to do during reading meta data table related code.
1. Wrong describe for  warn log `HoodieMetadataConfig.IGNORE_SPURIOUS_DELETES.key() + " config is set to false"` ->  `HoodieMetadataConfig.IGNORE_SPURIOUS_DELETES.key() + " config is set to true"`
2. do `metadataConfig.ignoreSpuriousDeletes()` instead of `!metadataConfig.ignoreSpuriousDeletes()` (a little confusing). Maybe can just ignore when set ignore true.
3. some typos.
*(or)*
(or)
*(example:)*
- …
=> [Minor]change log info and if-else logic in metadata table

website/docs/flink-quick-start-guide.md
[MINOR] Fix the Flink Guide, Streaming Query, create table sql without ','
*(or)*
(or)
*(example:)* …
=> [MINOR] Fix Flink Guide create sql without ','

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
`hoodie.deltastreamer.source.s3incr.ignore.key.prefix` and `hoodie.deltastreamer.source.s3incr.ignore.key.substring` can be null and are not required parameters. Using `getString` was throwing `IllegalArgumentException`
*(or)*
(or) …
=> Add default value as null for S3 Incremental source properties

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobExecutionStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDSpatialCurveSortPartitioner.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/columnstats/ColumnStatsIndexHelper.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestLayoutOptimization.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSpaceCurveLayoutOptimization.scala
Refactoring layout optimization (clustering) flow to
- Enable support for linear (lexicographic) ordering as one of the ordering strategies (along w/ Z-order, Hilbert)
- Reconcile Layout Optimization and Clustering configuration to be more congruent
- Refactored layout optimization flow to enable support for linear (lexicographic) ordering in column-stats indexes
- Reconcile Layout Optimization and Clustering configuration to be more congruent
- Refactored tests to validate full matrix of all optimization strategies, spatial curve composition strategies
This pull request is already covered by existing tests, such as *(please …
=> [HUDI-2872][HUDI-2646] Refactoring layout optimization (clustering) flow to support linear ordering

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableChangeColumnCommand.scala, hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTable.scala
=> [HUDI-3237] gracefully fail to change column datatype

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackRequest.java
=> [MINOR] Fixing serializability for ListingBasedRollbackRequest

hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
=> [HUDI-3215] Solve UT for Spark 3.2

website/package.json
The build of Hudi website is broken due to the following error from `npm run build`:
```
(asf-site)> npm run build
> hudi@0.0.0 build
> docusaurus build
[INFO] Website will be built for all these locales: 
- en
- cn
[INFO] [en] Creating an optimized production build...
✔ Client
✖ Server
Compiled with some errors in 2.64m
[ERROR] Docusaurus Node/SSR could not render static page with path / because of following error:
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at a.b.render (main:115785:32)
at a.b.read (main:115781:83)
at Object.exports.renderToString (main:115792:138)
at doRender (main:25801:356)
at async …
```
=> [MINOR] Fix build of Hudi website

website/package.json, website/src/pages/blog/streaming-data-lake-platform.md
Fix the broken link with a redirect, hence the regular redirect is not working, came up with this workaround since the link has been tweeted to reduce the impact.
*(or)*
(or)
*(example:)* …
=> [Docs] Stop-gap solution to fix the broken blog link

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Fixes HUDI-2943
- Add config to retry last pending clustering before writing to sink
- If the config set to true and inline clustering enabled, then complete the pending clustering before writing to sink.
*(or)*
(or)
*(example:)*
=> [HUDI-2943] Complete pending clustering before deltastreamer sync

hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkTempViewProvider.java
fix the issue of HUDI-1977, hudi-cli won`t print anything after run temp query comand
Modify ASparkTempViewProvider.java 
Manually verified the change by running a job locally.*
- [Y] Has a corresponding JIRA in PR title & commit
- [Y] Commit message is descriptive of the change
- [Y] CI is green
- [N] Necessary doc changes done or have another open PR
- [N] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.
=> [HUDI-1977] Fix Hudi CLI tempview query LOG issue

website/docs/query_engine_setup.md, website/versioned_docs/version-0.10.0/query_engine_setup.md, website/versioned_docs/version-0.9.0/query_engine_setup.md
We upgraded Hudi version from 0.5.3 to 0.9.0 in Presto 0.265 but that introduced a breaking dependency change in another presto module. Since then, we have fixed the hudi-presto-bundle in version 0.10.1. Now, we need to upgrade Hudi in Presto again. This is being tracked by HUDI-3010. This PR adds a note to either avoid upgrade or workaround it by manually placing the hudi-presto-bundle jar.
*(or)*
(or)
*(example:)*
- *Added integration …
=> [MINOR] Add a message for presto upgrade

rfc/rfc-46/rfc-46.md
Drafting RFC-46
See above 
N/A
=> [HUDI-3318] [RFC-46] Optimize Record Payload handling

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
=> [HUDI-3292] Enabling lazy read by default for log blocks during compaction

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
=> [HUDI-2711] Fallback to fulltable scan for IncrementalRelation if underlying files have been cleared or moved by cleaner

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/TwoToOneDowngradeHandler.java
when marker directory does not exists, two to one downgrade fails w/ exception. 
https://github.com/apache/hudi/issues/4666
*(or)*
(or)
*(example:)*
=> [HUDI-3346] Fixing non existant marker dir handling in TwoToOne downgrade

pom.xml
This reverts commit 6f1010799861b9e4b331d0bf5a473211200c15d1.
From azure pipeline runs, looks like there are lot of timeouts after the rocksdb version got upgraded. Testing out by reverting to see if this is the root cause. 
*(or)*
(or)
This change added tests and can be …
=> [HUDI-3368] Revert "[HUDI-3306] Upgrade rocksdb version (#4663)"

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackHelper.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackRequest.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestMetadataConversionUtils.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java, hudi-common/src/main/avro/HoodieRollbackMetadata.avsc, hudi-common/src/main/java/org/apache/hudi/common/HoodieRollbackStat.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java, hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
This change is addressing issues in regards to Metadata Table observing ingesting duplicated records leading to it persisting incorrect file-sizes for the files referred to in those records.
There are multiple issues that were leading to that: 
1. [HUDI-3322] Incorrect Rollback Plan generation: Rollback Plan generated for MOR tables was overly expansively listing all log-files with the latest base-instant as the ones that have been affected by the rollback, leading to invalid MT records being ingested referring to those.
2. [HUDI-3343] Metadata Table including Uncommitted Log Files during Bootstrap: Since MT is bootstrapped at the …
=> [HUDI-3322][HUDI-3343] Fixing Metadata Table Records Duplication Issues

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java, hudi-common/src/main/java/org/apache/hudi/TypeUtils.java, hudi-common/src/main/scala/org/apache/hudi/HoodieTableFileIndexBase.scala, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/BaseFileWithLogsSplit.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/BootstrapBaseFileSplit.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileInputFormatBase.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHFileInputFormat.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/InputPathHandler.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/PathWithLogFilePath.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/RealtimeFileStatus.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieHFileRealtimeInputFormat.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieParquetRealtimeInputFormat.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieRealtimeFileSplit.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeBootstrapBaseFileSplit.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeSplit.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/functional/TestHoodieCombineHiveInputFormat.java
Removing duplicated file-listing process w/in Hive's MOR `Hoodie{Parquet|HFile}RealtimeInputFormat`
See above
=> [HUDI-3191] Removing duplicating file-listing process w/in Hive's MOR `FileInputFormat`s

hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCompactionCommand.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
https://issues.apache.org/jira/browse/HUDI-3369
Users can use --mode schedule to build a compaction plan and execute this plan immediately through HoodieCompactor or hudi-cli
```
Example commands
connect --path /Users/yuezhang/tmp/xxxx
compaction scheduleAndExecute --parallelism 2 --schemaFilePath /xxx/schema --hoodieConfigs hoodie.compact.inline.max.delta.commits=0
```
OR 
```
spark-submit --master local --class org.apache.hudi.utilities.HoodieCompactor /Users/yuezhang/workproject/hudi/packaging/hudi-utilities-bundle/target/hudi-utilities-bundle_2.11-0.11.0-SNAPSHOT.jar --base-path /Users/yuezhang/tmp/xxxx--mode scheduleAndExecute --table-name xxxx  --spark-memory 4g --parallelism 2 --hoodie-conf hoodie.compact.inline.max.delta.commits=0
```
- *Modify AnnotationLocation …
=> [HUDI-3369] New ScheduleAndExecute mode for HoodieCompactor and hudi-cli

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieSourceTimeoutException.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
- Adding support for retries in detlastreamer on source errors. For eg, if source is down, instead of failing, users could add some retries. 
- Three new configs are added for this purpose to DetlaStreamerConfig. "--retry-on-source-failures", "-retry-interval-seconds" and "-max-retry-count". By default retries are disabled. 
*(or)*
(or)
*(example:)* …
=> [HUDI-3360] Adding retries to deltastreamer for source errors

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Prometheus [Pushgateway](https://prometheus.io/docs/practices/pushing/) never forgets series pushed to it and will expose them to Prometheus forever unless those series are manually deleted via the Pushgateway's API. When deltastreamer finds that there are no new records to be read from the source since the last checkpoint it doesn't emit a metric because the write path is not triggered and leads to a graph like below in case of PushGateway metrics reporter. For other metrics reporter it would be a null value and no data will be shown in the graph.
`22/02/07 11:23:10 INFO DeltaSync: No new data, source checkpoint has not changed. …
=> [HUDI-3373] Add zero value metrics for empty data source and PROMETHEUS_PUSHGATEWAY reporter

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/SchedulerConfGenerator.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSchedulerConfGenerator.java
Adding support to setting custom scheduler spark configs for streaming sink. 
Users have to set spark config as "spark.scheduler.allocation.file=/sample_alloc_file" when they launch the spark-shell to leverage this. 
sample file contents
```
<?xml version="1.0"?>
<allocations>
<pool name="sparkdatasourcewrite">
<schedulingMode>FAIR</schedulingMode>
<weight>3</weight>
<minShare>1</minShare>
</pool>
<pool name="hoodiecompact">
<schedulingMode>FAIR</schedulingMode>
<weight>2</weight>
<minShare>1</minShare>
</pool>
</allocations>
```
The poolname is hardcoded within hudi and so users are expected to match the pool names as is. 
Tested this patch manually by explicitly setting the allocation file and w/o. …
=> [HUDI-3367] Adding support for custom scheduler configs with streaming sink

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
When begin instantime for incremental pull is missing from source hudi table's timeline (due to archival), we support two strategies. read from latest and read upto latest. Read from latest is an incremental pull just with latest commit. Read upto latest is a snapshot query since the puller do not know what exactly to pull. There was some bug in this flow (read upto latest) and have fixed it. 
For eg, lets say source hudi table has the following timeline
C1, C2... C10. 
commits until C4 are archived. 
When the puller sets read upto latest with following begin timestamp:
Option.empty()
Or
C1
Or 
C2
Or 
C3
All of the above will result in snapshot query (or full table scan) with the fix in this patch. 
*(Please …
=> [HUDI-3361] Fixing missing begin checkpoint in HoodieIncremental pull

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableClustering.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableIncrementalRead.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
At the write client layer, inline and async has a very tighter meaning. enabling inline compaction means, both scheduling and execution is inline. Same applies to clustering as well. If async config is enabled, both scheduling and execution has to be done async and regular writer will not do anything. But any scheduling has to be done in a coordinated manner or in other words, there should not be any other operation inflight. For eg, if someone has a separate process to schedule and execute compaction, they have to ensure no other writers are in progress while scheduling. If not, it might lead to data loss. Which means, this puts an extra burden for users to configure lock providers. But Hudi has the intelligence where scheduling can be done inline, but execution can be done async. Just …
=> [HUDI-1847] Adding inline scheduling support for spark datasource path for compaction and clustering

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/RestoreUtils.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RestorePlanActionExecutor.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkMergeOnReadTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-common/src/main/avro/HoodieRestorePlan.avsc, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
Introducing restore.requested instant for restore action. 
- Restore is split into restore plan and restore execution phase. 
- A restore Plan is added which gets serialized into restore.requested instant during planning phase. This contains the list of instants to rollback. 
- During execution phase, restore plan is read from the requested instant and individual rollbacks are executed. 
- Once completed, timeline will contain 3 meta files for restore (requested, inflight and complete) and no meta files for rollbacks will be present in timeline. 
*(or)*
This pull request is already …
=> [HUDI-2432] Adding restore.requested instant and restore plan for restore action

hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java, pom.xml
fix problems that writing data using `DefaultHoodieRecordPayload` in spark 3.2 env will throw an exception as follows:
```
org.apache.avro.AvroRuntimeException: Not a valid schema field: ts
at org.apache.avro.generic.GenericData$Record.get(GenericData.java:256)
at org.apache.hudi.avro.HoodieAvroUtils.getNestedFieldVal(HoodieAvroUtils.java:439)
at org.apache.hudi.common.model.DefaultHoodieRecordPayload.getNestedFieldVal(DefaultHoodieRecordPayload.java:134)
at org.apache.hudi.common.model.DefaultHoodieRecordPayload.updateEventTime(DefaultHoodieRecordPayload.java:92)
at org.apache.hudi.common.model.DefaultHoodieRecordPayload.getInsertVa …
```
=> [HUDI-3333] fix that getNestedFieldVal breaks with Spark 3.2

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
=> [HUDI-2610] pass the spark version when sync the table created by spark

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java
Hoodie converts `Timestamp` to TIMESTAMP_MICROS format when upsert and other operations, except `bulk_insert`.
And `bulk_insert` enables `hoodie.datasource.write.row.writer.enable`, and use `HoodieRowParquetWriteSupport` to write datas. 
For the issue #4552 , that will cause problems by default. So i suggest to modify the `hoodie.parquet.outputtimestamptype` default value to TIMESTAMP_MICROS so that it will be convenience to users.
=> [HUDI-3402] Set hoodie.parquet.outputtimestamptype to TIMESTAMP_MICROS by default

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RestorePlanActionExecutor.java, hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
As part of restore, we want to rollback pending clustering operations first. Otherwise, commit sequence validation is failing and causing problems to timeline
- Rollback pending clustering instants followed by other commits as part of restore.
Did not get chance to add unit tests.
Verified with test dataset provided by @nsivabalan. Restore successfully reverts most commits. But there seems to be one other issue with metadata table related to schema compatibility 
org.apache.hudi.exception.HoodieException: Failed schema compatibility check for writerSchema base path :/tmp/hudi_tbl41/.hoodie/metadata
This doesn't seem to happen if metadata table is disabled
=> [HUDI-3362] Fix restore to rollback pending clustering operations followed by other rolling back other commits

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SqlSource.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlSource.java
https://issues.apache.org/jira/browse/HUDI-2413
- with SqlSource there is not checkpoint and is usually used only for one time backfill use-cases. So, added a config to deltastreamer named "--allow-commit-on-no-checkpoint-change". 
- Users are expected to set this config to true with SqlSource. 
- Added tests to TestSqlSource 
- Added tests to TestHoodieDeltaStreamer to test SqlSource.
=> [HUDI-2413] fix Sql source's checkpoint issue

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java
Check `started` flag before starting async service.
=> [MINOR] Prevent async service from starting twice

hudi-kafka-connect/pom.xml, pom.xml
Fix the build Hudi on Arm64 Fedora33.
Protocbuf did not support Arm64 until Protobuf 3.5.0.
So we should upgrade Protoc dependency for fix the build issues:
```
[INFO] Protoc version: 3.1.0
protoc-jar: protoc version: 310, detected platform: linux/aarch64
[INFO] Protoc command: /tmp/protocjar1741426592250217060/bin/protoc.exe
[INFO] Input directories:
[INFO]     /home/builder/hudi/hudi-kafka-connect/src/main/resources
[INFO] Output targets:
[INFO]     java: /home/builder/hudi/hudi-kafka-connect/target/generated-sources (add: main, clean: false, plugin: null, outputOptions: null)
[INFO] …
```
=> HUDI-1657: build failed on AArch64, Fedora 33

hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyViewRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Regardless of whether 'hoodie.file.index.enable' is enabled or not, use the unified relation and output the right schema information.
*(or)*
(or)
*(example:)* …
=> [HUDI-3200] deprecate hoodie.file.index.enable and unify to use BaseFileOnlyViewRelation to handle

website/docs/encryption.md, website/sidebars.js
=> [HUDI-2370][DOCS] Add encryption guide

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestArchivedCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCompactionCommand.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestMultiFS.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBootstrap.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/storage/row/TestHoodieRowCreateHandle.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableIncrementalRead.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
This PR removes hardcoded logic of disabling metadata table in tests and fixes tests that are broken with metadata table enabled.
=> [HUDI-3366] Remove hardcoded logic of disabling metadata table in tests

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
[HoodieClusteringConfig](https://github.com/apache/hudi/blob/master/hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java#L191) looks at a different key compared to `HoodieSparkSqlWriter` which looks at [DataSourceOptions](https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala#L595). This PR fixes that.
*(or)*
(or) …
=> [HUDI-3426] Sync datasource clustering config

hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunction.java
=> [HUDI-3442]Duplicate code calls for 'FlinkOptions.flatOptions'

hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java, hudi-client/hudi-client-common/pom.xml, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToThreeDowngradeHandler.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToFourUpgradeHandler.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java, hudi-client/hudi-spark-client/pom.xml, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java, hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java, hudi-common/src/main/java/org/apache/hudi/common/util/BinaryUtil.java, hudi-common/src/main/java/org/apache/hudi/common/util/SpillableMapUtils.java, hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java, hudi-common/src/test/java/org/apache/hudi/common/properties/TestTypedProperties.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java, hudi-integ-test/pom.xml, pom.xml
To detect partial writes on HDFS, this PR adds a new property which gets appended at the end of hoodie.properties file while creating or modiying table config. The value of the property is CRC of <database_name>.<table_name>. The PR also changes `TypedProperties` to maintain order of insertion.
- Add a new table config.
- Support the new config in UpgradeDowngrade.
- Ensure insertion order in TypedProperties.
*(or)*
(or)
*(example:)* …
=> [HUDI-2809] Introduce a checksum mechanism for validating hoodie.properties

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkUpsertDeltaCommitPartitioner.java, hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/WriteProfile.java
Method `getSmallFiles` could be very time consuming if there are many small files in one partitionPath. Though we already set `hoodie.parquet.small.file.limit` to 0, it will still call `getSmallFiles` to do the comparison, this could be avoided.
*(or)*
(or)
*(example:)*
- *Added …
=> [HUDI-3438] Avoid getSmallFiles if hoodie.parquet.small.file.limit is 0

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkConfigs.scala, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/SchedulerConfGenerator.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSchedulerConfGenerator.java
=> [MINOR] Moving spark scheduling configs out of DataSourceOptions

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseBulkInsertHelper.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaBulkInsertHelper.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaBulkInsertPreppedCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBulkInsertCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBulkInsertHelper.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBulkInsertPreppedCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkBulkInsertDeltaCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkBulkInsertPreppedDeltaCommitActionExecutor.java
`BaseBulkInsertHelper` should declare `BulkInsertPartitioner<I>` instead of `BulkInsertPartitioner<T>`.
=> [HUDI-3458] Fix BulkInsertPartitioner generic type

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-common/src/main/avro/HoodieMetadata.avsc, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
- Found couple of issues while testing restore w/ metadata enabled (COW and MOR table). 
- avro schema for metadata payload did not have default set to null for colsStats and bloomFilterMetadata that got added recently. Was running into issues with avro deserialization. 
- While reading logs for metadata table, partition name was not set with MergedLogRecordScanner. Have created a follow [ticket](https://issues.apache.org/jira/browse/HUDI-3454) to chase all such code paths and fix. 
- Tested restore for COW and MOR table for few scenarios. restore succeeded and validated the table after restore to ensure table record count matched the restored commit.
=> [HUDI-3432] Fixing restore with metadata enabled

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/update/strategy/BaseSparkUpdateStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/update/strategy/SparkRejectUpdateStrategy.java
=> [HUDI-3042] Abstract Spark update Strategy to make code more clean and remove duplicates

README.md, hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieSqlBase.scala, pom.xml
=> [HUDI-3423] upgrade spark to 3.2.1

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Adding delete partition support to deltastreamer. 
*(or)*
(or)
*(example:)*
=> [HUDI-2189] Adding delete partitions support to DeltaStreamer

packaging/hudi-flink-bundle/pom.xml
Solve the problem of "Caused by: java.lang.ClassNotFoundException: org.apache.hudi.org.apache.hadoop.hive.metastore.api.NoSuchObjectException
" in hive 3.
add dependency
```xml
<dependency>
<groupId>org.apache.hive</groupId>
<artifactId>hive-standalone-metastore</artifactId>
<version>${hive.version}</version>
<scope>${flink.bundle.hive.scope}</scope>
</dependency>
```
to hudi-flink-bundle module
I compile the source code of hudi with hive 3, and succeed in synchronizing the data to hive;
The test …
=> [MINOR] Add hive-standalone-metastore dependency to hudi-flink-bundle module

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
This PR fixes the problem of incorrect value and null count read from column stats in metadata table.  The root cause is the wrong order of arguments passed to the constructor of `HoodieMetadataColumnStats`.  The constructor is:
```
public HoodieMetadataColumnStats(java.lang.String fileName, java.lang.String minValue, java.lang.String maxValue, java.lang.Long valueCount, java.lang.Long nullCount, java.lang.Long totalSize, java.lang.Long totalUncompressedSize, java.lang.Boolean isDeleted) {
```
and the original init is 
```
columnStatMetadata = new HoodieMetadataColumnStats(
(String) v.get(COLUMN_STATS_FIELD_RESOURCE_NAME),
(String) v.get(COLUMN_STATS_FIELD_MIN_VALUE),
(String) v.get(COLUMN_STATS_FIELD_MAX_VALUE),
(Long) v.get(COLUMN_STATS_FIELD_NULL_COUNT),
(Long) …
```
=> [HUDI-3486] Fix wrong field order for constructing HoodieMetadataColumnStats

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark3Analysis.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieInternalV2Table.scala
=> [HUDI-3489] Unify config to avoid duplicate code

docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml, docker/demo/config/test-suite/test-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-clustering.properties
- Most of our existing tests deletes input data at the end of every iteration so that we can do long running tests. So validation at the end of every iteration happens only for partial data from input. Here we are adding medium scale tests where in we don't delete any input data at all and runs for 20 iterations.
- Added test properties specifically to test out repeated clustering for a long running deltastreamer test job. 
- Minor fixes to long running jobs to reduce to 1 validation per iteration. 
*(or)*
This pull request is already covered by existing tests, such as *(please …
=> [HUDI-3480][HUDI-3481] Enchancements to integ test suite

hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java
…ompaction
*(or)*
(or)
*(example:)*
=> [HUDI-3488] The flink small file list should exclude file slices with pending compaction

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
link: [HUDI-3493](https://issues.apache.org/jira/browse/HUDI-3493)
*(or)*
(or)
*(example:)*
=> [HUDI-3493] Not table to get execution plan

hudi-cli/src/main/java/org/apache/hudi/cli/commands/ClusteringCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestClusteringCommand.java
https://issues.apache.org/jira/browse/HUDI-3429
Support clustering scheduleAndExecute for hudi-cli and add clustering-cli Tests
*(or)*
(or)
*(example:)*
=> [HUDI-3429] Support clustering scheduleAndExecute for hudi-cli and add clustering-cli Tests

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/SqlKeyGenerator.scala
* Incorrect verification of KeyGenClass attribute results in NPE.  If not set, return an empty string, NPE appears when getRecordKey *
- *Modify org.apache.spark.sql.hudi.command.SqlKeyGenerator#originKeyGen *
*(or)*
(or)
*(example:)*
- *Manually …
=> [HUDI-3401] fix NPE caused by incorrect  beforeKeyGenClassName validation

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
When we start multiple hudi jobs in a sparkSession, or cache some rdds before a hudi job starts, SparkRDDWriteClient#releaseResources will release all persistent rdds, causing spark to recalculate.
So I think we should add the switch of whether to release all rdds.
*(or)*
(or) …
=> [HUDI-3515] Making rdd unpersist optional at the end of writes

hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/functional/TestHoodieCombineHiveInputFormat.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
Even though the test initializes with MOR table type but `InputFormatTestUtil#prepareMultiPartitionedParquetTable` would change it to COW. This PR fixes that by parameterizing table type.
*(or)*
(or)
*(example:)*
=> [MINOR] Fix table type in input format test

docker/demo/config/test-suite/insert-overwrite-table.yaml, docker/demo/config/test-suite/insert-overwrite.yaml, docker/demo/config/test-suite/spark-clustering.yaml, docker/demo/config/test-suite/test-metadata.properties, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseValidateDatasetNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/DeleteInputDatasetNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/DeltaGenerator.java, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertOverwriteNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertOverwriteTableNode.scala
- Added insert override nodes and yamls to integ test suite
- Minor clean ups
- Ran the newly added jobs in local docker to verify.
=> [HUDI-3483] Adding insert override nodes to integ test suite and few clean ups

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java
With latest addition of TypedProperties in HoodieTableConfig, we ran into issues w/ kafka key and value serializer types in properties. Apparently value type was class and hence when getting string values, it returns null values while populating TypedProperties. Fixed all such instances of key.serializer and value.serializer instantiations. 
Fixed all instantiations of key.serializer and value.serializer to ensure value is of type string. 
docker demo runs successfully w/o NPE w/ this patch.
=> [HUDI-3521] Fixing kafka key and value serializer value type from class to string

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java, hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
- "_hoodie_is_deleted" is more a reserved field in hoodie. Hoodie uses that to interpret a record as active or deleted. But the field as such is optional. So, adding extra validation to ensure if the field is present, it has to be of type Boolean. 
- Adding extra validation to SqlWriter to ensure if "_hoodie_is_deleted" field is present, it has to be of type Boolean. 
*(or)*
(or)
*(example:)*
- Added tests to TestCOWDataSource to test the fix.
=> [HUDI-3018] Adding validation to dataframe schema to ensure reserved field does not have diff data type

hudi-flink/src/main/java/org/apache/hudi/source/StreamReadOperator.java
ParquetColumnarRowSplitReader#batchSize is 2048, so Changing MINI_BATCH_SIZE to 2048 will reduce memory cache.
*(or)*
(or)
*(example:)* …
=> [MINOR] Change MINI_BATCH_SIZE to 2048

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/WorkloadProfile.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/WorkloadStat.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
Redo of https://github.com/apache/hudi/pull/4446
We may find some data which should be rollbacked in hudi table.
Root cause:
Let's first recall how rollback plan generated about log blocks for deltaCommit. Hudi takes two cases into consideration.
For some log file with no base file, they are comprised by records which are all 'insert record'. Delete them directly. Here we assume all inserted record should be covered by this way.
For those fileID which are updated according to inflight commit meta of instant we want to rollback, we append command block to these log file to rollback.  Here all updated record are handled.
However, the first condition is not always true. For indexes which can index log file, they could insert record to some existing log file. In current process, inflight …
=> [HUDI-2917] rollback insert data appended to log file when using Hbase Index

hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
This PR fixes the log file reader for S3 with hadoop-aws 2.7.x.
`HoodieLogFileReader` uses `FSDataInputStream:seek` API to scan a log file and load block content.  In S3, `S3AInputStream::seek` implementation is used.  For  hadoop-aws 2.7.x, `S3AInputStream` throws `EOFException` when the seek position is the file size, as shown in the [source code](https://github.com/apache/hadoop/blob/branch-2.7.4/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L80) below:
```
if (contentLength > 0 && pos > contentLength-1) {
throw new EOFException(
FSExceptionMessages.CANNOT_SEEK_PAST_EOF
+ " " + pos);
}
```
This causes the `EOFException` for scanning the last block in a file, since the seek position is the file size.  The problem can be reproduced by running hudi-cli …
=> [HUDI-3341] Fix log file reader for S3 with hadoop-aws 2.7.x

hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java, hudi-cli/src/test/java/org/apache/hudi/cli/testutils/SparkUtilTest.java
When not passing SparkMaster, by default Hudi CLI should use [SparkUtil.DEFAULT_SPARK_MASTER](https://github.com/apache/hudi/blob/release-0.10.0/hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java#L44). However, w/ a recent [code change](https://github.com/apache/hudi/commit/445208a0d20b457daeeb5f70995302c92dd19f31) in OSS, when SparkMaster is not passed, it would set Spark master to "" which causes the following exception when initializing a Hudi CLI job:
```
{{org.apache.spark.SparkException: Could not parse Master URL: ''at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.s …
```
=> [HUDI-3450] Avoid passing empty string spark master to hudi cli

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
When the EmbeddedTimelineService started and update `ViewStorageConfig` to `RemoteFileSystemViewConfig`, the `hoodie.filesystem.view.remote.timeout.secs` option is not in `RemoteFileSystemViewConfig`.
*(or)*
(or)
*(example:)*
- *Added …
=> [HUDI-3418] Save timeout option for remote RemoteFileSystemView

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java, hudi-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/util/BloomFilterData.java
This PR adds the functionality to validate the column stats and bloom filters stored in metadata table against the ground truth in base files in `HoodieMetadataTableValidator`.
- Adds two new validation tasks in `HoodieMetadataTableValidator`
- `--validate-all-column-stats`: validate column stats for all columns in the schema
- `--validate-bloom-filters`: validate bloom filters of base files
- Adds a new class `BloomFilterData` to facilitate validation of bloom filters
- Makes `ParquetUtils::readMetadata` static
- Cleans up naming and adds minor changes around logging messages and levels
This PR is verified by running the `HoodieMetadataTableValidator` with spark-submit for all validation task to make sure that existing and new validation logic work properly.  The validation of column …
=> [HUDI-3465] Add validation of column stats and bloom filters in HoodieMetadataTableValidator

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDataTableUtils.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDataTableValidator.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieRepairTool.java
Add data table validation tool to validate data table in sane condition.
- No data files found for commits prior to active timeline.
- No extra data files for completed commits in active timeline compared to whats stored in commit metadata. 
Can run in sync once mode or continuous mode as well
verified by running locally. 
both sync once and continious. injected failures in continuous after few rounds and ensured the tool caught it.
=> [HUDI-3497] Adding Datatable validator tool

hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java, hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java, hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java, hudi-flink/src/test/java/org/apache/hudi/utils/factory/ContinuousFileSourceFactory.java, hudi-flink/src/test/java/org/apache/hudi/utils/source/ContinuousFileSource.java
* Fix NPE problem during search Flink builtin function `TO_DATE('xxx')` while enable `Hudi` catalog, because the original logic of `getPartition(ObjectPath tablePath, CatalogPartitionSpec catalogPartitionSpec)` is return null, which will caused NPE problem.
* 
- *Replace `null` with FunctionNotExistException of getFunction method in HoodieCatalog.java*
- *Replace `null` with PartitionNotExistException of getPartition method in HoodieCatalog.java*
- *Add a IT case to test get builtin function*
- *Change `TableSchema` to `ResolveSchema` in ContinousFileSource.java*
- *Added integration tests(`testBuiltinFunctionWithCatalog`) in …
=> [MINOR] fix get builtin function issue from Hudi catalog

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndex.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java, hudi-flink/src/main/java/org/apache/hudi/sink/BucketStreamWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/BucketStreamWriteOperator.java, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java, hudi-flink/src/test/java/org/apache/hudi/sink/StreamWriteITCase.java, hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
*This pull request is to implement RFC-35(https://cwiki.apache.org/confluence/display/HUDI/RFC-35%3A+Make+Flink+MOR+table+writing+streaming+friendly)*
- *Implement bucket index for Flink writer pipeline*
- *Implement BucketStreamWriteFunction to write log file in a stream like fashion*
- *Added IT test for bucket stream write function.*
=> [HUDI-3315] RFC-35 Part-1 Support bucket index in Flink writer

rfc/rfc-38/rfc-38.md
=> [MINOR] RFC-38 markdown content error

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieMultiTableDeltaStreamer.java, hudi-utilities/src/test/resources/delta-streamer-config/short_trip_uber_config.properties, hudi-utilities/src/test/resources/delta-streamer-config/uber_config.properties
Made schema registry url configs more flexible as per the request in https://github.com/apache/hudi/issues/4585
- Added a check for source and target schema registry urls in table overridden properties
- Added test cases
*(or)*
(or)
*(example:)*
- *Manually verified …
=> [HUDI-3264]: made schema registry urls configurable with MTDS

rfc/rfc-27/rfc-27.md
Updated the schema and key types used for data skipping index. 
*(or)*
(or)
*(example:)*
=> [HUDI-2973] RFC-27: Data skipping index to improve query performance

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
PopulateMetafields value for metadata table will never get updated once metadata table get initialized for the first time. With 0.11, we are making populate meta fields as false for metadata table which was true by default in 0.10.0. So fixing the update in this patch by re-initializing the metaclient if property value has changed. Every other property is statically configured except this config which user can override. hence had to fix just one property. 
Add re-intialization of metadata table metaclient and table config if populate meta fields have changed. 
- TestHoodieBackedMetadata.testUpdationOfPopulateMetaFieldsForMetadataTable
=> [HUDI-3544] Fixing "populate meta fields" update to metadata table

hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java
=> [HUDI-3548] Fix if user specify key "hoodie.datasource.clustering.async.enable" directly, async clustering not work

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanPartitionFilter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestPartitionAwareClusteringPlanStrategy.java, hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCommonUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDataSourceHelpers.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionHoodiePathCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackToInstantTimeProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/parser/HoodieSqlCommonAstBuilder.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCallProcedure.scala
*Supporting clustering command for SparkSQL*
- *Add RunClusteringProcedure and ShowClusteringProcedure*
- *Add test case in TestCallProcedure*
*(or)*
(or)
*(example:)*
=> [HUDI-3445] Support Clustering Command Based on Call Procedure Command for Spark SQL

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java, hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java, hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java, hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
=> [HUDI-3460] Add reader merge memory option for flink

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
Timeline server when serving remote requests, has a logic to refresh its local view of the timeline based on timeline hash. Client sends a timeline hash and timeline server compares with its local timeline hash and if they differ, a refresh of timeline happens before serving the request. But this refresh gets triggered even if the client is behind, but the server is already caught up. This could have severe perf impact with async table services and spark streaming pipeline use-cases where commit throughput is high. So, adding a new value to be maintained by the timeline for lastUpdatedTime. and the same will be sent as param with remote request as well. 
Fix: So, the fix ensures that timeline server triggers a refresh of local timeline only if its last known instant < client's last known …
=> [HUDI-2761] Fixing timeline server for repeated refreshes

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java, hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java, hudi-common/src/test/resources/simple-test-evolved-compatible.avsc, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/functional/TestHoodieCombineHiveInputFormat.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
*Fixing Hive getSchema for RT tables*
Refer issue for more details:  https://github.com/apache/hudi/issues/2802
Unit tests to be explored. I have tested on local and cluster spark-hive.
=> [HUDI-3130] Fixing Hive getSchema for RT tables addressing different partitions having different schemas

hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/DeleteSupportSchemaPostProcessor.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SparkAvroPostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/DummySchemaProvider.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/SparkAvroSchemaProvider.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
In our use case, data is read from kafka(binlog with some preprocess), schema read from hive, we need 
add `_hoodie_is_deleted` column to schema to support delete operation
This pull request is already covered by existing tests, such as:
org.apache.hudi.utilities.schema.TestSchemaPostProcessor#testDeleteSupport
=> [HUDI-3520] Introduce DeleteSupportSchemaPostProcessor to support adding _hoodie_is_deleted column to schema

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieSourcePostProcessException.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/processor/JsonKafkaSourcePostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSourcePostProcessor.java
Currently, we have `Transform` to transform source to target dataset before writing, but it is based on DataSet.
In some scenarios, our kafka data is not in the right format we need, such as binlog json format.
We need a way to extract/prepare the data we need from the original data before converting it into a DataSet.
*(or)*
(or)
This …
=> [HUDI-3525] Introduce JsonkafkaSourcePostProcessor to support data post process before it is transformed to DataSet

hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
when reading the delta log file, we compare the data in the external spillablemap with the delta log data. If oldrecord is selected, there is no need to rewrite the data in the external spillablemap. Rewriting data will waste a lot of resources when data is spill to disk
*(or)*
(or) …
=> [HUDI-3069] Improve HoodieMergedLogRecordScanner avoid putting unnecessary hoodie records

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala, hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java, hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Flipping the value of preserver commit metadata for compaction to true. Disabled for metadata table since meta fields are not populated. 
To discuss: 
when populate meta fields are disabled, should be check that preserve metadata can't be set to true. this might be an issue w/ kafka connect where we directly create log files. 
*(or)*
(or)
*(example:)* …
=> [HUDI-3213] Making commit preserve metadata to true for compaction

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Avoid including whole `MultipleSparkJobExecutionStrategy` object into the closure for Spark to serialize
See above
*(example:)*
=> [HUDI-3561] Avoid including whole `MultipleSparkJobExecutionStrategy` object into the closure for Spark to serialize

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/upgrade/JavaUpgradeDowngradeHelper.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java, hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java, hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/SparkRDDWriteClientOverride.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
This change makes sure MT records are updated appropriately on HDFS: previously after Log File append operations MT records were updated w/ just the size of the deltas being appended to the original files, which have been found to be the cause of issues in case of Rollbacks that were instead updating MT with records bearing the full file-size.
To make sure that we hedge against similar issues going f/w, this PR alleviates this discrepancy and streamlines the flow of MT table always ingesting records bearing full file-sizes.
- Refactored MT records composition from HoodieCommitMetadata to always operate on full file-sizes
- Fixed …
=> [HUDI-3365] Make sure Metadata Table records are updated appropriately on HDFS

hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
https://issues.apache.org/jira/browse/HUDI-2747
Fix hudi cli metadata commands.  Currently when running hudi cli metadata commands locally, it complains about spark master, e.g., yarn master not found.  The commands need to take in spark related configs so that they can run locally and in cluster.
Let's take `metadata list-partitions` as an example,
Before this patch
```
67411 [Spring Shell] INFO  org.apache.spark.SparkContext  - Running Spark version 2.4.4
67442 [Spring Shell] INFO  org.apache.spark.SparkContext  - Submitted application: HoodieCLI
67515 [Spring Shell] INFO  org.apache.spark.SecurityManager  - Changing view acls to: yuezhang
67515 [Spring Shell] INFO  org.apache.spark.SecurityManager  - Changing modify acls to: yuezhang
67516 [Spring Shell] INFO …
```
=> [HUDI-2747]Support set --sparkMaster for MDT cli

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
- Adding a configuration to guard timeline server timelime refresh based on latest commit. We are seeing flakiness wrt master CI runs. so, guarding this by a flag and setting default value to false. Might have to get to the root of it to find the right fix (which might take sometime). 
Added a new config "hoodie.refresh.timeline.server.based.on.latest.commit" to enable refreshing of timeline server timeline refresh based on latest commit. 
- Already original patch got landed which got tested a/ all existing tests. here we are adding just the config to guard the behavior.
=> [HUDI-3576] Configuring timeline refreshes based on latest commit

hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java, hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java, hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMessage.java, hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java, hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java, hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java, hudi-flink/src/test/java/org/apache/hudi/sink/meta/TestCkpMetadata.java
=> [HUDI-2677] Add DFS based message queue for flink writer[part3]

pom.xml
By default we don't need to build
```
<module>docker/hoodie/hadoop</module>
<module>hudi-integ-test</module>
<module>packaging/hudi-integ-test-bundle</module>
```
We should skip installing them during CI jobs and most dev work. We can activate them by activating `integration-tests` profile. `release` profile should activate `integration-tests` profile by default to include integ-test-bundle.
=> [HUDI-3584] Skip integ test modules by default

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLookupHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java, hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkWriteableTestTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/HoodieMetadataBloomIndexCheckFunction.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieGlobalBloomIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkWriteableTestTable.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieDeltaWriteStat.java, hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java, hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-common/src/main/java/org/apache/hudi/metadata/MetadataRecordsGenerationParams.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Rework of #4761 
This diff introduces follinwg changes:
- Write stats are converted to metadata index records during the commit. Making them use the HoodieData type so that the record generation scales up with needs. 
- Metadata index init support for bloom filter and column stats partitions.
- When building the BloomFilter from the index records, using the type param stored in the payload instead of hardcoded type.
- Delta writes can change column ranges and the column stats index need to be properly updated with new ranges to be consistent with the table dataset. This fix add column stats index update support for the delta writes.
This pull request is a …
=> [HUDI-3258] HoodieData for metadata index records, bloom and colstats init

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SupportsUpgradeDowngrade.java
With some recent refactoring, SupportsUpgradeDowngrade throws Task not serializable exception. Making it extend Serializable in this patch. 
- Verified using integ test suite jobs which failed if not for this patch and succeeded with this patch.
=> [HUDI-3587] Making SupportsUpgradeDowngrade serializable

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieSchemaPostProcessException.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/ChainedSchemaPostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/DummySchemaPostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
…ulti processors at once
*Introduce ChainedSchemaPostProcessor to support setting multi schema processors*
org.apache.hudi.utilities.TestSchemaPostProcessor#testChainedSchemaPostProcessor
=> [HUDI-3568] Introduce ChainedSchemaPostProcessor to support setting multi processors at once

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala, hudi-common/src/test/resources/simple-test-doced.avsc, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroConversionUtils.scala, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/DDLExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HMSDDLExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/QueryBasedDDLExecutor.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
*The pr is syncing source table column comments to a hive table with syncing hudi to hive when users add column comments to datasource schema.*
- *Add a hive sync config(hoodie.datasource.hive_sync.sync_comment). This config is false by default.*
- *While syncing data source to hudi, add table column comments to datasource avro schema, and if the sync_comment is true, syncing column comments to the hive table.*
*(for example: using spark datasource)*
`StructType schema = new StructType().add("key", "string", false, "comment")`
`sparkSession.createDataFrame(rdd, schema)`
`.write().format("org.apache.hudi")`
`......`
`.option("hoodie.datasource.hive_sync.sync_comment","true")`
`......`
`.save("/xxxx");`
*Run TestHiveSyncTool#testUpdateTableComments and …
=> [HUDI-3383] Sync column comments while syncing a hive table, especially using spark datasource api

docker/README.md
This PR documents how we can build arm64 images. This is in relation to #4985 
*(or)*
(or)
*(example:)*
=> [HUDI-3602] Add steps to build multi-arch images using buildx

docker/demo/trino-batch1.commands, docker/demo/trino-batch2-after-compaction.commands, docker/demo/trino-table-check.commands, hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
This PR adds Trino Queries in integration tests.
- Adds Trino query execution in `ITTestHoodieDemo`
This change added integration tests around Trino in `ITTestHoodieDemo`.
=> [HUDI-3586] Add Trino Queries in integration tests

hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestParquetDFSSourceEmptyBatch.java
when Deltastreamer consumes an empty batch, but checkpoint moved ahead, hudi injects NullSchemaProvider as part of consumed InputBatch. Which returns null schema (Schema.create(Schema.Type.NULL)) schema when asked for source or target schema. So, this gets serialized into commit metadata and later runs into issues when table schema is fetched. 
Fix: when serializing the schema to commit metadata, we avoid adding the entry if its null schema (Schema.create(Schema.Type.NULL)).  
Ideally, we want to fix the schema provider returned as part of empty batch itself. But don't want to fix it right away as it could blow up somewhere else. So, created a [ticket](https://issues.apache.org/jira/browse/HUDI-3596) for later. 
TableSchemaProvider is capable of walking back to previous commits to find …
=> [HUDI-3595] Fixing NULL schema provider for empty batch

hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/DropColumnSchemaPostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
…olumns from schema
*Introduce DropColumnSchemaPostProcessor to support drop columns from schema*
org.apache.hudi.utilities.TestSchemaPostProcessor#testDeleteColumn
org.apache.hudi.utilities.TestSchemaPostProcessor#testDeleteColumnThrows
=> [HUDI-3522] Introduce DropColumnSchemaPostProcessor to support drop columns from schema

hudi-common/src/main/java/org/apache/hudi/common/util/CustomizedThreadFactory.java, hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryExecutor.java, hudi-common/src/test/java/org/apache/hudi/common/util/TestCustomizedThreadFactory.java
This pull request adds thread factory  in BoundedInMemoryExecutor.
Under the old code, we could not clearly distinguish the role of each thread in the thread dump during the data merging phase of the MOR table. So I added a CustomizedThreadFactory class. And added a thread pool factory name that can be used to identify the role of the thread for BoundedInMemoryExecutor.
*(or)*
This pull request is already covered by existing …
=> [HUDI-3566]add thread factory in BoundedInMemoryExecutor

hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
*Use standard test schema in our UT instead of a shema from a specific enterprise data*
This pull request is already covered by existing tests:
org.apache.hudi.utilities.TestSchemaPostProcessor
=> [HUDI-3575] Use HoodieTestDataGenerator#TRIP_SCHEMA as example schema in TestSchemaPostProcessor

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/columnstats/ColumnStatsIndexHelper.java
NOTE: This code will soon be cleaned up after HUDI-3514 lands
Make sure Column Stats does not fail in case it fails to load previous Index Table state.
See above
=> [HUDI-3513] Make sure Column Stats does not fail in case it fails to load previous Index Table state

hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestDefaultHoodieRecordPayload.java
HoodiePayloadProperty could be empty from the code: https://github.com/apache/hudi/blob/548000b0d635067acf7574c4cf5122759e79b52b/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala#L71
If we use DefaultHoodieRecordPayload, there could be NPE.
```java
at org.apache.hudi.avro.HoodieAvroUtils.getNestedFieldVal(HoodieAvroUtils.java:471)
at org.apache.hudi.common.model.DefaultHoodieRecordPayload.updateEventTime(DefaultHoodieRecordPayload.java:93)
at org.apache.hudi.common.model.DefaultHoodieRecordPayload.combineAndGetUpdateValue(DefaultHoodieRecordPayl …
```
=> [HUDI-3592] Fix NPE of DefaultHoodieRecordPayload if Property is empty

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/processor/ChainedJsonKafkaSourcePostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSourcePostProcessor.java
…etting multi processors at once
Introduce ChainedJsonKafkaSourePostProcessor to support setting multi processors at once
org.apache.hudi.utilities.sources.TestJsonKafkaSourcePostProcessor#testChainedJsonKafkaSourcePostProcessor
=> [HUDI-3569] Introduce ChainedJsonKafkaSourePostProcessor to support setting multi processors at one time

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
If clustering/compaction rollback failed mid-way, if rollback of a pending clustering/compaction is re-attempted, a new rollback instant will be generated. We would want to retry using the same rollback instant. Main motivation is that, the old failed rollback instant is never cleaned up. And so it could lead to liveness issues w/ metadata table. 
- Fixed rolling back of pending clustering/compaction to re-use rollback instant if present. 
- Added TestHoodieSparkMergeOnReadTableInsertUpdateDelete#testRepeatedRollbackOfCompaction
- Added TestHoodieClientOnCopyOnWriteStorage#testPendingClusteringRollback
=> [HUDI-3556] Re-use rollback instant for rolling back of clustering and compaction if rollback failed mid-way

hudi-common/src/main/java/org/apache/hudi/common/config/OrderedProperties.java, hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java, hudi-common/src/test/java/org/apache/hudi/common/properties/TestOrderedProperties.java, hudi-common/src/test/java/org/apache/hudi/common/properties/TestTypedProperties.java
`TypedProperties#keys` is not thread-safe. It was added in #4712 to ensure insertion order of properties is maintained. It was done in order to add a table checksum config in the end which would be used to validate that `hoodie.properties` is not written partially. However, TypedProperties not being thread-safe could result in ConcurrentModificationException as there are places in clustering where write config is passed to spark executor and it might happen that while one thread is trying to serialize it the other is trying to modify it. However, the solution to original problem need not depend on ordering. We can just add table checksum in the end and then while reading `hoodie.properties` just ensure that prop exists.
- Remove `TypedProperties#keys`
- Convert props to linked hashmap and …
=> [HUDI-3593] Restore TypedProperties and flush checksum in table config

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java
Today, in a production environment, when I use structuredStreaming to write to a MOR table, maybe for some reason there is a marker file under ./hoodie/temp/ but the data file doesn't exist. An exception will be thrown at this point, when I add the judgment, the task can run normally
=> [HUDI-3583] Fix MarkerBasedRollbackStrategy NoSuchElementException

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CreateSavepointsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteSavepointsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackSavepointsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowSavepointsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallCommandParser.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRunClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestSavepointsProcedure.scala
link: [HUDI-3501](https://issues.apache.org/jira/browse/HUDI-3501)
1. `create_savepoints`
2. `show_savepoints`
3. `delete_savepoints`
4. `rollback_savepoints`
*(or)*
(or)
*(example:)*
- …
=> [HUDI-3501] Support savepoints command based on Call Produce Command

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
- In continuous mode when async clustering is enabled, and if there is no new data to consume for the first time, deltastreamer throws NPE while trying to invoke clustering. bcoz, the writeClient itself is not initialized. 
- Fixed fetching of clustering instant in deltastreamer to return Option.empty if writeclient is not initialized. 
- Tested manually with local deltastreamer.
=> [HUDI-3621] Fixing NullPointerException in DeltaStreamer

docker/demo/config/test-suite/cow-spark-long-running.yaml, docker/demo/config/test-suite/cow-spark-simple.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml, docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml, docker/demo/config/test-suite/detlastreamer-long-running-example.yaml, docker/demo/config/test-suite/insert-overwrite-table.yaml, docker/demo/config/test-suite/insert-overwrite.yaml, docker/demo/config/test-suite/simple-clustering.yaml, docker/demo/config/test-suite/simple-deltastreamer.yaml, docker/demo/config/test-suite/spark-clustering.yaml
- Removing hive-sync nodes from spark validation yamls. We have separate yamls for hive validations and those are not touched in this patch.
=> [HUDI-3623] Removing hive sync node from non hive yamls

pom.xml
Adding spark3.2.0 profile and bundle to hudi.
- Updated root pom to add spark3.2.0 profile. 
- Verified manually with spark-shell with spark3.2.0-hadoop-3.2 jar. 
Command used to build the bundle "mvn clean package -DskipTests -Dspark3.2.0"
=> [HUDI-3620] Adding spark3.2.0 profile

packaging/hudi-timeline-server-bundle/pom.xml
This pull request adds `org.objenesis:objenesis` to hudi-timeline-server-bundle pom.
If not adding this dependency to bundle, hudi will occasionally encounter errors similar to the this.
```
2022-03-11 05:28:48,223 [qtp818093527-18] ERROR javalin.Javalin: Exception occurred while servicing http-request
java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy
at org.apache.hudi.common.util.SerializationUtils$KryoSerializerInstance.<init>(SerializationUtils.java:88)
at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source)
at java.base/java.lang.ThreadLocal.setInitialValue(Unknown Source) …
```
=> [HUDI-3606] Add `org.objenesis:objenesis` to hudi-timeline-server-bundle pom

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieOperation.java
https://issues.apache.org/jira/browse/HUDI-3619
Fix HoodieOperation fromValue using wrong constant value.
Fix HoodieOperation fromValue using wrong constant value.
Fix HoodieOperation fromValue using wrong constant value.
=> [HUDI-3619] Fix HoodieOperation fromValue using wrong constant value

hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java, hudi-common/src/test/java/org/apache/hudi/common/properties/TestTypedProperties.java
`TypedProperties` invokes `Properties#stringPropertynames()` which expects that key and values should be strings. It causes keys with non-string values to be not found. See #5026 . This PR fixes that behavior.
*(or)*
(or)
*(example:)*
=> [HUDI-3633] Allow non-string values to be set in TypedProperties

hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java
=> [HUDI-3589] flink sync hive metadata supports table properties and serde properties

docker/compose/docker-compose_hadoop284_hive233_spark244.yml, docker/hoodie/hadoop/pom.xml, docker/hoodie/hadoop/prestobase/Dockerfile
The latest master of Presto relies on hudi-presto-bundle, while current Presto releases rely on hudi-common and hudi-hadoop-mr 0.9.0, which are pulled in plugin/hive-hadoop2/ in the Docker setup, making it hard to test the latest changes in Hudi due to class conflict.
As a temporary workaround, this PR removes `hudi-common-0.9.0.jar` and `hudi-hadoop-mr-0.9.0.jar` in `plugin/hive-hadoop2/` to avoid conflicts with latest hudi-presto-bundle.jar, which is copied from the build.  This PR also upgrades Presto to 0.271, so that the new presto docker image is pushed to `apachehudi/hudi-hadoop_2.8.4-prestobase_0.271:latest`.  In this way, if there is any issue with the changes in this PR, we can roll this back without any side effect.
- Removes `hudi-common-0.9.0.jar` and …
=> [HUDI-3588] Remove hudi-common and hudi-hadoop-mr jars in Presto Docker image

hudi-flink/pom.xml, hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java, hudi-flink/src/main/java/org/apache/hudi/util/FlinkStateBackendConverter.java
Now, HoodieFlinkStreamer utility only support one backend - FsStateBackend.
I think it's not flexible for the application configuration. Could we make backend configurable?
Moreover, for flink version 1.14, FsStateBackend is deprecated in favor of org.apache.flink.runtime.state.hashmap.HashMapStateBackend and org.apache.flink.runtime.state.storage.FileSystemCheckpointStorage.
*(or)*
This pull request is already covered by …
=> [HUDI-3607] Support backend switch in HoodieFlinkStreamer

website/blog/2021-08-18-improving-marker-mechanism.md, website/blog/2021-08-23-s3-events-source.md, website/blog/2021-09-01-building-eb-level-data-lake-using-hudi-at-bytedance.md, website/blog/2021-12-16-lakehouse-concurrency-control-are-we-too-optimistic.md, website/blog/2022-01-06-apache-hudi-2021-a-year-in-review.md, website/blog/2022-01-14-change-data-capture-with-debezium-and-apache-hudi.md, website/docusaurus.config.js, website/src/css/custom.css, website/src/theme/BlogLayout/index.js, website/src/theme/BlogPostItem/index.js, website/src/theme/BlogPostItem/styles.module.css
*As discussed with Kyle and Vinoth, redesigned the blog page with grid layout.*
I don't want to block the development, hence split the work into two phases:
1. Redesigned the blog page in the grid layout. (this PR covers this work)
2. Add source text in the blog then merge the blog page with the talks and articles page.
I have added few images to the blog post, to add images, update each and every blog post with the image property in the header of the blog, for example, to add the image for this blog update this file with the following text:
website/blog/2021-08-18-improving-marker-mechanism.md
image: /assets/images/blog/marker-mechanism/timeline-server-based-marker-mechanism.png
- *Redesigned the blog page with grid layout*
This pull …
=> [DOCS] Redesigned the blog page with grid layout

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
https://issues.apache.org/jira/browse/HUDI-3376
add an option named `--skip-data-files-for-cleaning` which will skip to compare the data files which are under deletion by cleaner
When enabled, HoodieMetadataTableValidator will read the clean plan for pending cleaning action and get under deletion data files. Then hoodie will skip to compare these files.
This patch is tested on our local env.
There 're pending cleaning actions during performing HoodieMetadataTableValidator.
Before this patch validator failed with 
```
4257 [Executor task launch worker for task 1] INFO  org.apache.hudi.utilities.HoodieMetadataTableValidator  - Validation of getLatestBaseFiles succeeded for partition 20210623
4258 [Executor task launch worker for task 1] ERROR …
```
=> [Hudi-3376] Add an option to skip under deletion files for HoodieMetadataTableValidator

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
This PR adds logic to automatically adjust write configs based on metadata table enablement and write concurrency mode, to prevent possible missing configs that are required for enabling metadata table and multi-writer.  Write configs in scope are:
```
hoodie.metadata.enable (read-only in the new logic)
hoodie.write.concurrency.mode (can be auto updated in the new logic)
hoodie.write.lock.provider (can be auto updated in the new logic)
hoodie.cleaner.policy.failed.writes (can be auto updated in the new logic)
```
The following scenarios are checked:
| Metadata Table | Async Table Services | Lock Provider Set by User | Action |
| ----------- | ----------- | ----------- | ----------- |
| Enabled      | Enabled     |  No | Set `hoodie.write.concurrency.mode=optimistic_concurrency_control`, …
=> [HUDI-3404] Automatically adjust write configs based on metadata table and write concurrency mode

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java, hudi-common/src/main/java/org/apache/hudi/common/util/CompactionUtils.java, hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java
For Hudi MOR table, the scheduling of compaction is triggered under certain conditions, configured by `hoodie.compact.inline.trigger.strategy`.  The default triggering condition is the number of delta commits, with the config of `hoodie.compact.inline.max.delta.commits`.  If this setting is larger than the archival config of `hoodie.keep.max.commits`, there is not enough delta commits in the active timeline and the compaction will never happen.
To guard around such configs, for MOR table with triggering strategy of `NUM_COMMITS` (trigger compaction when reach N delta commits) and `NUM_AND_TIME` (trigger compaction when both NUM_COMMITS and TIME_ELAPSED are satisfied), the archival always makes sure that there are enough delta commits in the active timeline to trigger compaction …
=> [HUDI-3494] Consider triggering condition of MOR compaction during archival

hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
…o adjust the number of parallelism
*(or)*
(or)
*(example:)*
=> [HUDI-3598] Row Data to Hoodie Record Operator parallelism needs to always be consistent with input operator     for chaining purpose

docker/demo/config/test-suite/cow-spark-long-running.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-hive.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml, docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml, docker/demo/config/test-suite/detlastreamer-long-running-example.yaml, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseValidateDatasetNode.java
=> [HUDI-3659] Reducing the validation frequency for integ test yamls

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieCommonUtils.scala, hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieConversionUtils.scala, hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala, hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java, hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyViewRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieDataSourceHelper.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileScanRDD.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/HoodieHadoopFSUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/execution/datasources/HoodieInMemoryFileIndex.scala, hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/TestHoodieInMemoryFileIndex.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
NOTE: This PR is stacked on top of #4818
Refactoring Spark DataSource Relations to avoid code duplication. Following Relations were in scope:
- `BaseFileOnlyViewRelation`
- `MergeOnReadSnapshotRelaation`
- `MergeOnReadIncrementalRelation`
See above
=> [HUDI-3457] Refactored Spark DataSource Relations to avoid code duplication

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java, hudi-common/src/main/java/org/apache/hudi/common/util/Option.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Currently, Column Stats is not able to properly index first commit in the table b/c it uses `TableSchemaResolver`, which is not able to fetch schema for empty tables.
Instead, we should leverage writer's schema provided w/in `HoodieCommitMetadata`
Fixing Column Stats index to properly handle first Data Table commit
See above 
=> [HUDI-3663] Fixing Column Stats index to properly handle first Data Table commit

hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystem.java
This PR removes the assert of `FileStatus::getAccessTime` which is flaky on rare occasions (the difference is in ms as shown below), since the access time can be changed when reading the file to get the file status for the expected and actual.  This only affects `testReadInlineFile()`.
```
[ERROR] org.apache.hudi.common.fs.inline.TestInLineFileSystem.testReadInlineFile
[ERROR]   Run 1: TestInLineFileSystem.testReadInlineFile:110->verifyFileStatus:372 expected: <1647752030224> but was: <1647752030244>
[ERROR]   Run 2: TestInLineFileSystem.testReadInlineFile:110->verifyFileStatus:372 expected: <1647752042953> but was: <1647752042973>
[ERROR]   Run 3: TestInLineFileSystem.testReadInlineFile:110->verifyFileStatus:372 expected: <1647752043009> but was: <1647752043029>
[ERROR]   Run 4: …
```
=> [MINOR] Remove flaky assert in TestInLineFileSystem

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/TwoToThreeUpgradeHandler.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestTwoToThreeUpgradeHandler.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaSortAndSizeExecutionStrategy.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
By default, for Deltastreamer and Spark datasource, if the key generator class is not configured by the user, the `SimpleKeyGenerator` is used by default.  However, the table upgrade from v2 to v3 still expects explicit key generator class config for Spark and fails if not set.  This PR sets the key generator class to `org.apache.hudi.keygen.SimpleKeyGenerator` for Spark client if it is not set in the write configs, so that the table upgrade can succeed without the following validation error.
```
22/03/14 12:28:10 ERROR HoodieDeltaStreamer: Shutting down delta-sync due to exception
java.lang.IllegalStateException: Missing config: Key: 'hoodie.table.keygenerator.class' , default: null description: Key Generator class property for the hoodie table since version: version is not defined …
```
=> [HUDI-3640] Set SimpleKeyGenerator as default in 2to3 table upgrade for Spark engine

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/ConcurrentOperation.java, hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
`REPLACE_COMMIT_ACTION` is used for different write operations like clustering, insert_overwrite or insert_overwrite_table. However, there is a difference between whether requested/inflight replace commit metadata has any content or not depending on the write operation. This PR attempts to fix that and avoid NPE due to empty replacecommit metadata. We should ideally have a standard for replacecommit metadata as pointed out in HUDI-1739.
*(or)*
(or) …
=> [HUDI-3642] Handle NPE due to empty requested replacecommit metadata

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
=> [minor] Checks the data block type for archived timeline

hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamerWithMultiWriter.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieMultiTableDeltaStreamer.java
This PR fixes some of the deltastreamer tests in order to stabilize the CI
- Remove glob pattern basePath from the deltastreamer tests.
- Ensure correct partition fields are set in hive sync config.
- Disable jdbc source test.
*(or)*
(or)
*(example:)*
=> [HUDI-3689] Fix glob path and hive sync in deltastreamer tests

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java, hudi-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Addresses NPE in `ParquetUtils` not handling `null` min/max statistics
- Addressed NPE
- Tidying up
=> [HUDI-3684] Fixing NPE in `ParquetUtils`

azure-pipelines.yml
The cache task does not make mvn install faster, removing it.
=> [HUDI-3689] Remove Azure CI cache

pom.xml
#5120 upgrades maven-surefire-plugin.version from 3.0.0-M4 to 3.0.0-M5 and skips some tests.  We need to bring the old version back and run through the tests.
As above.
=> [HUDI-3706] Downgrade maven surefire and failsafe version

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieMultiTableDeltaStreamer.java
Fix testcases in 
-TestHoodieMultiTableDeltaStreamer
- testCsvDFSSourceNoHeaderWithoutSchemaProviderAndNoTransformer
- testParquetDFSSourceWithoutSchemaProviderAndTransformer
Disable test cases with both schema provider and transfomer in TestHoodieDeltaStreamer
Disable flaky testDeletePartitions
=> [HUDI-3689] Fix delta streamer tests

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Two flaky tests in TestHoodieDeltaStreamer are disabled in this PR to unblock CI:
```
testHoodieAsyncClusteringJob (follow-up: HUDI-3710)
testParquetDFSSourceWithoutSchemaProviderAndTransformer (follow-up: HUDI-3707)
```
=> [HUDI-3689] Disable flaky tests in TestHoodieDeltaStreamer

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
This PR addresses the failure of retried clean action under the following scenario:
```
(1) C5.clean.requested in data table
(2) C5.clean.inflight in data table
(3) Apply changes to metadata table
(4) C5.deltacommit.requested and C5.deltacommit.inflight in metadata table
(5) Job crashes
(6) Restart the job to rerun the same clean action C5
```
The following exception is thrown:
```
19747 [main] WARN  org.apache.hudi.table.action.clean.CleanActionExecutor  - Failed to perform previous clean operation, instant: [==>00000000000005__clean__INFLIGHT]
org.apache.hudi.exception.HoodieIOException: Failed to create file /var/folders/60/wk8qzx310fd32b2dp7mhzvdc0000gn/T/junit94869438059871451/dataset/.hoodie/metadata/.hoodie/00000000000005.deltacommit.requested
at …
```
=> [HUDI-3624] Check all instants before starting a commit in metadata table

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
This PR makes ZookeeperBasedLockProvider serializable so that clean action does not complain about `Task not serializable` due to ZookeeperBasedLockProvider or CuratorFramework.
As above.
This PR is verified by running deltastreamer continuous mode writing to a COW table, with async clustering and cleaner enabled, using ZooKeeper as the lock provider.  Before this change, the job encounters `Task not serializable` exception.  After this change, the job proceeds without any issue.
=> [HUDI-3638] Make ZookeeperBasedLockProvider serializable

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/WriterHelpers.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkStateBackendConverter.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
=> [HUDI-3701] Flink bulk_insert support bucket hash index

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
=> [HUDI-3703] Reset taskID in restoreWriteMetadata

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/columnstats/ColumnStatsIndexHelper.java, hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystExpressionUtils.scala, hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/HoodieSparkTypeUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/HoodieCatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/Spark3Adapter.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark3_1CatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_1Adapter.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/HoodieSpark3_2CatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/adapter/Spark3_2Adapter.scala
Supporting Composite Expressions (including standard Spark functions and UDFs) as Filter Expressions in Data Skipping flow.
For example, if previously we were only supporting rather simple expressions over Data Table attributes like `WHERE columnA = 42`, now we will be supporting much broader scope of expressions (strictly defined below) allowing for example Data Skipping to properly digest queries like `WHERE date_format(columnA, 'MM/dd/yyyy') = '01/01/2022'` referencing Spark's standard function `date_format`.
Formally, now supported are any expressions such that it
1. References exactly 1 attribute (column, meaning that …
=> [HUDI-3594] Supporting Composite Expressions over Data Table Columns in Data Skipping flow

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieDataSourceHelper.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileScanRDD.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieUnsafeRDD.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/HoodieUnsafeRDDUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Refactoring `MergeOnReadRDD` to 
- Avoid duplication
- Enable optimization to avoid reading base-file with full-schema, fetching only projected columns
- Unified MOR record iteration logic w/in 3 iterators extending each other
- Added optimization to consider whether a) virtual keys are used and b) whether non-default RecordPayload class is used to determine whether we can do projected read from base-file instead of full-schema one
=> [HUDI-3396] Refactoring `MergeOnReadRDD` to avoid duplication, fetch only projected columns

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieOrcWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieParquetWriter.java, hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieInternalRowParquetWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
Currently writing t/h Spark DataSource connector, does not respect "hoodie.parquet.max.file.size" setting: in the snippet pasted below i'm trying to limit the file-size to 16Mb, while on disk i'm getting ~80Mb files.
The reason for that is that we rely on `ParquetWriter` to control the file size (`canWrite` method), that relies in turn on FileSystem to trace how much was actually written to FS.
The problem with this approach is that `ParquetWriter` is writing lazily: It creates instances of `ParquetWriter` which in turn cache the whole record group when `write` methods are invoked and only flushes the data to FS only when closing …
=> [HUDI-3709] Fixing `ParquetWriter` impls not respecting Parquet Max File Size limit

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRollbacksCommand.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/CopyOnWriteRollbackActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MergeOnReadRollbackActionExecutor.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestCopyOnWriteRollbackActionExecutor.java
Before this change, the sequence of changes in the rollback action are:
(1) Get the instant (C1) to roll back.  If there is already a pending rollback (RB_C1) for the same instant (C1) in the active timeline, the same rollback instant (RB_C1) and the rollback plan are reused.  Otherwise, schedule a new rollback instant.
(2) Transition C1 to inflight if completed.
(3) Delete data files written by C1.
(4) Delete instant files (C1) in the data table timeline.
(5) Commit changes from the rollback (RB_C1) to metadata table
(6) Transition the rollback instant (RB_C1) from inflight to complete on data table timeline.
By design, we should only change data table timeline after committing the changes to the metadata table.  This PR changes the order of timeline changes as below, switching the order …
=> [HUDI-3604] Adjust the order of timeline changes in rollbacks

hudi-common/src/main/java/org/apache/hudi/common/util/ParquetReaderIterator.java, hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieParquetReader.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
We were running integration tests against hudi and in recent times we are seeing "too many open files" and the spark long running COW tests fails. Looks like we don't close the parquet reader in couple of places. Fixing the closure in this patch. 
*(or)*
(or)
*(example:)*
=> [HUDI-3724] Fixing closure of ParquetReader

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionHoodiePathCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionShowHoodiePathCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionShowHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedureUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCompactionProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCompactionProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCompactionProcedure.scala
Supporting compaction command for Spark SQL, so that we can manually trigger/show compaction by call procedure command:
```
call run_compaction( 'schedule', 'test')
call run_compaction(op => 'schedule', table => 'test')
call run_compaction(op => 'schedule', path => './dataset/test')
...
call run_compaction('run', 'test')
call run_compaction(op => 'run', table => 'test')
call run_compaction(op => 'schedule', path => './dataset/test', timestamp => '20220314175600')
...
````
- *Add RunCompactionProcedure and ShowCompactionProcedure*
- *Add test case in TestCallProcedure*
*(or)*
This pull request is already covered by existing tests, such as *(please describe …
=> [HUDI-3538] Support Compaction Command Based on Call Procedure Command for Spark SQL

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
Optimization for bootstrap when use flink bucket index.  Load and cache the filegroups info of a partition which poccessing the records belong to instead of loading all partitions at first.
- BucketStreamWriteFunction
=> [HUDI-3539] Flink bucket index bucketID bootstrap optimization.

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestClientRollback.java
When reattempting a pending rollback and the instant to rollback does not exist in the active timeline anymore due to a failure just before the rollback was transitioned from inflight to complete, such rollback cannot successfully be completed.   This PR fixes the logic so that in such case the rollback can be reattempted successfully.
- Changes how the rollback is executed in different scenarios in `BaseHoodieWriteClient`.
- Adds unit tests in `TestClientRollback`.
This change added tests in `TestClientRollback` and is verified as follows:
- Run deltastreamer continuous mode writing MOR table.  Fail the deltastreamer and a rollback before markers are deleted or just before the rollback is transitioned from inflight to complete.  Rerun the deltastreamer.  Verified that the same rollback …
=> [HUDI-3720] Fix the logic of reattempting pending rollback

hudi-aws/pom.xml, hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogClient.java, hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java, hudi-aws/src/main/java/org/apache/hudi/aws/sync/AwsGlueCatalogSyncTool.java, hudi-aws/src/main/java/org/apache/hudi/aws/sync/HoodieGlueSyncException.java, hudi-aws/src/main/java/org/apache/hudi/aws/utils/S3Utils.java, hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java, hudi-common/src/main/java/org/apache/hudi/common/util/MapUtils.java, hudi-common/src/test/java/org/apache/hudi/common/util/TestCollectionUtils.java, hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectTransactionServices.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/DLASyncTool.java, hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/HoodieDLAClient.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/AbstractHiveSyncHoodieClient.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncException.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/DDLExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/GlobalHiveSyncTool.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/AbstractSyncHoodieClient.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/model/Partition.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/TableUtils.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Add AWS Glue sync implementation to allow sync to AWS Glue catalog directly via AWS SDK APIs.
=> [HUDI-2757] Implement Hudi AWS Glue sync

docker/compose/docker-compose_hadoop284_hive233_spark244.yml, docker/demo/config/test-suite/multi-writer-1-ds.yaml, docker/demo/config/test-suite/multi-writer-1.properties, docker/demo/config/test-suite/multi-writer-2-sds.yaml, docker/demo/config/test-suite/multi-writer-2.properties, docker/demo/config/test-suite/multi-writer-local-1.properties, docker/demo/config/test-suite/multi-writer-local-2.properties, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieMultiWriterTestSuiteJob.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DFSDeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/WriterContext.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/DeleteNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/InsertNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/UpsertNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/DeltaGenerator.java, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkBulkInsertNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkDeleteNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkUpsertNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/spark/sql/BaseSparkSqlNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/spark/sql/SparkSqlCreateTableNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/spark/sql/SparkSqlDeleteNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/spark/sql/SparkSqlMergeNode.scala, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/spark/sql/SparkSqlUpdateNode.scala, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestDFSHoodieTestSuiteWriterAdapter.java, pom.xml
- Added multi-writer test support to integ test framework. With this support, two jobs can concurrently run (1 deltastreamer and 1 spark datasource ) writing to same hudi table. Each job will do localized validation (for the data ingested by self). 
- Added a new job called HoodieMultiWriterTestSuiteJob, which can be used to trigger multiple concurrent jobs. 
- Fixed sparkdatasource test nodes integ test to de-couple from deltastreamer checkpointing. 
- Added properties and yamls for multi-writer tests 
- Verified by running a job locally
```
spark-submit --packages org.apache.spark:spark-avro_2.11:2.4.0 --conf spark.task.cpus=3 --conf spark.executor.cores=3 --conf spark.task.maxFailures=100 --conf spark.memory.fraction=0.4  --conf spark.rdd.compress=true  --conf …
```
=> [HUDI-2566] Adding multi-writer test support to integ test

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableDropPartitionCommand.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/TruncateHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTruncateTable.scala
when truncate partition table，neither metadata nor data is truncated and truncate partition table with partition specs fails 
```
// truncate partition table without partition spec, the query is success but never delete data
spark-sql> truncate table mor_partition_table_0314;
Time taken: 0.256 seconds
```
```
// truncate partition table with partition spec, 
spark-sql> truncate table mor_partition_table_0314 partition(dt=3);
Error in query: Table spark_catalog.default.mor_partition_table_0314 does not support partition management.;
'TruncatePartition unresolvedpartitionspec((dt,3), None)
+- ResolvedTable …
```
=> [HUDI-3722] Fix truncate hudi table's error

hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
The config has a bad default value which prevent to turn it to null and lead to a NPE when no endpoint_url is specified.
This PR removes the default value
fixes #4904
=> [HUDI-3736] Fix default dynamodblock url default value

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala
In `TestDataSkippingUtils`, we are instantiating [Timestamp](https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html#Timestamp-long-) which expects milliseconds since January 1, 1970, 00:00:00 GMT. The time given in the test translates to 7th March in GMT but date in filter expression is an earlier one so the test fails. This PR fixes that.
*(or)*
(or)
*(example:)*
- *Added …
=> [MINOR] Fix dates as per UTC in TestDataSkippingUtils

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Please refer https://issues.apache.org/jira/browse/HUDI-3647 for more details.
*(or)*
(or)
*(example:)*
=> [HUDI-3647]HoodieMetadataTableValidator: check MDT was initialized at first

hudi-sync/hudi-datahub-sync/pom.xml, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/HoodieDataHubSyncException.java, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubEmitterSupplier.java, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java, hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestDataHubSyncConfig.java, hudi-sync/hudi-datahub-sync/src/test/resources/log4j-surefire-quiet.properties, hudi-sync/hudi-datahub-sync/src/test/resources/log4j-surefire.properties, hudi-sync/pom.xml, packaging/hudi-datahub-sync-bundle/pom.xml, packaging/hudi-datahub-sync-bundle/src/main/java/org/apache/hudi/datahub/bundle/Main.java, packaging/hudi-utilities-bundle/pom.xml, pom.xml
Add MVP implementation for `hudi-datahub-sync` to sync table schema as a DataHub Dataset. See https://datahubproject.io/docs/generated/metamodel/entities/dataset
=> [HUDI-3536] Add hudi-datahub-sync implementation

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
…stion writers using SpakAllowUpdateStrategy
fix the issue of https://issues.apache.org/jira/browse/HUDI-3355
.
*(or)*
(or)
*(example:)*
=> [HUDI-3355] Issue with out of order commits in the timeline when ingestion writers using SparkAllowUpdateStrategy

.github/workflows/bot.yml, README.md, pom.xml
To follow the updated model of compatibility with Spark, we need to provision additional Hudi Spark bundles as part of the 0.11 release referencing Spark minor version in the bundle name, "spark3.1", "spark3.2", "spark2.4".  Aliases are also created for backward compatibility.  Specifically,
| Label | Artifact Name | Maven Profile Option | Notes |
|--|--|--|--|
| Spark 2.4, Scala 2.11  | hudi-spark2.4-bundle_2.11 | `-Pspark2.4` | For Spark 2.4.4, which is the same as the default  |
| Spark 2.4, Scala 2.12 | hudi-spark2.4-bundle_2.12 | `-Pspark2.4,scala-2.12` | For Spark 2.4.4, which is the same as the default and Scala 2.12 |
| Spark 3.1, Scala 2.12 | hudi-spark3.1-bundle_2.12 | `-Pspark3.1` | For Spark 3.1.x |
| Spark 3.2, Scala 2.12 | hudi-spark3.2-bundle_2.12 | `-Pspark3.2` | For Spark …
=> [HUDI-3681] Provision additional hudi-spark-bundle with different versions

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
There was a clash between the commit time("001","002") and random fileId generated. So, when we validate that there are not base files with commit time "002", if could return a file which has random UUID part matched. 
*(or)*
(or)
*(example:)*
=> [MINOR] Fixing flakiness in TestHoodieSparkMergeOnReadTableRollback.testRollbackWithDeltaAndCompactionCommit

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
fix npc when spark read table which is init by flink.
configuration **hoodie.datasource.write.partitionpath.field (unpartitioned table)** will not write into hoodie.properties
*(or)*
(or)
*(example:)*
- *Added HoodieClientWriteTest to …
=> [HUDI-3750] Fix NPE when build HoodieFileIndex

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
When multi-writers are involved, archival fails w/ NullPointerException. Hence guarding with locks. 
- Fix HoodieTimelineArchiver to lock during archiving. Instants to be archived has to be guarded across multiple writers and until archiving is complete, we can't give up the lock. 
*(or)*
(or)
*(example:)*
=> [HUDI-3713] Guarding archival for multi-writer 

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
Fix lost log write when there is inflight compaction.
Include compaction instant when constructing `HoodieMetadataFileSystemView`, which is consistent with `HoodieTableFileSystemView`.
- A test case is provided to verify the fix.
=> [HUDI-3692] Fix lost log writes during async compaction when using metadata table

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
Adding HoodieFailedWritesCleaningPolicy for restore with hudi-cli
- Adding HoodieFailedWritesCleaningPolicy for restore with hudi-cli. Adding an argument to savepoint_rollback
- Verified the fix locally with hudi-cli
=> [HUDI-3733] Adding HoodieFailedWritesCleaningPolicy for restore with hudi-cli

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
- During rollback, we have a validation that only latest commit should be rolledback. Or the commit being rollbacked should be the latest one. If there was a pending clustering instant, our validation was failing. So, fixed the case in this patch. 
- Also, during restore, at the end, cleaning up completed rollback got missed. Fixed the same here. 
- Fixed Rollback validation to ignore pending clustering
- Fixed restore to clean up completed rollback instant as well.
- Added tests to TestHoodieClientOnCopyOnWriteStorage.testRolblackOfRegularCommitWithPendingReplaceCommitInTimeline
- Manually tested the restore w/ hudi-cli.
=> [HUDI-3732] Fixing rollback validation

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/hudi/benchmark/HoodieBenchmarkBase.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/CowTableReadBenchmark.scala
… parquet file
*(or)*
(or)
*(example:)*
=> [HUDI-3729][SPARK] fixed the per regression by enable vectorizeReader for parquet file

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
In order to drop any metadata partition (index), we can reuse the DELETE_PARTITION operation in metadata table. Subsequent to this, we can support drop index (with table config update) for async metadata indexer.
- Add a new API in `HoodieTableMetadataWriter`
- Current only supported for Spark metadata writer
Added a unit test in TestHoodieBackedMetadata, which creates multiple metadata partitions and then drops one. Asserted that there are no file slice from the dropped partition.
=> [HUDI-3743] Support DELETE_PARTITION for metadata table

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkWriteHelper.java, hudi-common/src/main/java/org/apache/hudi/common/model/DeleteRecord.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroPayload.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordPayload.java, hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java, hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java, hudi-common/src/main/java/org/apache/hudi/common/util/SpillableMapUtils.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMergedLogRecordReader.java, hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestGlobalDeleteRecordGenerator.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
=> [HUDI-2752] The MOR DELETE block breaks the event time sequence of CDC

hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
If we enable point look ups for Hfile in MDT(hoodie.metadata.enable.full.scan.log.files), it fails w/ class not found. Check the linked jira for details. We did test out inline FS before. but one of the commit overwrote it. 
Commit where this was flipped: https://github.com/apache/hudi/pull/4333/files#r840216398
So, this patch fixes the hadoop conf for inline FS. 
Fixed hadoop conf for inline FS. 
- Verified quick start guide works w/ local FS and S3.
=> [HUDI-3763] Fixing hadoop conf class loading for inline reading

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
Before this change, `hoodie.bloom.index.parallelism` is used as the parallelism for generating bloom filter index in metadata table.  Since the default value of the config is 0, when generating the metadata bloom filter records, the method below always uses parallelism as 1, which does not work well for large batch ingestion.  The reason why it has default of 0 is that in the non-metadata-table bloom filter flow, the parallelism can be automatically figured out based on the shuffle parallelism.
`HoodieTableMetadataUtil.convertMetadataToBloomFilterRecords()`:
```
final int parallelism = Math.max(Math.min(allWriteStats.size(), recordsGenerationParams.getBloomIndexParallelism()), 1);
HoodieData<HoodieWriteStat> allWriteStatsRDD = context.parallelize(allWriteStats, parallelism);
return …
```
=> [HUDI-3773] Fix parallelism used for metadata table bloom filter index

hudi-common/src/main/avro/HoodieMetadata.avsc
This PR fixes the schema validation failure due to newly added field in #4948.  The failure happens when the table is written by a 0.11.0-SNAPSHOT release before that change with metadata table enabled, and later written with an updated 0.11.0-SNAPSHOT release using the new schema.  The failure is due to no default value set for the field.
- Adds default value in the avro schema.
Tested locally and in staging that the schema compatibility check can pass.
=> [HUDI-3708] Fix failure with HoodieMetadataRecord due to schema compatibility check

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToFourUpgradeHandler.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
When the write client disables metadata table, the metadata table becomes out-of-sync after new commits.  This PR adds the logic to delete the metadata table when the write client disables metadata table updates.  The new deletion logic is only invoked if `hoodie.metadata.enable` in write config is false, and `hoodie.table.metadata.partitions` is either absent or non-empty, indicating that the metadata table might exist.  Note that the user should wait for the metadata table to be fully deleted before re-enabling metadata table on the write side.
- Adds logic in `HoodieTable` for deleting metadata table
- Invokes the metadata table deletion upon getting metadata writer when metadata table is disabled.
This change adds new tests in TestHoodieBackedMetadata to validate the flow of disabling …
=> [HUDI-3451] Delete metadata table when the write client disables MDT

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
Currently, BloomIndex tries to rely solely on Column Stats to lookup records locations. This is however incorrect, since CS state might not be complete at any given moment; instead we should use it on the basis of best effort (not assuming that it would have any record at all), and for those files that are not found in ColStats we should list from them directly.
*(or)*
(or)
*(example:)*
- *Added …
=> [HUDI-3776] Fix BloomIndex incorrectly using ColStats to lookup record location

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala, hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
- Added a new config named AutoAdjustLockConfigs in HoodieWriteConfig which will be enabled only for deltastreamer and streaming sink flow. We enable InProcessLockProvider automatically if user has not configured one on certain conditions. 
- Introduced a new config to guard auto adjust lock configs. Explicitly enabled for deltastreamer and streaming sink flow. 
- Fixed DeltaStreamer to explicitly set table type in writeConfig. 
- Added tests to TestHoodieWriteConfig. 
- Tested Deltastreamer locally for MOR w/ async compaction and ensured auto adjustment kicks in.
=> [HUDI-3772] Fixing auto adjustment of lock configs for deltastreamer

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
This PR addresses one minor comment in #5186:
> Can we reuse HoodieTableMetadataUtil#deleteMetadataTable or refactor existing/add another method in util?
- Reuses HoodieTableMetadataUtil#deleteMetadataTable when deleting metadata table in `HoodieTable`
=> [MINOR] Reuse deleteMetadataTable for disabling metadata table

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableDropPartitionCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java, hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/HoodieDLAClient.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/AbstractSyncHoodieClient.java
=> [HUDI-3780] improve drop partitions

hudi-examples/hudi-examples-dbt/.gitignore, hudi-examples/hudi-examples-dbt/README.md, hudi-examples/hudi-examples-dbt/dbt_project.yml, hudi-examples/hudi-examples-dbt/models/example/hudi_insert_overwrite_table.sql, hudi-examples/hudi-examples-dbt/models/example/hudi_insert_table.sql, hudi-examples/hudi-examples-dbt/models/example/hudi_upsert_partitioned_cow_table.sql, hudi-examples/hudi-examples-dbt/models/example/hudi_upsert_partitioned_mor_table.sql, hudi-examples/hudi-examples-dbt/models/example/hudi_upsert_table.sql, hudi-examples/hudi-examples-dbt/models/example/schema.yml
This PR demonstrates hudi integration with dbt, it has a few models to demonstrate the different ways in which you can create hudi datasets using dbt.
- *Example dbt models to demonstrate how to use hudi with dbt*
- *Follow the instructions described in the readme.md file in this PR.
=> [HUDI-2319] dbt example models to demonstrate hudi dbt integration

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
Fix HUDI-3782
Now that we have table configs for inflight and completed metadata partitions, and given that both reader and writer are going to rely on this config, we need to ensure that this config is updated properly even when any one of the metadata indexes is enabled/disabled.
For instance, let's say user started with metadata enabled and colstats enabed. Colstats partition was fully built and the table config got updated. Now, they disable it and we miss to update table config. So the writers won't update the colstats partition and it would be out of sync. Readers think that the table config has it so it's already in sync but that's incorrect. This patch fixes this issue.
- Determine whether there is a need to delete MDT partition if any index config is disabled.
- Determine whether …
=> [HUDI-3782] Fixing table config when any of the index is disabled

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java
- During compaction, updates are present in logs, where as those records that are not updated are in base files. With compaction and preserving commit metadata, we did fix the code path for records that are updated, but those from previous base files were not fixed for file names. Infact, we had this inconsistency even before adding support for preserve commit metadata. i.e. with 0.9.0, after compaction, some records will have meta fields untouched (from previous base file), but those from logs will have all meta files re-written. We are fixing that w/ this patch.
- Fixing HoodieMergeHandle to fix preserve commit metadata for untouched records from previous base file.
- Verified manually. 
before fix
```
spark.sql("select _hoodie_file_name, count(*) from hudi_trips_snapshot  where …
```
=> [HUDI-3800] Fixed preserve commit metadata for compaction for untouched records

scripts/release/deploy_staging_jars.sh
Make `scripts/release/deploy_staging_jars.sh` to handle different build profiles for scala, spark and flink.
=> [HUDI-3340] Fix deploy_staging_jars for different profiles

hudi-client/hudi-flink-client/pom.xml, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/parquet/ParquetSchemaConverter.java, hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/io/storage/row/parquet/TestParquetSchemaConverter.java, hudi-flink-datasource/hudi-flink/pom.xml, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, packaging/hudi-flink-bundle/pom.xml, pom.xml
=> [HUDI-3808] Flink bulk_insert timestamp(3) can not be read by Spark

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroSchemaConverter.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataToAvroConverters.java
now,  flink will write decimalType as byte[]
when spark read that decimal Type, if spark find the precision of current decimal is small spark treat it as int/long which caused the  errors
test step：
step1：create a hive table which contains decimalType
create table hivetb_numeric(id int, c1 tinyint, c2 smallint, c3 int, c4 bigint, c5 float, c6 double, c7 decimal(10,4), c8 binary) using parquet; insert into hivetb_numeric values (1,10,15,100,1230000,56.32,1123.45678,4545.1234,'5'),(2,11,16,101,1230001,57.43,1124.4578,4556.134,'6'),(3,12,17,102,1230002,58.54,1125.459,4565.1445,'7');
step2：run flink job
CREATE TABLE hudi_batch_cow( id …
=> [HUDI-3096] fixed the bug that the cow table(contains decimalType) wriite by flink cannot be read by spark.

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieHiveUtils.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieHFileInputFormat.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestInputPathHandler.java
```sql
create table test_hudi_table (
id int,
name string,
price double,
ts long,
dt string
) using hudi
options (
preCombineField = 'ts',
type = 'cow'
)
location '/tmp/test_hudi_table';
```
```sql
select count(1) from test_hudi_table;
```
```java
ERROR : Status: Failed
ERROR : Vertex failed, vertexName=Map 1, vertexId=vertex_1647336877182_0100_4_00, diagnostics=[Vertex vertex_1647336877182_0100_4_00 [Map 1] killed/failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input: test_hudi_table initializer failed, vertex=vertex_1647336877182_0100_4_00 [Map 1], java.lang.NullPointerException
at org.apache.hudi.hadoop.utils.HoodieInputFormatUtils.getTableMetaClientForBasePath(HoodieInputFormatUtils.java:327)
at org.apache.hudi.hadoop.InputPathHandler.parseInputPaths(InputPathHandler.j …
```
=> [HUDI-3643] Fix hive count exception when the table is empty and the path depth is less than 3

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMergedLogRecordReader.java
- Even if point look ups are enabled for log record reader for metadata table, we do see an extra full scan is triggered. Triaged and root caused it to "read lazy" argument being always set to false. Likely these were written having FILES partition in mind where its always full scan. 
- Fixed "lazy read" to true for metadata log record readers in general.
- manually verified the fix. 
- And existing tests should cover in general
=> [HUDI-3810] Fixing lazy read for metadata log record readers

packaging/hudi-hive-sync-bundle/pom.xml
The Hive sync fails with `ClassNotFoundException` on a Hudi table if metadata table is enabled on the read path, because `hudi-hive-sync-bundle` does not package HBase classes which are needed for reading metadata table.  This PR fixes `hudi-hive-sync-bundle` to include HBase dependencies and shading.
- Adds changes related to HBase dependencies and shading to `pom.xml` of`hudi-hive-sync-bundle`, similar to changes to other bundles in #5004.
This pull request is already covered by existing IT tests.
=> [HUDI-3823] Fix hudi-hive-sync-bundle to include HBase dependencies and shading

hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java, hudi-examples/hudi-examples-flink/src/test/java/org/apache/hudi/examples/quickstart/TestQuickstartData.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
HUDI-3454
There were some paths where we did not init partition while building log record scanner. Fixed all such code paths.
- Depend on `FSUtils#getRelativePartitionPath(basePath, logFilePath.getParent)` to get the partition.
- If the list of log file paths in the split is empty, then fallback to usual behaviour.
*(or)*
(or)
*(example:)*
=> [HUDI-3454] Fix partition name in all code paths for LogRecordScanner

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteTable.scala
fix can not delete record by use  spark sql. operation.key must be "delete"
*(or)*
(or)
*(example:)*
=> [HUDI-3781] fix spark delete sql can not delete record

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Fixing non-partitioned table Partition Records persistence in MT.
Right now for non-partitioned table both "" (empty) and "." will be persisted as corresponding partitions, which is incorrect. Instead we make sure that we always map factual partition path (empty) into a _partition-id_ (".") before persisting it to MT.
Check out above
=> [HUDI-3825] Fixing non-partitioned table Partition Records persistence in MT

docker/README.md
As above to bridge the gaps in docker build setup docs.
The page can be visualized.  Only docs change.
=> [MINOR] Update README of docker build setup

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLookupHandle.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
This PR adds a new config to control the use and reading of metadata index in HoodieBloomIndex, separate from the existing write configs, e.g., `hoodie.metadata.index.column.stats.enable`, which control the writing of the index in metadata table.
- Adds new config `hoodie.bloom.index.use.metadata` to control the use of index from metadata table in HoodieBloomIndex.  When true, the index lookup uses bloom filters and column stats from metadata table when available to speed up the process.
- Replaces the control knobs with the new config for reading metadata index on the write path.
=> [HUDI-3807] Add a new config to control the use of metadata index in HoodieBloomIndex

hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestClusteringCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCompactionCommand.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/main/java/org/apache/hudi/common/fs/HoodieWrapperFileSystem.java, hudi-common/src/main/java/org/apache/hudi/common/model/BaseFile.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java, hudi-common/src/main/java/org/apache/hudi/hadoop/CachingPath.java, hudi-common/src/main/java/org/apache/hudi/hadoop/LazyCachingPath.java, hudi-common/src/main/java/org/apache/hudi/hadoop/SerializablePath.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
Fixing performance hits in reading Column Stats Index:
1. [HUDI-3834] There's substantial performance degradation in Avro 1.10 default generated `Builder` classes: they by default rely on `SpecificData.getForSchema` that load corresponding model's class using reflection, which takes a hit when executed on the hot-path (this was bringing overall runtime to read full Column Stats Index of 800k records to **60s**, whereas now it's taking mere **3s**)
2. Addressing memory churn by over-used Hadoop's `Path` creation: `Path` ctor is not a lightweight sequence and produces quite a bit of memory churn adding pressure on GC. Cleaning such …
=> [HUDI-3834] Fixing performance hits in reading Column Stats Index

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Addressing the problem of Data Skipping not respecting Metadata Table configs which might differ b/w write/read paths. More details could be found in HUDI-3812.
- Fixing Data Skipping configuration to respect MT configs (on the Read path)
- Tightening up DS handling of cases when no top-level columns are in the target query
- Enhancing tests to cover all possible cases
=> [HUDI-3812] Fixing Data Skipping configuration to respect Metadata Table configs

docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml, docker/demo/config/test-suite/deltastreamer-medium-clustering.yaml, docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml, docker/demo/config/test-suite/deltastreamer-non-partitioned.yaml, docker/demo/config/test-suite/insert-overwrite-table.yaml, docker/demo/config/test-suite/spark-long-running-non-partitioned.yaml, docker/demo/config/test-suite/test-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-clustering-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-clustering-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-clustering-inline-compact.properties, docker/demo/config/test-suite/test-clustering-metadata-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-clustering-metadata-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-clustering.properties, docker/demo/config/test-suite/test-inline-compact.properties, docker/demo/config/test-suite/test-metadata-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-metadata-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-metadata-inline-compact.properties, docker/demo/config/test-suite/test-metadata.properties, docker/demo/config/test-suite/test-nonpartitioned-inline-compact.properties, docker/demo/config/test-suite/test-nonpartitioned-metadata-inline-compact.properties, docker/demo/config/test-suite/test-nonpartitioned-metadata.properties, docker/demo/config/test-suite/test-nonpartitioned.properties, docker/demo/config/test-suite/test.properties, hudi-integ-test/README.md, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseValidateDatasetNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/ValidateDatasetNode.java, hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/SparkDataSourceContinuousIngest.scala
- Adding support for testing non-partitioned datasets w/ integ tests
- Added few test yamls and properties files
- Fixed few other issues w/ integ tests yamls and properties files.
*(or)*
(or)
*(example:)*
=> [HUDI-3842] Integ tests for non partitioned datasets

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR fixes the NullPointerException during reading Hudi log files in HoodieMetadataTableValidator, possibly due to empty or partial log files written by an inflight instant.
- Adds the logic to skip the check of a log file if the schema cannot be read or IOException happens.
This pull request is tested using a long-running HoodieMetadataTableValidator job to make sure that NPE is not thrown when empty or partial log files are present.
=> [HUDI-3847] Fix NPE due to null schema in HoodieMetadataTableValidator

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/TransactionManager.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestTransactionManager.java
- We had 2 begin and 2 end transaction methods in transaction manager, where one of them did not take in the owner info. Cleaning those up and fixed all callers to send in the transaction onwer info. 
- Also, if transaction was started by caller1, but if end transaction was called by caller2, we were letting the caller2 release the lock. So, fixed that to ensure only the owner who acquired the lock can end the transaction. 
- Cleaned up an extraneous begin and end method in transaction manager. 
- Fixed ending of a transaction by a different caller than who acquired the lock. 
- Added a test to TestTransactionManager to verify the fix.
=> [HUDI-3798] Fixing ending of a transaction by different owner and removing some extraneous methods in trxn manager

packaging/hudi-hadoop-mr-bundle/pom.xml, pom.xml
This PR specify parquet version for hudi-hadoop-mr-bundle module, used to solve the conflict problem for hive that hudi-hadoop-mr-bundle will include 1.12.2 version of parquet-avro  when -Dspark3 is used
- specify parquet version when compile hudi using -Dspark3 for hudi-hadoop-mr-bundle 
*(or)*
(or)
*(example:)*
=> [HUDI-3817] shade parquet dependency for hudi-hadoop-mr-bundle

docker/demo/config/test-suite/test-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-clustering-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-clustering-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-clustering-inline-compact.properties, docker/demo/config/test-suite/test-clustering-metadata-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-clustering-metadata-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-clustering.properties, docker/demo/config/test-suite/test-inline-compact.properties, docker/demo/config/test-suite/test-metadata-aggressive-clean-archival-inline-compact.properties, docker/demo/config/test-suite/test-metadata-aggressive-clean-archival.properties, docker/demo/config/test-suite/test-metadata-inline-compact.properties, docker/demo/config/test-suite/test-metadata.properties, docker/demo/config/test-suite/test-nonpartitioned-inline-compact.properties, docker/demo/config/test-suite/test-nonpartitioned-metadata-inline-compact.properties, docker/demo/config/test-suite/test-nonpartitioned-metadata.properties, docker/demo/config/test-suite/test-nonpartitioned.properties, docker/demo/config/test-suite/test.properties
Enabling timeline server for integ tests does not shutdown the job fully in the end. Disabling it for now as we need to investigate this and re-enable it back later. Have created a follow up task for the investigation and re-enabling it https://issues.apache.org/jira/browse/HUDI-3852
*(or)*
(or)
*(example:)* …
=> [MINOR] fixing timeline server for integ tests

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
HUDI-3844
Without this patch, the indexer presumes only those metadata indexes are enabled which are passed to it in the props. Any other metadata index (other than FILES ofc) created by regular writers will get deleted. Indexer should not presume, instead reset its config if any MDT partition is available.
- Update props in indexer based on table config.
- Guard MDT partitions init by async index config in metadata writer.
- Add UT to cover the scenario.
*(or)*
(or)
*(example:)* …
=> [HUDI-3844] Update props in indexer based on table config

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/MetadataConversionUtils.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
In Local and hdfs file schemes, there could be partial files created, where in the commit meta files could be empty. We put in a fix sometime back to delete these entries during archival as it will hinder the archival and will fail the pipeline. But we wanted to maintain the entry for book keeping purposes. So, in this patch, we are not deleting such instances, but creating an instant w/o any plan and serializing it to archived folder. So, that we will know exactly what all entries have been archived. 
- Fixed timeline archiver to archive even empty instants instead of deleting them. 
- TestTimelineArchiver.testArchiveCompletedRollbackAndClean
=> [HUDI-3799] Fixing not deleting empty instants w/o archiving

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
Fixing incorrect selection of MT partitions to be updated.
See above.
=> [HUDI-3839] Fixing incorrect selection of MT partitions to be updated

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Add support for `hoodie.datasource.write.drop.partition.columns` config for DeltaStreamer code path.
- *Add support for `hoodie.datasource.write.drop.partition.columns` config for DeltaStreamer code path.*
- *Added method to TestHoodieAvroUtils class to verify the change.*
- *Manually verified the change by running a job locally using the local docker setup, the BigQuery tables were created properly as expected.*
=> [HUDI-3838] Implemented drop partition column feature for delta streamer code path

README.md, scripts/release/deploy_staging_jars.sh
- Make flink 1.13 and 1.14 profiles build with scala 2.11 during deploy
- Update GH actions setup accordingly
- Update README
=> [HUDI-3843] Make flink profiles build with scala-2.11

docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml
=> [MINOR] Integ Test Reducing partitions for log running multi partition yaml

.github/workflows/bot.yml, README.md, packaging/hudi-utilities-slim-bundle/pom.xml, pom.xml
- Fix GH actions to not run patch versions
- Update readme for explaining different spark bundles and build instructions
- Remove parquet-avro from utilities-slim to avoid conflicts with different spark bundles
=> [HUDI-3859] Fix spark profiles and utilities-slim dep

docker/compose/docker-compose_hadoop284_hive233_spark244.yml, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieConcatHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieOrcWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieParquetWriter.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieMergeHandle.java
Fixing `FILENAME_METADATA_FIELD` not being correctly updated in `HoodieMergeHandle`, in cases when old-record is carried over from existing file as is.
- Revisited HoodieFileWriter API to accept HoodieKey instead of `HoodieRecord`
- Fixed FILENAME_METADATA_FIELD not being overridden in cases when simply old record is carried over
- Exposing standard JVM's debugger ports in Docker setup
=> [HUDI-3855] Fixing `FILENAME_METADATA_FIELD` not being correctly updated in `HoodieMergeHandle`

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
Since Data Skipping now solely relies on Metadata Table's Column Stats Index, which is currently in experimental mode, we should disable Data Skipping in the 0.11 release and subsequently immediately re-enable on master (along with Column Stats Index) 
- Disabling Data Skipping by default
=> [HUDI-3867] Disable Data Skipping by default

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
=> [HUDI-3870] Add timeout rollback for flink online compaction

hudi-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
This PR improves error handling of loading Hudi conf, addressing comments from #4167.
- Catches exception if there is error loading default conf and uses try-with-resources statement for the reader in `DFSPropertiesConfiguration`.
Using `spark-shell`, when the default config file is not present:
```
scala> df.write.format("hudi").
|         options(getQuickstartWriteConfigs).
|         option(PRECOMBINE_FIELD.key(), "ts").
|         option(RECORDKEY_FIELD.key(), "uuid").
|         option(PARTITIONPATH_FIELD.key(), "partitionpath").
|         option(TBL_NAME.key(), tableName).
|         mode(Overwrite).
|         save(basePath)
22/04/12 23:12:16 WARN DFSPropertiesConfiguration: Cannot find HUDI_CONF_DIR, please set it as the dir of hudi-defaults.conf
22/04/12 23:12:16 WARN …
```
=> [HUDI-3869] Improve error handling of loading Hudi conf

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
This PR fixes the check of inline and async table services in `HoodieWriteConfig`.  This addresses the comment from #4406 .
- Adjusts `areAnyTableServicesExecutedInline()` and `areAnyTableServicesAsync()` in `HoodieWriteConfig`.
This pull request is already covered by existing tests and adds a new test around all async table service configs.
=> [HUDI-3686] Fix inline and async table service check in HoodieWriteConfig

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
- Fetching partitions from glue sync may not complete in one call. if a token is set in the result, we have to make another request. 
- Fixed GlueSyncClient to make repeated getPartitions() call if not fully fetched.
*(or)*
(or)
*(example:)*
=> [HUDI-3876] Fixing fetching partitions in GlueSyncClient

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteTable.scala
=> [HUDI-3845] Fix delete mor table's partition with urlencode's error

hudi-common/src/main/java/org/apache/hudi/common/util/ObjectSizeCalculator.java
=> [HUDI-3652] Make ObjectSizeCalculator threadlocal to reduce memory footprint

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackStrategy.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
Recently we made a [fix](https://github.com/apache/hudi/pull/4957) to listbased rollback strategy to rely on commit metadata for completed commits. For completed commits, we are relying on commit metadata to deduce the list of files to be deleted and we have fs.listStatus in one of the places. But there are chances, that a commit is cleaned up by the cleaner and hence no data files exists. So, fixing this to do exists check to ensure we can ignore non existant files to be rolledback. 
- Fixed list based rollback strategy to ignore non existant data files while deducing list of files to delete for a complete commit. 
- TestHoodieSparkMergeOnReadTableRollback.testRestoreWithCleanedUpCommits
=> [HUDI-3848] Fixing restore with cleaned up commits

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
After saw a comment on https://github.com/apache/hudi/commit/f2a93ead3b5a6964a72b3543ada58aa334edef9c#r69671705 regarding the closable and autoClosable, I went back to check the code. We use https://github.com/apache/spark/blob/ef8fb9b9d84b6adfe5a4e03b6e775e709d624144/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala#L200 which returns an iterator and not an instance of Closable or AutoClosable. But guarding it using AutoClosable. 
*(or)*
(or) …
=> [MINOR] Fixing parquet reader iterator close 

website/package.json
This PR fixes the docs build due to the latest std-env 3.1.1 release.  
- Uses "std-env" module from 3.0.1 release (one version older) instead in package.json.
The website can successfully be built after the fix.
=> [MINOR] Fix docs build due to std-env

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
- TestHoodieDeltastreamer.testHoodieAsyncClusteringJob has been flaky in CI and hence it was disabled. Fixing it in this patch. 
Context: we can't schedule async clustering when regular writers are making commits if they are overlapping. So, for now, have fixed the flakiness to stop ingestion and ensure the clustering job is able to scheduled and execute. But we need to fix the data generation in general. Have also created a follow up ticket. https://issues.apache.org/jira/browse/HUDI-3872 to work on test data generation to cover many more cases for async clustering in general. 
- Fixed flakiness around testHoodieAsyncClusteringJob in tests. 
- Fix itself is in tests only
=> [HUDI-3710] Fixing async clustering job test in TestHoodieDeltaStreamer

hudi-common/src/main/avro/HoodieMetadata.avsc
Adding default null for some of the fields in col stats in MDT schema
*(or)*
(or)
*(example:)*
=> [HUDI-3886] Adding default null for some of the fields in col stats in MDT schema

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
When using custom transformers, user may not have turned on config to reconcile schema explicitly. In that case, the schema in the transformed dataset and that coming from a schema provider could differ. This PR fixes it by passing the latest schema if it is present, irrespective of whether `hoodie.datasource.write.reconcile.schema` is true or false.
*(or)*
(or)
*(example:)*
- *Added …
=> [HUDI-3707] Fix deltastreamer test with schema provider and transformer

packaging/hudi-datahub-sync-bundle/pom.xml
This PR fixes the datahub sync bundle to include HBase dependencies and shading, so that it does not introduce ClassNotFoundException related to HBase classes.
- Adds HBase dependencies and shading to pom.xml of datahub sync bundle.
This PR is verified by running deltastreamer using both utilities bundle and datahub sync bundle.  There is no issue any more.
=> [HUDI-3894] Fix datahub to include HBase dependencies and shading

packaging/hudi-kafka-connect-bundle/pom.xml
This PR fixes the `NoClassDefFoundError` due to `org.apache.hudi.schema.FilebasedSchemaProvider`.  The class is not packaged to the hudi-kafka-connect-bundle because of changes in flink modules from #5072 (Right now, Kafka Connect Sink for Hudi temporarily relies on schema provider classes in Flink that do not use Spark context).  The PR corrects the shade include rule for the flink module.
```
java.lang.NoClassDefFoundError: org/apache/hudi/schema/FilebasedSchemaProvider
at org.apache.hudi.connect.writers.KafkaConnectConfigs.<clinit>(KafkaConnectConfigs.java:57)
at org.apache.hudi.connect.HoodieSinkTask.start(HoodieSinkTask.java:80)
at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:308)
at …
```
=> [HUDI-3903] Fix NoClassDefFoundError with Kafka Connect bundle

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java, hudi-utilities/src/test/resources/delta-streamer-config/indexer-only-bloom.properties
Currently, drop index deletes the partition but leaves any pending instant on the timeline. If we do not delete the pending index instants, then compaction may not kick in the MDT. This PR fixes the behavior.
- Update dropIndex API in `HoodieBackedTableMetadataWriter`
- Add UT for the scenario
- Added a UT, which schedules column_stats index but then calls drop index, so the indexing.requested should be deleted.
- Manually verified for indexing.inflight by killing the regular writer.
=> [HUDI-3899] Drop index to delete pending index instants from timeline if applicable

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/SparkDatasetMixin.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSourceStorage.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Spark unfortunately predicates some of its optimization `Rule`s (and some other handling) on usage of `HadoopFsRelation` which leads to those optimizations not being applied when we rely on our custom `Relation` impls. 
To work this around for the 0.11, we fallback to `HadoopFsRelation` in cases when it's feasible to do so.
> NOTE: We're partially restoring [logic present in 0.10.1](https://github.com/apache/hudi/blob/cc3896be2a023f8819883d745178503286ac2ab1/hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/DefaultSource.scala#L182)
- Adding `toHadoopFsRelation` method for `BaseFileOnlyRelation`
- Fallback to …
=> [HUDI-3902] Fallback to `HadoopFsRelation` in cases non-involving Schema Evolution

hudi-kafka-connect/README.md
This PR adds S3 related setup in Kafka Connect quick start, to make it easier to try Kafka Connect Sink for Hudi on S3 storage.
=> [HUDI-3905] Add S3 related setup in Kafka Connect quick start

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR fixes the partition path construction in metadata table validator for non-partitioned tables.
- Uses `FSUtils.getPartitionPath()` to construct partition path so that it does not complain about non-partitioned table.
This pull request is verified by running the `HoodieMetadataTableValidator` on both partitioned and non-partitioned tables that the validator works for both cases.
=> [HUDI-3920] Fix partition path construction in metadata table validator

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
=> [HUDI-3917] Flink write task hangs if last checkpoint has no data input

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java
Currently when rollback a compact action it just revert the request instant to inflight
But in CompactionCommitSink it keep the preview compact event when rollback
It will cause commit too fast before all next real compact events come and use wrong fileId
*(or)*
(or)
*(example:)*
- …
=> [HUDI-3912] Fix lose data when rollback in flink async compact

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
by default there are no retries at all for lock acquisition. So, if lock acquisition times out in 60 secs, we bail out. But metadata write could take longer for large datasets. and hence we need to fix the default since we are looking to enable InProcessLockProvider by default if users haven't configured lock provider. 
*(or)*
(or)
*(example:)* …
=> [HUDI-3938] Fixing default value for num retries to acquire the lock

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieDataSourceHelper.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieParquetFileFormat.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
#5364 made extraction of values for partition columns from partition path became configurable, _disabling_ it by default, 
since by default Hudi persists partition columns in the data file which could be fetched directly instead of parsing partition values from partition path.
This PR adds a fallback configuration allowing to control whether partition values should be parsed from the partition path (which is default Spark behavior).
- Unified shouldOmitPartitionColumns and `shouldExtractPartitionValuesFromPartitionPath` flags
- Added new `EXTRACT_PARTITION_VALUES_FROM_PARTITION_PATH`
- Added test
This pull request is already covered …
=> [HUDI-3935] Adding config to fallback to enabled Partition Values extraction from Partition path

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/action/InternalSchemaMerger.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/InternalSchemaUtils.java, hudi-common/src/test/java/org/apache/hudi/internal/schema/utils/TestAvroSchemaEvolutionUtils.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
=> [HUDI-3921] Fixed schema evolution cannot work with HUDI-3855

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
This PR fixes the projection logic around a nested field which is used as the pre-combined key field.  The fix is to only check and append the root level field for projection, i.e., "a", for a nested field "a.b.c" in the mandatory columns.
- Changes the logic to check and append the root level field for a required nested field in the mandatory columns in `HoodieBaseRelation.appendMandatoryColumns`
- Adds tests to guard around the behavior for a nested field used as pre-combined key.
This change adds tests in `TestHoodieAvroUtils` and `TestMORDataSourceStorage`.  `TestMORDataSourceStorage` contains tests that use nested field "fare.currency" as the pre-combined key.  Before this change, the tests with nest fields fail.  After this PR, the tests pass.
=> [HUDI-3936] Fix projection for a nested field as pre-combined key

README.md
This PR adds commit activity, twitter badgers, and Hudi logo in README.
The medium-definition Hudi logo image is added to the Hudi site in #5331 .
Only README.md updates.
=> [DOCS] Add commit activity, twitter badgers, and Hudi logo in README

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
HiveConf is getting eagerly loaded when HoodieSparkSqlWriter is touched. Strangely this happens only with spark2 and scala12 and not w/ any other profiles. And after inspecting the usages, looks like we don't really need to use HiveConfig in HoodieSparkSqlWriter, all we need is HadoopConf. So, have fixed the usage. 
- Removed unintended usage of HiveConf in HoodieSparkSqlWriter. 
Ran quick start locally and verified that w/ the patch, it succeeds. and w/o the patch, we get failure w/ spark2 and scala12.
=> [HUDI-3947] Fixing Hive conf usage in HoodieSparkSqlWriter

packaging/hudi-flink-bundle/pom.xml, packaging/hudi-presto-bundle/pom.xml, packaging/hudi-trino-bundle/pom.xml
This PR adds the missing artifact of `hbase-server` and `commons-lang3` and removes unused `hbase-protocol` in presto bundle.  This PR also removes `hbase-annotations` (only test annotation classes that are not needed in production) from trino bundle.
- Adds `org.apache.hbase:hbase-server`  and `org.apache.commons:commons-lang3` in the shading `include` rule and removes `org.apache.hbase:hbase-protocol` (not used) in presto bundle.  The `commons-lang3` is also shaded.
- Removes `org.apache.hbase:hbase-annotations` from trino bundle
After switching `DEFAULT_METADATA_ENABLE_FOR_READERS` to true to enable metadata table reading during queries, the CI passes after this fix (it is broken before this fix).
=> [HUDI-3948] Fix presto bundle missing HBase classes

hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParsePartitionUtil.scala
Fix cast exception while reading boolean type of partitioned field
*(or)*
(or)
*(example:)*
=> [HUDI-3923] Fix cast exception while reading boolean type of partitioned field

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
support generan parameter 'sink.parallelism' for flink-hudi
=> [HUDI-3951]support general parameter 'sink.parallelism' for flink-hudi

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
We should do a non-null check on option 'path' in flink hudi sink so that flink can expose the 'path' problem as early as possible, instead of throwing the error at runtime.
```
Caused by: java.lang.IllegalArgumentException: Can not create a Path from a null string
at org.apache.hadoop.fs.Path.checkPathArg(Path.java:122) ~[hadoop-common-2.7.6.jar:?]
at org.apache.hadoop.fs.Path.<init>(Path.java:134) ~[hadoop-common-2.7.6.jar:?]
at org.apache.hudi.common.fs.FSUtils.getFs(FSUtils.java:103) ~[hudi-flink1.14-bundle_2.11-0.11.0-rc1.jar:0.11.0-rc1]
at org.apache.hudi.util.StreamerUtil.tableExists(StreamerUtil.java:289) ~[hudi-flink1.14-bundle_2.11-0.11.0-rc1.jar:0.11.0-rc1]
at org.apache.hudi.util.StreamerUtil.initTableIfNotExists(StreamerUtil.java:258) …
```
=> [HUDI-3946] Validate option path in flink hudi sink

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Fixing hoodie.properties/tableConfig when no precombine field is set. 
- Fixed instantiation of new table to set the null for preCombine if not explicitly set by the user. 
- Added tests to TestCOWDataSource.testNoPreCombine and TestMORDataSource.testNoPreCombine.
=> [HUDI-3972] Fixing hoodie.properties/tableConfig for no preCombine field with writes

website/docs/quick-start-guide.md
=> [HUDI-3925][DOC]Add schema evolution doc for sparksql

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
…k should exit.
*After the async compaction operation is complete, the task should exit.*
*(or)*
(or)
*(example:)*
=> [HUDI-3945] After the async compaction operation is complete, the task should exit

website/docs/schema_evolution.md
add schema type change maxtrix for schema evolution doc.
address the comments on [HUDI-3945](https://github.com/apache/hudi/pull/5238)
*(or)*
(or)
*(example:)* …
=> [MINOR]add schema type change matrix for schema evolution doc.

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
=> [MINOR] support different cleaning policy for flink

hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
This PR is a bandaid fix to address the following CI failure:
```
Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
org.apache.hudi.utilities.TestHoodieIndexer.init(TestHoodieIndexer.java:84)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688) …
```
=> [MINOR] Fix CI by ignoring SparkContext error

website/releases/download.md, website/releases/release-0.10.0.md, website/releases/release-0.10.1.md, website/releases/release-0.11.0.md, website/releases/release-0.7.0.md, website/releases/release-0.8.0.md, website/releases/release-0.9.0.md
=> [HUDI-3997] Add 0.11.0 release notes

website/docs/performance.md, website/releases/release-0.11.0.md, website/versioned_docs/version-0.11.0/performance.md
Adding documentation around Data Skipping introduced in the upcoming 0.11 release.
- Cleaned up outdated query's runtimes comparison (Uber internal, very cryptic and hard to understand w/o Uber's background)
- Added paragraph dedicated to Data Skipping
N/A
=> [HUDI-3930][Docs] Adding documentation around Data Skipping

website/docs/metadata_indexing.md, website/docs/performance.md, website/docs/syncing_aws_glue_data_catalog.md, website/docs/syncing_datahub.md, website/docs/syncing_metastore.md, website/releases/release-0.11.0.md, website/sidebars.js, website/versioned_docs/version-0.11.0/metadata_indexing.md, website/versioned_docs/version-0.11.0/performance.md, website/versioned_docs/version-0.11.0/syncing_aws_glue_data_catalog.md, website/versioned_docs/version-0.11.0/syncing_datahub.md, website/versioned_docs/version-0.11.0/syncing_metastore.md, website/versioned_sidebars/version-0.11.0-sidebars.json
- Moved big query under catalog syncing
- Renamed async_meta_indexing to metadata_indexing
- Edits to clarify data skipping docs, added link to rfc
- Edits on release notes
*(or)*
(or)
*(example:)*
- *Added integration …
=> [DOCS] Changes for 0.11.0 release docs

azure-pipelines.yml, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/DagUtils.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestDFSHoodieTestSuiteWriterAdapter.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/converter/TestDeleteConverter.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/dag/TestDagUtils.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/generator/TestGenericRecordPayloadEstimator.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSHoodieDatasetInputReader.java
In latest master, the unit tests in hudi-integ-test module are not executed in CI.  This PR adds a task in CI to run unit tests in hudi-integ-test.  This PR also fixes three issues causing test failures: (1) Fixes the generation of yaml file based on DAG because of new schema; (2) Set "none" if there is no dependency of a DAG node; (3) Fixes wrong logic in `TestDeleteConverter#testGenerateDeleteRecordsFromInputRecords()`; (4) Fixes wrong size in `TestGenericRecordPayloadEstimator#testSimpleSchemaSize()`.  The rest failed tests are disabled and going to be addressed by HUDI-3668.
- Adds a task in CI to run unit tests of hudi-integ-test module in `azure-pipelines.yml`
- Fixes the generation of yaml file based on DAG in `DagUtils`
- Fixes a few unit tests: …
=> [HUDI-3667] Run unit tests of hudi-integ-tests in CI

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/NoNewDataTerminationStrategy.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/PostWriteTerminationStrategy.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/TerminationStrategyUtils.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestDataSource.java
With continuous mode deltastreamer, there is no way to trigger gracefull shutdown. This patch is adding a post write termination strategy giving an option to users to trigger shutdown if need be. For eg, if there is no new data to consume from source, users may wish to shutdown the continuous mode and restart the pipeline after sometime instead of having the pipeline running all the time. For instance, users can configure graceful shutdown if there is no new data from source for 5 consecutive times. Here is the interface for the termination strategy. 
Also, this might help in bootstrapping new a new table. instead of doing one bulk load or bulk_insert leverage a large cluster for a large input of data, one could start deltastreamer on continuous mode and add a shutdown strategy to …
=> [HUDI-3675] Adding post write termination strategy to deltastreamer continuous mode

hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/avro/HoodieSpark3_2AvroDeserializer.scala
Now the `datetimeRebaseMode` of `AvroDeserializer` is hardcode and the value is "EXCEPTION".    
We can support reading the configuration `AVRO_REBASE_MODE_IN_READ` of SQLCONf to switch the behavior of read.
- AvroDeserializer supports AVRO_REBASE_MODE_IN_READ configuration
=> [HUDI-3849]  AvroDeserializer supports AVRO_REBASE_MODE_IN_READ configuration

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/BuiltinKeyGenerator.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/ComplexKeyGenerator.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/GlobalDeleteKeyGenerator.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/NonpartitionedKeyGenerator.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/RowKeyGeneratorHelper.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/SimpleKeyGenerator.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/TimestampBasedKeyGenerator.java, hudi-client/hudi-spark-client/src/test/scala/org/apache/hudi/keygen/TestRowGeneratorHelper.scala, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieDatasetBulkInsertHelper.java, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/BulkInsertDataInternalWriterHelper.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieDatasetBulkInsertHelper.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestComplexKeyGenerator.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestGlobalDeleteRecordGenerator.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestNonpartitionedKeyGenerator.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestSimpleKeyGenerator.java
- Adding few perf optimizations for bulk insert row writer. 
- Avoid using udf for key generator for SimpleKeyGen and NonPartitionedKeyGen. 
- Fixed NonPartitioned Key generator to directly fetch record key from row rather than involving GenericRecord.
- Other minor fixes around using static values instead of looking up hashmap. 
- Fixed TestHoodieDatasetBulkInsertHelper tests to test the fixed functionality. Rest of the fixes are covered with existing tests.
=> [HUDI-3995] Making perf optimizations for bulk insert row writer path

website/docusaurus.config.js
Pull up Blog into one of the top items
Currently Blogs are nested under Learn tab. We want o pull this to top items for better discoverability
*(or)*
(or)
*(example:)*
- *Added …
=> [DOCS] Pull up Blog into top navigation items

hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
I have two partitions named p1 and p2.
I only delete record in p1 and only update record in p2.
Run flink offline compaction and it will throw NPE, because the log file in p1 only contains delete operation and hudi cannot get schema from it.
If a `.log` file only contain delete operation, we can't parse schema from this file. So it should scan another `.log` file to parse schema when the code runs in the moment.
*(or)*
This …
=> [HUDI-4003] Try to read all the log file to parse schema

hudi-cli/src/main/scala/org/apache/hudi/cli/SparkHelpers.scala, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroParquetWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieBaseParquetWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriterFactory.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieOrcWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieParquetWriter.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java, hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieInternalRowParquetWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/storage/TestHoodieFileWriterFactory.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
`getDataSize` has non-trivial overhead in the current `ParquetWriter` impl, requiring traversal of already composed Column Groups in memory. Instead we can sample these calls to `getDataSize` to amortize its cost.
- Sample memory checks of the currently written output size to avoid excessive block traversals
- Extracted HoodieBaseParquetWriter encapsulating shared functionality b/w `ParquetWriter` impls
=> [HUDI-4038] Avoid calling `getDataSize` after every record written

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
When creating table like below with a 'comment' and check by "show create table", the comment is not shown
```
create table test(
id int,
name string,
price double,
ts long
) using hudi
comment "This is a simple hudi table"
preCombineField = 'ts'
)
```
The cause is as below:
1. Current hudi & spark3 invokes ShowCreateTableExec when "show create ..."
2. ShowCreateTableExec checks table property of 'comment' for result
3. Spark HiveClientImpl hides property of 'comment', but set it to Catalog#comment when returning a CatalogTable (https://github.com/apache/spark/blob/master/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala#L487)
This PR targets to fix and give a support.
- *Restore table property of 'comment' when …
=> [HUDI-4079] Supports showing table comment for hudi with spark3

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestParquetDFSSourceEmptyBatch.java
- fixing the way we test empty batches with parquet dfs source in TestHoodieDeltaStreamer. 
- Fixing the way we test empty batches with parquet dfs source in TestHoodieDeltaStreamer. 
*(or)*
(or)
*(example:)*
=> [HUDI-4085] Fixing flakiness with parquet empty batch tests in TestHoodieDeltaStreamer

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/HadoopConfigurations.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/schema/FilebasedSchemaProvider.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkTables.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ViewStorageProperties.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/meta/TestCkpMetadata.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/partitioner/TestBucketAssigner.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadOperator.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestViewStorageProperties.java
=> [HUDI-3336][HUDI-FLINK]Support custom hadoop config for flink

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Fix a minor NPE issue when using `Option`.
* Remove the default `null` since it will be returned by default
* Use `Option.ofNullable()` instead of `Option.of()` to avoid NPE
*(or)*
(or)
*(example:)*
=> [MINOR] Fix a NPE for Option

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/InputBatch.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
- Fixing schema to set with writeConfig in deltastreamer when empty batch is consumed. 
- Fixing schema to set with writeConfig in deltastreamer when empty batch is consumed. 
*(or)*
(or)
*(example:)*
=> [HUDI-4072] Fixing NULL schema for empty batches in deltastreamer

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/CompactionAdminClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseWriteHelper.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackStrategy.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/savepoint/SavepointActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/WriteMarkers.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotCopier.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
add table info to sparkJobStatus and make it easy to see TableInfo in spark web console like that in following picture:
it's very useful espaicially when write multi table in one sparkContext.
*(or)*
(or)
*(example:)*
=> [HUDI-4097] add table info to jobStatus

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Related links：[issues-5248](https://github.com/apache/hudi/issues/5248) [PR-5215](https://github.com/apache/hudi/pull/5215)
Filter the properties should not be used when create table for Spark SQL
*(or)*
(or)
*(example:)*
=> [HUDI-4001] Filter the properties should not be used when create table for Spark SQL

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetastoreConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
The preparations which changes existing modules for hudi metastore.
The following commits are in https://github.com/apache/hudi/pull/5064
- Modify the  access modifier of HoodieActiveTimeline for inheritance.
- Get properties when build hoodieMetaClient for get more info.
- Add HoodieMetastoreConfig 
=> [HUDI-3654] Preparations for hudi metastore.

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/DropHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDropTable.scala
For a MOR table 'mor_simple' and its RO table 'mor_simple_ro' and RT table 'mor_simple_rt', if user drops 'mor_simple_ro' without purging. There might be issue. Reproduce like below:
```
1. Create table as below:
CREATE TABLE mor_simple (
`id` INT,
`name` STRING,
`price` DOUBLE)
USING hudi
location '/user/hive/warehous/mor_simple'
OPTIONS(
'type' = 'mor',
'primaryKey' = 'id',
'hoodie.table.precombine.field' = 'id'
); 
2. Trigger hive-sync by inserting values 
insert into mor_simple values (1, 'z3', 1)
3. 'show tables' -- we will find mor_simple_rt and mor_simple_ro show up;
4. 'drop table mor_simple_ro' and 'show tables' -- we will find mor_simple is dropped but mor_simple_ro can never be dropped.
```
This PR refines DropHoodieTableCommand and takes more consideration of identifier of …
=> [HUDI-4087] Support dropping RO and RT table in DropHoodieTableCommand

docker/demo/config/test-suite/spark-long-running-non-partitioned.yaml
- Adding delay between each round and increasing the freq of validation
*(or)*
(or)
*(example:)*
=> [MINOR] Fixing spark long running yaml for non-partitioned

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
=> [HUDI-4109] Copy the old record directly when it is chosen for merging

pom.xml
Spark3.2 uses antlr version 4.8, Hudi uses 4.7, use the same version to avoid a log of antlr check versions.
org.antlr.v4.runtime.RuntimeMetaData#checkVersion
```
ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8
```
Spark3.2.0 use 4.8
[[SPARK-35457](https://issues.apache.org/jira/browse/SPARK-35457)][BUILD] Bump ANTLR runtime version to 4.8
Spark3.1.0 use 4.8-1
[[SPARK-33475](https://issues.apache.org/jira/browse/SPARK-33475)][BUILD] Bump ANTLR runtime version to 4.8-1 
- *Bump ANTLR runtime version in Spark 3.x*
This pull request is already covered by existing tests, such as *TestTimeTravelTable*.
=> [HUDI-4111] Bump ANTLR runtime version in Spark 3.x

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCLIUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionHoodiePathCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionShowHoodiePathCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionShowHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCompactionProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCompactionProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCompactionProcedure.scala
Unify clustering/compaction related procedures' output type to provide more useful info
- Modify  the output type of `RunCompactionProcedure`, `ShowCompactionProcedure`, `RunClusteringProcedure`, `ShowClusteringProcedure`, `CompactionHoodiePathCommand`, `CompactionHoodieTableCommand`, `CompactionShowHoodiePathCommand`, `CompactionShowHoodieTableCommand`*
- Modify `TestClusteringProcedure`, `TestCompactionProcedure` and `TestCompactionTable`
This pull request is already covered by existing tests, such as `TestClusteringProcedure`, `TestCompactionProcedure` and `TestCompactionTable`
=> [HUDI-4116] Unify clustering/compaction related procedures' output type

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
=> [HUDI-4130] Remove the upgrade/downgrade for flink #initTable

hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/scheduler/DagScheduler.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
- Minor fixes to exception log with DeltaSync.
- removing unwanted metrics flush in integ test
*(or)*
(or)
*(example:)*
=> [MINOR] Minor fixes to exception log and removing unwanted metrics flush in integ test

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
Yesterday, when we add more nodes to kafka cluster, some of our hudi tasks failed with a NPE as below:
at org.apache.hudi.utilities.sources.helpers.KafkaOffsetGen.getNextOffsetRanges(KafkaOffsetGen.java:241)
at org.apache.hudi.utilities.sources.JsonKafkaSource.fetchNewData(JsonKafkaSource.java:67)
at org.apache.hudi.utilities.sources.Source.fetchNext(Source.java:76)
at org.apache.hudi.utilities.deltastreamer.SourceFormatAdapter.fetchNewDataInAvroFormat(SourceFormatAdapter.java:63)
at org.apache.hudi.utilities.deltastreamer.DeltaSync.readFromSource(DeltaSync.java:430)
at …
=> [HUDI-4122] Fix NPE caused by adding kafka nodes

packaging/hudi-spark-bundle/pom.xml
https://issues.apache.org/jira/browse/HUDI-3858
Users use hudi-spark-bundle will meet exception 
```
25826 [main] INFO  org.apache.hudi.common.table.HoodieTableMetaClient  - Finished Loading Table of type MERGE_ON_READ(version=1, baseFileFormat=HFILE) from file:///var/folders/61/77xdhf3x0x9g3t_vdd1c9_nwr4wznp/T/junit4739117508195793393/hudi_test_batch/.hoodie/metadata
25826 [main] INFO  org.apache.hudi.common.table.view.FileSystemViewManager  - Creating View Manager with storage type :REMOTE_FIRST
25826 [main] INFO  org.apache.hudi.common.table.view.FileSystemViewManager  - Creating remote first table view
25826 [main] INFO  org.apache.hudi.common.table.view.FileSystemViewManager  - Creating remote view for basePath file:/var/folders/61/77xdhf3x0x9g3t_vdd1c9_nwr4wznp/T/junit473911750819579 …
```
=> [HUDI-3858] Shade javax.servlet for hudi-spark-bundle

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieStagedTable.scala
Current HoodieStagedTable#abortStagedChanges cleans up data path by the table property of location, which doesn't work for a MANAGED table. This PR proposes to pass table path to HoodieStagedTable and do cleanup work properly.
- *HoodieCatalog add a function to deduce table path and pass to HoodieStagedTable*
- *Added test*
=> [HUDI-4100] CTAS failed to clean up when given an illegal MANAGED table definition

hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql, pom.xml
To fix the RAT plugin issue identified in the issue [HUDI-3890](https://issues.apache.org/jira/browse/HUDI-3890)
- Removed `<exclude>**/*.sql</exclude>` from parent pom.xml so that RAT plugin can scan the .sql file
- Added the license in .sql file (hudi\hudi-spark-datasource\hudi-spark\src\test\resources\sql-statements.sql)
- This pull request can be verified by existing tests  
- We can also run` mvn apache-rat:check` to validate the  licenses
=> [HUDI-3890] fix rat plugin issue

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- Relax the validation in checking primary key and preCombineField to allow nested field
=> [HUDI-4051] Allow nested field as primary key and preCombineField in spark sql

hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCleaningPolicy.java, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/sql/InsertMode.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveSyncMode.java
Fixed Such as title.
*(or)*
(or)
*(example:)*
=> [MINOR] Removing redundant semicolons and line breaks in enum Objects

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ZeroToOneUpgradeHandler.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/HoodieTestCommitGenerator.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandle.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandle.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java, hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieWriteStat.java, hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java, hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java, hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/TestCluster.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotCopier.java
=> [HUDI-4134] Fix method naming consistency issues in FSUtils

website/versioned_docs/version-0.10.1/quick-start-guide.md
Hi team, 
I wanted to add unset documentation for hudi spark sql, which I was searching for, so this might be useful for others.
I tried it on my tables and worked perfectly fine as this is the syntax from spark sql documentation.
Will this be merged to 0.11 docs or should I open a new PR?
This pull request modifies quick-start document
Add alter table unset tblproperties command documentation.
This pull request is a trivial rework  of spark guide.
- [ x] Commit message is descriptive of the change
- [ x] CI is green
- [ x] Necessary doc changes done or have another open PR
- [ x] For large changes, please consider breaking it into sub-tasks under an umbrella JIRA.
=> [MINOR][DOCS] Document alter table unset tblproperties comand

docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-hive.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml, docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml, docker/demo/config/test-suite/deltastreamer-medium-clustering.yaml, docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml, docker/demo/config/test-suite/detlastreamer-long-running-example.yaml, docker/demo/config/test-suite/spark-long-running-non-partitioned.yaml, docker/demo/config/test-suite/spark-long-running.yaml, hudi-integ-test/README.md, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieContinousTestSuiteWriter.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieInlineTestSuiteWriter.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/WriterContext.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseValidateDatasetNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/DeltaGenerator.java
- Adds support to test any test yaml for deltastreamer continuous mode and with async table services if need be. 
- Adds support to test any test yaml for deltastreamer continuous mode and with async table services if need be. 
- Added HoodieContinuousTestSuiteWriter to assist with this. 
- Fixed Validation to wait for deltastreamer to catch up before doing the actual validation. 
- Tested MOR w/ long running with deltastreamer continuous mode w/ async compaction locally.
=> [HUDI-4084 Adding support to test async table services with integ test suite framework

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
Compaction commit metadata did not have write operation set. This patch fixes it to set it to COMPACT
*(or)*
(or)
*(example:)*
=> [HUDI-2473] Fixing compaction write operation in commit metadata

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
=> [HUDI-4145] Archives the metadata file in HoodieInstant.State sequence

hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/UpgradeOrDowngradeCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java, hudi-cli/src/test/java/org/apache/hudi/cli/testutils/SparkUtilTest.java
This pull request fixes a potential NPE and some finer points of hudi cli. 
- Modify the initLauncher code of SparkUtil, make a judgment on libdirectory.
- Correctly rename the method initJavaSparkConf to initJavaSparkContext.
- Fix the return string message in UpgradeOrDowngradeCommand.
*(or)*
(or)
*(example:)*
=> [MINOR] Fix a potential NPE and some finer points of hudi cli

website/docs/tuning-guide.md, website/versioned_docs/version-0.10.1/tuning-guide.md, website/versioned_docs/version-0.11.0/tuning-guide.md
- The parameters `spark.yarn.driver.memoryOverhead` and `spark.yarn.executor.memoryOverhead` are out of date. After Apache Spark 2.3.0, they were replaced by `spark.driver.memoryOverhead` and `spark.executor.memoryOverhead` respectively.
- Check out this link for details :
https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/SparkConf.scala#L706-L709
-  ![image](https://user-images.githubusercontent.com/95120044/169958616-cf31303e-076e-4cb2-99bc-3af53653642e.png)
-  ![image](https://user-images.githubusercontent.com/95120044/169958727-ba3e89f4-66cc-422c-be2e-f5830d762e03.png)
=> [MINOR][DOCS] Update `spark.yarn.driver.memoryOverhead` and `spark.yarn.executor.memoryOverhead` in the tuning-guide.

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/CustomColumnsSortPartitionerWithRows.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDCustomColumnsSortPartitioner.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RowCustomColumnsSortPartitioner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitionerForRows.java
like RDDCustomColumnsSortPartitioner, we can use this partitioner to sort customer columns users specified.
for example:
```scala
df.write.format("hudi")
.option(HoodieWriteConfig.TABLE_NAME, "test_table")
.option(OPERATION.key, DataSourceWriteOptions.BULK_INSERT_OPERATION_OPT_VAL)
.option(RECORDKEY_FIELD.key, "session_id")
.option(PARTITIONPATH_FIELD.key, "date")
.option("hoodie.bulkinsert.user.defined.partitioner.class", "org.apache.hudi.execution.bulkinsert.CustomColumnsSortPartitionerWithRows")
.option("hoodie.bulkinsert.user.defined.partitioner.sort.columns", "page_type")
.mode(SaveMode.Append)
.save("hdfs://test/test_table") …
```
=> [HUDI-4040]Bulk insert: Add customColumnsSortpartitionerWithRows

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, packaging/hudi-utilities-slim-bundle/README.md, packaging/hudi-utilities-slim-bundle/pom.xml, pom.xml
This PR removes all the hudi-spark* dependencies, except hudi-spark-client, from hudi-utilities-slim-bundle. `hudi-spark-client` is needed due to compile-time dependency on `SparkRDDWriteClient` and `HoodieSparkEngineContext` classes.
* Ran a deltastreamer job locally with Spark 2.4.7, 3.1.2 and 3.2.0. Commands added in `packaging/hudi-utilities-slim-bunde/README.md`
=> [HUDI-4023] Decouple hudi-spark from hudi-utilities-slim-bundle

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
Currently we only accept hoodie.sql.bulk.insert.enable to control whether bulk_insert is enabled or not in spark sql mode, so during building buildHoodieInsertConfig(https://github.com/apache/hudi/blob/f30b3aef3e5e12e9119d6b5294c94a0282719e00/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala#L97), we use this param to decide insert operation. But it could be overridden at last: https://github.com/apache/hudi/blob/f30b3aef3e5e12e9119d6b5294c94a0282719e00/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala#L177
So if we …
=> [MINOR] Fix the issue when handling conf hoodie.datasource.write.operation=bulk_insert in sql mode

hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDbDiskMap.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
=> [HUDI-4151] flink split_reader supports rocksdb

packaging/hudi-integ-test-bundle/pom.xml
*To enable the pushgetway for Hudi metrics*
- *Added simpleclient artifactset for hudi-integ-test-bundle/pom.xml*
- *Run the test for integ test bundle and build the jar*
- *setup the prometheus/pushgsteway*
- *Run the integ test , you should be able to see the hudi metrics without any issue .
=> [HUDI-4166] Added SimpleClient plugin for integ test bundle

hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java, hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
This PR adds the "oci" scheme for using Hudi against Oracle Cloud Infrastructure using its HDFS Client.
I have documentation which I will put in another PR, apologies if I could have combined across branches I'm bad at git.
Changes:
- Registered OCI scheme, indicating appends are not supported.
- Added a test similar to existing tests for other schemes.
This pull request is pretty trivial. I validated it using the Hudi quickstart and results were the same as using a local path.
=> [HUDI-3551] Add the Oracle Cloud Infrastructure (oci) Object Storage URI scheme.

website/docs/cloud.md, website/docs/oci_hoodie.md
This is documentation to complement PR #4952
Modifies cloud.md to add oci to the list.
Adds oci_hoodie.md with detailed docs on using oci.
=> [HUDI-3551] Documentation for the Oracle Cloud Infrastructure (oci) Object Storage URI scheme

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/DropHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDropTable.scala
If a hudi table directory is lost on DFS due to some maloperation and cannot restore, user cannot drop it from SQL interface any more. We may provide an easy way for user to drop the table and do cleanup work. 
When resolving DropTableCommand, Spark analyzer retrieves schema of underlying table relation. Currently HoodieCatalogTable queries HoodieTableMetaClient for table schema, which cannot be constructed if table directory is broker/lost.
- Adjust HoodieCatalogTable -- returns table schema without dependency on underlying filesystem.
- *Added tests*
=> [HUDI-4149] Drop-Table fails when underlying table directory is broken

packaging/hudi-aws-bundle/pom.xml, packaging/hudi-aws-bundle/src/main/java/org/apache/hudi/aws/bundle/Main.java, packaging/hudi-integ-test-bundle/pom.xml, packaging/hudi-spark-bundle/pom.xml, packaging/hudi-utilities-bundle/pom.xml, packaging/hudi-utilities-slim-bundle/pom.xml, pom.xml
Adds a new bundle where aws-specific dependencies are shaded. It is meant to be used along with other bundles e.g. hudi-utilities-bundle when running deltastreamer with DynamoDB as lock provider.
Manually verified by running the `hudi-integ-test-bundle` along with `hudi-aws-bundle` for multi-writer setup with DynamoDB lock provider. Verfied the logs and DynamoDB table got populated.
=> [HUDI-4011] Add hudi-aws-bundle

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java, hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/index/bloom/TestFlinkHoodieBloomIndex.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/RocksDbBasedFileSystemView.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
The timeline refresh invokes the fs view #sync, which has two actions now:
1. reload the timeline of the fs view, so that the nest fs view request is based on this timeline metadata
2. if this is a local fs view, clear all the local states or if this is a remote fs view, send request to sync the remote fs view
But, let's see the construction, the meta client is instantiated freshly so the timeline is already the latest,
the table is also constructed freshly, so the fs view has no local states, that means, the #sync is unnecessary totally.
Removes the timeline refresh has a benifit: if avoids unncecessary #refresh of the remote fs view, if all the clients send request to
- *Please review …
=> [HUDI-4167] Remove the timeline refresh with initializing hoodie table

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
=> [HUDI-4183] Fix using HoodieCatalog to create non-hudi tables

website/src/css/custom.css, website/src/theme/BlogPostItem/index.js
The images earlier had distorted width so fixed their sizing so that they look clear. 
Removed read time from blogs list page such that it will only be visible in the blogs page
Made the tags black by default and blue color when onHover. 
*(or)*
(or)
This change added tests and …
=> [MINOR][UI]Resized the blog images , tags onHover:blue, readingTime only visible in blogs page

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
fixes #5730 
The order of hive partition was not respected
=> [HUDI-4187] Fix partition order in aws glue sync

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteMarkerProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallProcedure.scala
This change add `DeleteMarker` procedure to Hudi Spark's call procedure supprot.
- Add `DeleteMarkerProcedure` class to support `call delete_marker` SQL command.
- Added UT “Test Call delete_marker Procedure” in `TestCallProcedure`.
=> [HUDI-4168] Add Call Procedure for marker deletion

packaging/hudi-aws-bundle/pom.xml, packaging/hudi-datahub-sync-bundle/pom.xml, packaging/hudi-flink-bundle/pom.xml, packaging/hudi-gcp-bundle/pom.xml, packaging/hudi-hadoop-mr-bundle/pom.xml, packaging/hudi-hive-sync-bundle/pom.xml, packaging/hudi-integ-test-bundle/pom.xml, packaging/hudi-kafka-connect-bundle/pom.xml, packaging/hudi-presto-bundle/pom.xml, packaging/hudi-spark-bundle/pom.xml, packaging/hudi-timeline-server-bundle/pom.xml, packaging/hudi-trino-bundle/pom.xml, packaging/hudi-utilities-bundle/pom.xml, packaging/hudi-utilities-slim-bundle/pom.xml
This PR addresses the `ClassNotFoundException` for HBase classes from `hbase-protocol` (which are not included in the bundles), reported by #5496.
- Add the entry of `org.apache.hbase:hbase-protocol` as an `include` rule for shading in the bundles
After this change, by running the following command to check the shaded classes, the proto classes are found:
```
> jar tf packaging/hudi-spark-bundle/target/hudi-spark3.2-bundle_2.12-0.12.0-SNAPSHOT.jar | grep org/apache/hudi/org/apache/hadoop/hbase/protobuf
...
org/apache/hudi/org/apache/hadoop/hbase/protobuf/generated/AuthenticationProtos$TokenIdentifier.class
...
```
=> [HUDI-4190] Include hbase-protocol for shading in the bundles

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java, hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java, hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java, hudi-common/src/main/java/org/apache/hudi/util/Lazy.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestTableSchemaResolverWithSparkSQL.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
As has been outlined in HUDI-4176, we've hit a roadblock while testing Hudi on a large dataset (~1Tb) having pretty fat commits where Hudi's commit metadata could reach into 100s of Mbs.
As could be seen from the screenshot in such cases current implementation of `TableSchemaResolver` is doing a lot of repeated throw-away computations reading `HoodieCommitMetadata` (during init, fetching table's schema, fetching table's internal schema, etc).
Given the size some of ours commit metadata instances Spark's parsing and resolving phase (when `spark.sql(...)` is involved, but before returned `Dataset` is dereferenced) starts to dominate …
=> [HUDI-4176] Fixing `TableSchemaResolver` to avoid repeated `HoodieCommitMetadata` parsing

hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieVirtualKeyInfo.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeSplit.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
When Non partitioned key gen is used with virtual keys, read path could break since partition path may not exist. Fixing that in this patch. 
- Fixed generating virtual key info on the read path. 
Added test to 
- TestHoodieParquetInputFormat to validate the fix.
=> [HUDI-4171] Fixing Non partitioned with virtual keys in read path

rfc/rfc-53/rfc-53.md
=> [MINOR][RFC-53] Fix typos

hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java, hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileReader.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java, hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/partial-column-stats-index-table.json, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
- Key fetched from metadata table especially from base file reader is not sorted. and hence may result in throwing NPE (key prefix search) or unnecessary seeks to starting of Hfile (full key look ups). Fixing the same in this patch. This is not an issue with log blocks, since sorting is taking care within [HoodieHfileDataBlock](https://github.com/apache/hudi/blob/7da97c8096ad4eabb49b42c86013679ed5009451/hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java#L211). 
- Commit where the sorting was mistakenly reverted https://github.com/apache/hudi/pull/5208/
- Sorting list of keys and key prefixes to be looked up with base file reader in metadata table.
- Fixed one of the test in TestColStatsIndex. 
- Verifying the sort fix is going to be hard as it has …
=> [HUDI-4200] Fixing sorting of keys fetched from metadata table

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/JFunction.scala, hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSparkSessionExtension.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_1Adapter.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/hudi/ResolveHudiAlterTableCommand312.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/hudi/Spark3DefaultSource.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/adapter/Spark3_2Adapter.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/ResolveHudiAlterTableCommandSpark32.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark3Analysis.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieInternalV2Table.scala
There are multiple issues with our current DataSource V2 integrations: b/c we advertise Hudi tables as V2, Spark expects it to implement certain APIs which are not implemented at the moment, instead we're using custom Resolution rule (in HoodieSpark3Analysis) to instead manually fallback to V1 APIs. This poses following problems:
1. It doesn't fully implement Spark's protocol: for ex, this rule doesn't cache produced `LogicalPlan` making Spark re-create Hudi relations from scratch (including doing full table's file-listing) for every query reading this table. However, adding the caching in that sequence is not an option, since V2 …
=> [HUDI-4178] Addressing performance regressions in Spark DataSourceV2 Integration

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/SqlKeyGenerator.scala
=> [HUDI-4213] Infer keygen clazz for Spark SQL

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Skip table config validatiton if save mode is set to Overwrite
Check the save mode when doing validating
TestHoodieSparkSqlWriter. testValidateTableConfigWithOverwriteSaveMode
=> [HUDI-3889] Do not validate table config if save mode is set to Overwrite

hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
- Looks like getAllPartitionPaths have regressed in perf from 0.9.0 to 0.11.0. I could able to triage it to newly written code where in "isExists()" is called to determine Hoodie partition metadata. So, reverting the change to how it was before. 
Offending commit is https://github.com/apache/hudi/pull/4643
I tried listing a table with 10k partitions. 0.9.0 is taking 85 to 90 secs, while 0.11.0 took ~800 secs. 
HoodiePartitionMetadata.hasPartitionMetadata is taking roughly 50 to 60% when profiled. With the fix in this patch, listing took ~90 secs. 
- Fixing getAllPartitionPaths for FileSystemBackedMetadata.
*(or)*
This pull request is already covered by existing …
=> [HUDI-4221] Fixing getAllPartitionPaths perf hit w/ FileSystemBackedMetadata

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataTableWithSparkDataSource.scala
When reading the metadata table directly with the metadata table path in Spark, i.e., `spark.read.format("hudi").load("<base_path>/.hoodie/metadata/").show`, it throws `NullPointerException` from `getLogRecordScanner`:
```
  at org.apache.hudi.metadata.HoodieBackedTableMetadata.getLogRecordScanner(HoodieBackedTableMetadata.java:484)
  at org.apache.hudi.HoodieMergeOnReadRDD$.scanLog(HoodieMergeOnReadRDD.scala:342)
  at org.apache.hudi.HoodieMergeOnReadRDD$LogFileIterator.<init>(HoodieMergeOnReadRDD.scala:173)
  at org.apache.hudi.HoodieMergeOnReadRDD$RecordMergingFileIterator.<init>(HoodieMergeOnReadRDD.scala:252)
  at org.apache.hudi.HoodieMergeOnReadRDD.compute(HoodieMergeOnReadRDD.scala:101)
  at …
```
=> [HUDI-4223] Fix NullPointerException from getLogRecordScanner when reading metadata table

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
When reading the metadata table directly with the metadata table path in Spark, i.e., `spark.read.format("hudi").load("<base_path>/.hoodie/metadata/").show`, it throws NullPointerException from when creating the HFile reader:
```
at org.apache.hudi.org.apache.hadoop.hbase.io.hfile.CacheConfig.<init>(CacheConfig.java:178)
at org.apache.hudi.org.apache.hadoop.hbase.io.hfile.CacheConfig.<init>(CacheConfig.java:167)
at org.apache.hudi.org.apache.hadoop.hbase.io.hfile.CacheConfig.<init>(CacheConfig.java:163)
at org.apache.hudi.HoodieBaseRelation$.$anonfun$createHFileReader$1(HoodieBaseRelation.scala:531)
at org.apache.hudi.HoodieBaseRelation.$anonfun$createBaseFileReader$1(HoodieBaseRelation.scala:482)
at …
```
=> [HUDI-4205] Fix NullPointerException in HFile reader creation

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroSchemaConverter.java
=> [MINOR]  fix AvroSchemaConverter duplicate branch in 'switch'

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
This pull request strip extra spaces when creating new configuration.
When using flink-sql to create a table, if the key of an option contains spaces, the option will be invalid.
Example：
If option ‘hive_sync.mode’ has more spaces, the table will not be sync with hms.
- Modify `fromMap` function in `FlinkOptions` class.
This pull request is a trivial rework without any test coverage.
=> [HUDI-4227] Strip extra spaces when creating new configuration

hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieOrcReaderWriter.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieReaderWriterBase.java
Fix flakey test testReaderFilterRowKeys in TestHoodieOrcReaderWriter
TestReaderFilterRowKeys needs to get the key from RECORD_KEY_METADATA_FIELD, but the writer in current UT does not populate the meta field and the schema does not contains meta fields. 
This fix writes data with schema which contains meta fields and calls writeAvroWithMetadata for writing.
This pull request is already covered by existing tests, TestHoodieOrcReaderWriter
=> [HUDI-3682] testReaderFilterRowKeys fails in TestHoodieOrcReaderWriter

hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
This pull request is to add UT for drop partition column, corresponding to [HUDI-3863](https://issues.apache.org/jira/browse/HUDI-3863).
- Add test case in TestHoodieDeltaStreamer
=> [HUDI-3863] Add UT for drop partition column in deltastreamer testsuite

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowRollbacksProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallProcedure.scala
This change add `ShowRollbacks` procedure to Hudi Spark's call procedure support.
Add `ShowRollbacksProcedure` class to support `call show_rollbacks` and `call show_rollback` SQL command.
- Added UT “Test Call show_rollbacks Procedure” in `TestCallProcedure`.
=> [HUDI-3499] Add Call Procedure for show rollbacks

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/payload/SqlTypedRecord.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
improve repeat init object in ExpressionPayload, it cose lots of cpu time
*(or)*
(or)
*(example:)*
=> [HUDI-4217] improve repeat init object in ExpressionPayload

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java
Remove useless targetTableName parameter in HoodieMultiTableDeltaStreamer 
In `HoodieMultiTableDeltaStreamer`, multiple target table names are configured by the parameter `hoodie.deltastreamer.ingestion.tablesToBeIngested`, and the parameter `--target-table` is not actually used, but it is a required item, which is very confusing, so I think it is reasonable to remove this parameter
*(or)*
(or)
*(example:)* …
=> [HUDI-4265] Deprecate useless targetTableName parameter in HoodieMultiTableDeltaStreamer

hudi-common/src/main/java/org/apache/hudi/common/index/HoodieIndex.java, hudi-common/src/main/java/org/apache/hudi/common/index/HoodieIndexType.java, hudi-spark-datasource/hudi-spark/src/main/antlr4/org/apache/hudi/spark/sql/parser/HoodieSqlCommon.g4, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Index.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/parser/HoodieSqlCommonAstBuilder.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestIndexSyntax.scala
Support Create/Drop/Show/Refresh Index Syntax for Spark SQL, SQL Syntax:
```sql
-- Create Index
CREATE INDEX [IF NOT EXISTS] index_name ON [TABLE] table_name 
[USING index_type] 
(column_name1 [OPTIONS(key1=value1, key2=value2, ...)], column_name2 [OPTIONS(key1=value1, key2=value2, ...)], ...) 
[OPTIONS (key1=value1, key2=value2, ...)]
-- Drop Index
DROP INDEX [IF EXISTS] index_name ON [TABLE] table_name
-- Show Indexes
SHOW INDEXES {FROM | IN} [TABLE] table_name
-- Refresh Index
REFRESH INDEX index_name ON [TABLE] table_name
```
Notice:
- Create/Drop Index Syntax are forked from Spark 3.3.0-rc3, https://github.com/apache/spark/blob/branch-3.3/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBaseParser.g4
Reference：
- Hive sql index syntax： …
=> [HUDI-4165] Support Create/Drop/Show/Refresh Index Syntax for Spark SQL

hudi-cli/src/main/java/org/apache/hudi/cli/commands/ExportCommand.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ExportInstantsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestExportInstantsProcedure.scala
=> [HUDI-3507] Support export command based on Call Produce Command

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/CompactionAdminClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java, hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java
Some code can be reused in``rollbackInflightCllustering`` and ``rollbackInflightCompaction``.  After refactoring those codes, it's more easier to add other rollback actions.
- Remove ``BaseHoodieWriteClient.rollbackInflightClustering``
- Modify ``HoodieTable``, ``SparkRDDWriteClient``, ``HoodieActiveTimeline`` and so on
=> [HUDI-4275] Refactor rollback inflight instant for clustering/compaction to reuse some code

hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
Variable 'internalSchema' initializer 'InternalSchema.getEmptyInternalSchema()' is redundant 
*(or)*
(or)
*(example:)*
=> [MINOR][COMMON] Removing redundant variable initializer 'InternalSchema.getEmptyInternalSchema()'

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/event/WriteMetadataEvent.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/NonThrownExecutor.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Fix concurrency issue when endInput event is handled before the previous events. It could lead to removal of data files before the end of Flink job.
- added new method `executeSync` to `NonThrownExecutor`
- endInput is handled using `executeSync` in `StreamWriteOperatorCoordinator` now
- added unit test to `TestStreamWriteOperatorCoordinator`
=> [HUDI-4258] Fix when HoodieTable removes data file before the end of Flink job

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala, hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/execution/datasources/HoodieInMemoryFileIndex.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
If a hudi table is all logs files without any base files, following query will return 0
```scala
spark.read.format("hudi")
.load(basePath + "/*/*/*/*")
.count()
```
*(or)*
(or)
*(example:)* …
=> [HUDI-4173] Fix wrong results if the user read no base files hudi table by glob paths

hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java
fix problems about the command 'commits sync' description does not match.
=> [HUDI-4251] fix problems about the command 'commits sync' description does not match.

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCommitsCommand.java
Fix hudi-cli rollback failure with rollbackUsingMarkers option
- Call the correct method in SparkMain when rollbackUsingMarkers option is provided
=> [HUDI-4177] Fix hudi-cli rollback with rollbackUsingMarkers method call

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
=> [HUDI-4270] Bootstrap op data loading missing

hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java, hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFSViewWithClustering.java, hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
The fs view API `fetchLatestBaseFiles` is being used in presto-hive connector and it did not filter out clustered filegroups so the query would have duplicates in result. This PR fixes that behavior.
- Filter out replaced (clustered) file groups in `fetchLatestBaseFiles`
- Improved an existing UT to cover this API.
=> [HUDI-4290] Fix fetchLatestBaseFiles to filter replaced filegroups

website/docs/configurations.md, website/docs/quick-start-guide.md, website/versioned_docs/version-0.10.1/configurations.md, website/versioned_docs/version-0.11.0/configurations.md
[Externalized config file](https://hudi.apache.org/docs/0.10.0/configurations#externalized-config-file) documentation is missing in 0.10.1 or later versions. Added it in this PR and also added a link to it in the quickstart guide.
*(or)*
(or)
*(example:)*
=> [DOCS] Add externalized confilg file doc in latest versions

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
We check whether the rollback is successful by checking whether the file name contains commit instanceTime in testRollbackWithDeltaAndCompactionCommit, but the instanceTime string is too short, it may appear in the file name.
It's not easy to reproduce, this is the log I copy from Jira.
```
2022-03-29T01:30:26.3550882Z org.opentest4j.AssertionFailedError: There files should have been rolled-back when rolling back commit 002 but are still remaining. Files: [file:/tmp/junit5890929166894435504/2015/03/16/00264b80-ca3f-4aaa-80fc-fedfe4c72ee5-0_1-1393-4266_001.parquet] ==> expected: <0> but was: <1>
```
This fix lengthens the …
=> [HUDI-3735] TestHoodieSparkMergeOnReadTableRollback is flaky

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/StatsFileSizeProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/StatsWriteAmplificationProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestStatsProcedure.scala
=> [HUDI-3512] Add call procedure for StatsCommand

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
Fix TestHoodieSparkSqlWriter.testSchemaEvolutionForTableType failed random
the reason for it is that:
1）when we use glob path to read hudi table (like spark.read.format("hudi").load("/tmp/tableName/*/*/*")).   spark will infer parquet schema auto,
2）when evolution happen,  hoodie table may exist different schema parquet files,  spark choose a parquet file  randomly to infer schema
3）once spark choose a old parquet file，an old schema will be used which is wrong.
Therefore  we should specify the schema to the latest commit schema since the table schema evolution.
This pull request is a …
=> [HUDI-4296] fix the bug that TestHoodieSparkSqlWriter.testSchemaEvolutionForTableType is flaky

azure-pipelines.yml
To avoid potential CI build errors like 
```
2022-06-24T08:51:53.7477185Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project hudi-hadoop-hive-docker: An Ant BuildException has occured: Warning: Could not find file /home/vsts/work/1/s/packaging/hudi-utilities-bundle/target/hudi-utilities-bundle_2.11-0.12.0-SNAPSHOT.jar to copy.
2022-06-24T08:51:53.7479039Z [ERROR] around Ant part ...<copy file="/home/vsts/work/1/s/docker/hoodie/hadoop/hive_base/../../../../packaging/hudi-utilities-bundle/target/hudi-utilities-bundle_2.11-0.12.0-SNAPSHOT.jar" tofile="target/hoodie-utilities.jar"/>... @ 7:203 in /home/vsts/work/1/s/docker/hoodie/hadoop/hive_base/target/antrun/build-main.xml
```
=> [HUDI-4317] Remove -T option from CI build

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/parser/HoodieSpark3_2ExtendedSqlParser.scala
In `HoodieSpark3_2ExtendedSqlAstBuilder`, there are three places where the syntax is not supported, which causes sql to report an error in the parse stage.
```
visitInsertOverwriteDir
visitInsertOverwriteHiveDir
withRepartitionByExpression
```
We can avoid exceptions, so we can also use `delegate.parsePlan`.
- *Spark3.2 custom parser should not throw exception*
- *add UT.*
=> [HUDI-4309] Spark3.2 custom parser should not throw exception

hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
Several PRs have supported using the configuration `hoodie.common.spillable.diskmap.type` to decide which diskmap to use before constructing the `HoodieMergedLogRecordScanner`.
But there are several places where such a configuration is not supported.
https://issues.apache.org/jira/browse/HUDI-2044
https://issues.apache.org/jira/browse/HUDI-4151
- *Support for spillable diskmap configuration when constructing HoodieMergedLogRecordScanner*
=> [HUDI-4316] Support for spillable diskmap configuration when constructing HoodieMergedLogRecordScanner

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
When using other CatalogPlugin with name leesf along with HoodieCatalog, the sql for the following
`insert into leesf.db.table select id, name from hudi_db.hudi_table`, the BaseSpark3Adapter#toTableIdentifier method will throw the following exception 
```
org.apache.spark.sql.AnalysisException: leesf.db.table is not a valid TableIdentifier as it has more than 2 name parts.
    at org.apache.spark.sql.errors.QueryCompilationErrors$.identifierHavingMoreThanTwoNamePartsError(QueryCompilationErrors.scala:1394)
```
Catch exception in BaseSpark3Adapter#toTableIdentifier. 
=> [HUDI-4315] Do not throw exception in BaseSpark3Adapter#toTableIdentifier

hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/SchemaProvider.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunBootstrapProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowBootstrapMappingProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowBootstrapPartitionsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestBootstrapProcedure.scala
=> [HUDI-3504] Support bootstrap command based on Call Produce Command

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
As https://issues.apache.org/jira/projects/HUDI/issues/HUDI-4287 mentioned
Not only in the streaming rollback but also batch write , we should bootstrap the
ckp meta after all write task is ready . And when write tasks failed or first time run
clean the ckp meta path
step to reproduce
- job start with time 1 instant1 
- task write failed trigger flink restart
- abort instant1 as instant1.abort
- start to rollback instant1
- write task bootstrap ready and load the ckpMeta with instant1.inflight and instant1.abort
- flushbucket with instant1 
- end rollback instant1 delete instant1 relate data files
- start instant2
data lose
This pull request is a trivial rework …
=> [HUDI-4311] Fix Flink lose data on some rollback scene

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
This test flakes only when bootstrap base files cleaning is also enabled. The test data has two partitions and clean planner tries to find eligible files for cleaning with parallelism defined by `Math.min(#partitions, config#CLEANER_PARALLELISM_VALUE)`, in this case it becomes two. But, from the logs it appears as though once in a while, an executor is lost and hence the plan does not have an eligible file for one of the partitions. In order to fix the flakiness, this PR does two things:
- Separate out the cleaner test with bootstrap base file cleaning to a separate UT, instead of a parameterized test.
- Set cleaner parallelism to 1 for more predictability.
Executor log for a successful run:
```
48634 [Executor task launch worker for task 33] WARN …
```
=> [HUDI-4291] Fix flaky TestCleanPlanExecutor#testKeepLatestFileVersions

hudi-spark-datasource/hudi-spark/src/main/antlr4/org/apache/hudi/spark/sql/parser/HoodieSqlCommon.g4, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallCommandParser.scala
fix use `spark.sql("call show_commits(table => 'delete_error_test', limit => 10);").show(false)` with ';' cause parse error
*(or)*
(or)
*(example:)*
=> [HUDI-4325] fix spark sql procedure cause ParseException with semicolon

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
=> [HUDI-4332] The wrong current instant may cause file deletion in AppendWriteFunction

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/util/DataTypeUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java, hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java, hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
Currently after #4253 no matter whether the user specified it explicitly or was relying on a default value this config value will be overridden (ie potentially reverting what have been specified by the user). As such, there's no way presently to enforce this config on the write side if your schema contains `DecimalType` fitting into the range. 
Instead the behavior should be to only override _default_ config value in cases when there's a `DecimalType` of expected range, and if this config have been specified by the user -- it should not be overridden.
- Fixed sequence determining whether Parquet's legacy-format writing property …
=> [HUDI-4320] Make sure `HoodieStorageConfig.PARQUET_WRITE_LEGACY_FORMAT_ENABLED` could be specified by the writer

hudi-aws/pom.xml, hudi-cli/pom.xml, hudi-client/hudi-client-common/pom.xml, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/client/http/HoodieWriteCommitHttpCallbackClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogHttpClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogReporter.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/callback/http/TestCallbackHttpClient.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/datadog/TestDatadogHttpClient.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/datadog/TestDatadogReporter.java, hudi-gcp/pom.xml, hudi-integ-test/pom.xml, hudi-kafka-connect/pom.xml, hudi-spark-datasource/hudi-spark/pom.xml, hudi-sync/hudi-adb-sync/pom.xml, hudi-sync/hudi-datahub-sync/pom.xml, hudi-sync/hudi-hive-sync/pom.xml, hudi-timeline-service/pom.xml, hudi-utilities/pom.xml, packaging/hudi-integ-test-bundle/pom.xml, packaging/hudi-kafka-connect-bundle/pom.xml, packaging/hudi-timeline-server-bundle/pom.xml, pom.xml
Upgrades hudi to log4j2 for future compatibility and for security updates.
Pull request still WIP, testing with integration test framework now
=> [HUDI-1176] Upgrade hudi to log4j2

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CreateSavepointsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteSavepointsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackSavepointsProcedure.scala
Fix HUDI-4334: close SparkRDDWriteClient after usage in Create/Delete/RollbackSavepointsProcedure
- Close SparkRDDWriteClient in finally after try-catch in Create/Delete/RollbackSavepointsProcedure
=> [HUDI-4334] close SparkRDDWriteClient after usage in Create/Delete/RollbackSavepointsProcedure

hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java
When users trigger 'commit rollback' for a committed instant, it will throw followed exception when set rollbackUsingMarkers 
true as default.
We may need a common strategy for rollback action either rolling back an uncompleted instant or a finished commit.
Also users could set rollbackUsingMarkers on demands for better performance when rolling back an uncompleted instant
```
1643654 [Thread-55] INFO  org.apache.hudi.cli.utils.InputStreamConsumer  - 22/03/29 18:00:03 INFO Executor: Adding file:/private/var/folders/61/77xdhf3x0x9g3t_vdd1c9_nwr4wznp/T/spark-97304f5c-e7f7-41b3-a535-c646b6ed02c6/userFiles-1d3d3fa9-f552-4939-b630-f0bc3bad7ed0/jetty-http-9.4.15.v20190215.jar to class loader
1643851 [Thread-55] INFO  org.apache.hudi.cli.utils.InputStreamConsumer  - 22/03/29 18:00:04 INFO …
```
=> [MINOR] Make CLI 'commit rollback' using rollbackUsingMarkers false as default

hudi-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
This PR aims to let Hudi external config support Spark cluster mode. In Spark cluster mode, the Spark driver would run on a random node within the cluster. Hudi external config file only exists in the master node and this would cause a file not found issue when the Spark driver is not running on the master node.
In this PR, when loading the external config file, it would first try to load the hudi-defaults.conf from the class loader. To add hudi-defaults.conf to the Spark class loader, similar to hive-site.xml, we can add hudi-defaults.conf through spark.yarn.dist.files option.
- *Modify AnnotationLocation …
=> [HUDI-4331] Allow loading external config file from class loader

hudi-common/src/main/java/org/apache/hudi/common/util/StringUtils.java, hudi-common/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
Fix the bug that records will be overwrited incorrectly, when the type of recordkey or primarykey is binary.
- Modify objToString in StringUtils, and add test cases
=> [HUDI-4336] Fix records overwritten bug with binary primary key

hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java
This is a follow-up to #2070, retrying bind does not seem to take effect, because `miniDfsCluster` is not initialized, calling the stop method we will get a null pointer.
```
2022-06-23T18:59:25.1514164Z java.lang.NullPointerException
2022-06-23T18:59:25.1515051Z 	at org.apache.hudi.common.testutils.minicluster.HdfsTestService.stop(HdfsTestService.java:106)
2022-06-23T18:59:25.1516107Z 	at org.apache.hudi.common.testutils.minicluster.HdfsTestService.start(HdfsTestService.java:96)
2022-06-23T18:59:25.1517359Z 	at org.apache.hudi.utilities.testutils.UtilitiesTestBase.initTestServices(UtilitiesTestBase.java:118)
2022-06-23T18:59:25.1518418Z 	at org.apache.hudi.utilities.transform.TestSqlFileBasedTransformer.initClass(TestSqlFileBasedTransformer.java:52)
```
- *Added a loop when creating HDFS …
=> [MINOR] Following #2070, Fix BindException when running tests on shared machines.

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
=> [HUDI-4346] Fix the params of bulkInsertAsRow not update BULKINSERT_ARE_PARTITIONER_RECORDS_SORTED

hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java
Remove mandatory check of partiton path for cli command
=> [HUDI-3984] Remove mandatory check of partiton path for cli command

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/UpgradeOrDowngradeProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
This change add `UpgradeOrDowngradeProcedure` to Hudi Spark's call procedure support.
Add `ShowArchivedCommitsProcedure`class to support call `upgrade_table`and `downgrade_table` SQL command.
- Added UT “Test Call downgrade_table and upgrade_table Procedure” in `TestUpgradeOrDowngradeProcedure`.
=> [HUDI-3505] Add call procedure for UpgradeOrDowngradeCommand

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ListMetadataFilesProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ListMetadataPartitionsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/MetadataCreateProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/MetadataDeleteProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/MetadataInitProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataStatsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ValidateMetadataFilesProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
=> [HUDI-3511] Add call procedure for MetadataCommand

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ConfigUtils.java, hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestConfigUtils.java
=> [HUDI-3730] Add ConfigTool#toMap UT

hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java
To align with other occurrences in the codebase, use "className" instead of FQCN.
=> [MINOR] Improve variable names

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowFsPathDetailProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowFsPathDetailProcedure.scala
|   path_num   |  file_num    | storage_size     | storage_size(unit)     |   storage_path   |  space_consumed    |  quota    |   space_quota   |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 0 | 1 | 434867 | 424.67KB | file:/private/var/folders/9d/qtc20f6x197431jvthgs58zr0000gn/T/spark-00064bc3-a260-4efc-a62c-5e9f64fad7c5/h0/1b73b522-3369-4fc7-a97d-801749466e4e-0_0-27-39_20220705044036342.parquet | 434867 | -1 | -1 |
| 0 | 1 | 434821 | 424.63KB | file:/private/var/folders/9d/qtc20f6x197431jvthgs58zr0000gn/T/spark-00064bc3-a260-4efc-a62c-5e9f64fad7c5/h0/1b73b …
=> [HUDI-4359] Support show_fs_path_detail command on Call Produce Command

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
the error due to the wrong configuration `hoodie.datasource.hive_sync.database`
Example:
```sql
use hudi;
create table test_hudi_table using hudi
partitioned by(dt)
options(
preCombineField = 'ts',
type = 'cow'
)
AS
select 1 as id, 'a1' as name, 10 as price, 1000 as ts,'2022-07-03' as dt;
```
two tables is created by sync hive;`EXTERNAL default.test_hudi_table` and `hudi.test_hudi_table`,And added a partition in `default.test_hudi_table` but the`hudi.test_hudi_table`  didn't,So it is empty when querying the table `hudi.test_hudi_table`
```sql
use hudi;
create table test_hudi_table_2 using hudi
options(
preCombineField = 'ts',
type = 'cow'
)
AS
select 1 as id, 'a1' as name, 10 as price, 1000 as ts,'2022-07-03' as dt;
```
two tables is created by sync …
=> [HUDI-4356] Fix the error when sync hive in CTAS

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
This PR fix a repeated calculation bug when Merge with precombine expression. 
Detail is in https://issues.apache.org/jira/browse/HUDI-4219
When build sourceDF with PreCombine field, fix the equality judging between targetPreCombineField and sourceExpression. PreCombine expression like "col=s.col+2" used to be recognized not equal, it cause that precombine expression will be calculated repeatedly.
- *Manually verified the change by running a merge on cluster.*
=> [HUDI-4219] Merge Into when update expression "col=s.col+2" on precombine cause exception

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/parser/HoodieSpark3_2ExtendedSqlAstBuilder.scala, hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/parser/HoodieSpark3_2ExtendedSqlParser.scala
like https://issues.apache.org/jira/browse/HUDI-4309 describe `In HoodieSpark3_2ExtendedSqlAstBuilder, there are three places where the syntax is not supported, which causes sql to report an error in the parse stage.`
- support repartition for `timetravel's` sql
- before upgrade to spark3.3, only timetravel sql use `HoodieSpark3_2ExtendedSqlAstBuilder`
*(or)*
(or)
*(example:)*
- *Manually verified the change by running a …
=> [HUDI-4309] fix spark32 repartition error

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Aims to resolve the following bugs in AWS Glue Meta Sync post schema evolution.
* CreateTable filters out the partition column but updating the table doesn't filter the schema which leads to having duplicate columns and incompatible metadata in Glue.
* Table properties not getting updated when the schema changes because of the incorrect `nonEmpty` predicate.
* Update table parameters function overrides the `EXTERNAL` and `last_commit_time_sync` causing to reload all the partitions.
* Separates `getColumnsFromSchema` logic into a method that provides common functionality to get the columns in a consistent manner for both creating and updating tables (Excluding partition columns).
* Replaces `nonEmpty(tableProperties)` with `isNullOrEmpty(tableProperties)` to make sure tableProperties are …
=> [HUDI-4335] Bug fixes in AWSGlueCatalogSyncClient post schema evolution.

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java, hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala, hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/action/InternalSchemaMerger.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/InternalSchemaUtils.java, hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java, hudi-common/src/test/java/org/apache/hudi/internal/schema/utils/TestAvroSchemaEvolutionUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
…d add new fields.
Improve schema reconciliation to make it more flexible in presence of full schema evolution being enabled.
just like the feature  https://docs.delta.io/latest/delta-update.html#-merge-schema-evolution
Desired behavior:
1) incoming data has missing columns that were already defined in the table –> null values will be injected into missing columns 
2) incoming data contains new columns not defined yet in the table -> columns will be added to the table schema (incoming dataframe?)
3) incoming data has missing columns that are already defined in the table and new columns not yet defined in the table -> new columns …
=> [HUDI-4276] Reconcile schema-inject null values for missing fields and add new fields

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/DeDupeType.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/DedupeSparkJob.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/SparkHelpers.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairAddpartitionmetaProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairCorruptedCleanFilesProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairDeduplicateProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairMigratePartitionMetaProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairOverwriteHoodiePropsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/resources/table-config.properties, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala
=> [HUDI-3500] Add call procedure for RepairsCommand

conf/hudi-defaults.conf.template, docker/demo/config/hoodie-incr.properties, docker/demo/sparksql-incremental.commands, hudi-common/src/test/java/org/apache/hudi/common/util/TestDFSPropertiesConfiguration.java, hudi-common/src/test/resources/external-config/hudi-defaults.conf, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-kafka-connect/demo/config-sink-hive.json, hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectConfigs.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfigHolder.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveQueryDDLExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/JDBCExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/HiveSyncGlobalCommitParams.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDropPartitionsTool.java
Remove deprecated `useJdbc` config. Users should move to setting `syncMode` instead.
=> [HUDI-4324] Remove use jdbc config from hudi sync

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java, hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncConfig.java
Infer database and table names from table configs. Make the arguments optional in sync tool.
=> [HUDI-4323] Make database table names optional in sync tool

pom.xml
Bump Flink versions to 1.14.5 and 1.15.1
- *Change Flink versions in pom.xml*
This pull request is already covered by existing tests, such as *all flink tests*.
=> [HUDI-4379] Bump Flink versions to 1.14.5 and 1.15.1

hudi-common/src/main/java/org/apache/hudi/common/table/log/InstantRange.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/WriteProfiles.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java
=> [HUDI-4391] Incremental read from archived commits for flink

hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/replication/TestHiveSyncGlobalCommitTool.java
To unblock landing PRs. Proper fix in https://github.com/apache/hudi/pull/6110/
=> [MINOR] Disable TestHiveSyncGlobalCommitTool

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
=> [HUDI-4403] Fix the end input metadata for bounded source

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandle.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
=> [HUDI-4408] Reuse old rollover file as base file for flink merge handle

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Fix the issue that COW tables cannot use `globPaths` or `hoodie.datasource.read.paths` to read files
Also add more tests to cover the usage of `hoodie.datasource.read.paths`.
```scala
spark.read.format("org.apache.hudi")
.option(DataSourceReadOptions.QUERY_TYPE.key, DataSourceReadOptions.QUERY_TYPE_SNAPSHOT_OPT_VAL)
.option(DataSourceReadOptions.READ_PATHS.key, "hdfs://test/testTable/.files")
.load()
```
1. HoodieFileIndex should also consider if glob.path is specified
2. Add more tests to cover `DataSourceReadOptions.READ_PATHS`
This pull request is a trivial rework / code cleanup …
=> [HUDI-4170] Make user can use hoodie.datasource.read.paths to read necessary files

hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
- Honoring file group count for metadata partitions w/ AsyncIndexing flow. Prior to this patch, file group count as per the config was not honored for non FILES partition. This patch fixes it. 
- Fixed to honor the overriden file group count for non FILES partition in metadata table with Async Indexer. 
- TestHoodieIndexer.testColStatsFileGroupCount
- Manually verified for synchronous code path for instantiating column stats that file group count was honored.
=> [HUDI-4156] Fixing file group count issues with metadata partitions

hudi-flink-datasource/hudi-flink/pom.xml, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HiveSchemaUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogFactory.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/TypeInfoLogicalTypeVisitor.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/HoodieCatalogTestUtils.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
=> [HUDI-4416] Default database path for hoodie hive catalog

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ExpressionEvaluator.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
=> [HUDI-4372] Enable matadata table by default for flink

hudi-common/src/main/resources/hbase-site.xml
This PR changes the `hbase.defaults.for.version.skip` config to true instead of false as default in `hbase-site.xml` under `hudi-common/src/main/resources` to skip the HBase version check to avoid any inconvenience caused by the `RuntimeException` due to version mismatch if multiple versions of HBase library are present in the class path.
- Changes the `hbase.defaults.for.version.skip` config to true and adds notes in `hbase-site.xml` under `hudi-common/src/main/resources`
=> [HUDI-4401] Skip HBase version check

hudi-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSqlConf.scala
Currently when doing Hudi queries w/ Spark, it won't load the external configurations. Say if customers enabled metadata listing in their global config file, then this would let them actually query w/o metadata feature enabled. This PR fixes this issue and allows loading global configs during the Hudi reading phase.
- *Added a test case in [TestSqlConf.scala] to verify the change.*
=> [HUDI-3764] Allow loading external configs while querying Hudi tables with Spark

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
JIRA https://issues.apache.org/jira/browse/HUDI-4434
Contribute internal EMR patches to target goal of out of box experience for 0.12 on EMR 6.9.0 (for hudi-spark), for now disabling these two properties. 
Read optimized queries on Hudi 0.11 are failing with EMR spark with partition schema mismatch error, the root caused comes from the data prefetcher feature implemented by EMR Spark team. To target goal of out of box experience for hudi 0.12 on emr 6.9.0, the safest bet is to disable the data prefetcher functionality for Hudi.
This issue has been introduced since 0.11, because with this release Hudi has introduced its own …
=> [HUDI-4434] Disable EmrFS file metadata caching and EMR Spark's data prefetcher feature

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
This PR fixes the missing bloom filters in metadata table in the non-partitioned table due to incorrect record key generation.  Before this PR, the file name is wrong when generating the metadata payload for the bloom filter.  For example, below shows the file name used to construct the metadata payload:
```
Filename: 03656eb-c000-474b-945e-aa9298c3334d_1-0-1_0000001.parquet Bloom filter record key: DW/eaNVbRdo=xDmB/pnnQIMnCbUZywNZxw==
Filename: f1a759f-8e00-4cc4-8af0-676d3c892657_1-0-1_0000002.parquet Bloom filter record key: DW/eaNVbRdo=t/6nT2vbZbsGoSkZBCOKZA==
Filename: ca4aa60-2659-4fae-9d57-c4f51e8a7343_1-0-1_0000003.parquet Bloom filter record key: DW/eaNVbRdo=DsnvarlysKz9lJxfoZ81iA==
```
The file name misses the first character.  In Bloom Index, when doing a lookup in the metadata …
=> [HUDI-4400] Fix missing bloom filters in metadata table in non-partitioned table

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Row writer with multi-writer enabled has a NullPointerException. Fixing the same in this patch. 
- Row writer flow was not calling preWrite which is expected to be called for multi-writers. So, fixing that in this patch. 
- Added a simple test to TestHoodieSparkSqlWriter to test the bulk insert row writer w/ concurrency control configs.
- Verified multi-writer test with integ test framework locally w/ both writers ingesting via bulk_inserts.
=> [HUDI-4204] Fixing NPE with row writer path and with OCC

packaging/hudi-presto-bundle/pom.xml
- Upgrading protocol buffers version in presto bundle due to security vulnerability. 
- [CVE-2015-5237](https://github.com/advisories/GHSA-jwvw-v7c5-m82h) [CVE-2021-22570](https://github.com/advisories/GHSA-77rm-9x9h-xj3g) [CVE-2021-22569](https://github.com/advisories/GHSA-wrvw-hg22-4m67)
*(or)*
(or)
*(example:)* …
=> [HUDI-4247] Upgrading protocol buffers version for presto bundle

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CommitsCompareProcedure.scala
Fix result missing information issue in commits_compare Procedure.
Before fix:
After fix:
=> [MINOR] Fix result missing information issue in commits_compare Procedure

hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
=> [MINOR] Disable Flink compactor IT test

azure-pipelines.yml, hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/replication/TestHiveSyncGlobalCommitTool.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestService.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/TestCluster.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Reverts apache/hudi#6110
Revert due to skipping tests; it shouldn't be landed before all tests passing.
=> Revert "[HUDI-4437] Fix CI issue with TestHiveSyncTool"

hudi-common/src/main/java/org/apache/hudi/common/util/PartitionPathEncodeUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestFileIndex.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadOperator.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestShowPartitions.scala
When we define a table in Hive with a partitioning column, all NULL values within that column appear as `__HIVE_DEFAULT_PARTITION__`. It is the sentinel value which is understood by both Hive and Spark. Previously we used `default` string as the default partition value. That would result in casting errors as mentioned in HUDI-4303 or HUDI-4159. This PR fixes that behavior.
- Change default partition value to `__HIVE_DEFAULT_PARTITION__`.
- Fix tests.
*(or)*
(or)
*(example:)*
- *Added integration tests …
=> [HUDI-4303] Use Hive sentinel value as partition default to avoid casting err

conf/hudi-defaults.conf.template, docker/demo/config/hoodie-incr.properties, docker/demo/sparksql-incremental.commands, hudi-common/src/test/java/org/apache/hudi/common/util/TestDFSPropertiesConfiguration.java, hudi-common/src/test/resources/external-config/hudi-defaults.conf, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-kafka-connect/demo/config-sink-hive.json, hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectConfigs.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfigHolder.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveQueryDDLExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/JDBCExecutor.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/HiveSyncGlobalCommitParams.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDropPartitionsTool.java
This reverts commit 046044c83d6382d455cfb0ff5c1130ddf926fcf3.
Considering BWC in the next release, we revert this change. The plan is to batch remove deprecated user-facing configs at one go at a proper release time (e.g. 1.0.0).
=> Revert "[HUDI-4324] Remove use_jdbc config from hudi sync (#6072)"

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeRecordReaderUtils.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
JIRA https://issues.apache.org/jira/browse/HUDI-4435
For Avro to 1.10.2, bootstrap realtime table queries through inputformat would break w/ the following error:
```
org.apache.avro.AvroRuntimeException: Not a valid schema field: _hoodie_commit_seqno
```
This is because when converting Avro records to ArrayWritable, Hudi calls `avroToArrayWritable(Object value, Schema schema)` which would try to extract all the fields in the schema from Avro record. However, in some queries, not all the fields are required in the record, e.g. when enabling usesCustomPayload (which is enabled for bootstrap tables by default), only projection columns …
=> [HUDI-4435] Fix Avro field not found issue introduced by Avro 1.10.2

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
Segregating all the config flips in #5643 . This one changes the default bulk insert sort mode.
*(or)*
(or)
*(example:)*
=> [HUDI-4071] Make NONE sort mode as default for bulk insert

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
In our production env, the fresh based on the latest commit cause data loss for all kinds of corner cases, when there are async table service commit on the timeline, so revert this change before we prove that it is production ready and a valid promotion.
Here is a test screen shot:
=> [HUDI-4448] Remove the latest commit refresh for timeline server

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
=> [HUDI-4450] Revert the checkpoint abort notification

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
https://issues.apache.org/jira/browse/HUDI-4439 
Amazon CloudWatch reporter is broken for metadata enabled tables.
This appears to be broken since this commit: https://github.com/apache/hudi/commit/9797fdfbb27ca8f5f06875ad958b597becc27a8d. The commit makes metrics prefix configurable, changing it from the earlier way of using the table name directly. For metadata table, while publishing the metrics, this turns up as empty because the inference mechanism does not find table name in the HoodieConfig it is trying to lookup.
This breaks while publishing metrics to cloudwatch, since it cannot publish a Dimension with empty value.
This …
=> [HUDI-4439] Fix Amazon CloudWatch reporter for metadata enabled tables

hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieSyncValidateCommand.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ValidateHoodieSyncProcedure.scala
=> [HUDI-3510] Add sync validate procedure

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java, pom.xml
We occasionally see failures in CI due to the junit `TempDir` not being cleaned up. Other people have seen similar errors due to some references to the files in that dir not being closed properly. This PR updates the `SparkClientFunctionalTestHarness` to provide a single `FileSystem` instance per test and close it after the test completes.
- update `getFs()` method in `SparkClientFunctionalTestHarness` to return a single instance
- close `FileSystem` instance at end of tests with `@AfterEach` method in the test harness
=> [HUDI-4456] Close FileSystem in SparkClientFunctionalTestHarness 

hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
This PR restores the logging behavior in IT where stdout output is only logged for non-zero exit from commands in IT.
- Adjusts the logging behavior in `ITTestBase`
Only logging changes.
=> [MINOR] Only log stdout output for non-zero exit from commands in IT

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ColumnStatsIndices.java
=> [HUDI-4458] Add a converter cache for flink ColumnStatsIndices

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackToInstantTimeProcedure.scala
Based on [#6197](https://github.com/apache/hudi/pull/6197), Set `RollbackToInstantTimeProcedure`'s `ROLLBACK_USING_MARKERS_ENABLE` to `false` to pass ut.
*(or)*
(or)
*(example:)*
- …
=> [HUDI-4071] Match ROLLBACK_USING_MARKERS_ENABLE in sql as datasource

hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/replication/TestHiveSyncGlobalCommitTool.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestCluster.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestService.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Improve HiveTestService, HiveTestUtil, and related classes.
=> [HUDI-4455] Improve test classes for TestHiveSyncTool

hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkClientTestHarness.java, hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/MiniClusterUtil.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestInputPathHandler.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
Clean up resources from local hdfs cluster and zookeeper cluster.
=> [HUDI-4456] Clean up test resources

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieArchivalConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieFileGroup.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieFileGroup.java, hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/MockHoodieTimeline.java
This PR builds on top of #5350 
- So far, archival will stop at the first savepoint commit and will not proceed further. For users who may not be interested in incremental queries, but just "as of instant", we can let them proceed further by skipping just the savepoint commit. This opens up new opportunities for Hudi users. For eg, one can retain commits for years, by adding one savepoint per day for older commits (say > 30 days old).  And they can query hudi using "as of instant" for very old data. If not, one has to retain every commit and let archival stop at the first commit which may not be a good experience for users. 
- Had to fix one the core methods in HoodieTimeline with this change boolean `isBeforeTimelineStarts(String instant)`. Please do check the changes here. Prior to this …
=> [HUDI-3884] Support archival beyond savepoint commits

hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/payload/TestAWSDmsAvroPayload.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/AWSDmsTransformer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestAWSDatabaseMigrationServiceSource.java
* The payload classes from `hudi-common` get shaded inside `hudi-hadoop-mr-bundle` and are used at hive runtime . Hive realtime view is unable to reference `AWSDmsAvroPayload` as this class is bundled in `hudi-spark`.
* This change is to relocate `AWSDmsAvroPayload` from `hudi-spark` to `hudi-common`
=> [HUDI-4471] Relocate AWSDmsAvroPayload class to hudi-common

hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java, hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncConfig.java
- infer repeated sync configs from original configs
- `META_SYNC_BASE_FILE_FORMAT`
- infer from `org.apache.hudi.common.table.HoodieTableConfig.BASE_FILE_FORMAT`
- `META_SYNC_ASSUME_DATE_PARTITION`
- infer from `org.apache.hudi.common.config.HoodieMetadataConfig.ASSUME_DATE_PARTITIONING`
- `META_SYNC_DECODE_PARTITION`
- infer from `org.apache.hudi.common.table.HoodieTableConfig.URL_ENCODE_PARTITIONING`
- `META_SYNC_USE_FILE_LISTING_FROM_METADATA`
- infer from `org.apache.hudi.common.config.HoodieMetadataConfig.ENABLE`
As proposed in https://github.com/apache/hudi/blob/master/rfc/rfc-55/rfc-55.md#compatible-changes
=> [HUDI-4474] Infer metasync configs

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AwsGlueCatalogSyncTool.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java, packaging/hudi-aws-bundle/pom.xml
Some changes in https://github.com/apache/hudi/pull/5854/ broke BWC for some users. The PR makes the usage BWC.
- Keep constants in `HiveSyncConfig`.
- Revert back to `AwsGlueCatalogSyncTool` from `AWSGlueCatalogSyncTool`
=> [HUDI-3730] Make metasync configs backward compatible

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataFileSystemView.java
This PR fixes the performance problem of repeated data file reading and log merging in the metadata table.
In `HoodieBackedTableMetadata` which provides the metadata based on the metadata table, there is a flag `reuse` to control whether to reuse base file and log readers across multiple API calls.  If enabled, the readers are reused and the merged log records are cached inside the log reader so they can be returned immediately.  If disabled, the data file reading and log merging happen again from the cold load.  The Presto Hive connector uses `FileSystemViewManager.createInMemoryFileSystemView` to create file system view, and when metadata table is enabled, the `reuse` flag is set to false, causing repeated reading and poor performance during the query planning phase.
This PR flips the …
=> [HUDI-4469] Flip reuse flag to true in HoodieBackedTableMetadata to improve file listing

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieRealtimePath.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieCopyOnWriteTableInputFormat.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieMergeOnReadTableInputFormat.java
In Hudi 0.11.0 a lot of refactoring has been done to the `InputFormat` code for better organization and optimizations. As part of that `HoodieRealtimePath` class was introduced, which extends the standard hadoop Path and a method to determine whether the path `isSplitable` was introduced in the class. This logic does not take into account whether the real time path is for bootstrap split or not. It simply determines whether splitting is possible based on whether there is a base path (base parquet file).
When bootstrap feature was developed, it was a design decision to disable file splitting for bootstrap scenario because there is no …
=> [HUDI-4126] Disable file splits for Bootstrap real time queries (via InputFormat)

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/TransactionManager.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
=> [HUDI-4484] Add default lock config options for flink metadata table

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
=> [HUDI-4494] keep the fields' order when data is written out of order

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_1Adapter.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_2Adapter.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_3Adapter.scala
=> [MINOR] Minor changes around Spark 3.3 support

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystPlansUtils.scala, hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteTable.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestShowPartitions.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystPlanUtils.scala
In our internal benchmarks we've detected that there's a very clear performance gap b/w following sequences even though they are using essentially the same underlying infra:
1. Spark SQL: `INSERT INTO` statement
2. Writing via Spark DS
The issue turned out to be inadvertent dereferencing of the incoming `Dataset` into `RDD[Row]`, entailing the penalty of deserialization of every row. 
After resolving both of this code-paths have comparable runtime.
- Cleaning up shaping up flow to avoid unnecessary conversions
- Cleaning up schema reconciliation and evolution handling to fix improper nullability handling
- Avoiding the conversion …
=> [HUDI-4081][HUDI-4472] Addressing Spark SQL vs Spark DS performance gap

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
=> [HUDI-4499] Tweak default retry times for flink metadata table lock

hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
- We reverted the logic for getAllPartitionPaths in https://github.com/apache/hudi/pull/5829. But based on feedback, made some minor tweaks to the reverted code (leverage spark par for dir processing) and perf numbers are still holding good and infact better in some cases. 
Perf numbers from S3 listing: 
Listing a hudi table w/ 10k partitons with each partition having just 1 file. 
// Each value is avg from 10 runs. 
0.9.0: 11 to 12 secs. 
0.11.0: 120 to 140 secs.
master: 11 to 12 secs. 
this patch: 8 to 9 secs. 
Listing a hudi table w/ 40 partitions w/ each having ~ 1000 files. 
0.9.0: 900 to 1000 msec.
0.11.0: 700 to 850 ms
master: 930 to 1030 ms.
this patch: 200 to 240 ms. 
- Optimizing getAllPartitionPaths 
Already covered by existing tests.
Ran perf tests over S3.
=> [HUDI-4221] Optimzing getAllPartitionPaths 

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
=> [HUDI-4504] Disable metadata table by default for flink

hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
This PR improves file name extraction logic in metadata utils by adding a new util method.  This addresses https://github.com/apache/hudi/pull/6113#discussion_r929275152.
- Adds a new util method `FSUtils.getFileName`
- Refactors the logic of extracting file names in `HoodieTableMetadataUtil`
- Adds a unit test for the new util method
This change adds a new test as mentioned above.
=> [HUDI-4507] Improve file name extraction logic in metadata utils

docker/demo/config/test-suite/deltastreamer-hive-sync-presto.yaml, hudi-integ-test/pom.xml, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/DagUtils.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseQueryNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/HiveQueryNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/PrestoQueryNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/TrinoQueryNode.java, hudi-integ-test/src/test/resources/unit-test-cow-dag.yaml, packaging/hudi-integ-test-bundle/pom.xml, pom.xml
Just like HiveQueryNode, this PR adds query nodes for other engines such as Presto and Trino.
*(or)*
(or)
*(example:)*
=> [HUDI-4025] Add Presto and Trino query node to validate queries

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
Fixes the issue observed in #5702 .
Essentially, if lock is not null but its state has not yet transitioned to ACQUIRED, retry fails because the lock is no de-allocated. This PR fixes that.
*(or)*
(or)
*(example:)*
=> [HUDI-4518] Free lock if allocated but not acquired

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java
[HUDI-4510]  Repair config "hive_sync.metastore.uris" in flink sql hive schema sync is not effective
*(or)*
(or)
*(example:)* …
=> [HUDI-4510]  Repair config "hive_sync.metastore.uris" in flink sql hive schema sync is not effective

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
When "hoodie.archive.beyond.savepoint" is enabled, we can't support "restore" as there could be holes in the timeline. We have a [jira](https://issues.apache.org/jira/browse/HUDI-4500) to fix it properly. Until then, we need to throw exception when restore is attempted. 
- Failing restore in BaseHoodieWriteClient when "hoodie.archive.beyond.savepoint" is enabled.
- TestHoodieClientOnCopyOnWriteStorage#testRestoreWithSavepointBeyondArchival
=> [HUDI-4501] Throwing exception when restore is attempted with hoodie.arhive.beyond.savepoint is enabled

hudi-common/src/main/java/org/apache/hudi/common/util/DefaultSizeEstimator.java, hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordSizeEstimator.java, hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java, hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDBBasedMap.java
Let's say HoodieCleaner failed for any reason, if we rerun it, will throw the following exception. need to implement Serializable interface in ExternalSpillableMap.  there should be no side effects of adding Serializable interface
> 2/08/01 10:43:08 ERROR HoodieCleaner: Fail to run cleaning for hdfs://xx/user/xxxx/
org.apache.spark.SparkException: Task not serializable
at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:416)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:406)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
at …
=> [HUDI-4516] fix Task not serializable error when run HoodieCleaner after one failure

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Previously, we can not support more than 128 insert tasks in flink writer, since we use Flink's `StreamGraphGenerator.DEFAULT_LOWER_BOUND_MAX_PARALLELISM`, which is 128.
Add WRITE_BULK_INSERT_MAX_PARALLELISM configuration in `FlinkOptions`.
*(or)*
(or)
*(example:)*
- …
=> [HUDI-4477] Adjust partition number of flink sink task

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
…e to correctly sort and de duplicate data by PRECOMBINE_FIELD.
Signed-off-by: HunterXHunter <1356469429@qq.com>
*(or)*
(or)
*(example:)* …
=> [HUDI-4298] Mor table reading for base and log files lost sequence of events

.github/workflows/bot.yml, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java, hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestConvertFilterToCatalystExpression.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
Enabling full-suite of tests in "hudi-spark" module to run against all supported Spark versions.
Fixing Spark 3.3 `AvroSerializer` implementation to properly port Hudi's custom fixes to it.
See above 
=> [HUDI-4525] Fixing Spark 3.3 `AvroSerializer` implementation

hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java, hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncConfig.java
=> [HUDI-4447] fix no partitioned path extractor error when sync meta

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCLIUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CommitsCompareProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ExportInstantsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackToInstantTimeProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowArchivedCommitsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitFilesProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitPartitionsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitWriteStatsProcedure.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestNestedSchemaPruningOptimization.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/HoodieSparkProcedureTestBase.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestBootstrapProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCleanProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCommitsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCompactionProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCopyToTableProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestExportInstantsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestFsViewProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestHdfsParquetImportProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestHoodieLogFileProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestSavepointsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowFsPathDetailProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestStatsProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
=> [HUDI-4520] Support qualified table 'db.table' in call procedures

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
=> [HUDI-4487] support to create ro/rt table by spark sql

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCleanProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCleanProcedure.scala
=> [HUDI-4533] Fix RunCleanProcedure's ArrayIndexOutOfBoundsException

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
Signed-off-by: LinMingQiang <1356469429@qq.com>
*(or)*
(or)
*(example:)* …
=> [HUDI-4385] Support to trigger the compaction in the flink batch mode write.

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieOptionConfig.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
#6285 
*(or)*
(or)
*(example:)*
=> [HUDI-4530] fix default payloadclass in mor is different with cow

website/versioned_docs/version-0.11.1/hoodie_cleaner.md
This pull request is a description of the cleanup policy for KEEP_LATEST_BY_HOURS. Since this policy was implemented, and it works well, but the documentation has not been reflected, so it was updated on the latest documentation 0.11.1.
This pull request is a trivial rework without any test coverage.
=> [DOCS] Added the description of the cleaning policy

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
support retain hour cleaning policy for flink
this pr reference #5459
we need time based clean policy for flink streaming write to hudi,
although we can calculate retain_hour using retain_commits * checkpoint_time, we may modify the checkpoint_time sometimes, so it's nessary to add this.
=> [HUDI-4544] support retain hour cleaning policy for flink

hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
As above.
- Adds functional tests of Spark structured streaming on both COW and MOR tables.
This change added tests mentioned above.
=> [HUDI-4540] Cover different table types in functional tests of Spark structured streaming

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
=> [HUDI-4514] optimize CTAS to adapt to saveAsTable api in different modes

docker/demo/config/hoodie-incr.properties, hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
- `HoodieConfig#setDefaults` looks up declared fields, so should pass static class for reflection, otherwise, subclasses of HoodieSyncConfig won't set defaults properly
- Pass all write client configs of deltastreamer to meta sync 
- Make `org.apache.hudi.hive.MultiPartKeysValueExtractor` the default for deltastreamer, to align with SQL and flink
=> [HUDI-4474] Fix inferring props for meta sync

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/CopyOnWriteRestoreActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/MergeOnReadRestoreActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackPlanActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/CopyOnWriteRollbackActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MergeOnReadRollbackActionExecutor.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestClientRollback.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
Ideally, rollback is not triggered for completed instants. However, if it gets triggered due to some extraneous condition or forced while rollback strategy still configured to be marker-based, then fallback to listing-based rollback instead of failing.
- CTOR changes in rollback plan and action executors.
- Change in condition to determine whether to use marker-based rollback.
- Added UT to cover the scenario. 
*(or)*
(or)
*(example:)* …
=> [HUDI-4550] Fallback to listing based rollback for completed instant

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- When deltastreamer is used for writes and if upgrade is required, upgrade fails when there is a partially failed commit in timeline. bcoz, Deltastreamer calls startCommit() which internally rollsback the partially failed commit. Following this, writeClient.upsert is called, where in upgrade is triggered. In this code block of interest, we again try to check for partially failed commits and rollback them. but metaclient wasn't reloaded and hence we run into issues.
- Fixed upgrade to reload the metaclient. 
*(or)*
(or) …
=> [HUDI-4534] Fixing upgrade to reload Metaclient for deltastreamer writes

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/MarkerBasedRollbackUtils.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java, hudi-common/src/main/java/org/apache/hudi/common/util/MarkerUtils.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerDirState.java
If `MARKERS.type` file is not present, the logic assumes that the direct markers are stored, which causes the read failure in certain cases even where timeline server based marker is enabled. This PR handles the failure by falling back to timeline based marker in such cases.
See #5591 for more details.
*(or)*
(or)
*(example:)*
- *Manually …
=> [HUDI-4517] If no marker type file, fallback to timeline based marker

hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
[HUDI-4508] Repair the exception when reading optimized query for mor in hive and presto/trino, if the fileSlice with log file has not base file.
In mor table , file slice may just has log file but has no base file, before the file slice is compacted. In this situation, if query mor in reading optimized query mod, it will match the condition `!baseFileOpt.isPresent()` in `HoodieCopyOnWriteTableInputFormat.createFileStatusUnchecked()` and throw IllegalStateException. It's not suitable. Instead of throw exception, it is more suiltable to query nothing in the file slice.
*(or)*
This …
=> [HUDI-4508] Repair the exception when reading optimized query for mor in hive and presto/trino

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
=> [MINOR] Improve flink dummySink's parallelism

packaging/hudi-aws-bundle/pom.xml, packaging/hudi-flink-bundle/pom.xml, packaging/hudi-kafka-connect-bundle/pom.xml, packaging/hudi-utilities-bundle/pom.xml, packaging/hudi-utilities-slim-bundle/pom.xml
- Shade `metrics-core` in `hudi-aws-bundle`
- Remove duplicate includes in other bundles
Without this change, if Hudi metrics is turned on and metrics report type is Cloudwatch, then write client initialization fails. Stacktrace in HUDI-4568. The reason is that `metrics-core` is shaded in hudi-spark-bundle but not in hudi-aws-bundle but this dependency is used in hudi-aws for which we get NoMethodFoundError.
High
Run below script (with metrics and hive turned on). Without this fix, the write will fail with NoMethodFoundError
```
./bin/pyspark \
--jars /home/hadoop/hudi-spark3.2-bundle_2.12-0.13.0-SNAPSHOT.jar,/home/hadoop/hudi-aws-bundle-0.13.0-SNAPSHOT.jar \
--conf "spark.serializer=org.apache.spark.serializer.KryoSerializer"   \
--conf …
```
=> [HUDI-4568] Shade dropwizard metrics-core in hudi-aws-bundle

hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/replication/TestHiveSyncGlobalCommitTool.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java, hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncConfig.java
- Infer `META_SYNC_PARTITION_FIELDS` and `META_SYNC_PARTITION_EXTRACTOR_CLASS` from `hoodie.table.partition.fields` first; if not set, then from `hoodie.datasource.write.partitionpath.field`
Without this fix, in the scenario mentioned above, the partition extractor would be set as `NonPartitionedExtractor` even though hoodie.properties has a partition field.
Added a test to cover the scenario in `TestHoodieSyncConfig`. Also, manually verified spark-sql as follows:
```
spark-sql> create table hudi_cow_pt_tbl (
>   id bigint,
>   name string,
>   ts bigint,
>   dt string,
>   hh string
> ) using hudi
> tblproperties (
>   type = 'cow',
>   primaryKey = 'id',
>   preCombineField = 'ts'
>  )
> partitioned by (dt, hh)
> location '/tmp/hudi/hudi_cow_pt_tbl';
spark-sql> …
```
=> [HUDI-4571] Fix partition extractor infer function when partition field mismatch

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/QueryBasedDDLExecutor.java
During refactoring (#5854), the condition to determine sync sql cascade option is mistyped. Fixing it to checking `META_SYNC_PARTITION_FIELDS`.
=> [MINOR] Fix wrong key to determine sync sql cascade

hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java, hudi-examples/hudi-examples-spark/src/test/java/org/apache/hudi/examples/quickstart/TestHoodieSparkQuickstart.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteFromTable.scala, hudi-utilities/src/test/resources/hive-site.xml
This change aims to add/improve test coverage by picking some low-hanging fruits.
- Added "hive-site.xml" to fix DeltaStreamer tests failing locally (unable to connect to Hive)
- Added `TestDeleteFromTable`
- Beefed up Spark's Quickstart guide test
=> [HUDI-4577] Adding test coverage for `DELETE FROM`, Spark Quickstart guide

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCleanProcedure.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCleanProcedure.scala
support mor clean policy param and trigger policy
none
=> [HUDI-3503] Support more feature to call procedure CleanCommand

packaging/hudi-flink-bundle/pom.xml
Before 0.11.1, hudi-flink-bundle include hudi-aws because hudi-client-common included hudi-aws.
But after [HUDI-3193](https://issues.apache.org/jira/browse/HUDI-3193),we need to include it mannually.
=> [HUDI-4590] Add hudi-aws dependency to hudi-flink-bundle.

website/docs/schema_evolution.md, website/versioned_docs/version-0.11.0/schema_evolution.md, website/versioned_docs/version-0.11.1/schema_evolution.md
This PR updates the schema evolution docs page and fixes incorrect information.  The latest, 0.11.0, and 0.11.1 versioned docs are updated.
- Only docs update.
=> [HUDI-4576][DOCS] Fix schema evolution docs

hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java
show fsview all doesn't work with non-partitioned table and "`show fsview all --pathRegex */*/*`" doesn't work as expected.
*(or)*
(or)
*(example:)* …
=> [HUDI-4555] fix bug in cli show fsview all

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
Before that, the code 'FlinkStreamerConfig.toFlinkConfig(cfg)' will be called twice. It's mostly misleading and the same thing both times.
**Risk level: none
=> [HUDI-4611] optimized code in the class of HoodieFlinkStreamer

website/docs/quick-start-guide.md
This PR updates the Spark Guide website page with Spark 3.3 support. 
=> [HUDI-4564] Update docs for Spark 3.3 support

hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
when process blocks in hoodieLogRecordReader, the `progress` field track approximate progress by number of log-files seen,
but it is calculated wrong as operator priority incorrect.
=> [MINOR] fix `progress` field calculate logic in HoodieLogRecordReader

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUpgradeDowngradeCommand.java
This PR fixes the table upgrade from version THREE to FOUR using Hudi CLI.  Before this fix, the following exception is thrown.  This is due to the missing `hoodie.table.name` property in the write config passed in.
```
22/08/11 15:35:39 INFO UpgradeDowngrade: Attempting to move table from version THREE to FIVE
22/08/11 15:35:39 WARN SparkMain: Failed: Could not upgrade/downgrade table at "/<>/test_table" to version "FIVE".
java.lang.IllegalArgumentException: hoodie.table.name property needs to be specified
at org.apache.hudi.common.table.HoodieTableConfig.generateChecksum(HoodieTableConfig.java:437)
at org.apache.hudi.table.upgrade.ThreeToFourUpgradeHandler.upgrade(ThreeToFourUpgradeHandler.java:43)
at org.apache.hudi.table.upgrade.UpgradeDowngrade.upgrade(UpgradeDowngrade.java:147)
at …
```
=> [HUDI-4608] Fix upgrade command in Hudi CLI

website/docs/quick-start-guide.md, website/docs/table_management.md, website/versioned_docs/version-0.11.0/quick-start-guide.md, website/versioned_docs/version-0.11.0/table_management.md, website/versioned_docs/version-0.11.1/quick-start-guide.md, website/versioned_docs/version-0.11.1/table_management.md
This PR updates the docs of Spark SQL create table statement.  Based on #4584, the create table statement for an existing Hudi table does not require `partitioned by` or `options` statement (`options (primaryKey = 'id', preCombineField = 'ts') partitioned by (dt)`), and it should be
```
create table hudi_existing_tbl using hudi
location '/tmp/hudi/hudi_existing_table';
```
=> [HUDI-4580][DOCS] Update docs of Spark SQL create table statement

hudi-cli/src/main/java/org/apache/hudi/cli/commands/UpgradeOrDowngradeCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUpgradeDowngradeCommand.java
This PR improves usability of upgrade/downgrade commands in Hudi CLI by the following:
- For the upgrade command (`upgrade table`), if `--toVersion` is not specified, the current/latest table version is used.
- Adds support for numeric table version.  If the numeric table version is provided through `--toVersion`, it is converted to the `HoodieTableVersion` enum name internally, e.g., `2` -> `TWO`.
This PR adds new tests for the conversion of the input version option to the desired version name.
Only affecting the upgrade and downgrade commands in Hudi CLI.
Tested the following CLI commands and they all work as expected:
- `upgrade table --sparkMaster local[2]`: `Hoodie table upgraded/downgraded to FIVE`
- `downgrade table --toVersion 2 --sparkMaster local[2]`: `Hoodie …
=> [HUDI-4609] Improve usability of upgrade/downgrade commands in Hudi CLI

hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java, hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerCreationDispatchingRunnable.java
Use hash map in concurrent environment, it may cause exception and crash ScheduledExecutorService which will lead to timeline based markers request timed out.
Use ConcurrentHashMap to fix it.
=> [HUDI-4574]fixed timeline based marker thread safaty issue

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
=> [HUDI-4621] Add validation that bucket index fields should be subset of primary keys

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
New (trivial) feature - force running meta sync as a post-condition of a successful delta-streamer sync, even if the commit was empty.
* add `--force-empty-sync`
=> [HUDI-4354] add --force-empty-sync flag to deltastreamer

website/src/pages/tech-specs.md
- Consistent terminlogy; tables vs datasets, management vs maintenance
- Fixed few ommissions around meta fields, added more rationale
- Clarified partitioning bit more
- Formatting, typos.
- 
none
=> [DOCS] Edits to the Hudi Tech specs

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
=> [HUDI-4529] Tweak some default config options for flink

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsInference.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
The default value of `READ_TASKS`, `WRITE_TASKS`, `CLUSTERING_TASKS` is 4, which could be the parallelism of the execution environment.
- Updates `READ_TASKS`, `WRITE_TASKS`, `CLUSTERING_TASKS` with no default value, which default is the parallelism of the execution environment.
- Updates `COMPACTION_TASKS` with no default value, which default is WRITE_TASKS*COMPACTION_DELTA_COMMITS/5.
=> [HUDI-4551] The default value of READ_TASKS, WRITE_TASKS, CLUSTERING_TASKS is the parallelism of the execution environment

hudi-cli/src/main/java/org/apache/hudi/cli/HoodiePrintHelper.java, hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java, hudi-cli/src/main/java/org/apache/hudi/cli/Table.java, hudi-cli/src/main/java/org/apache/hudi/cli/TableHeader.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/TimelineCommand.java
=> [HUDI-3579] Add timeline commands in hudi-cli

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
```sql
spark.sql(
s"""
|create table $tableName (
| id int,
| name string,
| price double,
| ts long,
| dt string
|) using hudi
| location '${tmp.getCanonicalPath}/$tableName'
| tblproperties (
| primaryKey ='id',
| preCombineField = 'ts'
| )
""".stripMargin)
// Insert data
spark.sql(s"insert into $tableName select 1, 'a1', 1, 10, '2022-08-18'")
spark.sql(
s"""
| merge into $tableName as t0
| using (
| select 1 as id, 'a1' as name, 11 as price, 110 as ts, '2022-08-19' as dt union all
| select 2 as id, 'a2' as name, 10 as price, 100 as ts, '2022-08-18' as dt
| ) as s0
| on t0.id = s0.id
| when not matched then insert *
""".stripMargin
)
```
```
11493 [Executor task launch worker for task 65] ERROR org.apache.hudi.table.action.commit.BaseSparkCommitActionExecutor  - Error upserting …
```
=> [HUDI-4643] MergeInto syntax WHEN MATCHED is optional but must be set

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
=> [HUDI-4676] infer cleaner policy when write concurrency mode is OCC

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
1. Use Enum Class instead of constant string for option default value in FlinkOptions.
2. fix doc error for default value
=> [HUDI-4683] Use enum class value for default value in flink options

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
=> [HUDI-4686] Flip option 'write.ignore.failed' to default false

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
When I use hbase index, I find the job can't be finished. I set log level to DEBUG and see endlessly printing 
```
22/08/17 18:26:45 DEBUG RateLimiter: Release permits: maxPremits: 100, available: 100
22/08/17 18:26:45 DEBUG RateLimiter: Release permits: maxPremits: 1000, available: 1000 
```
We create a RateLimiter to limit the request rate when we use hbase index. We use a thread pool to release the semaphore, but we don't terminate the thread pool .
none
=> [HUDI-4637] Release thread in RateLimiter is not terminated

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala, hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java
Flipping default for "ignore failed batch" config in streaming sink to false to favor data integrity. 
could thwart data loss w/ hudi. 
**Risk level: high
=> [HUDI-4665] Flipping default for "ignore failed batch" config in streaming sink to false

hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java, hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/hive/TestHoodieCombineHiveInputFormat.java
Fix flakiness
```text
[ERROR] org.apache.hudi.hadoop.functional.TestHoodieCombineHiveInputFormat  Time elapsed: 0.675 s  <<< ERROR!
at org.apache.hudi.common.testutils.minicluster.HdfsTestService.configureDFSCluster(HdfsTestService.java:135)
at org.apache.hudi.common.testutils.minicluster.HdfsTestService.start(HdfsTestService.java:87)
at org.apache.hudi.common.testutils.minicluster.MiniClusterUtil.setUp(MiniClusterUtil.java:41)
```
=> [HUDI-4696] Fix flaky TestHoodieCombineHiveInputFormat

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java, hudi-common/src/main/java/org/apache/hudi/common/util/RetryHelper.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java, hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
This reverts commit 660177bce1cd82975d7c25715497e0d2fbb2a95e.
Some [thread safety issues](https://github.com/apache/hudi/pull/5884/files#r955363946) are deducted w/ this feature added. Reverting it for now. I will let the author put up a new patch w/ proper fix. 
Could result in wrong data being served. Should not be an issue w/ SparkEngineContext. But java and flink could be impacted since in Spark, remoteFSView requests are triggered by executors. 
=> [HUDI-4721] Revert "[HUDI-3669] Add a remote request retry mechanism for 'RemoteHoodietablefiles… (#5884)"

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
Fixing `DebeziumSource` to properly commit consumed offsets;
Tidying up
Low.
=> [Stacked on 6386] Fixing `DebeziumSource` to properly commit consumed offsets

hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestTimeTravelQuery.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala
=> [HUDI-4703] use the historical schema to response time travel query

packaging/hudi-aws-bundle/pom.xml, packaging/hudi-hive-sync-bundle/pom.xml
- Remove Avro shading from hudi-hive-sync-bundle and hudi-aws-bundle
- We cannot shade avro in hudi-spark-bundle or hudi-utilities-bundle because we use certain SparkConf APIs that expect unshaded Avro classes. If we shade Avro in hudi-hive-sync-bundle without shading in hudi-spark or hudi-utilities bundle then it can lead to conflict (NoMethodFoundError) as mentioned in HUDI-4549.
Tested hive sync locally and on EMR with changing the order of jars in the launch command.
=> [HUDI-4549]  Remove avro from hudi-hive-sync-bundle and hudi-aws-bundle

hudi-integ-test/pom.xml, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieContinousTestSuiteWriter.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieInlineTestSuiteWriter.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieMultiWriterTestSuiteJob.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/SparkDataSourceContinuousIngestTool.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DFSDeltaConfig.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/DagUtils.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseQueryNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseValidateDatasetNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/HiveQueryNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/HiveSyncNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/PrestoQueryNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/TrinoQueryNode.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/ValidateAsyncOperations.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/scheduler/DagScheduler.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/GenericRecordFullPayloadGenerator.java, hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/reader/DFSAvroDeltaInputReader.java
open check plugin in integ-test, and fix style
=> [HUDI-4483] fix checkstyle in integ-test module

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java, hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Fix HUDI-4340: DeltaStreamer bootstrap failed when metrics on caused by DateTimeParseException: Text '00000000000001999' could not be parsed
HoodieTimeline.METADATA_BOOTSTRAP_INSTANT_TS is a invalid value, "00000000000001", which can not be parsed by DateTimeFormatter with format SECS_INSTANT_TIMESTAMP_FORMAT = "yyyyMMddHHmmss" in method HoodieInstantTimeGenerator.parseDateFromInstantTime.
Error log in DeltaStreamer
```log
Exception in thread "main" java.time.format.DateTimeParseException: Text '00000000000001999' could not be parsed: Invalid value for YearOfEra (valid values 1 - 999999999/1000000000): 0
at …
```
=> [HUDI-4340] fix not parsable text DateTimeParseException in HoodieInstantTimeGenerator.parseDateFromInstantTime

website/docs/docker_demo.md
When I saw https://hudi.apache.org/docs/docker_demo "Docker demo" I assumed it was going to be based on pulling docker images - it wasn't clear that I had to have the hudi repo local to my machine first. 
This PR adds a couple of notes to make this clearer, as well as fixing capitalization on `Hudi` and `Docker`.
=> [DOCS] Clarification to Docker quickstart demo

website/docs/docker_demo.md, website/docs/quick-start-guide.md
fix link rendering error in Docker Demo and some other typos.
This pull request is a trivial rework without any test coverage.
=> [DOCS] Fix link rendering error in Docker Demo and some other typos

hudi-kafka-connect/README.md
This pull requests documents a possible cause for an issue when starting the Hudi Kafka Sink:
```shell
org.apache.hudi.exception.HoodieException: Fatal error instantiating Hudi Transaction Services 
....
Caused by: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
```
- *Modify document about Kafka Connect Hudi Sink setup*
- *Adds troubleshoot section with documentation about the javax.security.auth.login.LoginException error*
=> [DOCS] Add doc about javax.security.auth.login.LoginException in Hudi KC Sink

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HiveSchemaUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
=> [HUDI-4740] Add metadata fields for hive catalog #createTable

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestInlineCompaction.java
Fixed flaky InlineCompactionTest. Test had some dependency on timer. Have bumped up the timer so that its more deterministic. 
Improves CI stability 
=> [HUDI-4695] Fix flaky TestInlineCompaction#testCompactionRetryOnFailureBasedOnTime

hudi-kafka-connect/pom.xml, pom.xml
Hudi was unable to build on m1 macs. Fix was to add a profile that changes the protoc version. The profile is activated by mac os + aarch64 processor.
Able to build on m1 macs, no impact otherwise
**Risk level:  low **
- [ ✅] Read through [contributor's guide](https://hudi.apache.org/contribute/how-to-contribute)
- [✅ ] Change Logs and Impact were stated clearly
- [ N/A] Adequate tests were added if applicable
- [ ✅] CI passed
=> [HUDI-4193] change protoc version so it compiles on m1 mac

website/docs/quick-start-guide.md, website/docs/writing_data.md, website/versioned_docs/version-0.10.0/quick-start-guide.md, website/versioned_docs/version-0.10.0/writing_data.md, website/versioned_docs/version-0.10.1/quick-start-guide.md, website/versioned_docs/version-0.10.1/writing_data.md, website/versioned_docs/version-0.11.0/quick-start-guide.md, website/versioned_docs/version-0.11.0/writing_data.md, website/versioned_docs/version-0.11.1/quick-start-guide.md, website/versioned_docs/version-0.11.1/writing_data.md, website/versioned_docs/version-0.12.0/quick-start-guide.md, website/versioned_docs/version-0.12.0/writing_data.md
This PR add examples of soft deletes to the Hudi website.
- Adds a new sub-section of "Soft Deletes" with examples in Spark quick start guide and moves the existing delete examples to "Hard Deletes"
- Renames the variables in hard-delete examples to be clear
- Adds an example of soft deletes in the "Writing Data" page
- Updates versioned docs back to 0.10.0
=> [HUDI-4748][DOCS] Add examples of soft deletes in docs

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
Fixed flaky TestCopyOnWriteActionExecutor#testPartitionMetafileFormat. When generating data, test wasn't generating data to all partitions. during validation we validate that partition meta file exists for one of the 3 partitions that HoodieTestDataGenerator generates. 
will fix CI stability
=> [HUDI-4438] Fix flaky TestCopyOnWriteActionExecutor#testPartitionMetafileFormat

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieArchivalConfig.java
As above.
Only updates to config description.
=> [MINOR] Fix typo in HoodieArchivalConfig

hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
AWSGlueCatalogSyncClient udpatePartitionsToTable() function
https://issues.apache.org/jira/browse/HUDI-4742
If the location is wrong, then the table could not be queried almost, it's a serious bug, when synced to AWS glue
low
=> [HUDI-4742] Fix AWS Glue partition's location is wrong when updatePartition

hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java, hudi-client/hudi-java-client/src/test/resources/testDataGeneratorSchema.txt, hudi-client/hudi-spark-client/src/test/resources/testDataGeneratorSchema.txt, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
- Adding support to hudi-cli to repair deprecated partition. Until 0.12, fallback partition in hudi (if partition path value is null for a record), is `default`. From 0.12, we have switched to `__HIVE_DEFAULT_PARTITION__`. This cli support will assist users to rewrite data from the deprecated partition to `__HIVE_DEFAULT_PARTITION__` partition. 
Not sure how many have these sentinel partitions. So, may not be high for sure. 
**Risk level: Low -> Medium. 
=> [HUDI-4642] Adding support to hudi-cli to repair deprecated partition

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/InProcessLockProvider.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestInProcessLockProvider.java
There are some callers of txnManager apis which does not set the current owner instant. this patch fixes that, so that during unlock only the intended owner can actually unlock and not by anyone else. 
Added tests to InProcessLockProvider to test the unintended unlock by diff owner. already we have similar test for TransactionManager. 
No detected bugs yet. just as precautionary measure. 
=> [HUDI-4751] Fix owner instants for transaction manager api callers

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeyGenUtils.java
Delete the judgment on length.
Because this function needs to return the value corresponding to the key in the recordKey. However, when the length is equal to 1, the entire recordKey is returned.
When there is only one primary key, the cdc data read by the user contains the delete type rowdata.
low
=> [HUDI-4739] Wrong value returned when key's length equals 1

hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/DiffCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieSyncValidateCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/utils/CommitUtil.java, hudi-cli/src/main/java/org/apache/hudi/cli/utils/TimelineUtil.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCompactionCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestDiffCommand.java, hudi-cli/src/test/java/org/apache/hudi/cli/testutils/HoodieTestCommitMetadataGenerator.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java, hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
- Add merge API to merge two timelines in `HoodieDefaultTimeline`. This enables merging active and archived timeline.
- Add partition level info to commits and compaction command.
- Add diff command to compare metadata.
- Add commands to list out all actions for file id through a range of commits.
- Add unit tests.
Changes can be helpful while debugging timeline using CLI.
low
=> [HUDI-4528] Add diff tool to compare commit metadata

hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java, hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java, hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java
* Added a hudi-cli command to move from one partition to another, e.g. `rename partition --oldPatition 2022/08/29 --newPartition 2022/08/30`.
* Deletes the older partition after moving data to new partition.
* Added a unit test.
none
low (new CLI command which is used in an offline manner)
=> [HUDI-4648] Support rename partition through CLI

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Incremental Source for a hudi table of type MOR fails since the commit timeline fetched works only for COW table. Fixing the timeline call in this patch.
Enables incremental source with Hudi's MOR table. 
**Risk level: medium**
Incremental source w/ hudi's MOR table was broken prior to this patch.
=> [HUDI-4775] Fixing incremental source for MOR table

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeyGenUtils.java
=> [minor] following HUDI-4739, fix the extraction for simple record keys

website/blog/2020-08-22-ingest-multiple-tables-using-hudi.md
=> [HUDI-4634] Update schema provider configuration in MTDS blog

hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala, hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala, style/scalastyle.xml
In HoodieStreamingSink, if a microbatch gets committed in Hudi but spark checkpoint write fails, then Spark will retry and Hudi will rewrite the data. This causes data duplication. This PR makes the sink idempotent by adding the batchId to hudi commit metadata and then always checking the current batchId with the previously committed one, and skips if it's a retry.
*(or)*
(or)
*(example:)*
- …
=> [HUDI-4389] Make HoodieStreamingSink idempotent

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
fix merge into sql use unresolved attr cause use the wrong condition branch `resolve Star assignment`
=> [HUDI-4776] Fix merge into use unresolved assignment

website/src/pages/roadmap.md
This PR updates the 2022 H2 roadmap based on the plan for 0.12.1 and 0.13.0 releases.
=> [HUDI-4635] Update 2022 H2 roadmap

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Fix KryoException when bulk insert into a not bucket index hudi table
Provide InternalTypeInfo instead of TypeInformation of RowData to transform method when adding SortOperator to flink pipeline. Because SortOperator now use kryo to serialize BinaryRowData object that it pass to flink collector which will cause KryoException see [https://github.com/apache/hudi/issues/6540](url).
Use InternalTypeInfo will switch to a flink serializer to avoid KryoException.
no public API or user-facing feature change
=> [HUDI-4795] Fix KryoException when bulk insert into a not bucket index hudi table

hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/S3EventsMetaSelector.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestS3EventsMetaSelector.java
When we start a new deltastreamer with S3EventsSource, checkpoint is Option.empty(). After consumption from source, if there is no data, the source returns "val=0" as the checkpoint. So, deltastreamer assumes checkpoint has changed and makes an empty commit. This needs fixing. 
https://github.com/apache/hudi/blob/0d0a4152cfd362185066519ae926ac4513c7a152/hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/S3EventsMetaSelector.java#L151
low
=> [HUDI-4615] Return checkpoint as null for empty data from events queue. 

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroSchemaConverter.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroToRowDataConverters.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/DataTypeUtils.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataToAvroConverters.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestAvroSchemaConverter.java, hudi-flink-datasource/hudi-flink1.13.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java, hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java, hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
=> [HUDI-4782] Support TIMESTAMP_LTZ type for flink

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/Metrics.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
After turning on CloudWatch metrics for Hudi, programs running in Spark-shell do not exit properly because the ThreadPool running CloudWatch metrics reporter is preventing JVM from terminating. This CR attempts to fix this issue by calling the shutdown() API when the main program completes.
_Describe any public API or user-facing feature change or any performance impact._  
N/A
low
=> [HUDI-4731] Shutdown CloudWatch reporter when query completes

hudi-tests-common/src/main/resources/log4j2.component.properties, pom.xml
Fixing ScalaTest tests to properly respect Log4j2 configs (by adding `log4j2.component.properties` file)
Additionally addressing an issue of Pulsar Spark connector breaking compilation for some invocations (when `scala-2.1x` profile is not specified explicitly)
Risk: None
=> [HUDI-4793] Fixing ScalaTest tests to properly respect Log4j2 configs

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
[HUDI-4797] fix merge into table for source table with different column order
=> [HUDI-4797] fix merge into table for source table with different column order

packaging/hudi-flink-bundle/pom.xml
There's a typo for the `Kryo-shaded` item in flink-bundle's pom file which causes the lib not to be packaged into the bundle file. Not sure if we should include it or just remove it.
The Kryo lib causes a lot of issues when we integrate hudi with Flink. This change could potentially introduce some dependency conflict to the existing jobs.
=> [MINOR] Typo fix for kryo in flink-bundle

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
Use base table instant for metadata table initialization.
When initializing COL-STATS or BLOOM-FILTER partition in metadata table, currently we assign instant of metadata table to the records. The value will finally be overwritten in `HoodieAppendHandle` using instant from base table.
This patch fixes the behavior by assigning instant of base table at the very beginning.
No public API change.
None.
=> [HUDI-4807] Use base table instant for metadata table initialization

hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
When Hudi choose Append save mode in Spark, basePath，basePath with special text will return error codes.
Example: " ...tmp/hudi-test/中文路径/hudi-table..." will return “...tmp/hudi-test/ä¸­æè·¯å¾/hudi-table...”, 
Cause Append failed
=> [HUDI-4826] When Hudi choose Append save mode in Spark, the basepath may be error codes

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/HoodieReadClient.java
Currently the hudi read client use BLOOM and this cannot be overwriten. This allows to use GLOBAL_BLOOM
and provides fast lookup on the primary key (without partition keys)
```
HudiReadClient client =
new HudiReadClient(context, path, spark.sqlContext(), GLOBAL_BLOOM);
client.readROView(keyRdd, 200);
```
=> [HUDI-4763] Allow hoodie read client to choose index

README.md
Link dev setup and contribution guideline in readme.
None
None
=> [MINOR] Add dev setup and spark 3.3 profile to readme

hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestAWSDmsAvroPayload.java
=> [HUDI-4831] Fix AWSDmsAvroPayload#getInsertValue,combineAndGetUpdateValue to invoked correct api

packaging/hudi-flink-bundle/pom.xml
Make Avro version consistent across Hudi and make sure flink bundle is usable even when user is building against spark3 profile
=> [HUDI-4806] Use Avro version from the root pom for Flink bundle

hudi-common/src/main/java/org/apache/hudi/common/util/JsonUtils.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieCommitMetadata.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieReplaceCommitMetadata.java
This PR fixes the serialization of commit metadata to remove redundant fields in serialized commit metadata in JSON.
The commit metadata in JSON (*.commit, *.deltacommit) written to the Hudi timeline under `.hoodie/` contains redundant fields that can be trimmed.  As shown below, the same set of write stats is written to both "partitionToWriteStats" and "writeStats", doubling the size and increasing the serde overhead.  Other fields like "totalRecordsDeleted", "writePartitionPaths", "fileIdAndRelativePaths", etc., can be removed as well as they are derived from "partitionToWriteStats" and not directly used by HoodieCommitMetadata class.
The root cause of the problem is that, when serializing the `HoodieCommitMetadata` and `HoodieReplaceCommitMetadata` class instance to JSON string, the …
=> [HUDI-4825] Remove redundant fields in serialized commit metadata in JSON

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
https://issues.apache.org/jira/browse/HUDI-3879
Several improvements for HoodieMetadataTableValidator.
*(or)*
(or)
*(example:)*
=> [HUDI-3879] Suppress exceptions that are not fatal in HoodieMetadataTableValidator

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
=> [HUDI-4814] Schedules new clustering plan based on latest clustering instant

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java, hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
This PR fixes the issue where the markers are not deleted after full-record bootstrap operation (with instant time `00000000000002`).  In the functional tests of bootstrap, the temp folder verification is added to check if there are remaining marker folders.
No impact on public API.
Before this PR, the functional tests fail with the new temp folder verification.  After this PR, the function tests pass.
The change is also verified by running the Deltastreamer with bootstrap operation.  All markers are deleted after the bootstrap is complete.
=> [HUDI-4817] Delete markers after full-record bootstrap operation

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
=> [HUDI-4843] Delete the useless timer in BaseRollbackActionExecutor

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala
Immutable keygen configs were not being set during bootstrap. This PR fixes that. 
=> [HUDI-3403] Ensure keygen props are set for bootstrap

pom.xml
Upgrade Protobuf to latest available version
- Upgrade Protobuf to 3.21.5 to support project compilation on macOS M1 (aarm64).
- [CVE-2021-22569](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22569) High - CVSS Score: 7.5, An implementation weakness in how unknown fields are parsed in Java. A small (~800 KB) malicious payload can occupy the parser for several minutes by creating large numbers of short-lived objects that cause frequent, repeated GC pauses.
=> [HUDI-4193] Upgrade Protobuf to 3.21.5

website/docs/quick-start-guide.md, website/versioned_docs/version-0.12.0/quick-start-guide.md
Add validation to scala and python quick start guides. 
Add python insert overwrite. 
Fix python insert missing "\\" for multiline function chain.
Fix incorrect variable name softDeleteDs to soft_delete_ds for python soft delete.
Use createOrReplaceTempView instead of registerTempTable in python hard delete because it is depreciated.
Fix comment in python time travel query that uses "//" for comment instead of "#".
better and less buggy quick start guide
=> [HUDI-4759] Update website with validations

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieBootstrapConfig.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapDeltaCommitActionExecutor.java, hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/bootstrap/SparkFullBootstrapDataProviderBase.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala
This PR fixes the following issues for bootstrap operation:
* Partition discovery in `SparkFullBootstrapDataProviderBase`
* Handling of `FULL_RECORD` mode in `SparkBootstrapCommitActionExecutor`
* Schema resolution in `HoodieBootstrapRelation`
No public API change.
Medium. Only for bootstrapped tables.
=> [HUDI-4785] Fix partition discovery in bootstrap operation

hudi-common/src/main/java/org/apache/hudi/internal/schema/action/InternalSchemaChangeApplier.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/action/TableChangesHelper.java, hudi-common/src/test/java/org/apache/hudi/internal/schema/action/TestTableChanges.java
InternalSchemaChangeApplier#applyAddChange forget to remove parent name when calling ColumnAddChange#addColumns
Add removing parent name when calling ColumnAddChange#addColumns in InternalSchemaChangeApplier#applyAddChange
Error when use InternalSchemaChangeApplier#applyAddChange to add a nest type
=> [HUDI-4706] Fix InternalSchemaChangeApplier#applyAddChange error to add nest type

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala
`InSet` is an optimized version of the `In` operator in Spark (containing exclusively static values). 
Hudi's CSI index lookup seq isn't handling it properly at the moment, essentially rendering queries containing it ineffective in terms of Data Skipping.
Risk level: None
=> [HUDI-4851] Fixing CSI not handling `InSet` operator properly

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/ConsoleMetricsReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/InMemoryMetricsReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/JmxMetricsReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/Metrics.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsGraphiteReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/cloudwatch/CloudWatchMetricsReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogMetricsReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PrometheusReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PushGatewayMetricsReporter.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PushGatewayReporter.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestMetricsReporterFactory.java
- Removes a confusing method, `getReporter()` in the abstract class MetricsReporter since we want to be calling `stop` the MetricsReporter instances to make sure they are cleaned up properly
- Updates Metrics.java to call `stop` method
- Updates implementations of MetricsReporter to no longer implement getReporter method
- Fixes import order in classes that were touched as part of this PR
The API for the `MetricsReporter` is changing due to the removal of the `getReporter` method
=> [HUDI-4796] MetricsReporter stop bug

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableRenameCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTable.scala
update tblp 'path' when table rename
*(or)*
(or)
*(example:)*
=> [HUDI-3861] update tblp 'path' when rename table

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Fix KEY_GENERATOR_CLASS_NAME will be assigned default as `ComplexKeyGenerator` in `org.apache.spark.sql.catalyst.catalog.HoodieCatalogTable#extraTableConfig`
The `org.apache.hudi.DataSourceOptionsHelper#inferKeyGenClazz` is not used at all：
at `org.apache.hudi.DataSourceWriteOptions#keyGeneraterInferFunc`, because not set default value, will not be called；at `org.apache.spark.sql.hudi.command.SqlKeyGenerator#getRealKeyGenClassName`, also not be called, because `beforeKeyGenClassName != null && beforeKeyGenClassName.nonEmpty` is excluded from `org.apache.spark.sql.hudi.command.SqlKeyGenerator#originKeyGen`
SparkSql will also follow infer way when KEY_GENERATOR_CLASS_NAME not user defined.
none
=> [HUDI-4813] Fix infer keygen not work in sparksql side issue

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/CatalogOptions.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogFactory.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalogFactory.java
=> [HUDI-4856] Missing option for HoodieCatalogFactory

hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java, hudi-common/src/test/java/org/apache/hudi/common/model/TestAWSDmsAvroPayload.java
JIRA: https://issues.apache.org/jira/browse/HUDI-4864 
Without this change encountered the following exceptions with DMS during delete operations when trying to query MOR table with snapshot. 
1.
```
Caused by: java.util.NoSuchElementException: No value present in Option
at org.apache.hudi.common.util.Option.get(Option.java:88)
at org.apache.hudi.common.model.AWSDmsAvroPayload.<init>(AWSDmsAvroPayload.java:52)
... 35 more
```
2.
```
java.util.NoSuchElementException: No value present in Option
at org.apache.hudi.common.util.Option.get(Option.java:89)
at org.apache.hudi.common.model.AWSDmsAvroPayload.combineAndGetUpdateValue(AWSDmsAvroPayload.java:90)
at org.apache.hudi.common.model.AWSDmsAvroPayload.combineAndGetUpdateValue(AWSDmsAvroPayload.java:84)
at …
```
=> [HUDI-4864] Fix AWSDmsAvroPayload#combineAndGetUpdateValue when using MOR snapshot query after delete operations

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/cow/TestBlockLocationSort.java
BlockLocation sort compare implementation is not idempotent, causing `getBlockIndexForPosition()` to throw `IllegalArgumentException`.
Issue link: https://issues.apache.org/jira/browse/HUDI-4841
PR where bug was introduced:
#2814
CopyOnWriteInputFormat#getBlockIndexForPosition() requires BlockLocations to be sorted by offsets in ascending order. 
However, the current comparator implementation does not guarantee that the BlockLocation array is sorted in an ascending order.
**Stacktrace**
```log
Caused by: java.lang.IllegalArgumentException: The given offset is not contained in the any block.    
at org.apache.hudi.table.format.cow.CopyOnWriteInputFormat.getBlockIndexForPosition(CopyOnWriteInputFormat.java:374)    
at org.apache.hudi.table.format.cow.CopyOnWriteInputFormat.createInputSplits( …
```
=> [HUDI-4841] Fix BlockLocation array sorting idempotency issue

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
For Hudi Deltastreamer with async cleaning, when the Spark job fails in the middle of the cleaning, leaving a clean instant inflight in the timeline, the Spark job retried next time may not resume the inflight clean action if `hoodie.clean.allow.multiple` is `false`, i.e., multiple clean schedules are disabled.  This is due to a bug of the conditional check which is used for both clean service scheduling and execution.
The fix is to let clean service execution proceed regardless of whether the scheduling a new clean action happens, so that inflight clean action can proceed.
Adjusted the functional test covering the logic around allowing multiple cleans to follow the expected behavior.
Tested locally by setting `hoodie.clean.allow.multiple` to `false` andinjecting …
=> [HUDI-4736] Fix inflight clean action preventing clean service to continue when multiple cleans are not allowed

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/LogFileLengthBasedCompactionStrategy.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/LogFileNumBasedCompactionStrategy.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java
When reading Hudi data, the number of small files greatly affects the reading performance. When compressing logs, we can provide a strategy to compress more delte log files first
=> [HUDI-4842] Support compaction strategy based on delta file num

hudi-common/src/main/java/org/apache/hudi/common/fs/BoundedFsDataInputStream.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
Problem: Not all dfs throw EOFException, when seek index out of the length of file, such as chdfs. So it is not suitable to use EOFException to check whether "currentPos + blocksize - Long.BYTES" is out of the file length.
Solution: When throw IOException，read file length to check whether to the end.
*(or)*
(or) …
=> [HUDI-4282] Repair IOException in CHDFS when check block corrupted in HoodieLogFileReader

hudi-examples/hudi-examples-spark/pom.xml, hudi-examples/hudi-examples-spark/src/test/java/org/apache/hudi/examples/quickstart/TestHoodieSparkQuickstart.java, hudi-examples/hudi-examples-spark/src/test/python/HoodiePySparkQuickstart.py, hudi-examples/hudi-examples-spark/src/test/python/README.md, hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/QuickstartUtils.java
Create examples in pyspark and add validations to them
Can be used for new users. Might be used for CI testing
=> [HUDI-4757] Create pyspark examples

hudi-cli/src/test/java/org/apache/hudi/cli/functional/CLIFunctionalTestHarness.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/HoodieReadClient.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDReadClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieReadClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestInlineCompaction.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java, hudi-examples/hudi-examples-spark/src/test/java/org/apache/hudi/examples/quickstart/TestHoodieSparkQuickstart.java, hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieRepairTool.java
We can read HUDI data via Spark , Flink or JAVA API (In-progress) , so it's better to rename the class name for Spark Reader.
It will make codes more clear.
- *Rename org.apache.hudi.client.HoodieReadClient -> org.apache.hudi.client.SparkRDDReadClient*
*(or)*
(or)
*(example:)* …
=> [HUDI-3959] Rename class name for spark rdd reader

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeyGenUtils.java
=> [HUDI-4828] Fix the extraction of record keys which may be cut out

hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerMetrics.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
Improvement for monitoring.
Report the number of AvroKafkaMessages that are about to be processed via metrics
This pull request is a trivial rework / code cleanup without any test coverage. Manually verified the change by running a job in production on our end.
=> [HUDI-4873] Report number of messages to be processed via metrics

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
This PR improves the description of two configs: `hoodie.compact.inline.max.delta.commits` and `hoodie.compact.inline.max.delta.seconds`.
Only docs change.
=> [HUDI-4870] Improve compaction config description

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/HoodieLazyInsertIterable.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkWriteHelper.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaWriteHelper.java, hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
=> [minor] following 3304, some code refactoring

hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java, hudi-sync/hudi-adb-sync/src/main/java/org/apache/hudi/sync/adb/AdbSyncTool.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Fixes issue #6578 
While considering whether to drop partition, meta sync should only drop partitions that were part of latest drop_partition operation (replacecommit) metadata. 
Also, ensure archive timeline since last synced time is considered while fetching partitions written since last synced time.
Medium. No public API change. But, the issue could lead to wrong results.
Added a test to verify the change.
=> [HUDI-4832] Fix drop partition meta sync

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/client/http/HoodieWriteCommitHttpCallbackClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogHttpClient.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogReporter.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/SparkConsistentBucketClusteringPlanStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkConsistentBucketClusteringExecutionStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/update/strategy/SparkConsistentBucketDuplicateUpdateStrategy.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDConsistentBucketPartitioner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieMergeOnReadTestUtils.java
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
==>
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
=> [HUDI-4810] Fix log4j imports to use bridge API 

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java, hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
* This pull request fix https://github.com/apache/hudi/issues/5861*
* The issue is caused by after changing the table to spark data source table, the table SerDeInfo is missing. *
- add updateTableSerDeInfo for HiveSyncTool
=> [HUDI-4326] add updateTableSerDeInfo for HiveSyncTool

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDropTable.scala
JIRA: https://issues.apache.org/jira/browse/HUDI-4875
Without this change encountered the following exception when `DROP VIEW test_view` after `CREATE TEMP VIEW test_view AS SELECT 1`, while HoodieSparkSessionExtension is enabled in Spark 3.2, :
```
org.apache.spark.sql.catalyst.analysis.NoSuchTableException: Table or view 'test_view' not found in database 'default'
at org.apache.spark.sql.catalyst.catalog.SessionCatalog.requireTableExists(SessionCatalog.scala:225)
at org.apache.spark.sql.catalyst.catalog.SessionCatalog.getTableRawMetadata(SessionCatalog.scala:516)
at org.apache.spark.sql.catalyst.catalog.SessionCatalog.getTableMetadata(SessionCatalog.scala:502)
at org.apache.spark.sql.hudi.SparkAdapter.isHoodieTable(SparkAdapter.scala:160)
at …
```
=> [HUDI-4875] Fix NoSuchTableException when dropping temporary view after applied HoodieSparkSessionExtension in Spark 3.2

hudi-kafka-connect/README.md
=> [DOCS] Improve the quick start guide for Kafka Connect Sink

hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieFileGroup.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestQueryMergeOnReadOptimizedTable.scala
When querying a read_optimized table, the expectation is that only & all completed parquet files can be scanned. But when there is a pending compaction job contains the completed parquet files, they can not be queried. 
When query a read_optimized table in spark-sql, always fetch latest completed file slice(file slice in pending compaction will be filtered) 
Only the code path of RO table be changed
=> [HUDI-4729] Fix fq can not be queried in pending compaction when query ro table with spark

hudi-examples/hudi-examples-common/src/main/java/org/apache/hudi/examples/common/HoodieExampleDataGenerator.java, hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java
The examples never check to make sure the desired actions are correct.
=> [HUDI-4758] Add validations to java spark examples

rfc/rfc-46/rfc-46.md
=> [RFC-46][HUDI-4414] Update the RFC-46 doc to fix comments feedback

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java, hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java, hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCUtils.java, hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
=> [HUDI-3478][HUDI-4887] Use Avro as the format of persisted cdc data

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/catalyst/encoders/DummyExpressionHolder.scala
This is taking up the fix from https://github.com/apache/hudi/pull/6700, and adding the test for it
**Risk level: None
=> [HUDI-4851] Fixing handling of `UTF8String` w/in `InSet` operator

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
As above.
Only config description update.
=> [HUDI-3901] Correct the description of hoodie.index.type

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/savepoint/SavepointHelpers.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
Supporting delete savepoint for MOR table
Users could delete unnecessary savepoints and unblock archival for MOR table.
**Risk level: medium **
Extraneous savepoints could be hanging around and thwarting the archival progress for MOR table. With this patch, we should be able to make progress.
=> [HUDI-4883] Supporting delete savepoint for MOR

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandleWithChangeLog.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java, hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java, hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCOperation.java, hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCSupplementalLoggingMode.java, hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCUtils.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCDCDataBlock.java
=> [HUDI-4897] Refactor the merge handle in CDC mode

hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/AddColumnSchemaPostProcessor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
introduce a new schema postprocessor which support add new column 
introduce a new schema postprocessor which support add column 
tests
This pull request is already covered by existing tests:
org.apache.hudi.utilities.TestSchemaPostProcessor#testAddPrimitiveTypeColumn
=> [HUDI-3523] Introduce AddPrimitiveColumnSchemaPostProcessor to support add new primitive column to the end of a schema

hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Fix TestHoodieLogFormat`s minor typo for 'thee' -> 'the'
N/A
**Risk level: none
=> [MINOR] Fix TestHoodieLogFormat`s minor typo

hudi-cli/pom.xml, hudi-client/hudi-spark-client/pom.xml, hudi-examples/hudi-examples-spark/pom.xml, hudi-flink-datasource/hudi-flink/pom.xml, hudi-spark-datasource/hudi-spark-common/pom.xml, packaging/hudi-flink-bundle/pom.xml, pom.xml
=> [HUDI-4906] Fix the local tests for hudi-flink

hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala, hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystPlanUtils.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystPlanUtils.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/Spark31NestedSchemaPruning.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystPlanUtils.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/Spark32NestedSchemaPruning.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystPlanUtils.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/Spark33NestedSchemaPruning.scala, pom.xml
Fixing compatibility w/ Spark 3.2.2, by abstracting away instantiation of `ProjectionOverSchema` utility behind `SparkAdapter`
**Risk level: Low
=> [HUDI-4899] Fixing compatibility w/ Spark 3.2.2

pom.xml
This PR fixes the hudi-spark3-bundle.  Before this PR, reading a Hudi table with Spark datasource in Spark 3.3 shell with hudi-spark3-bundle throws the following exception.  Some classes are not packaged into the spark3 bundle.
```
scala> val df = spark.read.format("hudi").load("<table_path>")
java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider org.apache.hudi.Spark32PlusDefaultSource not found
at java.util.ServiceLoader.fail(ServiceLoader.java:239)
at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
at …
```
=> [HUDI-4892] Fix hudi-spark3-bundle

website/docs/concurrency_control.md, website/versioned_docs/version-0.10.0/concurrency_control.md, website/versioned_docs/version-0.10.1/concurrency_control.md, website/versioned_docs/version-0.11.0/concurrency_control.md, website/versioned_docs/version-0.11.1/concurrency_control.md, website/versioned_docs/version-0.12.0/concurrency_control.md
This PR improves docs on DynamoDB-based lock provider to avoid confusion on setting the configs.
The website can be built and visualized with `npm start`.
=> [HUDI-4010] Improve docs on DynamoDB-based lock provider

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndex.java
Fix a few typos in HoodieIndex.java
=> [MINOR] Fix a few typos in HoodieIndex

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/ConcurrentOperation.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java, hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
There are two minor issues fixed here;
1. When the insert_overwrite operation is performed, the clusteringPlan in the requestedReplaceMetadata will be null,
Calling getFileIdsFromRequestedReplaceMetadata will have a null pointer
2. When insert_overwrite operation, inflightCommitMetadata!=null, getOperationType should be obtained from getHoodieInflightReplaceMetadata, the original code will have a null pointer
=> [HUDI-4412] Multiple writers NPE when Insert_overwrite

hudi-common/src/main/java/org/apache/hudi/internal/schema/convert/AvroInternalSchemaConverter.java, hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
=> [MINOR] retain avro's namespace

hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
Currently, Spark Avro serializer/deserializer has a bug that it will return the same object when we call this method twice continuously.  For example:
val row1: InternalRow = ...
val row2: InternalRow = ... // record2 is different with record1
val serializeredRecord1 = serialize(row1)
val serializeredRecord2 = serialize(row2)
serializeredRecord1.equals(serializeredRecord2)  // this is not expected.
That is because we use the `val` to declare the serializer/deserializer methods, so the latter's result will cover the previous one.
=> [HUDI-4915] improve avro serializer/deserializer

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Apparently in clustering, data file creations are triggered twice since we don't cache the write status and for doing some validation, we do isEmpty on JavaRDD<WriteStatus> which ended up retriggering the action. 
Could improve the clustering performance. 
**Risk level: medium**
If not for the fix, clustering could be triggered twice, but only one set of files will be included in the final commit metadata. Duplicated copy will be deleted during marker reconciliation step. 
validateWriteResult(clusteringPlan, writeMetadata) in BaseCommitActionExecutor was was the reason behind triggering the execution twice. 
Test/Verification:
Manually verified that if not for the fix, markers are created twice(two files differ just in write token) and later reconcilation step deletes one of them. With …
=> [HUDI-4760] Fixing repeated trigger of data file creations w/ clustering

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
Managed memory weight should be set when sort clustering is enabled, otherwise the fraction of memory to allocate is 0 that throws the following exception when initialzing the sorter.
- Sets the managed memory weight when sort clustering is enabled in Pipelines#cluster()
- Initializes the `BinaryExternalSorter` in `ClusteringOperator#doClustering()`.
When sort clustering is enabled, the `ClusteringOperator` could initialize the `BinaryExternalSorter`.
high.
- Introduces the `testWriteCopyOnWriteWithSortClustering` in `ITTestDataStreamWrite` to verify whether the sort clustering could work normally.
=> [HUDI-4914] Managed memory weight should be set when sort clustering is enabled

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionCodeGen.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
fix merge into assigment code gen error
=> [HUDI-4910] Fix unknown variable or type "Cast"

hudi-cli/src/main/java/org/apache/hudi/cli/commands/KerberosAuthenticationCommand.java
Added kerberos kinit command for hudi cli. Now it supports connecting to Kerberized Hadoop cluster.
As it may be complicated to prepare a temporary Kerberized environment for unit tests, I have tested it with local Kerberized Hadoop cluster.
It has no impact on performance.
=> [HUDI-4718] Add Kerberos kinit command support for cli.

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLayoutConfig.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
ISSUE: https://github.com/apache/hudi/issues/6723
When we use BUCKET index in spark, the default BUCKET_INDEX_ENGINE_TYPE is SIMPLE. While only SparkBucketIndexPartitioner supports the SIMPLE bucket index.
This pr sets default partitioner for SIMPLE BUCKET index
=> [HUDI-4902] Set default partitioner for SIMPLE BUCKET index

.github/PULL_REQUEST_TEMPLATE.md
As above.  The author of PRs should put up docs updates as part of their contribution.  The author should create a Jira for the docs and link them in the PR description. 
=> [MINOR] Update PR template with documentation update

website/docs/faq.md, website/versioned_docs/version-0.12.0/faq.md
As above.
The website can be built and visualized properly locally with `npm start`.
=> [HUDI-4805] Update FAQ with workarounds for HBase issues

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/meta/TestCkpMetadata.java
Co-authored-by: TengHuo <teng_huo@outlook.com>
Ensure that INFLIGHT instant fetched from the CkpMetadataPath is always larger than previous committed instant.
This is to prevent the error described in [HUDI-4907](https://issues.apache.org/jira/browse/HUDI-4907)
**Note:** This is a short term fix. @TengHuo and I are looking to refactor this section of the code. 
=> [HUDI-4907] Prevent single commit multi instant issue

azure-pipelines.yml, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieReadClient.java
TestHoodieReadClient was using local fs and hence defaulting to hdfs while running in azure CI. Locally I ran the test 50 times and could not reproduce the issue. To avoid hdfs related flakiness, migrating the test to use "file" scheme explicitly. 
Will help stabilize CI runs. 
=> [HUDI-4923] Fixing flaky test in TestHoodieReadClient.testReadFilterExistAfterBulkInsertPrepped

hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
Existing cli tool to repair deprecated partition had some assumptions about partition type being string. Also, it did not delete the physical old partition. Fixing those in this patch. 
=> [HUDI-4848] Fixing repair deprecated partition tool

hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
When using the HoodieSnapshotExporter to export a Hudi dataset on S3 to a different bucket, i.e., the source-base-path and the target-output-path are in different buckets, IllegalArgumentException is thrown:
```
./bin/spark-submit \
...
--jars /home/hadoop/hudi-spark3.2-bundle_2.12-0.13.0-SNAPSHOT.jar \
--class "org.apache.hudi.utilities.HoodieSnapshotExporter" \
/home/hadoop/hudi-utilities-bundle_2.12-0.13.0-SNAPSHOT.jar \
--source-base-path "s3a://ethan-lakehouse-us-east-2/hudi/hudi_trips_cow/" \
--target-output-path "s3a://ethan-tmp/backup/" \
--output-format "hudi"
```
```
Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS s3a://ethan-tmp//backup -expected s3a://ethan-lakehouse-us-east-2
at org.apache.hadoop.fs.s3native.S3xLoginHelper.checkPath(S3xLoginHelper.java: …
```
=> [HUDI-4913] Fix HoodieSnapshotExporter for writing to a different S3 bucket or FS

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/bootstrap/HoodieSparkBootstrapSchemaProvider.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala
=> [HUDI-4453] Fix schema to include partition columns in bootstrap operation

hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java, hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Fix Mor reads the log file and skips the complete block as a bad block, resulting in data loss
jira issues https://issues.apache.org/jira/browse/HUDI-2780
=> [HUDI-2780] Fix the issue of Mor log skipping complete blocks when reading data

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaRDD.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/data/TestHoodieJavaRDD.java, hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java, hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java, hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListData.java
This PR adds the logic to auto-tune the dedup parallelism.  Before this change, the write shuffle parallelism (`hoodie.insert|upsert|bulkinsert.shuffle.parallelism`, default value as 200) is directly fed into the Spark's `reduceByKey` transformation.  The default parallelism 200 is too high if the input batch of records is small.  This has caused increased latency in the write operations when dedup is enabled, which also affects CI test finish time.
The fix is to limit the parallelism based on the number of partitions of the input RDD of records.  A new API `getNumPartitions` is added in `HoodieData` abstraction to retrieve the information.
`TestHoodieSparkSqlWriter#testToWriteWithoutParametersIncludedInHoodieTableConfig` which does not have shuffle parallelism set:
Before this PR: dedup …
=> [HUDI-4924] Auto-tune dedup parallelism

hudi-common/pom.xml, hudi-common/src/main/java/org/apache/hudi/common/util/ObjectSizeCalculator.java, hudi-common/src/test/java/org/apache/hudi/common/util/TestObjectSizeCalculator.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java, hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieSanity.java, packaging/hudi-flink-bundle/pom.xml, packaging/hudi-hadoop-mr-bundle/pom.xml, packaging/hudi-hive-sync-bundle/pom.xml, packaging/hudi-integ-test-bundle/pom.xml, packaging/hudi-kafka-connect-bundle/pom.xml, packaging/hudi-presto-bundle/pom.xml, packaging/hudi-spark-bundle/pom.xml, packaging/hudi-trino-bundle/pom.xml, packaging/hudi-utilities-bundle/pom.xml, pom.xml
JDK versions 16 or later enforce strong encapsulation and do now allow to invoke `setAccessible` on a field, especially when the `isAccessible` is false. More details in [JEP 403](https://openjdk.org/jeps/403). This PR attempts to address that for `ObjectSizeCalculator`. An immediate use case where this would be beneficial is integrating Hudi with other libraries, e.g. Trino, that are using higher versions of JDK. 
We evaluated two other approaches:
1. Get the object size base on the amount of byte serialized. However, this runs into error if the incoming object does not implement `Serializable`.
2. Use Java's [Instrumentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.instrument/java/lang/instrument/Instrumentation.html) API. For this, we need to create an instrumentation …
=> [HUDI-4687] Avoid setAccessible which breaks strong encapsulation

hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/ValidateAsyncOperations.java
Fixing call to right timeline api for completed clean for ValidateAsyncOperations
stabilizes integration tests
N/A
=> [MINOR] fixing validate async operations to poll completed clean instances

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkCopyOnWriteTableArchiveWithReplace.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java, hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
Revert "[HUDI-4792] Batch clean files to delete (#6580)"
This reverts commit cbf9b83ca6d3dada14eea551a5bae25144ca0459.
We have some integration tests w/ clustering enabled. with 50+ commits, clustering fails where in it could not locate the files to be clustered. Apparently the clean plans is bit off. Since we have code freeze in a day, reverting the original commit for now until we find the right fix. 
No docs changes required.
=> [HUDI-4934] Revert batch clean files

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/metrics/HoodieLockMetrics.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java, hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
Added metrics for the following for the locking infra
1. Lock request latency
2. Count of Lock success
3. Count of failed to acquire the lock
4. Duration of locks held with support for re-entrancy
5. Conflict resolution metrics. Success vs Failure
6. Conflict resolution times.
=> [HUDI-4722] Added locking metrics for Hudi

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java, hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
HoodieSqlCommonUtils.withSparkConf() determines whether it is a hudi config key by judging the prefix `hoodie.`, which will cause the `as.of.instant` configuration to be handled incorrectly. This PR is compatible with the judgment logic of `as.of.instant`.
*(or)*
(or)
*(example:)*
- …
=> [HUDI-4936] Fix `as.of.instant` not recognized as hoodie config

hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala, hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystExpressionUtils.scala, hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystExpressionUtils.scala
This PR aims at relaxing current `MERGE INTO` constraints to permit limited casting operations w/in matched-on conditions by:
- Stripping out superfluous symmetrical casting (`cast(target.id as string) = cast(source.id as string`)
- Verifying that the incoming source dataset's primary-key could actually be up-casted to the target table's primary-key data-type w/o loss of precision (for ex, when `target.id` is of type `Int` and `source.id` is of type `Short`)
**Risk level: Low**
No docs update are required
=> [HUDI-4861] Relaxing `MERGE INTO` constraints to permit limited casting operations w/in matched-on conditions

hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
https://github.com/apache/hudi/issues/6354
I realized that this issue was caused by we must use ExpressionPayload in MergeInto, but for now, write.payload.class can be overwritten by the user, so I changed the logic forced to use ExpressionPayload in MergeInto
=> [HUDI-4925] Should Force to use ExpressionPayload in MergeIntoTableCommand

hudi-utilities/pom.xml, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudStoreIngestionConfig.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceCloudStorageHelper.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/FileDataFetcher.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/FilePathsFetcher.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/GcsIngestionConfig.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/MessageBatch.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/MessageValidity.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/MetadataMessage.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubMessagesFetcher.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/QueryInfo.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsSource.java, hudi-utilities/src/test/resources/delta-streamer-config/gcs-metadata.avsc, pom.xml
JIRA issue: https://issues.apache.org/jira/browse/HUDI-4850
This PR brings in an incremental pull from a Google Cloud Storage bucket to Hudi, similar to the existing feature on the S3 side of things (https://hudi.apache.org/blog/2021/08/23/s3-events-source/).
This design document contains more details about the feature: [Incremental Ingestion from Google Cloud Storage - Design and Implementation](https://docs.google.com/document/d/1VfvtdvhXw6oEHPgZ_4Be2rkPxIzE0kBCNUiVDsXnSAA/edit#)
Adds a new feature that integrates with parts of Google Cloud Storage. Runs as a separate process, and only when invoked explicitly by the user.
=> [HUDI-4850] Incremental Ingestion from GCS

packaging/hudi-aws-bundle/pom.xml, packaging/hudi-datahub-sync-bundle/pom.xml, packaging/hudi-gcp-bundle/pom.xml, packaging/hudi-timeline-server-bundle/pom.xml, packaging/hudi-utilities-slim-bundle/pom.xml
Shade JOL in remaining bundles. Fix `java.lang.NoClassDefFoundError: org/openjdk/jol/info/GraphLayout`.
None
=> [HUDI-4957] Shade JOL in bundles to fix NoClassDefFoundError:GraphLayout

hudi-cli/src/main/java/org/apache/hudi/cli/commands/KerberosAuthenticationCommand.java
Add Kerberos kdestroy command support
None
low
=> [HUDI-4718] Add Kerberos kdestroy command support

hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
=> [HUDI-4769] Option read.streaming.skip_compaction skips delta commit

hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
copy the object if ser/de Row or Record
LOW
=> [HUDI-4949] optimize cdc read to avoid the problem of reusing buffer underlying the Row

hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/SinglePartPartitionValueExtractor.java, hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestPartitionValueExtractor.java, hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java, hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncConfig.java
This PR fixes the issue reported in #6281.
For Deltastreamer, when using `TimestampBasedKeyGenerator` with the customized output dateformat (`hoodie.deltastreamer.keygen.timebased.output.dateformat`) of partition path containing slashes, e.g., "yyyy/MM/dd", and hive-style partitioning disabled (by default), the meta sync fails.  Relevant key generator configs are:
```
--hoodie-conf hoodie.datasource.write.partitionpath.field=createdDate
--hoodie-conf hoodie.datasource.write.keygenerator.class=org.apache.hudi.keygen.TimestampBasedKeyGenerator
--hoodie-conf hoodie.deltastreamer.keygen.timebased.timezone=GMT
--hoodie-conf hoodie.deltastreamer.keygen.timebased.output.dateformat=yyyy/MM/dd
--hoodie-conf hoodie.deltastreamer.keygen.timebased.timestamp.type=EPOCHMILLISECONDS 
```
Hive Sync …
=> [HUDI-4966] Add a partition extractor to handle partition values with slashes

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
There is a writing error in `commitTime`, which may not cause test failure here, but may cause problems in the future (we are currently developing our hudi metastore, and found this small error during our test)
none
none
=> [MINOR] Fix testUpdateRejectForClustering

hudi-aws/pom.xml, hudi-gcp/pom.xml, hudi-utilities/pom.xml
Move aws & gcp dependencies to the cloud modules respectively.
Affecting dev modules; No bundle dependencies change.
NA
=> [HUDI-4962] Move cloud dependencies to cloud modules

scripts/release/validate_staged_release.sh
- Source release validation should skip src/resources/banner.txt for CLI (Sprint boot application).
- Improve error message for validation script.
NA
NA
=> [HOTFIX] Fix source release validate script

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
Calculate average record size for Spark upsert partitioner based on commit instants only. Previously it's based on commit and replacecommit, of which the latter may be created by clustering which has inaccurately smaller average record sizes, which could result in OOM due to size underestimation.
Skip replacecommit for calculating average record size may also skip stats from insert overwrite. If a timeline only contains replacecommit from insert overwrite, the average record size will fall back to user-defined estimated size (`hoodie.copyonwrite.record.size.estimate`). The impact is small as commits will follow and subsequently improve the calculation results.
NA
=> [HUDI-4980] Calculate avg record size using commit only

hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUpgradeDowngradeCommand.java, hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java, hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java, hudi-kafka-connect/README.md, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
Update Kafka-connect setup with some details. Also, remove `HoodieConfig#create`, which is being used only in tests an unnecessarily class loader has to load `org.apache.hadoop.fs.FSDataInputStream`.
Refactoring does not have any impact in this case.
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setup# …
=> [HUDI-4970] Update kafka-connect readme and refactor HoodieConfig#create

hudi-integ-test/README.md
Adding more multi-writer notes to hudi-integ-test README. 
updating readme for integ tests.
=> [HUDI-4986] Enhancing README for multi-writer tests

website/docs/docker_demo.md, website/versioned_docs/version-0.12.0/docker_demo.md
1. Added instructions for how to run with m1 mac which was developed in HUDI-2786. 
2. Put the command for  "Upload the first batch to Kafka topic 'stock ticks'" on a different line because it was annoying to copy 
3. hoodie:stock_ticks_mor was incorrectly hoodie:stock_ticks 2 times in step 8
4. In 0.12.0 I added the sync with hive changes siva made to the current version
Website is now better
This is the documentation update for HUDI-2786
=> [HUDI-4976] added m1 changes to the site

packaging/hudi-aws-bundle/pom.xml, packaging/hudi-datahub-sync-bundle/pom.xml, packaging/hudi-flink-bundle/pom.xml, packaging/hudi-gcp-bundle/pom.xml, packaging/hudi-hadoop-mr-bundle/pom.xml, packaging/hudi-hive-sync-bundle/pom.xml, packaging/hudi-integ-test-bundle/pom.xml, packaging/hudi-kafka-connect-bundle/pom.xml, packaging/hudi-presto-bundle/pom.xml, packaging/hudi-spark-bundle/pom.xml, packaging/hudi-timeline-server-bundle/pom.xml, packaging/hudi-trino-bundle/pom.xml, packaging/hudi-utilities-bundle/pom.xml, packaging/hudi-utilities-slim-bundle/pom.xml, pom.xml
- Properly shade kryo-shaded, which exports `com.esotericsoftware.reflectasm` as well.
- Make shading configs re-usable.
Bundle e2e testing with different combinations.
NA
=> [HUDI-4971] Fix shading kryo-shaded with re-usable configs

packaging/hudi-spark-bundle/pom.xml
we are not enabled to use hudi bundle due to conflicts with elasticsearch client on the httpClient version.
This fixes the issue
=> [HUDI-4995] Fix dependency conflicts bundle with several http clients

packaging/hudi-datahub-sync-bundle/pom.xml
- Make parquet-avro and avro scope provided in datahub bundle
- Remove unneeded dependencies
[Official guide](https://hudi.apache.org/docs/syncing_datahub) shows running datahub sync bundle with utilities-bundle (deltastreamer) or utilities-slim+spark-bundle, which will provide parquet-avro that matches running spark's parquet version. Running datahub-sync bundle as a standalone sync tool requires hadoop and parquet dependencies (no official support/guide yet).
NA
=> [HUDI-4975] Fix datahub bundle dependency

hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java, hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
JIRA: https://issues.apache.org/jira/browse/HUDI-4993
When pushing metadata to Datahub it is necessary to be able to customize the DataPlatform name used for the entities, and also the environment for the datasets. Currently they are hardcoded, to "hudi" and "DEV" respectively. This PR adds CLI options and hoodie configs for both, to the DatahubSyncTool.
Adds user-facing configuration option to Datahub Sync tool. Current defaults continue.
- _Any new feature or user-facing change requires updating the Hudi website. Please create a Jira ticket, attach …
=> [HUDI-4993] Make DataPlatform name and Dataset env configurable in DatahubSyncTool

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/InProcessLockProvider.java, hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestInProcessLockProvider.java
Extend InProcessLockProvider to support multiple table ingestion
Adds capability to use multiple tables leveraging InProcessLockProvider within same jvm.
**Risk level: low *
n/a
n/a
=> [HUDI-4963] Extend InProcessLockProvider to support multiple table ingestion

hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java, hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java, hudi-common/src/main/java/org/apache/hudi/exception/HoodieSecondaryIndexException.java, hudi-common/src/main/java/org/apache/hudi/secondary/index/HoodieSecondaryIndex.java, hudi-common/src/main/java/org/apache/hudi/secondary/index/SecondaryIndexManager.java, hudi-common/src/main/java/org/apache/hudi/secondary/index/SecondaryIndexType.java, hudi-common/src/main/java/org/apache/hudi/secondary/index/SecondaryIndexUtils.java, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Index.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala, hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestIndexSyntax.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
Implementing create/drop/show/refresh index command for secondary index based on related index syntax, and persisting index metadata into hoodie.properties.
- Add ``SecondaryIndexManager``, ``SecondaryIndexUtils``, ``HoodieSecondaryIndexException``, ``TestSecondaryIndex``
- Rename ``HoodieIndex`` to ``HoodieSecondaryIndex``
- Rename ``HoodieIndexType`` to ``SecondaryIndexType``
- Modify ``HoodieTableConfig``, ``HoodieTableMetaClient``, ``Index``, ``IndexCommands``
- Added TestSecondaryIndex to verify the change
=> [HUDI-4293] Implement Create/Drop/Show/Refresh Index Command for Secondary Index

hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
When metadata table is just getting initialized, but first commit is not yet fully complete(or lets say metadata initialization failed mid-way), reading from metadata table could fail w/ the stacktrace posted in the linked jira. Fixing the read of hudi table to fallback to FS based listing if FILES partition in metadata table if not yet ready to serve data. 
Also, if user sets "hoodie.metadata.enable" = true while querying, even if metadata table is not available, we try to fetch from metadata table. Have fixed the same in this patch as well. 
Users should not see any failures or data loss while reading from hudi table if metadata table initialization is happening or if it fails mid-way.
_Choose one. If medium or high, explain what verification was done to mitigate …
=> [HUDI-4952] Fixing reading from metadata table when there are no inflight commits

hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/AbstractHoodieRowData.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieRowDataCreation.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieRowDataWithMetaFields.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestBulkInsertWriteHelper.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
After this change, the clustering would keep the original commit time by default .
none
=> [HUDI-5016] Flink clustering does not reserve commit metadata

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
JIRA: HUDI-5002. Improve SparkHoodieHBaseIndex#generateStatement With Hbase Recommend Method.
When I read the code, I found that SparkHoodieHBaseIndex#generateStatement uses Hbase's deprecated method(setMaxVersion), I replaced it with new method.
```
private Get generateStatement(String key) throws IOException {
return new Get(Bytes.toBytes(getHBaseKey(key))).setMaxVersions(1).addColumn(SYSTEM_COLUMN_FAMILY, COMMIT_TS_COLUMN)
.addColumn(SYSTEM_COLUMN_FAMILY, FILE_NAME_COLUMN).addColumn(SYSTEM_COLUMN_FAMILY, PARTITION_PATH_COLUMN);
} 
```
Does not affect the original logic, use a recommend method to replace.
_Choose one. If medium or high, explain what verification was done to mitigate …
=> [HUDI-5002] Remove deprecated API usage in SparkHoodieHBaseIndex#generateStatement 

website/docs/configurations.md, website/versioned_docs/version-0.11.0/configurations.md, website/versioned_docs/version-0.11.1/configurations.md, website/versioned_docs/version-0.12.0/configurations.md
Update 0.11.0 plus version of docs to reflect correct default value for hoodie.index.type config. This PR - https://github.com/apache/hudi/pull/6749 can fix the docs going forward automatically. …
=> [DOCS] Fix hoodie.index.type default value description in docs

hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogFactory.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/HoodieCatalogTestUtils.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalogFactory.java, hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Flink hive catalog external config not work
Risk level: low
N/A
=> [HUDI-5010] Fix flink hive catalog external config not work

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java, hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandleWithChangeLog.java, hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandleWithChangeLog.java, hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java, hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java, hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java, hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCFileSplit.java, hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieCDCLogRecordIterator.java, hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java, hudi-common/src/main/java/org/apache/hudi/common/util/JsonUtils.java, hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java, hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java, hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/HoodieCDCTestBase.scala, hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
CDCLogger supports flush and rollover.
low
no new configs
=> [HUDI-4948] Improve CDC Write

hudi-common/src/test/java/org/apache/hudi/common/model/TestPartialUpdateAvroPayload.java
fix error logic of unit test `testUseLatestRecordMetaValue` 
none
none 
none
=> [HUDI-5030]fix ut `TestPartialUpdateAvroPayload`.`testUseLatestRecordMetaValue`

hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
JIRA: HUDI-5033. Fix Broken Link In MultipleSparkJobExecutionStrategy.
When I read the code, I found that there is a link that cannot be linked to the code. I will fix it. I have completed the inspection of the entire module (hudi-spark-client), only this is the problem
N/A
=> [HUDI-5033] Fix Broken Link In MultipleSparkJobExecutionStrategy

packaging/hudi-integ-test-bundle/pom.xml
Upgrade org.apache.thrift:libthrift from 0.9.3 to 0.14.0 for vulnerability fix
There are 1 security vulnerabilities found in org.apache.thrift:libthrift 0.9.3
- [CVE-2018-1320](https://www.oscs1024.com/hd/CVE-2018-1320)
Only updating integ-test-bundle.
Run `mvn compile` failed locally, couldn't complete the build process.
Run `mvn clean test` failed locally, unit-test couldn't pass.
What happened？
There are 1 security vulnerabilities found in org.apache.thrift:libthrift 0.9.3
- [CVE-2018-1320](https://www.oscs1024.com/hd/CVE-2018-1320)
What did I do？
Upgrade org.apache.thrift:libthrift from 0.9.3 to 0.14.0 for vulnerability fix
What did you expect to happen？
Ideally, no insecure libs should be used.
How was this patch tested?
Run `mvn compile` failed locally, couldn't …
=> [HUDI-5037] Upgrade org.apache.thrift:libthrift to 0.14.0

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr_compliance.yml, scripts/pr_compliance.py
Created better error messages so that users can figure out how they filled out the pr incorrectly
Changed risk level section in the template because it was confusing to some users.
Now risk level is written below the section header. Validation for this does not check for "(write none, low medium or high below)" because I think some users might delete that.
This should allow users to be able to fix their incorrectly filled out pr without help from me
low
Overall execution path should not be changed at all, so I don't expect the script to fail. Error messages could possibly suggest incorrect issue with the pr but I have pretty thorough tests so I think it should be accurate.
N/A
=> [HUDI-5022] made better error messages for pr compliance

hudi-common/src/main/java/org/apache/hudi/common/fs/inline/InLineFSUtils.java, hudi-common/src/main/java/org/apache/hudi/common/fs/inline/InLineFsDataInputStream.java, hudi-common/src/test/java/org/apache/hudi/common/fs/inline/InLineFSUtilsTest.java
InLineFileSystem will throw NumberFormatException, cause the type of startOffset is int and out of bounds.
The exception detail see [HUDI-5003](https://issues.apache.org/jira/browse/HUDI-5003)
N/A
low
N/A
=> [HUDI-5003] Fix the type of InLineFileSystem`startOffset to long

docker/demo/sparksql-bootstrap-prep-source.commands, hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java, hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BootstrapExecutor.java, hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Add missing table configs for bootstrap in Deltastreamer.
Fixes a critical bootstrap bug.
=> [HUDI-4855] Add missing table configs for bootstrap in Deltastreamer

hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
Seeing noisy debug logs (`Fail to parse event time value`) with tests. Fixing null event time handling. 
```
109986 [consumer-thread-1] DEBUG org.apache.hudi.client.WriteStatus [] - Fail to parse event time value: null
java.lang.IllegalArgumentException: Input String cannot be null.
at org.apache.hudi.common.util.ValidationUtils.checkArgument(ValidationUtils.java:40) ~[classes/:?]
at org.apache.hudi.common.util.DateTimeUtils.parseDateTime(DateTimeUtils.java:77) ~[classes/:?]
at org.apache.hudi.client.WriteStatus.markSuccess(WriteStatus.java:102) ~[classes/:?]
at org.apache.hudi.testutils.MetadataMergeWriteStatus.markSuccess(MetadataMergeWriteStatus.java:68) ~[test-classes/:?]
at org.apache.hudi.io.HoodieCreateHandle.write(HoodieCreateHandle.java:159) ~[classes/:?]
at …
```
=> [MINOR] Handling null event time

style/scalastyle.xml
In order to solve `msck repair` bug when disable `hoodie.datasource.write.hive_style_partitioning`, I am designing `RepairHoodieTableCommand`, it need to copy part of the code in spark, the number of parameters to one function is 10, therefore I open this PR to increase maxParameters size in scalastyle first.
The maximum number of parameters is increased to 10
none …
=> [MINOR] Increase maxParameters size in scalastyle

hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Closing writers and scanners in TestHoodieLogFormat.
n/a
low. stablizes CI. 
N/A
=> [HUDI-3900] Closing resources in TestHoodieLogRecord
