apache/hudi

- hudi-client/hudi-client-common/src/test/resources/prometheus.properties
The PR fixes job name in prometheus.properties. 
NA
low
> [MINOR] Fix job name in prometheus.properties

- website/docs/troubleshooting.md
Adding faq on GCS issue w/ writes
> [DOCS] Adding faq on GCS issue w/ writes

- website/versioned_docs/version-0.13.0/flink-quick-start-guide.md
> [HUDI-5972] Fix the flink 1.13 bundle jar version on website

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
Remove duplicated WriteOperationType.INSERT.value
No public API or user-facing feature change or performance impact.
Low, removing duplicate
> [MINOR] Remove duplicated WriteOperationType.INSERT.value

- website/docs/procedures.md
update doc of procedures about savepoint since this pr https://github.com/apache/hudi/pull/6186/files was merged.
And add doc about usage of 'show_savepoints'.
only document, no code changed.
none
Spark SQL [procedures](https://hudi.apache.org/docs/next/procedures#create_savepoints)
> [HUDI-5856][DOCS] Update SQL in procedures.md

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroSchemaConverter.java
typo of method name
none
none
none
> [MINOR] Fix typo for method in AvroSchemaConverter

- hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/kafka/HoodieWriteCommitKafkaCallback.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/callback/TestKafkaCallbackProvider.java
Fix NPE when use kafka callback
No impact
none
> [HUDI-5952] Fix NPE when use kafka callback

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/BootstrapMetadataHandler.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CopyToTableProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CreateSavepointProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteSavepointProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ExportInstantsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HdfsParquetImportProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackToSavepointProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunBootstrapProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowArchivedCommitsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowBootstrapMappingProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowBootstrapPartitionsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitPartitionsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataTableStatsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowSavepointsProcedure.scala
> [MINOR] Optimize code style

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCLIUtils.scala
- hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunBootstrapProcedure.scala
Support database name for meta sync in bootstrap.
no
none
> [HUDI-6013] Support database name for meta sync in bootstrap

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
Hotfix in MergeIntoHoodieTableCommand::validate with remove used arguments
there is no impact to other moudles
> [HUDI-6024] Hotfix in MergeIntoHoodieTableCommand::validate with remove used arguments

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockOperatorStateStore.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockStateInitializationContext.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockStreamingRuntimeContext.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestFunctionWrapper.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
Add more tests for task partial over, global failover, and job failover.
none
none
> [HUDI-6036] Add more tests for task and coordinator interaction

- pom.xml
For ex, running `ITTestHoodieSanity.testRunHoodieJavaAppOnMultiPartitionKeysCOWTable` produces quite a few of the following exceptions: 
```
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.logging.log4j.util.LoaderUtil.newInstanceOf(LoaderUtil.java:190)
at org.apache.logging.log4j.util.LoaderUtil.newInstanceOf(LoaderUtil.java:211)
at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:207)
at …
```
> [HUDI-5406] Fix NoClassDefFoundError: org/apache/log4j/helpers/OnlyOnceErrorHandler

- hudi-common/src/main/java/org/apache/hudi/common/bloom/BloomFilterFactory.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/HoodieDynamicBoundedBloomFilter.java
HotFix in HoodieDynamicBoundedBloomFilter with refactor arguments in HoodieDynamicBoundedBloomFilter
not any impact to other moudles
> [HUDI-6023] Remove the unused argument in HoodieDynamicBoundedBloomFilter constructor

- website/blog/2023-03-16-Setting-Uber-Transactional-Data-Lake-in-Motion-with-Incremental-ETL-Using-Apache-Hudi.mdx
- website/blog/2023-04-07-Speed-up-your-write-latencies-using-Bucket-Index-in-Apache-Hudi.mdx
- website/src/pages/videos.md
> [DOCS][MINOR] Add new blogs

- hudi-utils/README.md
- hudi-utils/generate_config.sh
This PR improves config generation script by adding more bundles and revises the docs for clarity.
Makes the script easier to use.
none
Updates `hudi-utils/README.md`
> [HUDI-6075] Improve config generation script and docs

- website/docs/concurrency_control.md
- website/versioned_docs/version-0.12.0/concurrency_control.md
- website/versioned_docs/version-0.12.1/concurrency_control.md
- website/versioned_docs/version-0.12.2/concurrency_control.md
Update docs for FileSystem based lock provider
NA
NA
NA
> [MINOR][DOCS] Update docs for fs based lock provider

- doap_HUDI.rdf
Updating DOAP file for 0.12.3
Updating DOAP file for 0.12.3
none
N/A
> [MINOR] Updating DOAP file for 0.12.3

- hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java
- hudi-examples/hudi-examples-spark/src/main/scala/org/apache/hudi/examples/spark/HoodieDataSourceExample.scala
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/HoodiePipeline.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/hive/HoodieCombineHiveInputFormat.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeUnmergedRecordReader.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveAvroSerializer.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/utils/TestHiveAvroSerializer.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieContinuousTestSuiteWriter.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieMultiWriterTestSuiteJob.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DFSDeltaConfig.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/configuration/DeltaConfig.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/WriterContext.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/BaseValidateDatasetNode.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/CompactNode.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/DeltaGenerator.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/reader/DFSHoodieDatasetInputReader.java
- hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/HoodieMetaserverPreparations.java
- hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
- hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestService.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
As above.
Only typo fixes.
none
N/A
> [MINOR] Fix typos in multiple modules

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotCopier.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/HoodieDeltaStreamerConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltastreamerMultiWriterCkptUpdateFunc.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/AvroConvertor.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudStoreIngestionConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/MetadataMessage.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/multisync/TestMultipleMetaSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestFilebasedSchemaProvider.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSanitizationUtils.java
As above.
Only typo fixes.
none
N/A
> [MINOR] Fix typos in hudi-utilities module

- website/blog/2023-03-23-Spark-ETL-Chapter-8-with-Lakehouse-Apache-HUDI.mdx
- website/blog/2023-04-02-global-vs-non-global-index-in-apache-hudi.mdx
- website/src/pages/talks.md
- website/src/pages/videos.md
updated blog and video content
> [DOCS] updated community blog and videos

- hudi-console/README.md
- hudi-console/hudi-console/src/main/assembly/bin/hudi.sh
- hudi-console/hudi-console/src/main/java/org/apache/hudi/console/HudiConsoleBootstrap.java
[Improve] hudi-console module how to build updated
> [Improve] hudi-console module how to build updated

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Improve TestStreamWriteOperatorCoordinator#testCommitOnEmptyBatch. Now will send all write events before committing the empty instant
Improve the test only 
None
> [MINOR] Improve TestStreamWriteOperatorCoordinator#testCommitOnEmptyBatch

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
[MINOR] Match the directory-filter-regex to the relative directory name.
> [MINOR] Match the directory-filter-regex to the relative directory name.

- azure-pipelines.yml
Reverts apache/hudi#7943
as this is actually costing money
> Revert "[MINOR] enable publish test results"

- hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/HoodieDeltaStreamerConfig.java
As above.
Improves documentation and config page generation.
none
As above.
> [HUDI-6179] Add description to the DeltaStreamer config group

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
As above.
Code cleanup.
none
N/A
> [MINOR] Remove redundant advanced config marking

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
In #8499 , a user has raised a very reasonable requirement:
Currently, if the insert statement specifies less columns than the target table size, the following exception will be thrown:
> Exception in thread "main" java.lang.AssertionError: assertion failed: The number of insert assignments[3] must equal to the targetTable field size[4]
For a wide table that has 1000 columns, the user is required to specify all the columns with default values null to avoid this exception. Can we support partial insert in merge into (default to null if not specified) command so the developer can maintain clean SQL statement.
E.g. Delta merge command has already supported this.
https://docs.databricks.com/sql/language-manual/delta-merge-into.html
This PR aims to support this feature.
NA
NA
NA
> [HUDI-6105] Support partial insert in MERGE INTO command

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java
- hudi-utilities/src/test/resources/delta-streamer-config/short_trip_uber_config.properties
Fix misconfig in https://github.com/apache/hudi/pull/8399/files#diff-cead696b47f975856c3053a840d25202e8e2964fea26b9ab0060c7f5b4e39b4aR28 that caused CI failure
Fix CI.
None
NA
> [HUDI-4630] Fix hudi-utilities test's transformer misconfig

- docker/compose/docker-compose_hadoop284_hive233_spark244_mac_aarch64.yml
Fix for https://github.com/apache/hudi/issues/8700
Fixes URI exception error when connecting remotely using a java client
none
none
no documentation update needed.
- [ x] Read through [contributor's guide](https://hudi.apache.org/contribute/how-to-contribute)
- [ x] Change Logs and Impact were stated clearly
- [ x] Adequate tests were added if applicable
- [ x] CI passed
> [MINOR] Update docker-compose_hadoop284_hive233_spark244_mac_aarch64.yml

- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
- hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
- hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
As above.
Code cleanup only.
none
N/A
> [MINOR] Remove unused imports in Spark adapters

- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieUnsafeRowUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
- hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/catalyst/analysis/HoodieSpark2Analysis.scala
- style/scalastyle.xml
Change scalastyle ReturnChecker lever to error
Change scalastyle ReturnChecker lever to error
low
none
> [MINOR] Change scalastyle ReturnChecker lever

- hudi-timeline-service/pom.xml
add jetty-util in hudi-timeline-server module
none
low
Need to update
> [HUDI-6208] Fix jetty conflicts in the packaging process

- hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/IncrementalTimelineSyncFileSystemView.java
Fix some typos and delete unused parameter in Table File System View.
No
None
> [MINOR] Fix some typos and delete unused parameter

- doap_HUDI.rdf
Updating DOAP file for 0.12.3
Updating DOAP file for 0.12.3
none
> [MINOR] Updating DOAP file for 0.13.1

- pom.xml
For some maven profiles, the tests are not skipped even if `-DskipTests` is specified with mvn command.  This PR fixes the issue.  The bug is introduced by #8445.
Fixes the dev setup.
none
N/A
> [HUDI-6272] Fix POM to properly skip tests

- website/docs/syncing_metastore.md
- website/versioned_docs/version-0.13.0/syncing_metastore.md
Fixes an incorrect field description on the page.
Fixes an incorrect field description on the website.
NONE
NONE
> [DOCS] Update syncing_metastore.md

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
this change would not produce no impact，and it only a minor hotfix in HoodieSparEngineContext
changes …
> [Minor] hotfix in HoodieSparkEngineContext with delete log

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/BootstrapCommand.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunBootstrapProcedure.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BootstrapExecutor.java
Bootstraping into the same directory does not work so prevent the user from doing this.
Less user error.
None
N/A
> [HUDI-6264] Assert that bootstrap base path is different than path

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java
- hudi-flink-datasource/hudi-flink1.13.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
Fixing checkstyle and removed unnecessary index in `ParquetSplitReaderUtil`.
None
None
> [MINOR] Fix checkstyle + removed unnecessary index in #add

- .codecov.yml
[MINOR] Enabling codecoverage for master branch.
Enabling codecoverage for master branch.
Codecoverage allows us to find areas to test.
None
None
> [MINOR] Enabling codecoverage for master branch.

- packaging/hudi-flink-bundle/pom.xml
searched the main code, use spaces instead of tabs
none
none
none
> [MINOR] use spaces instead of tabs

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Minor fixes after https://github.com/apache/hudi/pull/8745
none
none
> [HUDI-6182] Fix the hive sync compatibility and improve timeline check

- website/src/pages/videos.md
Updated video section for new content
cc @bhasudha to review
> [DOCS] Add new videos to hudi website

- website/docs/procedures.md
- Add semicolon after SQL statement
- Remove error description
none
none
none
> [MINOR][DOCS] Unify the sql format in the procedures.md file

- hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/kafka/HoodieWriteCommitKafkaCallback.java
Log the exception in the hudi commit kafka callback
NONE
NONE
NONE
> [HUDI-6121] Log the exception in the hudi commit kafka callback

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkMergeOnReadTable.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/compact/HoodieFlinkMergeOnReadTableCompactor.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Add log compaction to Flink MDT
none
none
> [HUDI-6348] Flink MDT log compaction

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
Spark sql Core flow test was broken. Also it was not actually using bulk-insert so now it correctly does that.
Fix test.
None.
NA
> [HUDI-6314] Fix spark sql core flow

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetaserverConfig.java
- hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/HoodieMetaserver.java
Rename hudi metastore to metaserver
Rename hudi metastore to metaserver
none
none
> [MINOR] Rename hudi metastore to metaserver

- README.md
> [HUDI-6341] Update README with Spark 3.4 support

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
refract code and no impact 
refract code and no impact 
> [MINOR] Remove imports and methods in HoodieWriteConfig and HoodieSparkSqlWriter

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
> [HUDI-6365] Set hive sync tool only if syncs list is empty

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Add database name to operator uid and operator name, so we can identify differ tables in different databases
Add database name to operator uid and operator name
none
> [MINOR] Add database name to flink operator uid and operator name

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BucketBulkInsertPartitionerWithRows.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BucketIndexBulkInsertPartitionerWithRows.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/BucketPartitionUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Hudi bucket index bulk insert into need partition sort to improve speed
none
none
changes to the …
> [HUDI-6383] Hudi bucket index bulk insert into need partition sort to improve speed

- website/docs/quick-start-guide.md
add hudi_table_changes docs to spark quickstart guide
documentation for work done in PR #8729
none
none
NA
> [HUDI-6225][DOCS] hudi_table_changes docs in spark quickstart guide

- website/docs/querying_data.md
Fixed error in sample scala code in `Querying Data` page
None
None
N/A
> [DOCS][MINOR] Docs fix spark sample code querying data

- .github/workflows/bot.yml
- pom.xml
> [HUDI-6413] Fix build on Spark 2.4 and Scala 2.12

- website/docs/precommit_validator.md
- website/versioned_docs/version-0.13.0/precommit_validator.md
- website/versioned_docs/version-0.13.1/precommit_validator.md
Improved the data quality docs
N/A
None
None
> [DOCS] Update data quality docs

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Fixed an archival related test which was disabled when RLI patch was added. Fixes are only in test code. 
Fixed an archival related test which was disabled when RLI patch was added. Fixes are only in test code. 
low
N/A
> [HUDI-6385] Fixing archival tests after RLI base patch

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadWithFullTableScan.scala
Clean up all resources after each test.
Only fixing test.
none
> [HUDI-6445] Fix flaky TestIncrementalReadWithFullTableScan

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieGlobalBloomIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieBucketIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieGlobalSimpleIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieSimpleIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLocationFetchHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/update/strategy/SparkConsistentBucketDuplicateUpdateStrategy.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTableRecordIndex.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieGlobalBloomIndex.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestGlobalIndexEnableUpdatePartitions.java
Make record-level index support update partition path scenario.
RLI indexing performance
Medium
NA
> [HUDI-6431] Support update partition path in record-level index

- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReader.java
> [MINOR] Adjust annotation in HoodieLogFormatReader

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
remove unused commits num check before executing compactor/clustering.
> [HUDI-6458]Scheduling jobs should not fail when there is no completed commits

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestGlobalIndexEnableUpdatePartitions.java
Optimizing updates to RLI partition in MDT when Update Partition path = false and few minor fixes.
Optimizing updates to RLI partition in MDT when Update Partition path = false and few minor fixes.
low.
N/A
> [HUDI-6437] Fixing/optimizing record updates to RLI

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Remove a method and reload metaclient after table config update to replace that method's usage.
none
none
> [MINOR] Test table cleanup

- hudi-utils/generate_config.sh
- hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
- website/docs/configurations.md
- website/src/theme/DocPage/index.js
> [DOCS] Automatically generate basic configurations page.

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddColumnsCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
- hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/hudi/command/Spark30AlterTableCommand.scala
- hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/hudi/command/Spark31AlterTableCommand.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterTableCommand.scala
Add spark sql conf in AlterTableCommand
Add spark sql conf in AlterTableCommand
low
none
> [HUDI-6470] Add spark sql conf in AlterTableCommand

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/FlinkSizeBasedClusteringPlanStrategy.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/JavaSizeBasedClusteringPlanStrategy.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/SparkSizeBasedClusteringPlanStrategy.java
> [MINOR] ClusteringPlanStrategy code refactor

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java
> [MINOR] Fix content in TestHoodieCompactionStrategy#testBoundedIOSimple

- hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
fix minor issue
affects config doc generation part
low
> [HUDI-6112] Minor fix to config doc gen tool

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
Adding tests to validate restore of compaction commit
Adding tests to validate restore of compaction commit
low
N/A
> [HUDI-6246] Adding tests to validate restore of compaction commit

- hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
- website/docs/basic_configurations.md
- website/docs/configurations.md
copy of basic_configs adn all_configs pages generated from doc generation tool
doc updates.
low
> [HUDI-6112] Basic and All configs pages generated from Config doc generation tool

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
See detail in issue [issue-9139](https://github.com/apache/hudi/issues/9139)
This pr would check whether exists write error before commit compaction
NA
NA
> [HUDI-6512] Check whether exists write error before commit compaction

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
revert #9156 since #9163 merged
enable the test
low
NONE
> [MINOR] Revert HUDI-6521 Disable failing test case

- website/versioned_docs/version-0.13.1/record_payload.md
> Documentation Update to enhance readability

- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsSource.java
Fixing the correct resource path
None
low
No
> [HUDI-6530] Fixing the testcase to reflect correct resource path

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackToInstantTimeProcedure.scala
Fix bugs about call rollback_to_instant exception.
Fixes #9193 
None
None
None
> [MINOR] Fix bugs about call rollback_to_instant exception.

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
Remove unnecessary merge in the merge helper
Improves performance and code clarity 
none
N/A
> [HUDI-6544] Remove unnecessary merge for bootstrap files in merge helper

- website/docs/basic_configurations.md
Update basic_configurations.md
> Documentation change to Increase readability for  basic_configurations

- website/docs/faq.md
- website/docs/querying_data.md
- website/docs/troubleshooting.md
- website/docs/tuning-guide.md
- website/src/pages/tech-specs.md
- Add more questions in FAQ
- Split all questions in FAQ to these pages - faq,troubeshooting and tuning
- Organize questions based on component within each page
Restructure faq
Doc changes
Low
This PR is for FAQ and minor spec update
> [HUDI-6552][DOCS] Restructure and reorganize FAQ

- website/src/pages/tech-specs.md
update table version in tech-specs.md
keep spec uptodate on table version bumps
Low
> [DOCS][MINOR]Fix spec to update table version

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
Change log level convenient to address issues.
None
None
> [HUDI-6572] Change log level which relate to clustering

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
… merge into matched condition
Error messages will be reported when using RuntimeReplaceable functions (such as nvl) in the merge into matching conditions.
error log:
Caused by: java.lang.UnsupportedOperationException: Cannot evaluate expression: nvl(age#24, 0)
at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotEvaluateExpressionError(QueryExecutionErrors.scala:79)
at org.apache.spark.sql.catalyst.expressions.Unevaluable.eval(Expression.scala:309)
at org.apache.spark.sql.catalyst.expressions.Unevaluable.eval$(Expression.scala:308)
at org.apache.spark.sql.catalyst.expressions.Nvl.eval(nullExpressions.scala:185)
at org.apache.spark.sql.catalyst.expressions.ExpressionProxy.proxyEval(SubExprEvaluationRuntime.scala:132)
at org.apache.spark.sql.catalyst.expressions.SubExprEvaluationRunti …
> [HUDI-6500] Supports using RuntimeReplaceable functions in MERGE INTO matched condition

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/ExportCommand.java
fix writer close in ExportCommand
none
low
N/A
> [MINOR] fix writer close in ExportCommand

- hudi-platform-service/hudi-metaserver/hudi-metaserver-server/bin/start_hudi_metaserver.sh
> [MINOR] Remove irrelevant comments

- website/docs/table_types.md
- website/docs/timeline.md
- website/src/css/custom.css
- website/src/theme/DocPage/index.js
- Add local configs
- Keep uptodate on different query types
Docs update
Impacts website info
low
> [DOCS] Update timeline and table types pages

- website/docs/basic_configurations.md
- website/docs/migration_guide.md
- website/src/theme/DocPage/index.js
Update bootstrap page with configs and minor fixes
Doc changes
Low
> [DOCS] Update bootstrap page

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Fixing deletion of MDT index. 
Fixing deletion of MDT index. 
low
N/A
> [HUDI-6324] Fixing deletion of MDT index

- website/contribute/developer-setup.md
As above
Developer setup docs improvement
none
As above
> [DOCS] Improve Developer Setup page

- hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
> [MINOR] Fix typo in config docs

- website/releases/release-0.11.0.md
As above
Docs to mention table version change in 0.11.0
none
As above
> [DOCS][HUDI-6536] Add docs on table version change in 0.11.0

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
Disable because there are some cross-engine issues that are stil suspended.
none
none
> [MINOR] Disable the MDT for flink by default

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
Fix bug of bucket bulk insert
NA
NA
> [HOTFIX] Make a copy of partitionPath, since UTF8String could be pointing into a mutable underlying buffer

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestConsistentBucketIndex.java
Fix it failure introduced by  #9199
Fix it failure introduced by  #9199
NONE
NONE
> [MINOR] Fix consistent hashing bucket index it failure

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java
asyncService log prompt incomplete
asyncService log prompt incomplete
none
> asyncService log prompt incomplete

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CopyToTempViewProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
> [MINOR] Unify class name of Spark Procedure

- hudi-sync/hudi-hive-sync/pom.xml
- hudi-utilities/pom.xml
…ion for the maven-jar-plugin
in the hudi-utilities and hudi-hive-sync modules, add skip configuration for the maven-jar-plugin
none
> [HUDI-6690] Generate test jars for hudi-utilities and hudi-hive-sync modules

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
Remove duplicate switch branch in HoodieInputFormatUtils
Duplicate switch branch in HoodieInputFormatUtils
none
> [MINOR] Remove duplicate switch branch in HoodieInputFormatUtils

- website/docs/quick-start-guide.md
Doc update, Add command for CreateHoodieTableLike
None
None
> [HUDI-6676][DOCS] Add command for CreateHoodieTableLike

- website/blog/2023-07-20-Backfilling-Apache-Hudi-Tables-in-Production-Techniques-and-Approaches-Using-AWS-Glue-by-Job-Target-LLC.mdx
- website/blog/2023-07-21-AWS-Glue-Crawlers-now-supports-Apache-Hudi-Tables.mdx
- website/blog/2023-07-27-Apache-Hudi-Revolutionizing-Big-Data-Management-for-Real-Time-Analytics.mdx
- website/blog/2023-08-03-Apache-Hudi-on-AWS-Glue-A-Step-by-Step-Guide.mdx
- website/blog/2023-08-03-Data-lake-Table-formats-Apache-Iceberg-vs-Apache-Hudi-vs-Delta-lake.mdx
- website/blog/2023-08-09-Lakehouse-Trifecta-Delta-Lake-Apache-Iceberg-and-Apache-Hudi.mdx
fixed broken images 
@nsivabalan please review
> [DOCS] Updated image paths for blogs

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
Test runs now
Testing for release
none
N/A
> [HUDI-6673] Fix Incremental Query Syntax - Spark SQL Core Flow Test

- website/docs/flink-quick-start-guide.md
- website/docs/querying_data.md
- website/versioned_docs/version-0.13.1/flink-quick-start-guide.md
- website/versioned_docs/version-0.13.1/querying_data.md
Add doc for Hudi catalog.
none
none
> [HUDI-6697] Add doc for Flink Hudi Catalog

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieMergeOnReadTestUtils.java
RecordReader is not being closed in tests. If tests are being executed in images with low limits on file descriptors and allowed files, test may fail.
None
None
changes to the …
> [MINOR] Close record readers after use during tests

- packaging/hudi-flink-bundle/pom.xml
Add flink-metrics-dropwizard to flink bundle to fix ClassNotFound Exception
Add flink-metrics-dropwizard to flink bundle
NONE
NONE
> [MINOR] Add flink-metrics-dropwizard to flink bundle

- website/docs/metadata.md
- website/docs/metadata_indexing.md
- website/src/theme/DocPage/index.js
Summary:
- Add inline configs
- Add specific index descriptions
- Add high level context
- Restructure content for readability …
> [DOCS] Update Metadata table and metadata indexing related pages

- website/docs/quick-start-guide.md
Add doc for add partition sql command. HUDI-6671
Low
Low
Add the add partition command doc.
> [HUDI-6671][DOC] Add partition sql command doc

- hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
[MINOR] Modify return type description
[MINOR] Modify return type description
none
> [MINOR] Modify return type description

- website/docs/record_payload.md
- website/src/theme/DocPage/index.js
update record payload page
docs update
Low
> [DOCS] Update Record payload page

- website/docs/file_sizing.md
- website/src/theme/DocPage/index.js
Summary:
- Add inline configs
- Add some background
refer summary above
Doc changes
Low
> [DOCS] Update file sizing page

- hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
A line was missed while upgrading AWS dependencies. We are missing an arg to the update table call.
Fixes a bug
None
> [MINOR] Fix AWS refactor bug by adding skipTableArchive arg

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
Fixing warn log with auto key gen. 
Fixing warn log with auto key gen. 
none
> [MINOR] Fixing warn log with auto key gen

- azure-pipelines-20230430.yml
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/TestHoodieMetadataBase.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java
Fixing metrics to use console type in tests
Fixing metrics to use console type in tests
none
> [HUDI-6445] Fixing metrics to use IN-MEMORY type in tests

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
Updates the code to only call the collect method once if possible.
Reduces overhead of generating the commit stats
None
> [HUDI-6763] Optimize collect calls

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
Fixed issue for delete events for AWSDmsAvroPayload when CDC enabled
none
low
none
> [HUDI-6562] Fixed issue for delete events for AWSDmsAvroPayload when CDC enabled

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
When Flink < 1.17 is used, `ITTestSchemaEvolution` will fail. This is so as implicit inference of Map value's schema are used. The schema used will be the row's last schema. This may cause unintended truncation (if last row is of length that is shorter than the longest string's key value) or unintended whitespace padding (if last row is of the longest map.key string length)
**An example is shown below of truncation:**
```sql
tEnv.executeSql("
select  cast(f_map as map<string, int>)
from (values  
( map['Indica', 111]) ),
( map['Danny', 111] ),
( map['Han', 111] ),
( map['Julian', 111] ),
( map['Fabian', 111] ),
( map['Sophia', 111] ),
( map['Emma', 111] ),
( map['Bob', 111] ),
( map['a', 111] )
) 
as A(f_map)").print()
```
**An example is shown below of whitespace padding:**
```sql …
```
> [MINOR] Fix failing schema evolution tests in Flink versions < 1.17

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
update some error operator name and uid
> [MINOR] Update operator name for compact&clustering test class

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCreateRecordUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Fixed a regression where streaming sink shouldn't drop meta columns. Details in https://github.com/apache/hudi/pull/9261#discussion_r1311534951
Fix streaming sink quickstart example.
Low
NA
> [HUDI-6579] Fix streaming write when meta cols dropped

- website/docs/hoodie_cleaner.md
- website/src/theme/DocPage/index.js
update docs page for cleaning with inline configs
docs change
low
> [DOCS] Update cleaning page

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
_automatically create a database when using the flink catalog dfs mode._
_automatically create a database when using the flink catalog dfs mode._
_none._
> [HUDI-6818] Create a database automatically when using the flink catalog dfs mode

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Fix logic for throwing exception in getRecordIndexUpdates.
None
Low
None
> [HUDI-6819] Fix logic for throwing exception in getRecordIndexUpdates.

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/FlinkCompactionMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/FlinkWriteMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/HoodieFlinkMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactOperator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/CompactFunctionWrapper.java
Support flink compaction metrics
sub-task for HUDI-2141
Support flink compaction metrics
low
Will update documents in another pr
> [HUDI-2141] Support flink compaction metrics

- hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
- hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
- hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Remove the log file appending totally to simplify the log file rollback and exception handling for reader.
none
none
> [HUDI-6742] Remove the log file appending for multiple instants

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
- Adjust the scenarios to cover GLOBAL_SIMPLE and GLOBAL_BLOOM cases.
- For MDT disabled/enabled case, disable/enable both writer and reader
Manual spark sql tests (as it's not running by CI)
None. Test only.
NA
> [HUDI-6835] Adjust spark sql core flow test scenarios

- hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
Fixing failing tests with BQ sync tests.
Fixing failing tests with BQ sync tests
low.
> [MINOR] Fixing failing tests with BQ sync tests

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/KeyRangeLookupTree.java
Refer to the implementation of Math.max() and Math.min(). 
This way you can unify the style of the if branch statement above.
Make source code more readable.
NONE
NONE
NONE
> [MINOR] Improve the logic when building bloom filter KeyRangeLookupTree

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
A hbase index config inproper use
N/A
N/A
N/A
> [MINOR] Fix hbase index config improper use

- hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/client/HoodieMetaserverClientProxy.java
Automatic release connection
Reduce port occupation.
none
none
> [HUDI-6630] Automatic release connection for hoodie metaserver client

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSqlStatement.scala
replace directory connector markers in TestSqlStatement
replace directory connector markers in TestSqlStatement
none
N/A
> [HUDI-6862] Replace directory connector markers in TestSqlStatement

- website/docs/quick-start-guide.md
- website/versioned_docs/version-0.13.0/quick-start-guide.md
- website/versioned_docs/version-0.13.1/quick-start-guide.md
make the spark start command consistent with the `README.md`
none
none
> [DOCS] Add new conf about kryo registrator to spark start command

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieReaderWriterBase.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
Close record readers in TestHoodieReaderWriterBase after use during tests
none
> [MINOR] Close record readers in TestHoodieReaderWriterBase after use during tests

- website/docs/quick-start-guide.md
As above.
Docs update.
none
As above.
> [HUDI-6341][DOCS] Add Spark 3.4 support in quick start

- website/src/pages/roadmap.md
update 0.14.0 timeline in roadmap page
minor
low
> [DOCS][MINOR] Update roadmap page for 0.14.0 timeline

- scripts/release/validate_staged_bundles.sh
Enhancing validate staged bundles script
Enhancing validate staged bundles script
none
> [MINOR] Enhancing validate staged bundles script

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
Abstract repetitive commit in `CommitActionExecutor`
Abstract repetitive commit in `CommitActionExecutor`
low
none
> [HUDI-6584] Abstract commit in CommitActionExecutor

- website/docs/flink-quick-start-guide.md
Add more information for Flink quick start.
None
None
> [HUDI-6880] Update Flink quick start for release 0.14.0

- website/docs/querying_data.md
Updates to the StarRocks entry for Hudi.
Updates to the StarRocks entry for Hudi.
None
low
Just updating the documentation links and text per newer version of StarRocks
> [DOCS] Update StarRocks support in querying_data.md

- .github/workflows/bot.yml
- azure-pipelines-20230430.yml
Update the options passed in to maven install commands to help with connection issues seen in recent builds. I found the options in this StackOverflow post https://stackoverflow.com/questions/55899091/maven-retry-dependency-download-if-failed
Improve build stability 
None
> [MINOR] Set connection settings for maven to avoid build flakiness

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Fix the check for connector identity in HoodieHiveCatalog
Fix the check for connector identity in HoodieHiveCatalog
none
none
> [MINOR] Fix the check for connector identity in HoodieHiveCatalog

- website/docs/syncing_metastore.md
- Added a brief intro about Hive metastore.
- Removed deprecated config.
- Added default values and better explanation for rest of the configs.
Docs update.
low
> [DOCS] Update hive metastore sync docs

- website/docs/flink-quick-start-guide.md
- website/versioned_docs/version-0.13.1/flink-quick-start-guide.md
Fixed the unclosed dependency version tags.
Just docs changes.
none
> [MINOR][DOC] Fixe the unclosed dependency version tags

- rfc/README.md
Minor typo fix after conflict resolution.
none
none
> [MINOR] RFC readme fix

- hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
- hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieSanity.java
Will be fixed in HUDI-6917. Disabling to unblock other PRs and let the tests continue.
none
none
> [MINOR] Disable falky integration test temporarily

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/CopyOnWriteInsertHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/HoodieLazyInsertIterable.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/execution/ExplicitWriteHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
> [HUDI-6937]CopyOnWriteInsertHandler#consume cause clustering performance degradation

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
Async archiving for Flink.
none
none
> [HUDI-6939] Add async archiving for Flink

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
add ut for https://issues.apache.org/jira/browse/HUDI-6941 for stages number check
none
none
> [HUDI-6941] Add unit test for HUDI-6941 for stages number check

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
- pom.xml
- scripts/release/validate_source_copyright.sh
fix https://github.com/apache/hudi/issues/7204
fix hive snapshot query add non hoodie paths file status
medium. Unit Tests to verify changes
N/A
> [HUDI-5220] fix hive snapshot query add non hoodie paths file status

- website/docs/flink-quick-start-guide.md
Restructuring of Flink Quickstart page and follow the Spark Quickstart guide.
website hygiene
low
> [Docs] Flink Quickstart Restructuring

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/CompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
Make the lazy loading more smart and efficient.
none
none
> [HUDI-6929] Lazy loading dynamically for CompletionTimeQueryView

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
Minor code refactor to HoodieArchivedTimeline.
none
none
> [HUDI-7019] Add instant details consumer to HoodieArchivedTimeline

- website/docs/cli.md
see [PR 9937](https://github.com/apache/hudi/pull/9937), HUDI-6382
new function in hudi-cli
none
- Add new table command to hudi-cli, nameing `table change-table-type <target-table-type>`
> [Docs] add function doc for hudi table type change command

- website/blog/2023-11-01-record-level-index.md
[MINOR] Fixing rli blog index latency image link
[MINOR] Fixing rli blog index latency image link
none
> [MINOR] Fixing RLI blog index latency image link

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/ShowHoodieTablePartitionsCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestShowPartitions.scala
ShowPartitionsCommand should consider lazy delete_partitions, fix comments here: https://github.com/apache/hudi/pull/4489#issuecomment-1287063774
None
None …
> [HUDI-7054] ShowPartitionsCommand should consider lazy delete_partitions

- website/src/theme/BlogPostItem/index.js
blog pages redirection bug fix
web site changes
low
> [DOCS] Minor Bug fix for blogs page

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
This PR adds the support of reading only log files in the file group reader-based Spark parquet file format (`HoodieFileGroupReaderBasedParquetFileFormat`).
- In `HoodieFileGroupReaderBasedParquetFileFormat#buildReaderWithPartitionValues`, the record iterator from the new file group reader is returned when there are only log files in a file group.
- Fixes the log file iterator to properly project the data based on the required / reader schema in `SparkFileFormatInternalRowReaderContext`.
- Adds new tests on read log files only in `TestHoodieFileGroupReaderBase`.
As above, improves functionality.
low
N/A
> [HUDI-7055] Support reading only log files in file group reader-based Spark parquet file format

- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
HoodieBaseFileGroupRecordBuffer does a record merge and then gets the option without checking. testBaseFileAndLogFileUpdateMatchesDeleteBlock exposes that the option can be empty. The fix is to check and return an empty option if that is the case
get rid of failure point
none
N/A
> [HUDI-7058] Check if option is empty before get in HoodieBaseFileGroupRecordBuffer

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieIncrementalFileIndex.scala
hasPushedDownPartitionPredicates is not set to true in all cases when listFiles is called, so the planner repeatedly tries to resolve it
no more stack overflow
low
N/A
> [HUDI-7047] Fix Stack Overflow Caused by partition pruning

- website/docs/procedures.md
Add doc for partital columns to copy_to_table
none
none
> [DOC] Add doc for partital columns to copy_to_table

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
COW: BaseFileOnlyRelation.
MOR: HoodieBootstrapMORRelation.
Low.
Low.
> [HUDI-7060] Handle time travel queries using snapshot relation

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java
> [MINOR] Add logs in PartitionAwareClusteringPlanStrategy

- packaging/bundle-validation/base/build_flink1146hive313spark313.sh
We are gonna remove the support for flink 1.13, so update the bundle validation scripts. 
none
none
> [HUDI-7082] Add Flink 1.14 and Spark 3.13 docker image script

- website/docs/procedures.md
> [DOC] Add args for ShowProcedures

- doap_HUDI.rdf
Update DOAP with 1.0.0-beta1 release.
Proceed with release.
none
> [MINOR] Update DOAP with 1.0.0-beta1 Release

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
throw a exception when using bulk_insert and stream mode
no
no
no
> [Minor] throw a exception when using bulk_insert and stream mode

- website/docusaurus.config.js
- website/releases/release-1.0.0-beta1.md
Link tech spec for Hudi 1.0 under `Learn` dropdown and in the 1.0.0-beta1 release notes.
Increase visibility of tech specs.
low
> [MINOR] Link tech specs for Hudi 1.0

- website/src/pages/tech-specs-1point0.md
Add some details on log compaction and async indexer.
Update tech spec 1.0.
none
> [MINOR] Update spec for log compaction and indexer

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
[MINOR] Removing unnecessary guards to row writer with deltastreamer
[MINOR] Removing unnecessary guards to row writer with deltastreamer
none
> [MINOR] Removing unnecessary guards to row writer with deltastreamer

- README.md
[![Twitter Follow](https://img.shields.io/twitter/follow/ApacheHudi)](https://twitter.com/apachehudi)
NA
LOWEST
Readme update
- [Y] Read through [contributor's guide](https://hudi.apache.org/contribute/how-to-contribute)
- [Y] Change Logs and Impact were stated clearly
> Fixed twitter link to redirect to twitter

- hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
- hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
Add support for Hopsworks File System (HopsFS)
No
None
> [MINOR] Add Hopsworks File System to StorageSchemes

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodiePartitionCDCFileGroupMapping.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
Remove unused import
None
None
> [MINOR] Remove unused import

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/HttpRequestClient.java
- hudi-common/pom.xml
- hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
- pom.xml
Making perf enhancements to JSON serde. 
1. Fixed ObjectMapper to use AfterBurnerModule to improve perf. 
2. Fixed ObjectMapper to be instantiated once. 
3. Fixed TypeReference used to execute http requests to avoid repeated instantiations. 
Perf improvements to Json Serde   …
> [HUDI-7095] Making perf enhancements to JSON serde

- website/docs/flink-quick-start-guide.md
- website/versioned_docs/version-0.14.0/flink-quick-start-guide.md
Fix the link of Flink create catalog in latest abd version 0.14.0 quick start guide.
Docs change.
none
> [DOCS] Fix the link of Flink create catalog

- hudi-examples/hudi-examples-dbt/.gitignore
- hudi-examples/hudi-examples-dbt/README.md
- hudi-examples/hudi-examples-dbt/dbt_project.yml
- hudi-examples/hudi-examples-dbt/models/example_cdc/profile_changes.sql
- hudi-examples/hudi-examples-dbt/models/example_cdc/profiles.sql
- hudi-examples/hudi-examples-dbt/models/example_cdc/raw_updates.sql
- hudi-examples/hudi-examples-dbt/models/example_cdc/schema.yml
Add a new example project to illustrate dbt usage with CDC.
Show usage with dbt.
None.
NA
> [HUDI-7149] Add a dbt example project with CDC capability

- hudi-common/src/main/java/org/apache/hudi/common/config/ConfigProperty.java
Remove useless ) for ConfigProperty.toString
> Remove useless ) for ConfigProperty.toString

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/common/HoodieWriteCommitCallbackMessage.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
Add commit action type and extra metadata to write callback on commit message
No impact on the commit callback API
low to medium
> [HUDI-7161] Add commit action type and extra metadata to write callback on commit message

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
> [HUDI-7165][FOLLOW-UP] Add test case for stopping heartbeat for un-committed events

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
Fixing view manager reuse with Embedded timeline server
Fixing view manager reuse with Embedded timeline server
low
> [MINOR] Fixing view manager reuse with Embedded timeline server

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSource.scala
Added the search for meta columns.
Make the test pass.
LOW.
> [HUDI-7077] Fix missing field error caused by meta columns

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Disabling the test due to its flakiness.
No impact.
Low due to its flakiness.
> [HUDI-7174] Disable a flaky test

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestNestedSchemaPruningOptimization.scala
Just try to re-enable the test.
Fixing the bugs.
LOW
> [HUDI-7078] Re-enable TestNestedSchemaPruningOptimization

- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java
Fixing integ test writer for commit time generation
Fixing integ test writer for commit time generation
low
> [MINOR] Fixing integ test writer for commit time generation

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/prune/PartitionPruners.java
Comparison between defaultParName and partValue
> [HUDI-7169]Comparison between defaultParName and partValue

- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowFileSystemViewProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestFsViewProcedure.scala
fix call show_fsview_all failure error due to not specify partition path
_no._
_none._
1. https://issues.apache.org/jira/browse/HUDI-7186
> [HUDI-7185] fix call show_fsview_all failure error due to not specify partition path

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
call register metric before rollback compcation
```
at org.apache.hudi.client.transaction.lock.metrics.HoodieLockMetrics.<init>(HoodieLockMetrics.java:57)
at org.apache.hudi.client.transaction.lock.LockManager.<init>(LockManager.java:67)
at org.apache.hudi.client.transaction.lock.LockManager.<init>(LockManager.java:56)
at org.apache.hudi.client.transaction.TransactionManager.<init>(TransactionManager.java:45)
at org.apache.hudi.table.action.rollback.BaseRollbackActionExecutor.<init>(BaseRollbackActionExecutor.java:89)
at org.apache.hudi.table.action.rollback.BaseRollbackActionExecutor.<init>(BaseRollbackActionExecutor.java:72)
at org.apache.hudi.table.action.rollback.MergeOnReadRollbackActionExecutor.<init>(MergeOnReadRollbackActionExecutor.java:47 …
```
> [HUDI-7196]Call register metric before rollback compcation for CompactionPlanOperator

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Add test case with the partition value is null to PartitionPruner
test case
> [HUDI-7169][TEST]Add test case with the partition value is null to PartitionPruner

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
Optimize contains impl with HoodieDefaultTimeline
Optimize contains impl with HoodieDefaultTimeline
low
> [HUDI-7199] Optimize contains impl with HoodieDefaultTimeline

- website/src/pages/roadmap.md
Updating timeline for 0.14.1
Updating timeline for 0.14.1
low
> [MINOR] Updating timeline for 0.14.1

- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
- hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
- hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_5Adapter.scala
Changes:
1. removed some unused imports.
2. reordered some imports.
None.
None.
> [MINOR] Clean some imports for some files

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieConversionUtils.scala
This regression was introduced in https://github.com/apache/hudi/pull/10173, so reverting the change in logic for HoodieConversionUtils.fromProperties
No impact on perf or reliability.
Low
> [HUDI-7138] Fix scala typed properties conversion for schema evol

- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestCustomMerger.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestEventTimeMerging.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieAvroRecordTestMerger.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestHarness.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieRecordTestPayload.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
Note: This PR is based on https://github.com/apache/hudi/pull/10277,
the only new part is the file: TestCustomMerger.java
1. Added a custom merger class;
2. Plug it into the test framwork;
3. Added a few tests to verify the logic of the merger.
Verified the workflow of custom merger.
None.
> [HUDI-7177] Test custom merger for MOR tables

- rfc/rfc-66/rfc-66.md
Add a generalized abstract to RFC-66.
LOW.
None.
> [MINOR] Add a brief abstract to RFC-66

- hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
Add StorageSchemes for Aliyun Apsara File Storage for HDFS
none
> [MINOR] Add StorageSchemes for Aliyun Apsara File Storage for HDFS

- README.md
- website/src/pages/talks.md
added hudi focused talks/presentations[
](url)
cc @bhasudha
> DOC-added talks/presentations

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetricsReporter.scala
> [HUDI-7257] missing datadog configuration metrics on mdt

- hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/TimelineRelation.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logcal/HoodieTimelineTableValuedFunction.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark32PlusAnalysis.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/TableValuedFunctions.scala
A new TVF, `hudi_timeline_query(...)` is added to support querying timeline through spark-sql. The information displayed is influenced by the 'Commits' command of hudi-cli (with some additional information).
A new relation, `TimelineRelation`, is added to transparently support this functionality. The relation implements `buildScan(...)` method of `TableScan` trait. It does not support filter or predicate push-down. Column filtering and predicate evaluation needs to be done by the execution layer. This seems reasonable for the initial implementation for this tool which is mainly going to be used as a debugging/introspection tool. The relation defines a fixed schema based on the information present ina Hudi timeline instant.
A new TVF, `hudi_timeline_query(...)` is added to support querying …
> [HUDI-7243] TVF to query hudi timeline through spark sql

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
HoodieFlinkStreamer should disable compaction in pipeline with append mode
low
low
> [HUDI-7268] HoodieFlinkStreamer should disable compaction in pipeline with append mode

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
If node path does not exist , we have to manually create it for zookeeper otherwise it fails to connect .
this patch fixes it  .
Lock provider improvements
low
> [HUDI-7198]Create nested node path if does not exist for zookeeper.

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
> Revert "[HUDI-7198]Create nested node path if does not exist for zookeeper."

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/ArchivalUtils.java
> [MINOR] Fix ArchivalUtils Logger name

- website/releases/release-0.14.1.md
Fixing 0.14.1 release docs
Fixing 0.14.1 release docs
none
> [MINOR] Fixing 0.14.1 release docs

- doap_HUDI.rdf
Updating doap file for 0.14.1 release
Updating doap file for 0.14.1 release
none
> [MINOR] Updating doap file for 0.14.1 release

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/FlinkClusteringMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitSink.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanOperator.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/ClusteringFunctionWrapper.java
add clustering metric for flink
no
low
add clustering metric for flink
> [HUDI-7266] add clustering metric for flink

- website/docs/syncing_onetable.md
- website/sidebars.js
- website/versioned_docs/version-0.14.0/syncing_onetable.md
- website/versioned_docs/version-0.14.1/syncing_onetable.md
- website/versioned_sidebars/version-0.14.0-sidebars.json
- website/versioned_sidebars/version-0.14.1-sidebars.json
Added OneTable to Catalogs page for both current and 0.14.0 (only supported from 0.14 onwards)
Doc change, minor.
Minor
Doc update
- [NA] CI passed
> [DOCS] Added onetable support

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
After apply [HUDI-6941](https://issues.apache.org/jira/browse/HUDI-6941) in the internal HUDI version(based on 0.14.0 version), there is a frequent occurrence of the execution plan selecting "broadcast hash join" to broadcast a large HUDI data source.
I tried to investigate the cause of this issue.
Those old query jobs does not set `spark.sql.extensions` as `HoodieSparkSessionExtension` because the user does not known the source table has been migrate from Hive table to HUDI table. So the `HoodiePruneFileSourcePartitions` is not taking effect. Then when `JoinSelection` call `HoodieFsRelation#Relation#sizeInBytes` which routing to `FileIndex#sizeInBytes`, it would return 0 because `FileIndex` using  lazy list mode by default. It causes broadcast the HUDI source.
And after apply …
> [HUDI-7241] Avoid always broadcast HUDI relation if not using HoodieSparkSessionExtension

- azure-pipelines-20230430.yml
Experimenting with Azure DevOps test reporting and flaky test detection
None 
low 
None
> [MINOR] Turning on publishing of test results to Azure Devops

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
[MINOR] Parallelized the check for existence of files in IncrementalRelation.
Parallelized the check for existence of files in IncrementalRelation.
Faster check during IncrementalRelation for large datasets with thousands of files.
None
None
> [MINOR] Parallelized the check for existence of files in IncrementalRelation.

- .github/workflows/bot.yml
The reason is to clean up any orphan resources.
Low.
None.
> [HUDI-6902] Use mvnw command for hadoop-mr test

- pom.xml
Changes:
1. Set initial memory 128M.
Low.
None.
> [HUDI-6902] Set minimum memory for unit tests

- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/ParquetDFSSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/ParquetDFSSource.java
ParquetDFSSource will merge the schema across files in a particular read.
https://issues.apache.org/jira/browse/HUDI-7300
ParquetDFSSource will merge the schema across files in a particular read.
Low
- We've added a new config to the ParquetDFSSource for them to merge the schema across all parquet files in a single commit.
- https://github.com/apache/hudi/pull/10463
> [HUDI-7300] Merge schema in ParuqetDFSSource

- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
The  modification_time may be consistent may the same, fix ut
None
None
None
> [MINOR] fix eager rollback mdt ut

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
- hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
> [MINOR] Revert "[MINOR] Handle parsing of all zero timestamps with MDT suffixes."

- website/docs/file_layouts.md
This PR adds an updated diagram for the 'File Layout' page
Updates the diagram for the page for better clarity
None
Update was for documentation
- CI passed
> [DOCS] Diagram Change for File Layout Page

- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsSource.java
> [HUDI-6902] Fix a unit test

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Use try-finally statement to wrap the logic.
Shutdown the hooks properly. Otherwise, we could have orphan processes in some corner cases.
None.
> [HUDI-6902] Shutdown metric hooks properly

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
https://github.com/apache/hudi/pull/10467 was not implemented correctly. Added testing and fixed implementation.
Fix incorrect method
low
N/A
> [HUDI-7284] Fix cluster stream sync check

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
FlinkTableFactory snatifyCheck should contains index type
low
none
> [HUDI-7317] FlinkTableFactory snatifyCheck should contains index type

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkConsistentBucketClusteringExecutionStrategy.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/ConsistentBucketIndexBulkInsertPartitionerWithRows.java
- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
Consistent Hashing row writer support sorting
now consistent hashing clustering support sorting
low
NONE
> [HUDI-7302] Consistent hashing row writer support sorting

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanOperator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
> [MINOR] add logger to CompactionPlanOperator & ClusteringPlanOperator

- website/docs/cloud.md
- website/docs/flink-quick-start-guide.md
- website/docs/flink_tuning.md
- website/docs/procedures.md
- website/docs/quick-start-guide.md
- website/docs/tuning-guide.md
- website/sidebars.js
Change left navigation for better organization
site change
No risk. site update.
> Improve left nav for better layout

- website/src/pages/index.js
took down the banner  @bhasudha
> took down the banner

- website/releases/release-0.14.1.md
> [Docs] Added known regression note for 0.14.1 release related to ComplexKeyGen

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Hive Sync was not able to extract the password from Hadoop credential store. Added logic to do the same if available. While using Dataproc server less, Hive sync was not able to extract the secrets stored in credential store.
low
> [HUDI-6868] Support extracting passwords from credential store for Hive Sync

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/schema/SchemaProvider.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDataTableValidator.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDropPartitionsTool.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotCopier.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieWithTimelineServer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/TableSizeStats.java
Serializable Class need contains serialVersionUID to keep compatibility，avoid report need 
Serializable id in upgrade
low
low
> [HUDI-7387] Serializable Class need contains serialVersionUID to keep compatibility in upgrade

- rfc/rfc-63/rfc-63.md
> [MINOR] Update func index RFC

- hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Fixes #10595
People having the issue should drop the glue table and recreate it from scratch w/ this patch
None
> [HUDI-7362] Fix hudi partition base path scheme to s3

- hudi-hadoop-common/src/test/java/org/apache/hudi/storage/hadoop/TestHadoopStorageConfiguration.java
As above to make test class name shorter.
Improve code quality.
none
N/A
> [MINOR] Rename test class to TestHadoopStorageConfiguration

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
Fix flaky test introduced in PRhttps://github.com/apache/hudi/pull/10619
Fixes flaky CI test
None 
> [HUDI-7381]  Fix flaky test introduced in PR 10619

- hudi-common/src/main/java/org/apache/hudi/common/HoodieSchemaNotFoundException.java
- hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
- hudi-common/src/main/java/org/apache/hudi/internal/schema/convert/AvroInternalSchemaConverter.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieEmptyRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
don't allow deduce schema to return null
If schema is not found, instead of exception use an empty relation
Remove stream failure scenario
low
N/A
> [HUDI-7147] Fix npe stream sync first batch, empty schema, upsert

- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveQueryDDLExecutor.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestFilebasedSchemaProvider.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlFileBasedSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Changed:
1.  Ensured Hive DDL executor released correctly and fully.
3. Fixed the resource releasing bugs.
The 4th module has been executed for 10+ times, and no failures at all.
Reduced flakiness of CI.
None.
> [MINOR] Release resources safely in tests

- website/docs/sql_queries.md
- website/versioned_docs/version-0.14.0/sql_queries.md
- website/versioned_docs/version-0.14.1/sql_queries.md
Wtih recent Athena queries, Hudi MOR tables are not queryable. Update in the docs until fixed.
Docs update.
none
> [DOCS] Update about recent Athena upgrade query failures

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
Just return early when short circuit conditions are encountered...
None.
None.
> [MINOR] Refactor the init method of HoodieAppendHandle.

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
As above, to fix logging messages which do not properly embed intended information to log.
Fixes logging.
none
N/A
> [HUDI-7426] Fix logging issues in StreamSync

- website/docs/write_operations.md
updated the delete description to include duplicate data
@xushiyan
> updated delete to mention duplicates- and did some writing cleanup

- .github/workflows/azure_ci.js
- .github/workflows/scheduled_workflow.yml
As above, to make sure all irrelevant PRs are filtered out in the results to reduce response size and all relevant PRs are processed from the paginated response.  This PR also makes the comment listing paginated to avoid missing some comments for processing.
HOTFIX: SKIP AZURE CI
no need to check Azure CI result as only script update
Tested by #10750.
As above.
none
N/A
> [HUDI-7438] Improve the filtering of PRs and pagination in scheduled workflow

- .github/workflows/azure_ci_check.yml
As above, to fix the GitHub workflow checking Azure CI report.
HOTFIX: SKIP AZURE CI
script update only
Fixes bug.
none
N/A
> [HUDI-7438] Fix workflow condition for issue_comment events

- .github/workflows/azure_ci_check.yml
As above.
HOTFIX: SKIP AZURE CI
script update only
Bug fix.
none
N/A
> [HUDI-7438] Fix issue number fetch in Azure CI check

- hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/Key.java
- hudi-common/src/main/java/org/apache/hudi/common/util/queue/BaseHoodieQueueBasedExecutor.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
As above.
Fixes typo.
none
N/A
> [MINOR] Fix typos in hudi-common module

- website/src/pages/tech-specs.md
Add notes to clarify more about column stats.
NA
NA
NA
> [DOCS] Add notes for column stats in tech spec

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
> [MINOR] Update HoodieMetadataPayload bloom index error message

- website/docs/clustering.md
Clarify clustering for java execution strategy
NA
NA
NA
> [DOCS][HUDI-7398] Add note for java clustering execution strategy

- website/docs/indexing.md
updated the indexing docs so the record index includes point looks up & also did some minor clean up on the writing of the other indexes 
@xushiyan
> [DOCS][MINOR] Docs clarification around read and write indexes

- website/docs/sql_queries.md
update doris doc with compatibility 
none
low
update doris doc
> initial commit to update doris docs

- website/docs/indexing.md
- website/docs/write_operations.md
updated indexing docs to include a quick note about the metadata table and multi-modal indexing
> Docs update indexing to include multimodal indexing

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Added basepath to task labels and logging wherever necessary for easier debugging. Also, logging some stats for upsert partitioner.
none
none
> [MINOR] Improve mdt validator and upsert partitioner logs

- website/src/theme/Navbar/index.js
Add scarf pixel in the top nav bar so all website pages can be tracked.
Use scarf.sh for website analytics. Approved by asf: https://privacy.apache.org/faq/committers.html
NA
NA
> [WEBSITE] Add scarf for website analytics

- website/docs/procedures.md
- website/versioned_docs/version-0.13.1/procedures.md
- website/versioned_docs/version-0.14.0/procedures.md
- website/versioned_docs/version-0.14.1/procedures.md
Add explanation for deduplicate command to the docs.
I've also updated the example in the docs to have a temp path for the repaired_output_path to avoid confusion.
None. No code changes involved
Low
- [X ] Read through [contributor's guide](https://hudi.apache.org/contribute/how-to-contribute)
- [ X] Change Logs and Impact were stated clearly
> [DOCS] Add explanation for deduplicate command

- hudi-gcp/pom.xml
- packaging/hudi-gcp-bundle/pom.xml
- pom.xml
Update libraries-bom in hudi-gcp-bundle/pom.xml to 26.15.0, same as hudi-gcp/pom.xml
enable newer version of bigquery library for the bundle
low
> [HUDI-7459] Update hudi-gcp-bundle pom

- scripts/release/deploy_staging_jars.sh
- scripts/release/validate_staged_bundles.sh
Some release scripts updates for 0.12.3
Some release scripts updates for 0.12.3
low
N/A
> [MINOR] Release 0.12.3 script update

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Adding test for composite keys with bulk insert row writer
Improve test coverage
none
N/A
> [HUDI-6953] Adding test for composite keys with bulk insert row writer

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
- hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
Clean unused methods and parameters of `FileSystemViewManager`
No
Low
No
> [MINOR] Clean code of FileSystemViewManager

- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndexClient.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
The functional index creation code-path creates a `HudiTable` object and gets a metadata writer. But, this code path (of creating metadata writer) also deletes the existing MDT partitions iff the write-config does not contain the relevant MDT/index configs. This logic is contained within `HoodieTable::deleteMetadataIndexIfNecessary`.
The existing code in `HoodieSparkFunctionalIndexClient::create` is the entry point for functional index creation. This creates a custom write-config in `HoodieSparkFunctionalIndexClient::buildWriteConfig` which is then used to create a client for the base table (on which the functional index needs to be created).  This PR fixes the issue noted earlier by adding the relevant MDT partitions config in `HoodieSparkFunctionalIndexClient::buildWriteConfig`. A test …
> [HUDI-7472] prevent MDT partitions from getting dropped

- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/S3EventsHoodieIncrSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/GcsObjectMetadataFetcher.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
Create a common method for filtering in S3 and GCS sources and add tests for filtering out extensions
Cleaner/ maintainable code and better test coverage 
Low
> [HUDI-7418] Create a common method for filtering in S3 and GCS sources and add tests for filtering out extensions

- pom.xml
Bump Spark 3.5 version from 3.5.0 to 3.5.1
None
Medium
> [HUDI-7463][branch-0.x] Bump Spark 3.5 version to Spark 3.5.1

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
ref: https://github.com/apache/hudi/pull/3306/files#diff-e6700bb657614fd972f92e1cb7c74b0f95d5164c62e298bb4712bb70db9f8ada
Reduces test run time.
none
none
> [HUDI-5167] Reducing total test run time: reducing tests for virtual keys

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/LSMTimelineWriter.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieArchivedTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
This is a subtask for goloal timeline, as the first step, we add the functionality of incremental loading for archived timeline.
none
none
> [HUDI-7476] Incremental loading for archived timeline

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGeneratorBase.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGenerators.java
Just a minor code clean.
no impact
low
no update
> [MINOR] Code clean for time generator

- website/src/theme/Navbar/index.js
Add matomo tracking code for website analytics.
Use matomo for website analytics. Approved by asf: https://privacy.apache.org/faq/committers.html
NA
NA
> [WEBSITE][MINOR] Add matomo for website analytics

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Set job context to more easily debug what is happening from the spark UI
Easier debugging
None
> [MINOR] additional job contexts for ease of debugging

- website/src/pages/powered-by.md
> [DOCS][MINOR] Update powered-by page

- website/docs/hoodie_streaming_ingestion.md
Link to transforms page from hoodie streamer page
Better discoverability.
NA
NA
> [MINOR][DOCS] Link to transforms page from hoodie streamer page

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Fixed and enabled test TestHoodieDeltaStreamer.testJdbcSourceIncrementalFetchInContinuousMode
no
none
> [MINOR] Fix and enable test TestHoodieDeltaStreamer.testJdbcSourceIncrementalFetchInContinuousMode

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieDeltaWriteStat.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieDeltaWriteStat.java
Minor refactoring to enhance reusability. @codope review please
none
none
> [HUDI-7421] Build HoodieDeltaWriteStat using HoodieDeltaWriteStat#copy

- website/src/pages/powered-by.md
> [DOCS] Add more users in the powered-by page

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
We have two `@BeforeEach` in `HoodieDeltaStreamerTestBase` without any guarantees of execution ordering. The reason for this situation is that the section with all `@Before*` and `@After*` is interrupted by `prepareInitialConfigs()` and `writeCommonPropsToFile()`. Refactored annotated methods to prevent future mistakes.
This MR could be a possible fix for HUDI-7467, but I couldn't reproduce the failure from the issue locally.
No
Low
No need
> [MINOR] Refactored `@Before*` and `@After*` in `HoodieDeltaStreamerTestBase`

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/partitioner/StreamReadAppendPartitioner.java
Fix the checkstyle for https://github.com/apache/hudi/pull/10911 
> [MINOR] Fix the checkstyle of /StreamReadAppendPartitioner

- website/releases/release-1.0.0-beta1.md
Clarify documentation on release page migration section.
Low
None. Doc changes
> [DOCS][MINOR] Fix release page docs for 1.0.0-beta1

- website/docs/sql_dml.md
Update user doc of partial insert in MERGE INTO command
None
None
None
> [HUDI-6331][DOCS] Update user doc of partial insert in MERGE INTO command

- pom.xml
upgrade mockito
newer mockito version
none
N/A
> [MINOR] Upgrade mockito to 3.12.4

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Trivial refactoring: removed code duplication in HoodieTableMetadataUtil by extracting of ClosableIterator<HoodieRecord> creation to separate method and call it from 3 different places.
none
none
none
> [HUDI-7619] Removed code duplicates in HoodieTableMetadataUtil

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSyncUnitTests.java
As above.
Cleaner code.
none
N/A
> [MINOR] Remove redundant lines in StreamSync and TestStreamSyncUnitTests

- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
As above.
Code quality improvement.
none
none
> [MINOR] Rename location to path in `makeQualified`

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
Follow-up for #11028, improvement for MDT cow and compaction performance.
none
none
none
> [HUDI-7625] Avoid unnecessary rewrite for metadata table

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/ExportCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/LogReaderUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/util/SerializationUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-examples/hudi-examples-java/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java
- hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/spark/HoodieWriteClientExample.java
- hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactionAdminTool.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SchedulerConfGenerator.java
As above.
Code improvements.
none
none
> [HUDI-7633] Use try with resources for AutoCloseable

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkPartitionUtils.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SparkSampleWritesUtils.java
Clean up usage of CachingPath outside hudi-common module
none
none
none
> [HUDI-7631] Clean up usage of CachingPath outside hudi-common module

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Minor fix to rli validation with MDT validator
Minor fix to rli validation with MDT validator
low
> [HUDI-7655] Minor fix to rli validation with MDT validator

- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/JDBCExecutor.java
fix Logger name to JDBCExecutor for JDBCExecutor
May affect log printing for JDBCExecutor
none
none
> [MINOR] fix LoggerName for JDBCExecutor

- hudi-common/src/main/java/org/apache/hudi/common/table/log/LogReaderUtils.java
As above.
Code cleanup only.
none
none
> [MINOR] Remove unused util methods in LogReaderUtils

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
RowDataKeyGen is creating excessive objects during recordKey/partitionPath computation to cut off last character from them (as methods getRecordKey, getRecordPartitionPath in RowDataKeyGen utilize deleteCharAt). Also fixed logging and strings concatenation.
none
none
none
> [HUDI-7660] Fix excessive object creation in RowDataKeyGen

- website/contribute/how-to-contribute.md
> [MINOR] Fix link

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
after https://github.com/apache/hudi/pull/10869 got landed, we are not returning every topic partition in final ranges. But for checkpointing purpose, we need to have every kafka topic partition in final ranges even if we are not consuming anything.
Checkpointing w/ kafka source is intact when certain partitions are already caught up. 
low
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setup# …
> [HUDI-7511] Fixing offset range calculation for kafka

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
#11059 introduces a change that serializes the whole meta client to be sent to the executors in the Spark DAG, which should be avoided (see https://github.com/apache/hudi/pull/11059#discussion_r1580706672).  This PR fixes the issue.
Fixes serialization overhead in Spark.
none
none
> [HUDI-7676] Fix serialization in Spark DAG in HoodieBackedTableMetadataWriter

- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
As above.
Fix build due to conflicts among PRs.
none
none
> [MINOR] Fix build on master

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanMetadataV1MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanMetadataV2MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanPlanV1MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanPlanV2MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/compaction/CompactionV1MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/compaction/CompactionV2MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/metrics/Metrics.java
> [HUDI-7681] Remove Hadoop Path usage in a few classes in hudi-common module

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMetrics.java
Make HoodieMetadataMetrics log level debug ro reduce noise
less noisy logs
none
> [HUDI-7683] Make HoodieMetadataMetrics log level debug ro reduce noise

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestSQL.java
The records must be sorted as required by the HFile writer impl.
none
none
none
> [HUDI-7684] Sort the records for Flink metadata table bulk_insert

- website/docs/reading_tables_batch_reads.md
> [DOCS] Add Daft read example

- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
We expect it to fail in the merge handle so we do not need to validate here
less confusing code
none
N/A
> [MINOR] remove unnecessary lines from java test

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
Use the HoodieMetadataPaylod util to test key.
Minor test improvement
none
> [HUDI-7706] Improve validation of partition stats index include key

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
Adding metrics to track mdt partitions enabled. 
Easier for feature rollout when enabling new partitions in MDT.
low
> [HUDI-7641] Adding metadata enablement metrics and index type metrics

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkPartitionTTLActionExecutor.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriterWithPartitionTTl.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriterPartitionTTL.scala
Partition TTL for Flink
none
none
none
> [HUDI-7715] Partition TTL for Flink

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Due to big changes from de-hadooping. A pr was merged that brakes the build on master.
Fixes master so it can build.
none
N/A
> [HUDI-7721] Fix broken build on master

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
`withInstantRange(instantRange)` has been set in line 198.
Code cleanup
low
> [MINOR] Remove duplicate settings

- website/docs/quick-start-guide.md
> [HUDI-5616][DOCS] Update spark quickstart with notes on HoodieKryoRegistrar

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
Hudi has a constraint that compaction schedule can happen only if there are no pending delta commits whose instant time < compaction instant being scheduled. We were throwing exception when this condition is not met. Fixing the user behavior here so that we do not throw exception and return an empty plan when this condition is met.
This will smoothen our experience w/ async table service since the we don't have control over ingestion writer.
low
ticket …
> [HUDI-7460] Relaxing compaction scheduling when there are pending delta commits

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
Fix failing tests for 0.15.0 branch. More details in the linked jira. 
Fix failing tests for 0.15.0 branch. More details in the linked jira. 
low
> [HUDI-7768] Branch 0.x failingtests async compaction metadata num commits check

- azure-pipelines-20230430.yml
This PR rebalances CI with the tests in the `hudi-hadoop-common` module.  Some tests are moved from `hudi-common` module to `hudi-hadoop-common` module, and we should run tests in both modules in the same task as before.
Balances CI finish time.
none
none
> [MINOR] Rebalance CI with tests in hudi-hadoop-common module

- hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
https://github.com/apache/hudi/issues/11223
none
none
none
> [MINOR] Remove legacy code and add try catch to listStatus of partition.

- hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
- hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
As above.
Simplifies `HoodieStorage` APIs.
none
none
> [HUDI-7775] Remove unused APIs in HoodieStorage

- website/src/pages/index.js
remove event banner
site changes
none
> [DOCS][MINOR] Remove events banner

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCRelation.scala
As above.
Testing only.
none
none
> [MINOR][TESTING][DNM] 0.15.0 RC1 testing

- hudi-examples/hudi-examples-flink/pom.xml
- hudi-examples/hudi-examples-flink/src/test/java/org/apache/hudi/examples/quickstart/TestHoodieFlinkQuickstart.java
Added dependency flink-metrics-dropwizard to hudi-examples/hudi-examples-flink
no
no
> [HUDI-4491] Re-enable TestHoodieFlinkQuickstart

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BucketIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
- add warning check
- some `isIndexAvailable` check will throw exception, will interrupt index selection.
none
none
none
> [MINOR] query index warning check

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/lookup/HoodieLookupFunction.java
Ignore loading data when the commit has not changed
> [HUDI-7787] Ignore loading data when the commit has not changed

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
> [minor] rename to hoodie

- .github/workflows/release_candidate_validation.yml
As above
Fixes release candidate validation script
none
none
> [MINOR] Fix Flink version in release candidate validation

- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReader.java
- hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
- Updates usage of slf4j library to match best practices
- Lowers log level to debug to avoid noisy logs
Reduces log volume
None
> [MINOR] Update log level for some MDT logs

- hudi-hadoop-common/src/test/java/org/apache/hudi/io/hadoop/TestHoodieHadoopIOFactory.java
As above, to improve the test to close resources properly.
Test improvement
none
none
> [MINOR] Improve TestHoodieHadoopIOFactory

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/BucketIndexUtil.java
[_Describe context and summary for this change. Highlight if any code was copied._]
(https://github.com/apache/hudi/issues/11288)
none
low
none
> [HUDI-7804] improve flink bucket index paritioner

- .github/workflows/bot.yml
- .github/workflows/release_candidate_validation.yml
As above, to avoid unnecessary CI runs on PRs.
Improves GitHub Ci stability.
none
non
> [MINOR] Fix GitHub CI concurrency

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
Fix LoggerName for BaseHoodieTableServiceClient
No
none
none
> [MINOR] Fix LoggerName for BaseHoodieTableServiceClient

- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
For now, all uses of `initTestServices()` are with `needsHdfs=false`, `needsHive=false`, `needsZookeeper=false`, except `HoodieDeltaStreamerTestBase`, where `needsHive=true`. So there is no problem with `initTestServices()` for now. But if we switch `needsZookeeper` to `true`, then we will face errors of Hive connection to Zookeeper in `HoodieDeltaStreamerTestBase`.
Correct order of services start:
1. Zookeeper
2. HDFS
3. Hive
Also fixed `cleanUpUtilitiesTestServices()` ordering, in reverse to corresponding initializations.
No impact
None
No need
> [MINOR] Correct order of test services start in `UtilitiesTestBase`

- hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/AbstractColumnReader.java
- pom.xml
Support Flink 1.18.1, #11393 for branch-0.x
none
low
> [HUDI-7828] Support Flink 1.18.1

- hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/AbstractColumnReader.java
- pom.xml
Adapt to Flink 1.18.1's API changes: https://github.com/apache/flink/pull/18304
None
Low
> [HUDI-7828][branch-0.x] Support Flink 1.18.1

- website/docs/syncing_aws_glue_data_catalog.md
- website/docs/syncing_metastore.md
Improve docs by explaining more on 
- partition value extractor usage
- conditional meta sync
- glue catalog sync specific configs
And fix some heading levels
> [HUDI-4967][HUDI-4834] Improve docs for hive sync and glue sync

- doap_HUDI.rdf
This PR updates DOAP with 0.15.0 Release for record keeping.
Publishes release.
none
none
> [MINOR] Update DOAP with 0.15.0 Release

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
Logging enhancement to help with debugging
Minor. This should only occasionally fallback so logs should not bloat.
none
> [MINOR] Add logs whenever fallback to fs listing even with MDT enabled

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
> [MINOR][branch-0.x] Remove calcite dependency

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java
Fix java doc of DeltaWriteProfile
none
none
none
> [HUDI-7851] Fix java doc of DeltaWriteProfile

- website/docs/procedures.md
> [DOCS] Update show_fsview_latest para

- release/release_guide.md
Minor release guide update
none
none
> [MINOR] Update release guide

- README.md
Fixed slack link in README and added Linkedin badge as well.
Github readme page update for links and badges. Impact is none.
none
> [MINOR] Fix README for Slack link update and Linkedin badge

- .asf.yaml
Allow @ad1happy2go to manage GH issues.
NA
None
None
> [MINOR] add `ad1happy2go` to github collaborators

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Enhanced sql source tests in deltastreamer. 
Enhanced sql source tests in deltastreamer. 
none
none
> [HUDI-4123] Enchancing deltastreamer sql source tests

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
Adding streaming read for mor table w/ compaction. 
Adding streaming read for mor table w/ compaction to increase test coverage.
none
none
> [MINOR] Adding tests for streaming read mor with compaction

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieMergedLogRecordScanner.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
- Minor updates to reduce the volume of logs produced during regular operation
- Lowers logging volume
None
> [MINOR] Reduce logging volume

- website/versioned_docs/version-0.13.0/snapshot_exporter.md
- website/versioned_docs/version-0.13.1/snapshot_exporter.md
- website/versioned_docs/version-0.14.0/snapshot_exporter.md
- website/versioned_docs/version-0.14.1/snapshot_exporter.md
- website/versioned_docs/version-0.15.0/snapshot_exporter.md
Adding the missing parallelism config in the snapshot exporter's doc.
site update
none
Adding the missing parallelism config in the snapshot exporter's doc.
> [DOCS] Add missing parallelism into snapshot_exporter.md

- website/src/pages/ecosystem.md
- website/versioned_docs/version-0.15.0/ecosystem.md
Add ecosystem page in top nav
site changes
none
> [DOCS] Add Ecosystem Page

- website/docusaurus.config.js
Add the ecosystem.md page in the top nav
site changes
none
> [DOCS] Update Ecosystem page

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTableDropPartition.scala
Replica of https://github.com/apache/hudi/pull/11487 for `0.x` branch
No user-facing impact.
Low as previous version with bug was working for ~year, there were couple of bugs reported, please check https://github.com/apache/hudi/pull/11487
> [HUDI-7914] Fix/replacecommit incorrect fields

- website/docs/platform_services_post_commit_callback.md
Fix documentation in addition to already merged PR https://github.com/apache/hudi/pull/10970
none
none
Added config param to Http Endpoints info.
> [HUDI-6441][DOCS] Passing custom Headers with Hudi Callback URL

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/ConsistentBucketAssignFunction.java
Fix NullPointerException after a clustering plan is finished
None
None
None
> [MINOR] Fix NPE after a clustering plan is finished

- website/docs/snapshot_exporter.md
Fix documentation in addition to already merged PR https://github.com/apache/hudi/pull/11509
none
none
Added new configuration options and example of the feature to Snapshot exporter page.
> [HUDI-7403][DOCS] Support Filter/Transformer to Hudi Exporter Utility

- hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
Clean up SchemaTestUtil code, delete duplicate code
none
none
none
> [HUDI-7965] Clean up SchemaTestUtil code

- hudi-examples/hudi-examples-k8s/Dockerfile
- hudi-examples/hudi-examples-k8s/README.md
- hudi-examples/hudi-examples-k8s/config/hadoop/core-site.xml
- hudi-examples/hudi-examples-k8s/config/k8s/flink-deployment.yml
- hudi-examples/hudi-examples-k8s/config/k8s/minio-standalone.yaml
- hudi-examples/hudi-examples-k8s/pom.xml
- hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/HudiDataStreamWriter.java
- hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/utils/DataGenerator.java
- hudi-examples/pom.xml
Add K8s example for Flink Hudi ingegration
No public API changes.
No Risk 
Added README for the new module
> [HUDI-7929] create k8s example for flink hudi integration

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/ShowHoodieCreateTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
add show create table command feature 
none
none
> [HUDI-7962] Add show create table command

- packaging/bundle-validation/README.md
- packaging/bundle-validation/base/Dockerfile
- release/release_guide.md
Improve release docs and update some links. 
Release guide improvement.
none
> [MINOR] Improve release docs and update some links

- website/src/pages/index.js
- website/src/theme/LayoutHead/index.js
- website/src/theme/LayoutHead/useTitleFormatter.js
> [DOCS] fix: update home page title

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieCleanerTestBase.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/SyncableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Fixing file system view closures in MDT code paths. 
Fixing file system view closures in MDT code paths. 
low.
> [HUDI-7921] Fixing file system view closures in MDT

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
- hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/BasicDao.java
Fixed codestyle of license and package statement ordering.
No
None
No need
> [MINOR] Codestyle of license and package statement ordering

- doap_HUDI.rdf
This PR updates DOAP with 1.0.0-beta2 Release for record keeping.
Publish new release version
none
> [MINOR] Update DOAP with 1.0.0-beta2 Release

- website/docs/sql_ddl.md
add doc for HUDI-7962 about show create table feature
none
none
> [DOCS] Add doc update for HUDI-7962

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Before merge of https://github.com/apache/hudi/pull/10957, there was no need to pass Spark config:
`spark.kryo.registrator=org.apache.spark.HoodieSparkKryoRegistrar`
in PySpark.
Now we got NullPointerException described in https://github.com/apache/hudi/issues/11616 due to not properly broadcasted `HadoopStorageConfiguration`.
This MR brings back previous behavior by broadcasting of `org.apache.spark.util.SerializableConfiguration`.
Brings back the same behavior as 0.15.0 release without mandatory setting of `spark.kryo.registrator`.
Low
No need
> [HUDI-7938] Broadcast `SerializableConfiguration` to avoid NullPointerException in Kryo SerDe

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
Fix wrong skipClean description in HoodieClusteringJob.java
No impact.
None
Corrected wrong skipClean description in HoodieClusteringJob.java
> [HOTFIX] Fix wrong skipClean description in HoodieClusteringJob.java

- hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/HudiDataStreamWriter.java
- hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/utils/DataGenerator.java
Fixed checkstyle in java code of k8s example for Flink Hudi integration (HUDI-7929). Only fixed indentation and spaces.
Made checkstyle:check pass.
none
none
> [MINOR] Fixed checkstyle in k8s example code (HUDI-7929)

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieCommitMetadata.java
Refactored method `HoodieCommitMetadata.getFileSliceForFileGroupFromDeltaCommit` to avoid doing the json tree walking.
none
none
none
> [HUDI-4822] Extract the baseFile and logFiles from HoodieDeltaWriteStat in the right way

- .github/workflows/bot.yml
Disable gh actions tests for spark < 3.3
step in removing support for older versions of spark
low
N/A
> [HUDI-7999] Disable CI for spark < 3.3

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/AvroConvertor.java
This PR improves error logging in JSON Avro conversion by adding the schema string for the conversion to the error message, to help debug conversion issues.
Improves error logging.
none
none
> [MINOR] Improve error logging in JSON Avro conversion

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowInvalidParquetProcedure.scala
ShowInvalidParquetProcedure add parameter to support delete
none
none
none
> [HUDI-8007] ShowInvalidParquetProcedure support delete by parameter

- website/docs/procedures.md
update  show_invalid_parquet  procedures parameter
NA
NA
procedure of show_invalid_parquet parameter is update
> [Docs]update show_invalid_parquet parameter

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestCreateTable.scala
Without throwing error, table gets created with incorrect partitions if values are inserted in the same order as create table schema.
Usability
low
> [HUDI-7964] Error out if partition schema and table schema do not match in create table command

- website/docs/metadata.md
- website/versioned_docs/version-0.14.0/metadata.md
- website/versioned_docs/version-0.14.1/metadata.md
- website/versioned_docs/version-0.15.0/metadata.md
Fix typo in metadata.md
No impact.
No risks.
Fix typo in metadata.md with no new features.
> [DOCS] Fix typo in metadata.md

- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-examples/hudi-examples-java/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java
1. Support MOR table type for HoodieJavaWriteClientExample
2. Typo Fix
Does not affect the public api
none
none …
> [MINOR]: Support MOR table type for HoodieJavaWriteClientExample

- website/releases/release-0.15.0.md
- website/versioned_docs/version-0.14.0/troubleshooting.md
- website/versioned_docs/version-0.14.1/troubleshooting.md
- website/versioned_docs/version-0.15.0/troubleshooting.md
- RLI ClassCastException Issue fix guide
- Known regression in 0.15.0
none
> [DOCS] Added RLI issue fix guidance and known 0.15.0 regression

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
1. Reduce unnecessary code paths
Reduce unnecessary code paths during judgment expression
none
none
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setu …
> [MINOR] Reduce unnecessary code paths

- .github/workflows/scheduled_workflow.yml
- Avoids running workflow on people's forks
- Less emails about failed workflows
None
> [MINOR] don't run scheduled workflow on forks

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
Cherry-pick change in master branch.
( https://github.com/apache/hudi/pull/11668 )
> [HUDI-712] Revert back to overwrite=true in HoodieSnapshotExporter

- README.md
- website/src/components/EventFeature/index.js
- website/src/pages/index.js
Site changes
Site change to add event banner
none
> [Minor] Add Events banner for upcoming Linkedin Live event

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Creating base file reader object is not necessary anymore
reduce fg reader overhead and simplify the code
low
N/A
> [HUDI-8079] Get rid of other count case for fg reader

- website/community/office_hours.md
- website/community/syncs.md
- website/docs/overview.md
- website/versioned_docs/version-0.10.0/overview.md
- website/versioned_docs/version-0.10.1/overview.md
- website/versioned_docs/version-0.11.0/overview.md
- website/versioned_docs/version-0.11.1/overview.md
- website/versioned_docs/version-0.12.0/overview.md
- website/versioned_docs/version-0.12.1/overview.md
- website/versioned_docs/version-0.12.2/overview.md
- website/versioned_docs/version-0.12.3/overview.md
- website/versioned_docs/version-0.13.0/overview.md
- website/versioned_docs/version-0.13.1/overview.md
- website/versioned_docs/version-0.14.0/overview.md
- website/versioned_docs/version-0.14.1/overview.md
- website/versioned_docs/version-0.15.0/overview.md
[DOCS] update community sync schedule
site changes to reflect office hours
site changes
none
> [DOCS] Change office hours to Wednesdays 9am

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/WriteStatMerger.java
To make the offset deterministic.
none
none
none
> [MINOR] Fix the log offset for merged write stat

- website/blog/2024-07-31-hudi-file-formats.md
- website/src/pages/index.js
site cahnges
site cahnges
none
> [MINOR][DOCS] Remove event banner

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/OneToZeroDowngradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/TwoToOneDowngradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ZeroToOneUpgradeHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Optimize HoodieTimeline#filterPendingExcludingMajorAndMinorCompaction function naming
none
none
none
> [HUDI-8108] Optimize HoodieTimeline#filterPendingExcludingMajorAndMinorCompaction function naming

- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
As described in https://issues.apache.org/jira/browse/HUDI-8078, write status rdd is not persist, it will case data write hudi 
repeat multiple times.  this pr aim to fix it.
none
low
> [HUDI-8078]Persisting writestatus to optimize the writes

- hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/DateLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/DecimalLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/DurationLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/EnumTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/FixedTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/JsonFieldProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/LocalTimestampMicroLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/LocalTimestampMilliLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/Parser.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/TimeLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/TimeMicroLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/TimeMilliLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/TimestampMicroLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/TimestampMilliLogicalTypeProcessor.java
- hudi-common/src/main/java/org/apache/hudi/exception/HoodieJsonConversionException.java
- hudi-common/src/main/java/org/apache/hudi/exception/HoodieJsonToAvroConversionException.java
- hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
Move MercifulJsonConverter from hudi-commons to hudi-utilities package, since it's where we need it. And allows us to enhance it to add new features like converting json to row.
This is mostly a code refactor, so impact will be minimal. As part of this refactor we had to remove HoodieJsonPayload since it's not required anymore with this change in place.
None …
> [HUDI-8105] Refactor MercifulJsonConverter to be extendible for Json to Row conversion

- website/src/css/custom.css
- website/src/theme/DocRoot/Layout/Main/index.js
- website/src/theme/DocRoot/Layout/Main/styles.module.css
- website/src/theme/DocRoot/Layout/Sidebar/ExpandButton/index.js
- website/src/theme/DocRoot/Layout/Sidebar/ExpandButton/styles.module.css
- website/src/theme/DocRoot/Layout/Sidebar/index.js
- website/src/theme/DocRoot/Layout/Sidebar/styles.module.css
- website/src/theme/DocRoot/Layout/index.js
- website/src/theme/DocRoot/Layout/styles.module.css
- website/src/theme/DocRoot/index.js
- website/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.js
- website/src/theme/NavbarItem/LocaleDropdownNavbarItem/styles.module.css
> docs table horizontal scroll fix

- hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCInferenceCase.java
Reformat some comments to make it more readable.
Better readability.
None.
None.
> [HUDI-6791] Format some comments

- website/src/components/EventFeature/index.js
- website/src/pages/index.js
Add events banner for next community sync event
site changes
none
> [DOCS] Add Event banner

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Improve HoodieActiveTimeline#revertCompleteToInflight parameter check
1) Parameter check
2) Corrected variable naming
none
none
none
> [HUDI-8113] Improve HoodieActiveTimeline#revertCompleteToInflight parameter check

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsSource.java
Update GcsEventsSource info logging to debug to reduce noise
None
None
None
> [HUDI-8174] Update GcsEventsSource messages info logging to debug to reduce noise

- .github/workflows/scheduled_workflow.yml
use scheduled workflow to delete the caches
Prevent ci from being broken
low
N/A
> [HUDI-8180] Delete the caches with workflow

- .github/workflows/scheduled_workflow.yml
--all flag didn't work. Try to go back to deleting 1 by 1
fix ci
low
N/A
> [HUDI-8180] use individual cache key when deleting caches

- .github/workflows/scheduled_workflow.yml
delete cache doesn't have required permissions
fix ci
low
N/A
> [HUDI-8180] Give all permissions to scheduled workflow

- website/src/theme/Navbar/Content/index.js
Add scarf pixel in the top nav bar so all website pages can be tracked.
Use scarf.sh for website analytics. Approved by asf: https://privacy.apache.org/faq/committers.html
> [WEBSITE] Ad scarf for website analytics

- hudi-io/src/main/java/org/apache/hudi/common/util/ComparableVersion.java
Improve code quality of `ComparableVersion` class
Code refactoring only.
none
N/A
> [MINOR] Improve code quality of ComparableVersion class

- website/src/pages/index.js
remove event banner
site change
none
> [SITE][MINOR] Remove Events banner

- hudi-client/hudi-client-common/pom.xml
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestEightToSevenDowngradeHandler.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
- hudi-tests-common/pom.xml
- pom.xml
1. Delete functional index, secondary index, and partition stats partitions.
2. Add configuration to avoid creation such partitions.
Fix the bug.
High.
> [HUDI-7900] Delete unsupported metadata partitions when downgrade

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/PartitionRegexBasedCompactionStrategy.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java
1. support specify partitions with regex for compaction
1. support specify partitions with regex for compaction
none
low
none …
> [HUDI-8214] Support specify partitions with regex for compaction

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroConversionUtils.scala
Cherry pick https://github.com/apache/hudi/pull/11925
NA
none
na
> [MINOR] Pass the avro exception for better information

- hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestSparkConfigUtils.scala
PR adds tests for APIs introduced in SparkConfigUtils
NA
low
NA
> [MINOR] Add tests for SparkConfigUtils

- website/community/team.md
Added new committer (wombatukun) to the Team page.
none
none
none
> [DOCS] add new committer to the Team page

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/BootstrapCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/ClusteringCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/MarkersCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/UpgradeOrDowngradeCommand.java
When adding the main args from the cli, validate that the number of args matches what is in the enum.
Ensure code correctness of CLI args, and reduce developer confusion
none
N/A
> [HUDI-8280] Validate that minargs is correct in hudi cli

- .github/workflows/bot.yml
As above, for debugging why integration tests run out of disk space.
As above.
none
none
> [MINOR] Add a step to show disk space before running integration tests

- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
- hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
The Jira aims to add validation for secondary index in HoodieMetadataTableValidator.
NA
low
NA
> [HUDI-8262] Add validation for secondary index in HoodieMetadataTableValidator

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/JavaScalaConverters.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
> [MINOR] Fix typos in JavaScalaConverters and KafkaOffsetGen

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Fixing updates to functional indexes. Prior to this patch, we were updating all file slices from latest FSV to functional index while applying any HoodieCommitMetadata. This patch fixes that only to consider files updated as part of the current commit metadata. 
Robust upates to Functional index. Prior to this patch, we were updating all file slices from latest FSV to functional index while applying any HoodieCommitMetadata. This patch fixes that only to consider files updated as part of the current commit metadata. 
low. …
> [HUDI-8341] Fixing updates to functional indexes

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
- Fix functional index update for clean operation.
- Fix filename passed while creating colstats records.
- Add a test to validate colstats record is soft deleted for cleaned file.
Correct functional index after clean operation.
low
> [HUDI-8343] Fix functional index update for clean operation

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
`OptionsResolver::isInsertOverwrite` is used in `BucketStreamWriteFunction::processElement`, which means that it's called for each record. And `OptionsResolver::isInsertOverwrite` uses strings comparison, which leads to excessive memory allocation.
Before changes:
After changes:
Memory utilization optimization
No
No need
> [HUDI-8383] Cached `OptionsResolver::isInsertOverwrite` in `BucketStreamWriteFunction::processElement`

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Fixing getLatestFileSlice calls to getLatestMergedFileSlice in MDT writer
Fixing getLatestFileSlice calls to getLatestMergedFileSlice in MDT writer.
low.
> [HUDI-8361] Fixing getLatestFileSlice calls to getLatestMergedFileSlice in MDT writer

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
Optimizing file slice pruning with col stats lookup
Optimizing file slice pruning with col stats lookup
low
> [HUDI-8390] Optimizing file slice pruning with col stats lookup

- website/src/components/EventFeature/index.js
- website/src/pages/index.js
Add event banner in site
site changes
none
> [SITE][MINOR] Add event banner for upcoming community sync

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
- Updates validations to ensure that un-committed log files are handled properly
Reduces false positives in validation errors
None
> [MINOR] Allow check for uncommitted log files in Metadata Validation

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCommandBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCorruptBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
- hudi-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieLogBlock.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileMetadataProcedure.scala
Fix log block footer incorrectly using HeaderMetadataType
none
none
none
> [HUDI-8448] Fix log block footer incorrectly using HeaderMetadataType

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
As above
Fix typo
none
As above
> [MINOR] Fix typo in payload class config docs in Hudi Streamer

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
Some more tests for functional index:
- update and verify pruning
- rollback and validate index
Test improvement
none
> [HUDI-8326] Add some more functional index tests

- hudi-examples/hudi-examples-flink/src/main/java/org/apache/hudi/examples/quickstart/HoodieFlinkQuickstart.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Removed unused imports in HoodieFlinkQuickstart, fixed TableType option in couple of parameterized tests of ITTestHoodieDataSource
fixed checkstyle, improved test coverage
none
none
> [MINOR] fixed table type option in ITTestHoodieDataSource

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestMetricsReporterFactory.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestSlf4jMetrics.java
- hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
- hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java
- hudi-common/src/main/java/org/apache/hudi/metrics/Slf4jMetricsReporter.java
1. introduce SLF4j metrics reporter
1. introduce SLF4j metrics reporter
none
none …
> [HUDI-8488] feat: introduce SLF4j metrics reporter

- website/src/pages/powered-by.mdx
Add JD to powered-by page
None
None
None
> [DOCS] Add JD to powered-by page

- website/src/css/custom.css
> fix: font size for anchor links in docs and blogs for markdown

- README.md
- doap_HUDI.rdf
- Better, accurate description for the project based on current state.
- break down features by areas.
None
None
None
> [MINOR] Change README

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
Improves metadata index config docs to be more clear.
Clarity in metadata index config docs.
none
As above
> [HUDI-8611] Improve metadata index config docs

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
We miss used target table version, and source table version.
Fix a bug.
Do proper checkpoint translation.
> [HUDI-8619] Fix stream source parameters

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
The expected row count is not always 2. but it can be gotten by group-by.
Less flakiness.
None.
> [HUDI-8633] Fix a flaky test for partition stats

- hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
`HoodieMetadataConfig.class` -> `HoodieMetaserverConfig.class`
None
none
none
> [MINOR] fix the wrong class parameter type

- README.md
Update README version description
none
none
none
> [MINOR] Update README version description

- website/docs/record_merger.md
Improves record merger docs for accuracy.
Also added the record merge write configs:
Docs improvement
none
As above
> [HUDI-8671][DOCS] Improve record merger docs

- doap_HUDI.rdf
This PR updates DOAP with 1.0.0 Release.
This PR updates DOAP with 1.0.0 Release.
none
> [MINOR] Update DOAP with 1.0.0 Release

- website/docs/metadata_indexing.md
- website/docs/quick-start-guide.md
- website/docs/sql_ddl.md
- website/docs/sql_queries.md
PR updates index related docs for Hudi 1.0 and mentions secondary index limitations as notes in various sections
NA
low
NA
> [DOCS] Update index related docs for Hudi 1.0

- website/docs/flink-quick-start-guide.md
- website/docs/quick-start-guide.md
Update Flink and Spark supported versions with Hudi 1.0.x in quickstart guide.
Docs update
none
> [DOCS] Update flink and spark versions for 1.0

- website/docusaurus.config.js
ignore truncation of preview and inline authors in blogs and video blogs when building site
none
none
> [Site][Minor]Ignore warning on blog truncation and authors in build

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
> [MINOR]  Log wheather there has data files to be read in stream read

- README.md
Update Maven and Java versions in README
Update Maven and Java versions in README
none
> [MINOR] Update Maven and Java versions in README

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Refactored `Pipelines::bulkInsert` to reduces code duplication, and makes branching inside this method more explicit.
No
No
No need
> [MINOR] Refactored `Pipelines::bulkInsert`

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java
Current validation  exception info for check metadata files has unclear semantics.
> [MINOR] Log details when the metadata files are not found.

- website/docs/concurrency_control.md
- website/docs/deployment.md
- website/docs/sql_ddl.md
- website/docs/sql_dml.md
- website/docs/sql_queries.md
- website/releases/release-1.0.0-beta2.md
- website/releases/release-1.0.0.md
Add release highlights for 1.0.0 release
Add release highlights for 1.0.0 release
low
> [DOCS] Add release highlights for 1.0.0 release

- website/docs/flink-quick-start-guide.md
- website/docs/quick-start-guide.md
- website/versioned_docs/version-1.0.0/flink-quick-start-guide.md
- website/versioned_docs/version-1.0.0/quick-start-guide.md
Update spark and flink versions in quickstart.
Update spark and flink versions in quickstart
none
> [DOCS] Update spark and flink versions in quickstart

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
Adds a test for dropping partition stats
NA
low
NA
> [HUDI-8650] Add test for dropping partition stats

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/utils/TestTransactionUtils.java
- Adds unit test
- Adds coverage and reduces risk of regressions
None
> [MINOR] Add test case validating meta-client reload in TransactionUtils

- website/docs/syncing_datahub.md
> [HUDI-8616] docs: update syncing DataHub docs

- website/i18n/cn/code.json
Fix overview banner latest version. Make it more clear.
Fix overview banner latest version. Make it more clear.
none
> [DOCS] Fix overview banner latest version

- hudi-sync/hudi-datahub-sync/pom.xml
- packaging/hudi-cli-bundle/pom.xml
- pom.xml
- bumping avro to 1.11.4
- Bundles have a new avro and other dependency binaries 
- Resolve some dependabot warnings. 
medium
none
> [MINOR] Resolving dependabot warnings

- website/src/pages/roadmap.md
Update current and future release versions in roadmap. Going forward, we will maintain latest release of 0.x and 1.x line in `Recent releases` section.
Update current and future release versions in roadmap docs.
none
> [DOCS] Update current and future release versions in roadmap

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
Adds a test for expression index with auto keygen
NA
low
NA
> [HUDI-8742] Add expression index test with auto keygen

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
Ensure secondary index gets created and updated for auto keygen tables. Added a test for the same.
Test secondary index on auto keygen tables.
low
> [HUDI-8791] Test secondary index on auto keygen tables

- pom.xml
Bump Spark version to 3.5.4
None
none
none
> [HUDI-8847] Bump Spark 35 version to 3.5.4

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestHoodieMultipleBaseFileFormat.scala
Add a check for orc files.
Improve the test accuracy.
None.
> [HUDI-8746] Improve a test in TestHoodieMultipleBaseFileFormat

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/TestIncrementalQueryWithArchivedInstants.scala
The config was not set correctly.
Fixed a typo.
None.
> [HUDI-8762] Fix a typo in TestIncrementalQueryWithArchivedInstants

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/ttl/strategy/PartitionTTLStrategy.java
Fix incorrect parameter usage and modify comment style.
none
none
none
> [MINOR] Fix incorrect parameter usage when selecting partition for TTL

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
Looking up in partition stats index only for indexed cols. We take into account left and right side of expr and ensure we do lookup if its feasible if there is a mix of cols indexed and non-indexed. 
Lets walk through an example to understand this in detail
c1 = 619sdc or c2 = 100 and c3 = 200
Say this is the filter expression in the query issued and there is no partition predicate provided 
case 1:
when all 3 cols are indexed w/ col stats:
expected col stats lookup expression is
(((('c1_minValue <= 619sdc) AND ('c1_maxValue >= 619sdc)) OR (('c2_minValue <= 100) AND ('c2_maxValue >= 100))) AND (('c3_minValue <= 200) AND ('c3_maxValue >= 200)))
i.e. all 3 cols will be looked up.
case 2:
only c1 and c2 are indexed for filter "c1 = 619sdc or c2 = 100 and c3 = 200":
since left of AND exp is …
> [HUDI-8836] Looking up in partition stats index only for indexed cols

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieColumnStatsIndexUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
Unifying supported cols across col stats and partition stats index
Unifying supported cols across col stats and partition stats index
low
> [HUDI-8681] Unifying supported cols across col stats and partition stats index

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
it has same issue with [https://github.com/apache/hudi/pull/8849](url) in compaction.
this PR fix this.
Low
None
None
> [HUDI-6304] Handle cases when inflight compaction files are removed and job failed leaving pending rollback files

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
This test, "TestRecordLevelIndex#testRLIWithMDTCleaning", is marked "Would take a long time to run on regular basis".  The PR shortens the runtime and reenables it.
NA
low
NA
> [HUDI-8688] Revisit TestRecordLevelIndex#testRLIWithMDTCleaning

- hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
- hudi-common/src/main/java/org/apache/hudi/avro/processors/JsonFieldProcessor.java
Change exceptions type when converting json to avro
NA
None
None
> [HUDI-8279] Throw HoodieJsonToAvroConversionException when converting from json to avro

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/HoodieWriterClientTestHarness.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
fix up of HUDI-8804
fix up of HUDI-8804
none
none
> [MINOR] fix up of HUDI-8804

- website/docs/indexes.md
- website/versioned_docs/version-1.0.0/indexes.md
Updated details indexing configurations on indexing page
none
> [DOCS] Updated details indexing configurations on indexing page

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Removing default lock provider.
Removing default lock provider.
low
> [HUDI-8930] Removing default lock provider

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
- hudi-common/src/main/java/org/apache/hudi/client/transaction/lock/NoopLockProvider.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Fix typo and remove hardcoded classnames. Followup to #12737 
Minor code cleanup
none
> [MINOR] Fix typo and remove hardcoded classnames 

- .github/workflows/release_candidate_validation.yml
- release/release_guide.md
As above based on the latest master.
Be consistent with the latest release.
none
Fixes the link in release guide.
> [HUDI-8953] Update bundle validation workflow on a release candidate

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
Add warning about primary keys setting by two different ways
User-friendly message
None
None
> [HUDI-8278] Add log message about different primary keys for HoodieTableFactory

- hudi-spark-datasource/hudi-spark3.5.x/src/test/java/org/apache/hudi/internal/HoodieBulkInsertInternalWriterTestBase.java
- hudi-spark-datasource/hudi-spark3.5.x/src/test/java/org/apache/hudi/spark3/internal/TestHoodieBulkInsertDataInternalWriter.java
- hudi-spark-datasource/hudi-spark3.5.x/src/test/java/org/apache/hudi/spark3/internal/TestHoodieDataSourceInternalBatchWrite.java
Refactored some minor style related issues.
Better readability.
None.
> [MINOR] Fix code issues reported by code review tool

- website/docs/python-rust-quick-start-guide.md
- website/src/pages/ecosystem.md
- website/versioned_docs/version-0.15.0/python-rust-quick-start-guide.md
- website/versioned_docs/version-1.0.0/python-rust-quick-start-guide.md
Update python/rust quick start page to be in sync with hudi-rs readme. And fix daft hudi page links.
> [DOCS] Update python/rust page and links

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Enable record. index validation by default.
Broader validation scope.
Low.
> [HUDI-8958] Enable record index validation by default

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java
remove type cast to avoid compilation issue on jenkin's
remove type cast to avoid compilation issue on jenkin's
none
NA
- [ x] Read through [contributor's guide](https://hudi.apache.org/contribute/how-to-contribute)
- [ x] Change Logs and Impact were stated clearly
- [ x] Adequate tests were added if applicable
- [ x] CI passed
> [MINOR] Fix compilation issue

- doap_HUDI.rdf
Updating doap for release 1.0.1
Updating doap for release 1.0.1
low
> [MINOR] Updating doap for release 1.0.1

- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
The jira aims to add a test to ensure that Hive sync throws exception in case there is an error encountered during sync.
NA
low
NA
> [HUDI-8965] Add a test to ensure that hive sync tool throws exception upon sync failure

- azure-pipelines-20230430.yml
This PR rebalances Azure CI jobs as the longest job is approaching 2 hours while the shortest is below 1 hour.
Before:
After:
Reduces overall CI running time.
none
none
> [MINOR] Rebalance Azure CI jobs (2025-02-13)

- website/src/pages/roadmap.md
This PR updates Hudi Roadmap page based on the latest.
Improves visibility on future new features.
none
Website page update
> [DOCS] Update Hudi Roadmap page

- azure-pipelines-20230430.yml
As above.
Avoids timeouts for now before rebalancing CI.
none
N/A
> [MINOR] Increase timeout of hudi-utilities tests in Azure CI

- website/docs/sql_dml.md
- website/versioned_docs/version-1.0.1/sql_dml.md
Update new specifications on merge into queries.
better user visbility.
none
na
> [HUDI-9077][DOCS] Update MERGE INTO docs

- hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestDataSourceUtils.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieDataSourceHelper.scala
Disabling failing test to unblock master
Disabling failing test to unblock master
low
> [HUDI-9086] Disabling failing test to unblock master

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
add MIT tests
better coverage
none
none
> [HUDI-8826] Extend MIT partial update test

- website/docs/sql_queries.md
- website/versioned_docs/version-0.10.0/query_engine_setup.md
- website/versioned_docs/version-0.12.2/query_engine_setup.md
- website/versioned_docs/version-0.12.3/query_engine_setup.md
- website/versioned_docs/version-0.13.0/query_engine_setup.md
- website/versioned_docs/version-0.13.1/querying_data.md
- website/versioned_docs/version-0.14.0/sql_queries.md
- website/versioned_docs/version-0.14.1/sql_queries.md
- website/versioned_docs/version-0.15.0/sql_queries.md
- website/versioned_docs/version-1.0.0/sql_queries.md
- website/versioned_docs/version-1.0.1/sql_queries.md
Update invalid link for doris hudi catalog.
none
none
Update invalid link for doris hudi catalog.
> [Docs]Update invalid link to doris hudi catalog

- website/versioned_docs/version-1.0.1/hudi_stack.md
> [Fix](opt)fix the error words in hudi_stack.md

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
- hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/testutils/SparkDatasetTestUtils.java
1. pass compaction/merge related props to HoodieBaseFileGroupRecordBuffer
none
low
none …
> [HUDI-9125] Pass compaction/merge related props to HoodieBaseFileGroupRecordBuffer

- .github/workflows/bot.yml
- packaging/bundle-validation/validate.sh
Try fixing bundle validation on Flink 1.18.
Fixing bundle validation on Flink 1.18.
low
> [HUDI-7803] Fix bundle validation on Flink 1.18

- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
In the multi-writer test of interest, if the instant time for DC is after compaction instant times, during conflict resolution, the DC of interest may not consider compaction and might succeed. Eventually the compaction execution will fail, but the tests of interest is mainly asserting that DC of interest will fail due to conflicts w/ compaction instant. So, fixing the flakiness in this patch. 
Ran all 4 combinations for 50 times and did not see any failures w/ this fix. 
stable CI 
low
- _Any new feature or user-facing change requires updating the …
> [HUDI-9083] Fixing flakiness with multi writer test

- website/blog/2025-03-13-hudi-on-dbr.mdx
Rendering failed because of the incorrect image path. Fixing the right file extension with this PR
Docs change
Low
NA
> [DOCS] Fix image path for recent blog

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Spark Insert Overwrite Support Row Writer
Spark Insert Overwrite Support Row Writer
low
> [HUDI-9207] Spark Insert Overwrite Support Row Writer

- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Fix tests in TestHoodieBackedMetadata after new default indexes enabled and drop partition requires config.
None
none
> [HUDI-9221] Fix tests in TestHoodieBackedMetadata after new default indexes enabled

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
- Factor in source table version when determining which view of the table to use in HudiIncrSource
- Add test coverage for source tables in v6
- Currently reading a table written with version 6 will through a runtime exception 
`java.lang.RuntimeException: Incremental query view for timeline version 1 not yet implemented`
Low …
> [HUDI-9238] Fix bug with HudiIncrSource when source is table version 6

- pom.xml
Bump Spark 35 version to 3.5.5
none
low
none
> [HUDI-9240] Bump spark 35 version to 3.5.5

- website/blog/2025-03-31-amazon-hudi.md
fixes an image path for thumbnail
_None_
> Fix Image path for the Amazon Blog

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordMerger.java
Fix typo and Add implementation class name in interface method of HoodieRecordMerger
None
None
None
> [MINOR]Fix typo and Add implementation class name in interface method of HoodieRecordMerger

- website/blog/2021-12-16-lakehouse-concurrency-control-are-we-too-optimistic.mdx
- website/src/pages/talks.md
….mdx
Weekly update for blogs and title updates as per request
none
none
N/A
- [Y ] Read through [contributor's guide](https://hudi.apache.org/contribute/how-to-contribute)
- [ Y] Change Logs and Impact were stated clearly
- [ Y] Adequate tests were added if applicable
- [ Y] CI passed
> [Weekly Docs] Blog updates and title updates

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/PartitionBucketIndexManager.scala
As above
Fix CI on master
none
N/A
> [MINOR] Fix build error on master

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
Fixing master for build failure
Fixing master for build failure
low
> [MINOR] Fixing master for build failure

- website/docs/sql_dml.md
Partial update is disabled when global index is used.
Better visibility of the limitation of current partial update supports.
None.
> [HUDI-9260][Docs] Add one more limitation for partial update

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestMergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
Disable partial update for CUSTOM merge mode.
Avoid some confusion from custom side if they use  custom merge mode.
Medium.
> [HUDI-9258] Disable partial update for CUSTOM merge mode

- website/constants.js
Update slack invite link in site. Previous link is expired.
minor site change
none
> [MINOR][SITE] Update slack shared invite link

- README.md
Updating README with latest Slack link
Only impacts slack link.  
none
> [MINOR] Update readme with latest slack link

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v2/LSMTimelineWriter.java
In rare cases, there could be existing arching file which is either committed or not. Handle the 2 cases in this PR.
none
none
> [HUDI-9286] Fix the atomicity of archived timeline write

- rfc/rfc-93/rfc-93.md
> [MINOR] Fix typo in RFC-93

- hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/util/SpillableMapUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestHoodieRecordUtils.java
- Cache the payload constructors when using reflection
- Avoid reflection on the metadata table paths for up to 15x throughput improvements when creating the instances
Improves throughput
Low
> [HUDI-9314] Reduce overhead for payload creation

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
add log
Add logging for us to debug potential data skewness in this function.
none
none
> [HUDI-9272] add logs to filterKeysFromFile

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieHBaseAvroHFileReader.java
Disable native hfile reader due to leaf_index issue.
Avoid hfile read failure
None.
> [HUDI-8601] By default disable native hfile reader

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Fix delete for HoodieAvroRecord during appending log blocks
none
low
> [HUDI-9317] Fix delete for HoodieAvroRecord during appending log blocks

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieSimpleIndex.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTableRecordIndex.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Also eliminate the the `#put` in `TypedProperties` constructor.
none
none
> [HUDI-9323] Fix the improper usage of HoodieConfig

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriterTableVersionSix.java
- hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala
The metadata config build is unnecessary.
none
none
> [HUDI-9327] Remove the unnecessry HoodieMetadataConfig build

- website/docusaurus.config.js
- website/src/theme/Navbar/Content/index.js
Try using footer to host img trackers.
> [SITE] move tracking img to footer

- website/docusaurus.config.js
- website/src/pages/asf/telemetry.md
- website/src/pages/markdown-page.md
> [SITE] Add telemetry page and privacy link

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
Avoid to schedule compaction when insert mor table for flink
> [HUDI-9350] Avoid to schedule compaction when insert mor table for flink

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
Support displaying complete dag for merge into statement in spark web ui
- reuse the hoodie table resolved by analyzing `MatchMergeIntoTable` to create `HoodieCatalogTable`
- make `MergeIntoHoodieTableCommand` extends `DataWritingCommand`
- create `MergeIntoHoodieTableCommand` with empty input plan, `getProcessedInputPlan` to make the input plan, then replace it
None
None
None
> [HUDI-9354] Support displaying complete dag for merge into statement in spark web ui

- doap_HUDI.rdf
Update DOAP to include version `1.0.2`.
None
None
None
> [MINOR] Update DOAP with 1.0.2 Release

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBloomFiltersIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala
This PR fixes the timestamp stored in the bloom filter records in the expression index to use the data table instant time on which the expression index partition is initialized, to be consistent with the bloom filter index.  The timestamp in the bloom filter records is not used in the production code and it is aded for easier debugging only, so there is no impact on bloom filter based skipping.  New tests are added to validate the timestamp used in the bloom filter metadata records.
As above for consistency on storage
none
none
> [HUDI-9368] Use data table instant time for bloom filter records in expression index

- hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
- hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
- hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
- hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
- hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestHoodieDataHubDatasetIdentifier.java
Backport PR https://github.com/apache/hudi/pull/13133 to `branch-0.x`
Low
None
In later PRs
> [HUDI-9377] feat(datahub-sync): adds DataPlatformInstance aspect

- website/releases/download.md
Fixing minor typo in release page
Fixing minor typo in release page
none
> [MINOR] Fixing minor typo in release page

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/BootstrapRowData.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/RowDataUtils.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/HoodieRowDataParquetReader.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieFileGroupReaderOnFlink.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
* Add tests for Flink file group reader
* Minor fix for BootstrapRowData
Improve the test coverage.
low
> [HUDI-9378] Add tests for Flink file group reader

- azure-pipelines-20230430.yml
- Reverting ubuntu version override https://github.com/apache/hudi/pull/13124 
unblocking master.
Green master
> [MINOR] Reverting ubuntu version override

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
Fix upgrade action for Flink writer
Support upgrade action for Flink wrtier.
low
> [HUDI-9419] Fix upgrade action for Flink writer

- hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
- hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
Backport PR https://github.com/apache/hudi/pull/13318
Low
None
None
> [MINOR] fix(datahub-sync): fixes database path for dataset's browse path

- website/src/pages/roadmap.md
As above
Roadmap update
none
none
> [DOCS] Add index abstraction to roadmap

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
Improve Flink Clustering Performance Using Row Reader
Flink clustering on CoW table
low
> [HUDI-9437] Improve Flink Clustering Performance Using Row Reader

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderSchemaHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/util/collection/CloseableFilterIterator.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
- hudi-examples/hudi-examples-flink/src/test/java/org/apache/hudi/examples/quickstart/TestQuickstartData.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactOperator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/HoodieRowDataParquetReader.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/RecordIterators.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadTableState.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StringToRowDataConverter.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieFileGroupReaderOnFlink.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStringToRowDataConverter.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
Integrating FileGroup reader into Flink regular merging reader.
Improve performance of flink regular reader.
medium
> [HUDI-9146][part2] Integrating FileGroup reader into Flink merge reader

- website/versioned_docs/version-0.15.0/faq_storage.md
Added FAQ entry for HBase compatibility issue with HDFS on Hadoop 3.x.
Added the workaround steps to mitigate HBase compatibility issue with HDFS on Hadoop 3.x.
none
Updated FAQ documentation.
> [HUDI-9490] Update FAQ with Workarounds for HBase Compatibility Issues on Hadoop 3.x

- .asf.yaml
Allow @rangareddy to manage GH issues.
NA
none
None
> [MINOR] Add rangareddy to github collaborators

- .github/workflows/bot.yml
> [HUDI-9495][Minor][UT] Modify bot to unify Flink avro and parquet version based on pom

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java
Add a configurable feature of adding Flink checkpoint Id into Hudi commit metadata
low
low
> [HUDI-9491] add checkpoint id into hudi commit metadata

- hudi-common/src/main/java/org/apache/hudi/avro/AvroRecordSerializer.java
- hudi-common/src/main/java/org/apache/hudi/avro/AvroRecordSizeEstimator.java
- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/serialization/RecordSerializer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecord.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecordSerializer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/util/SerializationUtils.java
- hudi-common/src/test/java/org/apache/hudi/avro/TestAvroRecordSizeEstimator.java
- hudi-common/src/test/java/org/apache/hudi/avro/TestSizeEstimator.java
- hudi-common/src/test/java/org/apache/hudi/common/serialization/TestBufferedRecordSerializer.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
…lity of FileGroup reader
Reduce size of Avro IndexedRecord to decrease spilling probability of FIleGroup reader.
Solve potential perf regression for Avro FileGroup Reader.
medium.
> [HUDI-9499] Add customized SizeEstimator and Serializer for Avro buffered record in FileGroup reader

- hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java
Removed unused SparkConf import in HoodieSparkQuickstart
Project builds successfully without setting modules in mvn command
none
none
> [MINOR] Removed unused imports in HoodieSparkQuickstart

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieStatsIndexTestBase.scala
- Force timeline refresh in rollback testing
- Fix flakey test
None
> [MINOR] Flakey test in TestRecordLevelIndexTableVersionSix

- website/blog/2025-06-16-Apache-Hudi-does-XYZ-110.mdx
- website/contribute/developer-sync-call.md
- website/docusaurus.config.js
- website/sidebarsCommunity.js
- website/sidebarsContribute.js
> [SITE] Improve dev sync call page and other links

- hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/spark/HoodieWriteClientExample.java
Removed unused imports in HoodieWriteClientExample
Project builds successfully without setting modules in mvn commands
none
none
> [MINOR] Removed unused imports in HoodieWriteClientExample

- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
Adds log files whenever hoodie property file is created or deleted. Also logs the changes to backup file.
NA
low
NA
> [MINOR] Add logs for hoodie property file changes

- website/blog/2025-06-30-uber-hudi.md
Corrected an error in the newly published Uber blog.
NA
None
> [DOC ]Fix: Corrected error in the Uber blog

- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
As tiltle. 
More clarity on the meaning of the properties.
Low.
> [HUDI-8401] Fix the description of MERGE_PROPERTIES config

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToNineUpgradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/NineToEightDowngradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/CommonClientUtils.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieWriteClient.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestCommonClientUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/others/TestMergeModeCommitTimeOrdering.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/others/TestMergeModeEventTimeOrdering.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Upgrade current table version to be 9.
None.
Low.
> [HUDI-8401] Upgrade current table version to 9

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
fix broken test
fix broken test
none
none
> [MINOR] fix broken test

- pom.xml
Upgrades to latest version with java8 support for mockito and update to latest patch on junit.
We have been seeing bytebuddy related issues in the java module's tests occasionally, this is brought in by mockito and some users of mockito also see issues in older versions.
None
> [MINOR] Upgrade junit and mockito

- hudi-examples/hudi-examples-flink/src/main/java/org/apache/hudi/examples/quickstart/source/ContinuousFileSource.java
Removed unused imports in ContinuousFileSource (hudi-examples)
Project builds successfully without setting modules in mvn commands
none
none
> [MINOR] Removed unused imports in ContinuousFileSource (hudi-examples)

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HFileReaderFactory.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
- hudi-common/src/test/java/org/apache/hudi/io/storage/TestHFileReaderFactory.java
- hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieNativeAvroHFileReader.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroFileReaderFactory.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/io/hadoop/TestHoodieHFileReaderWriter.java
> [HUDI-9626] Prefetch HFiles for metadata table if size is below a configured threshold

- .asf.yaml
Allow [@deepakpanda](https://github.com/deepakpanda93) to manage GH issues.
NA
None
none
> [MINOR] Add deepakpanda to github collaborators

- website/contribute/developer-sync-call.md
Edit Developer Sync page to reflect changes
Site update
none
> [Docs][Site] Add website changes for Hudi Developer Sync

- website/blog/2025-04-02-secondary-index.md
Fix the query to create secondary index in the `secondary-index` blog.
None
None
> [DOCS] Update Query for Creating Secondary Index on Secondary Index Blog

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseWriteHelper.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkWriteHelper.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaWriteHelper.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecordMergerFactory.java
Set prefixed merge properties properly.
Set prefixed merge properties properly.
low
> [MINOR] Set prefixed merge properties properly

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
Improve log in `monitorDirAndForwardSplits` of [HUDI-8863]
none
low
none
> [HUDI-9768] Further Improve of HUDI-8863

- .asf.yaml
Set discussions target so it'll get enabled properly.
> [MINOR] Update discussions settings

- hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
- hudi-common/src/test/java/org/apache/hudi/BaseHoodieTableFileIndexTest.java
add a getter method to hoodie file index
none
none
none
> [MINOR] add getter method for metadataConfig

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Gracefully handling flaky test - Upgrade and Downgrade compatibility
Gracefully handling flaky test - Upgrade and Downgrade compatibility - No impact
none
none
> [HUDI-9794] File Avro Bytes Flakiness fix with graceful handling

- website/static/.htaccess
For https://issues.apache.org/jira/browse/INFRA-27242
> chore: update CSP setting to allow kapa.ai (INFRA-27242)

- rfc/rfc-87/rfc-87.md
> [HUDI-8934] [RFC-87] Avro elimination in Flink writer

- scripts/pr_compliance.py
As per discussion (https://github.com/apache/hudi/discussions/13877#discussioncomment-14378731), the GH issue link is no longer required for fix PRs.  This PR removes the validation of issue link on fix PRs to be consistent with the guideline.
This PR removes the validation of issue link on fix PRs in `scripts/pr_compliance.py`.
Avoid unnecessary check and failures in PR compliance.
none
N/A
> chore: Remove validation of issue link on fix PRs

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
With landed a patch to fix performance with streaming writes to metadata here https://github.com/apache/hudi/pull/13976/. We had a minor bug in calculating right value for `enforceCoalesceWithRepartition` for table services (specifically clustering). Fixing the condition check in this patch. 
Fixing computing right value for `enforceCoalesceWithRepartition` for clustering table service with streaming writes to metadata table. 
We already have test coverage for all combinations https://github.com/apache/hudi/blob/21b8075f64ebc7f870936803853cf291a97c463e/hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java#L245 and all tests are succeeding w/o this fix. 
So, based on that, the fix in this patch is not strictly required. but it aligns with the …
> fix: Fixing condition to calculate enforceCoalesceWithRepartition for table services with streaming writes to mdt

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
https://github.com/apache/hudi/issues/14028
The test `TestUpgradeDowngrade.testUpgradeOrDowngrade` could throw NPE randomly.
During the downgrade from eight to seven table version, 
`ArchivedTimelineLoaderV2.loadInstants` invokes multi threads to load timeline instants, and stores them into a in-memory list using `ArchiveEntryFlusher.accept` function.
However, there are two issues:
1. `ArchiveEntryFlusher.accept` is not thread-safe.
2. The in-memory list is not thread safe list. 
Therefore, in some race conditions, the elements of the list could be cleared by one thread, while another thread is still doing appending, which causes the NPE issue during flush.
Therefore, the fix is to make `ArchiveEntryFlusher.accept` and `ArchiveEntryFlusher.close` function thread safe.
Before the fix, test …
> fix: Flaky NPE during downgrade from Eight to Seven table version

- website/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph.mdx
change to make syntax highlighting work
> chore: update puppygraph blog code block

- website/src/components/HomepageHeader/index.js
- website/src/components/HomepageHeader/styles.module.css
This reverts commit bf1ed6e22a7d34e039c5b7569793522d1534922d.
Blocked due to csp
> Revert "chore(site): embed cmu hudi talk video (#14025)"
