- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
```java
org.apache.flink.runtime.rest.handler.RestHandlerException: The main method caused an error: java.util.NoSuchElementException: No value present in Option
at org.apache.hudi.common.util.Option.get(Option.java:89)
at org.apache.hudi.table.HoodieTableSource.buildFileIndex(HoodieTableSource.java:341)
at org.apache.hudi.table.HoodieTableSource.getBatchInputFormat(HoodieTableSource.java:381)
at org.apache.hudi.table.HoodieTableSource.getInputFormat(HoodieTableSource.java:366)
at org.apache.hudi.table.HoodieTableSource.getInputFormat(HoodieTableSource.java:361)
at org.apache.hudi.table.HoodieTableSource$1.produceDataStream(HoodieTableSource.java:198)
at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecTableSourceScan.translateToPlanInternal(CommonExecTableSourceScan.java:10 …
```
> [HUDI-6624]Fix to return a empty list when there is no commit instant to read

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/ArchivalUtils.java
Moving the min and max instants functionality to a static function to improve usability.
No impact, refactoring.
Low
> [HUDI-6595] Move min and max instants to a static function in HoodieTimelineArchiver

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/FlinkClusteringConfig.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
The failed writes clean policy should be lazy when write concurrency mode is optimistic concurrency control. `FlinkOptions` should support to config failed writes clean policy. The parameters of `FlinkStreamerConfig`, `FlinkCompactionConfig` and `FlinkClusteringConfig` should also support failed writes clean policy parameter. Meanwhile, append mode without inline clustering should add clean operator in pipeline to rollback failed writes.
`FlinkOptions`, `FlinkStreamerConfig`, `FlinkCompactionConfig` and `FlinkClusteringConfig` supports to config failed writes clean policy. Meanwhile, append mode without inline clustering adds clean operator in pipeline to rollback failed writes via lazy failed writes clean policy.
none.
none.
> [HUDI-6540] Support failed writes clean policy for Flink

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
When upgrade hudi from 0.12.2->0.13.1, I found spark's capcity of insert overwrite partitioned table with dynamic partition lost,
see https://github.com/apache/hudi/issues/8283#issuecomment-1482745990: 
It will cause serious data problems if upgrade to 0.13.1, user will delete all data by mistake
As https://github.com/apache/hudi/pull/7365#issuecomment-1338371540 mentioned, 
`insert_overwrite_table` will override entire table. while `insert_overwrite_partition` will overwrite only matching partitions.
Now we can only use static partition syntax to realize `insert_overwrite_partition` semantics.
1) Keep insert overwrite semantics  to be forward compatible(recover dynamic partition capcity) 
2) Realize `insert_overwrite_table` semantics  with partitioned table as …
> [HUDI-6466] Fix spark insert overwrite partitioned table with dynamic partition

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestConsistentBucketStreamWrite.java
Current `BulkInsertWriterHelper` is used for both insert and bulk_insert operation, for `isInputSorted` in `BulkInsertWriterHelper`, we should first judge whether is  bulk_insert operation, because only under bulk_insert, there is a sort operation. (Remove the current `is bounded` judgment, because no matter whether it is  bounded or a non-bounded insert, there is no sort)
above
low
none
> [HUDI-6615] Fix the condition of isInputSorted in BulkInsertWriterHelper

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestWriteClient.java
When source returns an empty option, the writer schema is null. This causes an NPE with the table schema validation in spark write client causing the below exception. Skipping the validation when writer schema is null.
```
org.apache.hudi.exception.HoodieInsertException: Failed insert schema compability check.
at org.apache.hudi.table.HoodieTable.validateInsertSchema(HoodieTable.java:851)
at org.apache.hudi.client.SparkRDDWriteClient.insert(SparkRDDWriteClient.java:185)
at org.apache.hudi.utilities.deltastreamer.DeltaSync.writeToSink(DeltaSync.java:690)
at org.apache.hudi.utilities.deltastreamer.DeltaSync.syncOnce(DeltaSync.java:396)
at org.apache.hudi.utilities.deltastreamer.HoodieDeltaStreamer$DeltaSyncService.ingestOnce(HoodieDeltaStreamer.java:876)
at …
```
> [HUDI-6627] Fix NPE when spark client writer schema is null

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTableWithNonRecordKeyField.scala
Prepped upsert is slower. Disable it by default until we fix the performance. However, for pk-less we need meta columns and prepped upsert, so an exception for pk-less.
Should help a little with performance for the prepped writes.
none
> [MINOR] Infer prepped boolean correctly and disable prepped write for MergeInto

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Whem using custom key generator with timestamp field with type `EPOCHMILLISECONDS` and output date format as `yyyy/MM/dd`, partition parsing fails because partition column is thought to be of LongType even though it is string. 
Another issue is that if there are multiple partition fields with cusotm keygen, then lazy listing fails due to parsing of partitions with non-encoded slashes. This PR fixes these issues. 
It also adds a test to check partition pruning kicks in for TimestampBasedKeyGenerator.
Fixes couple of bugs bug when using custom keygen with timestamp fields.
low
Eager listing in case of custom keygen with multiple fields can be costlier but functional. Before this patch, it wasn't even functional.
_Describe any necessary documentation update if there is any new feature, …
> [HUDI-6320] Fix partition parsing in Spark file index for custom keygen

- hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
This reverts commit 72f047715fe8f2ad9ff19a31728fbfb761fbe0d9. We observed performance regression especially when the query has no partition predicates. ~Even though there is one stage reduced but there are too many tasks doing `fs.exists` calls.~
The number of tasks look the same in attached screenshots in https://github.com/apache/hudi/pull/9343#discussion_r1283447863 but  there is a difference in what stages are executed.
Fix performance regression.
low …
> Revert "[HUDI-6476] Improve the performance of getAllPartitionPaths (#9121)"

- hudi-flink-datasource/hudi-flink/pom.xml
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/FlinkStreamReadMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/HoodieFlinkMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadOperator.java
- packaging/hudi-flink-bundle/pom.xml
Subtask for HUDI-2141, support flink read metrics
stream write metrics and compaction metrics see #9118 
add some metrics
none
Will update document after merge
> [HUDI-2141] Support flink read metrics

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestAutoGenerationOfRecordKeys.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
We are recently added auto record key generation support mainly to cater to append only use-cases. So, as part of the work stream, this is a follow up patch. This patch makes bulk_insert as the default operation type for append only use-cases. For regular pipelines, "upsert" will be the default operation. 
With this patch, users can now do the following w/ hudi. 
```
a. non-partitioned: df.write.format("hudi").option("hoodie.table.name","hudi_tbl").save(path) -> will use bulk_insert. 
b. partitioned dataset: df.write.partitionBy(colA).format("hudi").option("hoodie.table.name","hudi_tbl").save(path) -> will use bulk_insert. 
c. multi-field partitioning: df.write.partitionBy(colA, colB).format("hudi").option("hoodie.table.name","hudi_tbl").save(path)  -> will use bulk_insert. 
``` 
If any …
> [HUDI-5514] Improving usability/performance with out of box default for append only use-cases

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
Fixes #8892 where a failover when performing a `BucketStreamWrite`s to MOR tables will not perform rollbacks, causing multiple log files with the same bucketId to be created. 
This PR is co-authored by @danny0405.
Due to shuffling, partial failover is not support when BucketStreamWrite is being performed. Given that all executors will restart, a rollback should be performed.
None
None …
> [HUDI-6588] Fix duplicate fileId on TM failover and recovery

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
With Record level support in HUDI, the sql queries related to record keys can leverage the Record Index. The Jira aims to add support for equality matches with record keys.
This should help improve performance for some sql equalTo queries on record keys.
low
NA
> [HUDI-6606] Use record level index with SQL equality queries

- hudi-aws/pom.xml
- hudi-aws/src/main/java/org/apache/hudi/aws/cloudwatch/CloudWatchReporter.java
- hudi-aws/src/main/java/org/apache/hudi/aws/credentials/HoodieAWSCredentialsProviderFactory.java
- hudi-aws/src/main/java/org/apache/hudi/aws/credentials/HoodieConfigAWSCredentialsProvider.java
- hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
- hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
- hudi-aws/src/main/java/org/apache/hudi/aws/utils/DynamoTableUtils.java
- hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
- hudi-aws/src/test/java/org/apache/hudi/aws/TestHoodieAWSCredentialsProviderFactory.java
- hudi-aws/src/test/java/org/apache/hudi/aws/cloudwatch/TestCloudWatchReporter.java
- hudi-aws/src/test/java/org/apache/hudi/aws/transaction/integ/ITTestDynamoDBBasedLockProvider.java
- hudi-utilities/pom.xml
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelector.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/S3EventsMetaSelector.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelector.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestS3EventsMetaSelector.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/CloudObjectTestUtils.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractCloudObjectsSourceTestBase.java
- packaging/hudi-aws-bundle/pom.xml
- packaging/hudi-utilities-bundle/pom.xml
- pom.xml
Upgrade AWS Java SDK to v2.
None
None
None
> [HUDI-6638] Upgrade AWS Java SDK to V2

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AutoRowDataKeyGen.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/AutoRowDataKeyGen.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGens.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java
Support use auto key generator in flink append mode when user don't provide primary key to align with spark.
Add a new class AutoRowDataKeyGen to used in AppendWriteFunction to support pk-less case.
none
low
none
> [HUDI-6644] Flink append mode use auto key generator

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-common/src/main/avro/HoodieMetadata.avsc
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
- hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectWriterProvider.java
Enhancing RLI schema with MDT to support for different fileID formats. We can store UUID based format or any other format as well. 
RLI can support storing fileId of any formats. 
1. UUID based one which can be reconstructed using high order bits, low order bits and fileIndex. 
2. raw string format stored using field "fileId". 
Changes in schema:
1. we are adding a field called "fileIdEncoding" to denote the fileId format. default value of 0 represents UUID based fileID, while 1 represents raw string format. 
2. Added a field named "fileId" which could store raw fileID in string format. 
3. Fixed "partition" field naming to "partitionName"
4. Made all columns nullable. 
5. Added proper docs to every field in RLI
low.
N/A
> [HUDI-6607] Fixing RLI schema to support different fileID formats

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/CompactionAdminClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/HoodieFileProbingFunction.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/HoodieMetadataBloomFilterProbingFunction.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkUpsertDeltaCommitPartitioner.java
- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/model/BaseFile.java
- hudi-common/src/main/java/org/apache/hudi/common/model/CompactionOperation.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieBaseFile.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieLogFile.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieBaseFile.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieLogFile.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/WriteProfile.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeSplit.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeFileSplit.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- Updates sections of the code to use the getters in the HoodieBaseFile and HoodieLogFile instead of FSUtils to move away from relying directly on the path for getting metadata about the file when possible
- Sets file ID and commit time in HoodieBaseFile on construction and avoids running `split` on the file name twice to improve efficiency
- Sets fileId, baseCommitTime, logVersion, logWriteToken, fileExtension, suffix, and path when creating HoodieLogFile instead of making multiple calls to a regex based matcher to improve efficiency
- Uses CachingPath instead of Path in HoodieLogFile for improved efficiency
Lowers overhead when extracting metadata about HoodieBaseFiles or HoodieLogFiles
low, unit tests were added to assert behavior is maintained 
_Describe any necessary documentation …
> [HUDI-6628] Rely on methods in HoodieBaseFile and HoodieLogFile instead of FSUtils when possible

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordDelegate.java
- hudi-common/src/main/java/org/apache/hudi/common/util/HoodieCommonKryoRegistrar.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieRecordDelegate.java
make `HoodieRecordDelegate ` implement `KryoSerializable`
Improve serialize/deserialize performance.
NONE
NONE
> [HUDI-6617] make HoodieRecordDelegate implement KryoSerializable

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/overwrite/PartitionOverwriteMode.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Flink insert overwrite should support dynamic partition instead of the whole table, which behavior is consistent with the semantics of insert overwrite in Flink.
Flink insert overwrite only supports static and dynamic partition for partitioned table.
none.
none.
> [HUDI-6592] Flink insert overwrite should support dynamic partition and whole table

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCreateRecordUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestAutoGenerationOfRecordKeys.scala
Adding support for upsert and deletes with spark datasource for pk less table. 
This patch opens up possibility to do updates or delete records with spark datasource writes for a primary key less table. 
For eg, if for a primary table, user prefers to delete all records for a given employee. 
```
val df = spark.read.format("hudi").load(basePath).filter("emp_id == '100')
df.write.format("hudi").option("hoodie.datasource.write.operation","delete").mode(Append).save(basePath) 
```
This is feasible for a pk less table. 
low. …
> [HUDI-6579] Adding support for upsert and deletes with spark datasource for pk less table

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
getHoodieWriteClient was not thread safe so I override the method so it is and more than 1 client could be used
Tests no longer flakey
none
N/A
> [HUDI-6386] Fix flakey multiwriter tests

- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java
- hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestSyncUtilHelpers.java
This PR introduces a targeted synchronization mechanism based on the `targetBasePath` in the `runHoodieMetaSync` method. The previous class-level synchronization has been replaced with finer-grained locking, allowing concurrent processing for different base paths. Added a unti test to check two syncs can run concurrently if it's different base paths.
Meta sync wouldn't block for multi table deltastreamer.
low …
> [HUDI-6652] Implement basePath-level synchronization in runHoodieMetaSync

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Currently MOR snapshot relation does not use the column stats index for pruning the files in its queries. This PR aims to add support for pruning the file slices based on column stats in case of MOR.
The approach is similar to what was used for `org.apache.hudi.HoodieFileIndex#listFiles`. For every partition path, logic for filtering the file slices has been moved to function `org.apache.hudi.HoodieFileIndex#filterFileSlices`.  This function is called by various relations for pruning the file slices.
1. Firstly, as usual, partitions are pruned based on partition filters in `HoodieFileIndex#getFileSlicesForPrunedPartitions`.
2. Next, data filters are used to employ record index or colstats on top of pruned partitions and file slices in `HoodieFileIndex#filterFileSlices`.
a. If there is an …
> [HUDI-6649] Fix column stat based data filtering for MOR

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Currently Record Index based pruning is only supported for EqualTo queries on a record key. This Jira aims to add support for IN query as well.
SQL queries with IN predicate on record key will be faster.
low
NA
> [HUDI-6651] Support IN SQL query with Record Index

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
Simplify CreateHoodieTableCommand logWarning
#8251 Trying to output the call stack, but it just removes the `getMessage` call, toString and `getMessage` have the same effect, so it's not fixed.
#8996 Fixed it, but not as succinctly as we could have just used `warn(String msg, Throwable t)` to output a log.
> [MINOR] Simplify CreateHoodieTableCommand logWarning

- hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestHoodieRecordUtils.java
Currently when the user's specified class does not exists, then this silently fall back to the default merger. It can corrupt silently the data by applying wrong logic and should fail instead.
Fail when merge class not found, instead of using default merger that might corrupt the data.
low
> [HUDI-6400] Fail when merger class not found

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/util/ConsistentHashingUpdateStrategyUtils.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
Fix utility class for update strategy of table with consistent bucket index.
NA
NA
NA
> [HUDI-6655] Fix TestWriteMergeOnRead#testConsistentBucketIndex

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkConfUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSource.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadByStateTransitionTime.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamSourceReadByStateTransitionTime.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
- Rename `HollowCommitHandling#EXCEPTION` to `HollowCommitHandling#FAIL`
- Rename `HollowCommitHandling#USE_STATE_TRANSITION_TIME` to `HollowCommitHandling#USE_TRANSITION_TIME`
User config change (no actual impact as this is newly added to not-yet-released 0.14.0)
None.
NA
> [HUDI-6312] Rename enum values of `HollowCommitHandling`

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieBaseFile.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/dto/BaseFileDTO.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/dto/FilePathDTO.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ExternalFilePathUtil.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieBaseFile.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataPayload.java
This change allows us to support creating a table from a set of initial files that were not created by Hudi. This will allow us to bootstrap tables from an existing set of files instead of requiring users to rewrite tables with filenames in a format that Hudi expects (outside of the bootstrap feature)
This feature only works if metadata table is enabled.
This PR also contains some minor changes around unnecessary copying of arrays, use of LinkedList, and over use of Option when dealing with collections to reduce memory overhead.
This introduces more complexity when parsing a file status into a HoodieBaseFile but allows for more flexibility when initializing a Hudi table and unlocks ability to do a zero-copy-bootstrap of an existing set of files.
low
_Describe any necessary documentation …
> [HUDI-6648] Support building table views from existing files

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTableWithNonRecordKeyField.scala
Currently merge into fails when primary key is a complex key and join conditions do not include all the primary key columns. The Jira aims to restrict the constraint only when optimized writes are enabled. With the optimized writes disabled, merge into doesn't update the records if the primary key does not match completely.
NA
low
NA
> [HUDI-6660]  For merge into use primary key constraint when optimized writes are enabled

- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
Disabling a flaky or long running tests with Incremental sync. HUDI-6666 has more details. 
Disabling a flaky or long running tests with Incremental sync. HUDI-6666 has more details. 
low
> [HUDI-6666] Disabling a flaky or long running tests

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTableWithNonRecordKeyField.scala
Allow merge into join condition to use any column instead of just pk and partition columns
More flexible MIT
none
N/A
> [HUDI-6662] Relax matching condition to allow non pk columns to match on

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIdentifier.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/ConsistentHashingBucketInsertPartitioner.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/index/bucket/TestConsistentBucketIdIdentifier.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkConsistentBucketClusteringExecutionStrategy.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/ConsistentBucketIndexBulkInsertPartitionerWithRows.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDConsistentBucketBulkInsertPartitioner.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RowRecordKeyExtractor.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/factory/HoodieSparkKeyGeneratorFactory.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BulkInsertDataInternalWriterHelper.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/ConsistentBucketBulkInsertDataInternalWriterHelper.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieBulkInsertDataInternalWriter.java
- hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/HoodieBulkInsertDataInternalWriter.java
Support consistent hashing row writer for bulk_insert load and clustering. 
Support consistent hashing bulk_insert row writer 
medium, will enabled by default since row writer is enabled by default
will update document after landing
> [HUDI-6534]Support consistent hashing row writer

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Currently Hudi will clear table path if there is any exception in CTAS command:
https://github.com/apache/hudi/blob/7102e0fbe5ff352e5cbb123c3c25b1e5cd238d78/hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala#L117-L121
It may mistakenly delete the path belongs to another hudi table, we need a check before the clear.
CTAS will not clear the table path which is not generated by it any more.
low
- _Any new feature or user-facing change requires updating the Hudi website. Please create a Jira ticket, attach …
> [HUDI-6668] CTAS should not clear existing hoodie table path

- hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
- hudi-common/src/main/java/org/apache/hudi/exception/HoodieTimeTravelException.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestTimeTravelQuery.scala
Fail time-travel query when the given timestamp covers any incomplete commit.
Time travel query behavior. Time travel usually won't cover incomplete commit, which mostly exists within recent time frame.
Low
NA
> [HUDI-6587] Check incomplete commit for time travel query

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
This PR fixes initialization of metadata table partitions upon failure:
- In `BaseHoodieTableServiceClient.rollbackFailedWrites`, the fix avoids bootstrap rollback logic for MDT as MDT is never a bootstrap table and such logic can be accidentally triggered, since the MDT initial commits, e.g., `00000000000000010`, `00000000000000011`, are smaller than `FULL_BOOTSTRAP_INSTANT_TS` (`00000000000002`).
- In `HoodieBackedTableMetadataWriter.initializeIfNeeded`, when async metadata indexing is disabled, if a partition is inflight, it means that the partition is not fully initialized, so the initialization should be triggered again.
A new test is added based on the following scenario.  Before the fix, the test fails.
This scenario fails before the fix: When both files and record_index partitions …
> [HUDI-6679] Fix initialization of metadata table partitions upon failure

- azure-pipelines-20230430.yml
UT FT other modules consistenly taking more than 3 hours. HUDI-6682 to track better redistribution of tests.
none
none
> [MINOR] Increase CI timeout for UT FT other modules to 4 hours

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
Fixing the log statement to fetch column value by name instead of index. We found spark sometimes infers the cumulative column as double and hence results in class cast exception. 
low
low
> [HUDI-6680] - Fixing the info log to fetch column value by name instead of index

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR fixes the timeline check in metadata table validator.
Metadata table validator (`HoodieMetadataTableValidator`) throws the following exception before this fix when there is a completed rollback and no completed commits in the data table, and there is no completed instant in the MDT.  In this case, both the data table and MDT are empty, but the timeline check has a bug causing the validation to fail, which is a false positive.
```
23/08/08 22:48:13 WARN HoodieMetadataTableValidator: Metadata table is not available to read for now, 
org.apache.hudi.exception.HoodieValidationException: There is no completed instant for metadata table.
at org.apache.hudi.utilities.HoodieMetadataTableValidator.checkMetadataTableIsAvailable(HoodieMetadataTableValidator.java:500)
at …
```
> [HUDI-6670] Fix timeline check in metadata table validator

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/NewHoodieParquetFileFormatUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionFileSliceMapping.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
Remove the broadcast when sending the file slices.
1 TB tpcds bootstrap queries 1-14 performance gap between new file format and fast bootstrap went from 2.23x to 1.01x. Similar performance gains expected for MOR table where many file slices have log files
low
N/A
> [HUDI-6663] New Parquet File Format remove broadcast to fix performance issue for complex file slices

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-common/pom.xml
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
[HUDI-6553] Speedup column stats and bloom index creation on large datasets.
When creating records for the column stats and bloom filter partitions:
1. Create list of tuples of (partitionName, fileName, isDeleted)
2. Parallelize the above list so all files are handled in parallel
Another benefit of the above approach is that creation of deletion and append records and handled in the same code which reduces code duplication. 
In a test on large dataset (5K partition, 1.3Million files) the index initialization time was reduced as follows:
Column Stats Index: 
Before change: 21mins
After change: ~5mins
Bloom Filter Index:
Before change: 25mins
After change: ~10mins
None
None
> [HUDI-6553] Speedup column stats and bloom index creation on large datasets.

- website/docs/file_layouts.md
- website/docs/indexing.md
- website/src/theme/DocPage/index.js
Update indexing page and file layout page
Docs changes
Low
> [DOCS] Update Indexing page with all index types and file layout page

- hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/TimelineCommand.java
This PR adds the rollback information from the metadata table to the output of the timeline commands in Hudi CLI, given that metadata data table also encounters more rollbacks now.  To make the table concise, the rollback information is added to the "Action" (for data table) or "MT Action" (for metadata table) column, instead of having an independent column showing the information.
Here's the new output:
```
hudi:hoodie_table->timeline show active --limit 200 --show-time-seconds --show-rollback-info
╔═════╤═══════════════════╤═══════════════════╤═══════════╤════════════════╤════════════════╤════════════════╗
║ No. │ Instant           │ Action            │ State     │ Requested      │ Inflight       │ Completed      ║
║     │                   │                   │           │ Time …
```
> [HUDI-6674] Add rollback info from metadata table in timeline commands

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
Clean action. 
Avoid to clean the whole table data on hdfs .
Clean action. 
When it is a non-partition table,  Clean action will input the `""`  as partition path , this will lead to Cleaner   to clean the whole table data on the  hdfs . path format is `table_basepath  + "/" + ""`
so, when path is `""`, it means this clean action should not delete  dir, just skip it;
low …
> [HUDI-6675] Fix Clean action will delete the whole table

- website/docs/quick-start-guide.md
- website/versioned_docs/version-0.12.0/quick-start-guide.md
- website/versioned_docs/version-0.12.1/quick-start-guide.md
- website/versioned_docs/version-0.12.2/quick-start-guide.md
- website/versioned_docs/version-0.12.3/quick-start-guide.md
- website/versioned_docs/version-0.13.0/quick-start-guide.md
- website/versioned_docs/version-0.13.1/quick-start-guide.md
Fix code typo in pyspark 'Insert Overwrite' section of Quick Start Guide.
Fix code typo in pyspark 'Insert Overwrite' section of Quick Start Guide.
Minor fix to code example.
Low
Fix code typo in pyspark 'Insert Overwrite' section of Quick Start Guide.
> [HUDI-6685] Fix code typo in pyspark 'Insert Overwrite' section of Quick Start Guide.

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
Table created by Spark may not have the preCombine field set up.
none
none
> [MINOR] Infer the preCombine field only if the value is not null

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
This PR fixes the log file CLI commands when the log file contains command blocks like rollback commands.  The PR also adds the "File Path" column to the output for `show logfile metadata` CLI so it's easier to see the corresponding file path.
The tests are adjusted to consider such a scenario.  Without the fix, the new tests fail with NPE.
Before the fix, when there are rollback command blocks in the log files, the log file command throws NPE:
```
hudi:hoodie_table->show logfile metadata --logFilePathPattern file:<base_path>/.1414abd2-346b-4c84-b380-c6ea6ec0863a-0_20230813220941456.log*
at java.util.Objects.requireNonNull(Objects.java:203)
at org.apache.hudi.cli.commands.HoodieLogFileCommand.showLogFileCommits(HoodieLogFileCommand.java:102)
at …
```
> [HUDI-6694] Fix log file CLI around command blocks

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR adds the validation of record index in MDT validator (`HoodieMetadataTableValidator`).  The following validation modes are added:
- Record index count validation (with CLI config `--validate-record-index-count`): validate the number of entries in the record index, which should be equal to the number of record keys in the latest snapshot of the table.
- Record index content validation (with CLI config `--validate-record-index-content`): validate the content of the record index so that each record key should have the correct location, and there is no additional or missing entry.  Two more configs are added for this mode: (1) `--num-record-index-error-samples`: number of error samples to show for record index validation when there are mismatches, (2) `--record-index-parallelism`: …
> [HUDI-6689] Add record index validation in MDT validator

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestIncrSourceHelper.java
Handling empty commit and returning current batch's endpoint to handle scenarios of customer configuring filters for specific objects in s3 among other objects.
Medium
Medium
> [HUDI-6686] - Handling empty commits after s3 applyFilter api

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR fixes the partition validation to only consider commits in the metadata table validator (`HoodieMetadataTableValidator`) to avoid false positives.
The partition validation considers all instants including rollbacks before this fix.  The completed rollback in the data table's timeline interferes with the partition validation in the metadata table validator. Only commits should be considered in the validation. See the following example.
Timeline of DT and MDT:
```
╔═════╤═══════════════════╤═════════════╤═══════════╤═══════════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═══════════╤═════════════╤═════════════╤═════════════╗
║ No. │ Instant           │ Action      │ State     │ Rollback Info     │ Requested   │ Inflight    │ Completed   │ MT          │ MT …
```
> [HUDI-6688] Fix partition validation to only consider commits in metadata table validator

- hudi-common/pom.xml
- hudi-common/src/main/java/org/apache/hudi/common/util/collection/Tuple3.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ColumnStatsIndices.java
`HoodieTableMetadataUtil` uses `scala.Tuple3` and adds the scala library dependencies for `Tuple3` at present. It should introduce `Tuple3` for `HoodieTableMetadataUtil` instead of scala library dependencies.
Introduces `Tuple3` for `HoodieTableMetadataUtil`.
none.
none.
> [HUDI-6553][FOLLOW-UP] Introduces Tuple3 for HoodieTableMetadataUtil

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/AvroConvertor.java
This PR update the variable `record` name to `recordValue` to make the code more readable, and replace the cast to string and the usage of `String.valueOf` by `toString`.
related: #9403
_Describe any public API or user-facing feature change or any performance impact: NA
_If medium or high, explain what verification was done to mitigate the risks: None
_Describe any necessary documentation update if there is any new feature, config, or user-facing change: None
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setup#webs …
> [MINOR] Rename kafka record value variable in JsonKafkaSource and replace casting to String by calling toStrin

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
Adjust the filter way when findind the earliest scheduled compaction/clustering instant for execution.
If spark offline compaction execution fails, both a.compaction.requested and a.compaction.inflight states exist at the same time in the timeline, which will cause the next  offline compaction never to rolledback for compaction plan a.compaction.requested. Spark offline clustering is the same as compaction.
low …
> [HUDI-6359] Spark offline compaction/clustering will never rollback when both requested and inflight states exist

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
* Only initialize the metadata writer when it is enabled
* Remove the unnecessary check for action type, the code in write client & sercive client are totally the same.
none
none
> [HUDI-6704] Fix Flink metadata table update

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
Fix test failure caused by unnecessary quotes around query type value.
```
Caused by: org.apache.hudi.exception.HoodieException: Invalid query type : "snapshot" for tableType: COPY_ON_WRITE,isBootstrappedTable: false 
```
Fix test only.
None.
NA
> [MINOR] Fix sql core flow test

- hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
As disscussed in #9343, the original HUDI-6476 has latency for partitioned table. We find the latency occurs in `fileSystem.isDirectory(p)` which can be avoid. 
Here is my test on HDFS with `show partitions` command.
After Revert:
After this patch:
Fix the latency.
low
> [HUDI-6476][FOLLOW-UP] Path filter by FileStatus to avoid additional fs request

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
`StreamerUtil#getTableConfig` only checks whether .hoodie exists at present. Because `HoodieTableSink#getSinkRuntimeProvider` would create `.hoodie/.aux/ids` directory for auto client id. Therefore `StreamerUtil#getTableConfig` should check whether hoodie.properties exists, then get table config via `hoodie.properties`.
`StreamerUtil#getTableConfig` checks whether hoodie.properties exists when getting table config.
none.
none.
> [MINOR] StreamerUtil#getTableConfig should check whether hoodie.properties exists

- website/versioned_docs/version-0.10.1/table_management.md
fix the use of spark parameters in website documents
fix the use of spark parameters in website documents
none
> fix the use of spark parameters in website documents

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
Adds support for syncing the base files of an MoR table to BigQuery so users to can query the table in a "Read Optimized" way like they can do with other query engines.
Allows users to query base files of MoR tables from BigQuery.
None
> [HUDI-6731] BigQuerySyncTool: add flag to allow for read optimized sync for MoR tables

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestGetPartitionValuesFromPath.scala
When we enable `hoodie.datasource.read.extract.partition.values.from.path` to get partition values from path instead of data file, the exception throw if partition column is not string type. 
This patch fix the issue by cast partition value string to target datatype, following Spark's approach.
```bash
Caused by: java.lang.ClassCastException: org.apache.spark.unsafe.types.UTF8String cannot be cast to java.lang.Integer
at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getInt(rows.scala:41)
at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getInt$(rows.scala:41)
at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getInt(rows.scala:195)
at …
```
> [HUDI-6729] Fix get partition values from path for non-string type partition column

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudStoreIngestionConfig.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelectorCommon.java
CloudObjectsSelectorCommon adds config `SPARK_DATASOURCE_READER_COMMA_SEPARATED_PATH_FORMAT` for comma separated path . 
For file formats like xml does not support array of strings in spark.read.load() .  
comma separated path formats are supported for loading data from more than 1 file . 
So this pr adds support for  comma separated path
low …
> [HUDI-6549] Adding support for comma separated path format for spark.read.load

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudDataFetcher.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelectorCommon.java
- hudi-utilities/src/test/resources/schema/sample_data_schema.avsc
- hudi-utilities/src/test/resources/schema/sample_gcs_data.avsc
CloudObjectsSelectorCommon now takes optional schemaProvider . 
Spark datasource read will use schemaProvider schema instead of inferred schema if schemaProvider is there . 
low 
> [HUDI-4115] Adding support for schema while loading spark dataset in s3/gcs source

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SupportsUpgradeDowngrade.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/upgrade/FlinkUpgradeDowngradeHelper.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/upgrade/JavaUpgradeDowngradeHelper.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/upgrade/SparkUpgradeDowngradeHelper.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSixToFiveDowngradeHandler.scala
Since the log block version (due to delete block change) has been upgraded in 0.14.0, the delete blocks can not be read in 0.13.0 or earlier.
Similarly the addition of record level index field in metadata table leads to column drop error on downgrade. The Jira aims to fix the downgrade handler to trigger compaction and delete metadata table if user wishes to downgrade from version six (0.14.0) to version 5 (0.13.0).
NA
low
NA
> [HUDI-6621] Fix downgrade handler for 0.14.0

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
If two cleans start at nearly the same time, they will both attempt to execute the same clean instances. This does not cause any data corruption, but will cause a writer to fail when they attempt to create the commit in the timeline. This is because the commit will have already been written by the first writer. Now, we check the timeline before transitioning state.
No writers will fail in this scenario now
low
N/A
> [HUDI-6718] Check Timeline Before Transitioning Inflight Clean in Multiwriter Scenario

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SnapshotLoadQuerySplitter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryInfo.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSnapshotQuerySplitterImpl.java
Snapshot load scan of historical table ( having majority of data in archived timeline ) causes large batch processing . 
Adding interface to support breaking snapshotload query into batches which can have commitId as checkpoint . 
Adding SnapshotLoadQuerySplitter interface and integrating that with HudiIncrSource for snapshotLoad . 
low  …
> [HUDI-6735] Adding support for snapshotLoadQuerySplitter for incremental sources.

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/hive/TestHoodieCombineHiveInputFormat.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieMergeOnReadSnapshotReader.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
- Set some serde configs to avoid NPE in TestMergeOnReadSnapshotRecordReader.
- Close filesytem properly in the remaining tests.
CI flakiness
low
> [HUDI-6754] Fix record reader tests in hudi-hadoop-mr

- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestDataSkippingWithMORColstats.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestMORColstats.java
Create tests for MOR col stats index to ensure that filegroups are read as expected
Verification that the feature works
none
N/A
> [HUDI-6681] Ensure MOR Column Stats Index skips reading filegroups correctly

- hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/hudi/command/Spark30AlterTableCommand.scala
- hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/hudi/command/Spark31AlterTableCommand.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterTableCommand.scala
Add `operationType` in alter table commit metadata
before,  xxx.commit
```json
{
"partitionToWriteStats" : { },
"compacted" : false,
"extraMetadata" : {
"schema" : "xxx",
"latest_schema" : "xxx"
},
"operationType" : null
}
```
after, xxx.commit
```json
{
"partitionToWriteStats" : { },
"compacted" : false,
"extraMetadata" : {
"schema" : "xxx",
"latest_schema" : "xxx"
},
"operationType" : "ALTER_SCHEMA"
}
```
Above
none
none
> [MINOR] Add operationType in alter table commit metadata

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Add detail exception when instant transition state
```java
2023-08-18 10:40:53.643 ERROR [pool-21-thread-1:1-thread-1] org.apache.hudi.sink.StreamWriteOperatorCoordinator - Executor executes action [handle end input event for instant 20230818104027208] error
java.lang.IllegalArgumentException: null
at org.apache.hudi.common.util.ValidationUtils.checkArgument(ValidationUtils.java:31)
at org.apache.hudi.common.table.timeline.HoodieActiveTimeline.transitionState(HoodieActiveTimeline.java:577)
at org.apache.hudi.common.table.timeline.HoodieActiveTimeline.transitionState(HoodieActiveTimeline.java:558)
at 
```
> Add detail exception when instant transition state

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddPartitionCommand.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableAddPartition.scala
Hoodie does not support 'add partition' sql now, so we can not get partitions added by 'add partition' command.
In this patch, we implement add partition in Hoodie side:
1. add new command `AlterHoodieTableAddPartitionCommand`
2. add new unit test `TestAlterTableAddPartition`
No
Low
> [HUDI-6671] Support 'alter table add partition' sql

- website/docs/quick-start-guide.md
Add Hudi 0.13.x to the Spark 3 support matrix doc https://hudi.apache.org/docs/quick-start-guide/
https://issues.apache.org/jira/browse/HUDI-6740
Doc only change
low
This is documentation only update
> [HUDI-6740] Add 0.13.x to Spark 3 support matrix doc

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
With Hudi's OCC, one of the commit is expected to fail if there are overalapping writes. From a user's standpoint, very likely user may retry the failed write w/o any additional action. So, adding a retry functionality to spark datasource writes with hudi automatically incase of conflict failures. 
User experience w/ multi-writers will be improved with these automatic retries. 
medium
Users should enable the retries w/ caution since it could keep retrying the failed commit again until max retries are exhausted. Could result in some compute cost for large batches. 
- Configs introduced 
- `hoodie.write.num.retries.on.conflict.failures` : max number of times to retry on conflict failures. Default is 0 i.e. no retry.
> [HUDI-4631] Adding retries to spark datasource writes on conflict failures:

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java
- hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
- hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/util/queue/SimpleExecutor.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroHFileReader.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHFileRecordReader.java
During our long running tests, we found a few conn leaks causing S3 or GCS conn timeouts and job failures. This PR fixes most of them that were related to metadata and RLI.
Only changes internal classes to ensure readers are closed properly.
medium
> [HUDI-6726] Fix connection leaks related to file reader and iterator close

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/ExpressionPredicates.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/RecordIterators.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestExpressionPredicates.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
- hudi-flink-datasource/hudi-flink1.13.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.13.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
- hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
- hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
- hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
- hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
- hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
`HoodieTableSource` supports the implementation of `SupportsFilterPushDown` interface that pushes down the `CallExpression` filter into `FileIndex`. `HoodieTableSource` should support parquet predicate push down to improve query performance, which evaluates `FilterPredicate` from `CallExpression` to push down `FilterPredicate` to `ParquetColumnarRowSplitReader`.
The impact is mainly query performance via parquet predicate push down.
low.
ticket number here …
> [HUDI-6066] HoodieTableSource supports parquet predicate push down

- hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
Support table name for meta sync in bootstrap.
Using bootstrap procedure to migrate an existing table into a Hudi table.
```
call run_bootstrap(
table=> "test_db.test_hudi_table",
table_type=>"COPY_ON_WRITE",
bootstrap_path=>"XXX",
base_path=>"XXX",
rowKey_field=>"device_id",
partition_path_field=>"p_date,product",
key_generator_class=>"org.apache.hudi.keygen.ComplexKeyGenerator",
enable_hive_sync=>true,
options => 'hoodie.datasource.hive_sync.mode=hms'
);
```
After sync to HMS, I get a hudi table which stored as `test_db. unknown ` instead of `test_db.test_hudi_table` in HMS. 
The root cause is not set table configure 'META_SYNC_TABLE_NAME' before start hive sync.
The pr aims to fix this bug.
NA
NA
NA
> [HUDI-6813] Support table name for meta sync in bootstrap

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataRecordIndex.scala
Fix ut due to the scala compile ambiguity of Properties#putAl
none
> [MINOR] Fix ut due to the scala compile ambiguity of Properties#putAll method

- hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
When table/database is not found when syncing table to Glue, glue should return `EntityNotFoundException`.
After upgrading to AWS SDK V2, Hudi uses `GlueAsyncClient` to get a `CompletableFuture`, which would throw `ExecutionException` with `EntityNotFoundException` nested when table/database doesn't exist. However, existing Hudi code doesn't handle `ExecutionException` and would fail the job.
Sample exception:
```
org.apache.hudi.exception.HoodieMetaSyncException: Could not sync using the meta sync class org.apache.hudi.aws.sync.AwsGlueCatalogSyncTool
at org.apache.hudi.sync.common.util.SyncUtilHelpers.runHoodieMetaSync(SyncUtilHelpers.java:81)
at org.apache.hudi.HoodieSparkSqlWriter$.$anonfun$metaSync$2(HoodieSparkSqlWriter.scala:959)
at …
```
> [MINOR] Catch EntityNotFoundException correctly

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
The same action type(commit) is used after the completion of mor-compaction and cow-commit. If skipcompaction is configured, it will cause the stream read to skip the normal commit when reading the cow table. SkipCompaction Config should not affect the stream read of the cow table .
ticket number …
> [HUDI-6808] SkipCompaction Config should not affect the stream read of the cow table

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java
If clustering failed, it's not printing the detailed error reason. For example, in #9094, the error message contains the list of failed files but doesn't contain the reason or stacktrace why it failed to write the files.
The exceptions are once stored to `failedRecords` by `WriteStatus#markFailure` method, but they are never accessed or logged. After this change, the exceptions will be printed in the log.
JIRA: HUDI-6805
Very little impact.
Low.
No documentation changes required.
> [HUDI-6805] Print detailed error message in clustering

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/CompletionTimeQueryView.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
Add a tool to query completion time efficiently on both active & archived timeline.
none
none
> [HUDI-6725] Support efficient completion time queries on the timeline

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/SchemaEvolutionContext.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
Current hive read schema evolution MOR table will error, e.g. :
```sql
-- spark-sql
set hoodie.schema.on.read.enable=true;
create table if not exists hudi_mor_test_tbl (
id   bigint,
name string,
num  int,
ts   bigint,
ds   string
) using hudi 
type = 'mor',
preCombineField = 'ts'
)
partitioned by (ds);
insert into hudi_mor_test_tbl partition(ds = '20211211') select 1, 'a1', 1000,100;
update hudi_mor_test_tbl set name = 'a2' where id = 1;
alter table hudi_mor_test_tbl rename column name to name_new; 
-- hive
select id,name_new from hudi_mor_test_tbl_rt;
Failed with exception java.io.IOException:java.lang.ArrayIndexOutOfBoundsException: 25
```
Fix above
low
None
> [HUDI-6804] Fix hive read schema evolution MOR table

- hudi-common/src/main/java/org/apache/hudi/common/model/debezium/MySqlDebeziumAvroPayload.java
- hudi-common/src/test/java/org/apache/hudi/common/model/debezium/TestMySqlDebeziumAvroPayload.java
In our end-to-end testing, found some mysql debezium records are ignored by Deltastreamer and we lose these updates in hudi tables. e.g. 
```
Existing record in hudi table has _event_seq "00000.23"
For the same record, new update comes with  _event_seq "00000.123" (same binlog file, higher position)
```
However, current implementation ignores the update "00000.123" since it is using string comparison. This PR fixes the issue by comparing binlog file number and position within binlog file for the record separately. 
Unit test added which fails without the fix included in this PR.
Fixes the data loss issue for mysql debezium
low
- _The config description must be updated if new configs …
> [HUDI-6766] Fixing mysql debezium data loss 

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/InstantRange.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
1. Disabling entire MDT after enabling needs some fixes. 
2. We do have some special instants times like initialization instant times, compaction, clean etc in MDT timeline. During InstantRange check, these should be considered as valid. 
1. allows users to disable metadata using write configs cleanly. 
2. Valid instants consideration while reading from MDT is solid now. We are going to treat any special instant time (that has additional suffix compared to DT's commit time) as valid. 
Especially with MDT partition initialization, the suffix is dynamic, and so we can't really find exact match. So, might have to go with total instant time length and treat all special instant times as valid ones. 
In the LogRecordReader, we will first ignore any uncommitted instants. And then if its …
> [HUDI-6397][HUDI-6759] Fixing misc bugs w/ metadata table

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
The core change is to
1. Use HoodieRecord data type for general process;
2. Support HoodieSparkRecord when extract field value from records;
Make column metadata stats index is available for Spark.
Low since we did not change the original support for Avro records.
> [HUDI-5249] Support column metadata stats index for Spark

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCleaner.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/ArchiveTask.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/CleanTask.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/ClusteringTask.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/CompactionTask.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/HoodieMultiTableServicesMain.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/MultiTableServiceUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/TableServicePipeline.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/TableServiceTask.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/multitable/TestHoodieMultiTableServicesMain.java
Origin Issue: https://github.com/apache/hudi/issues/8960
Now we have HoodieMultiTableDeltaStreamer using spark to ingest multi tables into hudi, and we can also ingest multi tables using a single flink in some platforms like alicloud vvp. In such scenario we may want to run all tables services outside of the ingestion job to improve stability.
Currently, hudi provides a bunch of offline table service jobs but we still need to run them manually or through some schedule tools. This Pr provides a tool to run all table services in a single spark job
provides a tool to run all table services in a single spark job
none
Will update document after merge
> [HUDI-6481] Support run multi tables services in a single spark job

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java
- hudi-common/src/main/avro/HoodieRollbackMetadata.avsc
- hudi-common/src/main/java/org/apache/hudi/common/HoodieRollbackStat.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
The Jira aims to add field for tracking log files from failed commit in the rollback metadata. The fix for using this field would be tracked in [HUDI-6758](https://issues.apache.org/jira/browse/HUDI-6758).
NA
low
NA
> [HUDI-6833] Add field for tracking log files from failed commit in rollback metadata

- pom.xml
There are 1 security vulnerabilities found in org.apache.pulsar:pulsar-client 2.8.1
- [CVE-2022-33684](https://www.oscs1024.com/hd/CVE-2022-33684)
Upgrade org.apache.pulsar:pulsar-client from 2.8.1 to 2.10.2 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> [HUDI-6845] Upgrade org.apache.pulsar:pulsar-client to 2.10.2

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
This pr adds project id to the query statement: changing "create external table dataset.table" to "create external table project.dataset.table"
Fix the bug where project id is missing.
None
> [HUDI-6831] Add back missing project_id to query statement in BigQuerySyncTool

- hudi-gcp/pom.xml
- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySchemaResolver.java
- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
- hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySchemaResolver.java
- hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncTool.java
- hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
- hudi-sync/hudi-adb-sync/src/main/java/org/apache/hudi/sync/adb/AdbSyncConfig.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
- hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestManifestFileWriter.java
Adds schema evolution support to the BigQuerySyncTool by converting the Hudi schema into the BigQuery Schema format when creating and updating the table. 
Ensures users can properly query their tables even after updating the schema of the tables.
Low, this only impacts users of the new manifest-style table in BigQuery
> [HUDI-6728] Update BigQuery manifest sync to support schema evolution

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/GcsObjectMetadataFetcher.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
Recent refactoring to support batching within commit for GCS incr job moved the filtering of  objects after the checkpoint batching. The issue with this on bootstrap scenarios where we are looking for only latest commits, we will have to go through the entire set of commits based on sourcelimit instead of directly skipping to the latest commit. 
Fix is to apply filtering before we start checkpoint batching. This change list will bring GCS job similar to S3 job. 
medium
low
> [HUDI-6738] - Apply object filter before checkpoint batching in GcsEventsHoodieIncrSource

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerDAGExecution.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestTransformer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Sometimes we see some flakiness around parquet inline reading. 
Ref: https://dev.azure.com/apache-hudi-ci-org/785b6ef4-2f42-4a89-8f0e-5f0d7039a0cc/_apis/build/builds/19457/logs/8
```
2023-08-25T05:00:14.1359469Z 1389627 [Executor task launch worker for task 1.0 in stage 4124.0 (TID 5621)] ERROR org.apache.hudi.common.table.log.AbstractHoodieLogRecordReader [] - Got exception when reading log file
2023-08-25T05:00:14.1360427Z org.apache.hudi.exception.HoodieException: unable to read next record from parquet file 
2023-08-25T05:00:14.1361525Z 	at org.apache.hudi.common.util.ParquetReaderIterator.hasNext(ParquetReaderIterator.java:54) ~[hudi-common-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
2023-08-25T05:00:14.1362403Z 	at org.apache.hudi.common.util.collection.MappingIterator.hasNext(MappingIterator …
```
> [HUDI-6753] Fix parquet inline reading flaky test

- .github/workflows/bot.yml
Adds 40 minute timeout for github check test-hudi-hadoop-mr-and-hudi-java-client
NA
low
NA
> [MINOR] Add timeout for github check test-hudi-hadoop-mr-and-hudi-java-client

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Optimize RLI to not ingest records for updates from data table.
Optimize RLI to not ingest records for updates from data table.
low
> [MINOR] Avoiding to ingest update records to RLI

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestTimeTravelQuery.scala
When time travel query overlaps with cleaner or archival window, we should explicitly fail the query. If not, we might end up serving partial/wrong results or empty rows. 
When time travel query overlaps with cleaner or archival window, we should explicitly fail the query. If not, we might end up serving partial/wrong results or empty rows. 
low …
> [HUDI-6834] Fixing time travel queries when overlaps with cleaner and archival time window

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Avoiding warn log for succeeding in first attempt
Avoiding warn log for succeeding in first attempt
none
> [MINOR] Avoiding warn log for succeeding in first attempt

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala
When users explicitly defines primaryKey and preCombineField when `CREATE TABLE`, subsequent `INSERT INTO` will deduce the operation as `UPSERT`.
Spark `INSERT INTO` semantics.
Medium
NA
> [HUDI-6478] Deduce op as upsert for INSERT INTO

- hudi-common/src/main/java/org/apache/hudi/common/bloom/BloomFilterFactory.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/HashFunction.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/HoodieDynamicBoundedBloomFilter.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/InternalBloomFilter.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/InternalDynamicBloomFilter.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/InternalFilter.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/Key.java
- hudi-common/src/main/java/org/apache/hudi/common/bloom/SimpleBloomFilter.java
- hudi-common/src/main/java/org/apache/hudi/common/util/hash/Hash.java
- hudi-common/src/main/java/org/apache/hudi/common/util/hash/JenkinsHash.java
- hudi-common/src/main/java/org/apache/hudi/common/util/hash/MurmurHash.java
- hudi-common/src/test/java/org/apache/hudi/common/bloom/TestInternalDynamicBloomFilter.java
Port `BloomFilter` related classes from Hadoop library. This has been done to remove Hadoop library dependency as part of HUDI-6824.
No change in public APIs. All functionalities should behave as is. 
low
> [HUDI-6826] Port BloomFilter related classes from Hadoop library

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestIncrSourceHelper.java
This will happen in new onboarding as the old code will initialize prev=start = firstcommit-time, incremental read following this will always get entries > prev, which case we will skip part of first commit in processing.
Initialized prevInstance of commit to default 000 to avoid skipping parts of first commit
Medium
Medium
> [HUDI-6724] - Defaulting previous Instant time to init time to enable full read of initial commit

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
1、initial writeTimer in StreamWriteOperatorCoordinator
initial writeTimer in StreamWriteOperatorCoordinator
medium
1、when checkpoint commit，the writeTimer in org.apache.hudi.client.BaseHoodieWriteClient#emitCommitMetrics is null and not be initialized , so it will ignore the org.apache.hudi.metrics.HoodieMetrics#updateCommitMetrics method， which
makes metrics can not be updated
2、in order to make the writetimer initialized，extract a method from initTable named initTimer 
- _Any new feature or user-facing change requires updating the Hudi website. Please create a Jira …
> [HUDI-6823] initial writeTimer in StreamWriteOperatorCoordinator

- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
- Create new HiveConf object every time when initializing `HiveSyncConfig` and add hadoopConf as resource
We have to load Hadoop conf otherwise properties like `--conf spark.hadoop.hive.metastore.client.factory.class=com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory` won't be able to passed via Spark Hudi job. This issue was introduced another PR to address the OOM issue changed it: https://github.com/apache/hudi/pull/8050
To address the OOM problem we can create a new HiveConf every time instead of casting hadoop conf to hive conf. So we don't keep references to old hadoop conf.
None
None
- _The config description must be updated if new configs are added or the …
> [HUDI-6550] Add Hadoop conf to HiveConf for HiveSyncConfig

- hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestCommitUtils.java
> [HUDI-6858] Fix checkpoint reading in Spark structured streaming

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
Document corresponding configs in cleaner docs and fix some spacing issues.
better documentation
None
N/A
> [MINOR] update cleaner docs

- website/docs/deployment.md
Adds documentation in the deployment guide for downgrading a hudi table. Currently the documentation only discusses the Upgrade steps.
NA
low
NA
> [DOCS] Add documentation around downgrading hudi table

- website/docs/gcp_bigquery.md
- Adds context around the new manifest based approach to the sync and the benefits.
- Updates the configuration to show use manifest option
- Adds additional context around partition handling
Better docs
None
> [HUDI-6857] Update BigQuerySyncTool docs

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
current incremental clean include clean instants when deciding if should fallback to full clean. This pr change to only include commits instants only, because incremental clean only use commits instants to decide which partition should clean.
no
low
> [HUDI-6847] Improve the incremental clean fallback logic

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
If multiple source operators in flink task belong to the same table, it will cause duplicate uids.
bug fix
low
N/A
> [HUDI-6848] Fix non-unique uid for hudi operators

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Before this PR, the auto-tuning logic for dedup parallelism dictates the write parallelism so that the user-configured `hoodie.upsert.shuffle.parallelism` is ignored.  This PR reverts #6802 to fix the issue.
Performance fix
low
N/A
> [HUDI-6863] Revert auto-tuning of dedup parallelism

- website/docs/schema_evolution.md
Fixing schema evolution docs. Moved OOB as first section. Moved comprehensive/schema on read to later section. 
Improves usability and brings more clarify to schema evol support w/ hudi
none
> [HUDI-6869] Fixing schema evolution docs

- hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_docker.sh
- hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_mac_m1.sh
- pom.xml
Upgrade thrift's version from 0.12.0 to 0.13.0.
There is an issue in thrift-0.12.0:
https://issues.apache.org/jira/browse/THRIFT-4805 
Will cause the following problems：
This error message has anything to do with the hoodie，
but if there is a program connected to hoodie metaserver, this error log message will be continuously output.
None
None
None
> [HUDI-6867] Upgrade thrift's version to 0.13.0

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/util/CompactionUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java
The current `getCleanInstantsToArchive` filters clean and rollback instants according to maxInstantsToKeep and minInstantsToKeep respectively. There are two disadvantages: 
1. If user has only a few rollback instants (not satisfied with the archive), then they will exist forever, even if the commit instant has become very large, which can be very confusing for users.
eg:
```java
// user: what is 202101.rollback?
202101.rollback, 202301.commit, 202302.commit ...
```
2. Archiving clean and rollback separately will cause holes in the active timeline.
eg:
```java
archive:
2.clean, 3.clean, 4.clean
active:
1.commit, 5.commit ...
```
A continuous active timeline is our goal.
Therefore, modifying the logic of `getCleanAndRollbackInstantsToArchive` as follows:
```java
// Since the commit instants …
```
> [HUDI-6678] Fix the acquisition of clean&rollback instants to archive

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
Use the project ID for the table when running the job.
This will requires users have permissions to run jobs in the target project that they are creating the table in.
Low, this feature is not yet released, and in general has relatively low usage.
N/A
- [ X ] Read through [contributor's guide](https://hudi.apache.org/contribute/how-to-contribute)
- [ X ] Change Logs and Impact were stated clearly
> [HUDI-6870] Pass project ID to BigQuery job

- hudi-common/src/main/java/org/apache/hudi/internal/schema/InternalSchema.java
- hudi-common/src/main/java/org/apache/hudi/internal/schema/action/InternalSchemaMerger.java
- hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/InternalSchemaUtils.java
- hudi-common/src/test/java/org/apache/hudi/internal/schema/action/TestMergeSchema.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterTableCommand.scala
When schema on read is enabled and user drops a column, then the commit goes through and column is dropped but `schemaId` is incorrecty set to `maxColumnId`. This is a bug. Firstly, drop column is a delete action which should not change the `maxColumnId`. Secondly, `schemaId` must always map to the commit time producing the schema change otherwise it breaks on the reader side or subsequent writes when schema on read is enabled.
Bug fix.
low
ticket number …
> [HUDI-6865] Fix InternalSchema schemaId when column is dropped

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySchemaResolver.java
- hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySchemaResolver.java
- hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
- Removes overhead incurred per partition on manifest file writing to improve performance of sync
- Adds backticks (`) to field names to avoid issues with reserved keywords in BigQuery
Lowers the time to sync the table and fixes bugs for some users
Low
> [HUDI-6871] BigQuery sync improvements

- hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
This PR can sufficient to ensure the retention of the previous commit for first pending clustering, no need to check again.
(https://github.com/apache/hudi/pull/8783)
none.
none.
> [HUDI-6581] Remove unnecessary validations in function getOldestInstantToRetainForClustering

- website/docs/schema_evolution.md
- website/versioned_docs/version-0.11.0/schema_evolution.md
- website/versioned_docs/version-0.11.1/schema_evolution.md
- website/versioned_docs/version-0.12.0/schema_evolution.md
- website/versioned_docs/version-0.12.1/schema_evolution.md
- website/versioned_docs/version-0.12.2/schema_evolution.md
- website/versioned_docs/version-0.12.3/schema_evolution.md
- website/versioned_docs/version-0.13.0/schema_evolution.md
- website/versioned_docs/version-0.13.1/schema_evolution.md
LONG -> FLOAT is supported, but doc-site says it is not. This PR fixes this discrepancy.
https://github.com/apache/hudi/blob/c1062ff75be2ea9f6febc64ca3865e84c7e6c66d/hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/SchemaChangeUtils.java#L39-L53
None
None
> [MINOR][DOCS] Fix supported type changes in doc site

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestMultiWriterWithPreferWriterIngestion.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestCopyOnWriteRollbackActionExecutor.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieClusteringJob.java
The default values for the configs below are incorrect:
1. hoodie.datasource.write.row.writer.enable
2. hoodie.clustering.preserve.commit.metadata (getPreserveHoodieMetadata)
The default values are not loaded from `#defaultVal` as the configurations are defined in a module-scope that is inaccessible by the current scope. This is why config keys are defined as string here.
Raising a PR to fix these inconsistencies first. Subsequent refactoring might be required to move these config-keys to a scope that is accessible by all other (relevant) modules.
**Note:** The existing test coverage does not cover clustering performed using the RowWriter API. Only RDD API is included as of now. 
None - correctness + ease of debugging through consistency
None
_Describe any necessary documentation update …
> [MINOR] Fix default config values if not specified in MultipleSparkJobExecutionStrategy

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
As above, for 0.14.0 config docs.
Fix 0.14.0 config docs.
none
Properly categorize the configs into basic vs advanced configs and fix the since version.
> [MINOR] Mark advanced configs and fix since version

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Cluster planning will run clustering every n commits. To do this, it gets the previous clustering instant and then finds the number of commits after that. However, it was finding the previous clustering instant just by finding the latest replacecommit. Replacecommit is also used for insert_overwrite. Now we check the commit metadata to ensure it is a cluster commit.
clustering now works as expected if lots of insert_overwrite is used
low
N/A
> [HUDI-6882] Differentiate between replacecommits in cluster planning

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/HoodieStreamerConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/KafkaSourceConfig.java
As above.
Mark advanced configs and add since version of "0.14.0".
None
Make sure that a few configs that should be advanced do not show up in the basic configuration page and the configs have the right since version.
> [MINOR] Mark a few new configs advanced and tag since version of 0.14.0

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SchedulerConfGenerator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSchedulerConfGenerator.java
Hudi `SchedulerConfGenerator` configure the generated local file name without scheme, for Spark3.2 or newer version, it could not find the config file:
```bash
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /mnt//yarn/nm-local-dir/usercache/user/appcache/application_1695109514894_0504/container_e2463_1695109514894_0504_01_000001/tmp/ad680d18-28ea-412e-84e0-51dd77d924bd8230486245389606996.xml
at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:87)
at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:77)
at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:169)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNam …
```
> [HUDI-6881] Hudi configured spark.scheduler.allocation.file should include scheme since Spark3.2

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java
`show archived commits` is broken when archived commit contains replacecommit.
- Make `show archived commits` handle replacecommit.
- Make sure `--limit` default to 10 to avoid too many output
NA
Low
NA
> [HUDI-6011] Fix cli show archived commits breaks for replacecommit

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/DiffCommand.java
- hudi-cli/src/main/java/org/apache/hudi/cli/utils/CLIUtils.java
Adding support to trim the timeline for hudi cli clean command. Also added option to load from archive timeline. 
More usable cli for inspecting clean commits
low
> [HUDI-5924] Fixing cli clean command to trim down a subset based on start and end

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
LayoutOptimizationStrategy config values are not snake case like all the other enum configs. This patch fixes that. Additionally, it is backwards compatible.
Less config confusion
none
N/A
> [HUDI-6062] Fix irregular enum config

- website/docs/cli.md
If a user wants to set up and run Hudi CLI on a GCP Dataproc node, currently there is no clear documentation for the same - https://issues.apache.org/jira/browse/HUDI-5826
Updates the cli documentation page with necessary steps for running Hudi CLI on a GCP Dataproc node.
Updates the documentation only
None
This itself is a documentation PR
> [HUDI-5826] Add Hudi CLI docs for GCP Dataproc node

- docker/hoodie/hadoop/trinobase/scripts/trino.sh
Copy the trino bundle at run time so that locally built bundle overrides the one that is present in the image.
Docker-based integ test to use snapshot version of hudi-trino-bundle.
none
> [HUDI-6893] Copy the trino bundle to override the one in the image

- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieEngineContext.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
If run a spark job to insert/insertOverWrite empty data into HUDI table using bulkInsert, the exceptions like 'java.lang.IllegalArgumentException: Positive number of partitions required' would be thrown out.
More detail in [HUDI-6827](https://issues.apache.org/jira/browse/HUDI-6827)
This pr aims to fix the bug.
NA
NA
NA
> [HUDI-6827] Fix task failure when insert into empty dataset

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkRecordMerger.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/CloseableInternalRowIterator.scala
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/CloseableScalaIterator.scala
- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReverseReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderState.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
- hudi-common/src/main/java/org/apache/hudi/common/util/collection/EmptyIterator.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
This PR introduces a new File Group Reader, `HoodieFileGroupReader<T>`, to unify Hudi-specific reader logic across all query types in a single class, while allowing plug-in `HoodieReaderContext<T>` for engine-specific implementation on reading data files, getting field values from a record, transforming a record, etc.  The type argument `T` denotes the type of engine-specific record representation, e.g., `InternalRow` in Spark, `RowData` in Flink, and `ArrayWritable` in Hive, etc.
The reader operates on the engine-specific record representation for reading and merging.  This includes reading the base file and log blocks into `ClosableIterator<T>`.  When merging, the engine-specific records are converted to `HoodieRecord<T>` and passed to `HoodieRecordMerger#merge` API.
This PR covers the …
> [HUDI-6785] Introduce a new File Group Reader

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Currently `CreateHoodieTableCommand` hard code inputFormat, outputFormat and serdeFormat as **PARQUET**, which results the inconsistency between base file format and catalog input format.
Fix the inconsistency.
None.
> [HUDI-6922] Fix inconsistency between base file format and catalog input format

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieInternalConfig.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwriteCommitActionExecutor.java
- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertOverwriteCommitActionExecutor.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
After Insert overwrite into a non-empty partition/table with empty datasets, the subsequent query results are incorrect
For example, current dataset of  partition dt=2021-07-17 is 
| id   | name  |      dt               |
| 1    |    'a'     | '2021-07-17' |
Using the following SQL to overwrite partition dt=2021-07-17
`insert overwrite table targetT partition(dt='2021-07-17') select id, name, price from sourceT where  dt=2021-07-17 and product='test'`
If the input dataset is empty. We expect after insert overwrite, the partition of dt=2021-07-17 is empty.
However, the query result is still the old data.
This pr aims to fix this bug.
NA
NA
NA
> [HUDI-6828] Fix wrong partitionToReplaceIds when insertOverwrite empty data into partitions

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/CustomAvroKeyGenerator.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/factory/TestCreateAvroKeyGeneratorByTypeWithFactory.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/CustomKeyGenerator.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestCustomKeyGenerator.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/factory/TestCreateKeyGeneratorByTypeWithFactory.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/factory/TestHoodieSparkKeyGeneratorFactory.java
Fixes an issue in the custom key generators where we are creating objects per record/row instead of reusing them. This leads to excess object creation which in turn creates more objects to garbage collect.
Improves performance for users using custom key generator
Low
> [HUDI-6916] Improve performance of Custom Key Generators

- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
Hudi can't infer default database name when running hive sync.
 
`hoodie.datasource.hive_sync.database` has a default value of `default` but it would use infer function to read `hoodie.database.name` before using default value.
 
And `hoodie.database.name` is set to an empty string by default and by mistake, which is considered non-null by java `Option` class so Hudi would continue to use the empty string instead of `default` to run hive sync, and cause exceptions below:
 
```
Caused by: org.apache.hudi.exception.HoodieException: Got runtime exception when hive syncing hudi_basic_test_mor51667
  at org.apache.hudi.hive.HiveSyncTool.syncHoodieTable(HiveSyncTool.java:168)
  at org.apache.hudi.sync.common.util.SyncUtilHelpers.runHoodieMetaSync(SyncUtilHelpers.java:79)
  ... 90 more
Caused …
```
> [HUDI-6913] Set default database name correctly

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/DirectMarkerTransactionManager.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSimpleTransactionDirectMarkerBasedDetectionStrategyWithZKLockProvider.java
If the lock provide is ZookeeperBasedLockProvider in SimpleTransactionDirectMarkerBasedDetectionStrategy, the lock_key will be `hoodie.write.lock.zookeeper.base_path` + partition + '/' + fileId in. If the table is a none partition table, the path of znode will be a wrong format.
none
none …
> [HUDI-5911] SimpleTransactionDirectMarkerBasedDetectionStrategy can't work with none-partitioned table

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestGetPartitionValuesFromPath.scala
When merge the log files for MOR table, it can not generate partition values if we drop partition columns while upsert data. As a result, the updated rows in log files will get null for partition columns.
To prevent this issue, we suggest disable `DROP_PARTITION_COLUMNS` while upsert MOR table.
Fix bug in get partition values from path in MOR log files.
None.
ticket number here and follow the [instruction](https://hudi.apache.org/contribute/developer-setup#w …
> [HUDI-6926] Disable DROP_PARTITION_COLUMNS when upsert MOR table

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
Fix TestHoodieSparkMergeOnReadTableInsertUpdateDelete not construct HoodieAvroDataBlock correctly
None
None …
> [MINOR] Fix TestHoodieSparkMergeOnReadTableInsertUpdateDelete not construct HoodieAvroDataBlock correctly

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
Currently we will list all partitions paths when calling 'alter table drop partition' to check if the table is hive style partitions and URL encoded. Listing all partitions path is expensive and we can  get these configs from table config instead. 
This behavior is aligh with 'insert into table', see `org.apache.spark.sql.hudi.ProvidesHoodieConfig#buildHoodieInsertConfig`. 
Get `hiveStylePartitioningEnable` and `urlEncodePartitioning` from table config when 'alter table drop partition'.
low
none
> [HUDI-6925] Do not list all partitions for 'alter table drop partition'

- .github/workflows/bot.yml
- hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
There are two issues with tests that are fixed by this PR:
1. `TestHoodieLogFormat#testHugeLogFileWrite` is trying to write a big log file which was frequently leading to namenode going down. PR removes the superfluous overflow testing.
2. Some unused docker images remained. So those images are pruned to reclaim space to avoid failure due to lack of space.
Fix docker integ tests.
none …
> [HUDI-6917] Fix docker integ tests

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/clustering/plan/strategy/TestSparkConsistentBucketClusteringPlanStrategy.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
We currently uses Flink to generate  clustering plans online, and then Spark to execute them offline.
What we expect is to generate a clustering plan every four commits，like:
commit1,commit2,commit3,commit4,clustering1,commit5,commit6,commit7,commit8,clustering2
However, current timeline is:
commit4,clustering1,commit5,clustering2,commit6,clustering3....
This is not what we want. 
Whether to generate a clustering plan should be determined by whether plan generation has been enabled, rather than whether plan execution has been enabled.
clustering plan generate.
- _The config description must be updated if new …
> [HUDI-6809] Optimizing the judgment of generating clustering plans

- hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java
Method ReflectionUtils.getClass is not thread safe, and in our union all stream read & stream write scenario, will throw null pointer exception.
code:
None.
None.
> [HUDI-6894] ReflectionUtils is not thread safe

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Reverts https://github.com/apache/hudi/commit/2d779fb5aa1ebfd33676ebf29217f25c60e17d12 and fixes #9858 
Fixes partition pruning and improves performance for a table with multiple partition fields.
After the fix, only 1 partition is listed as in the screenshot below.
none
> [HUDI-6941] Fix partition pruning for multiple partition fields

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Since [#9776](https://github.com/apache/hudi/pull/9776) is merged, this pr aims to support multiple streaming writers into the same MOR table with simple bucket index.
Set the following configure to enable this feature:  
* table.type=MERGE_ON_READ
* hoodie.write.concurrency.mode=OPTIMISTIC_CONCURRENCY_CONTROL
* index.type=BUCKET
* hoodie.index.bucket.engine=SIMPLE
* hoodie.cleaner.policy.failed.writes=LAZY
Besides, only enable async cleaning for one writer (by default, they are all enabled).
ps: This work is follow up of [#9125](https://github.com/apache/hudi/pull/9125). Thanks for contribution @danny0405 
NA
NA
Would be add in a separate PR.
> [HUDI-6480] Flink support non-blocking concurrency control

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
There are some details
Commit 20231008185332158 start at 18:53:32.184 and Rolling back immediately after 20 milliseconds(18:53:32.212)
```
2023-10-08 18:53:32.155 INFO  [pool-20-thread-1:0-thread-1] o.a.hudi.table.action.rollback.BaseRollbackActionExecutor - Rollback of Commits [20231008185331924] is complete
.....
2023-10-08 18:53:32.184 INFO  [pool-20-thread-1:0-thread-1] org.apache.hudi.sink.StreamWriteOperatorCoordinator - Create instant [20231008185332158] for table [hudi_sss] with type [COPY_ON_WRITE]
..... 
2023-10-08 18:53:32.212 INFO  [pool-20-thread-1:0-thread-1] org.apache.hudi.client.BaseHoodieWriteClient - Begin rollback of instant 20231008185332158
```
```
-rw-rw-rw-   3 xxx xxx          0 2023-10-08 18:55 hdfs://xxx/user/xxx/bdm_dev.db/hudi_xxx/.hoodie/20231008185533653.roll …
```
> [HUDI-6944] Fix Flink bootstrap concurrency issue causes job to keep rolling back

- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataParquetWriter.java
Fix HoodieRowDataParquetWriter `A Cast A` Exception in flink insert mode
no
low
> [HUDI-6945] Fix HoodieRowDataParquetWriter cast issue

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/FlinkStreamWriteMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
Support some useful flink write metrics. Mainly toward stream write and append write. Tests will be added after the overall design is approved. 
Note that OperatorCoodinator does not support getting `metricGroup`  in the current hudi flink version(1.17.1), so this PR will not include metrics like commit metrics(see #3235) that can only gather by StreamWriteCoordinator. We add task manager metrics only in this pr. 
This pr is following #3235 and fixed #6984. 
fixed #6984. 
none
Will update documents in another pr
> [HUDI-2141] Support flink stream write metrics

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Fix the bug that hoodie table config not work in table properties. Including:
1. Combine `mapTableConfigsToSqlOptions` and `mapDataSourceWriteOptionsToSqlOptions` to `mapHoodieOptionsToSqlOptions` in `HoodieOptionConfig`.
2. Remove unused code in `HoodieOptionConfig`.
Make `hoodie.table.*` configs take effect.
None.
> [HUDI-6924] Fix hoodie table config not wok in table properties

- hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
query should process listed partitions avoid driver oom due to large number files in table first partition 
https://issues.apache.org/jira/browse/HUDI-6950
currently if multiple partition table，would cause oom easy
eg:
CREATE TABLE `hudi_test`.`tmp_hudi_test_1` (
`id` string,
`name` string,
`dt` bigint,
`day` STRING COMMENT '日期分区',
`hour` INT COMMENT '小时分区'
)using hudi
OPTIONS ('hoodie.datasource.write.hive_style_partitioning' 'false', 'hoodie.datasource.meta.sync.enable' 'false', 'hoodie.datasource.hive_sync.enable' 'false')
'primaryKey' = 'id',
'type' = 'mor',
'preCombineField'='dt',
'hoodie.index.type' = 'BUCKET',
'hoodie.bucket.index.hash.field' = 'id',
'hoodie.bucket.index.num.buckets'=512
)
PARTITIONED BY (`day`,`hour`);
select count(1) from …
> [HUDI-6950] Query should process listed partitions to avoid driver oom due to large number files in table first partition

- hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
Updates two spots in the code to use try-with-resources to properly close the scanner
Closes resource
None
> [MINOR] HFileBootstrapIndex: use try-with-resources in two places

- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/execution/RangeSample.scala
- hudi-client/hudi-spark-client/src/test/java/org/apache/spark/sql/hudi/execution/RangeSampleSortTest.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/spark/sql/hudi/execution/TestRangeSampleSort.java
Fixes #8934
see https://issues.apache.org/jira/browse/HUDI-6369
Fix corner case for z-order clustering
low
N/A
> [HUDI-6369] Fix spacial curve with sample strategy fails when 0 or 1 rows only is incoming

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/CopyOnWriteInsertHandler.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/SparkLazyInsertIterable.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
…rce table has partitions and the target table does not
Hudi merge into creates empty partition files when the source table has partitions and the target table does not
No impact for users, this is a internal code refactoring.
medium，see ut for detail
> [HUDI-5031] Fix MERGE INTO creates empty partition files when source table has partitions but target table does not

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
This PR fixes the following failures in CI:
```
- Test multiple partition fields pruning *** FAILED ***
org.apache.spark.sql.catalyst.parser.ParseException: extraneous input ';' expecting <EOF>(line 2, pos 53)
== SQL ==
select * from h171 where day='2023-10-12' and hour=11;
-----------------------------------------------------^^^
at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:241)
at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:117)
at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:69)
at org.apache.spark.sql.hudi.parser.HoodieSpark2ExtendedSqlParser$$anonfun$parsePlan$1.apply(HoodieSpark2ExtendedSqlParse …
```
> [HUDI-6956] Fix CI failures on master

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestCompactionAdminClient.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/CompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
This is to avoid potential exceptions when the reader is processing an uncommitted log file while the cleaning or rollback service removes the log file.
none
none
> [HUDI-6952] Skip reading the uncommitted log files for log reader

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSourceDAGExecution.scala
Fix Overwrite error when ingest multiple tables. HoodieSparkSqlWriter#tableExists may be modified by multiple threads and cause some unexpected behavior. For example, we think the table does not exist after overwriting, but `tableExists` is modified by other threads as true so we won't init the table and create the meta folder. 
This PR makes `tableExists` a local variable to fix the problem.
Fix Overwrite error when ingesting multiple tables.
low
NONE
> [HUDI-6878] Fix Overwrite error when ingest multiple tables

- website/src/theme/DocPage/index.js
website fixes to ensure config links are working as expected.
website changes
Low
> [HUDI-6972][DOCS] Fix config link redirection

- website/releases/release-0.14.0.md
Updated release notes to specify that hudi_table_change table function can only be done though spark SQL/  Also updated and rounded out the title and text.
cc @bhasudha to review
> [Docs] update release notes 0.14.0

- hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
AWS has the limit for dropPartition api to delete only 25 partitions at a time. Updated batch size to reflect the same.
none
none
none
> [HUDI-6932] Updated batch size for delete partitions for Glue sync tool

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BulkInsertFunctionWrapper.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
- hudi-flink-datasource/hudi-flink1.13.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
- hudi-flink-datasource/hudi-flink1.14.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
- hudi-flink-datasource/hudi-flink1.15.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
- hudi-flink-datasource/hudi-flink1.16.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
- hudi-flink-datasource/hudi-flink1.17.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
In the previous [PR#9850](https://github.com/apache/hudi/pull/9850), I forget to take `bulk insert` into consideration.
How to handle the case if the multiple writer contains a job with bulk insert operation?
* Generated file group id: Generate a fixed file group ID because other jobs will use the fixed file group id suffix instead of random uuid suffix. The behavior needs to be consistent to prevent later writer jobs from writing the records with same primary key to different file groups.
* Deal with the transaction: The conflict resolution of bulk insert could not defer to the compaction phase. Because bulk insert writers flush data into base files, if there are multiple bulk insert job, there might exists multiple base files in the same bucket.
NA
NA
NA
> [HUDI-6962] Fix the conflicts resolution for bulk insert under NB-CC

- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
TestInsertTable#Test Bulk Insert Into Consistent Hashing Bucket Index Table failed continuously in #9776, I enabled it again and reproduced it locally. 
The test will cause the write job to abort, and when `org.apache.hudi.spark3.internal.HoodieDataSourceInternalBatchWrite#abort` is called, all the subtasks may not have already been canceled. So if we roll back the current instant immediately, new files may still be written after rollback scheduled, which will cause dirty data.  This bug exists before #9776,  but only after  #9776 the test will fail. 
We don't need to rollback the failed instant immediately, so to avoid this problem, I remove the line that rollback the instant in `org.apache.hudi.spark3.internal.HoodieDataSourceInternalBatchWrite#abort `. 
Bulk insert as row do not …
> [HUDI-6959] Bulk insert V2 do not rollback failed instant on abort

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseWriteHelper.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/commit/TestWriterHelperBase.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestSparkWriteHelper.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
This PR add tests on combine parallelism.  This should be landed after #9722.
No impact on production code logic.
none
N/A
> [MINOR] Add tests on combine parallelism

- pom.xml
This PR upgrades hadoop version from 2.10.1 to 2.10.2 to include important security fixes for log4shell.
Security fixes.
low
N/A
> [HUDI-6977] Upgrade hadoop version from 2.10.1 to 2.10.2

- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
This PR refactors the new file group reader (`HoodieFileGroupReader`) to instantiate `HoodieFileGroupRecordBuffer` inside the file group reader's constrcutors, instead of being passed in from outside.
Simplifies the instantiation of the new file group reader.
none
N/A
> [HUDI-6973] Instantiate HoodieFileGroupRecordBuffer inside new file group reader

- hudi-common/src/main/java/org/apache/hudi/common/table/log/InstantRange.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
1.Adding table name log when consuming commits,  suitable for multi table source scenarios.
Before modification
```
------------------------------------------------------------
---------- consumed to instant: 20231024202835937
------------------------------------------------------------
```
After modification
```
------------------------------------------------------------
---------- table: hudi_cow_1024_a 
---------- consumed to instant: 20231024211208038
------------------------------------------------------------
```
2.Add instant range info print.
#Before modification
`[split_reader -> Sink: Collect table sink (1/1)#0] INFO org.apache.hudi.source.StreamReadOperator - Processing input split : MergeOnReadInputSplit{splitNum=0, basePath=Option{val=hdfs://nameservice/hudi/hudi_cow_1024_a/2 …
> [MINOR] Add table name and range msg for streaming reads logs

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/DayBasedCompactionStrategy.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java
Remove redundant orderAndFilter method in DayBasedCompactionStrategy. 
For example, when partitionPaths = {"2017/01/01", "2017/01/02", "2017/01/03"}, hoodie.compaction.daybased.target.partitions = 1.
In filterPartitionPaths method, we will get the lastest partition "2017/01/03", we get the corresponding operations by scanning this partition.
```
public List<String> filterPartitionPaths(HoodieWriteConfig writeConfig, List<String> allPartitionPaths) {
return allPartitionPaths.stream().map(partition -> partition.replace("/", "-"))
.sorted(Comparator.reverseOrder()).map(partitionPath -> partitionPath.replace("-", "/"))
.collect(Collectors.toList()).subList(0, Math.min(allPartitionPaths.size(),
writeConfig.getTargetPartitionsPerDayBasedCompaction()));
}
```
But in orderAndFilter method, we …
> [HUDI-6975] Optimize the code of DayBasedCompactionStrategy

- hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/FilebasedSchemaProvider.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/RowSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/SanitizationUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSourceFormatAdapter.java
Moving sanitization from sourceFormatAdapter to RowSource , modifying unit tests to consider RowBasedSchemaProvider.
`RowSource` schemaProvider is constructing RowBasedSchemaProvider . Which can be overwritten in `Source` if  external schemaProvider is not null . 
If we sanitize after we create RowBasedSchemaProvider , then schema mismatch is happening ( df.schema is not same as inputBatch.getSchemaProvider.schema)
This Fix will do Sanitization in RowSource 
low …
> [HUDI-6923] Fixing bug with sanitization for rowSource

- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroHFileReader.java
org.apache.hudi.io.storage.HoodieAvroHFileReader.RecordIterator#hasNext uses org.apache.hadoop.hbase.io.hfile.HFileScanner#isSeeked to seek to the first line of the file.
```
if (!scanner.isSeeked()) {
hasRecords = scanner.seekTo();
}
```
if isSeeked returns false, scanner seeks to start of file.
After end of file is reached, isSeeked would still return false and the next time hasNext is called it seeks to start of file again leading to an infinite loop.
Documentation for HFileScanner#isSeeked
True is scanner has had one of the seek calls invoked; i.e. seekBefore(Cell) or seekTo() or seekTo(Cell). Otherwise returns false.
The PR adds a flag(eof) so that false is returned for hasNext if the flag is true.
NA
low
NA
> [HUDI-6896] HoodieAvroHFileReader.RecordIterator iteration never terminates

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Fix HoodieActiveTimeline::deleteInstantFileIfExists not show the file path when occur delete not success
tip: HoodieIOException is not from IOException
when some instants delete is not success，only report the failed instant without the path，but users need the path to get more details
none
low
- _Any new feature or user-facing change …
> [HUDI-7000] Fix HoodieActiveTimeline::deleteInstantFileIfExists not show the file path when occur delete not success

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDropTable.scala
We will first try to load schema from hoodie meta client since [HUDI-6219](https://issues.apache.org/jira/browse/HUDI-6219), it will throw exception if table directory does not exists, in which case we are unable to drop this hudi table.
```bash
20887 [ScalaTest-run-running-TestDropTable] WARN  org.apache.spark.sql.catalyst.catalog.HoodieCatalogTable [] - Failed to load table schema from meta client.
org.apache.hudi.exception.TableNotFoundException: Hoodie table not found in path file:/private/var/folders/6j/vkbrdtgd0x34sqjzgv7s8ckh0000gy/T/spark-8a41e162-dfab-4843-afcd-bb672628747d/h0/.hoodie
at org.apache.hudi.exception.TableNotFoundException.checkTableValidity(TableNotFoundException.java:57) ~[classes/:?]
at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient …
```
> [HUDI-6998] Fix drop table failure when load table as spark v2 table whose path is delete

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestBloomIndexTagWithColStats.java
…om.index.use.metadata
For example we have a table with filed a,b,c, and the primary key is a.
The key-values stored in Col-stats will be 
_hoodie_record_key, min: a:10, max a:100, ...
a, min 10, max 100, ...
b, min 100, max 1000, ...
c, min 99, max 999, ...
if hoodie.bloom.index.use.metadata = true, we load column ranges from col-stats and construct a KeyRangeLookupTree, we query the tree with HoodieKey(generated by KeyGenerator) to get BloomIndexFileInfo,  we should use `_hoodie_record_key` rather than `hoodie.table.recordkey.fields` . 
none
low
none
ticket …
> [HUDI-6946] Data Duplicates with range pruning while using hoodie.bloom.index.use.metadata

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/WriteMarkers.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/model/WriteConcurrencyMode.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsInference.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Currently, non-blocking concurrency control is enabled if a job config satisfy 'OCC + MOR + simple bucket index'.
It's a litter confusing and might lead to unexpected behavior under some cases.
It's better to create a new `WriteConcurrencyMode` type for non-blocking concurrency control .
NA
NA
NA
> [HUDI-6997] A new WriteConcurrencyMode type for non-blocking concurrency control

- packaging/hudi-spark-bundle/pom.xml
This PR fixes the bundling of RoaringBitmap dependency in Hudi bundles by including it in the shade rules and shading the classes, to avoid dependency conflict with engine-provided jars, e.g., Spark.
Before this fix, with Hudi Spark bundle, the following exception is thrown by Spark 3.2:
```
Caused by: java.lang.NoSuchMethodError: org.roaringbitmap.longlong.Roaring64NavigableMap.serializePortable(Ljava/io/DataOutput;)V
at org.apache.hudi.common.table.log.LogReaderUtils.encodePositions(LogReaderUtils.java:128)
at org.apache.hudi.common.table.log.LogReaderUtils.encodePositions(LogReaderUtils.java:109)
at org.apache.hudi.common.table.log.block.HoodieLogBlock.addRecordPositionsToHeader(HoodieLogBlock.java:147)
at org.apache.hudi.common.table.log.block.HoodieDeleteBlock.<init>(HoodieDeleteBlock …
```
> [HUDI-7016] Fix bundling of RoaringBitmap dependency

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
In `HoodieTable.java`, the code at line 173 is:
`public HoodieTableMetadata getMetadata() {
return metadata;
}`
While the code at line 1036 is:
`public HoodieTableMetadata getMetadataTable() {
return this.metadata;
}`
They both return the same variable, making the code redundant. So, we have kept the method at line 1036 which has a clearer name and changed the references of getMetadata to getMetadataTable.
None
None
None
> [MINOR] Delete the duplicated getMetadata method in HoodieTable.

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSortAndSizeExecutionStrategy.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkSortAndSizeClustering.java
Clustering plan is generated in PartitionAwareClusteringPlanStrategy. `writeConfig.getClusteringTargetFileMaxBytes()` decides the final size of parquet file. So fix it.
```
// check if max size is reached and create new group, if needed.
if (totalSizeSoFar + currentSize > writeConfig.getClusteringMaxBytesInGroup() && !currentGroup.isEmpty()) {
int numOutputGroups = getNumberOfOutputFileGroups(totalSizeSoFar, writeConfig.getClusteringTargetFileMaxBytes());
LOG.info("Adding one clustering group " + totalSizeSoFar + " max bytes: "
+ writeConfig.getClusteringMaxBytesInGroup() + " num input slices: " + currentGroup.size() + " output groups: " + numOutputGroups);
fileSliceGroups.add(Pair.of(currentGroup, numOutputGroups));
currentGroup = new ArrayList<>();
totalSizeSoFar = 0;
}
```
none
_If …
> [HUDI-6991] Fix hoodie.parquet.max.file.size conf reset error

- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
In some case even when purge is set true, truncate or drop but dir cannot be deleted
delete dir with recursive
> [HUDI-7013] Drop table command cannot delete dir even when purge is enable

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
Currently, there is no speed limit for stream read, and regardless of the instantranges, they will be read at once. It is easy to cause GC of monitor operator.
Add a configuration to limit the number of commits read per round in stream read mode.
stream read.
low.
> [HUDI-6969] Add speed limit for stream read

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/FlinkCompactionMetrics.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java
currently, when flink job start async compaction on a mor table, the metrics in org.apache.hudi.metrics.FlinkCompactionMetrics 
will update including pendingCompactionCount,compactionDelay,compactionCost. However, when a compaction failed need a metric to
help user to know specific instant whether the final compaction has occured rollback.
so attemp to add a metric named compactionFailedState in org.apache.hudi.sink.compact.CompactionCommitSink to record the instance
happend rollback, which also means the current compaction failed in current time
add a metric named compactionFailedState in org.apache.hudi.sink.compact.CompactionCommitSink to record the instance
happend rollback, which also means the current compaction failed in current time
no impact
low medium
_Describe any necessary …
> [HUDI-7011] a metric to indicate whether rollback has occurred in final compaction state

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedureUtils.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Since clustering plan generation is non-blocking, all generated pending clustering plans will be executed at once when using `call run_clustering(table => '$table', op => 'execute')` in default. Adding limit parameter to execute these plans in batches by `call run_clustering(table => '$table', op => 'execute', limit => 10)`. Limit parameter is optional and has no default value.
Support new parameter.
low …
> [HUDI-7022] RunClusteringProcedure support limit parameter

- hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestWaitBasedTimeGenerator.java
`testSlowerThreadLaterAcquiredLock` was disabled and got fixed by #9972. This PR simple enables it again.
none - test change
none
> [MINOR] Re-enable a test that got fixed

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
Initializing RLI for an existing table had a minor bug for non-partitioned dataset. Fixing as part of the patch. 
Opens up RLI for non partitioned dataset. 
low.
N/A
> [HUDI-7002] Fixing initializing RLI MDT partition for non-partitioned dataset

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java
- packaging/hudi-aws-bundle/pom.xml
- packaging/hudi-flink-bundle/pom.xml
- packaging/hudi-hive-sync-bundle/pom.xml
Relocates org.apache.avro to org.apache.hudi.org.apache.avro while shading hudi-common classes in hudi-hive-sync-bundle and hudi-aws-bundle to avoid conflicts while working with hudi-flink-bundle and any other bundle where it is relocated already.
Flink SQL Client Fixes.
low
NA
> [HUDI-7005] Fix hudi-aws-bundle relocation issue with avro

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Spark executes clustering will generate too many tasks which is equal to the the number of files in clustering plan. Support config it when read files.
None
> [HUDI-6990] Configurable clustering task parallelism 

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/CompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/util/CompactionUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Metadata table (MDT) has special handling for compaction. This PR ensures MDT compaction is handled in completion time based filesystem view. Previously, out-of-rder commit tests were disabled. This PR now enables that test to show the file slicing is happens correctly.
NOTE: This PR does not remove the limitation of single writer or OCC concurrency mode from MDT. That will be tackled separately.
Support out of order commits due to compaction in MDT with completion time view.
low
- _Any new feature or user-facing change requires updating the Hudi website. Please create a …
> [HUDI-2461] Support out of order commits in MDT with completion time view

- website/docs/procedures.md
Update run_clustering procedure docs.
none
> [DOCS] update run_clustering procedure docs

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroKafkaSource.java
- Filtering out null values from avro kafka source
- Tombstone records could have null values and hence filtering them out.
- Will unblock pipelines having tombstone records in kafka (postgres debezium for eg)
low
> [HUDI-7009] Filtering out null values from avro kafka source

- website/blog/2023-11-01-record-level-index.md
remove problematic tag `index` that messed up with docusaurus generating `index.html`  web pages.
```
Error:  Unable to build website for locale en.
Error:  Error: Redirect file creation error for "/home/runner/work/hudi/hudi/website/build/blog/tags/index.html/index.html" path: Error: EEXIST: file already exists, mkdir '/home/runner/work/hudi/hudi/website/build/blog/tags/index.html'.
at writeRedirectFile (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/plugin-client-redirects/lib/writeRedirectFiles.js:76:15)
at async Promise.all (index 238)
at async writeRedirectFiles (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/plugin-client-redirects/lib/writeRedirectFiles.js:81:5)
at async Object.postBuild (/home/runner/work/hudi/hudi/website/node_modules/@docusaurus/plugin …
```
> [MINOR] Fix build failure caused by bad tag name `index`

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HdfsParquetImportProcedure.scala
[MINOR] hotfix in HdfsParquetImportProcedure for parquet parameter is not need to add
none
none
> [MINOR] Hotfix in HdfsParquetImportProcedure for format parameter is not need to add

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordLocation.java
When building profile, the spark driver should only care data distribution on (partition_path, instant_time, file_id), instead of (partition_path, instant_time, file_id, record_position).
TESTS:
1. Before remove the record position from the comparison, the driver OOMed constantly.
2. After remove the record position from the comparision, both 500GB and 1TB query finished like a charm. 
This fix removes some stability regression for large queries.
Low.
> [HUDI-7036] Reduce the data amount collected on spark driver

- pom.xml
https://github.com/apache/hudi/pull/9136 upgraded the `rocksdbjni.version` from 5.17.2 to 7.5.3 so this is no longer needed, and could actually cause issues in the future
Prevent future issue for mac users
none
N/A
> [MINOR] Remove rocksdb version from m1 profile

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestSparkBuildClusteringGroupsForPartition.java
We build clustering group and get the final clustering plan with `getWriteConfig().getClusteringMaxNumGroups()` size. So there is no need to travel all FileSlices in `buildClusteringGroupsForPartition` method in some cases.
```
// PartitionAwareClusteringPlanStrategy
List<HoodieClusteringGroup> clusteringGroups = getEngineContext()
.flatMap(
partitionPaths,
partitionPath -> {
List<FileSlice> fileSlicesEligible = getFileSlicesEligibleForClustering(partitionPath).collect(Collectors.toList());
return buildClusteringGroupsForPartition(partitionPath, fileSlicesEligible).limit(getWriteConfig().getClusteringMaxNumGroups());
},
partitionPaths.size())
.stream()
.limit(getWriteConfig().getClusteringMaxNumGroups())
.collect(Collectors.toList());
```
none
_If medium or high, explain what verification …
> [HUDI-7010] Build clustering group reduces redundant traversals

- hudi-common/src/main/java/org/apache/hudi/common/model/PartialUpdateAvroPayload.java
currently PartialUpdateAvroPayload preCombine would not show details even when failed，user need it to judge whether success
none
none
> [HUDI-7039] PartialUpdateAvroPayload preCombine failed need show details

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCompactionProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCompactionProcedure.scala
RunCompactionProcedure support limit parameter to execute plans in batches by `call run_compaction(table => '$tableName', op => 'execute', limit => 10)`. Limit parameter is optional and has no default value.
none
> [HUDI-7038] RunCompactionProcedure support limit parameter

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Before changing MOR to COW, we will do a full compaction. But in the .commit meta file generated by compaction, there is no checkpoint info. So in such table type changing case, there is dataloss issue.
The pr is going to fix this.
none
low
none
> [HUDI-7048] Fix checkpoint loss issue when changing MOR to COW in streamer

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartialUpdateAvroPayload.scala
- style/scalastyle.xml
Fix following issues for the new filegroup reader:
- Handle nested schema
- Append partition values correctly.
Fixes some issue for new fielgroup reader for MOR table.
low
> [HUDI-7042] Fix new filegroup reader

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
testFileListingWithPartitionPrefixPruning has columns "id", "name", "price", "region_code", "dt" but commonOpts sets DataSourceWriteOptions.PRECOMBINE_FIELD.key -> "timestamp". We need to overwrite it with a column that exists
testAlteringRecordKeyConfig sets the precombine to ts but the datagenerator schema does not have that field
make tests more correct
none
N/A
> [MINOR] Fix tests that set precombine to nonexistent field

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
update containsInstant without containsOrBeforeTimelineStarts to fix data lost
jira：https://issues.apache.org/jira/browse/HUDI-7030
update containsInstant without containsOrBeforeTimelineStarts to fix data lost
high
Describe any necessary documentation update if there is any new feature, config, or user-facing change
The config description must be updated if new configs are added or the default value of the configs are changed
Any new feature or user-facing change requires updating the Hudi website. Please create a Jira ticket, attach the
changes to the website.
> [HUDI-7030] update containsInstant without containsOrBeforeTimelineStarts to fix data lost

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCDCFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieIncrementalFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/HoodieMultipleBaseFileFormat.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
In HoodieIncrementalFileIndex Seq.empty won't be returned unless the rest of the method is in an else block
disable vectorized reader for incremental
testPrunePartitionForTimestampBasedKeyGenerator :
- if the date is already in the output format then we don't need to try and convert it
- add partition pruning to the query
TestIncrementalReadWithFullTableScan:
- There are schema issues with impl that were fixed by correctly setting mandatory fields and projecting to the output schema
Remove some bugs
low
N/A
> [HUDI-7047] fix various issues with incremental queries in new file format

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/merge/SparkRecordMergingUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
This PR fixes the logic of merging partial updates with projected reader schema, i.e., the reader schema contains a subset of fields from the table schema based on the query.
- When processing log records in `HoodieBaseFileGroupRecordBuffer#doProcessNextDataRecord`, the schema of the combined record is also updated in the metadata since the schema can change due to partial merging;
- A bug of getting the field values from the older record in `SparkRecordMergingUtils#mergePartialRecords` is fixed.
- The partial update tests in `TestPartialUpdateForMergeInto` are enhanced to cover partial merging logic.
Makes sure the partial merging logic is correct.
low
N/A
> [HUDI-7046] Fix partial merging logic based on projected reader schema

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
Add a new config `hoodie.merge.use.record.positions` to tell the reader whether to merge the log block using positions or  not. Currently `hoodie.write.record.positions` controls this. We want to separate read and write.
better user experience
none
N/A
> [HUDI-7056] Add config for merging using positions

- hudi-common/src/main/java/org/apache/hudi/common/model/FileSlice.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/CompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestFileSlice.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadMonitoringFunction.java
IncrementalInputSplit has set an incorrect endInstant for MergeOnReadInputSplit, which can lead to inaccurate downstream stream read metrics.
stream read metrics
none.
> [HUDI-6992] IncrementalInputSplits incorrectly set the latestCommit attr

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CopyToTableProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCopyToTableProcedure.scala
currently CopyToTableProcedure only support all schema copy to a new table，but many sences user need a part columns from table schema，for example user don't need metadata column due to storage cost
none
lower
> [HUDI-7057] Support CopyToTableProcedure with patitial column copy

- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
When position based merging is enabled, we can safely skip reading records in delete blocks since we can use the record positions to skip records in base file, which should accelerate the performance of the delete operations.
Things have been considered.
1. position based merging is turned on.
2. processing time based merging strategy, which is by default.
3. the merging orders.
Low.
Low.
> [HUDI-7044] Skip reading records for delete blocks for positional merging

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
Due to the bug fixing status, we decide to use the following rules to turn on/off new_spark_file_format and file_group_reader_file_format. Rules are as follows:
1. For CDC queries, we should not use either of the two file formats. Then we keep using the existing relation.
2. For time_travel queries and bootstrap queries, we use new_spark_file_format but not use file_group_reader_file_format.
3. For Incremental queries, we use the existing relations, e.g., IncrementalRelation or MergeOnReadIncrementalRelation to handle.
Low.
Low.
> [HUDI-7060] Disable new file group reader or new parquet file format for CDC, time travel, and incremental query types

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
For MOR table, when position based merging is specified, no filters should be pushed down; otherwise, the filters can be pushed down for key based one.
TESTS:
1. need to make the demo work to demonstrate that the filter has been pushed down.
2. need to prove the the pushdown is logically correct for key based merging.
After fixing, the user should have higher performance for key based merging queries.
Low.
> [HUDI-7053] Fix the filter pushdown logic for file group reader

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
Currently, type change is not supported with new file format and file group reader. This PR turns them off for such tests. 
Should probaby be fixed by #10007 
none
none
> [MINOR] Turn off filegroup reader for type promotion tests

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
As above.  In some cases, e.g., in the test `org.apache.hudi.functional.TestCOWDataSource#testHoodieIsDeletedCOW`, the new file group reader has compatibility issues reading base files only with Spark.  So for now, the logic is reverted.
Fixes functionality issues.
none
N/A
> [HUDI-7063] Use existing relation logic for queries reading base files only in Spark

- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
Sometimes df.count() ends up calling hasnext multiple times before calling next() so we need to use caching iterator style
fix issue that was causing tests to fail
low
N/A
> [HUDI-7062] Implement Caching Iterator for new filegroup reader

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
supports batch result is cached so the different file readers used are consistent for a query. File format can be used multiple times, so we don't want support batch to be true for the next query
Remove failure point
low
N/A
> [HUDI-7064] Recheck should use batch when cached result is true

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
This PR improves the partial update logic in Spark SQL MERGE INTO statement so that the partial updates are not enabled if all fields corresponding to the table schema are updated (e.g., `UPDATE SET *`), since if all fields are updated, there is no point marking the updates as partial and existing merging logic based on full updates can still be applied.  A new test is added to validate the improvement from this PR.
Improves the case where all fields are updated and there is no need to go through partial update logic.
low
N/A
> [HUDI-7067] Add fallback to full update if all fields are updated in MERGE INTO statement

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
set "spark.sql.parquet.enableVectorizedReader" based on support batch
prevent failure
low
N/A
> [HUDI-7068] Disable vectorized reader for hoodie filegroup reader when schema isn't supported

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
This PR adds the check on update action to disable partial update for MERGE INTO statement without update action.  In case the inserts are added to the log block, since inserts have to be full records, the partial update functionality should be disabled and `IS_PARTIAL` log block header should not be added.
New tests are added for validation.
Avoid unnecessary partial update log blocks.
low
N/A
> [HUDI-7070] Disable partial update for MERGE INTO statement without update action

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/ShowHoodieTablePartitionsCommand.scala
Thinking it might be better to directly let `HoodieCatalogTable` to filter deleted partitions, it shouldn't show deleted partitions when calling `getPartitionPaths`.
This can also fix `RepairHoodieTableCommand` to not repair deleted partitions.
None
None …
> [HUDI-7054][FOLLOW_UP] HoodieCatalogTable should ignore lazily deleted partitions

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
As above.  When turning on the file group reader-based parquet file format for MOR snapshot queries, the following exception is thrown in a few tests although ts exists in the schema
```
2023-11-09T21:08:42.7345689Z - Test Call show_logfile_metadata Procedure *** FAILED ***
2023-11-09T21:08:42.7347213Z   java.lang.IllegalArgumentException: Field ts does not exist in the data schema
2023-11-09T21:08:42.7349324Z   at org.apache.spark.sql.execution.datasources.parquet.HoodieFileGroupReaderBasedParquetFileFormat.$anonfun$generateRequiredSchemaWithMandatory$4(HoodieFileGroupReaderBasedParquetFileFormat.scala:277)
2023-11-09T21:08:42.7407685Z   at scala.Option.getOrElse(Option.scala:189)
2023-11-09T21:08:42.7409315Z   at org.apache.spark.sql.execution.datasources.parquet.HoodieFileGroupReaderBas …
```
> [HUDI-7073] Fix schema projection in file group reader-based parquet file format

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
> [MINOR] Fix the flag for bootstrap

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/CompactHelpers.java
- hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Disable the new file format for the metadata table because we haven't implemented hfile base files yet. Also made new method for duplicated code
metadata table will work
low
N/A
> [HUDI-7079] disable new file format for metadata table

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
disable new reader explicitly 
not supported currently so will pass even if reader is enabled by default
none
N/A
> [MINOR] disable reader in schema evo test

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Enums can't be read by new filegroup reader, because it converts structtype to avro for the log block read schema
followup ticket was created to fix this:
https://issues.apache.org/jira/browse/HUDI-7081
prevent test failure
low
N/A
> [MINOR] Disable reader for test with enum

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSource.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestNestedSchemaPruningOptimization.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestHoodiePruneFileSourcePartitions.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
This PR enables the following new features by default through configs:
- Write record positions to MOR log data blocks (`hoodie.write.record.positions`)
- Enable partial updates when possible for Spark SQL MERGE INTO statement (`hoodie.spark.sql.merge.into.partial.updates`)
- Use new file group reader for MOR snapshot queries (`hoodie.file.group.reader.enabled`)
- Use new Hudi Spark parquet file format for various types of queries (`hoodie.datasource.read.use.new.parquet.file.format`)
The PR also disables a handful of tests which will be addressed later.
Turns on new features by default through configs for `1.0.0-beta1` release.
medium
Config will be automatically updated in the docs.
> [HUDI-7076] Turn on new features by default through configs for 1.0.0-beta1

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergedReadHandle.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java
Flink incremental queries works with non-blocking concurrency control.
Also fix the test regression of MDT in https://github.com/apache/hudi/pull/9871.
none
none
> [HUDI-7074] Flink incremental query for non-blocking concurrency control

- scripts/release/deploy_staging_jars.sh
- scripts/release/validate_staged_bundles.sh
- scripts/release/validate_staged_release.sh
This PR updates the release scripts based on the latest release:
- Adds build profiles for Spark 3.0 and 3.4 in `deploy_staging_jars.sh`.
- Adds `hudi-spark3.0-bundle_2.12` and `hudi-spark3.4-bundle_2.12` to the list of bundles in `validate_staged_bundles.sh`
- Uses HEAD requests which do not download the content (only checking if the URL or file exists) instead of `wget` to save time in bundle checking in `validate_staged_bundles.sh`
- Relax release version (which can be `1.0.0-beta1`) in `validate_staged_release.sh`
Makes sure the release scripts are up to date.
none
N/A
> [HUDI-7085] Update release scripts

- hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
Incremental read when first write contains delete and upsert will fail. It will return precombined result after fix the issue.
Lated Issue:
https://issues.apache.org/jira/browse/HUDI-7035
https://github.com/apache/hudi/issues/9987
Error Stack Following:
org.apache.hudi.exception.HoodieException: There should be a cdc log file.
at org.apache.hudi.common.table.cdc.HoodieCDCExtractor.parseWriteStat(HoodieCDCExtractor.java:276)
at org.apache.hudi.common.table.cdc.HoodieCDCExtractor.lambda$extractCDCFileSplits$1(HoodieCDCExtractor.java:131)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.apache.hudi.common.table.cdc.HoodieCDCExtractor.extractCDCFileSplits(HoodieCDCExtractor.java:126)
at org.apache.hudi.cdc.CDCRelation.buildScan0(CDCRelation.scala:105)
at …
> [HUDI-7035] Fix CDC Incremental Read When First Write Contains Delete And Upsert

- hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java
related issue: https://github.com/apache/hudi/issues/9902
get internal schema maybe meet  npe when parse avroSchema. So, we need to return InternalSchema.getEmptyInternalSchema() when avroSchema is null or empty.
none
none
> [MINOR] Fix npe for get internal schema

- packaging/hudi-utilities-bundle/pom.xml
This PR fixes the bundling of RoaringBitmap dependency in hudi-utilities-bundle. It was previously fixed for Spark bundle in https://github.com/apache/hudi/commit/8d2b664864bfb02311ff3bedbb937590203371d2 but we missed utilities bundle.
Without this fix, running deltastreamer with only hudi-utilities-bundle will throw below error.
```
java.lang.NoSuchMethodError: org.roaringbitmap.longlong.Roaring64NavigableMap.serializePortable(Ljava/io/DataOutput;)V
```
Fix dependency issue and successfully run deltastreamer with just hudi-utilities-bundle.
low …
> [HUDI-7016] Fix bundling of RoaringBitmap in hudi-utilities-bundle

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/HadoopConfigurations.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogFactory.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogUtil.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/HoodieCatalogTestUtils.java
Flink HoodieHiveCatalog supports hadoop parameters
Flink HoodieHiveCatalog supports hadoop parameters
low
Flink HoodieHiveCatalog supports hadoop parameters
> [HUDI-7050]Flink HoodieHiveCatalog supports hadoop parameters

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddColumnsCommand.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableChangeColumnCommand.scala
Currently, `AlterTableCommand`, `DropHoodieTableCommand`, `Spark30AlterTableCommand`, `Spark31AlterTableCommand` would not only update the specified table, but also would update the table with ro/rt suffix. But `AlterHoodieTableAddColumnsCommand`, `AlterHoodieTableChangeColumnCommand` missed to update schema of table with  ro/rt suffix. 
This pr aims to fix it.
NA
NA
NA
> [HUDI-7094] AlterTableAddColumnCommand/AlterTableChangeColumnCommand update table with ro/rt suffix

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCompactionProcedure.scala
Currently, if errors happened in compaction phase, we could only get the above exception. 
It's better to add more detailed logs help us to find which task occur write errors.
In this pr, add `path`  into error logs because we could find taskPartitionId, stageId, taskAttemptId in write token based on the file path.
NA
NA
NA
> [MINOR] Add detailed error logs in RunCompactionProcedure

- website/docs/concurrency_control.md
- website/releases/download.md
- website/releases/older-releases.md
- website/releases/release-0.10.0.md
- website/releases/release-0.10.1.md
- website/releases/release-0.11.0.md
- website/releases/release-0.11.1.md
- website/releases/release-0.12.0.md
- website/releases/release-0.12.1.md
- website/releases/release-0.12.2.md
- website/releases/release-0.12.3.md
- website/releases/release-0.13.0.md
- website/releases/release-0.13.1.md
- website/releases/release-0.14.0.md
- website/releases/release-0.6.0.md
- website/releases/release-0.7.0.md
- website/releases/release-0.8.0.md
- website/releases/release-0.9.0.md
- website/releases/release-1.0.0-beta1.md
Release notes for 1.0.0-beta1 release. Note that only the release page is updated. A new version is not cut as it is just beta. All beta features will be pointing to `/docs/next/...`. 
release notes
none
> [HUDI-7092] Release notes for 1.0.0-beta1 release

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCleaner.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
Issue: #10035 
Spark applications should not use `System.exit` to terminate itself, see [SPARK-1446](https://issues.apache.org/jira/browse/SPARK-1446)
None
Low
> [MINOR] Throw exceptions when cleaner/compactor fail

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
In https://github.com/apache/hudi/pull/6144, a new compaction trigger strategy was added named `NUM_COMMITS_AFTER_LAST_REQUEST`, org.apache.hudi.table.action.compact.CompactionTriggerStrategy.
However, the FlinkOptions description was not updated to include this new trigger strategy. Adding it in so that configs page on doc-site will reflect this trigger strategy for completeness.
**TODO:** 
Might need to do some refactoring to centralise these common config so that we do not have to worry about these de-sync in the future. Might also make it easier for testing.
None
None …
> [MINOR] Modified description to include missing trigger strategy

- hudi-aws/src/test/java/org/apache/hudi/aws/TestHoodieAWSCredentialsProviderFactory.java
As above, to disable a failed test introduced by #9260.  HUDI-7114 as a follow up to fix the test.
Unblocks CI.
none
N/A
> [MINOR] Disable failed test on master

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
The parallelism of singleton operator should be strictly controlled, which can avoid some problems caused by modifying parallelism through other means.
For example:
if set the split_monitor operator parallelism to 10 , it will read data 10 times.
> [HUDI-7090]Set the maxParallelism for singleton operator 

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
If Flink is crashed after instant committed but before `this.ckpMetadata.commitInstant(instant);`
Re-start, Flink may re-use a committed instant in append mode.
Will check candidate re-used instant is committed or not
if committed, Hoodie would abort current instant.
Flink append mode.
low
Committed instant 20231114121907373 is re-used in next writing loop.
related logs 
```
2023-11-14 12:20:04.791 INFO  [Sink: hoodie_append_:5/750)#114] org.apache.hudi.sink.common.AbstractStreamWriteFunction - Init write metadata state : WriteMetadataEvent{writeStatusesSize=1, taskID=524, instantTime='20231114121907373', lastBatch=false, endInput=false, bootstrap=true} & 
2023-11-14 12:20:04.792 INFO  [Sink: hoodie_append_:7/750)#114] org.apache.hudi.sink.common.AbstractStreamWriteFunction - Init write …
```
> [HUDI-7109] Fix Flink may re-use a committed instant in append mode

- packaging/bundle-validation/base/build_flink1146hive239spark248.sh
Add the build image for flink 1.14 and spark 2.4.8.
none
none
> [HUDI-7116] Add docker image for flink 1.14 and spark 2.4.8

- README.md
- scripts/release/deploy_staging_jars.sh
- scripts/release/validate_staged_bundles.sh
As above.
Release scripts and docs update.
none
As above.
> [HUDI-7113] Update release scripts and docs for Spark 3.5 support

- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudStoreIngestionConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
Adding max bytes per partition with cloud stores source in DS
Adding max bytes per partition with cloud stores source in DS. This should help scale cloud store source scaling for large ingest.
none
> [HUDI-7098] Adding max bytes per partition with cloud stores source in DS

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
In the existing table service, `HoodieMetrics` registers the duration and other relevant information for compaction, clustering, and clean operations. However, there are no corresponding metrics for the archive operation. Therefore, we have implemented the necessary metrics for the archive operation.
Additionally, we have defined string constants in the field to extract string literal in `HoodieMetrics`.
Providing metrics for archive.
None
None
None
> [HUDI-7099] Providing metrics for archive and defining some string constants

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
In Kafka AVRO source, the schema config for KafkaAvroSchemaDeserializer is only set during constructor and not refreshed for every batch. In Deltastreamer cont. mode, this creates an issue when schema evolves for the kafka messages.
Bug fix for Kafka Avro Source
Medium
> [HUDI-7108] Fix schema refresh for KafkaAvroSchemaDeserializer

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapMORRelation.scala
Currently, conf 'spark.sql.parquet.enableVectorizedReader' does not work properly. See complete discussion in [issue-9129](https://github.com/apache/hudi/issues/9129).
The pr aims to fix it.
none
none
NA
> [HUDI-7118] set conf 'spark.sql.parquet.enableVectorizedReader' to true automatically only if the value is not explicitly set

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/Metrics.java
When shutdown all the metrics, clear the metric cache to avoid reusing already stopped MetricsReporter
No public API change.
low
N/A
> [HUDI-7107] Reused MetricsReporter fails to publish metrics in Spark streaming job

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieParquetBloom.scala
Fixing set up and tear down in tests
Unblock CI instability
low
> [HUDI-7127] Fixing set up and tear down in tests

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Misc fixes to deltastreamer sources
Misc fixes to deltastreamer sources
none
> [MINOR] Misc fixes in deltastreamer

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PrometheusReporter.java
Adding support for multiple tables with Prometheus Reporter
Adding support for multiple tables with Prometheus Reporter
low
> [HUDI-7083] Adding support for multiple tables with Prometheus Reporter

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
This reverts commit 2567ada6d5654bf8463cb55e25f5d662aa5a8475 to solve #6940
Conflicts:
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
This commit is to add back the feature introduced in HUDI-5409, but changing the default value in the following snippet to true (=`ENABLE.defaultValue()`). Also, if the files partition is available, Hudi will use file index automatically regardless of the configuration.
```
if (HoodieTableMetadataUtil.isFilesPartitionAvailable(tableMetaClient) || conf.getBoolean(ENABLE.key(), ENABLE.defaultValue())) {
```
instead of false (=`DEFAULT_METADATA_ENABLE_FOR_READERS`) in …
> [HUDI-6734] Add back HUDI-5409: Avoid file index and use fs view cache in COW input format

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelector.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/ErrorTableUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
PR fixes a few things:
SQS source should send delete API if no delete messages.
Ensure the same catalog sync class is not called twice
Error table failure strategy has default value set
Minor bug fixes.
medium
> [HUDI-7106] Fix sqs deletes, deltasync service close and error table default configs.

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteMarkerProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteSavepointProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestSavepointsProcedure.scala
DeleteProcedures support batch mode
eg：
if user want to delete 100 or more markers，before the pr need execute sparksql job for 100 times，and just once after the pr，it would reduce much execute time in sparksql.
none
low
> [HUDI-7128] DeleteProcedures support batch mode

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieTableFileIndex.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieMergeHandleWithSparkMerger.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
Improving incr query by directly fetching the partitions based on commit metadata for commits based on start and end. And thus avoiding to poll metadata table or do file system based listing to fetch partitions in FileIndex.
Improves query perf of incr query.
low
> [HUDI-7096] Improving incremental query to fetch partitions based on commit metadata

- hudi-examples/hudi-examples-dbt/README.md
Update dbt example with more detailed instructions.
Improve dbt example for learning.
None.
NA
> [HUDI-7133] Improve dbt example for better guidance

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToFourUpgradeHandler.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/UpgradeOrDowngradeProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
When upgrade from table version 3 to table version 4 using UpgradeOrDowngradeProcedure, the following exception would be thrown out.
> java.lang.IllegalArgumentException: hoodie.table.name property needs to be specified
at org.apache.hudi.common.table.HoodieTableConfig.generateChecksum(HoodieTableConfig.java:478) ~[classes/:?]
at org.apache.hudi.table.upgrade.ThreeToFourUpgradeHandler.upgrade(ThreeToFourUpgradeHandler.java:43) ~[classes/:?]
at org.apache.hudi.table.upgrade.UpgradeDowngrade.upgrade(UpgradeDowngrade.java:173) ~[classes/:?]
at org.apache.hudi.table.upgrade.UpgradeDowngrade.run(UpgradeDowngrade.java:143) ~[classes/:?]
at org.apache.spark.sql.hudi.command.procedures.UpgradeOrDowngradeProcedure.$anonfun$call$1(UpgradeOrDowngradeProcedure.scala:69) ~[classes/:?]
at …
> [HUDI-7129] Fix bug when upgrade from table version three using UpgradeOrDowngradeProcedure

- hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestDefaultHoodieRecordPayload.java
This PR fixes the DefaultHoodieRecordPayload to allow the records with custom delete key (hoodie.payload.delete.field) and delete marker (hoodie.payload.delete.marker) to be properly ingested. Before this fix, the write fails with the following exception
Error for key:HoodieKey { recordKey=0 partitionPath=} is 
java.util.NoSuchElementException: No value present in Option
at org.apache.hudi.common.util.Option.get(Option.java:89)
at org.apache.hudi.common.model.HoodieAvroRecord.prependMetaFields(HoodieAvroRecord.java:132)
at org.apache.hudi.io.HoodieCreateHandle.doWrite(HoodieCreateHandle.java:144)
at org.apache.hudi.io.HoodieWriteHandle.write(HoodieWriteHandle.java:180)
at org.apache.hudi.execution.CopyOnWriteInsertHandler.consume(CopyOnWriteInsertHandler.java:98)
at …
> [HUDI-6961] Fixing DefaultHoodieRecordPayload to honor deletion based on meta field as well as custome delete marker

- hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SnapshotLoadQuerySplitter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
Adding support of `SnapshotLoadQuerySplitter`(interface) in `S3EventsHoodieIncrSource` and `GcsEventsHoodieIncrSource` . 
SnapshotLoad Query can be split into multiple checkpoints using SnapshotLoadQuerySplitter implementation . 
low
> [HUDI-7004] Add support of snapshotLoadQuerySplitter in s3/gcs sources

- .github/workflows/bot.yml
- azure-pipelines-20230430.yml
- packaging/bundle-validation/base/build_flink1153hive313spark323.sh
- packaging/bundle-validation/base/build_flink1162hive313spark331.sh
- packaging/bundle-validation/ci_run.sh
This PR improves the CI scripts in the following aspects:
- Removes `hudi-common` tests from `test-spark` job in GH CI as they are already covered by Azure CI
- Removes unnecesary bundle validation jobs and adds new bundle validation images (`flink1153hive313spark323`, `flink1162hive313spark331`)
- Updates `validate-release-candidate-bundles` jobs
- Moves functional tests of `hudi-spark-datasource/hudi-spark` from job 4 (3 hours) to job 2 (1 hour) in Azure CI to rebalance the finish time.
Improves CI and cuts finish time.
none
N/A
> [HUDI-7123] Improve CI scripts

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataTableColumnStatsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
This feature introduces a call procedure that allows users to specify the table name and column names to retrieve column stats information from the metadata table. This functionality facilitates the observation of data distribution status and assists in data skipping.
None
None
A procedure for show column stats information.
An example:
`call show_metadata_table_column_stats(table => 'tableName', targetColumns => 'column1,column2');`
Supports querying multiple columns simultaneously, separated by commas.
> [HUDI-7110] Add call procedure for show column stats information

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/AutoRecordGenWrapperAvroKeyGenerator.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/AutoRecordKeyGeneratorWrapper.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/AutoRecordGenWrapperKeyGenerator.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Fix partition key validation for custom payloads. Currently, deltastreamer is failing for custom payloads, since custom key generators since custom keygenerators require :<type> in writer configs, but the suffix is removed when storing in table properties.
NA
medium
> [HUDI-7052] Fix partition key validation for custom key generators.

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineServerHelper.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/HttpRequestClient.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestHoodieJavaWriteClientInsert.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
- hudi-common/pom.xml
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/dto/DTOUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/BaseFileHandler.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerDirState.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- pom.xml
- Allows users to reuse a running timeline server for other tables
- Minor performance improvements around object reuse and creation
- Use of AfterburnerModule where we saw a 22% increase in throughput for to/from json on the base file DTOs used in the timeline server
- Allows users to lower overhead when running multiple writers in the same JVM by reusing the underlying server instance
- Performance improvement in the json (de)serialization
low - feature for reusing the server is off by default …
> [HUDI-7112] Reuse existing timeline server and performance improvements

- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
Fixing instantiation of Hms Uri with HiveSync tool.
Updates how we handle HMS URIs so that we are able to handle multiple targets in the same multi-deltastreamer. We're currently setting the URIs in the hadoop configuration once and assuming that all HMS targets are the same. This change updates these assumptions so that we can handle a case where the user provides multiple targets by creating a copy of the configuration when there is a value already present in the hadoop configuration.
Fixes bug customer is experiencing when there are multiple HMS instances
none
- _Any …
> [HUDI-7097] Fixing instantiation of Hms Uri with HiveSync tool

- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubMessagesFetcher.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubQueueClient.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/gcs/TestPubsubMessagesFetcher.java
Scaling gcs event source to support consuming 1000 messages or more per round of ingestion to hudi. 
Scaling gcs event source to support consuming 1000 messages or more per round of ingestion to hudi. 
low.
> [HUDI-7086] Scaling gcs event source

- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SparkSampleWritesUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSparkSampleWritesUtils.java
We are doing multiple isEmpty calls , which can impact perf for non-empty but filtered rdds .
The way isEmpty is implemented ->
it checks in each job [1, 5, 25 , ...] partitions for non-empty untill it finds first non empty partition .
If there is filter applied in transformers/incremental sources then after filtering
we can have some partitions empty which can impact perf to find first non empty partition. 
perf improvement for filtered datasets .
low
- _Any new feature or user-facing change …
> [HUDI-7006] Reduce unnecessary is_empty rdd calls in StreamSync

- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/HoodieStreamerDatasetBulkInsertCommitActionExecutor.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
This PR fixes the bug which causes the `operationType` to be null in the commit metadata of bulk insert operation with row writer enabled in Hudi Streamer (`hoodie.datasource.write.row.writer.enable=true`).  `HoodieStreamerDatasetBulkInsertCommitActionExecutor` is updated so that `#preExecute` and `#afterExecute` should run the same logic as regular bulk insert operation without row writer.
The tests are updated to validate the logic.
Before this fix, the `operationType` is null in the commit metadata:
```
"operationType" : null
```
Fixes the bug.
low
N/A
> [HUDI-7139] Fix operation type for bulk insert with row writer in Hudi Streamer

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/ClusteringPlanStrategy.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/RocksDbBasedFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/util/RocksDBSchemaHelper.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
Mainly to solve the OOM when generating clean plan if there are too many partitions.
1. Clean allows grouping execution by setting cleanerParallelism.
2. After generating cleaning information for a partition, clean the metadata of that partition in TableFileSystemView.
ticket number here and follow …
> [HUDI-7041] Optimize the memory usage of timeline server for table service

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataTableColumnStatsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
https://github.com/apache/hudi/pull/10120
Improvement content:
1. Use the public method of obtaining column stats in the metadata table to acquire relevant content.
2. Simplify the implementation of some codes and remove meaningless and redundant codes.
3. Add handling of null values in type judgment to prevent the occurrence of NPE (NullPointerException).
4. Results can now be output in the order of column names.
5. The partition path can be matched with a prefix now.
None
None
None
> [HUDI-7110][FOLLOW-UP] Improve call procedure for show column stats information

- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
> [Minor] Fix the flaky tests in TestRemoteHoodieTableFileSystemView

- hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
Use the default value of `""` when there is no property set for the schema converter
Makes configuration easier for users trying to use default values
none
> [MINOR] Schema Converter should use default identity transform if not specified

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java
```
2023-11-27 19:39:20
java.io.IOException: Could not perform checkpoint 10 for operator Sink: bucket_write(table=hudi_xxxx_cdc) (60/192)#7.
at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1274)
at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointBarrierHandler.notifyCheckpoint(CheckpointBarrierHandler.java:147)
at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.triggerCheckpoint(SingleCheckpointBarrierHandler.java:287)
at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.access$100(SingleCheckpointBarrierHandler.java:64)
at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler$ControllerImpl.triggerGlobalCheckpoint(SingleCheckpoin …
```
> [HUDI-7147] Fix CDC write flush bug

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java
A potential problem: 
If the heartbeat client is updating the heartbeat time for the instant t1, then the write client completes the commit of the instant t1 and stops the heartbeat of the instant t1. 
At this time, the try-catch that updates the heartbeat will catch an exception: `File does not exist`. 
When handling this exception, we should check again whether the heartbeat of t1 instant has been stopped by the writing client. 
If it has been stopped, we should not throw this exception, but skip the update of this heartbeat directly. 
But if has not been stopped, we should throw an exception at this time.
NONE
NONE
NONE …
> [HUDI-7148] Add an additional fix to the potential thread insecurity problem of heartbeat client.

- hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
What have been changed:
1. Enabled time travel queries for MOR queries.
2. Changed the logic when a unqualified log block is met in order to keep merging log records.
TESTS:
Fixed failures for existing time travel query tests.
Time travel queries for MOR should work after these fixes.
Low
> [HUDI-7102] Fix a bug for time travel queries on MOR tables

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
when metric prefix length is 0 ignore the metric prefix
> [minor] when metric prefix length is 0 ignore the metric prefix

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/ActiveAction.java
Before modification:
Unable to directly determine the instant issue from the logs.
> [MINOR] Add log to print wrong number of instant metadata files

- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubMessagesFetcher.java
Fix the default for gcp pub sub max sync time to 1min for PR #10073
Fixing default for a new config introduced in master (not part of any release).
medium
> [HUDI-7086] Fix the default for gcp pub sub max sync time to 1min for PR #10073

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapRead.java
We enabled time travel queries for COW tables based on HadoopFsRelation, which uses FG reader file format, and fixed bugs related.  Changes include:
1. Enabled time travel queries for COW tables;
2. Moved file format object initialization from the constructor into a function to avoid the NULL file index error caused by lazy initialization.
3.  
Time travel queries should be more stable.
LOW since this is for 1.0.0.
> [HUDI-7103] Support time travel queies for COW tables

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieConversionUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
Two important fixes
Ensure ErrorTable class is serializable
Fix schema registry provider when schema converter class is NOT configured (Added UTs) - this fix was already done by PR https://github.com/apache/hudi/pull/10178
NA
Medium 
> [HUDI-7138] Fix error table writer and schema registry provider

- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteMetadataTableProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
follow up [HUDI-7128](https://issues.apache.org/jira/browse/HUDI-7128)，https://github.com/apache/hudi/pull/10148
DeleteMetadataTableProcedure need to support batch mode too
none
none
> [HUDI-7128][FOLLOW-UP] Support metadatadelete with batch mode

- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
- hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
Copies over the properties of the original schema when adding metadata fields. Adds test to assert this behavior.
Allows user defined properties to be carried through to the commit metadata
None, this is just metadata on the schema. We already had this behavior at the field level but also want it at the record level.
> [HUDI-7160] Copy over schema properties when adding Hudi Metadata fields

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
When using multi-writer, flink job may not close the failed instant's heartbeat that causing the lazy clean not process the corresponding commit.
none
low
> [HUDI-7165] Flink multi writer not close the failed instant heartbeat

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/CompletionTimeQueryView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/LSMTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ArchivedInstantReadSchemas.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/LSMTimelineReadBenchmark.scala
Add API for start time queries which will serve the completion time based incremental queries.
none
none
> [HUDI-7164] Add start time query API in CompletionTimeQueryView

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
Fixing range overflow with kakfa source and spark partition management
Pipeline will not fail with range overflow errors. 
low
> [HUDI-7153] Fixing range overflow with kakfa source and spark partition management

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceReadWithDeletes.java
Currently Spark would read the deleted data whose _hoodie_operation is D, which is unexpected.
See more detail in [HUDI-6217](https://issues.apache.org/jira/browse/HUDI-6217).
The pr aims to fix the bug.
None
None
> [HUDI-6217] Spark reads should skip record with delete operation metadata

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
When jobs throw exeption `org.apache.hudi.exception.HoodieException: unable to read next record from parquet file`, we do not deal with this exception. This results the job not failing and final state is success.
none
> [HUDI-7071] Throw exceptions when clustering/index job fail

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Fixing handling of empty batches with row writer and HoodieStreamer.  
HoodieStreamer should be able to handle empty batches w/o any NPEs hereafter. 
low
> [HUDI-7154] Fix NPE from empty batch with row writer enabled in Hudi Streamer

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordDelegate.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/model/TestHoodieRecordSerialization.scala
Similar to https://github.com/apache/hudi/pull/9114, corner case when a record moves from 1 partition to another with partition path update set to true
https://github.com/apache/hudi/blob/eab00d570fdc986d865b511cc0402069b4b9ce2b/hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java#L235-L242
1. Hbase index tagLocation is executed concurrently in different spark partitions, so the index delete operation may happen after index add operation, cause the undefined behavior as [codope](https://github.com/codope) said.
2. ReduceByKey can be a costly operation as https://github.com/apache/hudi/pull/9114#discussion_r1251177363 discussed
so add a flag to ignore this index delete operations in partitionPathUpdate condition
N/A
N/A
> [HUDI-6822] Fix deletes handling in hbase index when partition path is updated

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowColumnStatsOverlapProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
In HUDI-7110 , a tool has been made available to display column stats. However, this tool is not very user-friendly for manual observation when dealing with large data volumes. For instance, with tens of thousands of parquet files, the number of rows in column stats could be of the order of hundreds of thousands. This renders the data virtually unreadable to humans, necessitating further processing by code. Yet, if an administrator simply wishes to directly observe the data layout based on column stats under such circumstances, a more intuitive display tool is required. Here, we offer a tool that calculates the overlap degree of column stats based on partition and column name.
Overlap degree refers to the extent to which the min-max ranges of different files intersect with each other. …
> [HUDI-7166] Provide a Procedure to Calculate Column Stats Overlap Degree

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Fixing insert drop dups config interplay with insert overwrite operations. 
With insert overwrite write operations, does not make sense to honor drop dups config.
low
> [HUDI-7100] Fixing insert overwrite operations with drop dups config

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
Fixing closing of write client on failure scenarios
JVM will exit on all failure cases with spark writer
low
> [HUDI-6980] Fixing closing of write client on failure scenarios

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java
Previously we see the ConcurrentModificationException exception.
1. Make the test less flaky.
2. More robust in prod.
Low.
> [MINOR] Allow concurrent modification for heartbeat map

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/ActiveActionWithDetails.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/DummyActiveAction.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/ActiveAction.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
it’s a regression of HUDI-6539, while previously we support concurrent archiving, the concurrent archiving results in duplicates of instants but for audit purposes it still works, and our new file slicing also allows duplicates there.
The best solution is we guard the archiving with explicit lock, but for many production users, they do not config the lock with async separate table services there, so currently we just fallback to the old support. Might needs more discussion if we want to remove the duplicates(either the archiving timeline compaction takes over or the writer just do as single writer).
See an example we got multiple clean completed metadata file: 
none
none
- _The config …
> [HUDI-7172] Fix the timeline archiver to support concurrent writer

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCDCFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodiePartitionCDCFileGroupMapping.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
By using HadoopFsRelation.
Solved a bunch of bugs for CDC queries, including:
1. For non-partitioned tables, added virtual partition path;
2. Store data schema of underlying parquet files into the query options.
3. Fixed the way to initialize the meta client in the file format. 
4. Fixed the NULL file index problem by removing the file format initialization.
5. Fixed the ordering of CDCFileSplit returned from the CDCFileIndex.
6. Fixed the mapping between cdcSchema and requiredSchema.
Enables CDC queries to utilize HadoopFsRelation.
Low since we can turn it off.
> [HUDI-7125] Fix bugs for CDC queries

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerMetrics.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- Shutting down metrics for write client
- Shutting down deltastreamer in tests
Close resources properly
none
> [HUDI-6836] Shutting down deltastreamer in tests and shutting down metrics for write client

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableLikeCommand.scala
Create table should shutdown with exception when occur catalog sync error，when we create table failed with catalog，such as no privilege，should throw exception otherwise continue with warning
none
none
> [HUDI-7191] Create table should shutdown with exception when occur catalog sync error

- website/docs/quick-start-guide.md
- website/docs/sql_ddl.md
- website/versioned_docs/version-0.14.0/quick-start-guide.md
- website/versioned_docs/version-0.14.0/sql_ddl.md
Updated notes for SQL DDL and SQL Quickstart page to add more clarity.
If user is working on the tutorial locally and has a previous Spark-HMS integration and if they don't have a non-default database setup or if they don't provide `LOCATION` with DDL, they will face `java.io.IOException: Mkdirs failed to create file:/user/hive/warehouse/hudi_table/.hoodie` error.
Updated notes for SQL DDL and SQL Quickstart page to add more clarity.
MINOR
Update was to documentation.
- [NA] CI passed - CI runs after PR is raised.
> [MINOR][DOCS] updated notes for spark-hive integrated local environments

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
functional index doesn't work with unpartitioned table due to usage `new Path(basePath, partition + Path.SEPARATOR + filename);` with empty `partition` string
-
-
-
> [MINOR] Fix functional index for nonpartitioned table

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
Some of teh zk lock configs have defaults and so we should avoid checking for required props.
Some of teh zk lock configs have defaults and so we should avoid checking for required props.
low
> [MINOR] Relaxing required props with defaults

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Check the table type between hoodie.properies and table options
The commit and file of  hudi table is mixed, it caused problems when reading.
Use step:
(1) The `thoodie.table.type`  in hoodie.property is MERGE_ON_READ,  write data to the hudi table.
(2) Update the  table.type option to COPY_ON_WRITE in flink ddl, then write data to the hudi table.
(3) The commit and file of  hudi table is mixed, it caused problems when reading.
ticket number here and follow …
> [HUDI-7159]Check the table type between hoodie.properies and table options

- hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
Deleted the `base_path` we created when bootstrap failed.
`base_path` is always empty when we start bootstrap as we have checked in [BootstrapExecutorUtils](https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java)#initializeTable
Though we can still rerun bootstrap procedure and pass `bootstrap_overwrite` parameter, it's better to clean this path that we created after failure.
`run_bootstrap` spark procedure
low
none
> [HUDI-6012] Delete base path when failed to run bootstrap procedure

- hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/kafka/HoodieWriteCommitKafkaCallback.java
In call method from HoodieWriteCommitKafkaCallback in hudi-utilities module, the kafka send is async, how about to make the send to sync to ensure the kafka send call complete. No performance degradation, because the send call is in a try-with-resource.
Wait for the kafka send call response
None
None
> [HUDI-6094] make utilities kafka send call from async to sync

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
Fixing auto deletion of metadata table. Due to a bug, we are triggering deletion of mdt and updating hoodie.properties even if its already disabled and not present. Fixing it to trigger deletion only if its already enabled and new write config disables metadata table. There is no correctness issue, but a sub optimal code. 
Fixing auto deletion of metadata table.
low. …
> [HUDI-7206] Fixing auto deletion of mdt

- hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
If the incoming df is empty, the commit schema will be empty. Now, it will be the current table schema.
Currently if a user does an empty commit, we won't be able to detect invalid schema evolution in the next commit
low
N/A
> [HUDI-7201] Schema Evolution: use target schema if source is empty

- hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestShowPartitions.scala
`show partitions` sql can not return correct result in following two cases:
1. the dropped partitions should be displayed after they were recreated.
2. after `insert overwrite` a partitioned table, the partitions should be marked as `dropped`
bug fix.
None.
None.
> [HUDI-7171] Fix 'show partitions' not display rewritten partitions

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BulkInsertDataInternalWriterHelper.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieDatasetBulkInsertHelper.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Fixes #9991 
Issue:
There are two configs which when set in a certain manner throws exceptions or asserts
1. Configs to disable populating metadata fields (for each row)
2. Configs to drop partition columns (to save storage space) from a row
With 1 and 2 above, partition paths cannot be deduced using partition columns (as the partition columns are dropped higher up the stack. `BulkInsertDataInternalWriterHelper::write(...)` relied on metadata fields to extract partition path in such cases. But with only 1 it is not possible resulting in asserts/exceptions.
The fix is to push down the dropping of partition columns down the stack after partition path is computed. The fix manipulates the raw 'InternalRow' row structure by only copying the relevent fields into a new 'InternalRow' structure. …
> [HUDI-7040] Handle dropping of partition columns with populate meta fields disabled

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/index/TestHoodieIndexUtils.java
- hudi-spark-datasource/hudi-spark/pom.xml
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
With files and functional index, it should be possible to read the table from spark-sql attached to an external catalog, say remote Hive Metastore, even when the partition metadata is not syned to the catalog.
- Check whether partitions are passed to `HoodieCatalog`. If not, then use the metadata file system view to get the partitions.
- Add a test for querying a table without syncing partition metadata.
NOTE:  The change is in `HoodieCatalog` which is dependent on Spark 3.2. So, this feature is not available for Spark versions < 3.2.0. 
Query a table from spark-sql that is syned to catalog without the partition metadata. This means we can make meta sync faster and do away with heavy partition metadata.
medium
_Describe any necessary documentation update if there is any new feature, …
> [HUDI-7023] Support querying without syncing partition metadata to catalog

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java
The cleaning can happens concurrently in rare cases but it's actually unnecessary.
none
none
> [HUDI-7210] In CleanFunction#open, triggers the cleaning under option 'clean.async.enabled'

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
See the context in https://issues.apache.org/jira/browse/HUDI-7132, there is no need to clean the event by failure task signal, the events would be overridden when new events got received.
fix the potential data loss.
none
> [HUDI-7132] Data may be lost for flink task failure

- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/FileSystemTestUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/DataGenerationPlan.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileSliceTestUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
Our goal is to add a framework for unit tests at the level of file group reading. That is,
we don't need to involve any engine specific logic during the read, such that we could
1. Simplify the test process by providing unified and simple APIs,
2. Impose more granular read process for testing, and
3. Improve the test performance since no engine specific logic are involved.
We will add the framework step by step.
Steps:
1. Add a builder class to construct file group reader.
1. Simplify the process to construct file group reader level tests;
5. Improve the test performance by removing engine specific logic.
None.
> [HUDI-7176] Add file group reader test framework

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java
- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/utils/TestHoodieRealtimeInputFormatUtils.java
Describe context and summary for this change :
While using `HoodieParquetInputFormat` to read a partitioned hudi table from Flink we encountered below exception
```
at org.apache.hudi.hadoop.utils.HoodieRealtimeInputFormatUtils.addProjectionField(HoodieRealtimeInputFormatUtils.java:88)
at org.apache.hudi.hadoop.HoodieParquetInputFormat.getRecordReader(HoodieParquetInputFormat.java:90)
at org.apache.flink.api.java.hadoop.mapred.HadoopInputFormatBase.open(HadoopInputFormatBase.java:176)
at org.apache.flink.api.java.hadoop.mapred.HadoopInputFormatBase.open(HadoopInputFormatBase.java:58)
at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:84)
at …
```
> [MINOR] NPE fix while adding projection field & added its test cases

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
This PR is more about discussing with everyone how to fix the existing issues.
Assuming there are 4 instants in a Hudi table that need to be archived, with timestamps in ascending order (as they have been sorted after obtaining instantToArchive): these are 1.deltacommit, 2.deltacommit, 3.deltacommit, and 4.deltacommit, corresponding to the files a.parquet, b.parquet, c.parquet, and d.parquet, respectively.
In the archiving code, the deletion of instants is handled by the following code snippet:
```
if (!completedInstants.isEmpty()) {
    context.foreach(
        completedInstants,
        instant -> activeTimeline.deleteInstantFileIfExists(instant),
        Math.min(completedInstants.size(), config.getArchiveDeleteParallelism())
    );
}
```
Different instants are distributed across …
> [HUDI-7207] During archiving, complete instants are deleted serially to prevent data errors during data reads.

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwriteCommitActionExecutor.java
- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertOverwriteCommitActionExecutor.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
1. Refactor overwrite config deduce:
Record matching static partitions for static insert_overwrite operation;
Read replaced partition fileIds through write status for dynamic insert overwrite.
2. Reorder partition fields in hoodie table schema.
3. Add test cases for insert overwrite multiple partitioned table.
Fix the issue that static insert overwrite not work for multiple partitioned table.
low.
none.
> [HUDI-7183] Fix static insert overwrite partitions issue

- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestHarness.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
1. Use EmptyHoodieRecordPayload instead of HoodieEmptyRecord to represent a delete record.
2. Implement "projectRecord" function in reader context.
3. Fixe a bug in HoodieFileGroupReader.
4. Capsulate more logic into the framework to simplify test construction logic.
Facilitate test construction for file group reader.
LOW.
> [HUDI-7204] Improve fg reader test framework

- rfc/rfc-76/rfc-76.md
Adding RFC for auto record key generation. 
Will unblock more use-cases where users do not need to set any record keys.  
low. 
> [HUDI-4699] RFC for auto record key generation

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
- hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark35LegacyHoodieParquetFileFormat.scala
For Spark3.3+ version, we can do vectorized read for nested columns. However when
`spark.sql.parquet.enableNestedColumnVectorizedReader = true` and
`set spark.sql.parquet.enableVectorizedReader = true` is set, hudi will throw the following exception:
```text
Job aborted due to stage failure: Task 0 in stage 28.0 failed 1 times, most recent failure: Lost task 0.0 in stage 28.0 (TID 51) (30.221.100.176 executor driver): java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.UnsafeRow cannot be cast to org.apache.spark.sql.vectorized.ColumnarBatch
at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.next(DataSourceScanExec.scala:560)
at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.next(DataSourceScanExec.scala:549)
at …
```
> [HUDI-7190] Fix nested columns vectorized read for spark33+ legacy formats

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/parquet/TestHoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestSpark35RecordPositionMetadataColumn.scala
1. For Spark3.5, add row index (record position) column to the parquet file reader and file group reader. For <= Spark3.4, no such column is added.
2. For Spark3.5, enable record key related filters for positional merging; otherwise for <= Spark3.4.
3. For Spark3.5, read row index (record position) column out from the record. For <= Spark3.4, the position is generated from the positional record buffer.
1. Achieved the same filter pushdown functionality for both position and key based merging.
2. Made positional based merging more useful.
Low since we only enabled it for Spark3.5.
> [HUDI-7059] Hudi filter pushdown for positional merging

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
- hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
The [PR](https://github.com/apache/hudi/pull/9482) added a table schema update step for bigquery sync tool. It seems there're two issues (this PR focuses on the 1st one): 
1. When it reform the schema which is then compared to the bq table schema, the reformed schema puts partition fields in the beginning, while the bq table schema by default has partition fields at the end. So it unnecessarily triggers a schema update due to to order difference.
2. Though the sync tool for 0.14.0 does not support big lake connection id (there's a recent PR last month adding this support), a user can still recreate their table manually by adding connection id. The table update is adding the new schema into. external table definition. This does not work for biglake tables, and will cause error: "Schema can …
> [HUDI-7242] Avoid unnecessary bigquery table update when using sync tool

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Before modification： 
Make the Exception information more clearer .
> [MINOR] Merge logs into check instant file of HoodieActiveTimeline.transitionPendingState

- hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
fixes #10394
New dynamodb lock provider introduced in 0.14 fails to connect to http /https based dynamodb endpoint. It only works when no protocol is prepended , and only support https.
This fixes the issue
None
None
> [HUDI-7258] Fix dynamodb http endpoint

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/FileSystemBasedLockProvider.java
DataStream need in closeure in FileSystemBasedLockProvider
low
none
> [MINOR] DataStream need in closeure in FileSystemBasedLockProvider

- hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
Only validate the checksum if it exists.
Otherwise, some operations would throw exceptions. For example:
1. If a HUDI table was created with 0.10 Hudi version and read by 0.14.0, an `IllegalArgumentExeption` would be thrown out because checksum property doesn't exist in hoodie.properties.
2. Fail to upgrade a table created with 0.10 HUDI version using 0.14 version, an `IllegalArgumentExeption` would be thrown out because checksum property doesn't exist in hoodie.properties.
See more information in [issue#10404](https://github.com/apache/hudi/issues/10404).
None
None
None
> [HUDI-7262] Validate checksum only if it exists

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
Close compaction when using append mode
Unnecessary operations for StreamWriteOperatorCoordinator when using append mode. 
And it brought in the memory consumption of jobmanager container when scheduling compcation.
> [HUDI-7249][Close compaction when using append mode

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FileSystemRelation.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logcal/HoodieFileSystemViewTableValuedFunction.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark32PlusAnalysis.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/TableValuedFunctions.scala
Depends on [HUDI-7243]
A new TVF, `hudi_filesystem_view(...)` is added to support querying timeline through spark-sql. The information displayed is influenced by the 'fsview' command of hudi-cli
A new relation, `FileSystemRelation`, is added to transparently support this functionality. The relation implements buildScan(...) method of TableScan trait. It does not support filter or predicate push-down. Column filtering and predicate evaluation needs to be done by the execution layer. This seems reasonable for the initial implementation for this tool which is mainly going to be used as a debugging/introspection tool. The relation defines a fixed schema required to display basic file information of a given hudi table
A new TVF, `hudi_filesystem_view(...)` is added to support querying timeline …
> [HUDI-7261] TVF to query hudi table's filesystem state through spark-sql

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
If node path does not exist , we have to manually create it for zookeeper otherwise it fails to connect .
this patch fixes it  .
Catch KeeperException if node already exists for synchronous updates .  
Lock provider improvements
low
> [HUDI-7198]Create nested node path if does not exist for zookeeper.

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
…global conf
```
CREATE TABLE IF NOT EXISTS hudi_catalog.tmp.table
(
bb STRING,
dt STRING
)
PARTITIONED BY
(
dt
)
WITH
(
'connector' = 'hudi',
'path' = '',
'table.type' = 'COPY_ON_WRITE',
'write.operation' = 'insert',
'hoodie.datasource.write.recordkey.field' = 'dt',
'hoodie.parquet.max.file.size' = '536870912', -- 512M
'clustering.async.enabled' = 'true',
'clustering.schedule.enabled' = 'true',
'hoodie.clustering.async.max.commits' = '1000000',
'clustering.plan.strategy.small.file.limit' = '268435456', -- 256M
'clustering.plan.strategy.target.file.max.bytes' = '1610612736', -- 1.5G
'clustering.plan.partition.filter.mode' = 'RECENT_DAYS',
'clustering.plan.strategy.daybased.lookback.partitions' = '2',
'clustering.plan.strategy.daybased.skipfromlatest.partitions' = '0', …
```
> [HUDI-7271] copy a conf let following modification not to impact the global conf

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
This test was causing following tests to get stuck. Something to do with the lock provider maybe. After investigating for a couple hours I wasn't able to discover anything.  Created [HUDI-7275](https://issues.apache.org/jira/browse/HUDI-7275) to track.
Possibly the cause of some CI OOMs
none
N/A
> [MINOR] Disable org.apache.hudi.TestHoodieSparkSqlWriter#testInsertDatasetWithTimelineTimezoneUTC

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/ExecutorFactory.java
- hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryExecutor.java
- hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryQueue.java
When writing data with BoundedInMemoryQueue, the size of record is sampled periodically and BoundedInMemoryQueue is adjusted dynamically during runtime. Prior to this PR, the sampling rate is fixed and not configurable.
As I tested, about 9% CPU is used to estimate the object size to calculate the queue size. 
Currently the sampling rate is set to 64. If we can set the rate to 128, then we can save 4.5% CPU theoretically.
Note: Increasing sampling rate has diminishing returns beyond a certain threshold depending on record layout/schema.
improve performance by setting higher sampling rate
low 
- Add a new configuration named `hoodie.write.buffer.record.sampling.rate`, default 64. Higher value leads to lower CPU usage for object size estimation.
- Add a new config named …
> [HUDI-7279] make sampling rate configurable for BOUNDED_IN_MEMORY executor type

- hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/FilebasedSchemaProvider.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaProvider.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
Fixing refreshing of schemas in HoodieStreamer continuous mode.
Fixing refreshing of schemas in HoodieStreamer continuous mode. 
With FileBased schema provide one has to shutdown and restart deltstreamer if schema is changed. So we are fixing this as part of this patch. 
Wrt Schema registry based schema provider, everytime we call getSourceSchema, we make remote calls and fetch real time schema. If a pipeline has N transformers, chances are that each transformer could be operating w/ a diff schema. So, with caching and explicit refresh calls, we are ensuring for an entire write, only one source and target schema will be in play. 
low
- _The config description must be updated if new …
> [HUDI-5973] Fixing refreshing of schemas in HoodieStreamer continuous mode

- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Fixed unit test in TestJavaHoodieBackedMetadata, and TestHoodieDeltaStreamer.
Fixed unit tests.
Low.
> [MINOR] Fixed unit tests

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Differentiate between replace commits that are cluster and those that are not
streamer won't get stuck
low 
N/A
> [HUDI-7284] stream sync doesn't differentiate replace commits

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToFiveUpgradeHandler.java
When upgrade a nonPartitionedTable which created by 0.10/0.11 HUDI version, an `ArrayIndexOutOfBoundsException` would throw out.
Because the hoodie.table.partition.fields is empty in hoodie.properties. BTW, the empty config would be filtered out from hoodie.properties file since 0.12 version by [PR#6821](https://github.com/apache/hudi/pull/6821)
The pr aims to fix the minor bug.
None
None …
> [HUDI-7288] Fix ArrayIndexOutOfBoundsException when upgrade unPartitionedTable created by 0.10/0.11 HUDI version

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
_For insert type tables, we do not need to use keyby to distribute inputsplit to avoid data skewing issues with the split reader operator._
_none._
_none._
_none_
> [HUDI-7293]Incremental read of insert table using rebalance strategy

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/configuration/TestOptionsResolver.java
The OptionsResolver#getIndexType function convert to uppercase after obtaining index.type parameter
If the index. type parameter in Flink options is lowercase, an exception will be thrown that cannot be converted to HoodieIndex
Low
N/A
> [HUDI-7286]flink get hudi index type ignore case sensitive.

- pom.xml
After we set this parameter, the surefire will try to ping the forked JVM after the timeout.
If not set this parameter, surefire will rely on os to handle the orphan processes.
Low.
Low.
> [HUDI-6092] Set the timeout for the forked JVM for tests

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
These default Hadoop configurations are not used in Hudi tests.
The runtime of tests based on these Hadoop configurations should be reduced.
Low.
> [MINOR] Clean default Hadoop configuration values in tests

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
- hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
[MINOR] Handle parsing of all zero timestamps with MDT suffixes.
MDT uses an all zero timestamp if there are no exiting commits on the dataset. If additional indexes are initialized, they will use a suffix (001, 002 ..) on the all zero timestamp. This timestamp is a special case and should be not raise parse exception.
Prevents date parse exception when MDT and/or indexes are enabled on an empty dataset.
None
None
> [MINOR] Handle parsing of all zero timestamps with MDT suffixes.

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logcal/HoodieMetadataTableValuedFunction.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark32PlusAnalysis.scala
- hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/TableValuedFunctions.scala
Adds a TVF function to query hudi metadata through spark-sql. Since the metadata is already a MOR table, it simply creates a 'snapshot' on a MOR relation. Could not find any way to format (or filter) the RDD generated by the MOR snapshot relation. Uploading the PR to get some feedback.
Adds a TVF function to query hudi metadata through spark-sql. Since the metadata is already a MOR table, it simply creates a 'snapshot' on a MOR relation. Could not find any way to format (or filter) the RDD generated by the MOR snapshot relation. Uploading the PR to get some feedback.
A new TVF is exposed to the user
low
none
> [HUDI-7294] TVF to query hudi metadata

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
In the current implementation of data skipping, column statistics for the entire table are read and then subjected to data skipping filtering operations based on these stats. When the table has a large volume of data and a high number of partitions, this approach can reduce the efficiency of data skipping, as partition pruning conditions are not utilized.
By pushing down the conditions for partition filtering to after the column statistics are read and applying pruning at that point, the size of the column stats that are subsequently involved in data skipping will be significantly reduced. This not only saves time on later computations but also conserves memory.
During a test conducted on a table with a total of 25TB distributed across 60 subpartitions, a query was performed on one of the …
> [HUDI-7291] Pushing Down Partition Pruning Conditions to Column Stats Earlier During Data Skipping

- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapRead.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
testBootstrapRead and TestHoodieDeltaStreamerSchemaEvolutionQuick have many combinations of params. While it is good to test everything, there are lots of code paths that have extensive duplicate testing. Reduce the number of tests while still maintaining code coverage
faster CI
low
N/A
> [HUDI-7296] Reduce CI Time by Minimizing Duplicate Code Coverage in Tests

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogUtil.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/TableOptionProperties.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolutionBySQL.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolutionBySQLWithDFSCatalog.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolutionBySQLWithHMSCatalog.java
Since Flink 1.17, Flink SQL support more advanced alter table syntax.
```
-- add a new column 
ALTER TABLE MyTable ADD category_id STRING COMMENT 'identifier of the category';
-- modify a column type, comment and position
ALTER TABLE MyTable MODIFY measurement double COMMENT 'unit is bytes per second' AFTER `id`;
-- drop columns
ALTER TABLE MyTable DROP (col1, col2, col3);
-- rename column
ALTER TABLE MyTable RENAME request_body TO payload;
```
Find more detail information in [Flink Alter Table SQL ](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/table/sql/alter/).
We could support schema evolution by Flink SQL.
The [last pr](https://github.com/apache/hudi/pull/10426) supported it based on `HoodieHiveCatalog`.
This pr aims to support schema evolution based on …
> [HUDI-7270] Support schema evolution by Flink SQL using HoodieCatalog

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDataSkippingQuery.scala
In the current code version, support for column stats has not yet been extended to handle complex nested data types, such as map-type data structures. Take the table tbl as an example, which is defined with three fields: an integer field id, a string field name, and a map-type field attributes. Within this table structure, the id and name fields support column stats, and as such, HUDI will generate the corresponding column stats indices for these two fields at the time of table creation. However, no corresponding index will be generated for the attributes field. The specific table creation statement is as follows:
```
create table tbl (
id int,
name string,
attributes map<string, string>
) ...
```
To elaborate further, consider the following insert operation:
```
insert into tbl values …
```
> [HUDI-7246] Fix Data Skipping Issue: No Results When Query Conditions Involve Both Columns with and without Column Stats

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParsePartitionUtil.scala
Fix cast exception for byte/short/float partitioned field. Now we may support all type except nested columns.
Add support for reading  byte/short/float partitioned field. 
NONE
NONE
> [HUDI-7305] Fix cast exception for byte/short/float partitioned field

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Currently Hudi is not check index type when create table，even when user set inaccurate index name is passed when set absent value. such as:
create table ${targetTable} (
`id` string,
`name` string,
`dt` bigint,
`day` STRING,
`hour` INT
) using hudi
OPTIONS ('hoodie.datasource.write.hive_style_partitioning' 'false', 'hoodie.datasource.meta.sync.enable' 'false', 'hoodie.datasource.hive_sync.enable' 'false')
'primaryKey' = 'id',
'type' = 'mor',
'preCombineField'='dt',
'hoodie.index.type' = 'BUCKET_XXX',
'hoodie.bucket.index.hash.field' = 'id',
'hoodie.bucket.index.num.buckets'=512
)
partitioned by (`day`,`hour`)
Need fix it with check
low
low
- _The config description must …
> [HUDI-7314] Hudi Create table support index type check

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
In HUDI-7291, I applied the partition pruning conditions to the column stats earlier, reducing the amount of data during the data skipping process. However, for non-partitioned tables, or partitioned tables where the query does not involve partition conditions, this optimization introduces additional unnecessary serialization overhead. Therefore, a check has been added here to avoid filtering in such cases.
None
None
None
None
> [HUDI-7310] Optimize Column Stats Partition Pruning for Non-Partition Pruning Queries

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/CommonOptionUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSource.scala
Removed unnecessary test combinations, reduced combinations of parameterized tests
Reduced task parallelism for Spark from 4 to 2.
Reduction in azure CI job 3 runtime
none
None
> [MINOR] Reduce UT spark-datasource test times

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/ExpressionPredicates.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ImplicitTypeConverter.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestExpressionPredicates.java
Support literal type auto conversion for filter push down.
For example:
Given the field d_date with type of date, and then execute the SQL below:
select ... where d_date = '2024-01-01';
It will convert string literal '2024-01-01' to integer (epoch day) and then push down to parquet filter.
This patch is after HUDI-7303, which fixed the problem: value with date type will be unexpectedly converted to Long.
Low impact.
Low risk.
No need for documentation.
> [HUDI-7311] Add implicit literal type conversion before filter push down

- website/src/components/EventFeature/styles.module.css
For some reason, the button on the localhost and on prod are 2 different things- I updated the width to see if it changes join now on 1 line 
Below is the image of what is looks like in the hudi site and what I see on local host: 
@xushiyan @bhasudha
> updated button size so join now is on one line

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCDCDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCommandBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCorruptBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
Fix eager closure of log reader input streams with log record reader. While reading log blocks, we do make sure to close the actual content and release it for GC purposes. But the inputstream instantiated with log record reader is not closed. Fixing the same in this patch. 
Fix eager closure of log reader input streams with log record reader. Memory usage when reading 100+ log files will be reduced to minimal. 
Memory snapshot before this patch:
25 log files/25 log blocks were present in the file slice of interest. 
Notice 25 instances of input streams open. 
Memory snapshot after this patch. 
Dump taken just after reading all log block headers, but before starting to deser any block for records. 
_Describe any …
> [HUDI-7228] Fix eager closure of log reader input streams with log record reader

- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/ChainedTransformer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/ErrorTableAwareChainedTransformer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestChainedTransformer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestErrorTableAwareChainedTransformer.java
Updates the `Transformer` classes to take in a `Supplier<Option<Schema>>` instead of `Option<Schema>` so that the latest value can be used when the `transformedSchema` method is called.
- Provides more accurate schema
- Lazy evaluation of the schema also avoids an extra call to schema registries and potential exceptions that come with that
None, this code is not actively used …
> [HUDI-7323] Use a schema supplier instead of a static value

- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
hoodie.write.handle.missing.cols.with.lossless.type.promotion does not work with HoodieIncrSource unless meta cols are dropped. Now, we remove the meta cols in getDeducedSchemaProvider.
Most spark datasource cases are not impacted because we [drop the meta cols earlier in SparkSqlWriter](https://github.com/apache/hudi/blob/a83f7c038368f93ab41cda9273add9132c7bf7be/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala#L348)
allow hoodie.write.handle.missing.cols.with.lossless.type.promotion to be used with HoodieIncrSource even when meta cols aren't dropped
low
N/A
> [HUDI-7327] remove meta cols from incoming schema in stream sync

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/InProcessLockProviderWithRuntimeError.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestTransactionManager.java
- Add a new flag to `org.apache.hudi.client.transaction.lock.LockManager` , that is set once the HoodieLockMetrics lock duration timer had started, and is unset after said timer has been ended. This flag is used to prevent closing the lock duration timer if it has not already been started
- This is needed to avoid the scenario in https://issues.apache.org/jira/browse/HUDI-7308 , where if an exception is raised while LockManager tries to acquire lock of LockProvider, and the caller then directly calls LockManager::close (in order to ensure lock is released for other users) , another exception ``HoodieException("Timer was not started")`  will be thrown, which may "suppress" the original exception encountered when LockManager tried to acquire lock.  
- This should allow users to easily …
> [HUDI-7308] LockManager::unlock should not call updateLockHeldTimerMetrics if lockDurationTimer has not been started

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
https://issues.apache.org/jira/browse/HUDI-6941 Aim to judge number of task in query job，but is not accurate to get number of tasks，need add a SparkListener to check task numbers exactly
error is:
expect is:
test is:
none
none
> [MINOR] Fix UT error in HUDI-6941 with stage task numbers

- hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Turns out the pushdown feature `hoodie.datasource.hive_sync.filter_pushdown_enabled` can't work on glue due to missing implementation to retrieve schema.
This provide an implementation and makes glue sync benefit from this feature.
This fixes #10569
No impact
No risk
> [HUDI-7351] Hive-sync partition pushdown does not work with glue

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
- hudi-common/src/main/java/org/apache/hudi/common/util/BaseFileUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
This PR refactors the logic of writing partition metadata by using BaseFileUtils to hide format-specific logic in HoodiePartitionMetadata.
This is part of the effort to provide Hudi storage abstraction and decouple `hudi-common` from hadoop dependencies. For reference, the single big-change PR can be found here: #10360.
No behavior change.  The refactoring changes are covered by existing tests in `TestHoodiePartitionMetadata`.
none
N/A
> [HUDI-7342] Use BaseFileUtils to hide format-specific logic in HoodiePartitionMetadata

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/HoodieWriterClientTestHarness.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestConsistentBucketIndex.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestDataValidationCheckForLogCompactionActions.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieKeyLocationFetchHandle.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/ClusteringTestUtils.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkSortAndSizeClustering.java
By bisecting the tests of Hadoop-mr and java client modules, we figure out a couple of flaky tests.
After carefully profiling one of these tests, we realized that a rocksdb thread was running after all tests finished.
Then we disabled the explicit usage of EMBEDDED_KV_STORE, which is backed by rocksdb and ran the test for 10s of times to confirm that the timeout issue did not happen again.
We may need to debug further, but we can disable the EMBEDDED_KV_STORE based FSV for now.
Better CIs.
None.
> [HUDI-7334] Remove EMBEDDED_KV_STORE based FSV usage in tests

- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
- hudi-io/src/main/java/org/apache/hudi/common/util/ComparableVersion.java
- hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
- hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
As above.  `ComparableVersion` class is copied from`org.apache.hadoop.util.ComparableVersion` to avoid Hadoop dependency.
This is part of the effort to provide Hudi storage abstraction and decouple `hudi-common` from hadoop dependencies. For reference, the single big-change PR can be found here: #10360.
No behavior change.  This PR reduces the dependency on `org.apache.hadoop` classes.
none
N/A
> [HUDI-7345] Remove usage of org.apache.hadoop.util.VersionUtil

- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordSizeEstimator.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestUtils.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
should use the spillable map instead.
> [HUDI-7340] Use spillable map for cached log records in HoodieBaseFileGroupRecordBuffer

- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCDCDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCommandBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCorruptBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopSeekableDataInputStream.java
- hudi-io/src/main/java/org/apache/hudi/io/SeekableDataInputStream.java
This PR introduces `SeekableDataInputStream` for random access on a file, i.e., seeking to a position in a file and reading the content.  The random access on a file is used by the log scanner and reader.  Before this PR, the log reader relies on `FSDataInputStream` which is coupled with Hadoop file system.  To allow Hadoop-independent file systems to be used to read log files, the interface `SeekableDataInputStream` is introduced to provide random access APIs without relying on `FSDataInputStream`.
`HadoopSeekableDataInputStream` implements `SeekableDataInputStream` with `FSDataInputStream` instance and is used to realize the same logic as before (no behavior change).
This is part of the effort to provide Hudi storage abstraction and decouple `hudi-common` from hadoop dependencies. For …
> [HUDI-7347] Introduce SeekableDataInputStream for random access

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
I try to upgrade my hudi version, but it does not work, then i find org.apache.hudi.common.model.HoodieRecord does not 
have a serialVersionUID
high
when  user try to upgrade hudi, they will get the same error
Documentation Update
N/A
@yuzhaojing
> [MINOR]  Add serialVersionUID to HoodieRecord class

- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
We fix the time format for the timestamp. Previously, the Timestamp.toString() function prints nano seconds, which is not included in the actual output.
Less flaky test.
No.
> [HUDI-7365] Fix a flaky test for timestamp output format

- hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
The underlying reason is that in Hive 2.x version, the string format of the TimestampWritable depends on the length of the underlying timestamp. I.e., the string format can be any one of the following, depending on how many nano seconds the time has. 
yyyy-MM-dd HH:mm:ss
yyyy-MM-dd HH:mm:ss.S
yyyy-MM-dd HH:mm:ss.SS
yyyy-MM-dd HH:mm:ss.SSS
In order to make the comparison stable, we harden the string format.
Less flaky.
None.
> [HUDI-6902] Fix string format of the timestamp in a test

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
change getLastPendingClusterCommit to getLastPendingClusterInstant
because it's not a commit if it's pending
reduce dev confusion
none
N/A
> [HUDI-7284] Fix bad method name getLastPendingClusterCommit to getLastPendingClusterInstant

- hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Which is caused by issues from underlying MiniHDFS.
We should target to fix the root cause; disable the method for now.
Unblock CI tests.
Low.
> [HUDI-7375] Disable a test method failure caused by MiniHdfs

- hudi-io/src/main/java/org/apache/hudi/storage/HoodieLocation.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieLocation.java
This PR fixes HoodieLocation with encoded paths, e.g., `s3://foo/bar/1%2F2%2F3`, which should be kept as is.
New tests are added.  The tests pass now whereas they failed without the fix before.
Bug fix.
low
N/A
> [HUDI-7366] Fix HoodieLocation with encoded paths

- pom.xml
Bump version of Jetty ,HBase ,and pulsar-client
None
None
N/A
> [HUDI-7338] Upgrade Jetty, HBase, and pulsar-client

- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
- hudi-io/src/main/java/org/apache/hudi/storage/HoodieLocation.java
- hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieLocation.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
This PR makes the following changes to properly support qualified location:
- Adds `getUri` to `HoodieStorage`.
- Adds `makeQualified` to `HoodieLocation`.
- Adds `makeQualified` to `FSUtils`.
- New tests for the functionality.
Properly support qualified location with `HoodieStorage` and `HoodieLocation`.  This fixes the original test failures in #10591.
none
N/A
> [HUDI-7367] Add makeQualified APIs

- hudi-aws/pom.xml
- hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
- hudi-aws/src/test/java/org/apache/hudi/aws/sync/ITTestGluePartitionPushdown.java
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
After few days in production it turns out glue has a hard limit of expression (= 2048 chars). This patch handle this case, by fallback to returning all existing partitions.
Also the documentation was wrong about the pushdown max size. Fixed it and added a test case
None
None
> [HUDI-7351] Handle case when glue expression larger than 2048 limit

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
Please refer to the JIRA [HUDI-7392](https://issues.apache.org/jira/browse/HUDI-7392) for more details on this issue and how to reproduce it.
No lingering CLOSE_WAIT connections after this fix
None
No documentation update require
> [HUDI-7392] Fix connection leak causing lingering CLOSE_WAIT

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
hoodie.write.set.null.for.missing.columns was renamed to 
hoodie.write.handle.missing.cols.with.lossless.type.promotion. The config only adds the missing columns. The "reverse type promotion" is not controlled by a config.
Prevent config key change in next release
none
https://github.com/apache/hudi/pull/10612
> [HUDI-7373] revert config hoodie.write.handle.missing.cols.with.lossless.type.promotion

- .github/workflows/bot.yml
- Dockerfile
- azure-pipelines-20230430.yml
- hudi-platform-service/hudi-metaserver/hudi-metaserver-server/pom.xml
- pom.xml
The reason for this change is that 4th module of Azure CI could fail non-deterministically, and our best guess is that this module is somehow correlated with other modules, e.g., folders. Before we have bandwidth to root cause it, we decide to containerize Azure CI to rule out the possibility of module correlation.
In details, 
1. We created a base docker image named "apachehudi_azure_ci_base" and push it to apachehudi docker hub repo.
2. For each Azure CI module, we build a image by copying the hudi repo with the PR changes into the base image.
3. For each Azure CI module, we run the build-and-test command in both UT and FT tests. The idea steps should be build-testUT-testFT; however, it is hard to make the container keeps the file changes in the build step after switch to the following …
> [HUDI-6902] Containerize the Azure CI

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieClusteringJob.java
- Adding support to purge pending clustering instant. 
If a user made some mistake on clustering params and wishes to completely purge a pending clustering, we do not have any support for that. Adding support to purge a pending clustering and rolling it back fully. 
low.
> [HUDI-7397] Adding support to purge pending clustering instant

- packaging/hudi-aws-bundle/pom.xml
Exclude jackson-module-afterburner from hudi-aws module which has not relocated the jackson-databind and conflicts with hudi-flink-bundle.
Fixes Flink Hudi Table write issue.
none
NA
> [HUDI-7379] Exclude jackson-module-afterburner from hudi-aws module

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
This regression was introduced during refactoring, where we were not fetching the create and upsert times from the merge handle and only scan time was being set by the HoodieCompactor.
No change in public APIs
low
> [HUDI-7381] Fix compaction write stats and metrics for create and upsert time

- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlFileBasedSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractDFSSourceTestBase.java
Tests in hudi-utilities module cause serious flaky failures for Azure CI tests.
This is one of the steps that we try to stabilize the Azure CI test.
Removing one of the sources of instabilities.
None.
> [MINOR] Disable hdfs for hudi-utilities tests

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestMetadataConversionUtils.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
- hudi-common/src/main/avro/HoodieCleanMetadata.avsc
- hudi-common/src/main/avro/HoodieCleanerPlan.avsc
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanPlanV1MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanPlanV2MigrationHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
There are chances that incremental cleaner might miss to clean up some partitions which was part of previously savepointed commit. This patch fixes the gap. 
- Each Clean commit metadata is going to track the list of savepoints as of its planning. Subsequent clean planner, will find any savepoints that was deleted and include the partitions during planning that was part of them. 
Incremental cleaner will not miss to clean up older partitions which was touched by a recently removed savepoint but is not updated with regular writes. 
low
- _Any new feature or user-facing …
> [HUDI-7104] Fixing cleaner savepoint interplay to fix edge case with incremental cleaning

- hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
- hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemWithHFileReader.java
- hudi-io/src/main/java/org/apache/hudi/io/ByteArraySeekableDataInputStream.java
- hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileBlockReader.java
- hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileReaderImpl.java
- hudi-io/src/test/java/org/apache/hudi/io/hfile/TestHFileReader.java
This PR makes SeekableDataInputStream as the input of native HFile reader, so that the constructor of the native HFile reader is Hadoop-agnostic.
This is part of the effort to provide Hudi storage abstraction and decouple `hudi-common` from hadoop dependencies. For reference, the single big-change PR can be found here: #10360.
The constructor of the native HFile reader is Hadoop-agnostic.
none
N/A
> [HUDI-7410] Use SeekableDataInputStream as the input of native HFile reader

- hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestDFSHoodieTestSuiteWriterAdapter.java
- hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestFileDeltaInputWriter.java
- hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
- hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSAvroDeltaInputReader.java
- hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSHoodieDatasetInputReader.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/callback/TestKafkaCallbackProvider.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestFilebasedSchemaProvider.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlFileBasedSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestAbstractDebeziumSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractCloudObjectsSourceTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlFileBasedTransformer.java
`KafkaTestUtils` was created as a static variable and only initialized at the start of a test class.
A test class may contain multiple test methods. If the zookeeper session expires during the middle,
some test methods would fail. And we did see these failures happened in Azure CI.
To solve this problem, we recreated the `KafkaTestUtils` object for each test method instead.
Fix the session expiration error.
None.
> [MINOR] Fix zookeeper session expiration bug

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
This aligns with the doc change here: [10680]( https://github.com/apache/hudi/pull/10680)
Minor docs update.
Minor docs update.
none
> [MINOR][DOCS] Clarify config descriptions

- hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
Cleaning up `FileSystemViewManager#createViewManager` related code  that is passing around a `SerializableConfiguration` (HadoopConf) that is never used.
Added a doctstring to indicate that in `#init` function in `HoodieTableFileSystemView` is used for tests.
None
None
None
> [MINOR] Cleanup FileSystemViewManager code

- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
<html>
<body>
<p>OLAP query need support read data from origin table by default，for example，query from olap engine such as starrocks presto，we can only read data in ro/rt sub table and get empty data from origin table，this is not fitable：</p>
<p>query mor table with starrocks as:</p>
<p>MySQL <span class="error">[(none)]</span>&gt; select * from hudi_catalog_01.hudi_test.test_mor_hudi_22_rt;</p>
<div class="table-wrap">
_hoodie_commit_time | _hoodie_commit_seqno | _hoodie_record_key | _hoodie_partition_path | _hoodie_file_name
-- | -- | -- | -- | --
20230522100703567 | 20230522100703567_0_0 | 1 | partition=de | f14492ed-b672-4f60-8e86-6359790feb2a-0_0-17-2013_20230522101 row in set (2.11 sec)
</div>
<p>MySQL <span class="error">[(none)]</span>&gt; select * from …
> [HUDI-7415] Support OLAP engine query from origin table avoid empty result in default

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
We have support for filter the input files based on an extension (custom) for GCS Incr Source that can be configured. But we don't have the same for the S3 incr source (which always assumes that file extension is same as the format which may not be the case always).
Low impact
Low
> [HUDI-7418] Add file extension filter for s3 incr source

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Support table type name incase-sensitive when create table in sparksql.
When many user create table would set table.type = MOR/Mor/Cow/COW according to Hudi document，like：
CREATE TABLE `hudi_test`.`hudi_test29` (
  `app_id` STRING COMMENT '应用id',
  `message_id` STRING COMMENT '消息id',
  `dt` INT,
  `from` STRING,
  `day` STRING COMMENT '日期分区',
  `hour` INT COMMENT '小时分区'
)using hudi
  'primaryKey' = 'app_id,message_id',
  'type' = 'MOR',
  'preCombineField'='dt',
  'hoodie.index.type' = 'BUCKET',
  'hoodie.bucket.index.hash.field' = 'app_id,message_id',
  'hoodie.bucket.index.num.buckets'=256,
  'hoodie.datasource.hive_sync.table.strategy'='RT'
)
PARTITIONED BY (`day`,`hour`);
it would occur error as: 
java.lang.IllegalArgumentException: No enum constant …
> [HUDI-7423] Support table type name incase-sensitive when create table in sparksql

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudDataFetcher.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/GcsObjectMetadataFetcher.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
The logic to retrieve the data file format is duplicated across both sources, in S3 source we are handling the new config change properly but we are not doing it for GCS, moved it to a common class to reduce the duplicate code blocks. 
Refactored the generateFilter methods to public static methods for S3/GCS sources for ease of access. 
No impact to existing code, refactored code to remove duplicate logic.
Low
None.
> [HUDI-7416] Remove duplicate code for getFileFormat and Refactor filter methods for S3/GCS sources

- website/docs/schema_evolution.md
- website/versioned_docs/version-0.14.1/schema_evolution.md
hoodie.write.set.null.for.missing.columns was renamed to
hoodie.write.handle.missing.cols.with.lossless.type.promotion. The config only adds the missing columns. The "reverse type promotion" is not controlled by a config. Additionally, this commit never made it to the release, so hoodie.write.handle.missing.cols.with.lossless.type.promotion will not work, only hoodie.write.set.null.for.missing.columns .
Users can get the correct config
none
N/A
> [HUDI-7373] Make schema evolution doc and config correct

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Prefix HiveConf properties to Hoodie catalog properties map with '.hadoop', so that properties defined in hive-site.xml get used.
none
none
> [HUDI-6774] Prefix HiveConf props to Hoodie catalog properties map with '.hadoop'

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
This PR adds the time unit of the meta sync latency to the logs so it's easier to read.
Improves log readability.
none
N/A
> [HUDI-7427] Improve meta sync latency logging

- hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
- hudi-io/src/main/java/org/apache/hudi/storage/StorageSchemes.java
Currently Hudi not support NOS（Netease Object Storage），so add protocol to support it. https://issues.apache.org/jira/browse/HUDI-7428
none
none
> [HUDI-7428] Support Netease Object Storage protocol for Hudi

- packaging/hudi-flink-bundle/pom.xml
Remove shaded of codahale metrics in flink bundle
See https://github.com/apache/hudi/pull/9118#issuecomment-1926124497
We need to remove shaded of com.codahale.metrics to register metrics to flink. This change was tested in inner version.
Remove shaded of codahale metrics in flink bundle, now we can register write metrics to flink correctly.
low
NONE
> [HUDI-7435] Remove shaded of codahale metrics in flink bundle

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestComplexKeyGenerator.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestGlobalDeleteRecordGenerator.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestNonpartitionedKeyGenerator.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala
Some Key generators are creating excessive objects during recordKey/partitionPath computation to cut off last character from them (as methods getRecordKey, getRecordPartitionPath in KeyGenUtils utilize deleteCharAt).
Removed usage of deleteCharAt, replaced string concatenation with StringBuilder.append()  
Also with this fix now correct exception is thrown in case of keyIsNullEmpty: before - the StringIndexOutOfBoundsException was thrown on `recordKey.deleteCharAt(recordKey.length() - 1);` when recordKey is empty, now - HoodieKeyException is thrown.
none
none
- _Any new …
> [HUDI-7432] Fix excessive object creation in KeyGenUtils

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
Pick necessary bug fix to 0.x release
https://github.com/apache/hudi/pull/10325
None
None
None
None
> [HUDI-7207] Sequentially delete complete instant files in archival to prevent inconsistency during data reads

- .github/workflows/azure_ci_check.yml
This PR adds the GitHub action to check Azure CI report.  The action fails if Azure CI does not pass.
The action checks the last `hudi-bot` comment to look for the Azure CI report on the latest commit of the PR.
In case the check blocks merging unnecessarily, e.g., for hotfix, you can add this magic phrase, `HOTFIX: SKIP AZURE CI`, in the PR description to skip the Azure CI report check.
Enforces Azure CI check.
none
N/A
> [HUDI-7438] Add GitHub action to check Azure CI report

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriterUtc.scala
Fixed disabled TestHoodieSparkSqlWriter#testInsertDatasetWithTimelineTimezoneUTC by moving it in a separate class.
The problem is in the value of static HoodieInstantTimeGenerator.lastInstantTime in the heap.
If we run some tests with HoodieTimelineTimeZone.LOCAL and our local time is greater than UTC+0,
then some instant time will be saved in the heap. And if we try after to run any test with HoodieTimelineTimeZone.UTC, it will lead to the infinite loop in HoodieInstantTimeGenerator.createNewInstantTime(), where we compare old and new instant times.
The old value will be used from the previous test run from the heap.
No impact.
None.
No need.
> [HUDI-7275] Separate use of HoodieTimelineTimeZone.UTC and LOCAL in tests to prevent infinite loops

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeRecordReaderUtils.java
- Avro 1.10 throws ```AvroRuntimeException``` when field is not present in the schema. 
- Since reader schema doesn't contain all fields present in the table. This causes exceptions to be thrown for all fields which are not present in the schema.
- To fix, Verify the field before trying to fetch the value
- Catching exception and printing log introduces performance impact for MoR RT tables 
- SELECT query on 3TB TPCDS RT Table with ~40 columns and 10K row updates
- took ```429739 ms```
- with fix ```20689 ms```
_low_
_N/A_
> [HUDI-7440] Verify field exist in schema before fetching the value

- hudi-common/src/main/java/org/apache/hudi/common/data/HoodieBaseListData.java
- hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListData.java
There is an obvious logical error in HoodieBaseListData.isEmpty(). When the internal data structure is Stream<T>, there is a logical error in determining whether it is empty.
none
none
none
> Fix a bug in the HoodieBaseListData.isEmpty() empty-check logic

- .github/workflows/azure_ci_check.yml
This PR adds the write permission of commit statuses in the GitHub action of  Azure CI check, to test if the permission is allowed on master for `issue_comment` events.  The PR has to be landed on master for validation.
none
none
N/A
> [HUDI-7438] Add write permission of commit statuses in Azure CI check

- .github/workflows/azure_ci.js
- .github/workflows/azure_ci_check.yml
- .github/workflows/scheduled_workflow.yml
This PR redesigns and implements the way of surfacing Azure CI report status of a PR and fixes bugs in checking Azure CI report based on `issue_comment` event triggers.
There are a few things to be aware of:
- The GitHub token used by the GitHub workflows triggered by PRs from a fork (e.g., `yihua/hudi` instead of `apache/hudi`) has read-only permissions, and no write permissions are granted (Apache restriction).  Only the GitHub workflows triggered from master and branches on `apache/hudi` contain GitHub token with write permissions, including scheduled tasks and workflows triggered by issue/PR comments. Write permissions are required for creating commit status, commenting on the PR, adding labels to the PR, add related projects, etc.
- The Azure CI report is included in the comments …
> [HUDI-7438] Reimplement Azure CI report check with open PRs

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
StreamerUtil prints wrong path：
`2024-02-20 10:09:23,864 INFO  org.apache.hudi.util.StreamerUtil                            [] - Table [hdfs://warehouse/table_name/table_name] already exists, no need to initialize the table`
Logging update only.
none
N/A
> [MINOR] StreamerUtil prints wrong table path

- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/ProtoKafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/DefaultStreamContext.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceProfile.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceProfileSupplier.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamContext.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
There were test failures in the original PR and had to be reverted, bringing back the change and fixed the tests now. 
https://github.com/apache/hudi/pull/10687 
Introducing a new class known as SourceProfile which contains details about how the next sync round in StreamSync should be consumed. For eg:
`KafkaSourceProfile` contains number of events to consume in this sync round.
`S3SourceProfile` contains the list of files to consume in this sync round
`HudiIncrementalSourceProfile` contains the beginInstant and endInstant commit times to consume in this sync round.
In future we can add the method for choosing the writeOperationType and indexType as well, for `sourceProfile.getSourceSpecificContext()` will be used to consume the data from the source.
No change in public API's, Option has …
> [HUDI-7416] Add interface for SourceProfile to be used in StreamSync for reading data

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveAvroSerializer.java
Fix code style for HiveAvroSerializer
NONE
NONE
NONE
> [MINOR] Fix code style for HiveAvroSerializer

- website/docs/hoodie_streaming_ingestion.md
Add missing features for `HoodieStreamer`.
- move up intro part
- make help text up-to-date and collapsable
- improve bundle usage description
- add transformers intro
- add info for schema registry provider
- fix missing info in concurrency conctrol
- add info for pulsar, gcs events, and sql file based sources
- add info for error table
- add info for termination strategy
- add info for dynamic configuration update
- fix indentation and move down multi table streamer
For users to understand and use `HoodieStreamer` more easily
NA
NA
> [DOCS][HUDI-7444] Add missing features for `HoodieStreamer`

- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveAvroSerializer.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeRecordReaderUtils.java
Fix decimal conversion with legacy bytes type
Fix decimal conversion with legacy bytes type
low
NONE
> [HUDI-7443] Fix decimal conversion with legacy bytes type

- .github/workflows/bot.yml
- .github/workflows/pr_compliance.yml
- .github/workflows/scheduled_workflow.yml
HOTFIX: SKIP AZURE CI
script update only
This PR adjusts the GitHub workflows to run and check CI on PR targeting branch-0.x and branch-0.x itself.
As above to run tests for branch-0.x.
none
N/A
> [HUDI-7446] Enable CI on PRs targeting branch-0.x and branch-0.x

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCheckpointUtils.java
When allocedEvents in the offset computation function exceeds the  actualNumEvents that can be ingested in this round, there is a bug in the way the endOffset or toOffset is calculated leading to invalid offset ranges exception as re-produced in the unit test, this change fixes this bug.
No impact to existing users, this is a bug fix for kafka sources.
Medium. 
None
> [HUDI-7450] Fix offset computation bug when allocedEvents > actualNumEvents

- hudi-aws/pom.xml
- hudi-client/hudi-client-common/pom.xml
- hudi-client/hudi-flink-client/pom.xml
- hudi-client/hudi-java-client/pom.xml
- hudi-client/hudi-spark-client/pom.xml
- hudi-examples/hudi-examples-flink/pom.xml
- hudi-kafka-connect/pom.xml
- hudi-timeline-service/pom.xml
- packaging/hudi-aws-bundle/pom.xml
- packaging/hudi-datahub-sync-bundle/pom.xml
- packaging/hudi-flink-bundle/pom.xml
- packaging/hudi-gcp-bundle/pom.xml
- packaging/hudi-hadoop-mr-bundle/pom.xml
- packaging/hudi-hive-sync-bundle/pom.xml
- packaging/hudi-kafka-connect-bundle/pom.xml
- packaging/hudi-presto-bundle/pom.xml
- packaging/hudi-spark-bundle/pom.xml
- packaging/hudi-trino-bundle/pom.xml
- packaging/hudi-utilities-bundle/pom.xml
- packaging/hudi-utilities-slim-bundle/pom.xml
Exclude the test resources, especially the properties files that conflict with user-provided resources, from every module. This is a followup to https://github.com/apache/hudi/pull/7310#issuecomment-1328728297
Minimal impact. Just excluding some test resources.
low
> [HUDI-5292] Exclude the test resources from every module packaging

- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
For files that are not created by Hudi but added to the table (zero copy bootstrap or OneTable case) we are unable to remove the column stats after these files are removed from the table view.
Allows proper cleanup of metadata table's stats partition
None
> [MINOR] Allow removal of column stats from metadata table for externally created files

- hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/hadoop/fs/TestHadoopFSUtils.java
- hudi-io/src/main/java/org/apache/hudi/storage/StoragePathInfo.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestStoragePathInfo.java
This PR adds the replication and block size information to `StoragePathInfo` so that it is backward compatible for generating `FileStatus` from `StoragePathInfo` and Hive's `FileInputFormat` to properly generate splits based on the block size.  Hive's relevant logic is mentioned below.  Without this change, the replication and block size information are dropped; Hive's input format generates a huge number of splits with size 1, without block size (0), causing performance regression.
This fixes the test issue in the integration of `HoodieStorage` abstraction, which can be found in #10591.
Fixes backward compatibility in `HoodieStorage` abstraction.
low
N/A
> [HUDI-7431] Add replication and block size to StoragePathInfo to be backwards compatible

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelectorCommon.java
- hudi-utilities/src/test/resources/data/partitioned/country=IND/state=TS/data.json
- hudi-utilities/src/test/resources/data/partitioned/country=US/state=TX/data.json
In our current code we are doing a coalesce which just decreases the partitions but doesn't increase them, adding a function known as `coalesceOrRepartition` which does coalesce or repartition depending on the rdd partitions and the numPartitions calculated using the task/partition size. 
Improvement in S3/GCS sources to increase/decrease  parallelism based on partition size. 
Medium
None.
> [HUDI-7452] Repartition row dataset in S3/GCS based on task size

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileWriterFactory.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieInternalRowFileWriterFactory.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowParquetWriteSupport.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/io/storage/row/TestHoodieInternalRowParquetWriter.java
Allow custom write support for spark parquet row writer that extends HoodieRowParquetWriteSupport. 
Use `org.apache.hudi.io.storage.row.HoodieRowParquetWriteSupport` to set the custom write support. 
Allows for users to customize row writer like they are able to for avro writer.
low
N/A
> [HUDI-7385] Add config for custom write support for parquet row writer

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
- hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Reverts commit 42799c0956f626bc47318ddd91c626b1e58a0fc8
Reverting of adding of unnecessary parameter `hoodie.datasource.write.new.columns.nullable`.
It started from [issue 9042](https://github.com/apache/hudi/issues/9042). The real problem was in inconsistency between Hudi table schema and Spark catalog schema. But during discussion of the issue JIRA task [HUDI-6438](https://issues.apache.org/jira/browse/HUDI-6438) was created. As a results, the task was resolved by adding new parameter `hoodie.datasource.write.new.columns.nullable`, which is not right, because it allows to workaround implicit inconsistency in schemas. We need to provide consistency between existed schemas.
Furthermore, the real problem with inconsistency between Hudi table schema and Spark catalog schema was solved in …
> Revert "[HUDI-6438] Config parameter 'MAKE_NEW_COLUMNS_NULLABLE' to allow for marking a newly created column as nullable"

- pom.xml
Bump Spark 3.5 version from 3.5.0 to 3.5.1
None
Medium
N/A
> [HUDI-7463] Bump Spark 3.5 version to Spark 3.5.1

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
Refactoring checkTopicCheckpoint in KafkaOffsetGen for reusability by making it as public static, useful for validating source related checkpoints. 
no major impact, this pr just exposes an existing function
low
NA
> [HUDI-7462] Refactor checkTopicCheckpoint in KafkaOffsetGen for reusability

- hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/KafkaOffsetPostProcessor.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestKafkaOffsetPostProcessor.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
- KafkaOffsetPostProcessor now accounts for possibility that the supplied schema may provide the kafka metadata fields
- Only add record key to the json if it is non null to avoid an NPE
Fixes bugs
None
> [HUDI-7464] Fix minor bugs in kafka post-processing related code

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestHBasePutBatchSizeCalculator.java
- hudi-common/src/main/java/org/apache/hudi/common/fs/SizeAwareDataOutputStream.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieWithTimelineServer.java
This PR fixes 4 violations of Sonarqube Rule java:S2184 : ['Math operands should be cast before assignment'](https://rules.sonarsource.com/java/RSPEC-2184).
For more details, please see
[MITRE, CWE-190](http://cwe.mitre.org/data/definitions/190) - Integer Overflow or Wraparound
[CERT, NUM50-J.](https://wiki.sei.cmu.edu/confluence/x/AjdGBQ)- Convert integers to floating point for floating-point operations
[CERT, INT18-C.](https://wiki.sei.cmu.edu/confluence/x/I9cxBQ) - Evaluate integer expressions in a larger size before comparing or assigning to that size
The patch was automatically generated using the ViolationFixer tool.
Code quality improvements.
none
N/A
> [MINOR] Fix violations of Sonarqube rule java:S2184

- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
Created a new record buffer to store unmerged records.
Some workload can be supported.
Low.
> [HUDI-7341] Support unmerged record read

- .github/workflows/bot.yml
- azure-pipelines-20230430.yml
This PR splits tests in CI further to reduce total CI elapsed time:
- GitHub Java CI: splits the spark tests into two jobs, one for Java tests only and the other for Scala tests only (`test-spark` -> `test-spark-java-tests` and `test-spark-scala-tests`, `test-spark-java17` -> `test-spark-java17-java-tests` and `test-spark-java17-scala-tests`).  This roughly cuts the total time of `test-spark` from ~2h to ~70min after parallelizing.
- Azure CI: splits the job 3, `UT spark-datasource`, which takes ~3h, into two jobs, one for Java tests only (`Java UT spark-datasource`) and the other for Scala tests only (`Scala UT spark-datasource`), so after parallelizing, Azure CI takes ~2h to finish.
Another improvement added in this PR is to build only the necessary modules in Job 2-5 in Azure CI (we …
> [HUDI-7465] Split tests in CI further to reduce total CI elapsed time

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Made default value of  "hoodie.merge.allow.duplicate.on.inserts" as True and fixed tests.
low
low
Documentation update is needed as default value of HoodieWriteConfig property "hoodie.merge.allow.duplicate.on.inserts" changed to true
> [HUDI-6089] Handle default insert behaviour to ingest duplicates

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCompactionTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTableWithNonRecordKeyField.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
There are lots of functional tests running with the permutations of both Hudi record types, e.g., AVRO and SPARK, which are not necessary, e.g., not directly related to testing the record type.  This PR removes them to save time in CI.
Reduces time in CI to avoid running unnecessary tests.
This PR after removing redundant tests:
Master before this PR:
none
N/A
> [HUDI-7469] Reduce redundant tests with Hudi record types

- website/docs/schema_evolution.md
- website/versioned_docs/version-0.10.0/schema_evolution.md
- website/versioned_docs/version-0.10.1/schema_evolution.md
- website/versioned_docs/version-0.11.0/schema_evolution.md
- website/versioned_docs/version-0.11.1/schema_evolution.md
- website/versioned_docs/version-0.12.0/schema_evolution.md
- website/versioned_docs/version-0.12.1/schema_evolution.md
- website/versioned_docs/version-0.12.2/schema_evolution.md
- website/versioned_docs/version-0.13.0/schema_evolution.md
- website/versioned_docs/version-0.13.1/schema_evolution.md
- website/versioned_docs/version-0.14.0/schema_evolution.md
- website/versioned_docs/version-0.14.1/schema_evolution.md
Fix dataframe write option in `schema_evolution` docs
e.g.
`PRECOMBINE_FIELD_OPT_KEY` has no `key` attribute, and it is Deprecated, replace it with `PRECOMBINE_FIELD.key`
low
low
Fix schema_evolution docs
> [DOCS] Fix dataframe write option in schema_evolution docs

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToFourUpgradeHandler.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndexClient.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
There are a couple of issues in how functional indexes are managed.
1. HoodieSparkFunctionalIndexClient::create(...) was failing to register a functional index iff a (different) functional index was already created. Fixed this check by looking up the index-name in the FunctionalIndexMetadata
2. HoodieTableConfig `TABLE_METADATA_PARTITIONS` and `TABLE_METADATA_PARTITIONS_INFLIGHT` should actually store the Metadata partition path. While the path is contained in the `MeatadatPartitionType` for most of the indexes, it is not correct for functional-index. MeatadatPartitionType.FUNCTIONAL_INDEX only stores the prefix (i.e func_index_). The actual partition path needs to be extracted from the index-name.
3. Because of 2, most of the helper methods that operate on metadata-partitions, should …
> [HUDI-7458] Fix bug with functional index creation

- hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
getDiskBasedMap return both RocksDbDiskMap and BitCaskDiskMap not support values method，but other modules would call the method. we should support it
none
none
> [HUDI-7150] ExternalSpillableMap support values method

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/providers/SparkProvider.java
- hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/TestHoodieInMemoryFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSourceFormatAdapter.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSanitizationUtils.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlQueryBasedTransformer.java
This PR makes two minor changes:
- Increases the number of executors in Spark session in tests.
- Uses the existing util method to get Spark conf for a few tests.
Reduces test time
none
N/A
> [HUDI-7471] Increase the number of Spark executors in tests

- .github/PULL_REQUEST_TEMPLATE.md
- scripts/pr_compliance.py
As above, to make PR description validation strict.
No information in the "Documentation Update" section in the PR description will trigger PR validation failure:
As above.
none
none
> [MINOR] Add PR description validation on documentation updates

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
SQL confs are lost when doing bulk insert row writer with deltastreamer.
SQL conf settings will correctly be applied when using row writer bulk insert
low
N/A
> [HUDI-7479] SQL confs don't propagate to spark row writer properly

- hudi-client/hudi-client-common/pom.xml
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsM3Config.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/m3/M3MetricsReporter.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/m3/M3ScopeReporterAdaptor.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/m3/TestM3Metrics.java
- packaging/hudi-flink-bundle/pom.xml
- packaging/hudi-integ-test-bundle/pom.xml
- packaging/hudi-kafka-connect-bundle/pom.xml
- packaging/hudi-spark-bundle/pom.xml
- packaging/hudi-utilities-bundle/pom.xml
- packaging/hudi-utilities-slim-bundle/pom.xml
- pom.xml
- Added new MetricsReporter implementation org.apache.hudi.metrics.m3.M3MetricsReporter which emits metrics to M3
- Added new dependencies in HUDI : `com.uber.m3:tally-m3`, `com.uber.m3:tally-core`
- Users using https://m3db.io can enable reporting metrics to M3 by setting `hoodie.metrics.reporter.type` as `M3` and their corresponding host address/port in `hoodie.metrics.m3.host` / `hoodie.metrics.m3.port` 
low
Documentation should be updated with the new config options for M3 metrics reporting:
- `hoodie.metrics.m3.host`
- `hoodie.metrics.m3.port`
- `hoodie.metrics.m3.tags`
- `hoodie.metrics.m3.service`
- `hoodie.metrics.m3.env`
> [HUDI-7337] Implement MetricsReporter that reports metrics to M3

- hudi-aws/src/test/java/org/apache/hudi/aws/sync/ITTestGluePartitionPushdown.java
- hudi-aws/src/test/java/org/apache/hudi/aws/transaction/integ/ITTestDynamoDBBasedLockProvider.java
The tests do not work.  Disabling them to unblock Azure CI.
none
none
none
> [HUDI-7475] Disable ITs in hudi-aws module

- azure-pipelines-20230430.yml
This PR fixes Azure publishing of JUnit results to avoid double counting the same test results.  Only the last step in a job should have the `publishJUnitResults` enabled.  Otherwise, the tests from the previous step are published again, making these tests double counted:
Makes test count in Azure accurate.
none
N/A
> [MINOR] Fix Azure publishing of JUnit results

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
Current implementation of `HoodieSchemaUtils.deduceWriterSchema` is really complicated with many flags used in one place.
To figure out how this method is working, we need to draw directed acyclic graph. Here the current implementation:
Yellow is used for marking of flags, and purple is used for marking of returned schemas or exceptions.
We couldn't remove any of the used flags without changing processing logic. The only possibility is to refactor `deduceWriterSchema()` for simplification, and preparing for future removing of deprecated `hoodie.datasource.write.reconcile.schema`.
This MR proposes to consider the following changed processing schema:
Refactored `HoodieSchemaUtils.deduceWriterSchema`.
Low.
No need.
> [HUDI-6947] Refactored HoodieSchemaUtils.deduceWriterSchema with many flags

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileReaderFactory.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroFileReaderFactory.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieFileReaderFactory.java
Passing HoodieConfig down to newHFileReader instead of passing useBuiltInHFileReader only. So it'd be easier to add more customization directly to file reader level in the future without having to change newHFileFileReader method.
None
None
> [HUDI-7356] Passing configs to file reader constructor for flexibility

- website/docs/gcp_bigquery.md
updated  `hoodie.gcp.bigquery.sync.require_partition_filter` and removed `hoodie.gcp.bigquery.sync.base_path`
none
none
updated https://hudi.apache.org/docs/next/gcp_bigquery
@xushiyan please review
> [DOCS] Update GCP config doc

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
- Add unit test  org.apache.hudi.io.TestHoodieTimelineArchiver#testRetryArchivalAfterPreviousFailedDeletion to simulate scenario where an archival call does not delete all the completed `.commit` files on the timeline and archival is retried again. The expected behavior is that the subsequent archival retry should "clean up" the leftover `.commit` files. This scenario can happen if `org.apache.hudi.client.timeline.HoodieTimelineArchiver#deleteArchivedInstants` encounters transient failures when deleting completed instant files, such as due to the edge case that was resolved by HUDI-7207
None
none
- _The …
> [MINOR] Add UT org.apache.hudi.io.TestHoodieTimelineArchiver#testRetryArchivalAfterPreviousFailedDeletion

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
The code is developed by own. It is used to fix the code bug. 
When the BigQuery external table with an additional connection id, the changes of schema can't use the ExternalTableDefinition.setSchema()
I change the logic to detect if there is a connection id. And use this code to fix that bug.
On influence the update BQ schema process.
low medium
> [HUDI-7488] The BigQuerySyncTool can't work well when the hudi table schema changed  #10829

- website/docs/schema_evolution.md
- website/versioned_docs/version-0.14.1/schema_evolution.md
Update table to clearly show how schema is evolved and manipulated based on incoming and existing schema
Users are clear on schema evolution
none
N/A
> [HUDI-7482] Update schema evolution docs to explicitly state allowed type promotions

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
Fixing handling null values of extra metadata in clean commit metadata
Fixing handling null values of extra metadata in clean commit metadata
low.
> [HUDI-7491] Fixing handling null values of extra metadata in clean commit metadata

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Cleaner could delete partition but meta sync fails to drop partition in that case. This could cause query using engines that depend on hive metastore as catalog to fail. Only affects Hive sync.
Catalog will reflect correct partition metadata considering cleaner commits.
low
> [HUDI-7411] Meta sync should consider cleaner commit

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataWriteUtils.java
Metadata table should retain at least as much history as data table. Follow similar policy as data table and set retention to 1.2x for metadata table.
none
low
> [HUDI-7402] Align MDT cleaner configs with the data table

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
Currently Compaction preserveCommitMetadata field is set to false for MDT otherwise it is set to true. The Jira aims to use the default value (true) for MDT as well.
This is a follow-up clean-up of #8128.
NA
low
NA
> [HUDI-6043] Metadata Table should use default values for Compaction preserveCommitMetadata field

- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/streaming/StructuredStreamingSinkUtil.java
- hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/streaming/StructuredStreamingSinkTestWriter.scala
Adding support to test spark structured streaming job to integ test. Added a spark submit job for ease of testing w/ EKS as well. 
We should be able to test spark structured streaming as part of release certification. 
low.
N/A
> [HUDI-5101] Adding spark-structured streaming test support via spark-submit job

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
fix https://issues.apache.org/jira/browse/HUDI-7163
reference https://issues.apache.org/jira/browse/HUDI-4340
flink compact
low medium
None
> [HUDI-7163] Fix not parsable text DateTimeParseException when compact

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Here we account for action type "compaction". But compaction completed instant will have "commit" as action. So, we need to fix it.
low
low
> [HUDI-7478] Fix max delta commits guard check w/ MDT

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/ClusteringPlanStrategy.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/FlinkSizeBasedClusteringPlanStrategyRecently.java
Get partitions from active timeline instead of listing when building clustering plan
New strategy to build clustering plan for Flink
low
> [HUDI-7382] Get partitions from active timeline instead of listing when building clustering plan

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCheckpointUtils.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
The current logic for computing offset ranges is leading to skews and negative offsets because of the way they are calculated. 
https://github.com/apache/hudi/blob/master/hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java#L144 
Problems faced. 
1. We are calculating eventsPerPartition based on available partitions this can lead to skews where one partition handles only 1-10 messages and the remaining one handles 100K messages, the idea for minPartitions is to increase the parallelism and ensure that each spark task is reading approximately the same number of events. 
2. remainingPartitions can become negative when finalRanges exceeds the size of minPartitions. 
3. Complicated fork in code when minPartitions > toOffsetsMap, this is not required IMO …
> [HUDI-7506] Compute offsetRanges based on eventsPerPartition allocated in each range

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/LSMTimelineWriter.java
In LSMTimelineWriter we should wait for the parquet writer closed and then update the manifest and version file.
none
none
none
> [HUDI-7514] Update Manifest file after the parquet writer closed in LSMTimelineWriter

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestJdbcbasedSchemaProvider.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJdbcSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/JdbcTestUtils.java
From this discussion https://github.com/apache/hudi/pull/10866
hudi-utilities tests refactoring: put the JDBC user and password into static variables to avoid any misconfigs in tests in the future. @yihua, review please
none
none
> [HUDI-7516] Put jdbc-h2 creds into static variables for hudi-utilities tests

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
Removed redundant `fileId` from HoodieAppendHandle, because it's parent (HoodieWriteHandle) already contains field `protected final String fileId`.
none
none
none
> [MINOR] Remove redundant fileId from HoodieAppendHandle

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/partitioner/StreamReadAppendPartitioner.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/partitioner/StreamReadBucketIndexPartitioner.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/selector/StreamReadAppendKeySelector.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/selector/StreamReadBucketIndexKeySelector.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
To resolve data skew issues in stream read for the following scenario.
**Before modification:**
**After modification:**
**2. APPEND mode**
**Before modification:**
**After modification:** …
> [HUDI-7529] Resolve hotspots in stream read

- hudi-common/src/test/java/org/apache/hudi/client/transaction/lock/TestInProcessLockProvider.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
The reason for failure in `TestPartialUpdateForMergeInto` at `Test MERGE INTO with inserts only on MOR table when partial updates are enabled` case is absent proper cleaning of in-memory index in `TestSpark3DDL` at three test cases `Test FLOAT/DOUBLE/STRING to DECIMAL schema evolution (lost in scale)`.
Also, changed importing style in affected test classes to explicit for improved readability.
No
None
No need
> [HUDI-7487] Fixed test with in-memory index by proper heap clearing

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/BaseBootstrapMetadataHandler.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
I see a lot of code duplication in handleUpdateInternal() method of XXXCommitActionExecutor and HoodieXXXTable. Small refactoring/cleaning proposal:
1. rename HoodieWriteHandle.writeStatuses() to getWriteStatuses(), as it doesn't write, but gets
2. remove code duplications by extracting one part of common code from handleUpdateInternal() methods to HoodieMergeHandle.getWriteStatusesAsIterator()
3. remove code duplications by extracting another part of common code from handleUpdateInternal() methods to HoodieTable.runMerge()
none
none
none
ticket number here …
> [HUDI-7530] Refactoring of handleUpdateInternal in CommitActionExecutors and HoodieTables

- pom.xml
#10097 we relocated "com.fasterxml.jackson.module", 
https://github.com/apache/hudi/blob/2dcdd311245b38c0a9884338d6333212a730d310/pom.xml#L582-L586
this changes the package path of *jackson-module-scala_${scala.binary.version}*.
When we do spark stream read, we will get `ClassNotFoundException: org.apache.hudi.com.fasterxml.jackson.module.scala.DefaultScalaModule$`
none
none …
> [HUDI-7513] Add jackson-module-scala to spark bundle

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
Rollback the deletion of the setMaxParallelism setting in this pr.
https://github.com/apache/hudi/pull/10911
> [MINOR] Restore the setMaxParallelism setting for HoodieTableSource.produceDataStream

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/PreferWriterConflictResolutionStrategy.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RestorePlanActionExecutor.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/IncrementalQueryAnalyzer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
This PR fixes the regression introduced by #9755, by still considering pending clustering when scheduling a new clustering plan.
Refactoring of `ClusteringUtils` methods is also done to avoid confusion:
- Consolidates `#isClusteringCommit`, `#isPendingClusteringInstant` into `#isClusteringInstant` to check if a requested, inflight, or completed instant of replacecommit action is a clustering operation.
- Renames `#isClusteringInstant` to `#isCompletedClusteringInstant`
The tests are added to guard the fix, so that before the fix the test fails, and after the fix, the test succeeds.
Bug fix.
none
N/A
> [HUDI-7531] Consider pending clustering when scheduling a new clustering plan

- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataPayload.java
When there are repeated duplicate deletes to the partition file list in `files` partition of the MDT, the current HoodieMetadataPayload merging logic drops such "deletion", causing the file that is deleted from the file system and supposed to be deleted from MDT file listing still left in MDT, because the merging logic of file system metadata does not account for such a case.  Other MDT partitions have already considered repeated deletes when merging payloads.
This PR fixes the logic.  New tests are added around the repeated deletes (the tests fail before the fix and succeed after the fix).
The impact of this bug is that deleted files may still exist in MDT if there are repeated delete operations.  It does not cause any data loss.
Here's a concrete example of how this bug causes the …
> [HUDI-7518] Fix HoodieMetadataPayload merging logic around repeated deletes

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestFetchNextBatchFromSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSyncUnitTests.java
In a couple cases, the target schema for the input batch does not go through deduceSchema. It is important that every schema goes through there before attempting the write.
MOR read fails with empty schema. Ensure that schema is evaluated for all hudi relations, so that we can detect empty schema and send an empty rdd.
Reduce deltastreamer failure conditions. Reduce MOR read failure conditions.
low
N/A
> [HUDI-7500] fix gaps with deduce schema and null schema

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestPriorityBasedFileSystemView.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
This [PR](https://github.com/apache/hudi/pull/7865) added a preloading from the MDT for the sake of performance but it also forces all the file group information into memory. This leads to higher memory usage than is required for the cleaner planner.
Changes in this PR: 
- Adds new method to load a list of partitions
- Adds new endpoint for Remote FS View
- Removes old load-all call in the CleanPlanner constructor
Lowers amount of memory required for the cleaner planner
Low …
> [HUDI-7551] Avoid loading all partitions in CleanPlanner when MDT is enabled

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
At present, the default value of `read.streaming.skip_clustering` is false, which could cause the situation that streaming reading reads the replaced file slices of clustering, so that streaming reading may read T-1 day data when clustering the data of T-1 day to cause duplicated data and could not restore from checkpoint. Therefore streaming read should skip clustering instants for all cases to avoid reading the replaced file slices. Same to `read.streaming.skip_compaction`.
Streaming read should skip clustering instants to avoid duplicated reading.
none.
none.
> [HUDI-6317] Streaming read should skip compaction and clustering instants to avoid duplicates

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java
- Fix `org.apache.hudi.config.metrics.HoodieMetricsConfig.Builder#build` to initialize `HoodieMetricsConfig` using config from `HoodieMetricsM3Config` if `MetricsReporterType` is M3
none
> [MINOR] When M3 metrics reporter type is used HoodieMetricsConfig should create default values for HoodieMetricsM3Config

- hudi-cli/src/main/java/org/apache/hudi/cli/HoodieCLI.java
- hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestMetadataCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestBootstrapCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestHDFSParquetImportCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestRepairsCommand.java
Currently, we build HoodieTimeGeneratorConfig with default configuration, instead we should respect props users set.
none
none
none
> [HUDI-6884] hudi-cli should generate correct HoodieTimeGeneratorConfig

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineDiffHelper.java
Refactor methods in TimelineDiffHelper class to address following comment https://github.com/apache/hudi/pull/9007#discussion_r1264293961
none
none
none
> [HUDI-6538] Refactor methods in TimelineDiffHelper class

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
Please refer to the jira ticket [HUDI-7564](https://issues.apache.org/jira/browse/HUDI-7564) for a more detailed explanation.
When investigating an error thrown by Trino/Presto queries involving Timestamp types:
```log
2024-04-02 17:32:21 (UTC+8) INFO - Clear session property for connection.
2024-04-02 17:32:21 (UTC+8) ERROR- Task Execution failed with CommonException: Query failed (#20240402_093220_06724_cg4jg): Expected field to be long, actual timestamp(9) (field 0) 
```
We realised that there is a config inconsistency shown that indirectly causes the error thrown above. Trino/Presto requires that `TIMESTAMP` types to be synced to HMS as `LONG` types. 
This should be the default behaviour as:
```properties
hoodie.datasource.hive_sync.support_timestamp=false
```
However, we realised …
> [HUDI-7564] Fix HiveSyncConfig inconsistency

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Record level index speeds up queries (when appropriate config properties are enabled) by pruning files based on metadata's RLI partition entries. The current implementation can prune files only when the query predicate has a EqalTo (i.e '=') OR In filters/expressions on the record-key column.
However, the logic to detect if a 'In' query predicate references a record-key column is buggy. This can result in wrong results when the query predicate is a `In` expression ona  column other than record-key column. This seems like a serious bug that needs to be fixed.
This PR fixes this problem and adds a unit test for the same.
The changes introduced are:
RecordLevelIndexSupport.scala: The method `filterQueryWithRecordKey(...)` is where the bug exists. The switch-case for `In` expression was not …
> [HUDI-7569] [RLI] Fix wrong result generated by query

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfigHolder.java
Reverting the hive-sync support_timestamp inconsistency as described in https://github.com/apache/hudi/pull/10951#issuecomment-2034230672.
TLDR, this inconsistency was introduced to ensure that hive-sync's behaviour is inline with Spark's externalCatalog table schema sync, which is used in AlterTableHoodieCommand.
Hive-sync is used to create the _ro and _rt tables of MOR.
None
None
Updated the config description for `hoodie.datasource.hive_sync.support_timestamp` to document that this is an intended inconsistency.
> [HUDI-7564] Revert hive sync inconsistency and add docs for it

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
There is a chance that MDT could list additional partitions when compared to FS based listing. 
Reason:
We load active timeline from metaclient and poll FS based listing for completed commits. And then we poll MDT for list of all partitions. in between these two, there could be a commit that could have been completed and hence MDT could be serving that as well. So, lets account for that in our validation tool 
We may have false positive validation failures from MDT validators
low
- _Any new feature or user-facing change requires updating the Hudi …
> [HUDI-7556] Fixing MDT validator and adding tests

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
When ignoreFailed is enabled, HoodieMetadataTableValidator ignores failure and continues the validation. This jira aims to add api to get list of exceptions and an api to check if validation exception was thrown.
NA
low
NA
> [HUDI-7571] Add api to get exception details in HoodieMetadataTableValidator with ignoreFailed mode

- hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java
- hudi-cli/src/test/java/org/apache/hudi/cli/functional/CLIFunctionalTestHarness.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/HoodieTestCommitGenerator.java
- hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestFlinkSizeBasedClusteringPlanStrategy.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestSparkBuildClusteringGroupsForPartition.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieWriteStat.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFSViewWithClustering.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestCluster.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotCopier.java
I found in `FSUtils` class:  
```
// TODO: this should be removed  
public static String makeBaseFileName(String instantTime, String writeToken, String fileId)  
```
This method (without fileExtension param) is not used in main code at all, but has heavy usage (>100 referencies) in tests.
I removed it and fixed all depending tests by calling extended version of `makeBaseFileName` (with default base file extension as argument).  
So now there is only one `makeBaseFileName` method for all cases, and there is no possibility to make base file name with default extension mistakenly.
none
none
none
- _Any new feature or user-facing change requires updating the Hudi website. Please …
> [MINOR] Removed FSUtils.makeBaseFileName without fileExtension param

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
- hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/ErrorEvent.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieStreamerUtils.java
Handles cases of missing required fields and bad input values when converting to JSON. This conversion is used in combination with the Error Table so you cannot assume that the records are properly formatted.
Avoids exceptions being thrown for malformed input data being sent to the error table writer
None
changes to the …
> [MINOR] Handle cases of malformed records when converting to json

- .github/workflows/bot.yml
- .github/workflows/release_candidate_validation.yml
[MINOR] replace AdoptOpenJDK with Temurin jdk
AdoptOpenJDK is obsolete.
n/a
low
n/a
> [MINOR] use Temurin jdk

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
- Moved `writeTableMetadata` from `BaseHoodieWriteClient` to `BaseHoodieClient` and remove it from `BaseHoodieTableServiceClient`;  
- Removed `postWrite` from `HoodieJavaWriteClient` (as the same implementation exist in it's parent class `BaseHoodieWriteClient`);  
- Fixed logging in `BaseHoodieTableServiceClient`.
none
none
none
> [MINOR] Removed code duplicates in HoodieClients

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
- hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
- hudi-common/src/main/java/org/apache/hudi/common/model/RecordPayloadType.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBasicSchemaEvolution.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieOptionConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
Changed default payload type to HOODIE_AVRO_DEFAULT.  
Current default is OVERWRITE_LATEST which instantiates OverwriteWithLatestAvroPayload but it's not intuitive when latest gets written and user sets some precombine field and expects to merge records based on that field.
none
none
Needs to update default value in documentation.
> [HUDI-6854] Change default payload type to HOODIE_AVRO_DEFAULT

- hudi-common/src/main/java/org/apache/hudi/common/table/read/IncrementalQueryAnalyzer.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
In streaming scenarios, insert overwrite is usually used to repair data. Here you can control the visibility of downstream stream reads.
streaming read.
none.
> [HUDI-7230] stream read supports skipping insert overwrite instant

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestInlineCompaction.java
If there is no log files in the compaction plan, skip the compaction.
none
none
none
> [HUDI-7572] Avoid to schedule empty compaction plan without log files

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestPriorityBasedFileSystemView.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
This PR fixes two issues:
1. When a functional index is updated, it was getting re-initialized. This was happening because metadata partition type only contains the functional index partition prefix while hoodie.properties contains the full name. Due to discrepancy, metadata writer thought there is anew index that needs ot be initialized. This is fixed in `HoodieTableConfig#isMetadataPartitionAvailable`.
2. When a functional index is updated, it fetches latest file slices, including the pending ones, in data partition. There was a typo in building the filesystem view. Instead of passing data meta client, metadata meta client was passed.
Added a test which covers both these scenarios.
Fixes functional index bugs.
low
_Describe any necessary documentation update if there is any new feature, …
> [HUDI-7480] Fix functional index and avoid multiple initializations

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
refer to
https://issues.apache.org/jira/browse/HUDI-7477
Before modification:
1. The semantics are unclear. In fact, it is not the first 100 error messages， but the first10 file errors.
2. The printing positions of partition and global exception are reversed. 
And if there is no global exception, there is no need to print null.
4. Row-level exceptions. Although they are printed in the trace,  the online data traffic is usually very large,  so it is not wise to print them all.
So, I modified it to print the first 10 files with write exceptions
Then print global exceptions and row-level exceptions as needed,  and if there are row-level exceptions,  only print the first 100 exceptions.
_If medium or high, …
> [MINOR] Optimize print write error msg in StreamWriteOperatorCoordinator#doCommit

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Fixing false positive validation with MDT validator. When MDT has additional partition compared to FS based listing, we could get false positive. This has a minor fix over https://github.com/apache/hudi/pull/10939 and has tests. 
Robust MDT validations.
low.
> [HUDI-7556] Fixing false positive validation with MDT validator

- hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
- hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
- hudi-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
The `TableSchemaResolver` reads the schema from the log block.  The current way of instantiating log reader does not lazily read the content, causing the whole block content to be read, which is unnecessary.  During clustering, when clustering rewrites a file group that contains log files, it requires deriving the schema from the file group in the current logic.  Such logic happens in all paralleled threads on each file group on the Spark driver, causing OOM on the driver.
This PR fixes the `TableSchemaResolver` and `HoodieMetadataTableValidator` to read the log blocker header only for the schema and instant time, and avoid reading block content to reduce the memory requirement.
A test is added for reading the log file.  The memory usage is manually verified.
I have created follow-ups to …
> [HUDI-7583] Read log block header only for the schema and instant time

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
We wanna remove the very specific design for MDT so that it's behavior is in sync with the DT.
The criteria for simplification:
```xml
1. use the instant timestamp from DT to commit to the MDT as much as possible for any delta_commit on MDT.
2. for table sercives like cleaning, compaction and log_compaction, the timestamp is auto-generated.
3. avoid to trigger multiple commits to MDT for one DT action. 
```
The async index instant suffix is also fixed.
Also simplify the logic for MDT delta instant validation for log reader.
none
low medium
none
> [HUDI-7552] Remove the suffix for MDT table service instants

- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
Shutdown ExecutorService when HiveMetastoreBasedLockProvider is closed
When we submitted a clustering job with table with HMS lock, the jvm could not exit. 
The reason is that this thread pool did not exit.
medium
None
> [HUDI-7600] Shutdown ExecutorService when HiveMetastoreBasedLockProvider is closed

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
DataSourceWriteOptions.RECORD_MERGER_STRATEGY.key() should change the strategy set in the table configs but currently does not
make config work
none
N/A
> [HUDI-7605] allow merger strategy to be set in spark sql writer

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/LockConfiguration.java
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/Heartbeat.java
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
If a commit takes a long time, then the acquired lock will be timeout and throw exception.
Thus, send heartbeat periodically to hold the lock and ensure it availible.
low
none
> [HUDI-7601] Add heartbeat mechanism to refresh lock

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestNewHoodieParquetFileFormat.java
Was accidentally removed by https://github.com/apache/hudi/pull/10304
TestNewHoodieParquetFileFormat will pass now
legacy reader now has bootstrap mor functionality
none
N/A
> [HUDI-7599] add bootstrap mor legacy reader back to default source

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
This PR changes the default cleaner behavior to avoid multiple cleaner plans, i.e., only scheduling a new cleaner plan if there is no inflight plan, by setting the default of `hoodie.clean.allow.multiple` to false.  The config is also deprecated and going to be removed after one release.  This is to avoid overlapping cleaner plans when MDT is enabled, and there is no need to schedule multiple inflight cleaner plans.
Makes cleaner behavior easier to maintain and understand.
none
Config docs will be updated during the release process.
> [HUDI-7616] Avoid multiple cleaner plans and deprecate hoodie.clean.allow.multiple

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
Add since version for write configs
Following two since versions have already been marked, so no need to updated in this PR. 
[hoodie.metadata.log.compaction.enable -> 0.14.0](https://github.com/apache/hudi/blob/17ea14ab6d6a8ca7ecef2cfcdbc67b0c87f23987/hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java#L95)
[hoodie.log.compaction.enable -> 0.14.0](https://github.com/apache/hudi/blob/17ea14ab6d6a8ca7ecef2cfcdbc67b0c87f23987/hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java#L70)
version clarification 
_If medium or high, explain what verification was …
> [HUDI-7615] Mark a few write configs with the correct sinceVersion

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
Previously in #10874, we use the DT earliest pending instant time as the MDT compaction time, it may conflict with the delta_commit when the DT pending instant finally got committed.
The solution is to minus the instant time with 1 millisecond, there is still possibility to conflict, but that is very rare case.
none
low medium
none
> [HUDI-7577] Avoid MDT compaction instant time conflicts

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndex.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/functional/TestHoodieSparkFunctionalIndex.java
- hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieFunctionalIndex.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
The read path for functional index leads to a NPE which causes file-pruning to be skipped entirely. This PR fixes the issue as follows:
1. Parse query filter to extrat function name and target column
2. Check functional index definiton and if there is an index, then use that to skip files.
Correct data skipping with functional index.
low
NA
> [HUDI-7582] Fix functional index lookup

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandleWithChangeLog.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandleWithChangeLog.java
- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
There is no need to copy for most of the use cases. The regression in introduced in RFC-46, when the table columns number is large, there could be 50% performance regression comparing to 0.10.x release.
There are two use cases for the regression:
1. COW table ingestion
2. Compaction.
no impact.
none
none
> [HUDI-7578] Avoid unnecessary rewriting to improve performance

- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
The UserGroupInformation lost in  the new thread of timeline service threadpool. If it does not match the UserGroupInformation from the main thread, the spark writers might failed. See more information in [issues#11030](https://github.com/apache/hudi/issues/11030).
The pr aims to fix the problem.
None
None
changes to the …
> [HUDI-7626] propagate UserGroupInformation from the main thread to the new thread of timeline service threadpool

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
- hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/ArchiveExecutorUtils.java
Clean up literal usage in Hudi CLI argument check:  
- added min arguments count as an int field to SparkCommand enum, and now there is a single literal usage for each command (instead of 5 that was before);  
- added args count validation methods to SparkCommand;  
- extracted common logic of additional configs creation to `makeConfigs` method in SparkCommand;  
- extracted common logic of getting propsFilePath to `getPropsFilePath` method in SparkCommand;
- called args validation and configs/propsFilePath computations for all values before the `switch(cmd)`
- fixed logging;
- reused `ArchiveExecutorUtils.archive()` method for `archive` command execution.
none
none
none
- …
> [HUDI-4228] Clean up literal usage in Hudi CLI argument check

- hudi-io/src/main/java/org/apache/hudi/storage/StoragePath.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestStoragePath.java
As above, by using the custom implementation of `writeObject` and `readObject`.
Custom serde to save time.
none
none
> [HUDI-7636] Make StoragePath Serializable

- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
- hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
This PR adds `getDefaultBlockSize` and `openSeekable` APIs to `HoodieStorage` and implements these APIs in `HoodieHadoopStorage`.  The implementation follows the same logic of creating seekable input stream for log file reading, and `openSeekable` will be used by the log reading logic.
A few util methods are moved from `FSUtils` and `HoodieLogFileReader` classes to `HadoopFSUtils`class.
Supports seekable input stream and log reading with `HoodieStorage`.
none
none
> [HUDI-7635] Add default block size and openSeekable APIs to HoodieStorage

- hudi-io/src/main/java/org/apache/hudi/storage/StoragePathInfo.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestStoragePathInfo.java
As above, by comparing the path associated with the `StoragePathInfo` instance.
Makes StoragePathInfo Comparable
none
none
> [HUDI-7637] Make StoragePathInfo Comparable

- hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
Always use UUID as the temporary file suffix so that the method can be thread-safe.
This is required by #10886 
none
none
none
> [HUDI-7640] Uses UUID as temporary file suffix for HoodieStorage.createImmutableFileInPath

- hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSyncUnitTests.java
`StreamSync` constructor changed after `HoodieStorage` abstraction was introduced and the commit https://github.com/apache/hudi/commit/ca77fda51fe3036f86d4ddb8b0e58a2f160882dc was merged without rebasing. So, the master is broken. 
Fix test and build on master.
none
> [HUDI-7643] Fix test by using the right StreamSync constructor

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieErrorTableConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
- hudi-common/src/main/java/org/apache/hudi/common/config/TimestampKeyGeneratorConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/SqlFileBasedSourceConfig.java
Not all configurations are presented on [All configurations](https://hudi.apache.org/docs/configurations) page. This MR adds list of basic Hudi table configurations, and also some missed configurations of file-based SQL source, Hudi error table, and timestamp key generator.
Change only the list of all configurations on Hudi site.
None
Corresponding MR with updates to the `current` version of docs - https://github.com/apache/hudi/pull/11058.
> [MINOR] Added configurations of Hudi table, file-based SQL source, Hudi error table, and timestamp key generator to configuration listing

- hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
Found a lot of code duplicates and inconsistent naming in RemoteHoodieTableFileSystemView and RequestHandler classes.  
- removed code duplicates;  
- fixed logging;  
- fixed naming of constants (request urls);  
- moved some methods to right places;  
- removed extra newlines
none
none
none
> [HUDI-7623] Refactoring of RemoteHoodieTableFileSystemView and RequestHandler

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
- hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
- Add a static method to `MetadataPartitionType` to collect all partitionPath values into a `Set<String>`.
Enhance reuse.
none
> [MINOR] Reuse MetadataPartitionType enum to get all partition paths

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
Task: https://issues.apache.org/jira/browse/HUDI-7639  
Created new abstract class SparkBaseIndexSupport with abstract methods `getIndexName`, `isIndexAvailable`, `computeCandidateFileNames` and `invalidateCaches` (to override it in descendants) and concrete methods `getPrunedFileNames`, `getCandidateFiles` and `shouldReadInMemory` (moved from HoodieFileIndex or XXXIndexSupport to reuse it in descendants).
Made `ColumnStatsIndexSupport`, `FunctionalIndexSupport` and `RecordLevelIndexSupport` classes extend `SparkBaseIndexSupport`. Implementation of `computeCandidateFileNames` was made from corresponding if-else branches of `HoodieFileIndex.lookupCandidateFilesInMetadataTable()`. Implementations of  `getIndexName`, `isIndexAvailable` are trivial. Real implementation of `invalidateCaches` …
> [HUDI-7653] Refactor HoodieFileIndex for more flexibility

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
- hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
Fixed names of methods in HoodieMetadataConfig that return booleans so now they don't look like mutators.
none
none
none
> [MINOR] Fixed naming of methods in HoodieMetadataConfig

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ColumnStatsIndices.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroToRowDataConverters.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
This PR fixes HUDI-7647:
READ_UTC_TIMEZONE doesn't take effect while reading log files in MOR table. This PR fixes it.
No API changes.
Low risk.
None.
> [HUDI-7647] READ_UTC_TIMEZONE doesn't affect log files for MOR tables

- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Enable testArchivalWithMultiWriters back as they are passing
Fixing compaction plan parsing issue when compaction.requested is empty
low.
> [HUDI-6386] Enable testArchivalWithMultiWriters back as they are passing

- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
- hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
Removed FileSystem usage in HoodieLogFormatWriter by adding methods to HoodieStorage API `getDefaultBufferSize()`, `getDefaultReplication()`, `create(StoragePath path, boolean overwrite, Integer bufferSize, Short replication, Long sizeThreshold)` (with appropriate implementations in HoodieHadoopStorage) and use them in HoodieLogFormatWriter instead of using fs. Also fixed logging.
none
none
none
> [HUDI-7632] Remove FileSystem usage in HoodieLogFormatWriter

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/HoodieOfflineJobTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieClusteringJob.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieCompactorJob.java
Util methods in test class `TestHelpers` do not need to get `FileSystem` argument as the input as `FileSystem` instance is static in the base test class.  This PR cleans up such usage.
Makes using Hudi storage classes easier in tests.
none
N/A
> [HUDI-7650] Remove FileSystem argument in TestHelpers methods

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestIncrSourceHelper.java
Fix bug in checkpointing logic for S3/GCS in empty dataset use-case. The reason for the bug was following. 
1st  delta commit's checkpoint, processed 3 files.
```
23/12/06 16:55:26 INFO S3EventsHoodieIncrSource  : Querying S3 with:00000000000000, queryInfo:Query information for Incremental Source queryType: snapshot, previousInstant: 00000000000000, startInstant: 00000000000000, endInstant: 20231206150423946, orderColumn: _hoodie_commit_time, keyColumn: s3.object.key, limitColumn: s3.object.size, orderByColumns: [_hoodie_commit_time, s3.object.key]
23/12/06 16:55:42 INFO S3EventsHoodieIncrSource  : Adjusting end checkpoint:20231206150423946 based on sourceLimit :300000000
23/12/06 16:55:46 INFO S3EventsHoodieIncrSource  : Adjusted end checkpoint …
```
> [HUDI-7235] Fix checkpoint bug for S3/GCS Incremental Source

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
- MetadataPartitionType` now includes predicates for checking both the enabling condition based on metadata configuration and metaClient.
- Move the `HoodieBackedTableMetadataWriter::enablePartitions` method as a static method inside the enum itself.
- Add test for the enum.
Enhance reuse and ease of adding new metadata partitions (indexes).
low …
> [HUDI-7648] Refactor MetadataPartitionType so as to enahance reuse

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
Looks like in BQ sync, we are polling fsview for latest files sequentially for every partition.   
When MDT is enabled, we could load all partitions in one call. 
none
none
none
> [HUDI-7645] Optimize BQ sync tool for MDT

- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HadoopStorageConfiguration.java
- hudi-io/src/main/java/org/apache/hudi/storage/StorageConfiguration.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/BaseTestStorageConfiguration.java
This PR fixes the bug that subclasses implementing `StorageConfiguration` cannot be properly (de)serialized in Spark.  The root cause is that the `#writeObject(ObjectOutputStream out)` and `#readObject(ObjectInputStream in)` for `Serializable` have to be `private`; they cannot be `public` or `protected`.  A new test is added, which fails without the fix and passes with the fix.
Bug fix.
none
none
> [HUDI-7666] Fix serializable implementation of StorageConfiguration class

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/ProtoKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
Make the KafkaSource class public
Allow developers ability to reuse this abstraction for kafka sources
None
> [MINOR] Make KafkaSource abstraction public and more flexible

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
log the time taken when meta sync fails
more consistent logging between success an failure
none
N/A
> [HUDI-7658] Add time to meta sync failure log

- hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Currently a `null/hive/${user}` dir would be left over when the tests finished, which introduces some permission access issues for Azure CI test reports.
none
none
none
> [HUDI-7672] Fix the Hive server scratch dir for tests in hudi-utilities

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
- hudi-io/pom.xml
- hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/DedupeSparkJob.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieRepairTool.java
This PR removes usage of Hadoop classes and the Hadoop dependency from `hudi-io` module.
Makes `hudi-io` module Hadoop indepedent.
none
none
> [HUDI-7664] Remove Hadoop dependency from hudi-io module

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/DirectWriteMarkers.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
- hudi-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestDFSPropertiesConfiguration.java
- hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriterBase.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java
- hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
- hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDataSourceHelpers.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/DedupeSparkJob.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
This PR changes the return type of `HoodieStorage#getConf` to `StorageConfiguration` instead of generic `Object` so that it is easier to understand and pass around, and adds `HoodieStorage#unwrapConf` to return the underlying configuration instance.
API change to improve readability.
none
none
> [HUDI-7670] Return StorageConfiguration from getConf() and add unwrapConf() in HoodieStorage

- hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HadoopStorageConfiguration.java
- hudi-io/src/main/java/org/apache/hudi/storage/StorageConfiguration.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/BaseTestStorageConfiguration.java
This PR makes the following changes:
- Adds `StorageConfiguration#newInstance` to create a new `StorageConfiguration` instance with a new copy of the configuration.
- Adds `StorageConfiguration#setIfUnset` to set a property key with a value in the configuration, if the property key does not already exist.
- Renames `StorageConfiguration#get` to `StorageConfiguration#unwrap` for readability.
- Renames `StorageConfiguration#newCopy` to `StorageConfiguration#unwrapCopy` for readability.
New APIs to facilitate integration of `StorageConfiguration`.
none
none
> [HUDI-7668] Add and rename APIs in StorageConfiguration

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HiveSchemaUtils.java
Don't set default value for primary key when get schema from hms.
```
The main method caused an error: org.apache.flink.table.api.ValidationException: Invalid primary key 'PK_uuid'. Column 'uuid' does not exist.
at org.apache.flink.table.catalog.DefaultSchemaResolver.validatePrimaryKey(DefaultSchemaResolver.java:337)
```
> [HUDI-7675]Don't set default value for primary key when get schema from hms

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
[HUDI-7674] Fix Hudi CLI Command "metadata validate-files" to use file listing to validate
Bug fix for a Hudi CLI command 
Low
No Config change
> [HUDI-7674] Fix Hudi CLI Command "metadata validate-files" to use file listing to validate

- hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
The log is redundant.
none
none
none
> [MINOR] Remove the redundant log in HFileBootstrapIndex

- hudi-examples/hudi-examples-flink/pom.xml
- hudi-utilities/pom.xml
- packaging/hudi-integ-test-bundle/pom.xml
- pom.xml
This PR unifies `bijection-avro` dependency version in the repo and upgrades the dependency version in `hudi-integ-test-bundle` (there is no reason to use a different version).  Also note that `bijection-avro:0.9.7` supports Scala 2.13, which makes Scala 2.13 support easier.
Dependency management improvement.
none
none
> [HUDI-7694] Unify bijection-avro dependency version

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/util/BaseFileUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestBaseFileUtils.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataPayload.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodiePruneFileSourcePartitions.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestDataSkippingWithMORColstats.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
Build storage partition stats index and use it for data skipping. Main changes are as follows:
- Index is saved as another partition in the metadata table.
- Each index entry is a key-value, where key is the hash(columnName).concat(hash(partitionName)), and value is the stats.
- New configs in `HoodieMetadataConfig` and the writer changes are in `HoodieBackedTableMetadataWriter` with some util methods in `HoodieTableMetadataUtil`
- On the read path, main changes are in `HoodieFileIndex`. First, the partition pruning happens as usual, then depending on data filters, data can be skipped further if partition stats index is available.
Stats aggregated by storage partition. Efficient data skipping. Meta sync need not sync the partition metadata. Queries will use the index while planning in the …
> [HUDI-7144] Build storage partition stats index and use it for data skipping

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/DeletePartitionUtils.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/exception/HoodieDeletePartitionPendingTableServiceException.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/ttl/strategy/KeepByCreationTimeStrategy.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/ttl/strategy/KeepByTimeStrategy.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkPartitionTTLActionExecutor.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriterPartitionTTL.scala
After cherry pick https://github.com/apache/hudi/pull/9723, I find the delete partition instant can‘t be committed. 
Auto commit in HoodieSparkSqlWriter is disabled, while SparkDeletePartitionCommitActionExecutor calls commitOnAutoCommit to commit the instant.
DataSourceUtils -> createHoodieConfig
https://github.com/apache/hudi/blob/d286ae44c0fc4562a48d99ec40b4ce2a4fc198ea/hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java#L189-L190
SparkDeletePartitionCommitActionExecutor -> commitOnAutoCommit
https://github.com/apache/hudi/blob/d286ae44c0fc4562a48d99ec40b4ce2a4fc198ea/hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java#L180-L189
none
none
none
> [HUDI-7685] Fix delete partition instant commit in partition TTL

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
This PR adds the validation of the record keys of the PARTITION_STATS index records in MDT when verifying the data in the PARTITION_STATS index, to make the validation robust.
Test improvement.
none
none
> [HUDI-7706] Improve validation in PARTITION_STATS index test

- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
Stop retry inflate if encounter InterruptedIOException to avoid StackOverFlow error.
None
None
None
> [HUDI-7688] Stop retry inflate if encounter InterruptedIOException

- hudi-io/src/test/java/org/apache/hudi/io/storage/BaseTestStorageConfiguration.java
This PR adds tests on the new util methods in `StorageConfiguration` and `HoodieStorage` class to return underlying configuration instance with the specified type.
Tests on the util methods.
none
none
> [HUDI-7686] Add tests on the util methods for type cast of configuration instances

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SimpleConcurrentFileWritesConflictResolutionStrategy.java
We filter it from `SimpleConcurrentFileWritesConflictResolutionStrategy` class.
Fix a buggy process.
None.
> [HUDI-7710] Remove `compaction.inflight` from conflict resolution

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
Exclude partitions with no deleting files for clean plan.
Remove unnecessary info in  the clean plan - minor optimization to reduce cleaner memory footprint.
Low.
NA.
> [HUDI-7703] Clean plan to exclude partitions with no deleting file

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBootstrap.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
- hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
Streaming ingestion pipeline requires the support because a pending instant is almost always on the timeline.
none
none
none
> [HUDI-7701] Metadata table initailization with pending instants

- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
Fixing flaky deltastreamer tests for auto record key gen
Fixing flaky deltastreamer tests for auto record key gen
low
> [HUDI-7467] Fixing flaky deltastreamer tests for auto record key gen

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/ConcurrentOperation.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SimpleConcurrentFileWritesConflictResolutionStrategy.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestConflictResolutionStrategyUtil.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategyWithMORTable.java
During conflict resolution between an ingestion writer and a compaction operation, if the compaction is in `inflight` state, Hudi extracts a NULL compaction plan from this `inflight` file since there is no compaction plan stored there, which further causes NPE.
Therefore, during conflict resolution, we should replace `compaction.inflight` instant with `compaction.requested` instant.
Fixed a bug.
Low. …
> [HUDI-7710] Use compaction.requested during conflict resolution

- hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
Fix HoodieTableFileSystemView NPE in fetchAllStoredFileGroups
when user write data to a partition for many times with invalide partition would report and issue https://github.com/apache/hudi/issues/2001 also like this:
Job aborted due to stage failure: Task 3 in stage 35.0 failed 4 times, most recent failure: Lost task 3.3 in stage 35.0 (TID 32175) (10-222-33-34.lan executor 204): java.lang.NullPointerException
at java.util.ArrayList.<init>(ArrayList.java:178)
at org.apache.hudi.common.table.view.HoodieTableFileSystemView.fetchAllStoredFileGroups(HoodieTableFileSystemView.java:308)
at org.apache.hudi.common.table.view.AbstractTableFileSystemView.getAllFileGroupsIncludingReplaced(AbstractTableFileSystemView.java:976)
at org.apache.hudi.common.table.view.AbstractTableFileSystemView.getReplac …
> [HUDI-7720] Fix HoodieTableFileSystemView NPE in fetchAllStoredFileGroups

- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
In `UtilHelpers's buildSparkConf`, it force setting some spark configs, which cause the custom configs cannot be used like `spark.ui.port`
Do not force setting spark configs in UtilHelpers
low
None
> [MINOR] Do not force setting spark conf in UtilHelpers

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
- Fix usages of the glob paths to take in partition level paths instead of file level paths in clustering and metadata writing
- Fixes a bug where we see listing calls per file instead of per partition
low
> [MINOR] Use parent as the glob path when full file path specified

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieSimpleBucketIndex.java
Relate to the issue: https://github.com/apache/hudi/issues/7216
occur bucket id multiple, only need delete the parition next write can success，but did not delete partition currently，add a config to implement it.
low
low
> [HUDI-7522] Support find out the conflict instants in bucket partition when bucket id multiple

- hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/IncrementalTimelineSyncFileSystemView.java
As above, to remove Hadoop Path usage.
As above.
none
none
> [HUDI-7727] Avoid constructAbsolutePathInHadoopPath in hudi-common module

- hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/FileSystemBasedLockProvider.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/FileSystemBasedLockProviderTestClass.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/InProcessLockProviderWithRuntimeError.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestFileBasedLockProvider.java
- hudi-common/src/main/java/org/apache/hudi/client/transaction/lock/InProcessLockProvider.java
- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGeneratorBase.java
- hudi-common/src/test/java/org/apache/hudi/client/transaction/lock/TestInProcessLockProvider.java
- hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestWaitBasedTimeGenerator.java
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/functional/TestHiveMetastoreBasedLockProvider.java
- hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveSyncFunctionalTestHarness.java
As above, to avoid using Hadoop's `Configuration` class in the constructor.
Removes `Configuration` class usage in `LockProvider` to make `hudi-common` module Hadoop independent.
none
none
> [HUDI-7728] Use StorageConfiguration in LockProvider constructors

- hudi-aws/src/main/java/org/apache/hudi/aws/credentials/HoodieConfigAWSAssumedRoleCredentialsProvider.java
- hudi-aws/src/main/java/org/apache/hudi/config/HoodieAWSConfig.java
See issue [HUDI-7699](https://issues.apache.org/jira/browse/HUDI-7699).
[HUDI-6695](https://issues.apache.org/jira/browse/HUDI-6695) (#9260) added a AWS credentials provider to support assuming a role when syncing to Glue.
We use Hudi in a multi-tenant environment, and our customers give us delegated access to their Glue catalog.  In this multi-tenant setup it is important to use [an external ID](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html) to improve security when assuming IAM roles.
Furthermore, the STS session name is currently hard-coded to "hoodie".  It is helpful for us to have configurable session names so we have better tracability of what entities are creating STS sessions in the cloud.
Currently, the assumed role is configured with …
> [HUDI-7699] Support STS external ids and configurable session names in the AWS StsAssumeRoleCredentialsProvider

- pom.xml
Bump Spark 3.4 version from 3.4.1 to 3.4.3
None
Medium
None
> [HUDI-7737] Bump Spark 3.4 version to Spark 3.4.3

- hudi-common/src/main/java/org/apache/hudi/common/util/BaseFileUtils.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/TestParquetUtils.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/ColumnStatsIndexHelper.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataTableWithSparkDataSource.scala
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR moves the `ParquetUtils` class that uses parquet library to `hudi-hadoop-common` module.  To achieve this, a new API `BaseFileUtils#readColumnStatsFromMetadata` is abstracted.
Better abstraction and further dehadooping.
none
none
> [HUDI-7729] Move ParquetUtils to hudi-hadoop-common module

- hudi-cli/src/main/java/org/apache/hudi/cli/utils/InputStreamConsumer.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieWithTimelineServer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/TableSizeStats.java
FileStreamReader need set Charset with UTF-8 but hudi not all，the pr is aim to fix it.
none
low
> [HUDI-7738] FileStreamReader need set Charset with UTF-8

- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestManifestFileWriterSpark.java
When MDT is enabled, we can load all partitions from MDT once. As of now, in manifest writer, we are doing 1 partition at time which is unnecessary overhead when MDT is enabled. 
Bring down latency for BQ sync when MDT is enabled. 
low
> [HUDI-7654] Optimizing BQ sync for MDT

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Fixing false positive validation failure for RLI with MDT validation tool. 
When FS based record key locations are polled, we could have a pending commit. and when MDT is polled or record locations, the commit could have been completed. And so, rli validation could return additional record locations.
Robust RLI validation with MDT validator tool.
low …
> [HUDI-7673] Fixing false positive validation failure for RLI with MDT validation tool

- hudi-common/src/main/java/org/apache/hudi/common/conflict/detection/TimelineServerBasedDetectionStrategy.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
- hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/AsyncTimelineServerBasedDetectionStrategy.java
Shudown asyncDetectorExecutor in AsyncTimelineServerBasedDetectionStrategy
In order for the JVM to exit normally，when:
- `"hoodie.write.concurrency.early.conflict.detection.enable": "true"`
- `"hoodie.write.markers.type": "TIMELINE_SERVER_BASED"`
low
None
> [HUDI-7739] Shudown asyncDetectorExecutor in AsyncTimelineServerBasedDetectionStrategy

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
This block of code is problematic and can lead to OOM when we are we converting the iterator into a list and then returning the iterator back. This just holds up memory in the heap when the executor is running this block of code.
https://github.com/apache/hudi/blob/master/hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java#L86
```
records = avroRDD.mapPartitions(
(FlatMapFunction<Iterator<GenericRecord>, Either<HoodieRecord,String>>) genericRecordIterator -> {
if (autoGenerateRecordKeys) {
props.setProperty(KeyGenUtils.RECORD_KEY_GEN_PARTITION_ID_CONFIG, String.valueOf(TaskContext.getPartitionId()));
props.setProperty(KeyGenUtils.RECORD_KEY_GEN_INSTANT_TIME_CONFIG, instantTime);
}
BuiltinKeyGenerator builtinKeyGenerator = (BuiltinKeyGenerator) …
```
> [HUDI-7508] Avoid collecting records in HoodieStreamerUtils.createHoodieRecords and JsonKafkaSource mapPartitions

- hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
- hudi-common/src/test/java/org/apache/hudi/common/util/TestConfigUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/HoodieIncrSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Add a new config `HOODIE_SPARK_DATASOURCE_OPTIONS` which is used by the spark dataframe reader for HoodieIncrSource, options like using metadataTable, dataSkipping present inDataSourceOptions.scala can be passed for efficient pruning of files. 
https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala 
The files will be pruned using colstats and other mechanisms available making `HoodieIncrSource` more efficient.  
Low
HOODIE_SPARK_DATASOURCE_OPTIONS is the new config being added. 
A comma separate list of options that can be passed to the spark dataframe reader of a hudi table, eg: hoodie.metadata.enable=true,hoodie.enable.data.skipping=true.
> [HUDI-7523] Add HOODIE_SPARK_DATASOURCE_OPTIONS to be used in HoodieIncrSource

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/DummyTaskContextSupplier.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/FlinkTaskContextSupplier.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkAppendHandle.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/JavaTaskContextSupplier.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkTaskContextSupplier.java
- hudi-common/src/main/java/org/apache/hudi/common/engine/LocalTaskContextSupplier.java
- hudi-common/src/main/java/org/apache/hudi/common/engine/TaskContextSupplier.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
We added support to deduce spurious log blocks with log block reader (https://github.com/apache/hudi/pull/9545 and https://github.com/apache/hudi/pull/9611 ) in 0.14.0. 
Apparently there are some cases where it could lead to data loss or data consistency issues. 
https://github.com/apache/hudi/pull/9611#issuecomment-2016687160 
So, we are reverting the changes for now until we have a thorough patch where we can deduce such spurious log blocks. 
No data consistency issues w/ log record reader. 
medium
none
> [HUDI-7549] Reverting spurious log block deduction with LogRecordReader

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BulkInsertPartitioner.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/TestBulkInsertPartitioner.java
- hudi-client/hudi-java-client/src/main/java/org/apache/hudi/execution/bulkinsert/JavaCustomColumnsSortPartitioner.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDCustomColumnsSortPartitioner.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitioner.java
- hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
NOTE: This PR handles only AVRO code paths, there will be follow-up patch for RowWriter code paths as well. 
There are two problems with BULK_INSERT and partitioners.  
1. Passing user defined partitioner using `hoodie.bulkinsert.user.defined.partitioner.class` is not honoured in the StreamSync code path and the data is written in a non-sort mode and can lead to OOM errors because of too many open writeHandles. 
2. There is another problem with `RDDCustomColumnsSortPartitioner` where data is globally sorted but too many files are written because data is actually not pre-pending the partition keys in the sort columns. The unit test fails with this error for existing code.
```
org.opentest4j.AssertionFailedError: 
Expected :654
Actual   :3
<Click to see difference> 
// Verify each partition …
```
> [HUDI-7617] Fix issues for bulk insert user defined partitioner in StreamSync

- hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionMetrics.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudDataFetcher.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerMetrics.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
Previous PR -> https://github.com/apache/hudi/pull/10861 
Publish metrics for source parallelism for Kafka, S3/GCS sources.
No impact, only change in metrics.
Low
> [HUDI-7535] Add metrics for sourceParallelism and Refresh profile in S3/GCS

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- pom.xml
Bump Spark version 3.3.1 to 3.3.4. This includes fix for a data correctness issue as described in https://issues.apache.org/jira/browse/SPARK-44805
Spark patch version upgrade for 3.3.x.
low
> [HUDI-7749] Bump Spark version 3.3.1 to 3.3.4

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieIOHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergedReadHandle.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
Fixing RLI initialization to account for file slices instead of just base files while initializing
Initializing of RLI for MOR table will not have any data consistency issues.
low
> [HUDI-7712] Fixing RLI initialization to account for file slices instead of just base files while initializing

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/AverageRecordSizeUtils.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestAverageRecordSizeUtils.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java
Avg record size calculation only considers COMMIT actions for now. Fixing it to include replace commits and delta commits as well. 
Fixing avg record size estimation for delta commits and replace commits. 
low
> [HUDI-7429] Fixing average record size estimation for delta commits

- hudi-common/pom.xml
- hudi-common/src/test/java/org/apache/hudi/common/table/view/TestPriorityBasedFileSystemView.java
As above.
`hudi-common` is Hadoop-independent.
none
none
> [HUDI-7759] Remove Hadoop dependencies in hudi-common module

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
As above.
New feature turned off by default.
none
Config docs will be updated automatically during release.
> [HUDI-7765][branch-0.x] Turn off native HFile reader for 0.15.0 release

- pom.xml
As above, to avoid read failure on Spark 3.3.4 and 3.4.3.  HUDI-7769 as a follow-up to fix this.
Bug fix to avoid regression.
none
none
> [HUDI-7767][0.x] Revert Spark 3.3 and 3.4 upgrades

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
- hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBasicSchemaEvolution.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieOptionConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
Making OverwriteWithLatestPayload as default payload in 0.15.0
Making OverwriteWithLatestPayload as default payload in 0.15.0
low
> [HUDI-7771] Making OverwriteWithLatestPayload as default payload in 0.15.0

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
This MR fixes issue https://github.com/apache/hudi/issues/11044.
`hoodie.datasource.write.row.writer.enable` is `true` by default, and for `BULK_INSERT` operation there is a shortcut in `HoodieSparkSqlWriter.writeInternal()`, which leads to ignoring of `hoodie.combine.before.insert` parameter even it was set explicitly by user.
Added corresponding unit test, and also checked that the issue is fixed when PySpark with linked `hudi-spark-bundle` jar is used. (Made separate public repository for issues quick check if anyone would like to reuse it: https://github.com/geserdugarov/test-hudi-issues/)
The mentioned shortcut should be revisited, created separate Jira task [HUDI-7757](https://issues.apache.org/jira/browse/HUDI-7757).
None
Low
None
> [HUDI-7717] Disable row writer for bulk insert if combining before insert is set

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Added extra condition to check credential store for passwords if hive password property is set to default value "hive"
none
none
none
> [MINOR] Added condition to check default value to fix extracting password from credential store

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Added extra condition to check credential store for passwords if hive password property is set to default value "hive"
none
none
none
> [MINOR] [BRANCH-0.x] Added condition to check default value to fix extracting password from credential store

- hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySchemaResolver.java
- hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
- hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestManifestFileWriter.java
- Change the visibility of private constructor to make it possible to extend and pluing custom manifest writer classes.
- Make fetchLatestFilesForAllPartitions method in ManifestWriter to be non-static to avoid sharing multiple local variables with the inherited class.
- Change the visibility of BigQuerySchemaResolver so that it can be instantiaed outside the hudi repository.
None
low
> [HUDI-7761] Make the ManifestWriter Extendable

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/lookup/HoodieLookupFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/lookup/HoodieLookupTableReader.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/SerializableSchema.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestFileIndex.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
Supports flink lookup join
can use
`CREATE TABLE  datagen_source(
id  int,
name STRING,
proctime as PROCTIME()
) WITH (
'connector' = 'datagen',
'rows-per-second'='1',
'number-of-rows' = '2',
'fields.id.kind'='sequence',
'fields.id.start'='1',
'fields.id.end'='2'
);
select o.id,o.name,b.id as id2
from datagen_source AS o
join hudi_table/*+ OPTIONS('lookup.join.cache.ttl'= '2 day') */   FOR SYSTEM_TIME AS OF o.proctime AS b on o.id = b.id; `
This is basically the same as hive's lookup principle. Cache the hudi table data into the memory, set the ttl time, and read it with lookup
Supports flink lookup join
low
> [HUDI-6563] Supports flink lookup join

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
- hudi-common/src/main/java/org/apache/hudi/exception/InvalidHoodieFileNameException.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BucketIndexSupport.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBucketIndexSupport.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDataSkippingQuery.scala
spark support query filter use bucket field if a bucket table query with appropriate expression( = 、in、and、or)
impore table query performance when use spark
low
None
> [HUDI-6207] Spark bucket index query pruning

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
e.g.
When the actual partition structure is `dt=2021-12-09/hh=1`, but mistakenly config `dt=2021-12-09` in `hoodie.datasource.write.partitions.to.delete`, then, the partition `dt=2021-12-09` will be written to the metadata of replacecommit.
If we configure HMS partition synchronization at the same time, an error will always be reported:
Filter wrong partitions when using `hoodie.datasource.write.partitions.to.delete`
low
None
> [HUDI-7781] Filter wrong partitions when using hoodie.datasource.write.partitions.to.delete

- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
- hudi-client/hudi-spark-client/src/test/java/org/apache/spark/TestHoodieSparkKryoRegistrar.java
This PR fixes the issue that `HoodieHadoopConfiguration` is not properly (de)serialized by Kryo in Spark.  A new test is added to validate the (de)serialization.  Before the fix, the test failed with NullPointerException.
Fixes the bug.
none
none
> [HUDI-7784] Fix serde of HoodieHadoopConfiguration in Spark

- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
- hudi-client/hudi-spark-client/src/test/java/org/apache/spark/TestHoodieSparkKryoRegistrar.java
PR for master: https://github.com/apache/hudi/pull/11269
This PR targets at `branch-0.x`.
This PR fixes the issue that `HoodieHadoopConfiguration` is not properly (de)serialized by Kryo in Spark.  A new test is added to validate the (de)serialization.  Before the fix, the test failed with NullPointerException.
Fixes the bug.
none
none
> [HUDI-7784][branch-0.x] Fix serde of HoodieHadoopConfiguration in Spark

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/LSMTimeline.java
Found during backwards compatibility testing. Sometimes, Archiving would not have run for a Hudi table. In that case, LSMTimeline must gracefully handle instead of throwing File not found exception. 
Found during backwards compatibility testing. Sometimes, Archiving would not have run for a Hudi table. In that case, LSMTimeline must gracefully handle instead of throwing File not found exception. 
Backwards Compatibility
None
none
> [MINOR] LSMTimeline needs to handle case for tables which has not performed first archived yet

- packaging/hudi-integ-test-bundle/pom.xml
Fixing roaring bit map dep for integ test bundle
Fixing roaring bit map dep for integ test bundle
low
> [HUDI-7786] Fix roaring bitmap dependency in hudi-integ-test-bundle

- hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/ErrorTableUtils.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestErrorTableUtils.java
Same changes targeting master: https://github.com/apache/hudi/pull/11279
This PR targets at `branch-0.x`.
`BaseErrorTableWriter`, `HoodieStreamer`, `StreamSync`, and `StreamSyncService` are public API classes and contain public API methods which are frequently used and extended by users, which should be kept the same as before `HoodieStorage` abstraction changes.  This PR reverts a few API changes to keep them the same as 0.14.x releases.
Makes upgrade easier without breaking API changes.
none
none
> [HUDI-7785] Keep public APIs in utilities module the same as before HoodieStorage abstraction

- hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
- hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
- hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
PR targeting master: https://github.com/apache/hudi/pull/11255
This PR targeting `branch-0.x` contains the same changes as the above.
As above.
Simplifies `HoodieStorage` APIs.
none
none
> [HUDI-7775] Remove unused APIs in HoodieStorage

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/AverageRecordSizeUtils.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestAverageRecordSizeUtils.java
This PR makes the exception handling in `AverageRecordSizeUtils` more robust by catching the `Throwable` instead of `IOException`.
Robust exception handling in `AverageRecordSizeUtils`
none
none
> [HUDI-7788] Fixing exception handling in AverageRecordSizeUtils

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/SparkDataSourceContinuousIngestTool.java
- hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/helpers/DFSTestSuitePathSelector.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDataTableValidator.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDropPartitionsTool.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieRepairTool.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/TableSizeStats.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/HoodieMultiTableServicesMain.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/DFSPathSelector.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/DatePartitionPathSelector.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieMultiTableStreamer.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestDFSPathSelectorCommonMethods.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestDatePartitionPathSelector.java
This PR reverts the changes in `DFSPathSelector`, subclasses, and `UtilHelpers.readConfig` API so they still use Hadoop classes, given they are used in Spark and utilities classes, to avoid behavior change and breaking API change.
As above, makes upgrade easier.
none
none
> [HUDI-7790] Revert changes in DFSPathSelector and UtilHelpers.readConfig

- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
- hudi-common/src/main/java/org/apache/hudi/internal/schema/io/FileBasedInternalSchemaStorageManager.java
- hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/HoodieTableMetaserverClient.java
This PR adds a new API `#setStorage` to the `HoodieTableMetaClient` builder so the builder can take `HoodieStorage` instance directly to build the meta client.  The `HoodieTableMetaClient` can still be built through the storage configuration.  The instantiation of the meta client on the the read path in the `hudi-common` module has been replaced with the usage of `HoodieStorage` instance.
Simplifies Trino Hudi connector integration.
none
none
> [HUDI-7777] Allow HoodieTableMetaClient to build with HoodieStorage instance directly

- hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroHFileWriter.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroOrcWriter.java
When running tests in Trino with Hudi metadata table (MDT) enabled, the `HoodieAvroHFileWriter` throws class cast exception, since Trino uses dependency injection to provide the Hadoop file system instance, which may skip the Hudi wrapper file system logic.  This PR adds new logic to gracefully cast file system instance in Avro writers to handle such cases.
```
Caused by: java.lang.ClassCastException: class io.trino.hdfs.TrinoFileSystemCache$FileSystemWrapper cannot be cast to class org.apache.hudi.hadoop.fs.HoodieWrapperFileSystem (io.trino.hdfs.TrinoFileSystemCache$FileSystemWrapper and org.apache.hudi.hadoop.fs.HoodieWrapperFileSystem are in unnamed module of loader 'app')
at org.apache.hudi.io.hadoop.HoodieAvroHFileWriter.<init>(HoodieAvroHFileWriter.java:91)
at …
```
> [HUDI-7796] Gracefully cast file system instance in Avro writers

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestGlobalIndexEnableUpdatePartitions.java
We occasionally this duplicate keys being ingested to RLI partition in MDT. Fixing the root cause in this patch. 
Root cause:
After fetching record locations from RLI partition in MDT, before doing snapshot read to honor payload merge and ordering field, we fetch unique Partition and fileId pairs. Instead of fetching unique pair of {Partition, fileId}s, we were using [HoodieRecordGlobalLocation](https://github.com/apache/hudi/blob/e4b56b090fdcb76416c60bd7ddd4247f0955c152/hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java#L298) which also contains "instantTime" in addition to partition path and fileId. So, this was resulting in 1 record from incoming resulting in 2 to 3 or N records after joining because of this. 
I have written tests to reproduce the …
> [HUDI-7778] Fixing global index for duplicate updates

- hudi-aws/src/main/java/org/apache/hudi/config/GlueCatalogSyncClientConfig.java
- hudi-aws/src/main/java/org/apache/hudi/config/HoodieAWSConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieErrorTableConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java
- hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsM3Config.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/ParquetDFSSourceConfig.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/config/S3EventsHoodieIncrSourceConfig.java
This PR marks configs that are included in the upcoming 0.15.0 release.
Provides accurate "since" version of the configs in the docs.
none
none
> [HUDI-7798] Mark configs included in 0.15.0 release

- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
AbstractHoodieLogRecordReader#processNextRecord access modifier is wrong and should be changed from public to protected.
reason:
processNextRecord is used to process HoodieRecord inside the class. Derived classes implement this abstract member method. The access modifier should not be public. For example, the derived class HoodieMergedLogRecordScanner implements processNextRecord, which is used to merge HoodieRecord.
none
none
none
> [HUDI-7799] Optimize the access modifier of AbstractHoodieLogRecordReader#processNextRecord

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLocationFetchHandle.java
- hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkParquetReader.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestUpdateSchemaEvolution.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
- hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
- hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
- hudi-common/src/main/java/org/apache/hudi/common/util/FileFormatUtils.java
- hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieIOFactory.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroOrcReader.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReader.java
- hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieHadoopIOFactory.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/io/hadoop/TestHoodieHadoopIOFactory.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/SparkHelpers.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/ColumnStatsIndexHelper.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
This PR adds the flexibility to plug in custom `FileFormatUtils` implementation based on the `HoodieStorage` instance.  To realize this, two new APIs `#getFileFormatUtils` are added to the `HoodieIOFactory` so that the IO factory implementation class can customize the `FileFormatUtils` implementation to return.  The hardcoded logic in `FileFormatUtils#getInstance` for Hadoop-based implementation is moved to `HoodieHadoopIOFactory` class.  New tests are added in `TestHoodieHadoopIOFactory`.
Allows pluggable `FileFormatUtils` implementation
none
none
> [HUDI-7797] Use HoodieIOFactory to return pluggable FileFormatUtils implementation

- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
- hudi-common/src/main/java/org/apache/hudi/internal/schema/io/FileBasedInternalSchemaStorageManager.java
- hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
- hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/HoodieTableMetaserverClient.java
PR targeting master: #11266 #11309
This PR targets at `branch-0.x` with the same changes.
This PR adds a new API `#setStorage` to the `HoodieTableMetaClient` builder so the builder can take `HoodieStorage` instance directly to build the meta client.  The `HoodieTableMetaClient` can still be built through the storage configuration.  The instantiation of the meta client on the the read path in the `hudi-common` module has been replaced with the usage of `HoodieStorage` instance.
Note that, since `HoodieStorage` instance is intended to be not serializable, `HoodieTableMetaClient` still holds the `storageConf` instance which is serializable, which can be sent from the Spark driver to the executor.  In that way, the meta client still has the `storageConf` after deserialization on the executor …
> [HUDI-7777] Allow HoodieTableMetaClient to take HoodieStorage instance directly

- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/internal/schema/io/FileBasedInternalSchemaStorageManager.java
- hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
- hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
This PR fixes the unnecessary usage of HoodieStorage#newInstance to recreate HoodieStorage instance.
Avoids recreation overhead.
none
none
> [HUDI-7801] Directly pass down HoodieStorage instance instead of recreation

- .github/workflows/bot.yml
- .github/workflows/release_candidate_validation.yml
- packaging/bundle-validation/ci_run.sh
- packaging/bundle-validation/validate.sh
Bundle validation with Java 8 and 11 are skipped in GH CI.  This PR reenables them by fixing the `bot.yml`.
This PR includes changes to make `packaging/bundle-validation/ci_run.sh` take the docker container name to avoid name collision in the same GH CI task.
Improves bundle validation coverage.
none
none
> [HUDI-7707] Enable bundle validation on Java 8 and 11

- .github/workflows/release_candidate_validation.yml
- packaging/bundle-validation/ci_run.sh
- scripts/release/validate_staged_bundles.sh
PR targeting master: https://github.com/apache/hudi/pull/11314
This PR targets at `branch-0.x` with the same changes.
This PR makes several fixes to the bundle validation scripts:
- `.github/workflows/release_candidate_validation.yml`
- Adds Spark 3.5 and Scala 2.13 validation
- Removes ignored paths to avoid CI actions being cancelled
- `packaging/bundle-validation/ci_run.sh`
- Uses `STAGING_REPO_NUM` to determine whether to validate built bundle jars or release candidate jars
- Fixes Spark 3.5 and Scala 2.13 validation
- `scripts/release/validate_staged_bundles.sh`
- Adds new bundle jars to validate
- Makes curl requests parallelized to save time
Improves bundle validation scripts.
none
none
> [HUDI-7802] Fix bundle validation scripts

- .github/workflows/bot.yml
- .github/workflows/release_candidate_validation.yml
- packaging/bundle-validation/README.md
- release/release_guide.md
PR targeting master: https://github.com/apache/hudi/pull/11338
This PR targets at `branch-0.x` with the same changes.
As above.  Release candidate validation should only be enabled on demand by opening a PR on a release branch.
No impact on production code.
none
Updates release process doc.
> [MINOR] Disable release candidate validation by default

- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/lookup/HoodieLookupFunction.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/lookup/HoodieLookupTableReader.java
Should load all the input splits of the table.
none
none
none
> [HUDI-7795] Fix loading of input splits from look up table reader

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
_Archive operation only release lock when get.Avoid release other operations' locks incorrectly._
_low._
_None._
_None._
> [MINOR] Archive operation only release lock when get

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/ColumnStatsIndexHelper.java
- hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34LegacyHoodieParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark35LegacyHoodieParquetFileFormat.scala
With Hudi 0.14.1 release, without the Spark config `spark.kryo.registrator=org.apache.spark.HoodieSparkKryoRegistrar`, Hudi queries in the Hudi Spark quick start guide succeed.  In Hudi 0.15.0-rc2, without the Kryo registratrar, the Hudi queries start to throw NPE (see the stacktrace below), due to `HadoopStorageConfiguration` not properly broadcasted and serded.  To maintain the same user experience without requiring the Spark config `spark.kryo.registrator=org.apache.spark.HoodieSparkKryoRegistrar` by default, this PR reverts the changes of `HadoopStorageConfiguration` usage in Spark broadcasts and uses `org.apache.spark.util.SerializableConfiguration` instead for broadcasting the Hadoop configuration.
```
Driver stacktrace:
  at …
```
> [HUDI-7809] Use Spark SerializableConfiguration to avoid NPE in Kryo serde

- hudi-sync/hudi-datahub-sync/pom.xml
This PR upgrades io.acryl:datahub-client from 0.8.31 to 0.8.45 to fix security vulnerabilities.
Vulnerabilities that will be fixed with an upgrade:
INTRODUCED: 31 OCT 2022
[CVE-2022-39366](https://www.cve.org/CVERecord?id=CVE-2022-39366) 
[CWE-303](https://cwe.mitre.org/data/definitions/303.html)
|  | Issue | Score | Upgrade 
:-------------------------:|:-------------------------|:-------------------------|:-------------------------
Security vulnerability fix.
none
none
> [HUDI-7808] Upgrade io.acryl:datahub-client from 0.8.31 to 0.8.45

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala
Parse using the hudi path instead of the bootstrap base path incase the path has changed due to timestampkeygen etc.
partition parsing is correct for bootstrap and easier to maintain
none
N/A
> [HUDI-7770] Parse partition path from hudi directory for bootstrap tables

- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Due to the time travel query restrictions, disabling row writer for clustering by default. This patch is targetted against branch-0-x. We will triage the issue and relax the constraint for master post 0.15.0 release. 
Due to the time travel query restrictions, disabling row writer for clustering by default. Async clustering will not have any failures after this patch. 
low …
> [HUDI-7812] Disabling row writer for clustering

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanActionExecutor.java
This patch is for branch-0-x. Master patch https://github.com/apache/hudi/pull/11343
We can't let clean action executor skip files to be deleted. Due to networking glitches, there are chances some files may not be cleaned up. As of now, clean action execution succeeds and is tracked as part of "failedDeleteFiles". But if files to be deleted does not exists or already cleaned up, we are good. but if file deletion fails due to some other exception, we can't go past the issue. It could cause data consistency issues once the commit of interest goes into archived timeline (specifically incase of replace commits). So, this patch fixes the flow, where in clean action executor will ensure all intended files will be deleted for sure. On any exception, clean execution will fail. 
Added tests to …
> [HUDI-7655] Ensuring clean action executor cleans up all intended files

- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/CleanTask.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/ClusteringTask.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/CompactionTask.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieClusteringJob.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieCompactorJob.java
Making clean optional in standalone compaction and clustering job
Support only triggering clustering or compaction w/ standalone spark jobs.
low
> [HUDI-7407] Making clean optional in standalone compaction and clustering jobs

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCRelation.scala
The CDC releation expects `InternalRow` from the base and log files for merging, so we have to explicitly turn off `spark.sql.parquet.enableVectorizedReader`.  Otherwise, the error is thrown for the CDC query with Hudi legacy parquet file format on Spark:
```
Job aborted due to stage failure: Task 0 in stage 84.0 failed 1 times, most recent failure: Lost task 0.0 in stage 84.0 (TID 122) (fv-az692-999.kaylvc4pbm2utmerkaq2ecni0a.ex.internal.cloudapp.net executor driver): java.lang.AssertionError
at org.apache.spark.sql.execution.vectorized.OnHeapColumnVector.getLongs(OnHeapColumnVector.java:389)
at org.apache.spark.sql.vectorized.ColumnarArray.toLongArray(ColumnarArray.java:88)
at org.apache.spark.sql.vectorized.ColumnarArray.copy(ColumnarArray.java:65)
at …
```
> [HUDI-7769] Fix Hudi CDC read with legacy parquet file format on Spark

- hudi-common/src/main/java/org/apache/hudi/avro/JsonEncoder.java
- style/checkstyle.xml
- style/scalastyle.xml
`org.codehaus.jackson` is a older version of Jackson Core (`com.fasterxml.jackson.core:jackson-core`).  `org.codehaus.jackson:jackson-mapper-asl` has critical vulnerabilities ([CWE-502](https://cwe.mitre.org/data/definitions/502.html) | [CVE-2019-10202](https://www.cve.org/CVERecord?id=CVE-2019-10202) | [CVSS 9.8](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H) | [SNYK-JAVA-ORGCODEHAUSJACKSON-3326362](https://app.snyk.io/vuln/SNYK-JAVA-ORGCODEHAUSJACKSON-3326362)), which should be avoided.  This PR changes `JsonEncoder` to use Jackson Core and adds rules to check illegal imports of `org.codehaus.jackson`.
Unifies usage of JSON encoding.
none
none
> [HUDI-7817] Use Jackson Core instead of org.codehaus.jackson for JSON encoding

- hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
- hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_5Adapter.scala
In Hudi, the Spark3_5Adapter calls v2.v1Table which in turn invokes the logic within Delta. When executed on a Delta table, this may result in an error. Therefore, the logic to determine whether it is a Hudi operation has been altered to class name checks to prevent errors during Delta Lake executions.
When executing the delta test of spark3.5, the error is reported as follows:
`[DELTA_INVALID_V1_TABLE_CALL] v1Table call is not expected with path based DeltaTableV2
org.apache.spark.sql.delta.DeltaIllegalStateException: [DELTA_INVALID_V1_TABLE_CALL] v1Table call is not expected with path based DeltaTableV2
at org.apache.spark.sql.delta.DeltaErrorsBase.invalidV1TableCall(DeltaErrors.scala:1801)
at org.apache.spark.sql.delta.DeltaErrorsBase.invalidV1TableCall$(DeltaErrors.scala:1800)
at …
> [HUDI-7762]  Optimizing Hudi Table Check with Delta Lake by Refining Class Name Checks In Spark3.5

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- Updates log messages to avoid logging full commit metadata after each table service to reduce volume of logs when working with large tables
- Reduce log volume during normal operation
None
> [MINOR] Avoid logging full commit metadata at info level

- scripts/release/deploy_staging_jars.sh
This PR adds the staging jar deployment command for Spark 3.5 and Scala 2.13 profile to the release script.
Release jars for Spark 3.5 and Scala 2.13 profile.
none
none
> [HUDI-7766] Adding staging jar deployment command for Spark 3.5 and Scala 2.13 profile

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
- Avoid extra listing when initializing MDT and on first commit with small file handling
- Make listing use a queue instead of copying linked lists in MDT init
Minor reduction in overhead when initializing MDT
None
> [MINOR] Avoid listing files for empty tables

- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
Resolve the conflicts for which may be mixed hdfs and local path together
```
org.apache.flink.table.catalog.exceptions.CatalogException: Catalog hudi path /var/folders/k1/65gcjk_92ws2bjh3ftpz33fc0000gp/T/junit845658121822910144 does not exist.
at org.apache.hudi.table.catalog.HoodieCatalog.open(HoodieCatalog.java:122)
at org.apache.hudi.table.catalog.TestHoodieCatalog.beforeEach(TestHoodieCatalog.java:167)
```
It can use hdfs and local path to run test case.
The tempdir is creatd by local path. But hoodiecatalog may use hdfs path if the hadoop env exist 
none
none
> [HUDI-7822] Resolve the conflicts between mixed hdfs and local path in Flink tests

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SnapshotLoadQuerySplitter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSnapshotQuerySplitterImpl.java
Expanding the interface of the SnapshotLoadQuerySplitter to accept SourceProfileSupplier option.
Some SnapshotLoadQuerySplitter implementations may want to consider a SourceProfileSupplier in their logic, allowing source estimations to be used when splitting queries.
Low, small change to the API but no logic change within hudi itself.
Updated javadocs for the modified interface
> [HUDI-7816] Provide SourceProfileSupplier option into the SnapshotLoadQuerySplitter

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
- Updates log messages to avoid logging full commit metadata after each table service to reduce volume of logs when working with large tables
- Copy of https://github.com/apache/hudi/pull/11372
- Reduce log volume during normal operation
None
> [MINOR] Avoid logging full commit metadata at info level 

- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SnapshotLoadQuerySplitter.java
- hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
- hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSnapshotQuerySplitterImpl.java
cherry-picking changes from https://github.com/apache/hudi/pull/11368 to `branch-0.x`
Expanding the interface of the SnapshotLoadQuerySplitter to accept SourceProfileSupplier option.
Some SnapshotLoadQuerySplitter implementations may want to consider a SourceProfileSupplier in their logic, allowing source estimations to be used when splitting queries.
Low, small change to the API but no logic change within hudi itself.
Updated javadocs for the modified interface
> [HUDI-7816] Provide SourceProfileSupplier option into the SnapshotLoadQuerySplitter (branch-0.x)

- hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
- hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
Fixed task not serializable due to DynamoDBBasedLockProvider and HiveMetastoreBasedLockProvider in clean action  
with the same solution as ZookeeperBasedLockProvider (HUDI-3638, https://github.com/apache/hudi/pull/5112/files)
none
none
none
> [HUDI-7782] Task not serializable due to DynamoDBBasedLockProvider and HiveMetastoreBasedLockProvider in clean action

- doap_HUDI.rdf
This PR updates DOAP with 0.15.0 Release for record keeping in `branch-0.x` (PR targeting master https://github.com/apache/hudi/pull/11409).
Publishes release.
none
none
> [MINOR] Update DOAP with 0.15.0 Release

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Calcite is used at `TestParquetColumnProjection`. Currently Hudi uses calcite comes from Hadoop transitively while hadoop3+  has removed calcite from their project. We should switch to use scala.math.scala to avoid depending on calcite
none
none
> [MINOR] Remove calcite dependency

- hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToSixDowngradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToSevenUpgradeHandler.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
- hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairOverwriteHoodiePropsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
This PR creates placeholder table versions. Introduce new hoodie table property to track initial table version when table was created. This is needed to identify if the table was originally a 0.x or a 1.x table
Bump up table versions 
_none_
_none_
> [HUDI-7834] Create placeholder table versions and introduce new hoodie table property to track initial table version

- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
PR #11162 introduces the changes that make `HoodieSparkSqlTestBase` to swallow test failures.  This PR reverts the changes so that test failures are surfaced locally and in CI.
Makes sure test failures are surfaced in CI.
none
none
> [HUDI-7844] Fix HoodieSparkSqlTestBase to throw error upon test failure

- pom.xml
The following warning is thrown when doing maven parallel build with `mvn -T 1C ...`.  This PR bumps `apache-rat-plugin` to 0.16.1 to eliminate thread-safe warning in maven parallel build.
```
[WARNING] Enable debug to see precisely which goals are not marked as thread-safe.
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but this         *
[WARNING] * project contains the following plugin(s) that have goals not  *
[WARNING] * marked as thread-safe to support parallel execution.          *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in …
```
> [HUDI-7846] Bump apache-rat-plugin to 0.16.1 to eliminate thread-safe warning in maven parallel build

- hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala
- hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowFileSystemViewProcedure.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestFsViewProcedure.scala
Currently `show_fsview_all` support set `path_regex`, e.g.
```sql
call show_fsview_all(table => '$tableName', path_regex => 'day=d1/hh=h2')
call show_fsview_all(table => '$tableName', path_regex => 'day=d1/*/')
```
while `show_fsview_latest` only support set `partition_path`, e.g.
```sql
call show_fsview_latest(table => '$tableName', partition_path => 'day=d1/hh=h2')
```
This PR make `show_fsview_latest` support `path_regex` too, In fact, `partition_path` can be completely replaced by  `path_regex`, but for compatibility with old versions, we keep it
`show_fsview_latest` support  `path_regex`
Other fixs:
- change `partition_path` in `show_fsview_latest` from required to optional
- fix `call show_fsview_latest` when no commits in timeline
low
will update the doc of `call …
> [HUDI-7845] Call show_fsview_latest procedure support path_regex

- hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
When attempting to run HoodieStreamer without a props file, specifying all required extra configuration via --hoodie-conf parameters, the execution fails and an exception is thrown:  
`HoodieIOException: Cannot read properties from dfs from file file:/private/tmp/hudi-props-repro/src/test/resources/streamer-config/dfs-source.properties`  
When --props is not provided in command, then `propsFilePath` is set to default DEFAULT_DFS_SOURCE_PROPERTIES. So, if propsFilePath == DEFAULT_DFS_SOURCE_PROPERTIES, we should not try to read props file.
none
none
none
ticket …
> [HUDI-7390] fix: HoodieStreamer no longer works without --props being supplied

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
`HoodieBaseFileGroupRecordBuffer#compareTo` compares the numbers by casting them to the long value, which may not be safe for Float and Double.  This PR limits the allowed cases of ordering value comparison to avoid wrong results.
Makes ordering value comparison safe.
low
none
> [HUDI-7852] Constrain the comparison of different types of ordering values to limited cases

- hudi-examples/hudi-examples-flink/src/main/java/org/apache/hudi/examples/quickstart/HoodieFlinkQuickstart.java
- hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
- hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
OptionsResolver#allowCommitOnEmptyBatch has a hardcoded default value of "false", while ALLOW_EMPTY_COMMIT (hoodie.allow.empty.commit) defaults to "true", this function returns the wrong default value.
In addition, TestHoodieFlinkQuickstart was modified to avoid being affected by empty commits (hoodie.allow.empty.commit=true).
none
none
none
> [HUDI-7819] Fix OptionsResolver#allowCommitOnEmptyBatch default value bug

- pom.xml
PR targeting master: https://github.com/apache/hudi/pull/11426
This PR bumps the dependency AWS SDK v2 version to 2.25.69 on `branch-0.x`.
Dependency upgrade
none
none
> [HUDI-7854] Bump AWS SDK v2 version to 2.25.69

- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
- hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
- hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
When we do operations such as adding or removing fields from a schema, we do not copy properties over. This problem has already been addressed in some cases: https://github.com/apache/hudi/pull/10212, but wanted to ensure there are no gaps.
Prevent loss of record metadata
none
N/A
> [HUDI-7869] Ensure properties are copied when modifying schema

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
- hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Keeping backward compatibility with 0.x branch for instant completion time.
none
none
none
> [HUDI-7671] Make Hudi timeline backward compatible

- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCLIUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
[HUDI-7880] Support extraMetadata in Spark SQL Insert Into
[HUDI-7880] Support extraMetadata in Spark SQL Insert Into
none
> [HUDI-7880] Support extraMetadata in Spark SQL Insert Into

- hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
HoodieActiveTimeline#deleteCompletedRollback missing check for Action type, If called incorrectly, the meta files that are not Rollback Actions will be deleted by mistake.
none
none
none
> [HUDI-7891] Fix HoodieActiveTimeline#deleteCompletedRollback missing check for Action type

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
Added infer logic to `SevenToEightUpgradeHandler` similar to `HoodieTableMetaClient.inferRecordMergeMode()`. Record merge mode is required to dictate the merging behavior in release 1.x after merging https://github.com/apache/hudi/pull/9894. It plays the same role as the payload class config in the release 0.x.
As mentioned in [`HoodieTableVersion`](https://github.com/apache/hudi/blob/3415a4a1a2cdf415bd5fd9893196ef9e619e6728/hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java#L45):
- version 7 is Hudi 0.16, which has not been released yet,
- version 8 is Hudi 1.0 beta.
So I couldn't make end-to-end tests with upgrade from 7 to 8.
And due to added completion time in the timeline after https://github.com/apache/hudi/pull/9617, I couldn't update and read some table …
> [HUDI-7847] Infer record merge mode during table upgrade

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
- hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/SchemaEvolutionContext.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
Now hoodie.schema.cache.enable is used to decide if we want to use the schema cache. Before it was hardcoded to false in HoodieBaseFileGroupRecordBuffer and AbstractHoodieLogRecordReader.
none
none
It is needed to remove hoodie.schema.cache.enable option from documentation.
> [HUDI-7838] Remove the option hoodie.schema.cache.enable and always do the cache

- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
- hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
- hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
- hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestUtils.java
- hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileGroupReaderBasedRecordReader.java
- hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
- hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
Currently there are 4 params for the fg reader that  are for spillable map configs. They can just be stored in the TypedProperties that is already passed in to the fg reader.
Easier to use the fg reader and integrate it in other parts of hudi
low
N/A
> [HUDI-7876] use properties to store log spill map configs for fg reader

- hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
This PR disables new HFile reader by default as Spark tests encounter OOM in Github CI due to not releasing resources with the new HFile reader properly.  To unblock CI, we temporarily turn it off while working on a fix.
Unblocks CI.
none
none
> [MINOR] Disable new HFile reader by default

- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieGlobalSimpleIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieSimpleIndex.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieDeleteHelper.java
- hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java
- hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/commit/TestWriterHelperBase.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaPairRDD.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaRDD.java
- hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
- hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/data/TestHoodieJavaRDD.java
- hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestSparkWriteHelper.java
- hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java
- hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java
- hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListPairData.java
- hudi-common/src/main/java/org/apache/hudi/common/data/HoodiePairData.java
- hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
as https://github.com/apache/hudi/issues/11274 and https://github.com/apache/hudi/pull/11463 describe, there has two case question.
- if the rdd is input rdd without shuffle, the partitiion number is too bigger or too small
- user need can not control it easy
- in some case user can set `spark.default.parallelism` change it.
- in some case user can not change because hard-code
- and in spark, the better way is use `spark.default.parallelism` or `spark.sql.shuffle.partitions` can control it, other is advanced in hudi.
like dedup where use new deduce logical, user can use `spark.sql.shuffle.partitions` or `spark.default.parallelism` control the parallelism.
For special scenes, also can use advanced params.
low
None
> [HUDI-7906] improve the parallelism deduce in rdd write
